#!/usr/bin/env python3
"""Insert wave 60 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "mu_tool",
    group: "Music",
    name: "Tool",
    culture: "universal",
    description: "The progressive metal band known for complex time signatures, occult-influenced visuals, and albums that feel like spiritual journeys.",
    imageUrl: "",
    questions: [
      {
        id: "tol_200_01",
        categoryId: "mu_tool",
        tier: 200,
        prompt: "Who is the lead vocalist of Tool?",
        answer: "Maynard James Keenan",
        acceptableAnswers: ["Maynard", "MJK"],
      },
      {
        id: "tol_200_02",
        categoryId: "mu_tool",
        tier: 200,
        prompt: "What is the name of Tool's 2019 album that debuted at number one after a 13-year wait since their previous release?",
        answer: "Fear Inoculum",
        acceptableAnswers: [],
      },
      {
        id: "tol_200_03",
        categoryId: "mu_tool",
        tier: 200,
        prompt: "Tool is famous for refusing to put their music on streaming platforms for years. When their catalog finally appeared on Spotify in 2019, which album became the most streamed?",
        answer: "Lateralus",
        acceptableAnswers: [],
      },
      {
        id: "tol_400_01",
        categoryId: "mu_tool",
        tier: 400,
        prompt: "The title track of Lateralus uses a vocal pattern based on a mathematical sequence. What sequence is it?",
        answer: "The Fibonacci sequence",
        acceptableAnswers: ["Fibonacci", "Fibonacci sequence"],
        explanation: "Maynard's syllable count in the verses follows 1-1-2-3-5-8-13, matching the Fibonacci sequence — a deliberate compositional choice reflecting the album's themes of sacred geometry.",
      },
      {
        id: "tol_400_02",
        categoryId: "mu_tool",
        tier: 400,
        prompt: "Which Tool guitarist is known for his intricate, polyrhythmic playing style and also creates the band's elaborate visual art and music videos?",
        answer: "Adam Jones",
        acceptableAnswers: [],
        explanation: "Jones is a former Hollywood special effects artist who worked on Jurassic Park's practical effects before focusing full-time on Tool.",
      },
      {
        id: "tol_400_03",
        categoryId: "mu_tool",
        tier: 400,
        prompt: "Maynard James Keenan fronts two other notable bands besides Tool. Name either one.",
        answer: "A Perfect Circle or Puscifer",
        acceptableAnswers: ["A Perfect Circle", "Puscifer", "APC"],
      },
      {
        id: "tol_600_01",
        categoryId: "mu_tool",
        tier: 600,
        prompt: "Tool's drummer Danny Carey is known for incorporating polyrhythmic concepts from a specific non-Western musical tradition into his playing, particularly on Lateralus. What tradition?",
        answer: "Indian classical music (Konnakol / Carnatic rhythm)",
        acceptableAnswers: ["Indian classical", "Carnatic", "Konnakol", "Indian drumming"],
        explanation: "Carey studied Konnakol (South Indian vocal percussion) and incorporated its complex rhythmic subdivisions into tracks like 'Lateralus' and 'Rosetta Stoned.'",
      },
      {
        id: "tol_600_02",
        categoryId: "mu_tool",
        tier: 600,
        prompt: "The album 10,000 Days is widely believed to be named in reference to a personal event in Maynard's life. What is it?",
        answer: "The approximate number of days his mother Judith Marie was paralyzed before her death",
        acceptableAnswers: ["his mother's 27 years of paralysis", "how long his mother was in a wheelchair", "his mother Judith's illness duration"],
        explanation: "Judith Marie suffered a stroke that left her paralyzed for approximately 27 years (roughly 10,000 days). The songs 'Wings for Marie' and '10,000 Days' are direct tributes to her.",
      },
      {
        id: "tol_600_03",
        categoryId: "mu_tool",
        tier: 600,
        prompt: "Before joining Tool, Adam Jones worked in Hollywood special effects. On which blockbuster film's practical creature effects did he work before leaving the industry?",
        answer: "Jurassic Park",
        acceptableAnswers: ["Jurassic Park (1993)"],
        explanation: "Jones worked at Stan Winston's studio on the animatronic dinosaurs for Jurassic Park before committing full-time to Tool.",
      },
    ],
  },
  {
    id: "mu_rhcp",
    group: "Music",
    name: "Red Hot Chili Peppers",
    culture: "american",
    description: "The funk-rock pioneers from Los Angeles whose blend of punk energy, funk grooves, and emotional ballads has spanned four decades.",
    imageUrl: "",
    questions: [
      {
        id: "rhc_200_01",
        categoryId: "mu_rhcp",
        tier: 200,
        prompt: "What Red Hot Chili Peppers song features the lyrics 'Under the bridge downtown is where I drew some blood'?",
        answer: "Under the Bridge",
        acceptableAnswers: [],
      },
      {
        id: "rhc_200_02",
        categoryId: "mu_rhcp",
        tier: 200,
        prompt: "Who is the Chili Peppers' lead vocalist?",
        answer: "Anthony Kiedis",
        acceptableAnswers: ["Kiedis"],
      },
      {
        id: "rhc_200_03",
        categoryId: "mu_rhcp",
        tier: 200,
        prompt: "Which RHCP song about the state of California became one of their biggest hits, featuring the lyric 'Californication'?",
        answer: "Californication",
        acceptableAnswers: [],
      },
      {
        id: "rhc_400_01",
        categoryId: "mu_rhcp",
        tier: 400,
        prompt: "Guitarist John Frusciante has famously left and rejoined the band multiple times. How many times has he been a member of the Chili Peppers?",
        answer: "Three times",
        acceptableAnswers: ["3", "three", "3 times"],
        explanation: "Frusciante joined in 1988, left in 1992 due to addiction, returned in 1998 for their golden era, left again in 2009, and returned in 2019.",
      },
      {
        id: "rhc_400_02",
        categoryId: "mu_rhcp",
        tier: 400,
        prompt: "Flea, the band's bassist, is known for his slap bass technique. What is his real name?",
        answer: "Michael Peter Balzary",
        acceptableAnswers: ["Michael Balzary"],
        explanation: "Born in Melbourne, Australia, Balzary moved to LA as a child and got the nickname Flea from his childhood friend Anthony Kiedis.",
      },
      {
        id: "rhc_400_03",
        categoryId: "mu_rhcp",
        tier: 400,
        prompt: "Which RHCP album, produced by Rick Rubin and released in 1999, is considered their magnum opus and includes 'Scar Tissue' and 'Otherside'?",
        answer: "Californication",
        acceptableAnswers: [],
        explanation: "Californication marked John Frusciante's triumphant return to the band after his near-fatal heroin addiction. It has sold over 16 million copies worldwide.",
      },
      {
        id: "rhc_600_01",
        categoryId: "mu_rhcp",
        tier: 600,
        prompt: "During John Frusciante's years away from the band in the 1990s, his heroin addiction nearly killed him. He recorded a raw, disturbing solo album during this period that documented his deterioration. What was it called?",
        answer: "Niandra LaDes and Usually Just a T-Shirt",
        acceptableAnswers: ["Niandra Lades", "Niandra LaDes"],
        explanation: "Released in 1994, the album is a harrowing listen — lo-fi recordings made during Frusciante's deepest addiction, with some tracks recorded while he was barely functional.",
      },
      {
        id: "rhc_600_02",
        categoryId: "mu_rhcp",
        tier: 600,
        prompt: "The original guitarist of RHCP, Hillel Slovak, died of a heroin overdose in 1988. His death deeply affected the band's trajectory. What was the name of the pre-RHCP band that Kiedis, Flea, and Slovak were all members of?",
        answer: "Anthym (later What Is This?)",
        acceptableAnswers: ["Anthym", "What Is This?", "What Is This", "Chain Reaction"],
        explanation: "The intertwined history of the members — playing in each other's side projects — meant Slovak's death was not just a band loss but a deeply personal one.",
      },
      {
        id: "rhc_600_03",
        categoryId: "mu_rhcp",
        tier: 600,
        prompt: "Blood Sugar Sex Magik was recorded in a reportedly haunted mansion that had been owned by a famous magician and occultist. Who previously owned the house?",
        answer: "Harry Houdini",
        acceptableAnswers: ["Houdini"],
        explanation: "Rick Rubin had the band live and record in the Houdini mansion in Laurel Canyon. Band members reported strange occurrences during the sessions.",
      },
    ],
  },
  {
    id: "mu_pearl_jam",
    group: "Music",
    name: "Pearl Jam",
    culture: "american",
    description: "The Seattle grunge pioneers who survived the '90s and became one of rock's most enduring live acts, known for their fierce independence and Eddie Vedder's distinctive baritone.",
    imageUrl: "",
    questions: [
      {
        id: "pjm_200_01",
        categoryId: "mu_pearl_jam",
        tier: 200,
        prompt: "Who is Pearl Jam's lead singer, known for his powerful baritone and stage-diving?",
        answer: "Eddie Vedder",
        acceptableAnswers: ["Vedder"],
      },
      {
        id: "pjm_200_02",
        categoryId: "mu_pearl_jam",
        tier: 200,
        prompt: "What is the name of Pearl Jam's 1991 debut album that includes 'Alive,' 'Even Flow,' and 'Jeremy'?",
        answer: "Ten",
        acceptableAnswers: [],
      },
      {
        id: "pjm_200_03",
        categoryId: "mu_pearl_jam",
        tier: 200,
        prompt: "Pearl Jam is from which city, considered the birthplace of grunge?",
        answer: "Seattle",
        acceptableAnswers: ["Seattle, Washington"],
      },
      {
        id: "pjm_400_01",
        categoryId: "mu_pearl_jam",
        tier: 400,
        prompt: "In the mid-1990s, Pearl Jam waged a public battle against which ticketing company's monopoly on concert venues, even testifying before Congress?",
        answer: "Ticketmaster",
        acceptableAnswers: [],
        explanation: "Pearl Jam filed a complaint with the DOJ in 1994 and boycotted Ticketmaster venues for three years, though they ultimately couldn't break the monopoly.",
      },
      {
        id: "pjm_400_02",
        categoryId: "mu_pearl_jam",
        tier: 400,
        prompt: "The music video for 'Jeremy' depicts a troubled teenager's act of violence in a classroom. The video was based on a real event. What happened?",
        answer: "A 15-year-old student named Jeremy Delle shot himself in front of his English class in Richardson, Texas",
        acceptableAnswers: ["a student shot himself in class", "Jeremy Delle committed suicide in front of classmates"],
        explanation: "The 1991 video, directed by Mark Pellington, became one of MTV's most iconic and controversial videos.",
      },
      {
        id: "pjm_400_03",
        categoryId: "mu_pearl_jam",
        tier: 400,
        prompt: "Pearl Jam formed from the ashes of which Seattle band after its lead singer Andrew Wood died of a heroin overdose?",
        answer: "Mother Love Bone",
        acceptableAnswers: [],
        explanation: "Guitarist Stone Gossard and bassist Jeff Ament were in Mother Love Bone. After Wood's death, they recruited Eddie Vedder and formed Pearl Jam.",
      },
      {
        id: "pjm_600_01",
        categoryId: "mu_pearl_jam",
        tier: 600,
        prompt: "In June 2000, a crowd crush at Pearl Jam's concert at the Roskilde Festival in Denmark killed nine people. What lasting change did the band make to their performances afterward?",
        answer: "They implemented strict safety protocols and slower tempos early in sets to control crowd energy, and Eddie Vedder regularly stops shows if he sees fans in danger",
        acceptableAnswers: ["they changed their live show safety protocols", "strict crowd safety measures", "they stop shows for crowd safety"],
        explanation: "The tragedy deeply affected the band. They considered breaking up and took a long hiatus from European festivals. Vedder has since stopped multiple shows to help distressed fans.",
      },
      {
        id: "pjm_600_02",
        categoryId: "mu_pearl_jam",
        tier: 600,
        prompt: "Eddie Vedder recorded a demo tape to audition for the band. He recorded vocals over instrumentals Stone Gossard had sent him. What were those instrumental demos collectively called?",
        answer: "The Stone Gossard Demo '91 (also known as the 'Momma-Son' demos or simply the demo tape with 'Alive,' 'Once,' and 'Footsteps')",
        acceptableAnswers: ["Momma-Son", "the Gossard demos", "Stone Gossard Demo 91", "the three-song demo"],
        explanation: "Vedder received the instrumentals through former Red Hot Chili Peppers drummer Jack Irons. He wrote lyrics, recorded vocals, and mailed the tape back — landing the gig that would make him famous.",
      },
      {
        id: "pjm_600_03",
        categoryId: "mu_pearl_jam",
        tier: 600,
        prompt: "Pearl Jam's third album 'Vitalogy' (1994) was deliberately anti-commercial. It included a track that is just seven minutes of an accordion loop played by a non-musician. What is that track called?",
        answer: "Bugs",
        acceptableAnswers: [],
        explanation: "Vedder intentionally included 'Bugs' and other abrasive experiments to alienate casual fans and push back against their own mainstream popularity.",
      },
    ],
  },
  {
    id: "mu_gorillaz",
    group: "Music",
    name: "Gorillaz",
    culture: "universal",
    description: "The pioneering virtual band created by Damon Albarn and Jamie Hewlett, blending genres from hip-hop to electronica behind four animated characters.",
    imageUrl: "",
    questions: [
      {
        id: "grz_200_01",
        categoryId: "mu_gorillaz",
        tier: 200,
        prompt: "Which Gorillaz song features the lyrics 'I ain't happy, I'm feeling glad' and became one of their biggest hits?",
        answer: "Clint Eastwood",
        acceptableAnswers: [],
      },
      {
        id: "grz_200_02",
        categoryId: "mu_gorillaz",
        tier: 200,
        prompt: "What is the name of the blue-haired lead singer character in the Gorillaz animated universe?",
        answer: "2-D",
        acceptableAnswers: ["2D", "Stuart Pot", "Stu-Pot"],
      },
      {
        id: "grz_200_03",
        categoryId: "mu_gorillaz",
        tier: 200,
        prompt: "Which former Blur frontman is the real musical mastermind behind Gorillaz?",
        answer: "Damon Albarn",
        acceptableAnswers: ["Albarn"],
      },
      {
        id: "grz_400_01",
        categoryId: "mu_gorillaz",
        tier: 400,
        prompt: "The Gorillaz album 'Demon Days' features a track with a children's choir singing hauntingly over an apocalyptic beat. What is the name of this song?",
        answer: "Dirty Harry",
        acceptableAnswers: [],
        explanation: "The San Fernandez Youth Chorus performs the choral sections, giving the anti-war song an eerie, cinematic quality.",
      },
      {
        id: "grz_400_02",
        categoryId: "mu_gorillaz",
        tier: 400,
        prompt: "Who is the comic book artist and co-creator of Gorillaz responsible for all the band's visual art and character design?",
        answer: "Jamie Hewlett",
        acceptableAnswers: [],
        explanation: "Hewlett co-created the comic Tank Girl before teaming up with Albarn. The two conceived Gorillaz while watching MTV and complaining about the state of music.",
      },
      {
        id: "grz_400_03",
        categoryId: "mu_gorillaz",
        tier: 400,
        prompt: "The hit 'Feel Good Inc.' features a guest rapper whose distinctive laugh opens the track. Who is the featured artist?",
        answer: "De La Soul",
        acceptableAnswers: [],
        explanation: "De La Soul's contribution helped make 'Feel Good Inc.' the band's biggest commercial hit and earned a Grammy for Best Pop Collaboration with Vocals.",
      },
      {
        id: "grz_600_01",
        categoryId: "mu_gorillaz",
        tier: 600,
        prompt: "Gorillaz held a Guinness World Record after their debut. What was the record for?",
        answer: "Most successful virtual band",
        acceptableAnswers: ["most successful virtual band ever"],
        explanation: "Gorillaz were certified by Guinness as the world's most successful virtual band after their self-titled debut album sold over 7 million copies.",
      },
      {
        id: "grz_600_02",
        categoryId: "mu_gorillaz",
        tier: 600,
        prompt: "The fictional Gorillaz headquarters where the band supposedly lives and records is called Kong Studios. What real-world location inspired its creepy, haunted aesthetic?",
        answer: "A derelict building in North London where Albarn and Hewlett used to hang out",
        acceptableAnswers: ["an abandoned building in London", "a derelict London building"],
        explanation: "Kong Studios was depicted as a massive haunted complex. The lore includes zombies in the basement and Murdoc having won the building in a card game with Satan.",
      },
      {
        id: "grz_600_03",
        categoryId: "mu_gorillaz",
        tier: 600,
        prompt: "In the band's elaborate lore, bassist Murdoc Niccals created 2-D by crashing a car into the record shop where Stuart Pot worked, putting him in a coma and giving him his signature feature. What is 2-D's signature physical trait?",
        answer: "His eyes are entirely black (8-ball fractures from two separate car accidents caused by Murdoc)",
        acceptableAnswers: ["black eyes", "his eyes are black", "8-ball fractures", "completely black eyes"],
        explanation: "Murdoc's first crash fractured Stuart's eye, giving him one black eye. A second crash (while Murdoc was trying to impress girls with donuts in the car park) fractured the other. Both incidents knocked Stuart into comas.",
      },
    ],
  },
  {
    id: "mu_daft_punk",
    group: "Music",
    name: "Daft Punk",
    culture: "universal",
    description: "The legendary French electronic duo who redefined dance music across three decades while hiding behind robot helmets.",
    imageUrl: "",
    questions: [
      {
        id: "dfp_200_01",
        categoryId: "mu_daft_punk",
        tier: 200,
        prompt: "What massive 2013 Daft Punk hit features Pharrell Williams and Nile Rodgers and became one of the best-selling singles of all time?",
        answer: "Get Lucky",
        acceptableAnswers: [],
      },
      {
        id: "dfp_200_02",
        categoryId: "mu_daft_punk",
        tier: 200,
        prompt: "Daft Punk famously perform wearing what type of costume?",
        answer: "Robot helmets (and suits)",
        acceptableAnswers: ["robot helmets", "robot costumes", "helmets"],
      },
      {
        id: "dfp_200_03",
        categoryId: "mu_daft_punk",
        tier: 200,
        prompt: "What country are the two members of Daft Punk from?",
        answer: "France",
        acceptableAnswers: ["French"],
      },
      {
        id: "dfp_400_01",
        categoryId: "mu_daft_punk",
        tier: 400,
        prompt: "What are the real names of the two members of Daft Punk?",
        answer: "Thomas Bangalter and Guy-Manuel de Homem-Christo",
        acceptableAnswers: ["Thomas Bangalter, Guy-Manuel", "Bangalter and Guy-Manuel"],
      },
      {
        id: "dfp_400_02",
        categoryId: "mu_daft_punk",
        tier: 400,
        prompt: "Daft Punk composed the soundtrack for which 2010 Disney sci-fi sequel, blending orchestral music with their electronic style?",
        answer: "Tron: Legacy",
        acceptableAnswers: ["Tron Legacy", "TRON: Legacy"],
        explanation: "The soundtrack was a departure, featuring a full orchestra alongside synthesizers. It was their first major film score.",
      },
      {
        id: "dfp_400_03",
        categoryId: "mu_daft_punk",
        tier: 400,
        prompt: "The name 'Daft Punk' came from a negative review of their earlier band. What was that band called?",
        answer: "Darlin'",
        acceptableAnswers: ["Darlin"],
        explanation: "A British music magazine described their sound as 'daft punky thrash.' They took the insult as their new name when they pivoted to electronic music.",
      },
      {
        id: "dfp_600_01",
        categoryId: "mu_daft_punk",
        tier: 600,
        prompt: "Daft Punk's 2001 album 'Discovery' was adapted into an anime film by Leiji Matsumoto. What is the name of this musical film?",
        answer: "Interstella 5555: The 5tory of the 5ecret 5tar 5ystem",
        acceptableAnswers: ["Interstella 5555"],
        explanation: "The entire album plays as the film's soundtrack with no dialogue. Matsumoto — creator of Space Battleship Yamato — directed the alien abduction storyline.",
      },
      {
        id: "dfp_600_02",
        categoryId: "mu_daft_punk",
        tier: 600,
        prompt: "Daft Punk's legendary 1997 track 'Around the World' was directed by Michel Gondry in its music video. What is distinctive about the choreography in the video?",
        answer: "Five groups of dancers in different costumes represent different instruments/elements of the song, each dancing only when their musical part plays",
        acceptableAnswers: ["each dancer group represents a different instrument", "different costumed groups dance to different parts of the song"],
        explanation: "Gondry choreographed the video so that the movements literally visualize the music — skeletons for the bassline, mummies for the synth, athletes for the guitar riff, etc.",
      },
      {
        id: "dfp_600_03",
        categoryId: "mu_daft_punk",
        tier: 600,
        prompt: "Thomas Bangalter's father is a well-known figure in the music industry. Who is he, and what is his most famous songwriting credit?",
        answer: "Daniel Vangarde, who co-wrote 'D.I.S.C.O.' by Ottawan and produced numerous disco hits",
        acceptableAnswers: ["Daniel Vangarde", "his father is Daniel Vangarde, a disco producer"],
        explanation: "Daniel Vangarde was a prolific disco-era songwriter-producer. His influence on Thomas's musical sensibility is evident in Daft Punk's French house style.",
      },
    ],
  },
  {
    id: "vg_stardew_valley",
    group: "Video Games",
    name: "Stardew Valley",
    culture: "universal",
    description: "The beloved farming sim created entirely by one developer, where players build a new life growing crops, raising animals, and forming bonds in a charming rural town.",
    imageUrl: "",
    questions: [
      {
        id: "sdv_200_01",
        categoryId: "vg_stardew_valley",
        tier: 200,
        prompt: "In Stardew Valley, you inherit a farm from your grandfather after quitting your job at a soulless corporation. What is the name of that corporation?",
        answer: "Joja Corporation",
        acceptableAnswers: ["Joja", "JojaMart", "Joja Corp"],
      },
      {
        id: "sdv_200_02",
        categoryId: "vg_stardew_valley",
        tier: 200,
        prompt: "What is the name of the town where Stardew Valley takes place?",
        answer: "Pelican Town",
        acceptableAnswers: [],
      },
      {
        id: "sdv_200_03",
        categoryId: "vg_stardew_valley",
        tier: 200,
        prompt: "Stardew Valley was created almost entirely by a single developer. What is his name?",
        answer: "Eric Barone",
        acceptableAnswers: ["ConcernedApe"],
      },
      {
        id: "sdv_400_01",
        categoryId: "vg_stardew_valley",
        tier: 400,
        prompt: "The Community Center is a key building that can be restored by completing bundles for magical creatures. What are these forest spirits called?",
        answer: "Junimos",
        acceptableAnswers: ["Junimo"],
        explanation: "Junimos are small apple-shaped spirits that live in the Community Center. Completing their bundles restores the building and pushes back against Joja's influence.",
      },
      {
        id: "sdv_400_02",
        categoryId: "vg_stardew_valley",
        tier: 400,
        prompt: "What is the alternative to restoring the Community Center if you side with Joja Corporation instead?",
        answer: "You purchase a Joja membership and buy community upgrades from JojaMart, which converts the Community Center into a Joja Warehouse",
        acceptableAnswers: ["Joja Warehouse", "buy a Joja membership", "the Community Center becomes a Joja Warehouse"],
      },
      {
        id: "sdv_400_03",
        categoryId: "vg_stardew_valley",
        tier: 400,
        prompt: "Which NPC runs the local general store and is protective of his daughter, one of the game's marriage candidates?",
        answer: "Pierre",
        acceptableAnswers: [],
        explanation: "Pierre runs Pierre's General Store and is the father of Abigail — though the game hints that Abigail may actually be the Wizard's daughter.",
      },
      {
        id: "sdv_600_01",
        categoryId: "vg_stardew_valley",
        tier: 600,
        prompt: "Stardew Valley was originally inspired by a classic farming game series. Barone created it partly because he felt the original series had lost its way. What series inspired Stardew Valley?",
        answer: "Harvest Moon",
        acceptableAnswers: ["Harvest Moon (now Story of Seasons)"],
        explanation: "Barone was a fan of Harvest Moon: Back to Nature but felt later entries declined in quality. He spent 4.5 years solo-developing Stardew Valley as the game he wanted the series to become.",
      },
      {
        id: "sdv_600_02",
        categoryId: "vg_stardew_valley",
        tier: 600,
        prompt: "In the Skull Cavern, an endgame dungeon, what is the most efficient item players use to descend floors rapidly, a technique central to optimized runs?",
        answer: "Staircases (crafted from 99 stone each, or bought from the Desert Trader for Jade on Sundays)",
        acceptableAnswers: ["staircases", "stone staircases", "crafted staircases"],
        explanation: "Speed-farming Skull Cavern relies on stockpiling staircases to skip floors, targeting iridium ore on deep levels.",
      },
      {
        id: "sdv_600_03",
        categoryId: "vg_stardew_valley",
        tier: 600,
        prompt: "The 1.5 update added a major new area accessible by boat. What is this island called, and what ancient secret does it contain?",
        answer: "Ginger Island — it contains a hidden Volcano Dungeon, a farm, and the Qi Walnut Room with endgame challenges",
        acceptableAnswers: ["Ginger Island", "Ginger Island with Mr. Qi's challenges"],
        explanation: "Ginger Island was a massive free content update that added a tropical farm, volcano dungeon, new NPCs, and Mr. Qi's endgame challenge system.",
      },
    ],
  },
  {
    id: "vg_animal_crossing",
    group: "Video Games",
    name: "Animal Crossing",
    culture: "universal",
    description: "Nintendo's beloved life simulation series where players live in idyllic villages populated by charming animal neighbors, decorating, fishing, and collecting to their heart's content.",
    imageUrl: "",
    questions: [
      {
        id: "acr_200_01",
        categoryId: "vg_animal_crossing",
        tier: 200,
        prompt: "In Animal Crossing: New Horizons, which raccoon-like character runs the island and is both your benefactor and your landlord?",
        answer: "Tom Nook",
        acceptableAnswers: ["Nook"],
      },
      {
        id: "acr_200_02",
        categoryId: "vg_animal_crossing",
        tier: 200,
        prompt: "What is the name of the owl who runs the museum in Animal Crossing?",
        answer: "Blathers",
        acceptableAnswers: [],
      },
      {
        id: "acr_200_03",
        categoryId: "vg_animal_crossing",
        tier: 200,
        prompt: "Animal Crossing: New Horizons launched during a global event in 2020 that made it a cultural phenomenon. What was happening in the world?",
        answer: "The COVID-19 pandemic",
        acceptableAnswers: ["COVID", "the pandemic", "coronavirus lockdowns"],
      },
      {
        id: "acr_400_01",
        categoryId: "vg_animal_crossing",
        tier: 400,
        prompt: "Animal Crossing games run on a real-time clock. What unique mechanic does this create that frustrated some impatient players?",
        answer: "Events, shop restocks, and construction happen in real-world time — buildings take a full real day to build, seasonal events happen on their actual dates",
        acceptableAnswers: ["real-time clock progression", "things happen in real time", "you have to wait real days for things to happen"],
      },
      {
        id: "acr_400_02",
        categoryId: "vg_animal_crossing",
        tier: 400,
        prompt: "In New Horizons, what item's trading became an absurd player-driven economy, with turnip prices fluctuating and players visiting each other's islands to sell at the best price?",
        answer: "Turnips",
        acceptableAnswers: [],
        explanation: "The 'Stalk Market' — a pun on stock market — has players buying turnips from Daisy Mae on Sunday and selling at Nook's Cranny during the week when prices spike.",
      },
      {
        id: "acr_400_03",
        categoryId: "vg_animal_crossing",
        tier: 400,
        prompt: "What is the name of the K.K. Slider song that plays during the end credits of New Horizons and is the first song he performs on your island?",
        answer: "Welcome Horizons",
        acceptableAnswers: [],
        explanation: "K.K. Slider arrives once your island reaches three stars. His performance of 'Welcome Horizons' marks the symbolic completion of the game's main storyline.",
      },
      {
        id: "acr_600_01",
        categoryId: "vg_animal_crossing",
        tier: 600,
        prompt: "The original Animal Crossing on GameCube had a unique feature: playable NES games could be found as furniture items. Name any two of these NES games.",
        answer: "Examples: Balloon Fight, Donkey Kong, Excitebike, Clu Clu Land, Punch-Out, Wario's Woods, Golf, Pinball",
        acceptableAnswers: ["Balloon Fight", "Donkey Kong", "Excitebike", "Clu Clu Land", "any two NES games"],
        explanation: "Nintendo included full playable NES ROMs as collectible furniture items. This feature was removed in later games, likely due to Virtual Console sales.",
      },
      {
        id: "acr_600_02",
        categoryId: "vg_animal_crossing",
        tier: 600,
        prompt: "Mr. Resetti, the mole who scolds players for resetting without saving, was so frightening to young children that Nintendo received complaints. What change did they make in New Horizons?",
        answer: "He was demoted from his scolding role and works at the Rescue Service instead, since auto-save made his original job unnecessary",
        acceptableAnswers: ["he runs the rescue service", "he was given a different job", "he no longer scolds players"],
        explanation: "Resetti's rants were intentionally harsh to discourage save-scumming. In New Horizons, auto-save eliminated the need, so he was reassigned to a gentler role.",
      },
      {
        id: "acr_600_03",
        categoryId: "vg_animal_crossing",
        tier: 600,
        prompt: "Animal Crossing was originally developed for the Nintendo 64 in Japan and used a peripheral that no other region received. What was it?",
        answer: "The 64DD (Nintendo 64 Disk Drive)",
        acceptableAnswers: ["64DD", "Nintendo 64DD", "N64 Disk Drive"],
        explanation: "Dōbutsu no Mori was designed for the failed 64DD add-on, which used rewritable magnetic disks. When the 64DD flopped, it was ported to a standard N64 cartridge.",
      },
    ],
  },
  {
    id: "vg_subnautica",
    group: "Video Games",
    name: "Subnautica",
    culture: "universal",
    description: "An underwater survival game set on an alien ocean planet where players must explore increasingly terrifying depths to find a way off-world.",
    imageUrl: "",
    questions: [
      {
        id: "sub_200_01",
        categoryId: "vg_subnautica",
        tier: 200,
        prompt: "In Subnautica, what is the name of the massive spaceship that crashes on the alien planet at the start of the game?",
        answer: "The Aurora",
        acceptableAnswers: ["Aurora"],
      },
      {
        id: "sub_200_02",
        categoryId: "vg_subnautica",
        tier: 200,
        prompt: "What type of environment makes up most of the gameplay in Subnautica?",
        answer: "Underwater / ocean",
        acceptableAnswers: ["underwater", "ocean", "the sea", "an alien ocean"],
      },
      {
        id: "sub_200_03",
        categoryId: "vg_subnautica",
        tier: 200,
        prompt: "What is the name of the small escape pod that serves as your starting base in Subnautica?",
        answer: "Lifepod 5",
        acceptableAnswers: ["Lifepod 5", "the lifepod"],
      },
      {
        id: "sub_400_01",
        categoryId: "vg_subnautica",
        tier: 400,
        prompt: "The Reaper Leviathan is one of the most terrifying creatures in Subnautica. What biome is it most commonly found in, and what makes its approach so frightening?",
        answer: "The Crash Zone and Dunes — its roar can be heard before you see it, and it grabs your vehicle",
        acceptableAnswers: ["the Crash Zone", "Dunes", "it roars before attacking and grabs your sub"],
      },
      {
        id: "sub_400_02",
        categoryId: "vg_subnautica",
        tier: 400,
        prompt: "What disease affects the player and all life on the planet, and what ancient alien facility was built to contain it?",
        answer: "The Kharaa bacterium, contained by the Precursor/Architect facilities",
        acceptableAnswers: ["Kharaa", "Kharaa bacterium", "the Kharaa plague"],
        explanation: "The Kharaa bacterium is the reason the alien Architects quarantined the planet and built the gun that shot down the Aurora.",
      },
      {
        id: "sub_400_03",
        categoryId: "vg_subnautica",
        tier: 400,
        prompt: "What is the name of the deepest explorable area in Subnautica, where the primary alien facility is located?",
        answer: "The Primary Containment Facility in the Lava Lakes / Active Lava Zone",
        acceptableAnswers: ["Lava Lakes", "Active Lava Zone", "the lava zone"],
      },
      {
        id: "sub_600_01",
        categoryId: "vg_subnautica",
        tier: 600,
        prompt: "Subnautica has a notable design philosophy: it is a survival game with no conventional weapons. Why did the developers at Unknown Worlds make this deliberate choice?",
        answer: "They wanted to emphasize the vulnerability and wonder of exploration rather than combat, and felt weapons would undermine the horror of the deep ocean",
        acceptableAnswers: ["to focus on exploration over combat", "to make the ocean feel more threatening", "no weapons to emphasize vulnerability"],
        explanation: "Game director Charlie Cleveland made the decision partly as a response to a mass shooting, feeling that a survival game didn't need to be about killing.",
      },
      {
        id: "sub_600_02",
        categoryId: "vg_subnautica",
        tier: 600,
        prompt: "The Sea Emperor Leviathan plays a critical role in the endgame. What does the player need from this creature to cure the Kharaa infection?",
        answer: "Enzyme 42, produced by the Sea Emperor's hatched babies",
        acceptableAnswers: ["Enzyme 42", "an enzyme from its babies", "Enzyme 42 from the infant Sea Emperors"],
        explanation: "The Sea Emperor is not hostile — it telepathically communicates with the player throughout the game. Hatching its eggs produces the enzyme that cures the planet.",
      },
      {
        id: "sub_600_03",
        categoryId: "vg_subnautica",
        tier: 600,
        prompt: "Subnautica began as an early access title. The development team, Unknown Worlds Entertainment, previously created a popular FPS/RTS hybrid that built their reputation. What was that game?",
        answer: "Natural Selection 2",
        acceptableAnswers: ["Natural Selection", "Natural Selection 2", "NS2"],
        explanation: "Natural Selection was a Half-Life mod that became a standalone sequel. Its aliens-vs-marines asymmetric gameplay showed the team's talent for creature design.",
      },
    ],
  },
  {
    id: "vg_chrono_trigger",
    group: "Video Games",
    name: "Chrono Trigger",
    culture: "universal",
    description: "The legendary 1995 SNES RPG about time travel, widely considered one of the greatest video games ever made, developed by a dream team of Square's finest.",
    imageUrl: "",
    questions: [
      {
        id: "ctr_200_01",
        categoryId: "vg_chrono_trigger",
        tier: 200,
        prompt: "What is the name of the silent protagonist in Chrono Trigger who wields a katana?",
        answer: "Crono",
        acceptableAnswers: ["Chrono"],
      },
      {
        id: "ctr_200_02",
        categoryId: "vg_chrono_trigger",
        tier: 200,
        prompt: "What gameplay mechanic does Chrono Trigger revolve around, allowing players to visit different eras from prehistory to a post-apocalyptic future?",
        answer: "Time travel",
        acceptableAnswers: [],
      },
      {
        id: "ctr_200_03",
        categoryId: "vg_chrono_trigger",
        tier: 200,
        prompt: "Chrono Trigger was originally released on which console?",
        answer: "Super Nintendo (SNES)",
        acceptableAnswers: ["SNES", "Super NES", "Super Famicom"],
      },
      {
        id: "ctr_400_01",
        categoryId: "vg_chrono_trigger",
        tier: 400,
        prompt: "Chrono Trigger was developed by a 'Dream Team' of RPG creators. Which two legendary developers, known for Final Fantasy and Dragon Quest respectively, led the project?",
        answer: "Hironobu Sakaguchi (Final Fantasy) and Yuji Horii (Dragon Quest)",
        acceptableAnswers: ["Sakaguchi and Horii", "Hironobu Sakaguchi and Yuji Horii"],
      },
      {
        id: "ctr_400_02",
        categoryId: "vg_chrono_trigger",
        tier: 400,
        prompt: "What is the name of the parasite-like alien entity that crashes to Earth in 65,000,000 BC and becomes the game's ultimate antagonist?",
        answer: "Lavos",
        acceptableAnswers: [],
        explanation: "Lavos burrows into the planet and feeds on its energy for millions of years before erupting in 1999 AD to destroy civilization.",
      },
      {
        id: "ctr_400_03",
        categoryId: "vg_chrono_trigger",
        tier: 400,
        prompt: "Chrono Trigger was revolutionary for having multiple endings. Approximately how many different endings can players achieve?",
        answer: "Over a dozen (13 in the original, more added in later ports)",
        acceptableAnswers: ["13", "12", "over 10", "about 13"],
        explanation: "The New Game+ system lets players fight Lavos at different points in the story, each yielding a different ending based on when and how you defeat it.",
      },
      {
        id: "ctr_600_01",
        categoryId: "vg_chrono_trigger",
        tier: 600,
        prompt: "Chrono Trigger's combat system introduced a mechanic where party members could combine their abilities for powerful combo attacks. What are these combination techniques called?",
        answer: "Dual Techs and Triple Techs",
        acceptableAnswers: ["Dual Techs", "Triple Techs", "combination techs"],
        explanation: "The Tech system let characters combine abilities based on their elements — like Crono's lightning + Marle's ice = Antipode. Triple Techs used all three party members.",
      },
      {
        id: "ctr_600_02",
        categoryId: "vg_chrono_trigger",
        tier: 600,
        prompt: "The character Magus is initially presented as a villain but can later join the party. What is his true identity and original name from the Kingdom of Zeal?",
        answer: "He is Janus, the prince of the magical Kingdom of Zeal and Schala's brother",
        acceptableAnswers: ["Janus", "Prince Janus", "Schala's brother Janus"],
        explanation: "Young Janus was thrown through a time portal during the Ocean Palace disaster and ended up in the Middle Ages, where he grew up to become the feared wizard Magus.",
      },
      {
        id: "ctr_600_03",
        categoryId: "vg_chrono_trigger",
        tier: 600,
        prompt: "Akira Toriyama designed the characters for Chrono Trigger. One particular design choice he made for the character Frog was controversial with the American localization team. What was the issue?",
        answer: "Frog speaks in Elizabethan/Old English in the English localization, which was added by translator Ted Woolsey — Toriyama's original character spoke normally in Japanese",
        acceptableAnswers: ["the Old English speech was added in localization", "Frog's medieval speech wasn't in the Japanese version", "Ted Woolsey added the archaic dialogue"],
        explanation: "Woolsey's creative localization gave Frog his iconic 'thee/thou' speech pattern, which wasn't present in Japanese. Later re-translations removed it, sparking fan debate.",
      },
    ],
  },
  {
    id: "vg_castlevania",
    group: "Video Games",
    name: "Castlevania",
    culture: "universal",
    description: "Konami's gothic horror action series following the Belmont clan's centuries-long battle against Dracula, evolving from linear platformer to the genre-defining 'Metroidvania.'",
    imageUrl: "",
    questions: [
      {
        id: "cvn_200_01",
        categoryId: "vg_castlevania",
        tier: 200,
        prompt: "Which classic monster serves as the primary recurring antagonist throughout the Castlevania series?",
        answer: "Dracula",
        acceptableAnswers: ["Count Dracula"],
      },
      {
        id: "cvn_200_02",
        categoryId: "vg_castlevania",
        tier: 200,
        prompt: "What is the signature weapon of the Belmont family used across most Castlevania games?",
        answer: "A whip (the Vampire Killer)",
        acceptableAnswers: ["whip", "the whip", "Vampire Killer"],
      },
      {
        id: "cvn_200_03",
        categoryId: "vg_castlevania",
        tier: 200,
        prompt: "Which Castlevania game is considered the definitive entry that helped define the 'Metroidvania' genre alongside Super Metroid?",
        answer: "Castlevania: Symphony of the Night",
        acceptableAnswers: ["Symphony of the Night", "SotN"],
      },
      {
        id: "cvn_400_01",
        categoryId: "vg_castlevania",
        tier: 400,
        prompt: "In Symphony of the Night, who is the playable protagonist — Dracula's own son who rebels against his father?",
        answer: "Alucard",
        acceptableAnswers: [],
        explanation: "Alucard (Dracula spelled backwards) is the dhampir son of Dracula, first appearing in Castlevania III: Dracula's Curse.",
      },
      {
        id: "cvn_400_02",
        categoryId: "vg_castlevania",
        tier: 400,
        prompt: "Symphony of the Night has a famous opening line spoken by Dracula that has become a beloved meme. What does he say?",
        answer: "What is a man? A miserable little pile of secrets!",
        acceptableAnswers: ["what is a man", "a miserable little pile of secrets"],
        explanation: "The campy English voice acting in the PS1 opening became iconic. The full exchange between Richter Belmont and Dracula is beloved by fans.",
      },
      {
        id: "cvn_400_03",
        categoryId: "vg_castlevania",
        tier: 400,
        prompt: "What major secret does Symphony of the Night hide that effectively doubles the game's content, shocking players who thought they had finished?",
        answer: "An inverted castle — the entire castle flips upside down and becomes a second, harder version to explore",
        acceptableAnswers: ["the inverted castle", "an upside-down castle", "the castle flips upside down"],
        explanation: "Players who got the 'bad ending' missed the inverted castle entirely. Finding it required equipping specific items during the Richter boss fight.",
      },
      {
        id: "cvn_600_01",
        categoryId: "vg_castlevania",
        tier: 600,
        prompt: "Koji Igarashi (IGA), who directed Symphony of the Night, was not the original director. Who was the original director of SotN who established its core vision before IGA took over?",
        answer: "Toru Hagihara",
        acceptableAnswers: ["Hagihara"],
        explanation: "Hagihara directed the project initially. IGA served as assistant director and scenario writer before eventually being promoted. IGA became synonymous with the Metroidvania style.",
      },
      {
        id: "cvn_600_02",
        categoryId: "vg_castlevania",
        tier: 600,
        prompt: "The original Castlevania (1986) on the NES was developed under a different title in Japan. What was the Japanese name?",
        answer: "Akumajō Dracula (Demon Castle Dracula)",
        acceptableAnswers: ["Akumajo Dracula", "Demon Castle Dracula"],
        explanation: "The series has always been 'Akumajō Dracula' in Japan. 'Castlevania' was a Western-only title — a portmanteau of 'castle' and 'Transylvania.'",
      },
      {
        id: "cvn_600_03",
        categoryId: "vg_castlevania",
        tier: 600,
        prompt: "After leaving Konami, Koji Igarashi ran a Kickstarter to create a spiritual successor to Symphony of the Night. What was that game called, and what record did its Kickstarter set?",
        answer: "Bloodstained: Ritual of the Night — it became the most-funded video game on Kickstarter at the time with over $5.5 million",
        acceptableAnswers: ["Bloodstained", "Bloodstained: Ritual of the Night"],
        explanation: "The 2015 Kickstarter raised $5.5 million, proving massive demand for IGA's style. The game released in 2019 to positive reviews.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 60 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
