#!/usr/bin/env python3
"""Insert wave 82 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_lost_d",
    group: "TV Shows",
    name: "Lost (Deep Cut)",
    culture: "universal",
    description: "Beyond the Island basics — the deeper mythology of the Dharma Initiative and the numbers",
    imageUrl: "",
    questions: [
      { id: "lsd_200_01", categoryId: "tv_lost_d", tier: 200, prompt: "What recurring sequence of numbers appears throughout the show and was used by Hurley to win the lottery?", answer: "4, 8, 15, 16, 23, 42", acceptableAnswers: ["4 8 15 16 23 42"], explanation: "The Numbers appear everywhere — on the hatch, Hurley's lottery ticket, flight seat numbers — and correspond to Jacob's candidates." },
      { id: "lsd_200_02", categoryId: "tv_lost_d", tier: 200, prompt: "What is the Dharma Initiative, the scientific organization whose stations are found across the Island?", answer: "A 1970s scientific research project that built stations on the Island to study electromagnetism, psychology, zoology, and other fields", acceptableAnswers: ["Scientific research organization", "1970s research project on the Island", "Research organization with Island stations"], explanation: "The Dharma Initiative was funded by the Hanso Foundation and conducted experiments until being purged by the Others." },
      { id: "lsd_200_03", categoryId: "tv_lost_d", tier: 200, prompt: "What is the smoke monster, and what is its true identity revealed in the final season?", answer: "The Man in Black / Jacob's brother — a human whose body was destroyed by the Island's light source, transforming him into the smoke entity", acceptableAnswers: ["Man in Black", "Jacob's brother", "The Man in Black / Jacob's brother"], explanation: "The smoke monster is Jacob's unnamed twin brother, corrupted by the Island's electromagnetic/mystical energy source." },
      { id: "lsd_400_01", categoryId: "tv_lost_d", tier: 400, prompt: "What is the 'Incident' that occurred in 1977 at the Swan station site, and who caused it?", answer: "The Jughead hydrogen bomb was detonated by Juliet at the Swan construction site, which either caused or prevented the electromagnetic anomaly that required pressing the button every 108 minutes", acceptableAnswers: ["Jughead detonation at Swan site", "Hydrogen bomb detonation in 1977", "Juliet detonating the bomb"], explanation: "The Incident is the pivotal time-loop event where the survivors' attempt to prevent the future actually creates the very past they experienced." },
      { id: "lsd_400_02", categoryId: "tv_lost_d", tier: 400, prompt: "What is the 'frozen donkey wheel' and what does turning it do?", answer: "An ancient mechanism below the Orchid station that moves the Island through space and time and teleports the person who turns it to Tunisia", acceptableAnswers: ["Moves the Island", "Ancient wheel that moves the Island", "Teleports Island and person to Tunisia"], explanation: "The wheel was installed over a pocket of exotic matter and was first referenced when Ben used it to move the Island, then Locke stabilized it." },
      { id: "lsd_400_03", categoryId: "tv_lost_d", tier: 400, prompt: "What are the 'flash-sideways' scenes in Season 6, initially presented as an alternate timeline?", answer: "A shared afterlife / purgatory created by the characters so they could find each other and 'move on' together after death", acceptableAnswers: ["Shared afterlife", "Purgatory they created", "Afterlife to find each other"], explanation: "The flash-sideways was the most polarizing revelation — everything on the Island was real, but Season 6's parallel world was a collective afterlife." },
      { id: "lsd_600_01", categoryId: "tv_lost_d", tier: 600, prompt: "What is the Valenzetti Equation, and how does it connect the Numbers to the Dharma Initiative's true purpose?", answer: "A mathematical equation predicting the exact date of human extinction; the Numbers are its core factors, and the Dharma Initiative's ultimate goal was to change one of these factors to prevent the apocalypse", acceptableAnswers: ["Equation predicting human extinction", "Extinction prediction equation", "Math equation with Numbers as factors"], explanation: "The Valenzetti Equation was revealed in the Lost Experience ARG and provides the in-universe explanation for why the Numbers are so significant." },
      { id: "lsd_600_02", categoryId: "tv_lost_d", tier: 600, prompt: "What is the 'Cork' theory of the Island as explained by Jacob using a wine bottle metaphor?", answer: "The Island is literally a cork holding back malevolent energy (the Man in Black/evil) from flooding the world; the light at the Island's heart is the source of life, death, and rebirth", acceptableAnswers: ["Island is a cork holding back evil", "Cork preventing evil from spreading", "Island contains and blocks evil energy"], explanation: "Jacob's wine bottle metaphor — the Island as cork, evil as wine — provided the show's most direct explanation of the Island's purpose." },
      { id: "lsd_600_03", categoryId: "tv_lost_d", tier: 600, prompt: "What is the significance of the Hurley Bird, and why does it remain one of the show's most debated unresolved mysteries?", answer: "A large green bird that apparently calls Hurley's name; never explained, debated as either a Dharma experiment, the Island's consciousness, or simply a tropical bird whose call sounds like 'Hurley'", acceptableAnswers: ["Unexplained bird calling Hurley's name", "Green bird saying Hurley", "Dharma experiment or Island manifestation"], explanation: "The Hurley Bird appears briefly in Season 1 and 2 finales, calling what sounds like 'Hurley!' — it was never explained and became symbolic of the show's unanswered questions." }
    ]
  },
  {
    id: "tv_yellowjackets",
    group: "TV Shows",
    name: "Yellowjackets",
    culture: "american",
    description: "The Showtime series about a girls' soccer team that survives a plane crash — and what they did to survive",
    imageUrl: "",
    questions: [
      { id: "ylj_200_01", categoryId: "tv_yellowjackets", tier: 200, prompt: "What event strands the Yellowjackets soccer team in the wilderness for 19 months?", answer: "A plane crash in the Canadian/Ontario wilderness", acceptableAnswers: ["Plane crash", "A plane crash", "Their plane crashes"], explanation: "The team's charter plane crashes in the remote wilderness on their way to nationals, beginning a harrowing survival story." },
      { id: "ylj_200_02", categoryId: "tv_yellowjackets", tier: 200, prompt: "The show alternates between two timelines — the 1996 wilderness survival and what other period?", answer: "The present day (2021), following the adult survivors", acceptableAnswers: ["Present day", "2021", "The present day / adult timeline"], explanation: "The dual timeline structure slowly reveals what happened in the wilderness while showing how it still haunts the survivors 25 years later." },
      { id: "ylj_200_03", categoryId: "tv_yellowjackets", tier: 200, prompt: "What taboo act is strongly implied the survivors resorted to during the harsh winter?", answer: "Cannibalism", acceptableAnswers: ["Cannibalism", "Eating each other", "They ate each other"], explanation: "The show's central mystery is the extent of what the survivors did, with cannibalism being the most horrifying revelation." },
      { id: "ylj_400_01", categoryId: "tv_yellowjackets", tier: 400, prompt: "What mysterious symbol keeps appearing in the wilderness, carved into trees and eventually adopted by the group?", answer: "The Yellowjackets symbol — a figure with antlers/a geometric symbol that may represent something supernatural or just group psychosis", acceptableAnswers: ["The symbol", "Antler symbol", "Yellowjackets symbol", "The geometric symbol"], explanation: "The recurring symbol predates the crash and may indicate the wilderness has a dark history or supernatural presence — or it could be the girls' collective descent into ritualism." },
      { id: "ylj_400_02", categoryId: "tv_yellowjackets", tier: 400, prompt: "Which character becomes the 'Antler Queen,' the ritualistic leader of the wilderness group?", answer: "Lottie Matthews", acceptableAnswers: ["Lottie", "Lottie Matthews"], explanation: "Lottie's off-medication visions and apparent supernatural intuition lead her to become a messianic figure among the starving survivors." },
      { id: "ylj_400_03", categoryId: "tv_yellowjackets", tier: 400, prompt: "What is Shauna's darkest secret from the wilderness involving her best friend's boyfriend?", answer: "She was having an affair with Jeff (Jackie's boyfriend) before the crash, and her subsequent pregnancy and actions in the wilderness compound the betrayal", acceptableAnswers: ["Affair with Jackie's boyfriend Jeff", "Sleeping with Jeff", "Pregnant by Jackie's boyfriend"], explanation: "Shauna's betrayal of Jackie is one of the show's most complex moral threads, as guilt over the affair intertwines with the horrors of survival." },
      { id: "ylj_600_01", categoryId: "tv_yellowjackets", tier: 600, prompt: "What deliberate ambiguity does the show maintain about whether the wilderness events are supernatural or psychological, and what specific scenes support both interpretations?", answer: "Lottie's visions and the apparently ritualistic events could be genuine supernatural phenomena (she correctly predicts events) OR collective psychosis from starvation, isolation, and untreated mental illness", acceptableAnswers: ["Supernatural vs psychological ambiguity", "Could be real or mass psychosis", "Deliberate ambiguity about supernatural elements"], explanation: "The show's creators have intentionally maintained this ambiguity — every 'supernatural' event has a plausible psychological explanation, keeping viewers perpetually uncertain." },
      { id: "ylj_600_02", categoryId: "tv_yellowjackets", tier: 600, prompt: "What specific historical and fictional survival accounts did the showrunners cite as inspirations, beyond the obvious Donner Party comparison?", answer: "The 1972 Andes flight disaster (Alive), Lord of the Flies, the Donner Party, and real accounts of isolation-induced psychosis and group ritualism", acceptableAnswers: ["Andes crash, Lord of the Flies, Donner Party", "Alive, Lord of the Flies", "1972 Andes disaster and Lord of the Flies"], explanation: "The show synthesizes multiple survival narratives, but uniquely centers female experience in a genre typically dominated by male survival stories." },
      { id: "ylj_600_03", categoryId: "tv_yellowjackets", tier: 600, prompt: "What narrative technique does the show use with the pit girl cold open in the pilot, and how does it function as both flash-forward and misdirection?", answer: "The pilot opens with an unnamed girl being hunted and killed for a ritualistic feast; viewers assume it's the main timeline's future, but the show deliberately withholds who the girl is, using it as a structural Chekhov's gun", acceptableAnswers: ["Cold open with unnamed victim as misdirection", "Pit girl as structural mystery device", "Unknown victim opening as long-form mystery"], explanation: "The pit girl's identity becomes the show's ultimate mystery — every character relationship is viewed through the lens of 'could this be the person who falls?'" }
    ]
  },
  {
    id: "mu_radiohead_d",
    group: "Music",
    name: "Radiohead (Deep Deep Cut)",
    culture: "universal",
    description: "For those who've gone down every rabbit hole — the deepest Radiohead knowledge",
    imageUrl: "",
    questions: [
      { id: "rhd_200_01", categoryId: "mu_radiohead_d", tier: 200, prompt: "What innovative release model did Radiohead use for 'In Rainbows' in 2007?", answer: "Pay-what-you-want digital download — fans could choose to pay any amount, including nothing", acceptableAnswers: ["Pay what you want", "Name your own price", "Pay-what-you-want"], explanation: "The pay-what-you-want model was revolutionary and made global headlines, though the band later released it through traditional channels as well." },
      { id: "rhd_200_02", categoryId: "mu_radiohead_d", tier: 200, prompt: "What album followed OK Computer and featured a dramatic shift toward electronic and experimental music?", answer: "Kid A", explanation: "Kid A (2000) alienated many fans expecting another guitar-driven album but is now considered one of the greatest albums ever made." },
      { id: "rhd_200_03", categoryId: "mu_radiohead_d", tier: 200, prompt: "What is the name of Thom Yorke's solo project that has released multiple albums?", answer: "The Eraser / Atoms for Peace / solo work under his own name", acceptableAnswers: ["Atoms for Peace", "The Eraser", "His solo work"], explanation: "Yorke has released solo albums (The Eraser, Tomorrow's Modern Boxes, ANIMA) and formed the supergroup Atoms for Peace with Flea." },
      { id: "rhd_400_01", categoryId: "mu_radiohead_d", tier: 400, prompt: "What is the 'blip' theory about Radiohead's discography — the idea that albums exist in thematic pairs?", answer: "Each album pair shares thematic DNA: Pablo Honey/The Bends (guitar rock), OK Computer/Kid A (technology anxiety), Amnesiac/Hail to the Thief (paranoia), In Rainbows/The King of Limbs (rhythm-focused)", acceptableAnswers: ["Albums in thematic pairs", "Twin album theory", "Paired album concept"], explanation: "The pairing theory suggests albums are recorded in tandem and share sessions, themes, and approaches, with each pair representing a creative era." },
      { id: "rhd_400_02", categoryId: "mu_radiohead_d", tier: 400, prompt: "What is the significance of the bear logo and the 'modified bear' artwork that appears throughout Radiohead's visual identity?", answer: "Created by Stanley Donwood (Dan Rickwood) and Thom Yorke together, the bear evolved from Kid A artwork and became the band's unofficial mascot", acceptableAnswers: ["Stanley Donwood creation", "Bear from Kid A artwork", "Donwood and Yorke's collaborative art"], explanation: "Stanley Donwood has created all Radiohead artwork since The Bends, working alongside Yorke as a full creative partnership." },
      { id: "rhd_400_03", categoryId: "mu_radiohead_d", tier: 400, prompt: "What is 'Meeting People Is Easy,' and what period of the band's history does it document?", answer: "A 1998 documentary by Grant Gee following the grueling OK Computer world tour, showing the band's exhaustion and disillusionment with fame", acceptableAnswers: ["OK Computer tour documentary", "Documentary about OK Computer tour", "Grant Gee tour documentary"], explanation: "The film captures the alienation and media saturation that directly influenced the band's retreat from guitar rock into Kid A's experimentalism." },
      { id: "rhd_600_01", categoryId: "mu_radiohead_d", tier: 600, prompt: "What specific Ondes Martenot technique does Jonny Greenwood use, and what classical influence led him to adopt this rare instrument?", answer: "Greenwood plays the Ondes Martenot (an early electronic instrument) inspired by Olivier Messiaen's Turangalîla-Symphonie; he uses its ring controller for the wavering tones heard on Kid A and later albums", acceptableAnswers: ["Ondes Martenot inspired by Messiaen", "Ring controller technique from Messiaen", "Messiaen influence on Ondes Martenot use"], explanation: "Greenwood's use of the Ondes Martenot connects Radiohead to early 20th-century electronic music, and his classical training heavily influences the band's arrangements." },
      { id: "rhd_600_02", categoryId: "mu_radiohead_d", tier: 600, prompt: "What specific production technique on 'Everything in Its Right Place' involves Yorke's processed vocal becoming the song's primary harmonic instrument?", answer: "Yorke's vocals were sampled into a Prophet-5 synthesizer and played back chromatically as chord pads, making his voice the song's harmonic foundation rather than a melodic layer", acceptableAnswers: ["Voice sampled into Prophet-5", "Vocal samples as chord pads", "Voice fed into synthesizer as chords"], explanation: "This technique — feeding vocals into a synthesizer to be played as chords — created Kid A's opening sound and signaled the band's complete reinvention." },
      { id: "rhd_600_03", categoryId: "mu_radiohead_d", tier: 600, prompt: "What is the 'A Moon Shaped Pool' connection to Thom Yorke's personal life, and which specific track is understood as an elegy?", answer: "'True Love Waits' — a song Yorke had played live since 1995 but only studio-recorded after his separation from partner Rachel Owen; the album was released shortly before her death from cancer", acceptableAnswers: ["True Love Waits as elegy", "True Love Waits about Rachel Owen", "Connection to Rachel Owen's death"], explanation: "The inclusion of 'True Love Waits' as the album's devastating closer — a 21-year-old song given new heartbreaking context — made A Moon Shaped Pool Radiohead's most personal album." }
    ]
  },
  {
    id: "mu_fka_twigs",
    group: "Music",
    name: "FKA twigs",
    culture: "universal",
    description: "The avant-garde artist pushing the boundaries of pop, movement, and visual art",
    imageUrl: "",
    questions: [
      { id: "fka_200_01", categoryId: "mu_fka_twigs", tier: 200, prompt: "What does 'FKA' stand for in FKA twigs' stage name, and why was it added?", answer: "Formerly Known As — added due to a legal dispute with another artist/group called 'twigs'", acceptableAnswers: ["Formerly Known As", "FKA means Formerly Known As"], explanation: "She originally performed as 'twigs' (a childhood nickname for her cracking joints) but added FKA after a trademark dispute." },
      { id: "fka_200_02", categoryId: "mu_fka_twigs", tier: 200, prompt: "What 2019 album is considered her magnum opus, featuring tracks like 'Cellophane' and 'Sad Day'?", answer: "MAGDALENE", acceptableAnswers: ["MAGDALENE", "Magdalene"], explanation: "MAGDALENE explored heartbreak, femininity, and Mary Magdalene as a reclaimed figure, earning universal critical acclaim." },
      { id: "fka_200_03", categoryId: "mu_fka_twigs", tier: 200, prompt: "What physical art form does FKA twigs extensively train in and incorporate into her live performances and music videos?", answer: "Pole dancing / pole fitness", acceptableAnswers: ["Pole dancing", "Pole fitness", "Pole"], explanation: "Twigs trained intensively in pole dancing and wushu for MAGDALENE, incorporating athletic pole work into the 'Cellophane' video." },
      { id: "fka_400_01", categoryId: "mu_fka_twigs", tier: 400, prompt: "What visual artist directed the 'Cellophane' music video, and what specific pole choreography technique made it groundbreaking?", answer: "Andrew Thomas Huang directed it; twigs performed her own pole choreography at heights and angles that required months of training", acceptableAnswers: ["Andrew Thomas Huang", "Huang directed with real pole work"], explanation: "The 'Cellophane' video combined practical pole performance with CGI transformation sequences, creating one of the decade's most acclaimed music videos." },
      { id: "fka_400_02", categoryId: "mu_fka_twigs", tier: 400, prompt: "What is the concept behind the CAPRISONGS mixtape, and how does it differ from her album work?", answer: "A more spontaneous, collaborative mixtape celebrating freedom, joy, and sensuality after her MAGDALENE heartbreak period", acceptableAnswers: ["Joyful mixtape after heartbreak", "Celebratory collaborative mixtape", "Freedom and joy after MAGDALENE"], explanation: "CAPRISONGS featured collaborations with Pa Salieu, The Weeknd, and others, showing a more playful, dancehall-influenced side." },
      { id: "fka_400_03", categoryId: "mu_fka_twigs", tier: 400, prompt: "What connection does the MAGDALENE album have to the biblical Mary Magdalene?", answer: "Twigs reclaims Mary Magdalene as a figure of feminine strength rather than the 'fallen woman' narrative, paralleling her own experience of public scrutiny and misogyny", acceptableAnswers: ["Reclaiming Mary Magdalene", "Feminine strength reinterpretation", "Paralleling her own public scrutiny"], explanation: "The album reframes both Magdalene and twigs as women judged and reduced by patriarchal narratives, finding power in vulnerability." },
      { id: "fka_600_01", categoryId: "mu_fka_twigs", tier: 600, prompt: "What specific vocal processing technique does twigs use extensively, layering her voice into dense harmonic textures?", answer: "Extreme vocal stacking with pitch-shifted harmonies, often recording 20-30 vocal layers at different pitches to create choir-like textures from her voice alone", acceptableAnswers: ["Extreme vocal stacking", "Dense multi-layered pitch-shifted vocals", "20-30 vocal layers"], explanation: "Twigs' vocal production creates ethereal, otherworldly textures by treating her voice as a full instrument ensemble rather than a single melodic line." },
      { id: "fka_600_02", categoryId: "mu_fka_twigs", tier: 600, prompt: "What martial art did twigs train in for MAGDALENE-era performances, and how does she integrate it with other movement disciplines?", answer: "Wushu (Chinese martial arts), which she combines with pole dancing, contemporary dance, and voguing into a unique hybrid movement vocabulary", acceptableAnswers: ["Wushu", "Chinese martial arts / wushu", "Wushu combined with pole and dance"], explanation: "Twigs' interdisciplinary movement practice — martial arts, pole, vogue, contemporary — creates a performance language unlike any other pop artist." },
      { id: "fka_600_03", categoryId: "mu_fka_twigs", tier: 600, prompt: "What AI/technology art project did twigs create involving a deepfake of herself?", answer: "She created an AI deepfake chatbot of herself for social media, exploring questions of authenticity, identity, and parasocial relationships with technology", acceptableAnswers: ["AI deepfake chatbot", "Deepfake of herself", "AI chatbot exploring identity"], explanation: "The project examined how technology mediates celebrity-fan relationships and questioned what 'authenticity' means when an AI can perfectly replicate an artist's persona." }
    ]
  },
  {
    id: "vg_prey",
    group: "Video Games",
    name: "Prey (2017)",
    culture: "universal",
    description: "Arkane's immersive sim about shape-shifting aliens on a space station — the forgotten masterpiece",
    imageUrl: "",
    questions: [
      { id: "pry_200_01", categoryId: "vg_prey", tier: 200, prompt: "What is the name of the space station where the game takes place?", answer: "Talos I", acceptableAnswers: ["Talos I", "Talos 1", "Talos One"], explanation: "Talos I orbits the Moon and was originally a joint US-Soviet project before being acquired by the TranStar corporation." },
      { id: "pry_200_02", categoryId: "vg_prey", tier: 200, prompt: "What are the shapeshifting alien creatures that have overrun the station called?", answer: "Typhon", acceptableAnswers: ["Typhon", "The Typhon"], explanation: "The Typhon are a hostile alien species ranging from small mimics that disguise as objects to massive telepathic entities." },
      { id: "pry_200_03", categoryId: "vg_prey", tier: 200, prompt: "What special ability of the Mimic Typhon makes them terrifying — they can disguise themselves as what?", answer: "Everyday objects like coffee cups, chairs, boxes — any small object in the environment", acceptableAnswers: ["Everyday objects", "Any small object", "Coffee cups and chairs"], explanation: "Mimics can perfectly replicate any small object, creating constant paranoia — is that coffee cup real, or is it going to attack you?" },
      { id: "pry_400_01", categoryId: "vg_prey", tier: 400, prompt: "What twist is revealed about the protagonist Morgan Yu at the very beginning of the game?", answer: "Morgan has been living in a simulated apartment — the 'first day at work' is actually a test loop, and Morgan's memories have been wiped repeatedly using Neuromods", acceptableAnswers: ["Memory has been wiped", "Living in a simulation", "Neuromod memory wipes"], explanation: "The opening twist — that Morgan's 'normal life' is a lie — sets up the game's themes of identity, memory, and what makes us human." },
      { id: "pry_400_02", categoryId: "vg_prey", tier: 400, prompt: "What are Neuromods, and what is the horrifying side effect of removing them?", answer: "Neural modification devices that grant abilities (including Typhon powers); removing them erases all memories formed since installation", acceptableAnswers: ["Brain mods that erase memories on removal", "Neural mods with memory loss side effect", "Ability injectors that delete memories"], explanation: "Neuromods are installed via a needle through the eye and grant instant skills, but removing them destroys all memories formed after installation — the source of Morgan's amnesia." },
      { id: "pry_400_03", categoryId: "vg_prey", tier: 400, prompt: "What is the moral dilemma posed by the game's ending choices regarding Talos I?", answer: "Destroy Talos I to prevent the Typhon from reaching Earth (killing everyone aboard) or try to contain the threat and save the survivors", acceptableAnswers: ["Destroy station or save survivors", "Kill everyone or risk Typhon reaching Earth", "Blow up station vs contain threat"], explanation: "The choice between utilitarian destruction and risky preservation is complicated by the post-credits twist about Morgan's true identity." },
      { id: "pry_600_01", categoryId: "vg_prey", tier: 600, prompt: "What is the post-credits twist about who Morgan Yu actually is, and how does it recontextualize the entire game?", answer: "You are actually a Typhon organism being tested with Morgan's memories via a simulation; the operators are evaluating whether a Typhon can develop human empathy based on your choices", acceptableAnswers: ["You are a Typhon", "Player is a Typhon being tested", "Typhon with Morgan's memories"], explanation: "The revelation that you're a Typhon being evaluated for empathy turns the entire game into a test of whether alien consciousness can learn to be human." },
      { id: "pry_600_02", categoryId: "vg_prey", tier: 600, prompt: "What specific System Shock and Looking Glass Studios design philosophy does Prey follow as an 'immersive sim'?", answer: "The '0451' tradition — interconnected space, multiple solutions to every problem, environmental storytelling, and player agency over prescribed narrative paths", acceptableAnswers: ["0451 immersive sim tradition", "Multiple solutions and player agency", "Looking Glass immersive sim design"], explanation: "The code 0451 (first used in System Shock) appears in Prey as a nod to the immersive sim lineage, and every area offers multiple approaches through combat, stealth, hacking, or creative physics." },
      { id: "pry_600_03", categoryId: "vg_prey", tier: 600, prompt: "What specific GLOO Cannon interaction exemplifies the emergent gameplay that makes Prey's system design exceptional?", answer: "GLOO can be used to create climbable platforms on any surface, plug environmental hazards, immobilize enemies, AND create bridges to skip entire sections of the station — all from one tool", acceptableAnswers: ["GLOO creates platforms and solves multiple problems", "Multi-purpose tool for traversal and combat", "Climbable platforms from GLOO gun"], explanation: "The GLOO Cannon perfectly embodies immersive sim design — a single tool whose interactions with the game's systems create countless emergent solutions the designers never scripted." }
    ]
  },
  {
    id: "mv_fincher",
    group: "Movies",
    name: "David Fincher Films",
    culture: "universal",
    description: "The meticulous director of Se7en, Fight Club, and The Social Network",
    imageUrl: "",
    questions: [
      { id: "fnc_200_01", categoryId: "mv_fincher", tier: 200, prompt: "What 1999 film starring Brad Pitt and Edward Norton features the famous first rule: 'You do not talk about ___'?", answer: "Fight Club", explanation: "Fight Club was initially a box office disappointment but became a cultural phenomenon on home video." },
      { id: "fnc_200_02", categoryId: "mv_fincher", tier: 200, prompt: "What 1995 thriller follows two detectives hunting a serial killer who patterns his murders after the seven deadly sins?", answer: "Se7en (Seven)", acceptableAnswers: ["Se7en", "Seven"], explanation: "Se7en's bleak atmosphere and shocking ending established Fincher as a master of dark, psychologically complex thrillers." },
      { id: "fnc_200_03", categoryId: "mv_fincher", tier: 200, prompt: "What 2010 film dramatizes the founding of Facebook and Mark Zuckerberg's legal battles?", answer: "The Social Network", explanation: "The Social Network, written by Aaron Sorkin, won three Oscars and is considered one of the defining films of the 2010s." },
      { id: "fnc_400_01", categoryId: "mv_fincher", tier: 400, prompt: "What is Fincher's reputation for demanding excessive takes, and which film's production reportedly saw him shoot over 100 takes of certain scenes?", answer: "Zodiac — Fincher shot up to 70+ takes of some scenes; he's also notorious for 50+ takes on The Social Network and Mank", acceptableAnswers: ["Zodiac", "Zodiac and The Social Network", "Known for many takes, Zodiac"], explanation: "Fincher's obsessive perfectionism drives his actors to exhaustion but produces remarkably consistent, precise performances." },
      { id: "fnc_400_02", categoryId: "mv_fincher", tier: 400, prompt: "What 2014 film based on a Gillian Flynn novel starred Ben Affleck as a man suspected of murdering his wife?", answer: "Gone Girl", explanation: "Gone Girl's examination of media manipulation, marriage, and performance featured Rosamund Pike in a career-defining role." },
      { id: "fnc_400_03", categoryId: "mv_fincher", tier: 400, prompt: "What 2007 film follows the real investigation of the Zodiac Killer through the obsessive eyes of a newspaper cartoonist?", answer: "Zodiac", explanation: "Zodiac was Fincher's first fully digital film and is considered by many to be his masterpiece and one of the great American films." },
      { id: "fnc_600_01", categoryId: "mv_fincher", tier: 600, prompt: "What specific digital color grading process does Fincher use, often described as 'sickly' or 'desaturated,' and what colorist does he work with?", answer: "Fincher works with colorist Eric Hein (and previously Stephen Nakamura) using a signature desaturated, green/yellow-tinted grade that creates an oppressive, institutional atmosphere", acceptableAnswers: ["Desaturated green-yellow grade", "Signature sickly color grade", "Green tinted desaturation"], explanation: "Fincher's color palette — cold, desaturated, slightly green — is as recognizable as any visual signature in modern cinema." },
      { id: "fnc_600_02", categoryId: "mv_fincher", tier: 600, prompt: "What specific invisible VFX technique does Fincher use extensively, compositing actors' best performances from different takes into a single shot?", answer: "Face replacement / performance compositing — digitally combining the best facial performance from one take with the best body movement from another", acceptableAnswers: ["Face replacement", "Performance compositing", "Combining takes digitally"], explanation: "Fincher's use of invisible VFX to construct 'perfect' performances from multiple takes makes him a pioneer of digital filmmaking, though few viewers realize how extensively his films are composited." },
      { id: "fnc_600_03", categoryId: "mv_fincher", tier: 600, prompt: "What was Fincher's feature debut, and how did the disastrous production experience shape his subsequent career approach of demanding total creative control?", answer: "Alien 3 — studio interference and constant rewrites made it a miserable experience; Fincher disowned the film and vowed never to work without final cut authority again", acceptableAnswers: ["Alien 3", "Alien 3 studio interference"], explanation: "The Alien 3 nightmare taught Fincher that compromising his vision was worse than not making a film at all, leading to his famously uncompromising approach." }
    ]
  },
  {
    id: "his_printing",
    group: "History & Culture",
    name: "The Printing Revolution",
    culture: "universal",
    description: "How movable type changed civilization — from Gutenberg to the information age",
    imageUrl: "",
    questions: [
      { id: "prt_200_01", categoryId: "his_printing", tier: 200, prompt: "Who invented the movable type printing press in Europe around 1440?", answer: "Johannes Gutenberg", acceptableAnswers: ["Gutenberg", "Johannes Gutenberg"], explanation: "Gutenberg's press combined movable metal type, oil-based ink, and a wooden screw press to revolutionize information dissemination." },
      { id: "prt_200_02", categoryId: "his_printing", tier: 200, prompt: "What was the first major book printed using Gutenberg's press?", answer: "The Gutenberg Bible (42-line Bible)", acceptableAnswers: ["Gutenberg Bible", "The Bible", "42-line Bible"], explanation: "The Gutenberg Bible, printed around 1455, is considered the first major book produced with movable type in Europe." },
      { id: "prt_200_03", categoryId: "his_printing", tier: 200, prompt: "What religious movement was dramatically accelerated by the printing press in the 16th century?", answer: "The Protestant Reformation", acceptableAnswers: ["Protestant Reformation", "The Reformation", "Reformation"], explanation: "Martin Luther's 95 Theses spread across Europe in weeks thanks to printing — without the press, the Reformation might have remained a local dispute." },
      { id: "prt_400_01", categoryId: "his_printing", tier: 400, prompt: "What earlier East Asian invention of movable type predated Gutenberg by roughly 400 years?", answer: "Bi Sheng's ceramic movable type in China (around 1040 AD)", acceptableAnswers: ["Bi Sheng", "Chinese movable type", "Bi Sheng's ceramic type"], explanation: "Bi Sheng invented movable type using ceramic pieces during the Song Dynasty, though the thousands of Chinese characters made it less practical than alphabetic systems." },
      { id: "prt_400_02", categoryId: "his_printing", tier: 400, prompt: "What specific innovation made Gutenberg's type different from earlier movable type — his method of mass-producing identical letters?", answer: "The hand mold / type mold system that allowed rapid, precise casting of identical metal letters from a matrix", acceptableAnswers: ["Hand mold", "Type mold", "Metal type casting mold", "Matrix and mold system"], explanation: "Gutenberg's key innovation was the hand mold — a device that could rapidly cast identical metal letters from a master matrix, enabling mass production of type." },
      { id: "prt_400_03", categoryId: "his_printing", tier: 400, prompt: "What Venetian printer created the italic typeface and produced affordable pocket-sized books that democratized reading?", answer: "Aldus Manutius", acceptableAnswers: ["Aldus Manutius", "Aldo Manuzio"], explanation: "Manutius's Aldine Press invented italic type to fit more text per page, creating affordable octavo-format books that made classical literature accessible to the middle class." },
      { id: "prt_600_01", categoryId: "his_printing", tier: 600, prompt: "What specific alloy did Gutenberg develop for his type metal, and why were its properties essential for mass printing?", answer: "A lead-tin-antimony alloy that had a low melting point, expanded slightly when cooling to fill the mold perfectly, and was durable enough for thousands of impressions", acceptableAnswers: ["Lead-tin-antimony alloy", "Type metal alloy", "Lead tin antimony"], explanation: "The alloy's slight expansion during cooling ensured sharp, consistent letterforms — too much expansion and the type wouldn't fit together; too little and letters would be blurry." },
      { id: "prt_600_02", categoryId: "his_printing", tier: 600, prompt: "What was the 'Great Book Scare' phenomenon among European elites in the early decades of printing?", answer: "Established authorities (Church, guilds, universities) feared that cheap, uncontrolled information would undermine their gatekeeping power, leading to early censorship laws and the Index Librorum Prohibitorum", acceptableAnswers: ["Fear of uncontrolled information", "Censorship from information democratization", "Elites feared loss of information control"], explanation: "The printing press created history's first information revolution, and the response — censorship, book banning, licensing — mirrors modern debates about internet regulation." },
      { id: "prt_600_03", categoryId: "his_printing", tier: 600, prompt: "How did the printing press standardize European languages, and what specific linguistic effect did this have on English?", answer: "Printing fixed spelling, grammar, and vocabulary in ways that had been fluid in manuscript culture; for English, Caxton's printing choices froze Middle English spellings even as pronunciation continued to evolve, creating modern English's notoriously inconsistent spelling", acceptableAnswers: ["Fixed spelling while pronunciation changed", "Caxton froze spelling conventions", "Standardized language with spelling inconsistencies"], explanation: "This is why English spelling is so irregular — Caxton printed words as they were pronounced in the 1470s, but the Great Vowel Shift then changed pronunciation while the printed spellings remained frozen." }
    ]
  },
  {
    id: "sci_crispr",
    group: "Science & Nature",
    name: "CRISPR & Gene Editing",
    culture: "universal",
    description: "The revolutionary technology that lets us rewrite the code of life",
    imageUrl: "",
    questions: [
      { id: "crs_200_01", categoryId: "sci_crispr", tier: 200, prompt: "What does CRISPR stand for?", answer: "Clustered Regularly Interspaced Short Palindromic Repeats", acceptableAnswers: ["Clustered Regularly Interspaced Short Palindromic Repeats"], explanation: "CRISPR sequences were first discovered in bacteria, where they serve as a primitive immune system against viral infections." },
      { id: "crs_200_02", categoryId: "sci_crispr", tier: 200, prompt: "Which two scientists won the 2020 Nobel Prize in Chemistry for developing CRISPR-Cas9 as a gene editing tool?", answer: "Jennifer Doudna and Emmanuelle Charpentier", acceptableAnswers: ["Doudna and Charpentier", "Jennifer Doudna and Emmanuelle Charpentier"], explanation: "Their 2012 paper demonstrated that CRISPR-Cas9 could be programmed to cut DNA at specific locations, revolutionizing genetics." },
      { id: "crs_200_03", categoryId: "sci_crispr", tier: 200, prompt: "What protein acts as the 'molecular scissors' in the CRISPR system, cutting DNA at targeted locations?", answer: "Cas9", acceptableAnswers: ["Cas9", "CRISPR-associated protein 9"], explanation: "Cas9 uses a guide RNA to find the target DNA sequence, then cuts both strands, allowing genes to be deleted, modified, or inserted." },
      { id: "crs_400_01", categoryId: "sci_crispr", tier: 400, prompt: "What controversial event in 2018 involved Chinese scientist He Jiankui and CRISPR-edited human embryos?", answer: "He Jiankui created the first CRISPR-edited babies (twins Lulu and Nana), editing the CCR5 gene to supposedly confer HIV resistance", acceptableAnswers: ["Created CRISPR babies", "Edited human embryos", "He Jiankui's gene-edited babies"], explanation: "He's experiment was universally condemned by the scientific community as premature, dangerous, and unethical — he was imprisoned for three years." },
      { id: "crs_400_02", categoryId: "sci_crispr", tier: 400, prompt: "What is a 'gene drive,' and why does it raise concerns about unintended ecological consequences?", answer: "A CRISPR-based system that ensures a genetic modification is inherited by nearly 100% of offspring (instead of 50%), capable of spreading a trait through an entire wild population", acceptableAnswers: ["Forced inheritance spreading through populations", "100% inheritance of edited genes", "Gene spreading through entire species"], explanation: "Gene drives could theoretically eliminate malaria mosquitoes but could also cause irreversible ecological damage if the edited trait spreads beyond the target species." },
      { id: "crs_400_03", categoryId: "sci_crispr", tier: 400, prompt: "What is the first CRISPR-based therapy approved by regulators, and what disease does it treat?", answer: "Casgevy (exagamglogene autotemcel), approved in 2023 for sickle cell disease and transfusion-dependent beta thalassemia", acceptableAnswers: ["Casgevy for sickle cell disease", "Sickle cell disease treatment", "Casgevy"], explanation: "Casgevy works by editing patients' own blood stem cells to reactivate fetal hemoglobin production, effectively curing sickle cell disease." },
      { id: "crs_600_01", categoryId: "sci_crispr", tier: 600, prompt: "What is 'base editing' and how does it differ from traditional CRISPR-Cas9 cutting?", answer: "Base editing uses a modified Cas9 (nickase) fused to a deaminase enzyme that chemically converts one DNA base to another WITHOUT cutting both strands, reducing the risk of unintended insertions/deletions", acceptableAnswers: ["Chemical base conversion without double-strand cuts", "Modified Cas9 that changes bases without cutting", "Deaminase-based editing without breaks"], explanation: "Developed by David Liu at Harvard, base editing is more precise than traditional CRISPR because it doesn't rely on the cell's error-prone repair machinery." },
      { id: "crs_600_02", categoryId: "sci_crispr", tier: 600, prompt: "What is the 'off-target effects' problem in CRISPR, and what specific computational and experimental methods are used to minimize it?", answer: "Cas9 can cut DNA at sites similar but not identical to the target; methods include guide RNA optimization algorithms, high-fidelity Cas9 variants (eSpCas9, HiFi Cas9), and GUIDE-seq/DISCOVER-seq detection assays", acceptableAnswers: ["Unintended cuts at similar sequences", "Off-target cutting minimized by HiFi Cas9", "Guide RNA optimization and high-fidelity variants"], explanation: "Off-target effects remain CRISPR's biggest safety concern for therapeutic use, driving the development of increasingly precise Cas protein variants." },
      { id: "crs_600_03", categoryId: "sci_crispr", tier: 600, prompt: "What is 'prime editing' and why is it called the 'search and replace' of gene editing?", answer: "Prime editing uses a Cas9 nickase fused to a reverse transcriptase with a pegRNA that contains both the search sequence and the desired edit, enabling all 12 possible base-to-base conversions plus insertions and deletions without double-strand breaks", acceptableAnswers: ["Search and replace using reverse transcriptase", "Nickase plus reverse transcriptase", "All base conversions without double-strand breaks"], explanation: "Prime editing, also developed by David Liu's lab, is the most versatile gene editing tool yet — capable of any small edit without requiring donor DNA or double-strand breaks." }
    ]
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 82 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
