#!/usr/bin/env python3
"""Insert wave 62 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_invincible",
    group: "TV Shows",
    name: "Invincible",
    culture: "american",
    description: "Amazon's brutal animated superhero series based on Robert Kirkman's comic, where a teenager discovers his father — the world's most powerful hero — has a terrifying secret.",
    imageUrl: "",
    questions: [
      {
        id: "inv_200_01",
        categoryId: "tv_invincible",
        tier: 200,
        prompt: "What is the superhero name of Mark Grayson, the teenage protagonist of Invincible?",
        answer: "Invincible",
        acceptableAnswers: [],
      },
      {
        id: "inv_200_02",
        categoryId: "tv_invincible",
        tier: 200,
        prompt: "What is the name of Mark's father, the most powerful superhero on Earth who harbors a dark secret?",
        answer: "Omni-Man (Nolan Grayson)",
        acceptableAnswers: ["Omni-Man", "Nolan"],
      },
      {
        id: "inv_200_03",
        categoryId: "tv_invincible",
        tier: 200,
        prompt: "What alien race does Omni-Man belong to?",
        answer: "Viltrumite",
        acceptableAnswers: ["Viltrumites"],
      },
      {
        id: "inv_400_01",
        categoryId: "tv_invincible",
        tier: 400,
        prompt: "In the shocking Season 1 finale, Omni-Man reveals his true mission on Earth. What is it?",
        answer: "He was sent to weaken Earth's defenses so the Viltrumite Empire could conquer it",
        acceptableAnswers: ["to conquer Earth for the Viltrumites", "prepare Earth for Viltrumite conquest"],
      },
      {
        id: "inv_400_02",
        categoryId: "tv_invincible",
        tier: 400,
        prompt: "What is the name of the superhero team — Earth's equivalent of the Justice League — that Omni-Man brutally murders in the first episode?",
        answer: "The Guardians of the Globe",
        acceptableAnswers: ["Guardians of the Globe"],
        explanation: "The massacre of the Guardians in the final minutes of Episode 1 is one of the most shocking reveals in animated TV history.",
      },
      {
        id: "inv_400_03",
        categoryId: "tv_invincible",
        tier: 400,
        prompt: "Who voices Omni-Man in the animated series?",
        answer: "J.K. Simmons",
        acceptableAnswers: [],
        explanation: "Simmons's performance — switching between warm fatherly tones and cold Viltrumite brutality — is widely praised as career-defining voice work.",
      },
      {
        id: "inv_600_01",
        categoryId: "tv_invincible",
        tier: 600,
        prompt: "Robert Kirkman, who created the Invincible comic, is also the creator of which other massively successful comic series that became a TV phenomenon?",
        answer: "The Walking Dead",
        acceptableAnswers: [],
        explanation: "Kirkman created both series for Image Comics. Invincible ran for 144 issues (2003-2018) while The Walking Dead ran for 193 issues.",
      },
      {
        id: "inv_600_02",
        categoryId: "tv_invincible",
        tier: 600,
        prompt: "In the comics, the Viltrumites' incredible power comes with a dark aspect to their civilization's history. What did they do to achieve their species' strength?",
        answer: "They culled their own population — killing the weakest half of their species to ensure only the strongest survived and bred",
        acceptableAnswers: ["they killed the weak half of their species", "they purged their own weak", "selective culling of their population"],
        explanation: "This eugenics-driven history explains both Viltrumite strength and their small numbers, which becomes a critical plot point in the larger conflict.",
      },
      {
        id: "inv_600_03",
        categoryId: "tv_invincible",
        tier: 600,
        prompt: "During the infamous train scene in the Season 1 finale, Omni-Man uses a specific, devastating method to try to break Mark's will. What does he do?",
        answer: "He grabs Mark and flies him through a crowded subway train at high speed, using the bodies of civilians as projectiles against his own son",
        acceptableAnswers: ["flies him through a train, killing civilians", "uses Mark as a weapon through a subway train"],
        explanation: "The scene is one of the most disturbing in superhero media — Omni-Man weaponizes human lives to show Mark how meaningless they are, but Mark's refusal to give up is what ultimately breaks Nolan.",
      },
    ],
  },
  {
    id: "tv_what_we_do_shadows",
    group: "TV Shows",
    name: "What We Do in the Shadows",
    culture: "american",
    description: "The FX mockumentary comedy following a group of centuries-old vampire roommates navigating modern-day Staten Island.",
    imageUrl: "",
    questions: [
      {
        id: "wwd_200_01",
        categoryId: "tv_what_we_do_shadows",
        tier: 200,
        prompt: "What format does 'What We Do in the Shadows' use to tell its story — following the vampires around with cameras as if making a documentary?",
        answer: "Mockumentary",
        acceptableAnswers: ["mock documentary", "documentary style"],
      },
      {
        id: "wwd_200_02",
        categoryId: "tv_what_we_do_shadows",
        tier: 200,
        prompt: "What borough of New York City do the vampire roommates live in?",
        answer: "Staten Island",
        acceptableAnswers: [],
      },
      {
        id: "wwd_200_03",
        categoryId: "tv_what_we_do_shadows",
        tier: 200,
        prompt: "What is the name of the human who serves the vampires as their familiar, hoping to eventually be turned?",
        answer: "Guillermo de la Cruz",
        acceptableAnswers: ["Guillermo", "Gizmo"],
      },
      {
        id: "wwd_400_01",
        categoryId: "tv_what_we_do_shadows",
        tier: 400,
        prompt: "Nandor the Relentless was once a fearsome warrior from which historical region, where he conquered vast territories before becoming a vampire?",
        answer: "The Ottoman Empire / Al Quolanudar (a fictional country near modern-day Iran)",
        acceptableAnswers: ["Al Quolanudar", "the Ottoman Empire", "somewhere near Iran"],
        explanation: "Nandor frequently references his conquering past, though his modern inability to use email or understand technology undercuts his former glory.",
      },
      {
        id: "wwd_400_02",
        categoryId: "tv_what_we_do_shadows",
        tier: 400,
        prompt: "Guillermo harbors a secret that makes his role as a vampire's familiar deeply ironic. What is it?",
        answer: "He is a descendant of Abraham Van Helsing, the legendary vampire hunter, and has natural vampire-slaying abilities",
        acceptableAnswers: ["he's related to Van Helsing", "descendant of Van Helsing", "he has vampire slayer blood"],
      },
      {
        id: "wwd_400_03",
        categoryId: "tv_what_we_do_shadows",
        tier: 400,
        prompt: "What type of vampire is Colin Robinson, and how does he feed?",
        answer: "An energy vampire — he feeds by boring people, annoying them, or draining their emotional energy through tedious conversation",
        acceptableAnswers: ["energy vampire", "he's an energy vampire who bores people"],
        explanation: "Colin Robinson is a parody of that one coworker who drains your will to live. Mark Proksch's deadpan performance is a fan favorite.",
      },
      {
        id: "wwd_600_01",
        categoryId: "tv_what_we_do_shadows",
        tier: 600,
        prompt: "The TV series is based on a 2014 film of the same name. Who co-wrote and co-directed the original film, and in which country is it set?",
        answer: "Taika Waititi and Jemaine Clement — the film is set in Wellington, New Zealand",
        acceptableAnswers: ["Taika Waititi and Jemaine Clement, New Zealand"],
        explanation: "Waititi and Clement also play vampires in the original film. Waititi later directed Thor: Ragnarok and Jojo Rabbit.",
      },
      {
        id: "wwd_600_02",
        categoryId: "tv_what_we_do_shadows",
        tier: 600,
        prompt: "In Season 3, Colin Robinson dies and is reborn in an unusual way. How does he come back?",
        answer: "He shrivels up and dies, then a baby Colin Robinson is born from his desiccated body — growing rapidly into a child version of himself",
        acceptableAnswers: ["reborn as a baby from his corpse", "a baby version emerges from his body"],
        explanation: "The show revealed that energy vampires have a unique life cycle — they die and are reborn, explaining why Colin Robinson has 'always' been around.",
      },
      {
        id: "wwd_600_03",
        categoryId: "tv_what_we_do_shadows",
        tier: 600,
        prompt: "The show features a Vampiric Council scene with celebrity vampire cameos. Which real-life actors reprised vampire roles from other movies in the council chamber?",
        answer: "Tilda Swinton (Only Lovers Left Alive), Evan Rachel Wood (True Blood), Wesley Snipes (Blade), Danny Trejo (From Dusk Till Dawn), and others",
        acceptableAnswers: ["Tilda Swinton and Wesley Snipes among others", "Wesley Snipes as Blade", "various actors from vampire movies"],
        explanation: "The Vampiric Council sequence is a love letter to vampire cinema, with actors appearing in character from their respective vampire films.",
      },
    ],
  },
  {
    id: "mv_denis_villeneuve",
    group: "Movies",
    name: "Denis Villeneuve",
    culture: "universal",
    description: "The visionary Québécois director behind some of the 21st century's most ambitious sci-fi films, from Arrival and Blade Runner 2049 to the Dune saga.",
    imageUrl: "",
    questions: [
      {
        id: "dnv_200_01",
        categoryId: "mv_denis_villeneuve",
        tier: 200,
        prompt: "What epic sci-fi franchise did Denis Villeneuve adapt into two blockbuster films in 2021 and 2024?",
        answer: "Dune",
        acceptableAnswers: ["Dune (Frank Herbert)"],
      },
      {
        id: "dnv_200_02",
        categoryId: "mv_denis_villeneuve",
        tier: 200,
        prompt: "In Villeneuve's 2016 film Arrival, what do the alien visitors use to communicate with humans?",
        answer: "Circular ink-like symbols (logograms)",
        acceptableAnswers: ["circular symbols", "logograms", "ink circles", "circular language"],
      },
      {
        id: "dnv_200_03",
        categoryId: "mv_denis_villeneuve",
        tier: 200,
        prompt: "What is Denis Villeneuve's nationality?",
        answer: "Canadian (Québécois)",
        acceptableAnswers: ["Canadian", "French-Canadian", "Quebecois"],
      },
      {
        id: "dnv_400_01",
        categoryId: "mv_denis_villeneuve",
        tier: 400,
        prompt: "Arrival is based on a novella by Ted Chiang. What is the name of the novella, and what linguistic theory does it explore?",
        answer: "'Story of Your Life' — it explores the Sapir-Whorf hypothesis (linguistic relativity), the idea that the language you speak shapes how you perceive reality",
        acceptableAnswers: ["Story of Your Life, Sapir-Whorf hypothesis", "Story of Your Life, linguistic relativity"],
      },
      {
        id: "dnv_400_02",
        categoryId: "mv_denis_villeneuve",
        tier: 400,
        prompt: "Villeneuve's thriller 'Sicario' follows a FBI agent drawn into the brutal world of the U.S.-Mexico drug war. Who composed the film's intensely menacing score?",
        answer: "Jóhann Jóhannsson",
        acceptableAnswers: ["Johann Johannsson"],
        explanation: "Jóhannsson's pulsing, anxiety-inducing score — particularly the Juárez border crossing sequence — became iconic. He also scored Arrival before his untimely death in 2018.",
      },
      {
        id: "dnv_400_03",
        categoryId: "mv_denis_villeneuve",
        tier: 400,
        prompt: "In Dune, Villeneuve cast Timothée Chalamet as Paul Atreides. Who plays Paul's mother Lady Jessica, a member of the Bene Gesserit?",
        answer: "Rebecca Ferguson",
        acceptableAnswers: [],
      },
      {
        id: "dnv_600_01",
        categoryId: "mv_denis_villeneuve",
        tier: 600,
        prompt: "Before his Hollywood career, Villeneuve made a critically acclaimed Québécois film about the 1989 École Polytechnique massacre. What was it called?",
        answer: "Polytechnique",
        acceptableAnswers: [],
        explanation: "The 2009 film was shot in black and white and follows the mass shooting from multiple perspectives. It's considered one of the finest Canadian films ever made.",
      },
      {
        id: "dnv_600_02",
        categoryId: "mv_denis_villeneuve",
        tier: 600,
        prompt: "Villeneuve's 'Enemy' (2013) is an enigmatic psychological thriller starring Jake Gyllenhaal. The film ends with a giant spider in an apartment. What is the widely accepted interpretation of the spider metaphor?",
        answer: "The spider represents the protagonist's fear of commitment and women/relationships — it's a manifestation of his anxiety about repeating destructive patterns",
        acceptableAnswers: ["fear of commitment", "fear of women or relationships", "anxiety about his marriage"],
        explanation: "Enemy is based on José Saramago's novel 'The Double.' The spider imagery appears throughout and is widely interpreted as a symbol of the controlling feminine or entrapment in cycles.",
      },
      {
        id: "dnv_600_03",
        categoryId: "mv_denis_villeneuve",
        tier: 600,
        prompt: "For Dune, Villeneuve insisted on a specific creative approach to the sandworm sounds that broke with typical sci-fi creature design. What was it?",
        answer: "The sandworm sounds were created entirely from organic recordings — shifting sand, dragging objects through desert, and modulated animal sounds — with no synthetic elements",
        acceptableAnswers: ["all organic/natural sounds, no synthesizers", "real desert and animal sounds only"],
        explanation: "Sound designers Mark Mangini and Theo Green recorded extensively in real deserts. Villeneuve wanted everything to feel grounded and physical rather than sci-fi synthetic.",
      },
    ],
  },
  {
    id: "mv_tim_burton",
    group: "Movies",
    name: "Tim Burton",
    culture: "american",
    description: "The gothic visionary director known for his darkly whimsical aesthetic, from Edward Scissorhands and Beetlejuice to The Nightmare Before Christmas.",
    imageUrl: "",
    questions: [
      {
        id: "tmb_200_01",
        categoryId: "mv_tim_burton",
        tier: 200,
        prompt: "What Tim Burton film features a pale, gentle outcast with scissors for hands who falls in love with a suburban girl?",
        answer: "Edward Scissorhands",
        acceptableAnswers: [],
      },
      {
        id: "tmb_200_02",
        categoryId: "mv_tim_burton",
        tier: 200,
        prompt: "Which actor has starred in more Tim Burton films than anyone else, appearing in movies like Edward Scissorhands, Sweeney Todd, and Charlie and the Chocolate Factory?",
        answer: "Johnny Depp",
        acceptableAnswers: [],
      },
      {
        id: "tmb_200_03",
        categoryId: "mv_tim_burton",
        tier: 200,
        prompt: "What classic 1993 stop-motion film tells the story of Jack Skellington, the Pumpkin King of Halloween Town, who discovers Christmas Town?",
        answer: "The Nightmare Before Christmas",
        acceptableAnswers: [],
      },
      {
        id: "tmb_400_01",
        categoryId: "mv_tim_burton",
        tier: 400,
        prompt: "Tim Burton produced and conceived The Nightmare Before Christmas but didn't direct it due to scheduling. Who actually directed the film?",
        answer: "Henry Selick",
        acceptableAnswers: [],
        explanation: "Selick directed the painstaking stop-motion animation while Burton was busy directing Batman Returns. Selick later directed Coraline and Wendell & Wild.",
      },
      {
        id: "tmb_400_02",
        categoryId: "mv_tim_burton",
        tier: 400,
        prompt: "Before becoming a director, Burton worked as an animator at which major studio, where he felt creatively stifled?",
        answer: "Walt Disney Animation Studios",
        acceptableAnswers: ["Disney"],
        explanation: "Burton worked at Disney in the early 1980s but his dark, quirky style clashed with Disney's aesthetic. He was essentially paid to sit in a closet and draw, which led to his early short films.",
      },
      {
        id: "tmb_400_03",
        categoryId: "mv_tim_burton",
        tier: 400,
        prompt: "In Burton's 1988 hit Beetlejuice, what rule must the recently deceased couple follow about saying Beetlejuice's name?",
        answer: "Saying his name three times summons him (and saying it three times again sends him away)",
        acceptableAnswers: ["say his name three times", "saying Beetlejuice three times summons him"],
      },
      {
        id: "tmb_600_01",
        categoryId: "mv_tim_burton",
        tier: 600,
        prompt: "Burton made a short film at Disney in 1984 that was shelved for being too scary for children but later gained cult status. It was eventually expanded into a feature-length stop-motion film. What was the short called?",
        answer: "Frankenweenie",
        acceptableAnswers: [],
        explanation: "The 1984 live-action short was about a boy who reanimates his dead dog. Disney shelved it and fired Burton. He remade it as a full stop-motion feature in 2012.",
      },
      {
        id: "tmb_600_02",
        categoryId: "mv_tim_burton",
        tier: 600,
        prompt: "Burton's 1994 biographical film 'Ed Wood' follows the director often called 'the worst filmmaker ever.' What unusual creative choice did Burton make for the film's visual style?",
        answer: "He shot it entirely in black and white, despite studio pressure to use color",
        acceptableAnswers: ["shot in black and white", "filmed in black and white"],
        explanation: "Burton insisted on black-and-white to honor the era of Ed Wood's films and B-movie aesthetics. Martin Landau won an Oscar for his portrayal of Bela Lugosi.",
      },
      {
        id: "tmb_600_03",
        categoryId: "mv_tim_burton",
        tier: 600,
        prompt: "Burton's unrealized projects are legendary in Hollywood. He developed a Superman film in the 1990s that was never made despite costing tens of millions in pre-production. Who was cast as Superman?",
        answer: "Nicolas Cage",
        acceptableAnswers: ["Nic Cage", "Nicholas Cage"],
        explanation: "Superman Lives spent years in development with Nicolas Cage in costume fittings. The film's collapse is documented in the documentary 'The Death of Superman Lives: What Happened?'",
      },
    ],
  },
  {
    id: "mu_nin",
    group: "Music",
    name: "Nine Inch Nails",
    culture: "american",
    description: "Trent Reznor's industrial rock project that brought electronic aggression to the mainstream, from the raw fury of The Downward Spiral to his Oscar-winning film scores.",
    imageUrl: "",
    questions: [
      {
        id: "nin_200_01",
        categoryId: "mu_nin",
        tier: 200,
        prompt: "Who is the sole permanent member and creative mastermind behind Nine Inch Nails?",
        answer: "Trent Reznor",
        acceptableAnswers: [],
      },
      {
        id: "nin_200_02",
        categoryId: "mu_nin",
        tier: 200,
        prompt: "What NIN song was covered by Johnny Cash in what many consider the greatest cover version of all time?",
        answer: "Hurt",
        acceptableAnswers: [],
      },
      {
        id: "nin_200_03",
        categoryId: "mu_nin",
        tier: 200,
        prompt: "What genre is Nine Inch Nails most associated with, blending electronic music with rock aggression?",
        answer: "Industrial rock",
        acceptableAnswers: ["industrial", "industrial metal"],
      },
      {
        id: "nin_400_01",
        categoryId: "mu_nin",
        tier: 400,
        prompt: "The Downward Spiral was recorded in a house in Beverly Hills with a notorious and disturbing history. What happened there?",
        answer: "It was the house where members of the Manson Family murdered Sharon Tate and others in 1969",
        acceptableAnswers: ["the Sharon Tate murder house", "Manson murders", "the Cielo Drive house where Sharon Tate was killed"],
        explanation: "Reznor set up a studio he named Le Pig (referencing 'PIG' written in blood at the scene). He later said he regretted the decision, feeling it was exploitative.",
      },
      {
        id: "nin_400_02",
        categoryId: "mu_nin",
        tier: 400,
        prompt: "After a period of severe addiction and near-death, Reznor got sober and pivoted to film scoring. What was the first film he and collaborator Atticus Ross scored, winning them an Academy Award?",
        answer: "The Social Network",
        acceptableAnswers: [],
        explanation: "The 2010 David Fincher film launched Reznor and Ross's second career. They've since scored Gone Girl, Mank, Soul (winning a second Oscar), and Challengers.",
      },
      {
        id: "nin_400_03",
        categoryId: "mu_nin",
        tier: 400,
        prompt: "NIN's 'Closer' became a controversial hit in 1994 due to its explicit opening line and disturbing music video. The video was so graphic that MTV could only air it during what time slot?",
        answer: "Late night, and even then it was heavily edited with large portions replaced with black screens",
        acceptableAnswers: ["late night with heavy edits", "only late at night, heavily censored"],
      },
      {
        id: "nin_600_01",
        categoryId: "mu_nin",
        tier: 600,
        prompt: "In 2007, Reznor pioneered a radical approach to music distribution. What did he do with the album 'Ghosts I-IV' and later 'The Slip' that was revolutionary for a major artist at the time?",
        answer: "He released them independently for free (or pay-what-you-want) online after leaving his record label, making NIN one of the first major acts to embrace direct-to-fan digital distribution",
        acceptableAnswers: ["released them for free online", "pay what you want release", "free digital release"],
        explanation: "Reznor left Interscope Records and released Ghosts I-IV as a free/tiered download, and The Slip entirely free. This was months after Radiohead's In Rainbows experiment.",
      },
      {
        id: "nin_600_02",
        categoryId: "mu_nin",
        tier: 600,
        prompt: "The Fragile (1999) was a commercial disappointment compared to The Downward Spiral but is now considered NIN's masterpiece. What was unique about its structure?",
        answer: "It was a sprawling double album (Left and Right discs) with ambient interludes connecting aggressive tracks, designed as a continuous emotional journey through depression and recovery",
        acceptableAnswers: ["double album with Left and Right discs", "a double album designed as a continuous journey"],
        explanation: "Initially seen as overindulgent, The Fragile has been re-evaluated as Reznor's most ambitious and nuanced work. The 2017 Definitive Edition remaster further cemented its reputation.",
      },
      {
        id: "nin_600_03",
        categoryId: "mu_nin",
        tier: 600,
        prompt: "Reznor created an elaborate alternate reality game (ARG) to promote the album 'Year Zero.' What dystopian premise did it depict, and how did fans discover the game?",
        answer: "It depicted a 2022 American dystopia under a theocratic police state. Fans found USB drives planted at NIN concerts containing unreleased tracks and hidden websites, leading to a sprawling conspiracy narrative across dozens of websites.",
        acceptableAnswers: ["dystopian future ARG, USB drives at concerts", "USB drives with songs hidden at concerts leading to fake websites"],
        explanation: "The Year Zero ARG is considered one of the most ambitious and well-executed alternate reality games ever created, blurring the lines between marketing and art.",
      },
    ],
  },
  {
    id: "mu_foo_fighters",
    group: "Music",
    name: "Foo Fighters",
    culture: "american",
    description: "The post-grunge rock institution founded by Dave Grohl after Nirvana, becoming one of the biggest rock bands of the 21st century through relentless touring and anthemic songwriting.",
    imageUrl: "",
    questions: [
      {
        id: "foo_200_01",
        categoryId: "mu_foo_fighters",
        tier: 200,
        prompt: "Who founded the Foo Fighters and is the band's lead vocalist, originally famous as the drummer of another legendary band?",
        answer: "Dave Grohl",
        acceptableAnswers: [],
      },
      {
        id: "foo_200_02",
        categoryId: "mu_foo_fighters",
        tier: 200,
        prompt: "Before starting Foo Fighters, Dave Grohl was the drummer for which iconic grunge band?",
        answer: "Nirvana",
        acceptableAnswers: [],
      },
      {
        id: "foo_200_03",
        categoryId: "mu_foo_fighters",
        tier: 200,
        prompt: "What Foo Fighters anthem features the lyrics 'I've got another confession to make' and became one of their biggest hits?",
        answer: "Best of You",
        acceptableAnswers: [],
      },
      {
        id: "foo_400_01",
        categoryId: "mu_foo_fighters",
        tier: 400,
        prompt: "The first Foo Fighters album was unique because Dave Grohl played every single instrument and sang all the vocals himself. Why did he do this?",
        answer: "He recorded the demos alone at a studio to process his grief after Kurt Cobain's death, not originally intending to form a band",
        acceptableAnswers: ["he recorded it alone", "he played everything himself after Cobain died", "solo recordings after Nirvana ended"],
        explanation: "Grohl booked time at Robert Lang Studios in Seattle and recorded the entire album in five days. He only formed a band after the recordings gained attention.",
      },
      {
        id: "foo_400_02",
        categoryId: "mu_foo_fighters",
        tier: 400,
        prompt: "What does the name 'Foo Fighters' refer to?",
        answer: "A World War II term used by Allied pilots to describe unidentified flying objects or aerial phenomena",
        acceptableAnswers: ["WWII UFO sightings", "a term for UFOs in World War II", "unidentified aerial phenomena in WWII"],
      },
      {
        id: "foo_400_03",
        categoryId: "mu_foo_fighters",
        tier: 400,
        prompt: "Taylor Hawkins, the band's beloved drummer, tragically died in 2022. In what city and country did he pass away during a concert tour?",
        answer: "Bogotá, Colombia",
        acceptableAnswers: ["Bogota", "Colombia"],
        explanation: "Hawkins died hours before a scheduled festival performance. His death deeply affected the rock community, and the band held two massive tribute concerts in his honor.",
      },
      {
        id: "foo_600_01",
        categoryId: "mu_foo_fighters",
        tier: 600,
        prompt: "The Foo Fighters created a comedy horror film in 2022 where they play themselves recording an album in a haunted house. What was the film called?",
        answer: "Studio 666",
        acceptableAnswers: [],
        explanation: "The film features the band moving into an Encino mansion to record their 10th album, only to discover it's haunted by the spirit of a previous band's demonic recording session.",
      },
      {
        id: "foo_600_02",
        categoryId: "mu_foo_fighters",
        tier: 600,
        prompt: "In their early days, the Foo Fighters had an ongoing feud with the Westboro Baptist Church, who protested outside their concerts. How did the band famously respond at a 2011 protest?",
        answer: "They drove past the protesters on a flatbed truck playing 'Hot Buns' (a parody country song) while wearing wigs and costumes, turning the protest into a comedy bit",
        acceptableAnswers: ["performed from a truck outside the protest", "played music on a flatbed truck in front of them", "counter-protested with music from a truck"],
        explanation: "Grohl's gleeful trolling of the WBC became a viral moment. The band repeated similar stunts at other WBC protests, always choosing humor over confrontation.",
      },
      {
        id: "foo_600_03",
        categoryId: "mu_foo_fighters",
        tier: 600,
        prompt: "Dave Grohl famously broke his leg falling off stage during a 2015 concert in Gothenburg, Sweden. What did he do after the injury?",
        answer: "He was taken backstage, got his leg stabilized, and returned to finish the entire concert sitting in a custom-built throne — then completed the rest of the tour from the throne",
        acceptableAnswers: ["finished the show with a broken leg", "came back and played from a throne", "returned to finish the concert in a special chair"],
        explanation: "The 'Grohl Throne' became legendary. He had a custom guitar-shaped throne built and completed the remaining tour dates from it, refusing to cancel shows.",
      },
    ],
  },
  {
    id: "vg_metroid",
    group: "Video Games",
    name: "Metroid",
    culture: "universal",
    description: "Nintendo's iconic sci-fi series following bounty hunter Samus Aran through alien worlds, defining the exploration-based action genre alongside Castlevania.",
    imageUrl: "",
    questions: [
      {
        id: "met_200_01",
        categoryId: "vg_metroid",
        tier: 200,
        prompt: "What is the name of the armored bounty hunter protagonist of the Metroid series?",
        answer: "Samus Aran",
        acceptableAnswers: ["Samus"],
      },
      {
        id: "met_200_02",
        categoryId: "vg_metroid",
        tier: 200,
        prompt: "What jellyfish-like alien creatures, which the series is named after, are a recurring threat that latch onto and drain the life energy of their victims?",
        answer: "Metroids",
        acceptableAnswers: [],
      },
      {
        id: "met_200_03",
        categoryId: "vg_metroid",
        tier: 200,
        prompt: "The original Metroid (1986) had a famous twist at the ending. What was revealed about Samus when players completed the game quickly?",
        answer: "Samus is a woman — the game's ending reveals her without her armor, shocking players who assumed the armored protagonist was male",
        acceptableAnswers: ["Samus is a woman", "she's female", "Samus is revealed to be a woman"],
      },
      {
        id: "met_400_01",
        categoryId: "vg_metroid",
        tier: 400,
        prompt: "Metroid Prime (2002) transitioned the series from 2D to first-person and is considered one of the greatest games ever made. What studio developed it?",
        answer: "Retro Studios",
        acceptableAnswers: [],
        explanation: "Retro Studios, based in Austin, Texas, was a struggling studio that Nintendo gave the Metroid franchise to. Many fans were skeptical of a Western studio handling the IP, but the result was a masterpiece.",
      },
      {
        id: "met_400_02",
        categoryId: "vg_metroid",
        tier: 400,
        prompt: "What is the recurring dragon-like Space Pirate leader who serves as Samus's arch-nemesis throughout the series?",
        answer: "Ridley",
        acceptableAnswers: [],
        explanation: "Ridley killed Samus's parents when she was a child, making their rivalry deeply personal. He's named after Ridley Scott, director of Alien.",
      },
      {
        id: "met_400_03",
        categoryId: "vg_metroid",
        tier: 400,
        prompt: "What gameplay technique, named after the series, involves players acquiring new abilities that allow them to access previously unreachable areas, encouraging backtracking and exploration?",
        answer: "Metroidvania (the genre named after Metroid and Castlevania)",
        acceptableAnswers: ["Metroidvania"],
      },
      {
        id: "met_600_01",
        categoryId: "vg_metroid",
        tier: 600,
        prompt: "Super Metroid (1994) features a famous speedrunning trick where Samus can combine a shinespark with a wall jump to reach areas not normally accessible. What is this sequence-breaking technique called?",
        answer: "Mockball (or crystal flash for a different trick) — the mockball specifically lets Samus maintain running speed while morphed into a ball",
        acceptableAnswers: ["mockball", "Mockball"],
        explanation: "The mockball preserves run speed in morph ball form, allowing early access to items. It's a cornerstone of Super Metroid speedruns.",
      },
      {
        id: "met_600_02",
        categoryId: "vg_metroid",
        tier: 600,
        prompt: "Metroid Dread (2021) was in development hell for over 15 years. Which studio finally developed it, and what was the original platform it was planned for?",
        answer: "MercurySteam developed the final version. Dread was originally planned for the Nintendo DS around 2005-2006 but was cancelled due to technical limitations.",
        acceptableAnswers: ["MercurySteam, originally for DS", "MercurySteam, Nintendo DS"],
        explanation: "Dread was first mentioned by Yoshio Sakamoto in 2005. Multiple attempts to develop it failed before MercurySteam (who made Samus Returns) succeeded on the Switch.",
      },
      {
        id: "met_600_03",
        categoryId: "vg_metroid",
        tier: 600,
        prompt: "In Super Metroid's climax, the baby Metroid sacrifices itself to save Samus. This moment was designed to be emotional through a specific game design trick — the player already had a relationship with the baby Metroid from an earlier game. Which game established this connection?",
        answer: "Metroid II: Return of Samus — Samus spares the last baby Metroid after it imprints on her, thinking she's its mother",
        acceptableAnswers: ["Metroid II", "Metroid 2", "Return of Samus"],
        explanation: "The baby Metroid hatches at the end of Metroid II and follows Samus peacefully. Super Metroid opens with it being stolen, immediately investing the player emotionally.",
      },
    ],
  },
  {
    id: "vg_mario_deep",
    group: "Video Games",
    name: "Mario Deep Cuts",
    culture: "universal",
    description: "Beyond the surface of Nintendo's mascot — the development secrets, strange spinoffs, and deep lore of the Mario franchise.",
    imageUrl: "",
    questions: [
      {
        id: "mrd_200_01",
        categoryId: "vg_mario_deep",
        tier: 200,
        prompt: "What is Mario's full name, as confirmed by Nintendo?",
        answer: "Mario Mario",
        acceptableAnswers: [],
        explanation: "Shigeru Miyamoto confirmed that Mario's full name is 'Mario Mario' (and Luigi's is 'Luigi Mario'), matching what the 1993 movie used.",
      },
      {
        id: "mrd_200_02",
        categoryId: "vg_mario_deep",
        tier: 200,
        prompt: "What was Mario originally called in his first appearance in the 1981 arcade game Donkey Kong?",
        answer: "Jumpman",
        acceptableAnswers: [],
      },
      {
        id: "mrd_200_03",
        categoryId: "vg_mario_deep",
        tier: 200,
        prompt: "Who is the creator of Mario and many of Nintendo's most famous characters?",
        answer: "Shigeru Miyamoto",
        acceptableAnswers: ["Miyamoto"],
      },
      {
        id: "mrd_400_01",
        categoryId: "vg_mario_deep",
        tier: 400,
        prompt: "Mario wears a cap, has a mustache, and wears overalls. These design choices weren't aesthetic — they solved specific technical limitations of early hardware. What problems did each solve?",
        answer: "The cap avoided animating hair, the mustache made the face visible without detailed features, and the overalls made arm movements visible against the body — all due to limited pixel resolution",
        acceptableAnswers: ["cap hid hair, mustache showed the face, overalls showed arm movement", "technical limitations of pixel art"],
      },
      {
        id: "mrd_400_02",
        categoryId: "vg_mario_deep",
        tier: 400,
        prompt: "In Super Mario Bros. 3, there's a popular fan theory endorsed by Miyamoto about the entire game. What is it?",
        answer: "The entire game is a stage performance — evidenced by the curtain opening, bolted-down platforms, and the exit at the end of each level",
        acceptableAnswers: ["it's all a stage play", "the game is a theatrical performance"],
        explanation: "Miyamoto confirmed in 2015 that Super Mario Bros. 3 was always intended to be a stage performance, explaining all the theatrical elements.",
      },
      {
        id: "mrd_400_03",
        categoryId: "vg_mario_deep",
        tier: 400,
        prompt: "Mario was named after a real person. Who was this person, and what was his relationship to Nintendo?",
        answer: "Mario Segale, the landlord of Nintendo of America's warehouse in Tukwila, Washington",
        acceptableAnswers: ["Mario Segale", "their landlord", "Nintendo's warehouse landlord"],
        explanation: "Segale reportedly confronted Nintendo over overdue rent. The resemblance between the portly, mustachioed landlord and the character led to the naming.",
      },
      {
        id: "mrd_600_01",
        categoryId: "vg_mario_deep",
        tier: 600,
        prompt: "Super Mario 64's code contains a famously inscrutable plaque in front of the castle fountain. Fans have debated for decades what the blurry text says. What are the two most popular readings?",
        answer: "'L is Real 2401' — fans debated whether it meant Luigi was hidden in the game (he wasn't) or it was just a generic texture. Years later, Luigi was found in the leaked SM64 source code as an unfinished character.",
        acceptableAnswers: ["L is Real 2401", "L is real 2401"],
        explanation: "The 2020 Nintendo gigaleak revealed Luigi model data in SM64's source code, partially vindicating decades of fan speculation.",
      },
      {
        id: "mrd_600_02",
        categoryId: "vg_mario_deep",
        tier: 600,
        prompt: "Super Mario Bros. 2 (the Western version) is famously not an original Mario game. What game was it actually, and why did Nintendo make the swap?",
        answer: "It was Doki Doki Panic, a Fuji TV tie-in game. Nintendo of America felt the real Super Mario Bros. 2 (released in Japan) was too difficult and too similar to the original for Western audiences.",
        acceptableAnswers: ["Doki Doki Panic", "it was a reskin of Doki Doki Panic"],
        explanation: "The Japanese SMB2 (later released in the West as 'The Lost Levels') was essentially a brutally hard expansion. Nintendo reskinned Doki Doki Panic with Mario characters for the Western release.",
      },
      {
        id: "mrd_600_03",
        categoryId: "vg_mario_deep",
        tier: 600,
        prompt: "The Super Mario 64 speedrunning community has spent years trying to collect a star using the minimum number of A-button presses. What is this challenge called, and what is remarkable about the strategies used?",
        answer: "The A Button Challenge (ABC) — runners use incredibly complex strategies involving parallel universes, speed overflow glitches, and hyperspeed to avoid pressing the jump button, with some stars requiring hours of setup",
        acceptableAnswers: ["A Button Challenge", "ABC challenge", "the A press challenge"],
        explanation: "Pannenkoek2012's famous video 'Watch for Rolling Rocks in 0.5 A Presses' introduced the concept of 'half A presses' (holding A from a previous star) and became an iconic speedrun meme.",
      },
    ],
  },
  {
    id: "mu_soundgarden",
    group: "Music",
    name: "Soundgarden",
    culture: "american",
    description: "The Seattle grunge pioneers known for Chris Cornell's four-octave vocal range and Kim Thayil's dissonant guitar work, bridging metal heaviness with alternative experimentation.",
    imageUrl: "",
    questions: [
      {
        id: "sgn_200_01",
        categoryId: "mu_soundgarden",
        tier: 200,
        prompt: "Who was Soundgarden's legendary lead vocalist, also known for his work in Audioslave and a solo career?",
        answer: "Chris Cornell",
        acceptableAnswers: ["Cornell"],
      },
      {
        id: "sgn_200_02",
        categoryId: "mu_soundgarden",
        tier: 200,
        prompt: "What 1994 Soundgarden song about falling and hopelessness became their biggest hit and is widely considered one of the greatest grunge songs?",
        answer: "Black Hole Sun",
        acceptableAnswers: [],
      },
      {
        id: "sgn_200_03",
        categoryId: "mu_soundgarden",
        tier: 200,
        prompt: "Soundgarden is considered one of the 'Big Four' of grunge. Name any two of the other three bands.",
        answer: "Nirvana, Pearl Jam, Alice in Chains",
        acceptableAnswers: ["Nirvana", "Pearl Jam", "Alice in Chains"],
      },
      {
        id: "sgn_400_01",
        categoryId: "mu_soundgarden",
        tier: 400,
        prompt: "Soundgarden's 'Superunknown' (1994) debuted at number one. What makes it structurally unusual for a grunge album?",
        answer: "It features extensive use of unusual time signatures, alternate tunings, and psychedelic elements rather than standard punk-derived grunge structures",
        acceptableAnswers: ["unusual time signatures and tunings", "experimental time signatures", "psychedelic elements and odd meters"],
        explanation: "Songs like 'My Wave' (5/4 time), 'Spoonman' (7/4 sections), and 'The Day I Tried to Live' showcase the band's progressive tendencies disguised as radio rock.",
      },
      {
        id: "sgn_400_02",
        categoryId: "mu_soundgarden",
        tier: 400,
        prompt: "Before Soundgarden, Chris Cornell and Soundgarden's Matt Cameron collaborated with members of Pearl Jam on a project. What was this supergroup called?",
        answer: "Temple of the Dog",
        acceptableAnswers: [],
        explanation: "Temple of the Dog was a tribute to Andrew Wood of Mother Love Bone. Their self-titled album included 'Hunger Strike,' featuring an unknown Eddie Vedder on vocals.",
      },
      {
        id: "sgn_400_03",
        categoryId: "mu_soundgarden",
        tier: 400,
        prompt: "Soundgarden was one of the first grunge bands to sign to a major label. Which label signed them, making them the first Sub Pop-associated act to jump to a major?",
        answer: "A&M Records",
        acceptableAnswers: ["A&M"],
        explanation: "Their 1989 album Louder Than Love on A&M predated Nirvana's Nevermind on DGC by two years, making Soundgarden grunge's first major-label act.",
      },
      {
        id: "sgn_600_01",
        categoryId: "mu_soundgarden",
        tier: 600,
        prompt: "Chris Cornell's vocal range was legendary, spanning nearly four octaves. What specific vocal technique did he use on songs like 'Jesus Christ Pose' that set him apart from other rock vocalists?",
        answer: "He combined a powerful belt with controlled use of vocal fry, falsetto, and a technique similar to Tuvan throat singing to create harmonic overtones",
        acceptableAnswers: ["vocal fry and falsetto combination", "he used throat singing techniques", "mixed belt with overtone techniques"],
        explanation: "Cornell's ability to seamlessly transition between a full-chested roar and a delicate falsetto, sometimes in the same phrase, was virtually unmatched in rock music.",
      },
      {
        id: "sgn_600_02",
        categoryId: "mu_soundgarden",
        tier: 600,
        prompt: "Kim Thayil's guitar playing was defined by his use of unusual tunings. On 'Superunknown,' he tuned many songs to non-standard configurations. What extreme tuning did he use on 'My Wave'?",
        answer: "Drop D with the low E tuned down to C (CGDGBE or similar low tunings)",
        acceptableAnswers: ["drop tuning", "dropped C or similar", "heavily down-tuned guitar"],
        explanation: "Thayil and Cornell experimented with dozens of alternate tunings across their catalog, creating Soundgarden's uniquely heavy yet melodic sound.",
      },
      {
        id: "sgn_600_03",
        categoryId: "mu_soundgarden",
        tier: 600,
        prompt: "The band's name 'Soundgarden' comes from a real place in Seattle. What is it?",
        answer: "A Sound Garden — a wind-activated sound sculpture (A Sound Garden by Douglas Hollis) located at NOAA's campus on Sand Point in Seattle",
        acceptableAnswers: ["a sound sculpture in Seattle", "A Sound Garden sculpture", "a wind art installation"],
        explanation: "The sculpture consists of steel tower structures with organ pipes that produce tones when wind passes through them. It's located on the shore of Lake Washington.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 62 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
