#!/usr/bin/env python3
"""Insert wave 80 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_shogun",
    group: "TV Shows",
    name: "Shōgun (2024)",
    culture: "universal",
    description: "The epic FX adaptation of James Clavell's novel set in feudal Japan",
    imageUrl: "",
    questions: [
      { id: "shg_200_01", categoryId: "tv_shogun", tier: 200, prompt: "What English pilot is shipwrecked in Japan and becomes entangled in the political struggles of feudal lords?", answer: "John Blackthorne (Anjin)", acceptableAnswers: ["John Blackthorne", "Blackthorne", "Anjin"], explanation: "Blackthorne is based on the historical William Adams, the first Englishman to reach Japan." },
      { id: "shg_200_02", categoryId: "tv_shogun", tier: 200, prompt: "Which powerful lord, played by Hiroyuki Sanada, schemes to become the supreme ruler of Japan?", answer: "Lord Yoshii Toranaga", acceptableAnswers: ["Toranaga", "Lord Toranaga", "Yoshii Toranaga"], explanation: "Toranaga is based on Tokugawa Ieyasu, who historically became shōgun and unified Japan." },
      { id: "shg_200_03", categoryId: "tv_shogun", tier: 200, prompt: "What Japanese noblewoman serves as Blackthorne's translator and love interest?", answer: "Lady Toda Mariko", acceptableAnswers: ["Mariko", "Lady Mariko", "Toda Mariko"], explanation: "Mariko is a Christian convert torn between her duty to Toranaga and her personal faith and desires." },
      { id: "shg_400_01", categoryId: "tv_shogun", tier: 400, prompt: "What council of regents threatens Toranaga's life and forces him to scheme for survival?", answer: "The Council of Regents", acceptableAnswers: ["Council of Regents", "The Council of Regents", "The Regents"], explanation: "The five regents were appointed to rule until the heir comes of age, but their power struggles drive the show's political intrigue." },
      { id: "shg_400_02", categoryId: "tv_shogun", tier: 400, prompt: "What historical battle, depicted near the series' end, established the real Tokugawa shogunate's dominance?", answer: "Battle of Sekigahara (referenced/implied)", acceptableAnswers: ["Sekigahara", "Battle of Sekigahara"], explanation: "The Battle of Sekigahara in 1600 was the decisive conflict that led to Tokugawa Ieyasu's rise as shōgun." },
      { id: "shg_400_03", categoryId: "tv_shogun", tier: 400, prompt: "What does Mariko's final act at the castle accomplish for Toranaga's political strategy?", answer: "Her sacrificial death publicly exposes and shames the antagonists, turning political opinion in Toranaga's favor", acceptableAnswers: ["Her death turns opinion for Toranaga", "Sacrificial death shames enemies", "Public martyrdom for political advantage"], explanation: "Mariko's death at Osaka Castle is both a personal sacrifice and a calculated political move that Toranaga anticipated." },
      { id: "shg_600_01", categoryId: "tv_shogun", tier: 600, prompt: "What specific historical figure is Lord Ishido based on, and how did the real person's fate mirror the character's?", answer: "Ishida Mitsunari, who lost at Sekigahara and was executed by beheading", acceptableAnswers: ["Ishida Mitsunari", "Mitsunari"], explanation: "Ishida Mitsunari organized the Western coalition against Tokugawa but was defeated and executed after Sekigahara." },
      { id: "shg_600_02", categoryId: "tv_shogun", tier: 600, prompt: "What language approach did the 2024 series take that distinguished it from the 1980 miniseries?", answer: "Approximately 70% of dialogue is in Japanese with subtitles, rather than having Japanese characters speak English", acceptableAnswers: ["Mostly Japanese dialogue with subtitles", "70% Japanese language", "Japanese with subtitles"], explanation: "The decision to film primarily in Japanese gave the series unprecedented authenticity and was a major factor in its critical acclaim." },
      { id: "shg_600_03", categoryId: "tv_shogun", tier: 600, prompt: "What is the concept of 'crimson sky' (紅の空) that Toranaga references, and what does it represent in his strategy?", answer: "A seemingly desperate final gambit / the appearance of total defeat that actually positions him for ultimate victory", acceptableAnswers: ["Desperate final gambit", "Appearance of defeat hiding victory", "Strategic feigned desperation"], explanation: "'Crimson sky' represents Toranaga's philosophy of appearing to lose while actually maneuvering all pieces into place for inevitable victory." }
    ]
  },
  {
    id: "tv_bears_d",
    group: "TV Shows",
    name: "The Bear (Deep Cut)",
    culture: "american",
    description: "Beyond the basics of Carmy's kitchen — the deeper details of FX's culinary drama",
    imageUrl: "",
    questions: [
      { id: "brd_200_01", categoryId: "tv_bears_d", tier: 200, prompt: "What Michelin-starred restaurant did Carmy work at in New York before returning to Chicago?", answer: "A fictional high-end restaurant (based on establishments like Eleven Madison Park / The French Laundry)", acceptableAnswers: ["Eleven Madison Park", "A fine dining restaurant in New York", "High-end New York restaurant"], explanation: "While never explicitly named in early episodes, the show draws from real culinary world experiences at top restaurants." },
      { id: "brd_200_02", categoryId: "tv_bears_d", tier: 200, prompt: "What is Richie's full first name, and what is his relationship to the Berzatto family?", answer: "Richard; he was Mikey's best friend (not blood family)", acceptableAnswers: ["Richard", "Richie / Richard, Mikey's best friend"], explanation: "Richie's deep loyalty stems from his bond with the late Mikey Berzatto, not blood relation." },
      { id: "brd_200_03", categoryId: "tv_bears_d", tier: 200, prompt: "What does the kitchen brigade call out when they acknowledge an order or instruction?", answer: "Yes, Chef!", acceptableAnswers: ["Yes Chef", "Yes, Chef!", "Heard"], explanation: "The brigade system's call-and-response ('Yes, Chef!') and 'Heard!' are authentic kitchen culture elements." },
      { id: "brd_400_01", categoryId: "tv_bears_d", tier: 400, prompt: "In the acclaimed single-shot episode 'Fishes,' what family event descends into chaos, and what holiday is it set during?", answer: "A Christmas Eve dinner with the Berzatto family", acceptableAnswers: ["Christmas Eve dinner", "Christmas dinner", "Christmas Eve"], explanation: "The 'Fishes' episode captures an entire dysfunctional family Christmas in what feels like one continuous take, featuring guest stars like Jamie Lee Curtis." },
      { id: "brd_400_02", categoryId: "tv_bears_d", tier: 400, prompt: "What transformative experience does Richie have during his stage at a fine dining restaurant that changes his entire outlook?", answer: "He stages at Ever (a fictional restaurant) and discovers pride and purpose in hospitality/service", acceptableAnswers: ["Stage at Ever", "Discovers hospitality and service", "Fine dining stage changes his outlook"], explanation: "Richie's stage arc in Season 2 is one of TV's most celebrated character transformations, set to 'Love Story' by Taylor Swift." },
      { id: "brd_400_03", categoryId: "tv_bears_d", tier: 400, prompt: "What does Carmy find hidden in the tomato cans at the original beef restaurant?", answer: "Cash / money that Mikey had been hiding", acceptableAnswers: ["Money", "Cash", "Hidden cash", "Money in the cans"], explanation: "Mikey had been stashing cash in tomato cans, providing the funding needed to transform The Beef into The Bear." },
      { id: "brd_600_01", categoryId: "tv_bears_d", tier: 600, prompt: "What specific culinary technique does the show depict when Sydney prepares the dish that wins Carmy's respect in Season 1 — involving a refined Italian-African fusion approach?", answer: "A refined version of a traditional dish using classical French/Italian technique applied to her own cultural food heritage", acceptableAnswers: ["Italian-African fusion technique", "Classical technique on cultural food", "Refined cultural fusion cooking"], explanation: "Sydney's ability to elevate familiar flavors through classical technique demonstrates the show's thesis about the intersection of heritage and haute cuisine." },
      { id: "brd_600_02", categoryId: "tv_bears_d", tier: 600, prompt: "What real Chicago restaurant's kitchen served as the primary filming location for The Beef/The Bear?", answer: "Mr. Beef on Orleans (now closed), with additional sets built at Cinespace Studios", acceptableAnswers: ["Mr. Beef", "Mr. Beef on Orleans"], explanation: "The production used the real Mr. Beef restaurant and built additional kitchen sets to capture authentic Chicago Italian beef culture." },
      { id: "brd_600_03", categoryId: "tv_bears_d", tier: 600, prompt: "What is the significance of the recurring 'Let It Rip' tattoo, and whose philosophy does it represent?", answer: "It represents Mikey's approach to life — reckless abandon and living fully despite consequences; Carmy inherits this tension between control and chaos", acceptableAnswers: ["Mikey's philosophy", "Reckless abandon philosophy", "Mikey's approach to life"], explanation: "The tattoo embodies the show's central tension: Mikey's chaotic 'let it rip' ethos versus Carmy's obsessive need for control and perfection." }
    ]
  },
  {
    id: "mu_kate_bush",
    group: "Music",
    name: "Kate Bush",
    culture: "universal",
    description: "The visionary artist who created entire worlds with her voice and imagination",
    imageUrl: "",
    questions: [
      { id: "ktb_200_01", categoryId: "mu_kate_bush", tier: 200, prompt: "What 1985 song experienced a massive resurgence after being featured in Stranger Things Season 4?", answer: "Running Up That Hill (A Deal with God)", acceptableAnswers: ["Running Up That Hill", "Running Up That Hill (A Deal with God)"], explanation: "The song reached #1 in multiple countries in 2022, 37 years after its original release, thanks to Stranger Things." },
      { id: "ktb_200_02", categoryId: "mu_kate_bush", tier: 200, prompt: "At what age did Kate Bush become the first woman to have a UK #1 hit with a self-written song, with 'Wuthering Heights'?", answer: "19", acceptableAnswers: ["19", "Nineteen"], explanation: "Bush wrote 'Wuthering Heights' at 18 and it reached #1 when she was 19, inspired by Emily Brontë's novel." },
      { id: "ktb_200_03", categoryId: "mu_kate_bush", tier: 200, prompt: "What literary character did she portray in her debut hit, singing in a distinctive high-pitched voice?", answer: "Catherine Earnshaw (from Wuthering Heights)", acceptableAnswers: ["Catherine Earnshaw", "Cathy", "Catherine", "Cathy Earnshaw"], explanation: "Bush embodied the ghost of Catherine Earnshaw in the song, performing with dramatic choreography and her signature soprano." },
      { id: "ktb_400_01", categoryId: "mu_kate_bush", tier: 400, prompt: "What groundbreaking 1985 album was one of the first to use the Fairlight CMI sampler extensively and featured a cinematic, conceptual approach?", answer: "Hounds of Love", explanation: "Hounds of Love's second side, 'The Ninth Wave,' is a continuous suite about a woman drowning at sea, using the Fairlight to create otherworldly soundscapes." },
      { id: "ktb_400_02", categoryId: "mu_kate_bush", tier: 400, prompt: "What is 'The Ninth Wave,' the continuous suite that makes up Side B of Hounds of Love?", answer: "A conceptual suite about a woman lost at sea at night, drifting between consciousness and unconsciousness", acceptableAnswers: ["Suite about drowning at sea", "Woman lost at sea", "Conceptual suite about drowning"], explanation: "The Ninth Wave draws from Tennyson's poem and follows a woman's psychological journey while floating in the ocean at night." },
      { id: "ktb_400_03", categoryId: "mu_kate_bush", tier: 400, prompt: "What unprecedented live show residency did Kate Bush perform in 2014 after a 35-year absence from touring?", answer: "Before the Dawn at the Hammersmith Apollo", acceptableAnswers: ["Before the Dawn", "Before the Dawn at Hammersmith"], explanation: "Before the Dawn ran for 22 sold-out shows, with Bush performing elaborate theatrical productions of her album suites." },
      { id: "ktb_600_01", categoryId: "mu_kate_bush", tier: 600, prompt: "What specific Fairlight CMI sound did Bush use as the rhythmic foundation of 'Running Up That Hill,' sampling and manipulating what source?", answer: "A processed cello sample and Fairlight-programmed drum pattern with her own breathing/vocal samples layered in", acceptableAnswers: ["Fairlight cello sample", "Processed cello and breathing samples", "Fairlight drum and vocal samples"], explanation: "Bush pioneered the use of the Fairlight CMI's sampling capabilities, layering processed organic sounds into rhythmic foundations years before this became common." },
      { id: "ktb_600_02", categoryId: "mu_kate_bush", tier: 600, prompt: "What specific track on 'The Dreaming' album used the digeridoo and was inspired by Australian Aboriginal culture, and what controversy did it create?", answer: "The Dreaming (title track), which used didgeridoo and Aboriginal vocal styles, later discussed in context of cultural appropriation", acceptableAnswers: ["The Dreaming title track", "The Dreaming"], explanation: "Bush's fascination with Aboriginal culture influenced the album's experimental direction, though later discussions examined the cultural dynamics of a British artist using these elements." },
      { id: "ktb_600_03", categoryId: "mu_kate_bush", tier: 600, prompt: "What mathematical concept inspired the track 'Pi' from the album Aerial, and what notable error appears in the song's lyric?", answer: "She sings the digits of pi but makes an error around the 54th decimal place, skipping several digits", acceptableAnswers: ["Sings digits of pi with an error", "Error in pi digits around 54th place", "Skips digits of pi in the song"], explanation: "Bush sings pi to over 100 decimal places but makes a documented error, which fans have debated as either a mistake or intentional artistic choice." }
    ]
  },
  {
    id: "mu_miles",
    group: "Music",
    name: "Miles Davis",
    culture: "american",
    description: "The trumpeter who reinvented jazz at least five times across four decades",
    imageUrl: "",
    questions: [
      { id: "mld_200_01", categoryId: "mu_miles", tier: 200, prompt: "What 1959 album, featuring tracks like 'So What,' is the best-selling jazz record of all time?", answer: "Kind of Blue", explanation: "Kind of Blue has sold over 5 million copies and introduced modal jazz to a mainstream audience." },
      { id: "mld_200_02", categoryId: "mu_miles", tier: 200, prompt: "What controversial 1970 album fused jazz with rock and funk, alienating jazz purists?", answer: "Bitches Brew", explanation: "Bitches Brew's electric experimentation essentially created jazz fusion and sold over a million copies." },
      { id: "mld_200_03", categoryId: "mu_miles", tier: 200, prompt: "What instrument did Miles Davis play, becoming one of its most recognized practitioners?", answer: "Trumpet", acceptableAnswers: ["Trumpet", "The trumpet"], explanation: "Davis's trumpet tone — intimate, muted, and sparse — became one of the most recognizable sounds in music." },
      { id: "mld_400_01", categoryId: "mu_miles", tier: 400, prompt: "What approach did Miles use on Kind of Blue, giving musicians scales (modes) instead of chord changes to improvise over?", answer: "Modal jazz", acceptableAnswers: ["Modal jazz", "Modal improvisation", "Modes"], explanation: "Modal jazz freed musicians from complex chord progressions, allowing more melodic and atmospheric improvisation." },
      { id: "mld_400_02", categoryId: "mu_miles", tier: 400, prompt: "What pianist and composer arranged the landmark 'Birth of the Cool' sessions that pioneered cool jazz?", answer: "Gil Evans", acceptableAnswers: ["Gil Evans"], explanation: "Gil Evans's orchestral arrangements with Miles created a softer, more cerebral alternative to bebop's intensity." },
      { id: "mld_400_03", categoryId: "mu_miles", tier: 400, prompt: "During what period in the late 1970s did Miles completely withdraw from music, battling health problems and addiction?", answer: "1975-1980 (his 'silent period')", acceptableAnswers: ["1975-1980", "Late 1970s", "Five-year retirement", "The silent period"], explanation: "Miles retreated from public life for five years before returning with 'The Man with the Horn' in 1981." },
      { id: "mld_600_01", categoryId: "mu_miles", tier: 600, prompt: "What specific recording technique did producer Teo Macero pioneer on Bitches Brew, treating the studio recordings like raw material?", answer: "Tape splicing and editing of long jam sessions into composed pieces, essentially inventing post-production in jazz", acceptableAnswers: ["Tape splicing", "Post-production editing of jams", "Editing jam sessions into compositions"], explanation: "Macero spliced together hours of improvisations into cohesive tracks, presaging hip-hop sampling and electronic music production by decades." },
      { id: "mld_600_02", categoryId: "mu_miles", tier: 600, prompt: "What specific Harmon mute technique gave Miles his signature intimate tone on ballads like those on Kind of Blue?", answer: "Playing close to the microphone with a stemless Harmon mute, creating an intimate, breathy quality", acceptableAnswers: ["Stemless Harmon mute close-miked", "Harmon mute with stem removed", "Close-miked stemless Harmon"], explanation: "By removing the stem from the Harmon mute and playing directly into the microphone, Miles created his signature vulnerable, whispery tone." },
      { id: "mld_600_03", categoryId: "mu_miles", tier: 600, prompt: "What did Miles mean by his famous instruction to musicians: 'Don't play what's there, play what's not there'?", answer: "Emphasize space, silence, and the notes you choose NOT to play — restraint and negative space are as important as the notes themselves", acceptableAnswers: ["Use space and silence", "Play what's not there means use space", "Negative space in music"], explanation: "Miles's philosophy of 'less is more' — that silence and space between notes carry as much meaning as the notes themselves — became his defining artistic principle." }
    ]
  },
  {
    id: "vg_returnal",
    group: "Video Games",
    name: "Returnal",
    culture: "universal",
    description: "Housemarque's roguelike shooter about an astronaut trapped in a death loop on an alien planet",
    imageUrl: "",
    questions: [
      { id: "rtn_200_01", categoryId: "vg_returnal", tier: 200, prompt: "What is the name of the astronaut protagonist who crash-lands on the planet Atropos?", answer: "Selene Vassos", acceptableAnswers: ["Selene", "Selene Vassos"], explanation: "Selene is an ASTRA scout who discovers she's trapped in a time loop, dying and restarting on the hostile planet." },
      { id: "rtn_200_02", categoryId: "vg_returnal", tier: 200, prompt: "What genre-defining mechanic means that death sends Selene back to the crash site with most progress lost?", answer: "Roguelike / roguelite permadeath loop", acceptableAnswers: ["Roguelike", "Roguelite", "Permadeath", "Death loop"], explanation: "Returnal blends third-person bullet-hell action with roguelike structure, where each death randomizes the world layout." },
      { id: "rtn_200_03", categoryId: "vg_returnal", tier: 200, prompt: "What mysterious signal called 'White Shadow' is Selene drawn to investigate on the planet's surface?", answer: "The White Shadow broadcast / signal", acceptableAnswers: ["White Shadow", "The White Shadow", "White Shadow signal"], explanation: "The White Shadow signal pulls Selene deeper into Atropos, blurring the line between her mission and her personal psychological journey." },
      { id: "rtn_400_01", categoryId: "vg_returnal", tier: 400, prompt: "What 20th-century house does Selene encounter on the alien planet, and why is it impossible for it to be there?", answer: "Her childhood home — a 20th century house that shouldn't exist on an alien planet millions of light-years from Earth", acceptableAnswers: ["Her childhood home", "Selene's house", "Her house from Earth"], explanation: "The impossible house serves as a portal into Selene's past trauma and is the key to understanding the game's psychological narrative." },
      { id: "rtn_400_02", categoryId: "vg_returnal", tier: 400, prompt: "What does the astronaut figure that appears throughout the game represent?", answer: "Selene herself / her trauma and guilt, particularly related to a car accident", acceptableAnswers: ["Selene's trauma", "Herself", "Her guilt", "The car accident"], explanation: "The astronaut is a manifestation of Selene's psychological state, connected to a pivotal traumatic event involving her mother." },
      { id: "rtn_400_03", categoryId: "vg_returnal", tier: 400, prompt: "What is the significance of the octopus/squid-like creature that appears in house sequences?", answer: "It represents Selene's relationship with her mother and the cycle of trauma being passed down", acceptableAnswers: ["Mother-daughter trauma", "Relationship with her mother", "Intergenerational trauma"], explanation: "The cephalopod imagery connects to themes of drowning, suffocation, and the inescapable grip of inherited trauma." },
      { id: "rtn_600_01", categoryId: "vg_returnal", tier: 600, prompt: "What is the true nature of Atropos according to the game's secret ending, and what does it suggest about Selene's loop?", answer: "Atropos may be a psychological construct — the loop is Selene processing her guilt over a car accident where she drove into a lake, killing/injuring her mother (or child)", acceptableAnswers: ["Psychological construct", "Guilt over car accident", "Processing trauma from the accident"], explanation: "The secret ending reveals the car accident that is the true origin of Selene's loop, suggesting the entire planet may be her purgatory." },
      { id: "rtn_600_02", categoryId: "vg_returnal", tier: 600, prompt: "What does the name 'Atropos' reference in Greek mythology, and how does it connect to the game's themes?", answer: "Atropos is one of the three Fates (Moirai) — specifically the one who cuts the thread of life, representing death's inevitability", acceptableAnswers: ["Greek Fate who cuts life's thread", "One of the three Fates", "The Fate who cuts the thread of life"], explanation: "All three biome names reference the Moirai: Atropos (death), along with other mythological names, connecting the game to Greek fate and destiny." },
      { id: "rtn_600_03", categoryId: "vg_returnal", tier: 600, prompt: "What unique DualSense haptic feedback technique does Returnal use for its adaptive triggers that fundamentally changes gameplay?", answer: "Half-press for aim-down-sights, full-press for alt-fire — using the adaptive trigger's resistance midpoint as a gameplay mechanic", acceptableAnswers: ["Half-press vs full-press trigger", "Adaptive trigger midpoint for alt-fire", "Two-stage trigger mechanic"], explanation: "Returnal was the first game to use the DualSense adaptive trigger's pressure sensitivity as a core gameplay input rather than just feedback." }
    ]
  },
  {
    id: "vg_death_strand",
    group: "Video Games",
    name: "Death Stranding",
    culture: "universal",
    description: "Kojima's divisive masterpiece about connection, delivery, and rebuilding America",
    imageUrl: "",
    questions: [
      { id: "dst_200_01", categoryId: "vg_death_strand", tier: 200, prompt: "Who plays the protagonist Sam Porter Bridges, a delivery man reconnecting a fractured America?", answer: "Norman Reedus", explanation: "Norman Reedus plays Sam Bridges, a reclusive porter who must reconnect cities to the chiral network." },
      { id: "dst_200_02", categoryId: "vg_death_strand", tier: 200, prompt: "What are BTs (Beached Things), the ghostly entities that appear during timefall rain?", answer: "Stranded souls / entities from the realm of the dead that have become stuck in the world of the living", acceptableAnswers: ["Stranded souls", "Entities from the dead", "Ghosts stuck in the living world", "Beached Things"], explanation: "BTs are the souls of the dead unable to pass on, made visible by Sam's Bridge Baby and dangerous during timefall." },
      { id: "dst_200_03", categoryId: "vg_death_strand", tier: 200, prompt: "What is timefall, the unique weather phenomenon in the game?", answer: "Rain that rapidly ages anything it touches", acceptableAnswers: ["Rain that ages things", "Aging rain", "Rain that accelerates time"], explanation: "Timefall rapidly ages whatever it touches, rusting metal, decaying packages, and aging living organisms in seconds." },
      { id: "dst_400_01", categoryId: "vg_death_strand", tier: 400, prompt: "What is a Bridge Baby (BB), and why does Sam carry one?", answer: "A premature infant kept in a pod that connects to the 'other side,' allowing the user to detect BTs", acceptableAnswers: ["Baby that detects BTs", "Infant that senses the dead", "Premature baby in a pod for BT detection"], explanation: "BBs act as a bridge between the living and the dead, enabling their users to sense and avoid the otherwise invisible BTs." },
      { id: "dst_400_02", categoryId: "vg_death_strand", tier: 400, prompt: "What happens when a BT catches a living person and triggers a voidout?", answer: "A massive antimatter explosion occurs, creating a permanent crater — the fusion of living and dead matter causes annihilation", acceptableAnswers: ["Antimatter explosion", "Massive explosion creating a crater", "Voidout explosion"], explanation: "Voidouts are catastrophic explosions that destroyed entire cities, which is why cremation of the dead became essential." },
      { id: "dst_400_03", categoryId: "vg_death_strand", tier: 400, prompt: "What unique multiplayer mechanic allows players to help each other without directly interacting?", answer: "Asynchronous strand system — structures, ladders, bridges, and signs left by other players appear in your world", acceptableAnswers: ["Asynchronous multiplayer", "Shared structures", "Strand system", "Other players' structures appear"], explanation: "The 'strand' system embodies the game's theme of connection — you never meet other players but their contributions make your journey easier." },
      { id: "dst_600_01", categoryId: "vg_death_strand", tier: 600, prompt: "What real-world scientific concept does the 'Beach' draw from, specifically Schrödinger's cat and the many-worlds interpretation?", answer: "Each person has their own Beach (personal afterlife/transition space) based on quantum superposition — reality and death exist in superposition until observed", acceptableAnswers: ["Quantum superposition of death", "Personal afterlife via many-worlds", "Quantum Beach concept"], explanation: "The Beach represents a quantum state between life and death, drawing from real physics concepts to create the game's metaphysical framework." },
      { id: "dst_600_02", categoryId: "vg_death_strand", tier: 600, prompt: "What is the Last Stranding, and how does Amelie's role as an Extinction Entity connect to the game's six previous mass extinction events?", answer: "Amelie is the sixth Extinction Entity — each previous mass extinction was caused by an EE, and she must trigger the final one to end all life", acceptableAnswers: ["Amelie is sixth Extinction Entity", "Each extinction had an EE", "Final extinction entity"], explanation: "The game reframes Earth's mass extinctions as caused by Extinction Entities, with Amelie being the current one who must choose whether to end humanity." },
      { id: "dst_600_03", categoryId: "vg_death_strand", tier: 600, prompt: "What specific game design philosophy did Kojima coin to describe Death Stranding's genre, distinguishing it from 'shooter' games?", answer: "Strand game — a new genre focused on connection rather than combat", acceptableAnswers: ["Strand game", "Strand genre"], explanation: "Kojima coined 'strand game' to describe a genre where the core loop is about forming connections rather than destroying enemies." }
    ]
  },
  {
    id: "mv_villeneuve",
    group: "Movies",
    name: "Denis Villeneuve Films",
    culture: "universal",
    description: "The Quebecois director behind Arrival, Blade Runner 2049, and Dune",
    imageUrl: "",
    questions: [
      { id: "dvl_200_01", categoryId: "mv_villeneuve", tier: 200, prompt: "What 2016 sci-fi film starring Amy Adams explores how learning an alien language can change one's perception of time?", answer: "Arrival", explanation: "Arrival adapted Ted Chiang's 'Story of Your Life' and earned eight Oscar nominations." },
      { id: "dvl_200_02", categoryId: "mv_villeneuve", tier: 200, prompt: "What Frank Herbert adaptation did Villeneuve split into two films, with Part One releasing in 2021?", answer: "Dune", acceptableAnswers: ["Dune", "Dune: Part One"], explanation: "Villeneuve's Dune adaptation was the first to successfully translate the novel to screen, grossing over $400 million for Part One alone." },
      { id: "dvl_200_03", categoryId: "mv_villeneuve", tier: 200, prompt: "What Ridley Scott sequel did Villeneuve direct, starring Ryan Gosling as a replicant LAPD officer?", answer: "Blade Runner 2049", explanation: "Blade Runner 2049 was acclaimed as a rare worthy sequel, earning Roger Deakins his first Oscar for cinematography." },
      { id: "dvl_400_01", categoryId: "mv_villeneuve", tier: 400, prompt: "In Arrival, what is the Sapir-Whorf hypothesis, and how does it relate to Louise learning the heptapod language?", answer: "The idea that language shapes perception of reality — learning Heptapod B rewires Louise's brain to perceive time non-linearly", acceptableAnswers: ["Language shapes perception", "Language determines thought", "Sapir-Whorf hypothesis changes time perception"], explanation: "The film takes the linguistic relativity hypothesis to its extreme: learning the alien language literally changes how Louise experiences time." },
      { id: "dvl_400_02", categoryId: "mv_villeneuve", tier: 400, prompt: "What 2013 thriller features a father taking justice into his own hands when his daughter and her friend are abducted?", answer: "Prisoners", explanation: "Prisoners stars Hugh Jackman and Jake Gyllenhaal in an unflinching examination of how far a parent will go to protect their child." },
      { id: "dvl_400_03", categoryId: "mv_villeneuve", tier: 400, prompt: "In Blade Runner 2049, what does Officer K discover about his memories that drives the film's central mystery?", answer: "He discovers a memory of hiding a wooden horse that may mean he was born, not manufactured — suggesting he could be Deckard's child", acceptableAnswers: ["He might be born not made", "Wooden horse memory", "He could be Deckard's child"], explanation: "K's journey to discover whether he is the miracle child born of a replicant drives the emotional core of the film." },
      { id: "dvl_600_01", categoryId: "mv_villeneuve", tier: 600, prompt: "What specific visual approach did Bradford Young use as cinematographer on Arrival to create the film's muted, dreamlike quality?", answer: "Underexposed, low-contrast naturalistic photography with minimal artificial lighting, shooting at magic hour and in overcast conditions", acceptableAnswers: ["Underexposed naturalistic photography", "Low-contrast minimal lighting", "Deliberately underexposed"], explanation: "Young's approach was deliberately anti-spectacle for a sci-fi film, using darkness and muted tones to keep focus on the emotional and intellectual story." },
      { id: "dvl_600_02", categoryId: "mv_villeneuve", tier: 600, prompt: "What specific sandworm sound design technique did the Dune sound team use, combining real-world recordings?", answer: "Shifting sand recordings combined with processed whale sounds, tectonic plate movements, and drag racing engines", acceptableAnswers: ["Sand, whale sounds, and engines", "Processed natural and mechanical sounds", "Sand and whale recordings"], explanation: "The sound design team recorded actual shifting sand dunes, processed whale calls, and drag racing to create the sandworm's iconic presence." },
      { id: "dvl_600_03", categoryId: "mv_villeneuve", tier: 600, prompt: "What is the name of Villeneuve's early Quebecois film about a woman's search for her family's past in the Middle East, based on a Wajdi Mouawad play?", answer: "Incendies", explanation: "Incendies (2010) earned an Oscar nomination for Best Foreign Language Film and established Villeneuve's ability to handle complex, emotionally devastating narratives." }
    ]
  },
  {
    id: "his_pirates",
    group: "History & Culture",
    name: "The Golden Age of Piracy",
    culture: "universal",
    description: "The real history behind the Jolly Roger — 1650s to 1730s maritime lawlessness",
    imageUrl: "",
    questions: [
      { id: "pir_200_01", categoryId: "his_pirates", tier: 200, prompt: "What was Blackbeard's real name, and where was he finally killed in 1718?", answer: "Edward Teach (or Thatch), killed at Ocracoke Inlet, North Carolina", acceptableAnswers: ["Edward Teach", "Edward Thatch"], explanation: "Blackbeard was killed in a battle with Lieutenant Robert Maynard's forces, reportedly suffering five gunshot wounds and twenty sword cuts." },
      { id: "pir_200_02", categoryId: "his_pirates", tier: 200, prompt: "What pirate flag, featuring a skull and crossbones, became the universal symbol of piracy?", answer: "Jolly Roger", acceptableAnswers: ["Jolly Roger", "The Jolly Roger", "Skull and crossbones"], explanation: "The Jolly Roger was designed to terrify prey into surrendering without a fight, saving pirates from costly battles." },
      { id: "pir_200_03", categoryId: "his_pirates", tier: 200, prompt: "What Caribbean island port was known as the 'wickedest city on Earth' and served as a pirate haven until an earthquake destroyed it in 1692?", answer: "Port Royal, Jamaica", acceptableAnswers: ["Port Royal", "Port Royal Jamaica"], explanation: "Port Royal was a thriving pirate haven until a massive earthquake sent most of the city into the sea." },
      { id: "pir_400_01", categoryId: "his_pirates", tier: 400, prompt: "What democratic system did many pirate crews use, including written articles, elected captains, and compensation for injuries?", answer: "Pirate articles / pirate code / ship's articles", acceptableAnswers: ["Pirate articles", "Ship's articles", "Pirate code", "Articles of Agreement"], explanation: "Pirate ships were surprisingly democratic — crews voted on captains, divided loot fairly, and had written constitutions predating many national ones." },
      { id: "pir_400_02", categoryId: "his_pirates", tier: 400, prompt: "What was a 'letter of marque,' and how did it distinguish privateers from pirates?", answer: "A government license authorizing private ships to attack enemy vessels — privateers had legal permission while pirates did not", acceptableAnswers: ["Government license to attack enemy ships", "Legal permission to raid", "Government authorization for privateering"], explanation: "The line between pirate and privateer was often blurry — Sir Francis Drake was a hero to England and a pirate to Spain." },
      { id: "pir_400_03", categoryId: "his_pirates", tier: 400, prompt: "Who was Bartholomew 'Black Bart' Roberts, and why is he considered the most successful pirate of the Golden Age?", answer: "A Welsh pirate who captured over 400 ships between 1719-1722, more than any other pirate", acceptableAnswers: ["Welsh pirate who captured 400+ ships", "Most successful pirate capturing 400 ships", "Bartholomew Roberts"], explanation: "Roberts captured an estimated 400+ vessels in just three years, far surpassing Blackbeard's count, and was known for his strict crew discipline." },
      { id: "pir_600_01", categoryId: "his_pirates", tier: 600, prompt: "What was the 'Republic of Pirates' in Nassau, Bahamas, and which pirate leaders established it as a functioning anarchist state?", answer: "Benjamin Hornigold, Henry Jennings, and Charles Vane established Nassau as a pirate republic (~1706-1718) with its own governance and economy", acceptableAnswers: ["Hornigold and others in Nassau", "Nassau pirate republic", "Benjamin Hornigold's Nassau"], explanation: "The Republic of Pirates was a functioning society with elected leaders and economic systems, only ended when Woodes Rogers arrived as royal governor." },
      { id: "pir_600_02", categoryId: "his_pirates", tier: 600, prompt: "What was the Whydah Gally, and why was its 1984 discovery historically significant?", answer: "Formerly a slave ship captured by pirate Sam Bellamy; its 1984 discovery was the first authenticated pirate shipwreck ever found", acceptableAnswers: ["First authenticated pirate wreck", "Sam Bellamy's ship, first pirate wreck found", "First verified pirate shipwreck"], explanation: "The Whydah sank in 1717 off Cape Cod and was discovered by Barry Clifford, yielding over 200,000 artifacts and confirming many details of pirate life." },
      { id: "pir_600_03", categoryId: "his_pirates", tier: 600, prompt: "What role did Ching Shih play in piracy, and why is she considered the most powerful pirate in history?", answer: "She commanded over 1,800 ships and 80,000 pirates in the South China Sea (~1801-1810), creating a pirate confederation that defeated the Chinese navy", acceptableAnswers: ["Commanded 1800 ships and 80000 pirates", "Most powerful pirate, defeated Chinese navy", "Ching Shih's South China Sea confederation"], explanation: "Ching Shih's pirate confederation was so powerful that the Chinese government had to negotiate a truce, and she retired peacefully — a rarity for any pirate." }
    ]
  },
  {
    id: "sci_sleep",
    group: "Science & Nature",
    name: "The Science of Sleep",
    culture: "universal",
    description: "What happens when you close your eyes — the neuroscience of sleep and dreams",
    imageUrl: "",
    questions: [
      { id: "slp_200_01", categoryId: "sci_sleep", tier: 200, prompt: "What is REM sleep, and what happens to the body during this stage?", answer: "Rapid Eye Movement sleep — eyes move rapidly, brain is highly active, muscles are paralyzed, and most vivid dreaming occurs", acceptableAnswers: ["Rapid Eye Movement sleep", "REM stands for Rapid Eye Movement", "Stage with dreaming and paralysis"], explanation: "REM sleep was discovered in 1953 by Aserinsky and Kleitman, revealing that sleep is far more active than previously thought." },
      { id: "slp_200_02", categoryId: "sci_sleep", tier: 200, prompt: "What hormone, released by the pineal gland in response to darkness, helps regulate the sleep-wake cycle?", answer: "Melatonin", explanation: "Melatonin production increases in darkness and decreases with light exposure, helping synchronize the circadian rhythm." },
      { id: "slp_200_03", categoryId: "sci_sleep", tier: 200, prompt: "What is the approximate length of a complete sleep cycle, including all stages from light sleep to REM?", answer: "About 90 minutes", acceptableAnswers: ["90 minutes", "About 90 minutes", "Approximately 90 minutes"], explanation: "A typical night includes 4-6 complete cycles, with REM periods getting longer toward morning." },
      { id: "slp_400_01", categoryId: "sci_sleep", tier: 400, prompt: "What is the glymphatic system, discovered in 2012, and why is it important for brain health during sleep?", answer: "A waste-clearance system that flushes cerebrospinal fluid through the brain during deep sleep, removing toxic proteins including amyloid beta", acceptableAnswers: ["Brain waste clearance during sleep", "CSF flushing system", "Glymphatic waste removal"], explanation: "The glymphatic system is 10x more active during sleep, clearing metabolic waste including proteins linked to Alzheimer's disease." },
      { id: "slp_400_02", categoryId: "sci_sleep", tier: 400, prompt: "What is sleep paralysis, and why does it sometimes cause terrifying hallucinations?", answer: "The muscle atonia of REM sleep persists into waking consciousness, often accompanied by hypnagogic hallucinations because the brain is still partially in dream state", acceptableAnswers: ["REM paralysis during waking", "Muscle atonia persists while waking", "REM muscle paralysis while conscious"], explanation: "Sleep paralysis affects 8% of people and historically inspired supernatural explanations like succubi, the 'Old Hag,' and alien abduction accounts." },
      { id: "slp_400_03", categoryId: "sci_sleep", tier: 400, prompt: "What two competing processes regulate when you feel sleepy and awake, according to the two-process model of sleep?", answer: "Process S (sleep pressure/adenosine buildup) and Process C (circadian rhythm from the suprachiasmatic nucleus)", acceptableAnswers: ["Sleep pressure and circadian rhythm", "Process S and Process C", "Adenosine buildup and circadian clock"], explanation: "Process S (homeostatic sleep drive) builds pressure the longer you're awake, while Process C (circadian) follows a ~24-hour cycle regardless of sleep debt." },
      { id: "slp_600_01", categoryId: "sci_sleep", tier: 600, prompt: "What specific role do sleep spindles and sharp-wave ripples play in memory consolidation during NREM Stage 2 and 3?", answer: "Sleep spindles (thalamocortical bursts) and hippocampal sharp-wave ripples coordinate to replay and transfer memories from hippocampus to neocortex for long-term storage", acceptableAnswers: ["Memory replay and transfer", "Hippocampus to neocortex transfer", "Spindle-ripple coupling for memory consolidation"], explanation: "The precise temporal coupling of spindles and ripples during NREM sleep is now understood as the mechanism by which daily experiences are consolidated into permanent memories." },
      { id: "slp_600_02", categoryId: "sci_sleep", tier: 600, prompt: "What is fatal familial insomnia, and what prion mechanism causes it?", answer: "A prion disease caused by a mutation in the PRNP gene that destroys the thalamus, progressively eliminating the ability to sleep and causing death within 6-36 months", acceptableAnswers: ["Prion disease destroying the thalamus", "PRNP mutation destroying sleep ability", "Thalamic prion disease causing death from insomnia"], explanation: "FFI affects only about 40 families worldwide and demonstrates that sleep is literally essential for survival — total insomnia is invariably fatal." },
      { id: "slp_600_03", categoryId: "sci_sleep", tier: 600, prompt: "What is the relationship between slow-wave sleep and growth hormone secretion, and why is this clinically significant for children?", answer: "70-80% of daily growth hormone is secreted during slow-wave (N3) sleep, making sufficient deep sleep critical for childhood development", acceptableAnswers: ["Most growth hormone released during deep sleep", "70-80% of GH in slow-wave sleep", "Growth hormone secretion during N3"], explanation: "The pulsatile release of growth hormone during N3 sleep explains why chronic sleep deprivation in children can lead to growth disorders and developmental delays." }
    ]
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 80 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
