#!/usr/bin/env python3
"""Insert wave 73 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_atlanta",
    group: "tv",
    name: "Atlanta",
    culture: "american",
    description: "Earn, Paper Boi, and the surreal side of Atlanta's rap scene.",
    imageUrl: "",
    questions: [
      { id: "atl_200_01", categoryId: "tv_atlanta", tier: 200, prompt: "Who created, wrote, and stars in Atlanta as Earnest 'Earn' Marks?", answer: "Donald Glover", acceptableAnswers: ["Donald Glover", "Childish Gambino"], explanation: "Glover created the show and plays Earn, Paper Boi's cousin and manager." },
      { id: "atl_200_02", categoryId: "tv_atlanta", tier: 200, prompt: "What is Paper Boi's relationship to Earn, and what is he trying to become?", answer: "Paper Boi (Alfred) is Earn's cousin, and he's a rapper trying to break into the Atlanta music scene", acceptableAnswers: ["Earn's cousin, aspiring rapper", "Cousin who is a rapper"], explanation: "Brian Tyree Henry's Paper Boi anchors the show's exploration of the music industry." },
      { id: "atl_200_03", categoryId: "tv_atlanta", tier: 200, prompt: "What city and its culture is the show centered around?", answer: "Atlanta, Georgia — specifically its Black culture, rap scene, and social dynamics", acceptableAnswers: ["Atlanta", "Atlanta Georgia"], explanation: "The show captures Atlanta's unique cultural landscape unlike any other series." },
      { id: "atl_400_01", categoryId: "tv_atlanta", tier: 400, prompt: "What makes Darius (played by LaKeith Stanfield) one of TV's most unique characters?", answer: "He's a philosophical stoner who makes surreal observations and non-sequiturs that somehow always turn out to be profound or literally true", acceptableAnswers: ["Philosophical stoner with surreal insights", "Surreal philosopher character", "Weird observations that are actually deep"], explanation: "Darius exists in his own reality, often seeing truths others miss." },
      { id: "atl_400_02", categoryId: "tv_atlanta", tier: 400, prompt: "What genre-defying episode style does Atlanta use, mixing comedy with horror, surrealism, and social commentary?", answer: "The show blends genres freely — episodes can shift from comedy to horror to magical realism within minutes, creating a style often called 'Twin Peaks with rappers'", acceptableAnswers: ["Genre-blending surrealism", "Twin Peaks with rappers", "Comedy mixed with horror and surrealism"], explanation: "Atlanta refuses to stay in one genre, making each episode unpredictable." },
      { id: "atl_400_03", categoryId: "tv_atlanta", tier: 400, prompt: "In the 'Teddy Perkins' episode, what horror-inspired standalone story shocked viewers and critics?", answer: "A deeply unsettling episode where Darius visits a reclusive musician (resembling a decayed Michael Jackson figure) in a mansion — Glover himself plays Teddy in whiteface prosthetics, creating a haunting meditation on fame, race, and abuse", acceptableAnswers: ["Horror episode with Michael Jackson-like figure", "Donald Glover in whiteface as creepy recluse", "Teddy Perkins mansion horror episode"], explanation: "Teddy Perkins is considered one of the greatest TV episodes of the decade." },
      { id: "atl_600_01", categoryId: "tv_atlanta", tier: 600, prompt: "What is the significance of Atlanta's Season 3 European episodes that don't feature the main cast, and how did audiences react?", answer: "Several Season 3 episodes are standalone stories set in Europe with no regular characters — exploring race, reparations, and identity through allegorical horror. Many fans were divided, some calling them the show's best work, others wanting the main characters back", acceptableAnswers: ["Standalone European episodes without main cast", "Allegorical episodes dividing fans", "European anthology episodes about race"], explanation: "Glover used his platform to tell stories he felt were important, regardless of audience expectations." },
      { id: "atl_600_02", categoryId: "tv_atlanta", tier: 600, prompt: "How does Atlanta's depiction of the music industry differ from other shows about hip-hop, and what does Donald Glover say it's really about?", answer: "Glover has said Atlanta is about 'what it feels like to be Black' — the music industry is a lens, not the subject. Unlike Empire or other shows, it depicts the mundane grind, absurdity, and systemic obstacles rather than glamorizing the hustle", acceptableAnswers: ["About being Black, not about rap", "Uses rap as lens for Black experience", "Mundane reality vs glamorized hustle"], explanation: "Atlanta subverts every hip-hop show convention by making the experience, not the aspiration, the story." },
      { id: "atl_600_03", categoryId: "tv_atlanta", tier: 600, prompt: "What does the recurring 'Florida Man' motif and the invisible car represent in Atlanta's surrealist worldbuilding?", answer: "Atlanta presents surreal events as unremarkable — an invisible car, an alligator in a house, a Black Justin Bieber — to show that Black life in America already contains daily absurdities that feel surreal. The surrealism IS realism from a different perspective", acceptableAnswers: ["Surreal events as everyday Black experience", "Absurdity as realistic depiction", "Surrealism representing actual lived experience"], explanation: "What seems surreal to outside viewers is Atlanta's way of depicting how bizarre everyday life can feel." },
    ],
  },
  {
    id: "tv_bojack",
    group: "tv",
    name: "BoJack Horseman",
    culture: "american",
    description: "A washed-up sitcom horse confronts addiction, depression, and Hollywood's dark side.",
    imageUrl: "",
    questions: [
      { id: "bjh_200_01", categoryId: "tv_bojack", tier: 200, prompt: "What kind of animal is BoJack Horseman?", answer: "A horse", acceptableAnswers: ["Horse"], explanation: "BoJack is an anthropomorphic horse living in a world where humans and animal-people coexist." },
      { id: "bjh_200_02", categoryId: "tv_bojack", tier: 200, prompt: "What was the name of BoJack's famous 1990s sitcom that he can't move past?", answer: "Horsin' Around", acceptableAnswers: ["Horsin Around", "Horsin' Around"], explanation: "BoJack's identity is trapped in his former sitcom glory." },
      { id: "bjh_200_03", categoryId: "tv_bojack", tier: 200, prompt: "Despite being an animated comedy, what serious topics does BoJack Horseman deal with throughout its run?", answer: "Depression, addiction, trauma, toxic relationships, and the cycle of self-destructive behavior", acceptableAnswers: ["Depression and addiction", "Mental health and addiction", "Depression addiction trauma"], explanation: "The show is one of television's most honest depictions of mental health struggles." },
      { id: "bjh_400_01", categoryId: "tv_bojack", tier: 400, prompt: "What is Todd Chavez's running gag about his sexuality, and why was it groundbreaking for television?", answer: "Todd is asexual — one of the first major TV characters to be explicitly ace. The show handles his identity with care and specificity rather than as a punchline", acceptableAnswers: ["Todd is asexual", "Asexual representation", "First major asexual TV character"], explanation: "Todd's asexuality is treated as a genuine identity, not a joke or a problem to be fixed." },
      { id: "bjh_400_02", categoryId: "tv_bojack", tier: 400, prompt: "What is the 'underwater episode' (Fish Out of Water), and why is it considered a masterpiece of visual storytelling?", answer: "An almost entirely dialogue-free episode where BoJack attends an underwater film festival — the story is told purely through animation and physical comedy, ending with a devastating emotional gut-punch", acceptableAnswers: ["Silent underwater episode", "No-dialogue underwater episode", "Wordless episode at underwater festival"], explanation: "Fish Out of Water proved the show could be profound without saying a single word." },
      { id: "bjh_400_03", categoryId: "tv_bojack", tier: 400, prompt: "What is the significance of the phrase 'It gets easier. Every day it gets a little easier. But you gotta do it every day — that's the hard part'?", answer: "A jogger tells BoJack this after he starts running — it becomes the show's thesis about recovery: improvement isn't a moment, it's a daily practice with no finish line", acceptableAnswers: ["Recovery is daily practice", "Jogger's advice about daily effort", "No finish line, just daily work"], explanation: "This quote encapsulates the show's mature, unsentimental view of self-improvement." },
      { id: "bjh_600_01", categoryId: "tv_bojack", tier: 600, prompt: "What happens in 'Free Churro' (Season 5), and why is a 25-minute monologue considered one of TV's greatest episodes?", answer: "The entire episode is BoJack delivering his mother's eulogy — a single unbroken monologue that shifts between comedy, grief, anger, and devastating honesty about their relationship. It ends with the reveal that he's at the wrong funeral", acceptableAnswers: ["Full episode eulogy monologue, wrong funeral", "25-minute eulogy that ends at wrong funeral", "BoJack's mother's eulogy, entire episode"], explanation: "Free Churro is essentially a one-man show that captures the complexity of grieving a parent who hurt you." },
      { id: "bjh_600_02", categoryId: "tv_bojack", tier: 600, prompt: "In 'The View from Halfway Down,' what is actually happening to BoJack during the dinner party with dead characters?", answer: "BoJack is dying from drowning/overdose in his pool — the episode is his near-death experience. Each dead character performs their 'act' before walking through a door (death). The poem 'The View from Halfway Down' is about regretting suicide mid-fall", acceptableAnswers: ["He's drowning/dying, it's a death vision", "Near-death experience while drowning", "Dying in pool, dinner is death sequence"], explanation: "The episode — BoJack's most critically acclaimed — is a harrowing depiction of dying." },
      { id: "bjh_600_03", categoryId: "tv_bojack", tier: 600, prompt: "How does the series finale handle BoJack's fate differently than most shows about addiction, and why did it divide fans?", answer: "BoJack survives but faces real consequences — prison, lost friendships, Diane moving on. There's no redemption arc or dramatic death. The final scene shows BoJack and Diane sitting in silence on a rooftop, their friendship likely over. Some fans wanted catharsis; the show denied it because that's how life works", acceptableAnswers: ["He survives but loses everything, no redemption", "No cathartic ending, just consequences", "Realistic consequences instead of dramatic resolution"], explanation: "The show refuses to give BoJack (or the audience) the satisfying ending addiction stories usually provide." },
    ],
  },
  {
    id: "mu_kanye",
    group: "music",
    name: "Kanye West (Music Legacy)",
    culture: "american",
    description: "From chipmunk soul to Yeezus — the albums that reshaped hip-hop.",
    imageUrl: "",
    questions: [
      { id: "kny_200_01", categoryId: "mu_kanye", tier: 200, prompt: "What was Kanye West's debut album that challenged gangsta rap's dominance with soulful, introspective hip-hop?", answer: "The College Dropout", acceptableAnswers: ["College Dropout", "The College Dropout"], explanation: "Released in 2004, it proved you didn't need a gangsta persona to succeed in hip-hop." },
      { id: "kny_200_02", categoryId: "mu_kanye", tier: 200, prompt: "Before becoming a rapper, what role did Kanye play in the music industry, producing hits for Jay-Z and others?", answer: "He was a producer — he produced beats for Jay-Z's 'The Blueprint' and many other major albums", acceptableAnswers: ["Producer", "Beat producer", "He was a producer for Jay-Z"], explanation: "Kanye had to fight to be taken seriously as a rapper because labels only wanted him as a producer." },
      { id: "kny_200_03", categoryId: "mu_kanye", tier: 200, prompt: "What production technique defined Kanye's early sound, involving sped-up vocal samples from old soul records?", answer: "Chipmunk soul — pitching up soul samples to create high-pitched vocal loops", acceptableAnswers: ["Chipmunk soul", "Sped-up soul samples", "Pitched-up soul vocals"], explanation: "Kanye popularized (though didn't invent) the technique of speeding up soul samples." },
      { id: "kny_400_01", categoryId: "mu_kanye", tier: 400, prompt: "What concept album features Kanye singing through Auto-Tune about heartbreak after his mother's death and a broken engagement?", answer: "808s & Heartbreak", acceptableAnswers: ["808s and Heartbreak", "808s & Heartbreak"], explanation: "808s pioneered the emotional Auto-Tune style that influenced Drake, Kid Cudi, and modern hip-hop." },
      { id: "kny_400_02", categoryId: "mu_kanye", tier: 400, prompt: "What album is considered Kanye's magnum opus, featuring elaborate orchestration, and is frequently ranked as one of the greatest hip-hop albums ever?", answer: "My Beautiful Dark Twisted Fantasy", acceptableAnswers: ["MBDTF", "My Beautiful Dark Twisted Fantasy"], explanation: "MBDTF was Kanye's response to the Taylor Swift VMA incident — a maximalist masterpiece." },
      { id: "kny_400_03", categoryId: "mu_kanye", tier: 400, prompt: "What abrasive 2013 album marked Kanye's most experimental and confrontational turn, with industrial beats and screamed vocals?", answer: "Yeezus", explanation: "Yeezus stripped away melody for aggression, influenced by industrial and punk music." },
      { id: "kny_600_01", categoryId: "mu_kanye", tier: 600, prompt: "How did '808s & Heartbreak' fundamentally change the trajectory of hip-hop, despite being considered a failure at release?", answer: "It proved rappers could be emotionally vulnerable, use singing and Auto-Tune, and make sad music — directly spawning Drake's career, Kid Cudi's sound, and the entire emo-rap wave. Without 808s, modern hip-hop sounds completely different", acceptableAnswers: ["Created emotional hip-hop, spawned Drake and emo-rap", "Made vulnerability acceptable in rap", "Birthed emotional rap subgenre"], explanation: "808s was ahead of its time — its influence only became clear years later as its descendants dominated charts." },
      { id: "kny_600_02", categoryId: "mu_kanye", tier: 600, prompt: "What was the creative process behind 'My Beautiful Dark Twisted Fantasy' that involved Kanye isolating in Hawaii with rotating collaborators?", answer: "Kanye rented a studio compound in Hawaii and flew in artists (Pusha T, Kid Cudi, Bon Iver, Nicki Minaj, etc.) for intensive collaborative sessions — he'd play tracks on repeat for days, constantly revising. The process was part creative commune, part obsessive perfectionism", acceptableAnswers: ["Hawaii studio compound with rotating artists", "Intensive Hawaii sessions with many collaborators", "Isolated Hawaii recording with rotating guests"], explanation: "The Hawaiian sessions produced one of the most meticulously crafted albums in hip-hop history." },
      { id: "kny_600_03", categoryId: "mu_kanye", tier: 600, prompt: "What is the 'Runaway' film and its 35-minute music video, and how does the toast scene function as meta-commentary?", answer: "A short film set to MBDTF tracks where Kanye's character harbors a fallen phoenix (representing his public image). In the 'Runaway' performance, he toasts 'to the douchebags' and 'to the assholes' — simultaneously apologizing for and embracing his public persona, acknowledging he can't separate art from controversy", acceptableAnswers: ["Short film with toast to douchebags as self-commentary", "Phoenix metaphor film with self-aware toast", "35-min film toasting to his own villainy"], explanation: "The toast scene is Kanye at his most self-aware — weaponizing his villain status into art." },
    ],
  },
  {
    id: "mu_radiohead",
    group: "music",
    name: "Radiohead",
    culture: "universal",
    description: "OK Computer to Kid A — the band that made alienation beautiful.",
    imageUrl: "",
    questions: [
      { id: "rdh_200_01", categoryId: "mu_radiohead", tier: 200, prompt: "What 1997 Radiohead album, themed around technology and modern alienation, is often ranked as one of the greatest albums ever?", answer: "OK Computer", explanation: "OK Computer anticipated the anxieties of the internet age before most people were online." },
      { id: "rdh_200_02", categoryId: "mu_radiohead", tier: 200, prompt: "What early Radiohead hit features the lyric 'I'm a creep, I'm a weirdo'?", answer: "Creep", explanation: "Despite being their biggest hit, Radiohead grew to hate playing 'Creep' live." },
      { id: "rdh_200_03", categoryId: "mu_radiohead", tier: 200, prompt: "Who is Radiohead's lead singer, known for his distinctive falsetto and anxious stage presence?", answer: "Thom Yorke", acceptableAnswers: ["Yorke", "Thom Yorke"], explanation: "Yorke's voice and lyrics define Radiohead's emotional landscape." },
      { id: "rdh_400_01", categoryId: "mu_radiohead", tier: 400, prompt: "What radical shift did Radiohead make with 'Kid A' (2000) that shocked fans expecting another guitar album?", answer: "They abandoned conventional rock for electronic music, ambient textures, and experimental production — influenced by Aphex Twin and Autechre rather than guitar bands", acceptableAnswers: ["Shifted to electronic/experimental", "Abandoned guitars for electronics", "Electronic experimental departure"], explanation: "Kid A was initially divisive but is now considered one of the most important albums of the 2000s." },
      { id: "rdh_400_02", categoryId: "mu_radiohead", tier: 400, prompt: "What innovative release strategy did Radiohead use for 'In Rainbows' (2007) that challenged the music industry?", answer: "They released it as a 'pay what you want' download — fans could legally download the album for any price, including free", acceptableAnswers: ["Pay what you want", "Name your own price download", "Pay what you want digital release"], explanation: "The pay-what-you-want model made headlines and sparked debate about the future of music sales." },
      { id: "rdh_400_03", categoryId: "mu_radiohead", tier: 400, prompt: "What song from OK Computer features a computerized voice singing and is about car crash trauma?", answer: "Fitter Happier", acceptableAnswers: ["Fitter Happier"], explanation: "A text-to-speech voice reads a list of modern life aspirations, creating one of the most unsettling tracks in rock." },
      { id: "rdh_600_01", categoryId: "mu_radiohead", tier: 600, prompt: "What is the connection between the album art of 'Kid A' and 'Amnesiac,' and how were these albums recorded?", answer: "Both were recorded during the same sessions (1999-2000) and share a visual aesthetic by Stanley Donwood — they're essentially a double album split into two releases with different moods: Kid A is more electronic/ambient, Amnesiac more jazz-influenced and darker", acceptableAnswers: ["Same sessions split into two albums", "Twin albums from one recording period", "Recorded together, split into different moods"], explanation: "The two albums represent different facets of the same creative explosion." },
      { id: "rdh_600_02", categoryId: "mu_radiohead", tier: 600, prompt: "What happened during the stage collapse at Radiohead's Toronto concert in 2012, and how did it affect the band?", answer: "The stage roof collapsed before the show, killing drum technician Scott Johnson. The band was devastated; Thom Yorke was particularly affected. Criminal charges were filed but controversially dropped, leading the band to publicly criticize the justice system", acceptableAnswers: ["Stage collapsed killing drum tech", "Scott Johnson killed in stage collapse", "Crew member died, charges dropped"], explanation: "The tragedy deeply affected the band and highlighted safety issues in live event production." },
      { id: "rdh_600_03", categoryId: "mu_radiohead", tier: 600, prompt: "What is Jonny Greenwood's parallel career outside Radiohead, and how has it influenced the band's later sound?", answer: "Greenwood became an acclaimed film composer (There Will Be Blood, Phantom Thread, The Power of the Dog — multiple Oscar nominations) — his orchestral and avant-garde film scoring feeds back into Radiohead's increasingly cinematic arrangements", acceptableAnswers: ["Film composer for Paul Thomas Anderson", "Oscar-nominated film scoring career", "Film scores for There Will Be Blood etc."], explanation: "Greenwood's dual career as rock guitarist and orchestral composer makes him one of music's most versatile artists." },
    ],
  },
  {
    id: "vg_last_of_us",
    group: "video_games",
    name: "The Last of Us",
    culture: "american",
    description: "Joel and Ellie — survival, sacrifice, and the cost of love in a broken world.",
    imageUrl: "",
    questions: [
      { id: "tlu_200_01", categoryId: "vg_last_of_us", tier: 200, prompt: "What type of infection has devastated civilization in The Last of Us?", answer: "A fungal infection (Cordyceps) that turns humans into aggressive, zombie-like creatures", acceptableAnswers: ["Cordyceps fungus", "Fungal infection", "Cordyceps brain infection"], explanation: "The game's Cordyceps is based on a real parasitic fungus that controls insect behavior." },
      { id: "tlu_200_02", categoryId: "vg_last_of_us", tier: 200, prompt: "What is the relationship between Joel and Ellie, the game's two main characters?", answer: "Joel is a smuggler tasked with escorting Ellie, a teenager who is immune to the Cordyceps infection, across the country", acceptableAnswers: ["Smuggler and immune girl", "Joel escorts immune Ellie", "Protector and immune teenager"], explanation: "Their father-daughter bond that develops over the journey is the emotional core of the series." },
      { id: "tlu_200_03", categoryId: "vg_last_of_us", tier: 200, prompt: "What devastating event in the game's opening sets Joel on his path?", answer: "Joel's daughter Sarah is shot and killed by a soldier during the initial outbreak", acceptableAnswers: ["His daughter Sarah dies", "Sarah is killed", "Daughter shot by soldier"], explanation: "Sarah's death in the prologue establishes Joel's emotional damage and his eventual bond with Ellie." },
      { id: "tlu_400_01", categoryId: "vg_last_of_us", tier: 400, prompt: "What are the different stages of Cordyceps infection, from Runner to the terrifying Bloater?", answer: "Runner (recently infected) → Stalker → Clicker (blind, uses echolocation, signature clicking sound) → Bloater (heavily armored, throws acid)", acceptableAnswers: ["Runner Stalker Clicker Bloater", "Four stages from Runner to Bloater"], explanation: "The Clickers' distinctive clicking sound and one-hit kills make them the most feared enemy." },
      { id: "tlu_400_02", categoryId: "vg_last_of_us", tier: 400, prompt: "What controversial decision does Joel make at the end of the first game that defines his character?", answer: "He kills the Firefly surgeons to save Ellie from a surgery that would create a vaccine but kill her — then lies to Ellie about what happened", acceptableAnswers: ["Kills doctors to save Ellie, lies about it", "Stops the vaccine surgery to save Ellie", "Saves Ellie from fatal surgery and lies"], explanation: "Joel chooses one life over potentially saving humanity — the moral ambiguity defines the series." },
      { id: "tlu_400_03", categoryId: "vg_last_of_us", tier: 400, prompt: "In Part II, what event at the beginning drives Ellie's story and the game's central theme of revenge?", answer: "Joel is tortured and beaten to death by Abby (whose father was the surgeon Joel killed), while Ellie is forced to watch", acceptableAnswers: ["Joel is killed by Abby", "Abby kills Joel", "Joel beaten to death by Abby"], explanation: "Joel's brutal murder sets Ellie on a revenge journey that consumes and nearly destroys her." },
      { id: "tlu_600_01", categoryId: "vg_last_of_us", tier: 600, prompt: "Why was The Last of Us Part II's decision to make players play as Abby — Joel's killer — so controversial, and what was Naughty Dog's artistic intent?", answer: "After spending hours wanting to kill Abby, players are forced to play as her for ~10 hours, seeing her perspective and humanizing her. Naughty Dog wanted to challenge the player's desire for revenge by making them empathize with the 'enemy' — many players refused to accept this, while others called it the medium's most mature storytelling", acceptableAnswers: ["Forced empathy with antagonist divided players", "Playing as Joel's killer challenged revenge desire", "Made players humanize the villain"], explanation: "The game weaponizes player empathy against their own desire for vengeance." },
      { id: "tlu_600_02", categoryId: "vg_last_of_us", tier: 600, prompt: "What does Ellie's decision at the end of Part II — releasing Abby at the last moment — cost her, and what does it mean?", answer: "Ellie lets Abby go after nearly drowning her, breaking the revenge cycle. But she returns home to find Dina has left, she can't play guitar anymore (lost fingers), and she's alone. She chose mercy but lost everything she was fighting to protect — revenge took everything regardless", acceptableAnswers: ["Loses everything despite showing mercy", "Dina leaves, can't play guitar, alone", "Mercy breaks cycle but costs her everything"], explanation: "The ending argues that revenge destroys the avenger whether they complete it or not." },
      { id: "tlu_600_03", categoryId: "vg_last_of_us", tier: 600, prompt: "What was the massive 2020 leak controversy around Part II, and how did it affect the game's reception?", answer: "Major plot points (Joel's death, playing as Abby) leaked weeks before release, causing massive online backlash. The game was review-bombed before release. Despite the controversy, it won Game of the Year and sold over 10 million copies — but it remains one of gaming's most divisive titles", acceptableAnswers: ["Plot leaked, review bombed, still won GOTY", "Pre-release leaks caused backlash despite critical success", "Joel death leaked, divided community"], explanation: "The leak created a unique situation where many judged the game's story without experiencing its execution." },
    ],
  },
  {
    id: "vg_undertale",
    group: "video_games",
    name: "Undertale",
    culture: "universal",
    description: "The RPG where no one has to die — or where everyone does.",
    imageUrl: "",
    questions: [
      { id: "utl_200_01", categoryId: "vg_undertale", tier: 200, prompt: "What is the central moral mechanic of Undertale that makes it different from other RPGs?", answer: "You can complete the entire game without killing anyone — every enemy can be spared through non-violent actions", acceptableAnswers: ["No killing required", "Spare everyone", "Pacifist option for all enemies"], explanation: "Undertale's ACT/MERCY system turns combat into a puzzle of empathy." },
      { id: "utl_200_02", categoryId: "vg_undertale", tier: 200, prompt: "Who is the first character you meet in Undertale who teaches you about the game's mechanics?", answer: "Flowey (the flower)", acceptableAnswers: ["Flowey", "Flowey the Flower"], explanation: "Flowey's 'friendliness pellets' teach you that Undertale will subvert your expectations." },
      { id: "utl_200_03", categoryId: "vg_undertale", tier: 200, prompt: "Who is the goat-like character who acts as a motherly protector at the beginning of the game?", answer: "Toriel", explanation: "Toriel is the first boss you must choose to fight or spare — setting the game's moral tone." },
      { id: "utl_400_01", categoryId: "vg_undertale", tier: 400, prompt: "What are the skeleton brothers named, and what font are they associated with?", answer: "Sans (Comic Sans font) and Papyrus (Papyrus font) — each speaks in their respective font", acceptableAnswers: ["Sans and Papyrus", "Sans in Comic Sans, Papyrus in Papyrus"], explanation: "Sans is laid-back and punny; Papyrus is enthusiastic and wants to capture a human." },
      { id: "utl_400_02", categoryId: "vg_undertale", tier: 400, prompt: "What are the three main routes in Undertale, and how do they differ?", answer: "Neutral (some kills), Pacifist (no kills, befriend everyone), and Genocide (kill everything) — each gives a radically different story and ending", acceptableAnswers: ["Neutral Pacifist Genocide", "Three routes based on killing choices", "Kill none, kill some, kill all"], explanation: "The three routes make Undertale essentially three different games in terms of story and tone." },
      { id: "utl_400_03", categoryId: "vg_undertale", tier: 400, prompt: "What happens during the Sans boss fight on the Genocide route, and why is it so difficult?", answer: "Sans is the final boss of the Genocide route — he breaks RPG conventions by dodging your attacks, attacking during menus, and cheating. He knows you're a murderer because he's aware of the game's save/load system", acceptableAnswers: ["Sans breaks game rules, hardest boss", "He dodges and cheats, knows about saves", "Convention-breaking final genocide boss"], explanation: "Sans's fight is considered one of the hardest in gaming because he refuses to play fair." },
      { id: "utl_600_01", categoryId: "vg_undertale", tier: 600, prompt: "What permanent change does completing the Genocide route make to all future playthroughs, even after deleting save data?", answer: "The game modifies a persistent file that survives save deletion — all future True Pacifist endings are tainted with a horrifying final image showing the player character with demon eyes. The game remembers your sins and punishes you for trying to undo them", acceptableAnswers: ["Permanent file taints future pacifist endings", "Game permanently remembers genocide", "Can never truly get good ending again"], explanation: "Undertale comments on the player's desire to 'have it both ways' by making genocide permanent." },
      { id: "utl_600_02", categoryId: "vg_undertale", tier: 600, prompt: "Who is W.D. Gaster, and how does this hidden character connect to Undertale's meta-narrative?", answer: "A mysterious scientist who was the previous Royal Scientist before Alphys — he fell into his own creation and was scattered across time and space. He can only be encountered through rare events tied to a 'fun value' RNG seed, and his existence is fragmented across hidden rooms and corrupted data", acceptableAnswers: ["Hidden scientist scattered across time/space", "Previous Royal Scientist in hidden rooms", "Fragmented character accessed through fun values"], explanation: "Gaster exists in Undertale's code as a meta-character who may be aware of the game itself." },
      { id: "utl_600_03", categoryId: "vg_undertale", tier: 600, prompt: "How does Toby Fox use the concept of 'DETERMINATION' as both an in-game mechanic and a thematic statement about RPGs?", answer: "DETERMINATION is literally the power to save and reload — it's why the player can try again after dying. The game makes this a plot point: Flowey had determination too and used saves to manipulate everyone. Undertale argues that the player's ability to save/load is a form of godlike power that most games never question", acceptableAnswers: ["Save/load power as plot device and RPG commentary", "Determination = save ability, game questions that power", "Save system is literal in-universe power"], explanation: "Undertale turns a basic game mechanic (saving) into its central philosophical question." },
    ],
  },
  {
    id: "mv_tarantino_deep",
    group: "movies",
    name: "Tarantino Deep Cuts",
    culture: "american",
    description: "Beyond Pulp Fiction — dialogue, homage, and the Tarantino cinematic universe.",
    imageUrl: "",
    questions: [
      { id: "tqd_200_01", categoryId: "mv_tarantino_deep", tier: 200, prompt: "What 1994 Quentin Tarantino film tells interconnected crime stories in non-linear order and stars John Travolta and Samuel L. Jackson?", answer: "Pulp Fiction", explanation: "Pulp Fiction's non-linear storytelling and sharp dialogue revolutionized independent cinema." },
      { id: "tqd_200_02", categoryId: "mv_tarantino_deep", tier: 200, prompt: "What two-part martial arts revenge film stars Uma Thurman as 'The Bride'?", answer: "Kill Bill", acceptableAnswers: ["Kill Bill Volume 1 and 2", "Kill Bill"], explanation: "Kill Bill is Tarantino's love letter to martial arts, spaghetti westerns, and exploitation cinema." },
      { id: "tqd_200_03", categoryId: "mv_tarantino_deep", tier: 200, prompt: "What WWII Tarantino film features a squad of Jewish-American soldiers hunting Nazis in occupied France?", answer: "Inglourious Basterds", acceptableAnswers: ["Inglourious Basterds"], explanation: "The intentional misspelling is Tarantino's — the film features Christoph Waltz's Oscar-winning performance." },
      { id: "tqd_400_01", categoryId: "mv_tarantino_deep", tier: 400, prompt: "What connects all Tarantino films into a shared universe — including the fictional brands and character relationships?", answer: "All Tarantino films share a universe: Red Apple cigarettes, Big Kahuna Burger, and character connections (e.g., Vic Vega from Reservoir Dogs and Vincent Vega from Pulp Fiction are brothers)", acceptableAnswers: ["Shared brands and character connections", "Red Apple cigarettes and Vega brothers", "Connected universe with shared brands"], explanation: "Tarantino has two universes: the 'real' one and the 'movie-within-a-movie' one that characters in the real one watch." },
      { id: "tqd_400_02", categoryId: "mv_tarantino_deep", tier: 400, prompt: "What is the 'trunk shot' — Tarantino's signature camera angle used across almost all his films?", answer: "A low-angle shot looking up from inside an open car trunk as characters look down — first used in Reservoir Dogs and repeated in nearly every Tarantino film", acceptableAnswers: ["Looking up from inside car trunk", "Low-angle from trunk", "Camera in trunk looking up"], explanation: "The trunk shot has become one of cinema's most recognizable directorial signatures." },
      { id: "tqd_400_03", categoryId: "mv_tarantino_deep", tier: 400, prompt: "In 'Inglourious Basterds,' what makes the opening scene at the dairy farmer's house considered one of the greatest scenes in film?", answer: "A 20-minute conversation between Hans Landa and the farmer, entirely in French, slowly building tension as Landa reveals he knows Jewish families are hidden beneath the floor — Christoph Waltz controls the scene with terrifying charm", acceptableAnswers: ["20-minute tension scene with Landa at farmhouse", "Hans Landa interrogation at dairy farm", "Slow-build scene revealing hidden Jews"], explanation: "The scene demonstrates Tarantino's mastery of dialogue-as-suspense." },
      { id: "tqd_600_01", categoryId: "mv_tarantino_deep", tier: 600, prompt: "What is Tarantino's stated plan for his career, and why does the number 10 matter?", answer: "Tarantino has said he will only direct 10 films total and then retire — he believes directors get worse with age and wants to quit while ahead. 'Once Upon a Time in Hollywood' was his 9th; 'The Movie Critic' was announced then shelved as his potential 10th", acceptableAnswers: ["Only 10 films then retire", "Retirement after 10 films", "10-film career limit"], explanation: "Whether he'll actually stop is debated, but the self-imposed limit reflects his philosophy about artistic decline." },
      { id: "tqd_600_02", categoryId: "mv_tarantino_deep", tier: 600, prompt: "What is the 'Sicilian scene' in 'True Romance' (written by Tarantino, directed by Tony Scott), and why is it considered a masterclass in screenwriting?", answer: "Dennis Hopper's character, knowing he's about to be killed by the mob, deliberately insults Sicilians with a false story about their Moorish ancestry to provoke Christopher Walken into killing him quickly — he turns his death into an act of defiance to protect his son", acceptableAnswers: ["Hopper insults Walken to provoke quick death", "Sicilian ancestry monologue to protect his son", "Suicidal insult scene to save his son"], explanation: "The scene is Tarantino's purest demonstration of how dialogue can be more violent than any gunfight." },
      { id: "tqd_600_03", categoryId: "mv_tarantino_deep", tier: 600, prompt: "In 'Once Upon a Time in Hollywood,' how does Tarantino's alternate ending to the Manson murders function as a statement about cinema's relationship to real-world violence?", answer: "Instead of murdering Sharon Tate, the Manson family members accidentally enter Rick Dalton's house and are violently killed by Dalton and Cliff Booth — Tarantino uses cinema to 'save' Tate, arguing that movies can create justice that reality denied. It echoes Inglourious Basterds' alternate WWII ending", acceptableAnswers: ["Manson family killed instead of Tate", "Cinema rewrites history to save Tate", "Movies create justice reality denied"], explanation: "Tarantino's revisionist history argues that cinema is powerful enough to rewrite our worst tragedies." },
    ],
  },
  {
    id: "his_espionage",
    group: "history",
    name: "Spies & Espionage",
    culture: "universal",
    description: "Dead drops, double agents, and the shadow wars that shaped history.",
    imageUrl: "",
    questions: [
      { id: "esp_200_01", categoryId: "his_espionage", tier: 200, prompt: "What British intelligence agency is known as MI6, and what is its more famous fictional agent?", answer: "The Secret Intelligence Service (SIS) — James Bond is its most famous fictional member", acceptableAnswers: ["MI6, James Bond", "Secret Intelligence Service, 007"], explanation: "Ian Fleming, Bond's creator, was himself a naval intelligence officer." },
      { id: "esp_200_02", categoryId: "his_espionage", tier: 200, prompt: "What American intelligence agency, created in 1947, conducts covert operations and intelligence gathering worldwide?", answer: "The CIA (Central Intelligence Agency)", acceptableAnswers: ["CIA", "Central Intelligence Agency"], explanation: "The CIA grew out of the WWII-era Office of Strategic Services (OSS)." },
      { id: "esp_200_03", categoryId: "his_espionage", tier: 200, prompt: "What was the KGB, and which country did it serve?", answer: "The Soviet Union's main intelligence and security agency — responsible for foreign intelligence, domestic security, and counterintelligence", acceptableAnswers: ["Soviet intelligence agency", "USSR spy agency", "Soviet Union's KGB"], explanation: "The KGB was one of the largest and most effective intelligence agencies in history." },
      { id: "esp_400_01", categoryId: "his_espionage", tier: 400, prompt: "What were the 'Cambridge Five' — the most damaging spy ring in British intelligence history?", answer: "Five British upper-class men (including Kim Philby and Guy Burgess) recruited by Soviet intelligence while at Cambridge University who rose to senior positions in MI5, MI6, and the Foreign Office while secretly passing information to the USSR", acceptableAnswers: ["Five British spies for the Soviets", "Cambridge-recruited Soviet double agents", "Philby Burgess and others spying for USSR"], explanation: "The Cambridge Five penetrated the highest levels of British intelligence for decades." },
      { id: "esp_400_02", categoryId: "his_espionage", tier: 400, prompt: "What is a 'dead drop' in espionage, and why is it preferred over direct meetings between spies?", answer: "A secret location where one agent leaves materials for another to pick up later — it eliminates the risk of both agents being seen together", acceptableAnswers: ["Secret material exchange location", "Hidden spot for passing information without meeting", "Location for leaving/retrieving secret materials"], explanation: "Dead drops (hollowed rocks, magnetic containers under benches) reduce the chance of surveillance catching a handoff." },
      { id: "esp_400_03", categoryId: "his_espionage", tier: 400, prompt: "What was Operation Paperclip, and why was it controversial?", answer: "A secret US program that recruited former Nazi scientists (including Wernher von Braun) after WWII — their war records were whitewashed to bring their expertise to America's space and weapons programs", acceptableAnswers: ["US recruited Nazi scientists post-WWII", "Bringing Nazi scientists to America", "Recruiting German scientists with cleaned records"], explanation: "Many Paperclip scientists had used slave labor or were party members, but were given new identities." },
      { id: "esp_600_01", categoryId: "his_espionage", tier: 600, prompt: "What was the 'Venona project,' and what shocking revelation did its decrypted Soviet cables reveal about the Manhattan Project?", answer: "Venona was a secret US/UK program that decrypted Soviet intelligence communications from the 1940s — it revealed that the Soviets had multiple spies inside the Manhattan Project, including Klaus Fuchs, who gave them atomic bomb designs. The decrypts couldn't be used in court because the program itself was classified", acceptableAnswers: ["Decoded Soviet cables showing Manhattan Project spies", "Decryption revealing atomic spies like Fuchs", "Secret codebreaking exposing nuclear espionage"], explanation: "Venona proved Soviet espionage was far more extensive than anyone publicly acknowledged." },
      { id: "esp_600_02", categoryId: "his_espionage", tier: 600, prompt: "Who was Oleg Penkovsky, and why is he considered the most valuable Western spy of the Cold War?", answer: "A Soviet military intelligence (GRU) colonel who passed crucial nuclear missile intelligence to MI6 and the CIA — his information about Soviet missile capabilities helped JFK during the Cuban Missile Crisis by revealing that the USSR's nuclear arsenal was much smaller than feared", acceptableAnswers: ["GRU colonel who helped during Cuban Missile Crisis", "Soviet spy giving missile intel to West", "His intel showed USSR had fewer nukes than feared"], explanation: "Penkovsky's intelligence may have prevented nuclear war by giving Kennedy confidence to stand firm." },
      { id: "esp_600_03", categoryId: "his_espionage", tier: 600, prompt: "What is 'signals intelligence' (SIGINT) vs 'human intelligence' (HUMINT), and what was the Zimmermann Telegram's role in demonstrating SIGINT's power?", answer: "SIGINT is intelligence from intercepted communications; HUMINT is from human sources. The Zimmermann Telegram (1917) was a decoded German message proposing a military alliance with Mexico against the US — British SIGINT intercepted and decoded it, helping bring America into WWI", acceptableAnswers: ["Intercepted communications vs human sources; Zimmermann brought US into WWI", "SIGINT decoded German-Mexico alliance proposal", "British decoded telegram that brought US into WWI"], explanation: "The Zimmermann Telegram demonstrated that codebreaking could change the course of wars." },
    ],
  },
  {
    id: "sci_ocean",
    group: "science",
    name: "Ocean Science & Marine Biology",
    culture: "universal",
    description: "The deep blue — covering 71% of Earth and 95% unexplored.",
    imageUrl: "",
    questions: [
      { id: "ocn_200_01", categoryId: "sci_ocean", tier: 200, prompt: "What percentage of Earth's surface is covered by ocean?", answer: "About 71%", acceptableAnswers: ["71%", "About 70%", "71 percent"], explanation: "Despite covering most of Earth, over 80% of the ocean remains unmapped and unexplored." },
      { id: "ocn_200_02", categoryId: "sci_ocean", tier: 200, prompt: "What is the deepest known point in the ocean, located in the Mariana Trench?", answer: "Challenger Deep", acceptableAnswers: ["Challenger Deep", "The Challenger Deep"], explanation: "Challenger Deep reaches about 36,000 feet (11,000 meters) — deeper than Mount Everest is tall." },
      { id: "ocn_200_03", categoryId: "sci_ocean", tier: 200, prompt: "What ocean phenomenon involves large-scale movement of warm or cold water that affects global weather patterns?", answer: "Ocean currents (such as El Niño/La Niña or the Gulf Stream)", acceptableAnswers: ["Ocean currents", "El Niño", "Gulf Stream", "Ocean circulation"], explanation: "Ocean currents distribute heat around the planet and drive weather patterns." },
      { id: "ocn_400_01", categoryId: "sci_ocean", tier: 400, prompt: "What are hydrothermal vents, and why did their discovery change our understanding of where life can exist?", answer: "Volcanic openings on the ocean floor that emit superheated, mineral-rich water — they support entire ecosystems without sunlight, using chemosynthesis instead of photosynthesis", acceptableAnswers: ["Volcanic deep-sea vents supporting life without sunlight", "Deep-sea hot vents with chemosynthetic life", "Undersea volcanic vents with unique ecosystems"], explanation: "Their discovery proved life doesn't need sunlight, expanding the search for life on other worlds." },
      { id: "ocn_400_02", categoryId: "sci_ocean", tier: 400, prompt: "What is bioluminescence, and approximately what percentage of deep-sea creatures can produce their own light?", answer: "The ability of organisms to produce light through chemical reactions — roughly 76% of deep-sea creatures are bioluminescent", acceptableAnswers: ["Chemical light production, about 76%", "Living things making light, majority of deep sea", "Biological light, most deep-sea animals"], explanation: "Bioluminescence is the norm, not the exception, in the deep ocean." },
      { id: "ocn_400_03", categoryId: "sci_ocean", tier: 400, prompt: "What is the 'Great Pacific Garbage Patch,' and how big is it?", answer: "A massive concentration of floating plastic debris in the North Pacific, estimated at roughly twice the size of Texas — though most of it is microplastics invisible to the eye, not a solid island of trash", acceptableAnswers: ["Pacific plastic debris field, twice Texas size", "Huge plastic accumulation zone", "Plastic debris twice the size of Texas"], explanation: "The 'patch' is misleading — it's more like a dispersed plastic soup than a visible island." },
      { id: "ocn_600_01", categoryId: "sci_ocean", tier: 600, prompt: "What is the 'biological pump' in oceanography, and why is it critical for climate regulation?", answer: "The process where marine organisms near the surface absorb CO2, die, and sink to the deep ocean — effectively sequestering carbon for centuries. Without this pump, atmospheric CO2 would be significantly higher", acceptableAnswers: ["Marine organisms sinking carbon to deep ocean", "Dead organisms sequestering CO2 in deep sea", "Biological carbon sequestration via sinking organisms"], explanation: "The biological pump is one of Earth's most important carbon sinks, removing billions of tons of CO2." },
      { id: "ocn_600_02", categoryId: "sci_ocean", tier: 600, prompt: "What is 'ocean acidification,' and why is it sometimes called climate change's 'evil twin'?", answer: "The ocean absorbs about 30% of atmospheric CO2, which dissolves to form carbonic acid, lowering pH. This makes it harder for organisms like corals, shellfish, and plankton to build calcium carbonate shells — threatening the base of marine food chains", acceptableAnswers: ["CO2 absorption lowering ocean pH", "Dissolving shells from absorbed CO2", "Acid from CO2 destroying shell-building organisms"], explanation: "Ocean acidification is happening 100 times faster than any natural change in the past 55 million years." },
      { id: "ocn_600_03", categoryId: "sci_ocean", tier: 600, prompt: "What is the 'thermohaline circulation' (sometimes called the global ocean conveyor belt), and what could cause it to collapse?", answer: "A global system of deep ocean currents driven by differences in water temperature and salinity — cold, salty water sinks in the North Atlantic, driving global circulation. Melting Arctic ice adds fresh water, potentially weakening or shutting down the system, which would dramatically alter European climate", acceptableAnswers: ["Global current system that could collapse from Arctic ice melt", "Temperature/salt driven circulation threatened by freshwater", "Conveyor belt shutdown from melting ice"], explanation: "AMOC (Atlantic Meridional Overturning Circulation) weakening is one of climate science's most concerning tipping points." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 73 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
