#!/usr/bin/env python3
"""Insert wave 81 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_twin_peaks",
    group: "TV Shows",
    name: "Twin Peaks",
    culture: "american",
    description: "David Lynch's surreal murder mystery that changed television forever",
    imageUrl: "",
    questions: [
      { id: "twp_200_01", categoryId: "tv_twin_peaks", tier: 200, prompt: "What is the central mystery question posed in the show's first episode?", answer: "Who killed Laura Palmer?", acceptableAnswers: ["Who killed Laura Palmer", "Who killed Laura Palmer?"], explanation: "'Who killed Laura Palmer?' became a national obsession in 1990, spawning merchandise and cultural phenomenon." },
      { id: "twp_200_02", categoryId: "tv_twin_peaks", tier: 200, prompt: "What FBI agent, played by Kyle MacLachlan, investigates Laura Palmer's murder?", answer: "Special Agent Dale Cooper", acceptableAnswers: ["Dale Cooper", "Agent Cooper", "Special Agent Dale Cooper"], explanation: "Cooper's love of coffee, cherry pie, and dictation to 'Diane' made him one of TV's most beloved characters." },
      { id: "twp_200_03", categoryId: "tv_twin_peaks", tier: 200, prompt: "What mysterious location, accessed through the woods, features red curtains and a zigzag floor?", answer: "The Black Lodge / The Red Room", acceptableAnswers: ["The Black Lodge", "The Red Room", "Black Lodge"], explanation: "The Black Lodge is an extradimensional space where spirits dwell and time moves differently." },
      { id: "twp_400_01", categoryId: "tv_twin_peaks", tier: 400, prompt: "What is BOB, the entity responsible for Laura Palmer's death, and where does he come from?", answer: "A parasitic spirit from the Black Lodge who possesses humans and feeds on pain and suffering (garmonbozia)", acceptableAnswers: ["Evil spirit from the Black Lodge", "Parasitic entity from the Lodge", "Black Lodge spirit"], explanation: "BOB is a Lodge entity who possessed Leland Palmer and used him to abuse and ultimately kill Laura." },
      { id: "twp_400_02", categoryId: "tv_twin_peaks", tier: 400, prompt: "What substance called 'garmonbozia' do the Lodge spirits feed on?", answer: "Pain and suffering (manifested as creamed corn)", acceptableAnswers: ["Pain and suffering", "Creamed corn", "Garmonbozia / pain and suffering"], explanation: "Garmonbozia physically manifests as creamed corn, one of Lynch's most surreal and iconic visual metaphors." },
      { id: "twp_400_03", categoryId: "tv_twin_peaks", tier: 400, prompt: "In the Season 2 finale, what happens to Cooper in the Black Lodge that sets up the 2017 return?", answer: "His doppelgänger/evil double escapes the Lodge while the real Cooper remains trapped inside for 25 years", acceptableAnswers: ["Evil Cooper escapes, real Cooper trapped", "Doppelganger escapes", "Cooper is trapped and his evil double escapes"], explanation: "The final image of evil Cooper in the mirror asking 'How's Annie?' was one of TV's greatest cliffhangers, unresolved for 25 years." },
      { id: "twp_600_01", categoryId: "tv_twin_peaks", tier: 600, prompt: "In Twin Peaks: The Return, what is the significance of Episode 8's atomic bomb sequence, and how does it connect to the origin of BOB?", answer: "The first nuclear test at Trinity in 1945 tore open a rift that allowed BOB and other Lodge entities to enter our world; the bomb literally birthed evil into existence", acceptableAnswers: ["Nuclear test released BOB", "Trinity test created portal for evil", "Atomic bomb birthed BOB"], explanation: "Episode 8 is one of the most experimental hours in TV history, suggesting the atomic age literally unleashed metaphysical evil into the world." },
      { id: "twp_600_02", categoryId: "tv_twin_peaks", tier: 600, prompt: "What is the identity and significance of 'Judy' (Jowday) in The Return, the entity that even Phillip Jeffries fears?", answer: "An extremely powerful negative entity / the ultimate evil force — possibly an ancient deity called Jowday that is the source of all the darkness in the Twin Peaks mythology", acceptableAnswers: ["Ultimate evil entity", "Ancient negative force", "Jowday the extreme negative force"], explanation: "Judy represents the ultimate darkness that even the Lodge spirits fear, and Cooper's final mission in The Return is to find and confront her." },
      { id: "twp_600_03", categoryId: "tv_twin_peaks", tier: 600, prompt: "What does the final scene of The Return's Episode 18 suggest about Cooper's attempt to save Laura Palmer, and why does Laura scream?", answer: "Cooper may have shattered reality by trying to change the past; Laura's scream suggests she suddenly remembers everything — or that they are trapped in an alternate timeline/Lodge creation", acceptableAnswers: ["Reality shattered by changing the past", "Trapped in alternate reality", "Cooper broke reality trying to save Laura"], explanation: "The ambiguous ending suggests Cooper's attempt to rescue Laura created a fractured reality, with Laura's piercing scream implying horrific recognition of their situation." }
    ]
  },
  {
    id: "tv_watchmen",
    group: "TV Shows",
    name: "Watchmen (HBO)",
    culture: "american",
    description: "Damon Lindelof's brilliant sequel to the graphic novel, set in Tulsa, Oklahoma",
    imageUrl: "",
    questions: [
      { id: "wtc_200_01", categoryId: "tv_watchmen", tier: 200, prompt: "What real historical event does the show open with in its first scene?", answer: "The Tulsa Race Massacre of 1921", acceptableAnswers: ["Tulsa Race Massacre", "1921 Tulsa Massacre", "Tulsa Massacre", "Black Wall Street Massacre"], explanation: "The show begins with a devastating depiction of the Tulsa Race Massacre, grounding its superhero narrative in real American racial history." },
      { id: "wtc_200_02", categoryId: "tv_watchmen", tier: 200, prompt: "What masked identity does the protagonist Angela Abar use while fighting crime in Tulsa?", answer: "Sister Night", acceptableAnswers: ["Sister Night"], explanation: "Angela Abar, played by Regina King, operates as the costumed vigilante Sister Night in a world where police wear masks." },
      { id: "wtc_200_03", categoryId: "tv_watchmen", tier: 200, prompt: "What blue-skinned godlike being is revealed to be living in disguise in Tulsa?", answer: "Doctor Manhattan / Cal Abar", acceptableAnswers: ["Doctor Manhattan", "Dr. Manhattan", "Cal"], explanation: "Doctor Manhattan has been living as Angela's husband Cal, having transferred his consciousness into a human body." },
      { id: "wtc_400_01", categoryId: "tv_watchmen", tier: 400, prompt: "What white supremacist group serves as the show's primary antagonists, wearing Rorschach masks?", answer: "The Seventh Kavalry", acceptableAnswers: ["Seventh Kavalry", "The Seventh Kavalry", "7th Kavalry"], explanation: "The Seventh Kavalry co-opted Rorschach's journal and mask to justify their racist ideology — a chilling commentary on how radical symbols get appropriated." },
      { id: "wtc_400_02", categoryId: "tv_watchmen", tier: 400, prompt: "What is Nostalgia, the drug that allows Angela to experience her grandfather's memories?", answer: "Pills containing extracted memories that can be experienced by the person who takes them", acceptableAnswers: ["Memory pills", "Extracted memory pills", "Pills containing someone's memories"], explanation: "Nostalgia pills let Angela experience Will Reeves's memories of racism, violence, and his secret identity as Hooded Justice." },
      { id: "wtc_400_03", categoryId: "tv_watchmen", tier: 400, prompt: "What is the true identity of Hooded Justice, the first costumed hero, as revealed by the show?", answer: "Will Reeves, a Black police officer and Tulsa Massacre survivor", acceptableAnswers: ["Will Reeves", "A Black police officer", "Angela's grandfather"], explanation: "The show recontextualizes the first superhero as a Black man hiding behind a hood to fight the racism he experienced as a cop — a profound commentary on the superhero genre." },
      { id: "wtc_600_01", categoryId: "tv_watchmen", tier: 600, prompt: "What is Lady Trieu's Millennium Clock actually designed to do, and how does it connect to Doctor Manhattan's powers?", answer: "It's designed to capture and absorb Doctor Manhattan's powers by destroying his body and transferring his abilities to Trieu", acceptableAnswers: ["Capture Doctor Manhattan's powers", "Absorb Manhattan's abilities", "Transfer Manhattan's powers to Trieu"], explanation: "Lady Trieu engineered the entire Seventh Kavalry plot to draw Manhattan out, planning to use the Clock to steal his godlike powers for herself." },
      { id: "wtc_600_02", categoryId: "tv_watchmen", tier: 600, prompt: "What literary technique does Episode 6 ('This Extraordinary Being') use to blur the line between Angela's experience and Will's memories?", answer: "Seamless transitions between present and past where Angela physically inhabits her grandfather's memories, with the camera following her perspective in his body", acceptableAnswers: ["Angela inhabits grandfather's memories", "Seamless present-past transitions", "First-person memory embodiment"], explanation: "The episode won multiple Emmys for its innovative technique of having Angela live inside Will's memories, literally walking in his shoes through decades of racism." },
      { id: "wtc_600_03", categoryId: "tv_watchmen", tier: 600, prompt: "What is the significance of the final scene where Angela eats the egg, and what does the cut to black before she steps on the pool suggest?", answer: "Manhattan may have transferred his powers to Angela through the egg; the cut to black leaves ambiguous whether she actually gains his abilities or drowns", acceptableAnswers: ["Manhattan transferred powers via egg", "Ambiguous whether she gets powers", "Powers possibly transferred through egg"], explanation: "The egg is both literal (Manhattan said he could put his powers in organic matter) and metaphorical (birth, potential, legacy), and the ambiguous ending lets viewers choose their own meaning." }
    ]
  },
  {
    id: "mu_aphex",
    group: "Music",
    name: "Aphex Twin",
    culture: "universal",
    description: "Richard D. James and the outer limits of electronic music",
    imageUrl: "",
    questions: [
      { id: "apx_200_01", categoryId: "mu_aphex", tier: 200, prompt: "What is Aphex Twin's real name?", answer: "Richard D. James", acceptableAnswers: ["Richard D. James", "Richard James"], explanation: "Richard D. James has released music under numerous aliases including AFX, Polygon Window, and The Tuss." },
      { id: "apx_200_02", categoryId: "mu_aphex", tier: 200, prompt: "What 1999 album featuring the track 'Windowlicker' showcased his shift toward more accessible electronic music?", answer: "Windowlicker (single/EP)", acceptableAnswers: ["Windowlicker"], explanation: "Windowlicker's single became his most commercially successful release, accompanied by Chris Cunningham's disturbing music video." },
      { id: "apx_200_03", categoryId: "mu_aphex", tier: 200, prompt: "What 2001 album is considered a landmark of experimental electronic music, featuring drill 'n' bass and ambient tracks?", answer: "Drukqs", explanation: "Drukqs is a sprawling double album mixing aggressive breakcore with delicate prepared piano pieces." },
      { id: "apx_400_01", categoryId: "mu_aphex", tier: 400, prompt: "What ambient work, released in 1994, is considered one of the greatest ambient albums ever made?", answer: "Selected Ambient Works Volume II", acceptableAnswers: ["Selected Ambient Works Volume II", "SAW II", "Selected Ambient Works 85-92 Volume II"], explanation: "SAW II consists of untitled ambient pieces that range from serene to deeply unsettling, inspired by lucid dreaming." },
      { id: "apx_400_02", categoryId: "mu_aphex", tier: 400, prompt: "What music video director collaborated with Aphex Twin on the disturbing 'Come to Daddy' and 'Windowlicker' videos?", answer: "Chris Cunningham", acceptableAnswers: ["Chris Cunningham"], explanation: "Cunningham's collaborations with Aphex Twin produced some of the most iconic and disturbing music videos ever made." },
      { id: "apx_400_03", categoryId: "mu_aphex", tier: 400, prompt: "What is the legend about Richard D. James owning a tank and driving it around Cornwall?", answer: "He reportedly purchased a Daimler Ferret scout car (armored vehicle) and drove it around the countryside", acceptableAnswers: ["He bought a tank/armored vehicle", "Daimler Ferret scout car", "He owned an armored vehicle"], explanation: "The tank story is one of many James legends that blur the line between truth and myth — he has confirmed owning the vehicle." },
      { id: "apx_600_01", categoryId: "mu_aphex", tier: 600, prompt: "What hidden image is encoded in the spectrogram of the track 'ΔMi−1 = −αΣn=1NDi[n][Σj∈C[i]Fji[n − 1] + Fext_i[n−1]]' from Windowlicker?", answer: "A picture of Richard D. James's grinning face, visible when the audio is analyzed with a spectrogram", acceptableAnswers: ["His face", "Richard D. James's face", "A face in the spectrogram"], explanation: "James embedded his own face into the audio's frequency spectrum, discoverable only through spectrogram analysis — a technique he pioneered." },
      { id: "apx_600_02", categoryId: "mu_aphex", tier: 600, prompt: "What specific custom-built equipment does James use, and what is the significance of his modified Roland TB-303?", answer: "He modifies and circuit-bends hardware, including heavily modified TB-303s with additional oscillators and custom firmware for sounds impossible on stock units", acceptableAnswers: ["Modified TB-303s", "Circuit-bent hardware", "Custom modified synthesizers"], explanation: "James's approach to hardware modification — opening equipment and rewiring it to produce 'wrong' sounds — influenced an entire generation of electronic musicians." },
      { id: "apx_600_03", categoryId: "mu_aphex", tier: 600, prompt: "What was the Caustic Window album on Kickstarter, and what unusual circumstance surrounded its release?", answer: "An unreleased 1994 album that Aphex Twin fans crowdfunded to purchase at auction; the buyer then made it freely available, and James later confirmed his involvement", acceptableAnswers: ["Unreleased album bought at auction", "Crowdfunded unreleased album", "1994 album fans bought at auction"], explanation: "The Caustic Window LP was test-pressed but never released; fans crowdfunded over $67,000 to buy it at auction, and the winning bidder uploaded it for free." }
    ]
  },
  {
    id: "mu_pj_harvey",
    group: "Music",
    name: "PJ Harvey",
    culture: "universal",
    description: "Polly Jean Harvey — the shapeshifting artist who reinvents herself with every album",
    imageUrl: "",
    questions: [
      { id: "pjh_200_01", categoryId: "mu_pj_harvey", tier: 200, prompt: "What achievement did PJ Harvey accomplish with the Mercury Prize that no other artist has matched?", answer: "She is the only artist to win the Mercury Prize twice (for Stories from the City in 2001 and Let England Shake in 2011)", acceptableAnswers: ["Won the Mercury Prize twice", "Only artist to win Mercury Prize twice", "Two Mercury Prizes"], explanation: "Winning the Mercury Prize twice — a decade apart, for radically different albums — cements her status as one of Britain's most important artists." },
      { id: "pjh_200_02", categoryId: "mu_pj_harvey", tier: 200, prompt: "What raw, blues-influenced debut album established her as a fierce new voice in alternative rock in 1992?", answer: "Dry", explanation: "Dry showcased Harvey's powerful guitar work and unflinching lyrics about desire, the body, and gender." },
      { id: "pjh_200_03", categoryId: "mu_pj_harvey", tier: 200, prompt: "What 1995 album marked a dramatic transformation, with Harvey adopting glamorous aesthetics and a more accessible sound?", answer: "To Bring You My Love", explanation: "To Bring You My Love was a commercial breakthrough, featuring gothic blues and Harvey's theatrical reinvention." },
      { id: "pjh_400_01", categoryId: "mu_pj_harvey", tier: 400, prompt: "What 2011 anti-war album used WWI imagery and folk influences to examine England's history of conflict?", answer: "Let England Shake", explanation: "Let England Shake drew parallels between WWI and modern conflicts, using autoharp and samples of war songs." },
      { id: "pjh_400_02", categoryId: "mu_pj_harvey", tier: 400, prompt: "Which prominent alternative rock musician did Harvey have a well-known relationship and musical collaboration with in the mid-1990s?", answer: "Nick Cave", acceptableAnswers: ["Nick Cave"], explanation: "Harvey and Cave's relationship produced memorable collaborations including 'Henry Lee' from Cave's Murder Ballads album." },
      { id: "pjh_400_03", categoryId: "mu_pj_harvey", tier: 400, prompt: "What 2016 album was written after Harvey's travels to Afghanistan, Kosovo, and Washington D.C.?", answer: "The Hope Six Demolition Project", explanation: "The album drew on Harvey's experiences as a war correspondent, examining community destruction and political displacement." },
      { id: "pjh_600_01", categoryId: "mu_pj_harvey", tier: 600, prompt: "What unique art installation did Harvey create during the recording of 'The Hope Six Demolition Project' at Somerset House?", answer: "She recorded the entire album in a glass box as a public art installation called 'Recording in Progress,' where visitors could watch through one-way glass", acceptableAnswers: ["Glass box recording installation", "Recording in Progress at Somerset House", "Public recording in glass room"], explanation: "The Recording in Progress installation let visitors watch Harvey and her musicians work, turning the recording process into performance art." },
      { id: "pjh_600_02", categoryId: "mu_pj_harvey", tier: 600, prompt: "What specific guitar tuning and playing technique characterizes the raw sound of 'Rid of Me,' and who produced the album?", answer: "Steve Albini produced it using his signature minimalist approach; Harvey used abrasive open tunings and dramatic quiet-loud dynamics", acceptableAnswers: ["Steve Albini production with open tunings", "Albini produced with raw dynamics", "Steve Albini, open tunings"], explanation: "Albini's dry, unprocessed recording style combined with Harvey's visceral playing created one of the most raw-sounding albums in rock history." },
      { id: "pjh_600_03", categoryId: "mu_pj_harvey", tier: 600, prompt: "What specific sample opens 'The Words That Maketh Murder' on Let England Shake, and what war does it reference?", answer: "A sample of Eddie Cochran's 'Summertime Blues,' repurposed from a pop celebration into a commentary on the Gallipoli campaign", acceptableAnswers: ["Summertime Blues by Eddie Cochran", "Eddie Cochran sample", "Summertime Blues"], explanation: "Harvey's recontextualization of Cochran's innocent rock 'n' roll into a song about WWI carnage exemplifies the album's technique of finding horror in the familiar." }
    ]
  },
  {
    id: "vg_slay_spire",
    group: "Video Games",
    name: "Slay the Spire",
    culture: "universal",
    description: "The roguelike deckbuilder that created an entire genre",
    imageUrl: "",
    questions: [
      { id: "sts_200_01", categoryId: "vg_slay_spire", tier: 200, prompt: "How many playable characters are in the base game of Slay the Spire?", answer: "Four (Ironclad, Silent, Defect, Watcher)", acceptableAnswers: ["4", "Four"], explanation: "Each character has a completely unique card pool and playstyle: Ironclad (strength/self-damage), Silent (poison/shiv), Defect (orbs), Watcher (stances)." },
      { id: "sts_200_02", categoryId: "vg_slay_spire", tier: 200, prompt: "What are the three acts of a standard Slay the Spire run, culminating in which boss at the top?", answer: "Three acts with increasingly difficult bosses, with Act 3 bosses including the Awakened One, Donu and Deca, and the Time Eater", acceptableAnswers: ["Three acts", "3 acts with bosses"], explanation: "Each act ends with a boss fight, and reaching the top of the Spire reveals the heart — an optional final boss." },
      { id: "sts_200_03", categoryId: "vg_slay_spire", tier: 200, prompt: "What game mechanic allows you to increase difficulty after winning, adding modifiers up to a maximum level?", answer: "Ascension levels (up to Ascension 20)", acceptableAnswers: ["Ascension", "Ascension levels", "Ascension 20"], explanation: "Each Ascension level adds cumulative difficulty modifiers, with Ascension 20 being an extremely challenging test of game mastery." },
      { id: "sts_400_01", categoryId: "vg_slay_spire", tier: 400, prompt: "What is the Defect's core mechanic involving Orbs, and what are the four types of Orbs?", answer: "Lightning (damage), Frost (block), Dark (accumulating damage), and Plasma (energy); orbs passively trigger each turn and can be evoked for stronger effects", acceptableAnswers: ["Lightning Frost Dark Plasma", "Four orb types with passive and evoke effects"], explanation: "The Defect channels orbs in slots that passively trigger effects each turn, and evoking them triggers a more powerful one-time effect." },
      { id: "sts_400_02", categoryId: "vg_slay_spire", tier: 400, prompt: "What is the Heart of the Spire, and what must you collect to access the fight against it?", answer: "The true final boss; you must collect three keys (Ruby, Emerald, Sapphire) during the run to unlock the Act 4 fight", acceptableAnswers: ["True final boss needing 3 keys", "Final boss requiring ruby emerald sapphire keys", "Heart requiring three keys"], explanation: "The Heart is the game's ultimate challenge — a hidden Act 4 boss that requires sacrificing rewards during the run to collect keys." },
      { id: "sts_400_03", categoryId: "vg_slay_spire", tier: 400, prompt: "What is the concept of 'card removal' and why is removing cards from your deck sometimes more valuable than adding them?", answer: "Removing weak starter cards (Strikes/Defends) makes your deck smaller and more consistent, increasing the chance of drawing your powerful cards", acceptableAnswers: ["Deck thinning", "Removing weak cards for consistency", "Making deck smaller and more consistent"], explanation: "Deck thinning is a crucial strategy — a 15-card deck with all strong cards is often better than a 30-card deck with some powerful cards diluted by weak ones." },
      { id: "sts_600_01", categoryId: "vg_slay_spire", tier: 600, prompt: "What is the 'infinite combo' archetype, and what specific card interaction allows the Ironclad to play unlimited attacks in a single turn?", answer: "Using Dropkick on a vulnerable enemy with 0-cost attacks and draw effects to create an infinite loop (Dropkick draws a card and gains energy when hitting a vulnerable enemy)", acceptableAnswers: ["Dropkick infinite loop", "Dropkick on vulnerable for infinite", "Dropkick draw and energy loop"], explanation: "The Dropkick infinite requires the enemy to be vulnerable and the deck to be thin enough that Dropkick keeps cycling back — illustrating the game's deep combo potential." },
      { id: "sts_600_02", categoryId: "vg_slay_spire", tier: 600, prompt: "What seeding system does Slay the Spire use, and why did competitive players discover that certain seeds are mathematically unwinnable at Ascension 20?", answer: "Each run uses a numerical seed that determines all encounters, card rewards, and events; analysis showed some seeds have mathematically impossible combinations of challenges and available cards", acceptableAnswers: ["Numerical seed determining everything", "Deterministic seeding with some unwinnable seeds", "Seeds determine all RNG"], explanation: "The deterministic seeding means every run is technically 'solvable' like a puzzle, but some seeds at A20 present challenges that no possible decision tree can overcome." },
      { id: "sts_600_03", categoryId: "vg_slay_spire", tier: 600, prompt: "What design philosophy did MegaCrit use for the Watcher's Stance mechanic that makes her simultaneously the most powerful and most dangerous character?", answer: "Wrath stance doubles damage dealt AND received; Divinity gives triple energy but ends immediately — requiring precise stance-switching to maximize offense without dying", acceptableAnswers: ["Wrath doubles both damage dealt and received", "Stance switching risk-reward", "Double damage both ways in Wrath"], explanation: "The Watcher's high-risk/high-reward stance system creates the most complex decision-making in the game, as a mistimed Wrath stance can mean instant death." }
    ]
  },
  {
    id: "vg_bg3",
    group: "Video Games",
    name: "Baldur's Gate 3",
    culture: "universal",
    description: "Larian Studios' massive D&D RPG that swept the 2023 Game Awards",
    imageUrl: "",
    questions: [
      { id: "bg3_200_01", categoryId: "vg_bg3", tier: 200, prompt: "What parasitic creature is implanted in the player character's brain at the start of the game?", answer: "A Mind Flayer tadpole / Illithid tadpole", acceptableAnswers: ["Mind Flayer tadpole", "Illithid tadpole", "Tadpole"], explanation: "The ceremorphosis tadpole should transform you into a Mind Flayer, but something prevents it — uncovering why drives the main plot." },
      { id: "bg3_200_02", categoryId: "vg_bg3", tier: 200, prompt: "What tabletop RPG system does Baldur's Gate 3 use for its combat and skill checks?", answer: "Dungeons & Dragons 5th Edition", acceptableAnswers: ["D&D 5e", "Dungeons & Dragons 5th Edition", "5th Edition D&D", "D&D 5th Edition"], explanation: "BG3 faithfully implements D&D 5e rules including ability scores, spell slots, advantage/disadvantage, and the d20 system." },
      { id: "bg3_200_03", categoryId: "vg_bg3", tier: 200, prompt: "What is the name of the vampire spawn companion who can be romanced?", answer: "Astarion", acceptableAnswers: ["Astarion"], explanation: "Astarion is a High Elf Rogue vampire spawn who became one of the most popular RPG companions in gaming history." },
      { id: "bg3_400_01", categoryId: "vg_bg3", tier: 400, prompt: "What are the Absolute and the three 'Chosen' who lead its cult, and which dead gods are they connected to?", answer: "The Absolute is actually the Elder Brain controlled by three Chosen of dead gods: Ketheric Thorm (Myrkul), Orin the Red (Bhaal), and Enver Gortash (Bane)", acceptableAnswers: ["Elder Brain with three Chosen", "Ketheric, Orin, and Gortash", "Chosen of Myrkul, Bhaal, and Bane"], explanation: "The Dead Three — Myrkul, Bhaal, and Bane — each have a Chosen who together control the Elder Brain using the Netherstones." },
      { id: "bg3_400_02", categoryId: "vg_bg3", tier: 400, prompt: "What happens in the Dark Urge origin if you resist or succumb to Bhaal's influence throughout the game?", answer: "The Dark Urge is a custom origin where you play as Bhaal's chosen, struggling against murderous compulsions; you can resist Bhaal and reject your nature or fully embrace becoming his Slayer", acceptableAnswers: ["Resist or embrace Bhaal's murderous nature", "Bhaal's chosen struggling with murder urges", "Custom origin with Bhaal compulsions"], explanation: "The Dark Urge provides perhaps the most compelling narrative in the game, with gut-wrenching consequences for both resistance and submission." },
      { id: "bg3_400_03", categoryId: "vg_bg3", tier: 400, prompt: "What is the Guardian figure that appears in the player's dreams, and what is their true identity?", answer: "The Dream Visitor / Guardian is actually a Mind Flayer named the Emperor, a transformed Balduran who is protecting you from ceremorphosis", acceptableAnswers: ["The Emperor", "A Mind Flayer named the Emperor", "Transformed Balduran"], explanation: "The twist that your attractive dream guardian is actually a Mind Flayer who was once Balduran (founder of Baldur's Gate) recontextualizes the entire first act." },
      { id: "bg3_600_01", categoryId: "vg_bg3", tier: 600, prompt: "What specific D&D 5e rule modification did Larian make regarding reactions and opportunity attacks that differs from tabletop?", answer: "Reactions can be set to automatic, ask, or off — unlike tabletop where they're always player-decided; they also modified some reaction triggers for real-time flow", acceptableAnswers: ["Automated reaction system", "Reactions can be auto/ask/off", "Modified reaction toggle system"], explanation: "This was a key design decision to maintain gameplay flow while preserving tactical depth — pure tabletop reactions would require constant pausing." },
      { id: "bg3_600_02", categoryId: "vg_bg3", tier: 600, prompt: "What is the significance of Karlach's Infernal Engine heart, and why can't she return to the material plane at the end of the game without consequences?", answer: "Her heart is an Infernal Engine from Avernus that overheats on the material plane; without returning to Avernus for coolant or finding another solution, she will literally burn up and die", acceptableAnswers: ["Infernal Engine overheats outside Avernus", "Her heart burns up on material plane", "Avernus engine heart that overheats"], explanation: "Karlach's tragic choice — return to the hellish Avernus or die — is one of the game's most emotionally devastating character arcs." },
      { id: "bg3_600_03", categoryId: "vg_bg3", tier: 600, prompt: "How many total lines of recorded dialogue does Baldur's Gate 3 contain, and how does this compare to the entire Lord of the Rings film trilogy?", answer: "Approximately 2 million words of dialogue — roughly 3-4 times the entire Lord of the Rings trilogy", acceptableAnswers: ["2 million words", "Approximately 2 million words", "3-4 times Lord of the Rings"], explanation: "BG3's script dwarfs most other media, with each companion having more dialogue than most entire RPGs, necessitating years of voice recording." }
    ]
  },
  {
    id: "mv_kubrick_d",
    group: "Movies",
    name: "Stanley Kubrick (Deep Cut)",
    culture: "universal",
    description: "The perfectionist auteur's filmography — the deeper obsessions",
    imageUrl: "",
    questions: [
      { id: "kub_200_01", categoryId: "mv_kubrick_d", tier: 200, prompt: "What Stephen King adaptation features the Overlook Hotel and Jack Nicholson's iconic 'Here's Johnny!' scene?", answer: "The Shining", acceptableAnswers: ["The Shining"], explanation: "The Shining is one of the most celebrated horror films ever made, though Stephen King famously disliked Kubrick's interpretation." },
      { id: "kub_200_02", categoryId: "mv_kubrick_d", tier: 200, prompt: "What dystopian film features Alex DeLarge and his droogs committing 'ultraviolence' in a future Britain?", answer: "A Clockwork Orange", acceptableAnswers: ["A Clockwork Orange", "Clockwork Orange"], explanation: "A Clockwork Orange (1971) was so controversial that Kubrick himself withdrew it from UK distribution after receiving death threats." },
      { id: "kub_200_03", categoryId: "mv_kubrick_d", tier: 200, prompt: "What groundbreaking sci-fi film features HAL 9000 and the mysterious monolith?", answer: "2001: A Space Odyssey", acceptableAnswers: ["2001: A Space Odyssey", "2001"], explanation: "2001 (1968) redefined science fiction cinema and remains one of the most influential films ever made." },
      { id: "kub_400_01", categoryId: "mv_kubrick_d", tier: 400, prompt: "What special NASA lens did Kubrick use to film Barry Lyndon's famous candlelit scenes?", answer: "A Zeiss Planar 50mm f/0.7 lens, originally designed for NASA's Apollo program", acceptableAnswers: ["Zeiss Planar f/0.7", "NASA f/0.7 lens", "Zeiss f/0.7"], explanation: "Only ten of these lenses were ever made — three went to NASA, and Kubrick acquired three to shoot entirely by candlelight without artificial lighting." },
      { id: "kub_400_02", categoryId: "mv_kubrick_d", tier: 400, prompt: "How many takes did Kubrick reportedly require for the baseball bat scene with Shelley Duvall in The Shining?", answer: "127 takes", acceptableAnswers: ["127", "127 takes"], explanation: "The 127 takes of the baseball bat scene hold a Guinness World Record and contributed to Duvall's well-documented psychological distress during filming." },
      { id: "kub_400_03", categoryId: "mv_kubrick_d", tier: 400, prompt: "What was Kubrick's unfinished project about the Holocaust that he abandoned after learning Steven Spielberg was making Schindler's List?", answer: "Aryan Papers", acceptableAnswers: ["Aryan Papers", "The Aryan Papers"], explanation: "Kubrick had spent years developing Aryan Papers but shelved it, reportedly saying that Spielberg's film had 'done it already.'" },
      { id: "kub_600_01", categoryId: "mv_kubrick_d", tier: 600, prompt: "What specific front-projection technique was used for the 'Dawn of Man' sequence in 2001, and why was it revolutionary?", answer: "8x10 transparency front-projected onto a massive 3M Scotchlite screen using a custom-built projector, creating seamless African backgrounds in a British studio", acceptableAnswers: ["Front projection with Scotchlite screen", "8x10 front projection", "3M Scotchlite front projection"], explanation: "The front projection was so convincing that many viewers assumed the scenes were filmed on location; the technique used a half-silvered mirror and highly reflective screen." },
      { id: "kub_600_02", categoryId: "mv_kubrick_d", tier: 600, prompt: "What is the 'Room 237' conspiracy theory about hidden messages in The Shining, and what specific patterns do theorists point to?", answer: "Theories include: the film is about the genocide of Native Americans (Indian imagery), the Holocaust (the number 42), or Kubrick confessing to faking the Moon landing (Danny's Apollo 11 sweater)", acceptableAnswers: ["Multiple conspiracy theories about hidden messages", "Native American genocide, Holocaust, Moon landing theories", "Hidden meanings including Moon landing confession"], explanation: "The documentary Room 237 explored these theories, which range from plausible (Native American subtext) to conspiratorial (Moon landing confession)." },
      { id: "kub_600_03", categoryId: "mv_kubrick_d", tier: 600, prompt: "What is the significance of the Ludovico Technique in A Clockwork Orange, and what real psychological treatment inspired it?", answer: "Aversion therapy using forced viewing of violence while chemically inducing nausea; inspired by real aversion therapy used to 'treat' homosexuality and other behaviors in the 1960s-70s", acceptableAnswers: ["Aversion therapy", "Forced violence viewing with chemical nausea", "Real aversion therapy inspiration"], explanation: "The Ludovico Technique is a cinematic exaggeration of real aversion therapies that used nausea-inducing drugs paired with stimuli to condition away 'undesirable' behaviors." }
    ]
  },
  {
    id: "his_espionage",
    group: "History & Culture",
    name: "Cold War Espionage",
    culture: "universal",
    description: "The real spy stories behind the Iron Curtain — double agents, moles, and defectors",
    imageUrl: "",
    questions: [
      { id: "esp_200_01", categoryId: "his_espionage", tier: 200, prompt: "What was the name of the Soviet spy agency that served as the primary intelligence service during the Cold War?", answer: "KGB (Komitet Gosudarstvennoy Bezopasnosti)", acceptableAnswers: ["KGB", "The KGB"], explanation: "The KGB was one of the largest and most powerful intelligence agencies in history, employing over 480,000 people." },
      { id: "esp_200_02", categoryId: "his_espionage", tier: 200, prompt: "What group of British intelligence officers secretly spied for the Soviet Union, famously including Kim Philby and Guy Burgess?", answer: "The Cambridge Five", acceptableAnswers: ["Cambridge Five", "The Cambridge Five", "Cambridge Spy Ring"], explanation: "The Cambridge Five were recruited at Cambridge University in the 1930s and penetrated the highest levels of British intelligence." },
      { id: "esp_200_03", categoryId: "his_espionage", tier: 200, prompt: "What divided German city became the epicenter of Cold War espionage, with a famous wall separating East and West?", answer: "Berlin", acceptableAnswers: ["Berlin", "West Berlin / East Berlin"], explanation: "Berlin was the 'spy capital of the world' — every major intelligence agency operated there, and the wall became the symbol of the Cold War." },
      { id: "esp_400_01", categoryId: "his_espionage", tier: 400, prompt: "Who was Aldrich Ames, and why was his espionage considered the most damaging to the CIA?", answer: "A CIA counterintelligence officer who spied for the Soviet Union from 1985-1994, compromising over 100 operations and causing the execution of at least 10 CIA assets", acceptableAnswers: ["CIA officer who spied for Soviets", "CIA mole who got assets killed", "Counterintelligence officer selling secrets"], explanation: "Ames was paid $4.6 million by the KGB, making him one of the highest-paid spies in history while causing devastating losses to CIA human intelligence." },
      { id: "esp_400_02", categoryId: "his_espionage", tier: 400, prompt: "What was Operation GOLD (also known as the Berlin Tunnel), and what ironic fact undermined its success?", answer: "A CIA/MI6 tunnel tapped into Soviet communication cables in East Berlin, but the Soviets knew about it from the start through their mole George Blake", acceptableAnswers: ["Tunnel to tap Soviet communications", "Berlin tunnel compromised by George Blake", "Communication tunnel betrayed by mole"], explanation: "The Soviets allowed the tunnel to operate for 11 months to protect Blake's identity, feeding carefully controlled information through it." },
      { id: "esp_400_03", categoryId: "his_espionage", tier: 400, prompt: "What was a 'dead drop,' and why did spies prefer it over direct meetings?", answer: "A secret location where information or materials are left for another person to retrieve later, avoiding the risk of both parties being seen together", acceptableAnswers: ["Secret exchange location", "Hidden info exchange point", "Location for indirect material exchange"], explanation: "Dead drops eliminated the most dangerous moment in espionage — the face-to-face meeting — using pre-arranged locations like hollow trees, loose bricks, or bridge railings." },
      { id: "esp_600_01", categoryId: "his_espionage", tier: 600, prompt: "What was the Farewell Dossier, and how did the CIA use it to sabotage Soviet infrastructure through deliberately flawed technology?", answer: "A French mole (Vladimir Vetrov) provided a list of Soviet technology targets; the CIA then allowed the Soviets to 'steal' modified software that caused a massive Siberian pipeline explosion in 1982", acceptableAnswers: ["Modified technology causing pipeline explosion", "Flawed tech fed to Soviets", "CIA sabotage via stolen technology"], explanation: "The CIA inserted malicious code into pipeline control software the KGB was trying to steal, causing the most monumental non-nuclear explosion ever recorded." },
      { id: "esp_600_02", categoryId: "his_espionage", tier: 600, prompt: "What was Oleg Penkovsky's contribution to resolving the Cuban Missile Crisis, and what happened to him?", answer: "He provided crucial intelligence about Soviet missile capabilities that helped Kennedy understand Khrushchev was bluffing about nuclear readiness; he was caught and executed by firing squad in 1963", acceptableAnswers: ["Provided missile intelligence for Cuban Crisis", "Showed Soviets were bluffing", "Gave Kennedy intelligence about Soviet missiles"], explanation: "Penkovsky's intelligence — that Soviet missiles weren't as ready as claimed — gave Kennedy confidence to pursue a diplomatic solution rather than a military strike." },
      { id: "esp_600_03", categoryId: "his_espionage", tier: 600, prompt: "What was the significance of Vasili Mitrokhin's archive, and how did it reshape understanding of Cold War espionage?", answer: "A KGB archivist who secretly copied thousands of classified files over 12 years and defected to Britain in 1992 with the largest intelligence haul in history, exposing spy networks worldwide", acceptableAnswers: ["KGB archivist who copied files and defected", "Largest intelligence haul in history", "12 years of copied KGB files"], explanation: "The Mitrokhin Archive exposed Soviet agents across dozens of countries and is considered the most complete record of KGB operations ever made public." }
    ]
  },
  {
    id: "sci_black_holes",
    group: "Science & Nature",
    name: "Black Holes & Extreme Astrophysics",
    culture: "universal",
    description: "Where spacetime breaks — the physics of the universe's most extreme objects",
    imageUrl: "",
    questions: [
      { id: "bkh_200_01", categoryId: "sci_black_holes", tier: 200, prompt: "What is the boundary around a black hole beyond which nothing — not even light — can escape?", answer: "The event horizon", acceptableAnswers: ["Event horizon", "The event horizon"], explanation: "The event horizon isn't a physical surface but a boundary in spacetime — crossing it means escape is physically impossible." },
      { id: "bkh_200_02", categoryId: "sci_black_holes", tier: 200, prompt: "What was the name of the project that captured the first-ever image of a black hole in 2019?", answer: "Event Horizon Telescope (EHT)", acceptableAnswers: ["Event Horizon Telescope", "EHT"], explanation: "The EHT linked radio telescopes worldwide to create an Earth-sized virtual telescope, imaging the black hole in galaxy M87." },
      { id: "bkh_200_03", categoryId: "sci_black_holes", tier: 200, prompt: "What type of stellar event creates a stellar-mass black hole?", answer: "A supernova / collapse of a massive star", acceptableAnswers: ["Supernova", "Star collapse", "Stellar collapse", "Core collapse supernova"], explanation: "When a star more than ~25 times the Sun's mass runs out of fuel, its core collapses beyond the neutron star stage into a black hole." },
      { id: "bkh_400_01", categoryId: "sci_black_holes", tier: 400, prompt: "What is spaghettification, the process that occurs when falling into a stellar-mass black hole?", answer: "Tidal forces stretch an object vertically and compress it horizontally as the gravitational gradient grows extreme near the singularity", acceptableAnswers: ["Tidal stretching", "Stretching by tidal forces", "Vertical stretching and horizontal compression"], explanation: "The difference in gravitational pull between your head and feet becomes so extreme that you're stretched into a thin strand — like spaghetti." },
      { id: "bkh_400_02", categoryId: "sci_black_holes", tier: 400, prompt: "What is Hawking radiation, and what does it imply about black holes' ultimate fate?", answer: "Quantum effects near the event horizon cause black holes to slowly emit radiation and lose mass; given enough time, they will completely evaporate", acceptableAnswers: ["Quantum radiation causing evaporation", "Black holes slowly emit radiation and evaporate", "Thermal radiation from quantum effects"], explanation: "Hawking's 1974 prediction that black holes emit radiation revolutionized physics by connecting quantum mechanics, thermodynamics, and gravity." },
      { id: "bkh_400_03", categoryId: "sci_black_holes", tier: 400, prompt: "What are supermassive black holes, and where are they typically found?", answer: "Black holes millions to billions of times the Sun's mass, found at the centers of most galaxies, including our own Milky Way (Sagittarius A*)", acceptableAnswers: ["Galaxy center black holes", "Millions to billions solar masses at galaxy centers", "Sagittarius A* type objects"], explanation: "Nearly every large galaxy hosts a supermassive black hole; the Milky Way's — Sagittarius A* — has about 4 million solar masses." },
      { id: "bkh_600_01", categoryId: "sci_black_holes", tier: 600, prompt: "What is the black hole information paradox, and why did it challenge fundamental physics for decades?", answer: "If black holes destroy information when they evaporate via Hawking radiation, it violates quantum mechanics' requirement that information is never truly lost; this creates a contradiction between general relativity and quantum mechanics", acceptableAnswers: ["Information destruction violates quantum mechanics", "Conflict between GR and QM about information", "Whether black holes destroy quantum information"], explanation: "The information paradox drove theoretical physics for 50 years, with recent work suggesting information may be encoded on the event horizon or in radiation correlations." },
      { id: "bkh_600_02", categoryId: "sci_black_holes", tier: 600, prompt: "What is the Penrose process, and how does it theoretically allow energy extraction from a rotating black hole?", answer: "A particle entering a rotating black hole's ergosphere can split, with one fragment falling in and the other escaping with MORE energy than the original — extracting rotational energy from the black hole", acceptableAnswers: ["Energy extraction from ergosphere", "Particle splitting in ergosphere", "Extracting rotational energy via ergosphere"], explanation: "The Penrose process shows that spinning black holes have exploitable energy — the escaping particle carries away more energy than entered, slowing the black hole's rotation." },
      { id: "bkh_600_03", categoryId: "sci_black_holes", tier: 600, prompt: "What did the 2020 Nobel Prize in Physics recognize regarding black holes, and what observational evidence proved general relativity's predictions?", answer: "Roger Penrose won for proving singularity formation is inevitable in GR; Reinhard Genzel and Andrea Ghez won for tracking stars orbiting Sagittarius A*, proving a supermassive black hole exists at the Milky Way's center", acceptableAnswers: ["Penrose singularity proof, Genzel/Ghez Sgr A* observations", "Penrose for singularity theorem, star orbits around Sgr A*", "Singularity inevitability and Milky Way black hole proof"], explanation: "Genzel and Ghez independently tracked star S2's 16-year orbit around Sgr A*, providing the most direct evidence of a supermassive black hole's existence." }
    ]
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 81 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
