#!/usr/bin/env python3
"""Insert wave 76 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_house_of_dragon",
    group: "tv",
    name: "House of the Dragon",
    culture: "universal",
    description: "Fire and blood — the Targaryen civil war that tore Westeros apart.",
    imageUrl: "",
    questions: [
      { id: "htd_200_01", categoryId: "tv_house_of_dragon", tier: 200, prompt: "House of the Dragon is a prequel to which massively popular HBO series?", answer: "Game of Thrones", explanation: "Set roughly 200 years before Game of Thrones, during the Targaryen dynasty's peak." },
      { id: "htd_200_02", categoryId: "tv_house_of_dragon", tier: 200, prompt: "What civil war between two Targaryen factions is the central conflict of the show?", answer: "The Dance of the Dragons", acceptableAnswers: ["Dance of the Dragons", "The Dance"], explanation: "A devastating war between the Greens (Aegon II) and the Blacks (Rhaenyra) over the Iron Throne." },
      { id: "htd_200_03", categoryId: "tv_house_of_dragon", tier: 200, prompt: "What creatures give House Targaryen their military supremacy?", answer: "Dragons", explanation: "The Targaryens are the last dragonlord dynasty, and their dragons are weapons of mass destruction." },
      { id: "htd_400_01", categoryId: "tv_house_of_dragon", tier: 400, prompt: "Who are the two main claimants to the Iron Throne, and what are their factions called?", answer: "Rhaenyra Targaryen (the Blacks) and Aegon II Targaryen (the Greens)", acceptableAnswers: ["Rhaenyra and Aegon II", "Blacks and Greens"], explanation: "The colors come from the dresses worn at a tournament — green for Alicent, black for Rhaenyra." },
      { id: "htd_400_02", categoryId: "tv_house_of_dragon", tier: 400, prompt: "What is the name of the massive dragon ridden by Daemon Targaryen?", answer: "Caraxes (the Blood Wyrm)", acceptableAnswers: ["Caraxes", "The Blood Wyrm"], explanation: "Caraxes is known for his distinctive serpentine appearance and ferocity in battle." },
      { id: "htd_400_03", categoryId: "tv_house_of_dragon", tier: 400, prompt: "What role does Otto Hightower play in engineering the succession crisis?", answer: "As Hand of the King, he positions his daughter Alicent to marry King Viserys, then pushes for Alicent's son Aegon to inherit over the named heir Rhaenyra", acceptableAnswers: ["Hand of King who pushed Alicent's son over Rhaenyra", "Engineered Aegon's claim via his daughter", "Political schemer placing his grandson on throne"], explanation: "Otto's scheming across decades sets the Dance of the Dragons in motion." },
      { id: "htd_600_01", categoryId: "tv_house_of_dragon", tier: 600, prompt: "What is Aegon's prophecy ('A Song of Ice and Fire') that Viserys passes to Rhaenyra, and how does it connect to Game of Thrones?", answer: "A Targaryen prophecy that a great winter threat will come from the North and only a united realm under a Targaryen can stop it — this is the White Walker threat from Game of Thrones. The prophecy is what Rhaenyra believes gives her claim divine legitimacy", acceptableAnswers: ["Prophecy about northern threat connecting to White Walkers", "Winter threat prophecy linking to GoT", "Targaryen prophecy about the Long Night"], explanation: "The show recontextualizes Targaryen obsession with the throne as duty, not just ambition." },
      { id: "htd_600_02", categoryId: "tv_house_of_dragon", tier: 600, prompt: "What is the 'Blood and Cheese' incident, and why is it considered one of the most disturbing events in Westeros history?", answer: "Two assassins (Blood, a gold cloak, and Cheese, a ratcatcher) infiltrate the Red Keep to kill one of Aegon II's sons in retaliation for Lucerys's death. They force Queen Helaena to choose which of her sons dies — a horrific scene meant to mirror the cruelty of the Greens killing Rhaenyra's son", acceptableAnswers: ["Assassins force queen to choose which son dies", "Blood and Cheese kill royal child in retaliation", "Queen forced to pick which child is murdered"], explanation: "The incident escalates the war beyond any possibility of reconciliation." },
      { id: "htd_600_03", categoryId: "tv_house_of_dragon", tier: 600, prompt: "What historical real-world conflict is the Dance of the Dragons most directly based on?", answer: "The Anarchy (1138-1153) — a civil war between Empress Matilda and King Stephen over the English throne after Henry I named his daughter heir but the crown was seized by her cousin. The parallels (named female heir vs male usurper, devastating civil war) are nearly exact", acceptableAnswers: ["The Anarchy in medieval England", "Matilda vs Stephen English succession crisis", "12th century English civil war"], explanation: "George R.R. Martin openly drew from The Anarchy, with Rhaenyra mirroring Matilda." },
    ],
  },
  {
    id: "tv_mandalorian",
    group: "tv",
    name: "The Mandalorian",
    culture: "universal",
    description: "This is the way — a bounty hunter and a tiny green Force-user.",
    imageUrl: "",
    questions: [
      { id: "mnd_200_01", categoryId: "tv_mandalorian", tier: 200, prompt: "What is the adorable green creature that the Mandalorian protects, initially known to fans as 'Baby Yoda'?", answer: "Grogu", acceptableAnswers: ["Grogu", "Baby Yoda", "The Child"], explanation: "Grogu's real name wasn't revealed until Season 2, after a year of 'Baby Yoda' mania." },
      { id: "mnd_200_02", categoryId: "tv_mandalorian", tier: 200, prompt: "What is the Mandalorian's real name?", answer: "Din Djarin", acceptableAnswers: ["Din Djarin", "Din"], explanation: "Pedro Pascal plays Din Djarin, a Mandalorian bounty hunter." },
      { id: "mnd_200_03", categoryId: "tv_mandalorian", tier: 200, prompt: "What phrase serves as the Mandalorian creed and is repeated throughout the series?", answer: "This is the way", explanation: "The phrase represents the Mandalorian code of conduct and honor." },
      { id: "mnd_400_01", categoryId: "tv_mandalorian", tier: 400, prompt: "What is the Darksaber, and why is it significant to Mandalorian culture?", answer: "An ancient black-bladed lightsaber created by the first Mandalorian Jedi — whoever wields it has a legitimate claim to rule Mandalore, but it must be won in combat, not given", acceptableAnswers: ["Black lightsaber, ruler of Mandalore must win it in combat", "Ancient Mandalorian lightsaber granting leadership", "Black lightsaber won through combat for rulership"], explanation: "The Darksaber's rule of combat-earned succession creates major plot complications." },
      { id: "mnd_400_02", categoryId: "tv_mandalorian", tier: 400, prompt: "What technology does the show use to create photorealistic virtual sets instead of green screens?", answer: "The Volume — a massive LED screen wall (StageCraft by ILM) that displays real-time rendered environments, allowing actors to interact with photorealistic backgrounds", acceptableAnswers: ["The Volume", "StageCraft LED walls", "LED virtual production"], explanation: "The Volume revolutionized film production and has been adopted across the industry." },
      { id: "mnd_400_03", categoryId: "tv_mandalorian", tier: 400, prompt: "Which beloved Star Wars character makes a surprise appearance at the end of Season 2 to take Grogu for Jedi training?", answer: "Luke Skywalker (digitally de-aged Mark Hamill)", acceptableAnswers: ["Luke Skywalker", "Luke"], explanation: "The CGI Luke reveal became one of the most talked-about TV moments of 2020." },
      { id: "mnd_600_01", categoryId: "tv_mandalorian", tier: 600, prompt: "What is the 'Children of the Watch' vs mainstream Mandalorian culture debate, and how does it recontextualize Din Djarin's beliefs?", answer: "Din's sect (Children of the Watch) follows extreme orthodox rules like never removing your helmet — most Mandalorians (like Bo-Katan) consider this a fringe cult. Din discovers his entire worldview is based on an extremist interpretation of Mandalorian culture", acceptableAnswers: ["Din's sect is extremist, mainstream Mandos remove helmets", "Children of the Watch are fundamentalists", "His helmet rule is cult-like, not mainstream"], explanation: "The reveal challenges Din's identity — everything he believed about being Mandalorian was a radical interpretation." },
      { id: "mnd_600_02", categoryId: "tv_mandalorian", tier: 600, prompt: "How does the show's episodic 'adventure of the week' format deliberately mirror classic Westerns and samurai films?", answer: "Each episode follows a lone gunfighter arriving in a troubled town, solving problems, and moving on — directly referencing Kurosawa's 'Yojimbo,' Sergio Leone's 'Man with No Name' trilogy, and the TV show 'Kung Fu.' Jon Favreau has called it a 'space Western'", acceptableAnswers: ["Lone gunfighter Western/samurai format", "Space Western mirroring Kurosawa and Leone", "Adventure-of-week like classic Westerns"], explanation: "The Mandalorian revived the Star Wars franchise by returning to its Western and samurai roots." },
      { id: "mnd_600_03", categoryId: "tv_mandalorian", tier: 600, prompt: "What was the production challenge of keeping Grogu's existence secret before the premiere, and how did Lucasfilm accomplish it?", answer: "No merchandise was produced before launch (sacrificing hundreds of millions in holiday sales), the character wasn't in any marketing materials, and the puppet was hidden on set under the code name 'the asset' — even many crew members didn't know what was under the blanket between takes", acceptableAnswers: ["No merch made, hidden from marketing and crew", "Sacrificed merchandise revenue for secrecy", "Code named 'the asset,' hidden from crew"], explanation: "Disney deliberately forfeited a holiday merchandise season to preserve the surprise — unprecedented for a franchise this size." },
    ],
  },
  {
    id: "mu_prince",
    group: "music",
    name: "Prince",
    culture: "american",
    description: "The Purple One — Minneapolis funk, androgyny, and 39 studio albums of genius.",
    imageUrl: "",
    questions: [
      { id: "prc_200_01", categoryId: "mu_prince", tier: 200, prompt: "What is Prince's most famous album and film, sharing a title about a rain of a certain color?", answer: "Purple Rain", explanation: "Purple Rain (1984) was both a film and album that made Prince a global superstar." },
      { id: "prc_200_02", categoryId: "mu_prince", tier: 200, prompt: "What city is Prince from and remained loyal to throughout his career, building his Paisley Park studio there?", answer: "Minneapolis, Minnesota", acceptableAnswers: ["Minneapolis", "Minnesota"], explanation: "Unlike most artists who moved to LA or NYC, Prince stayed in Minneapolis and built his own creative empire." },
      { id: "prc_200_03", categoryId: "mu_prince", tier: 200, prompt: "What symbol did Prince change his name to in the 1990s during a dispute with his record label?", answer: "An unpronounceable 'Love Symbol' combining male and female symbols", acceptableAnswers: ["The Love Symbol", "An unpronounceable symbol", "The Artist Formerly Known As Prince symbol"], explanation: "He became 'The Artist Formerly Known As Prince' — a radical act of artistic rebellion against his label." },
      { id: "prc_400_01", categoryId: "mu_prince", tier: 400, prompt: "What is remarkable about Prince's musicianship on his early albums, particularly his debut 'For You'?", answer: "He played every single instrument and sang every vocal on the album — all 27 instruments credited, entirely self-performed at age 19", acceptableAnswers: ["Played all instruments himself at age 19", "One-man band on debut album", "Played 27 instruments solo"], explanation: "Prince's multi-instrumental talent was apparent from his first record." },
      { id: "prc_400_02", categoryId: "mu_prince", tier: 400, prompt: "What is the 'vault' at Paisley Park, and what is its significance to Prince's legacy?", answer: "A massive climate-controlled vault containing thousands of unreleased songs, albums, and videos — Prince recorded obsessively and released only a fraction of his output. Enough material reportedly exists for decades of posthumous releases", acceptableAnswers: ["Vault of thousands of unreleased songs", "Massive collection of unreleased recordings", "Storage of decades worth of unreleased music"], explanation: "The vault is estimated to contain enough music for 50+ years of posthumous albums." },
      { id: "prc_400_03", categoryId: "mu_prince", tier: 400, prompt: "What was Prince's legendary Super Bowl XLI halftime performance famous for?", answer: "He performed during actual pouring rain, playing 'Purple Rain' in the rain — considered the greatest Super Bowl halftime show ever. He also played a guitar solo silhouetted behind a giant sheet, creating an iconic visual", acceptableAnswers: ["Played Purple Rain in actual rain", "Performance in pouring rain at Super Bowl", "Rain performance with silhouette guitar solo"], explanation: "When asked if the rain would be a problem, Prince reportedly asked 'Can you make it rain harder?'" },
      { id: "prc_600_01", categoryId: "mu_prince", tier: 600, prompt: "What was Prince's battle with Warner Bros. over master ownership, and how did it influence the modern music industry?", answer: "Prince wrote 'SLAVE' on his cheek, changed his name to a symbol, and released deliberately uncommercial albums to escape his contract — he argued artists should own their masters. His fight presaged the modern debate about artist ownership (Taylor Swift, etc.) by decades", acceptableAnswers: ["SLAVE on cheek, fought for master ownership", "Name change and protest against label ownership", "Pioneer of artist ownership movement"], explanation: "Prince's 1990s battle was ahead of its time — artist ownership is now a central industry issue." },
      { id: "prc_600_02", categoryId: "mu_prince", tier: 600, prompt: "How did Prince famously handle the internet and music streaming differently from every other major artist?", answer: "He alternated between extremes — he was one of the first artists to release music exclusively online (1997), then became the most aggressive enforcer of copyright takedowns, removing virtually all his music from YouTube and streaming. He called the internet 'completely over' in 2010, then surprise-released albums on Tidal", acceptableAnswers: ["Early internet adopter then aggressive takedown enforcer", "Pioneered online releases then removed everything", "Internet pioneer who later pulled all music offline"], explanation: "Prince's contradictory relationship with the internet reflected his insistence on controlling his art absolutely." },
      { id: "prc_600_03", categoryId: "mu_prince", tier: 600, prompt: "What were the circumstances of Prince's death in 2016, and what systemic issue did it highlight?", answer: "He died of an accidental fentanyl overdose at age 57 — he had been taking counterfeit Vicodin pills that contained fentanyl without his knowledge. His death highlighted the counterfeit pill/fentanyl crisis that has since killed tens of thousands, and raised questions about celebrity medical care and pain management", acceptableAnswers: ["Accidental fentanyl in counterfeit pills", "Died from fake pills containing fentanyl", "Counterfeit Vicodin with fentanyl killed him"], explanation: "Prince's death brought national attention to the fentanyl-laced counterfeit pill epidemic." },
    ],
  },
  {
    id: "mu_amy_winehouse",
    group: "music",
    name: "Amy Winehouse",
    culture: "universal",
    description: "Back to black — jazz-soul genius, tabloid tragedy, and the 27 Club.",
    imageUrl: "",
    questions: [
      { id: "amw_200_01", categoryId: "mu_amy_winehouse", tier: 200, prompt: "What Amy Winehouse song about refusing to go to rehabilitation became her signature hit?", answer: "Rehab", explanation: "The song's defiant chorus reflected her real struggles with addiction." },
      { id: "amw_200_02", categoryId: "mu_amy_winehouse", tier: 200, prompt: "What was Amy Winehouse's second and final studio album, which won five Grammy Awards?", answer: "Back to Black", explanation: "Back to Black is one of the best-selling albums of the 21st century in the UK." },
      { id: "amw_200_03", categoryId: "mu_amy_winehouse", tier: 200, prompt: "At what age did Amy Winehouse die, joining the infamous '27 Club'?", answer: "27", explanation: "She died of alcohol poisoning in 2011, joining Hendrix, Morrison, Joplin, and Cobain." },
      { id: "amw_400_01", categoryId: "mu_amy_winehouse", tier: 400, prompt: "What musical genres did Amy Winehouse blend together to create her distinctive sound?", answer: "Jazz, soul, R&B, and ska/reggae — she combined 1960s girl group aesthetics with modern confessional songwriting", acceptableAnswers: ["Jazz soul R&B ska", "Jazz and soul with modern lyrics", "60s soul with confessional writing"], explanation: "Winehouse's voice and phrasing evoked Billie Holiday and Dinah Washington." },
      { id: "amw_400_02", categoryId: "mu_amy_winehouse", tier: 400, prompt: "Who produced 'Back to Black,' and what retro recording approach defined the album's sound?", answer: "Mark Ronson — they recorded with the Dap-Kings (Sharon Jones's band) at Daptone Studios in Brooklyn, using vintage equipment and analog recording to capture an authentic 1960s soul sound", acceptableAnswers: ["Mark Ronson with the Dap-Kings", "Ronson at Daptone Studios", "Mark Ronson with vintage recording approach"], explanation: "The collaboration between Winehouse's voice and the Dap-Kings' retro production was magical." },
      { id: "amw_400_03", categoryId: "mu_amy_winehouse", tier: 400, prompt: "What was the relationship between Amy's public struggles and the British tabloid press?", answer: "Tabloids relentlessly photographed and published her worst moments — addiction, fights, emaciation — turning her suffering into entertainment. The press coverage is widely seen as having worsened her condition rather than helping", acceptableAnswers: ["Tabloids exploited her addiction for entertainment", "Press made her suffering into content", "British tabloids worsened her condition"], explanation: "The documentary 'Amy' (2015) showed how tabloid harassment contributed to her spiral." },
      { id: "amw_600_01", categoryId: "mu_amy_winehouse", tier: 600, prompt: "What did Amy Winehouse's father Mitch do regarding her legacy that the 'Amy' documentary criticized?", answer: "The documentary showed Mitch appearing to prioritize commercial opportunities over Amy's wellbeing during her life, and after her death he established a foundation and participated in projects that some felt exploited her memory. He disputed the film's portrayal, calling it misleading", acceptableAnswers: ["Documentary criticized his commercialization of her legacy", "Accused of prioritizing business over her health", "Film showed him exploiting her memory"], explanation: "The documentary sparked debate about how families navigate grief, legacy, and commercialization." },
      { id: "amw_600_02", categoryId: "mu_amy_winehouse", tier: 600, prompt: "What makes 'Love Is a Losing Game' considered one of the greatest vocal performances ever recorded, according to music critics?", answer: "A devastatingly simple ballad where Winehouse's vocal control — the deliberate cracks, pauses, and restraint — conveys more emotion than technical perfection could. Tony Bennett called it the best vocal he'd ever heard, comparing her to Ella Fitzgerald and Billie Holiday", acceptableAnswers: ["Emotional restraint and vocal control praised by Bennett", "Simple ballad with devastating vocal performance", "Tony Bennett compared it to Fitzgerald and Holiday"], explanation: "The song demonstrates that great singing isn't about power — it's about communicating emotion." },
      { id: "amw_600_03", categoryId: "mu_amy_winehouse", tier: 600, prompt: "How did Amy Winehouse's Grammy wins for 'Back to Black' unfold, and why was the ceremony bittersweet?", answer: "She won five Grammys including Record and Song of the Year, but couldn't attend the US ceremony because she was denied a visa due to drug charges. She performed via satellite from London, visibly fragile — the contrast between artistic triumph and personal destruction was heartbreaking", acceptableAnswers: ["Won 5 Grammys but couldn't attend, performed via satellite", "Denied US visa, watched from London", "Visa denied from drug charges, satellite performance"], explanation: "The Grammy night encapsulated Winehouse's tragedy — the world celebrated her art while she suffered." },
    ],
  },
  {
    id: "vg_mass_effect",
    group: "video_games",
    name: "Mass Effect Trilogy",
    culture: "universal",
    description: "Commander Shepard — saving the galaxy one conversation at a time.",
    imageUrl: "",
    questions: [
      { id: "mse_200_01", categoryId: "vg_mass_effect", tier: 200, prompt: "What is the name of the player character who leads the fight against the Reapers across three games?", answer: "Commander Shepard", acceptableAnswers: ["Shepard", "Commander Shepard"], explanation: "Shepard can be male or female, with choices carrying across all three games." },
      { id: "mse_200_02", categoryId: "vg_mass_effect", tier: 200, prompt: "What ancient machine race threatens to exterminate all advanced organic life in the galaxy?", answer: "The Reapers", acceptableAnswers: ["Reapers"], explanation: "The Reapers harvest advanced civilizations every 50,000 years in a cyclical extinction." },
      { id: "mse_200_03", categoryId: "vg_mass_effect", tier: 200, prompt: "What is the name of Shepard's ship that serves as the player's hub throughout the trilogy?", answer: "The Normandy (SSV Normandy)", acceptableAnswers: ["Normandy", "SSV Normandy", "The Normandy"], explanation: "The Normandy is where Shepard's crew gathers and relationships develop between missions." },
      { id: "mse_400_01", categoryId: "vg_mass_effect", tier: 400, prompt: "What is the 'Paragon vs Renegade' system, and how does it differ from simple good/evil morality?", answer: "Paragon is diplomatic and compassionate; Renegade is ruthless and pragmatic — but both aim to save the galaxy. A Renegade Shepard isn't evil, just willing to make hard sacrifices for the greater good", acceptableAnswers: ["Diplomatic vs ruthless, both heroic", "Compassion vs pragmatism, not good vs evil", "Two heroic approaches, not morality binary"], explanation: "The system avoids the simplistic 'good/evil' binary of most RPGs." },
      { id: "mse_400_02", categoryId: "vg_mass_effect", tier: 400, prompt: "What devastating choice does Shepard face on Virmire involving two squadmates?", answer: "You must choose which squadmate to save — Ashley Williams or Kaidan Alenko — because you can only rescue one before the bomb detonates. The other dies permanently", acceptableAnswers: ["Choose between Ashley and Kaidan, one dies", "Save Ashley or Kaidan, other dies", "Virmire sacrifice choice"], explanation: "The Virmire choice was one of gaming's first truly permanent companion deaths." },
      { id: "mse_400_03", categoryId: "vg_mass_effect", tier: 400, prompt: "What happens to Shepard at the beginning of Mass Effect 2 that shocked players?", answer: "Shepard dies — the Normandy is destroyed and Shepard is killed in space. The Cerberus organization spends two years and billions of credits to resurrect them via the Lazarus Project", acceptableAnswers: ["Shepard dies and is resurrected", "Killed in space, rebuilt by Cerberus", "Dies and is brought back by Lazarus Project"], explanation: "Killing the protagonist in the opening minutes of a sequel was an incredibly bold narrative choice." },
      { id: "mse_600_01", categoryId: "vg_mass_effect", tier: 600, prompt: "What is the 'Suicide Mission' in Mass Effect 2, and how can every single squadmate die?", answer: "The final mission requires assigning the right people to the right roles (tech specialist, fire team leader, etc.) — wrong choices get specific people killed. If you didn't upgrade the Normandy or complete loyalty missions, additional squad members die. It's possible to lose everyone, including Shepard", acceptableAnswers: ["Wrong role assignments kill specific people", "All can die from wrong choices and unupgraded ship", "Every squadmate can die based on preparation and choices"], explanation: "The Suicide Mission is the gold standard for choice-consequence design in gaming." },
      { id: "mse_600_02", categoryId: "vg_mass_effect", tier: 600, prompt: "What was the Mass Effect 3 ending controversy, and how did BioWare respond?", answer: "The original endings reduced hundreds of hours of choices to three color-coded options (Destroy/Control/Synthesize) that felt nearly identical. Fans launched campaigns, petitions, and FTC complaints. BioWare released the free 'Extended Cut' DLC adding context and closure — one of gaming's first instances of fan pressure altering a finished product", acceptableAnswers: ["Three similar color-coded endings, fan backlash, Extended Cut DLC", "Endings ignored player choices, DLC added after protests", "Controversy over identical endings led to free DLC fix"], explanation: "The ending controversy remains the most significant fan-developer conflict in gaming history." },
      { id: "mse_600_03", categoryId: "vg_mass_effect", tier: 600, prompt: "What is the 'Indoctrination Theory' fan interpretation of Mass Effect 3's ending?", answer: "Fans theorized that Shepard's mind was being indoctrinated by the Reapers during the final sequence — the choice isn't real, it's the Reapers trying to trick Shepard into surrendering (Control/Synthesize) rather than Destroying them. Only Destroy is the 'real' ending. BioWare never confirmed or denied it", acceptableAnswers: ["Shepard was being mind-controlled by Reapers during ending", "Reapers indoctrinating Shepard, only Destroy is real", "Fan theory that ending choices are Reaper manipulation"], explanation: "Indoctrination Theory became one of gaming's most elaborate fan interpretations." },
    ],
  },
  {
    id: "vg_persona5",
    group: "video_games",
    name: "Persona 5",
    culture: "universal",
    description: "Phantom Thieves of Hearts — steal the corruption from society's rotten adults.",
    imageUrl: "",
    questions: [
      { id: "ps5_200_01", categoryId: "vg_persona5", tier: 200, prompt: "What is the Metaverse in Persona 5, and what do the Phantom Thieves do there?", answer: "A cognitive world where people's distorted desires manifest as palaces. The Phantom Thieves infiltrate palaces and steal the corrupt person's 'Treasure' to force a change of heart", acceptableAnswers: ["Cognitive world of desires, steal treasures for change of heart", "Mental world where desires become palaces", "Steal distorted desires to change hearts"], explanation: "The Metaverse makes psychological corruption into literal dungeons to explore." },
      { id: "ps5_200_02", categoryId: "vg_persona5", tier: 200, prompt: "What is the main character's code name as leader of the Phantom Thieves?", answer: "Joker", explanation: "Joker's real name is set by the player, though he's canonically named Ren Amamiya." },
      { id: "ps5_200_03", categoryId: "vg_persona5", tier: 200, prompt: "What daily life simulation aspect does Persona 5 blend with its dungeon-crawling RPG gameplay?", answer: "Players attend high school, build friendships (Confidants), study for exams, and manage daily activities — time management between social life and Phantom Thief duties is core to gameplay", acceptableAnswers: ["High school life simulation", "Social sim and dungeon RPG blend", "School life with time management"], explanation: "Persona's signature mix of social sim and JRPG makes every day matter." },
      { id: "ps5_400_01", categoryId: "vg_persona5", tier: 400, prompt: "What is the 'Confidant' system, and how does building relationships affect combat?", answer: "Confidants are social links with NPCs — spending time deepening these relationships unlocks combat bonuses, persona fusion abilities, and story content. Each confidant represents an Arcana from the Tarot", acceptableAnswers: ["Social relationships unlocking combat bonuses", "Tarot-based social links giving gameplay benefits", "NPC friendships tied to tarot and combat perks"], explanation: "The Confidant system rewards investing in characters with both story and mechanical depth." },
      { id: "ps5_400_02", categoryId: "vg_persona5", tier: 400, prompt: "What is Persona 5's visual style known for, and how does it extend to every interface element?", answer: "An explosive red-black-white color scheme with stylized anime art — even menus, loading screens, and transitions are elaborately animated. The UI design is considered the best in gaming, where every button press feels stylish", acceptableAnswers: ["Red-black-white stylized UI design", "Anime aesthetic extending to all menus", "Most stylish game interface ever made"], explanation: "Persona 5 proved that UI can be a game's defining artistic element." },
      { id: "ps5_400_03", categoryId: "vg_persona5", tier: 400, prompt: "What social themes does Persona 5 tackle through its villains' palaces?", answer: "Each palace ruler represents a form of societal corruption: an abusive teacher, a plagiarizing artist, a mafia boss exploiting youth, a corrupt CEO, a manipulative politician — the game critiques power structures that exploit vulnerable people", acceptableAnswers: ["Corruption: abuse, plagiarism, exploitation, corrupt politics", "Different forms of societal power abuse", "Adult corruption preying on youth"], explanation: "Persona 5's villains aren't fantasy monsters — they're recognizable types of real-world abusers." },
      { id: "ps5_600_01", categoryId: "vg_persona5", tier: 600, prompt: "What is the true nature of the Velvet Room prison in Persona 5, and what does its 'rehabilitation' theme reveal about the story?", answer: "The Velvet Room appears as a prison because Joker has been unjustly imprisoned by society — Igor (actually the false god Yaldabaoth in disguise) is manipulating both the Phantom Thieves and their enemies as pieces in a game. The 'rehabilitation' is the real Igor's attempt to help Joker break free of a rigged system", acceptableAnswers: ["Prison form reflects unjust imprisonment, Igor is fake", "Yaldabaoth impersonating Igor, rigged game", "False god manipulating both sides from Velvet Room"], explanation: "The Velvet Room's prison motif is the game's most layered metaphor — society itself is the cage." },
      { id: "ps5_600_02", categoryId: "vg_persona5", tier: 600, prompt: "How does Persona 5 Royal's additional semester and the character of Maruki challenge the Phantom Thieves' entire philosophy?", answer: "Dr. Maruki creates a 'perfect' reality where everyone's pain is erased — but at the cost of free will. The Phantom Thieves must reject a world where everyone is happy because it's built on a lie. It asks: if you could erase all suffering but people lose their autonomy, is that better? The Thieves choose painful freedom over comfortable illusion", acceptableAnswers: ["Must reject perfect fake reality for painful freedom", "Maruki's paradise removes free will", "Choose suffering with freedom over happy illusion"], explanation: "Maruki is the franchise's most sympathetic antagonist — his world is genuinely better, making the choice agonizing." },
      { id: "ps5_600_03", categoryId: "vg_persona5", tier: 600, prompt: "What is the significance of Persona 5's final palace being 'Mementos Depths' — the collective unconscious of all of Tokyo — and what does the public's reaction represent?", answer: "The public WANTS to be controlled — Mementos represents collective apathy and the desire for someone else to handle problems. The Phantom Thieves' final enemy isn't a single corrupt person but society's willingness to surrender autonomy. The game argues that apathy is the ultimate evil", acceptableAnswers: ["Public wants to be controlled, apathy is the enemy", "Collective unconscious shows societal submission", "Society's apathy is the real final boss"], explanation: "Persona 5's endgame transforms from fighting corrupt individuals to fighting collective complacency." },
    ],
  },
  {
    id: "mv_miyazaki_deep",
    group: "movies",
    name: "Hayao Miyazaki Deep Cuts",
    culture: "universal",
    description: "Beyond Spirited Away — the full filmography of animation's greatest master.",
    imageUrl: "",
    questions: [
      { id: "mzd_200_01", categoryId: "mv_miyazaki_deep", tier: 200, prompt: "What Studio Ghibli film features a girl riding a broomstick who loses her powers in a new city?", answer: "Kiki's Delivery Service", acceptableAnswers: ["Kiki's Delivery Service"], explanation: "Kiki's story about creative burnout and finding purpose resonates with adults and children alike." },
      { id: "mzd_200_02", categoryId: "mv_miyazaki_deep", tier: 200, prompt: "What Miyazaki film follows a young girl befriending forest spirits, including the large, sleeping Totoro?", answer: "My Neighbor Totoro", acceptableAnswers: ["Totoro", "My Neighbor Totoro"], explanation: "Totoro became Studio Ghibli's mascot and Japan's most beloved animated character." },
      { id: "mzd_200_03", categoryId: "mv_miyazaki_deep", tier: 200, prompt: "What environmental theme runs through nearly all of Miyazaki's films?", answer: "The relationship between humans and nature — typically showing industrialization destroying the natural world", acceptableAnswers: ["Humans vs nature", "Environmentalism", "Nature vs industrialization"], explanation: "Miyazaki's environmentalism is never preachy — it's woven into characters and worlds." },
      { id: "mzd_400_01", categoryId: "mv_miyazaki_deep", tier: 400, prompt: "What is unique about how Miyazaki writes and animates his films compared to most animated productions?", answer: "He starts animating before the screenplay is finished — he storyboards as he goes, often not knowing the ending when production begins. The story evolves organically through the animation process itself", acceptableAnswers: ["Animates without finished script", "Starts before knowing the ending", "Storyboards without completed screenplay"], explanation: "Miyazaki's process means his films feel like they're being discovered rather than constructed." },
      { id: "mzd_400_02", categoryId: "mv_miyazaki_deep", tier: 400, prompt: "In 'Princess Mononoke,' what is revolutionary about how the conflict between San and Lady Eboshi is presented?", answer: "Neither side is the villain — Eboshi provides jobs and freedom to women and lepers, while San protects the forest that Eboshi's iron works destroys. Miyazaki refuses to simplify complex issues into good vs evil", acceptableAnswers: ["Neither side is evil", "Both sides are justified", "No clear villain, both are sympathetic"], explanation: "Miyazaki's moral complexity is his greatest gift — he trusts audiences to handle ambiguity." },
      { id: "mzd_400_03", categoryId: "mv_miyazaki_deep", tier: 400, prompt: "What is 'The Wind Rises' about, and why was it controversial in Japan?", answer: "A fictionalized biography of Jiro Horikoshi, who designed the Zero fighter plane used in WWII — Japanese nationalists attacked it for being anti-war, while pacifists criticized it for romanticizing a weapon designer. Miyazaki, a committed pacifist, argued art can be beautiful even when created for terrible purposes", acceptableAnswers: ["Zero fighter designer biography, controversial for war themes", "Film about warplane designer attacked from both sides", "Jiro Horikoshi bio criticized by nationalists and pacifists"], explanation: "The Wind Rises is Miyazaki's most adult and morally complex film." },
      { id: "mzd_600_01", categoryId: "mv_miyazaki_deep", tier: 600, prompt: "What is Miyazaki's concept of 'ma' — the Japanese principle he uses in his films that Western animation typically lacks?", answer: "'Ma' means emptiness or pause — moments where nothing happens narratively, used to let the audience breathe and absorb atmosphere. Miyazaki deliberately includes scenes of characters just eating, traveling, or sitting quietly, because 'the time in between is important'", acceptableAnswers: ["Deliberate empty/pause moments in films", "Narrative pauses for breathing and atmosphere", "Japanese concept of meaningful emptiness"], explanation: "Ma is why Ghibli films feel different from Disney — the quiet moments are as important as the dramatic ones." },
      { id: "mzd_600_02", categoryId: "mv_miyazaki_deep", tier: 600, prompt: "How many times has Miyazaki 'retired' from filmmaking, and what does his relationship with retirement reveal about his creative philosophy?", answer: "He has announced retirement at least seven times (after Princess Mononoke, Spirited Away, Ponyo, The Wind Rises, and others) but keeps returning. He has said 'making films is what I live for' — his 2023 film 'The Boy and the Heron' came after his supposedly final retirement. He simply cannot stop creating", acceptableAnswers: ["Retired 7+ times but keeps returning", "Multiple fake retirements, can't stop creating", "At least 7 retirement announcements then came back"], explanation: "Miyazaki's retirements have become a running joke — the urge to create always wins." },
      { id: "mzd_600_03", categoryId: "mv_miyazaki_deep", tier: 600, prompt: "What is the autobiographical interpretation of 'The Boy and the Heron' (2023), and why is it considered Miyazaki's most personal film?", answer: "The film parallels Miyazaki's own life — a boy processing his mother's illness during WWII enters a fantastical tower built by a great-uncle (representing Miyazaki's creative legacy). The tower is collapsing, and the boy must choose whether to maintain it. It's Miyazaki asking whether his life's work matters and what he leaves behind", acceptableAnswers: ["Autobiographical about his legacy and mortality", "Personal film about whether his work matters", "Tower represents his creative legacy collapsing"], explanation: "At 82, Miyazaki made a film about a creator questioning whether their life's work means anything." },
    ],
  },
  {
    id: "his_industrial_revolution",
    group: "history",
    name: "The Industrial Revolution",
    culture: "universal",
    description: "Steam, steel, and suffering — the transformation that built the modern world.",
    imageUrl: "",
    questions: [
      { id: "ind_200_01", categoryId: "his_industrial_revolution", tier: 200, prompt: "What country did the Industrial Revolution begin in, starting in the mid-1700s?", answer: "England (Great Britain)", acceptableAnswers: ["England", "Britain", "Great Britain", "United Kingdom"], explanation: "Britain's combination of coal, iron, waterways, and colonial markets sparked industrialization." },
      { id: "ind_200_02", categoryId: "his_industrial_revolution", tier: 200, prompt: "What power source transformed manufacturing and transportation during the early Industrial Revolution?", answer: "Steam power (the steam engine)", acceptableAnswers: ["Steam", "Steam engine", "Steam power"], explanation: "James Watt's improved steam engine (1769) powered factories, mines, and eventually locomotives." },
      { id: "ind_200_03", categoryId: "his_industrial_revolution", tier: 200, prompt: "What industry was the first to be mechanized during the Industrial Revolution?", answer: "The textile industry (cotton manufacturing)", acceptableAnswers: ["Textiles", "Cotton", "Textile industry"], explanation: "Inventions like the spinning jenny and power loom mechanized cloth production." },
      { id: "ind_400_01", categoryId: "his_industrial_revolution", tier: 400, prompt: "What were the working conditions like in early industrial factories, particularly for children?", answer: "Children as young as 5-6 worked 12-16 hour days in dangerous conditions — climbing inside machines, working in mines, suffering injuries, lung diseases, and death. Child labor was standard until reform acts gradually restricted it", acceptableAnswers: ["Children worked 12-16 hour days in dangerous conditions", "Child labor from age 5-6 in factories and mines", "Deadly conditions with children in machines"], explanation: "The exploitation of children was one of industrialization's darkest chapters." },
      { id: "ind_400_02", categoryId: "his_industrial_revolution", tier: 400, prompt: "What were the 'Luddites,' and what did they actually want?", answer: "Skilled textile workers who destroyed machines not because they feared technology itself, but because factory owners used machines to replace skilled workers with cheaper unskilled labor, destroying their livelihoods", acceptableAnswers: ["Workers who broke machines over job loss", "Anti-machine workers protesting labor replacement", "Textile workers destroying job-killing machines"], explanation: "Luddites weren't anti-technology — they were anti-exploitation. The term is often misused today." },
      { id: "ind_400_03", categoryId: "his_industrial_revolution", tier: 400, prompt: "How did the railroad transform society beyond just transportation?", answer: "Railroads created standardized time zones (before trains, every town set its own clock), enabled national markets, transformed warfare, spurred steel production, created new social classes, and allowed people to live far from where they worked for the first time", acceptableAnswers: ["Created time zones, national markets, new social classes", "Standardized time, enabled commuting, transformed economy", "Time zones, markets, warfare, commuting"], explanation: "The railroad didn't just move goods faster — it restructured how humans experienced time and space." },
      { id: "ind_600_01", categoryId: "his_industrial_revolution", tier: 600, prompt: "What was the 'Great Stink' of 1858, and how did it transform public health infrastructure?", answer: "London's Thames River became so polluted with sewage during a hot summer that the smell shut down Parliament. The crisis finally forced the government to fund Joseph Bazalgette's massive sewer system — one of history's greatest engineering projects, which essentially ended cholera epidemics in London", acceptableAnswers: ["Thames sewage smell forced sewer construction", "Parliament shut down from river stink, led to sewers", "Stinking Thames led to Bazalgette's sewer system"], explanation: "It took literal stench reaching Parliament for politicians to fund public sanitation." },
      { id: "ind_600_02", categoryId: "his_industrial_revolution", tier: 600, prompt: "How did the Industrial Revolution create the concept of 'childhood' as we know it?", answer: "Before industrialization, children were simply small workers. Factory conditions were so horrific that reformers like Charles Dickens pushed for the idea that children deserved protection, education, and play. Child labor laws, compulsory schooling, and the concept of 'childhood innocence' are industrial-era inventions", acceptableAnswers: ["Factory horrors created concept of protecting children", "Child labor reform invented modern childhood", "Childhood as protected period was created by reform"], explanation: "The very idea that children shouldn't work is surprisingly recent — a reaction to industrial exploitation." },
      { id: "ind_600_03", categoryId: "his_industrial_revolution", tier: 600, prompt: "What is the 'Anthropocene' argument that links the Industrial Revolution to the current geological epoch?", answer: "Some scientists argue the Industrial Revolution marks the start of a new geological epoch — the Anthropocene — where human activity (particularly fossil fuel burning since ~1800) became the dominant force shaping Earth's geology, atmosphere, and ecosystems. The carbon we began releasing during industrialization is now altering the planet's climate, oceans, and biodiversity at geological scales", acceptableAnswers: ["Industrial Revolution started new geological epoch", "Fossil fuels began human-dominated geological era", "Industrialization started Anthropocene epoch"], explanation: "The Industrial Revolution may be the most consequential event in Earth's 4.5-billion-year history." },
    ],
  },
  {
    id: "sci_mathematics",
    group: "science",
    name: "Beautiful Mathematics",
    culture: "universal",
    description: "From zero to infinity — the numbers, proofs, and patterns behind reality.",
    imageUrl: "",
    questions: [
      { id: "mth_200_01", categoryId: "sci_mathematics", tier: 200, prompt: "What mathematical constant, approximately 3.14159, represents the ratio of a circle's circumference to its diameter?", answer: "Pi (π)", acceptableAnswers: ["Pi", "π", "3.14159"], explanation: "Pi is irrational — its digits never repeat or end." },
      { id: "mth_200_02", categoryId: "sci_mathematics", tier: 200, prompt: "What ancient Greek mathematician is famous for his theorem about right triangles (a² + b² = c²)?", answer: "Pythagoras", acceptableAnswers: ["Pythagoras", "Pythagorean theorem"], explanation: "The Pythagorean theorem is arguably the most important relationship in all of mathematics." },
      { id: "mth_200_03", categoryId: "sci_mathematics", tier: 200, prompt: "What number system, invented in India and transmitted through the Arab world, uses the symbol '0' and revolutionized mathematics?", answer: "The Hindu-Arabic numeral system (with zero)", acceptableAnswers: ["Hindu-Arabic numerals", "Arabic numerals with zero", "The decimal system with zero"], explanation: "The concept of zero as a number, not just a placeholder, was one of humanity's greatest intellectual achievements." },
      { id: "mth_400_01", categoryId: "sci_mathematics", tier: 400, prompt: "What is the Fibonacci sequence, and where does it appear in nature?", answer: "A sequence where each number is the sum of the two before it (1, 1, 2, 3, 5, 8, 13...) — it appears in flower petals, pinecone spirals, shell shapes, and branching patterns in trees", acceptableAnswers: ["Each number is sum of previous two, appears in nature", "1 1 2 3 5 8 13 pattern in flowers and shells", "Nature's number pattern in spirals and petals"], explanation: "The Fibonacci sequence's appearance in nature connects mathematics to biology in mysterious ways." },
      { id: "mth_400_02", categoryId: "sci_mathematics", tier: 400, prompt: "What did Euclid prove about prime numbers over 2,000 years ago that still holds true?", answer: "That there are infinitely many prime numbers — his proof by contradiction showed that no finite list of primes can be complete", acceptableAnswers: ["Infinite primes", "Primes are infinite", "There are infinitely many prime numbers"], explanation: "Euclid's proof is considered one of the most elegant in all of mathematics." },
      { id: "mth_400_03", categoryId: "sci_mathematics", tier: 400, prompt: "What is Euler's identity (e^(iπ) + 1 = 0), and why do mathematicians call it the most beautiful equation?", answer: "It connects five fundamental mathematical constants (e, i, π, 1, and 0) in a single elegant equation — linking exponential functions, imaginary numbers, circles, and basic arithmetic in an unexpected unity", acceptableAnswers: ["Connects five fundamental constants elegantly", "Links e, i, pi, 1, and 0 in one equation", "Five fundamental numbers connected in one formula"], explanation: "Richard Feynman called it 'the most remarkable formula in mathematics.'" },
      { id: "mth_600_01", categoryId: "sci_mathematics", tier: 600, prompt: "What is Gödel's Incompleteness Theorem, and why did it shatter the foundations of mathematics?", answer: "Kurt Gödel proved in 1931 that any consistent mathematical system complex enough to include arithmetic will contain true statements that cannot be proven within that system — mathematics can never be complete. You can't build a system that proves everything true about itself", acceptableAnswers: ["Math systems contain unprovable truths", "No complete consistent math system possible", "True statements exist that can't be proven"], explanation: "Gödel showed that the dream of a complete, self-proving mathematical foundation is impossible." },
      { id: "mth_600_02", categoryId: "sci_mathematics", tier: 600, prompt: "What is the Riemann Hypothesis, and why is it considered the most important unsolved problem in mathematics?", answer: "It conjectures that all non-trivial zeros of the Riemann zeta function lie on a specific line (real part = 1/2). If true, it would reveal deep structure in the distribution of prime numbers. It's been unproven since 1859 and carries a $1 million Millennium Prize", acceptableAnswers: ["Zeros of zeta function on critical line", "Prime number distribution conjecture since 1859", "Unsolved prime pattern problem worth $1 million"], explanation: "The Riemann Hypothesis connects the most abstract pure mathematics to the most fundamental objects — prime numbers." },
      { id: "mth_600_03", categoryId: "sci_mathematics", tier: 600, prompt: "What did Georg Cantor prove about infinity that caused a crisis in mathematics and drove him to a mental institution?", answer: "Cantor proved that some infinities are larger than others — the infinity of real numbers is 'bigger' than the infinity of whole numbers (uncountable vs countable infinity). This was so radical that prominent mathematicians attacked him personally, and the stress contributed to severe depression and institutionalization", acceptableAnswers: ["Some infinities are bigger than others", "Real numbers are a bigger infinity than whole numbers", "Different sizes of infinity drove him to breakdown"], explanation: "Cantor's work on transfinite numbers was initially rejected as 'mathematical insanity' before being accepted as foundational." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 76 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
