#!/usr/bin/env python3
"""Insert wave 72 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_black_mirror",
    group: "tv",
    name: "Black Mirror",
    culture: "universal",
    description: "The dark side of technology — each episode a standalone nightmare.",
    imageUrl: "",
    questions: [
      { id: "bkm_200_01", categoryId: "tv_black_mirror", tier: 200, prompt: "What does each episode of Black Mirror have in common structurally?", answer: "Each episode is a standalone story with different characters and settings, connected by the theme of technology's dark consequences", acceptableAnswers: ["Standalone episodes about technology", "Anthology about dark tech", "Different story each episode"], explanation: "Black Mirror is an anthology — no recurring characters (mostly), just recurring anxieties." },
      { id: "bkm_200_02", categoryId: "tv_black_mirror", tier: 200, prompt: "In 'Nosedive,' what social system controls everyone's life, affecting their housing, travel, and social standing?", answer: "A social rating system where everyone rates each other on a 1-5 scale after every interaction", acceptableAnswers: ["Social rating system", "Star rating system", "1-5 star social scores"], explanation: "The episode predates China's social credit system, making it eerily prescient." },
      { id: "bkm_200_03", categoryId: "tv_black_mirror", tier: 200, prompt: "What streaming platform revived Black Mirror from Channel 4, making it a global phenomenon?", answer: "Netflix", explanation: "Netflix picked up the show from Channel 4 starting with Season 3." },
      { id: "bkm_400_01", categoryId: "tv_black_mirror", tier: 400, prompt: "In 'San Junipero,' what is the twist about the reality that Yorkie and Kelly inhabit?", answer: "San Junipero is a simulated afterlife — the characters are elderly/dying people uploaded to a virtual beach town where they can live forever after death", acceptableAnswers: ["Virtual afterlife", "Simulated reality for the dying/dead", "Digital heaven"], explanation: "One of the show's rare happy endings — the couple chooses to live together in digital eternity." },
      { id: "bkm_400_02", categoryId: "tv_black_mirror", tier: 400, prompt: "In 'White Bear,' what is the horrifying twist about why the protagonist is being hunted while people film her?", answer: "She's a convicted child killer being punished — the 'hunt' is a daily justice park attraction where her memory is wiped each night so she relives the terror fresh every day", acceptableAnswers: ["She's a criminal in a punishment loop", "Memory-wiped daily punishment park", "Justice park where she relives terror daily"], explanation: "The episode forces viewers to question how far punitive justice should go." },
      { id: "bkm_400_03", categoryId: "tv_black_mirror", tier: 400, prompt: "What interactive Black Mirror episode lets the viewer make choices that affect the story's outcome?", answer: "Bandersnatch", acceptableAnswers: ["Black Mirror: Bandersnatch"], explanation: "The choose-your-own-adventure format created multiple endings and meta-commentary about free will." },
      { id: "bkm_600_01", categoryId: "tv_black_mirror", tier: 600, prompt: "In 'White Christmas,' what are 'cookies' and what ethical nightmare do they represent?", answer: "Digital copies of a person's consciousness — they're enslaved to perform tasks like being a smart home assistant, experiencing subjective years of solitary confinement as punishment. The episode asks whether torturing a copy of someone is morally equivalent to torturing the original", acceptableAnswers: ["Copied consciousness enslaved as digital servants", "Cloned minds tortured in digital prison", "Digital copies experiencing subjective eternity of punishment"], explanation: "The 'cookie' concept is Black Mirror's most disturbing technology — slavery of conscious copies." },
      { id: "bkm_600_02", categoryId: "tv_black_mirror", tier: 600, prompt: "What was the very first Black Mirror episode ('The National Anthem') about, and why did it cause walkouts when it aired?", answer: "The British Prime Minister is blackmailed into having sex with a pig on live television to save a kidnapped princess — viewers literally walked out thinking it couldn't be real television", acceptableAnswers: ["PM forced to have sex with pig on live TV", "Prime minister pig scene", "Pig blackmail episode"], explanation: "Creator Charlie Brooker said it was designed to make viewers complicit by watching, mirroring the in-show audience." },
      { id: "bkm_600_03", categoryId: "tv_black_mirror", tier: 600, prompt: "What real-world event made 'The National Anthem' seem prophetic years after it aired?", answer: "In 2015, it was reported that former UK PM David Cameron had put a private part of his body in a dead pig's mouth during a university initiation — matching the episode's premise in a surreal coincidence", acceptableAnswers: ["David Cameron pig story", "Cameron's university pig incident", "Real PM pig scandal matching the episode"], explanation: "Brooker said the real story was 'one of the most surreal moments of my life' — he had no idea when writing it." },
    ],
  },
  {
    id: "tv_arcane",
    group: "tv",
    name: "Arcane",
    culture: "universal",
    description: "Piltover and Zaun — sisters, shimmer, and the birth of legends.",
    imageUrl: "",
    questions: [
      { id: "arc_200_01", categoryId: "tv_arcane", tier: 200, prompt: "What popular video game is Arcane based on?", answer: "League of Legends", acceptableAnswers: ["League of Legends", "LoL"], explanation: "Arcane adapts the backstory of League of Legends champions." },
      { id: "arc_200_02", categoryId: "tv_arcane", tier: 200, prompt: "What are the names of the two sister protagonists whose relationship drives the show?", answer: "Vi and Jinx (Powder)", acceptableAnswers: ["Vi and Jinx", "Vi and Powder"], explanation: "Vi and Powder/Jinx's broken sisterhood is the emotional core of Arcane." },
      { id: "arc_200_03", categoryId: "tv_arcane", tier: 200, prompt: "What are the two cities in Arcane — the wealthy upper city and the oppressed underground?", answer: "Piltover (upper) and Zaun (undercity)", acceptableAnswers: ["Piltover and Zaun", "Zaun and Piltover"], explanation: "The class divide between Piltover and Zaun mirrors real-world inequality." },
      { id: "arc_400_01", categoryId: "tv_arcane", tier: 400, prompt: "What dangerous drug called 'shimmer' transforms users in the undercity, and who manufactures it?", answer: "Shimmer is a purple mutagen manufactured by Silco that enhances strength but causes addiction and physical mutation", acceptableAnswers: ["Purple mutagen by Silco", "Silco's mutation drug", "Silco manufactures shimmer"], explanation: "Shimmer represents the cycle of exploitation — the undercity's only resource weaponized against it." },
      { id: "arc_400_02", categoryId: "tv_arcane", tier: 400, prompt: "What animation studio created Arcane's distinctive visual style, and what technique combines 3D and 2D elements?", answer: "Fortiche Production — they use 3D character models with hand-painted textures and 2D effects, creating a look that resembles moving paintings", acceptableAnswers: ["Fortiche", "Fortiche Production", "3D with hand-painted textures"], explanation: "Fortiche spent over 6 years developing Arcane's unique visual style." },
      { id: "arc_400_03", categoryId: "tv_arcane", tier: 400, prompt: "What traumatic event in Jinx's childhood causes her psychological break and transforms Powder into Jinx?", answer: "Powder accidentally kills Mylo, Claggor, and Vander with a hextech-powered bomb while trying to help Vi — her adopted family dies because of her", acceptableAnswers: ["She accidentally kills her adopted family", "Accidentally bombs Vander Mylo and Claggor", "Her bomb kills her family"], explanation: "The moment Powder's attempt to help goes catastrophically wrong is the show's devastating turning point." },
      { id: "arc_600_01", categoryId: "tv_arcane", tier: 600, prompt: "What is the significance of Jinx's tea party scene in the Season 1 finale, and how does it parallel her internal conflict?", answer: "Jinx seats both Vi and Silco at a table with chairs for her dead friends (as mannequins), forcing a 'family dinner' between her two identities — Powder (Vi's sister) and Jinx (Silco's daughter). She's literally unable to choose which family she belongs to", acceptableAnswers: ["Tea party between two identities", "Family dinner forcing choice between Vi and Silco", "Powder vs Jinx identity crisis dinner"], explanation: "The tea party is a masterpiece of visual storytelling about fractured identity." },
      { id: "arc_600_02", categoryId: "tv_arcane", tier: 600, prompt: "How does Silco's final line — 'Don't cry. You're perfect' — to Jinx recontextualize his character as both villain and father figure?", answer: "Despite being the villain, Silco's dying words accept Jinx completely as she is — something Vi can't do because Vi keeps trying to bring back Powder. Silco becomes the only person who truly accepts Jinx", acceptableAnswers: ["He accepts Jinx fully, Vi can't", "His unconditional acceptance vs Vi wanting Powder back", "Only person who accepts Jinx as she is"], explanation: "The line transforms the audience's understanding of Silco — he genuinely loved Jinx as his daughter." },
      { id: "arc_600_03", categoryId: "tv_arcane", tier: 600, prompt: "In Season 2, what does Jinx's rocket to the Piltover council accomplish, and how does it mirror the series' opening tragedy?", answer: "Jinx fires a Hextech-powered rocket at the council chamber, mirroring how she accidentally destroyed her first family — but this time it's deliberate. It's Powder's tragedy rewritten as Jinx's declaration of war", acceptableAnswers: ["Council rocket mirrors accidental family bombing", "Deliberate attack mirroring childhood accident", "Intentional version of her childhood tragedy"], explanation: "The parallel between Powder's accident and Jinx's intentional attack shows how trauma becomes agency." },
    ],
  },
  {
    id: "mu_eminem",
    group: "music",
    name: "Eminem",
    culture: "american",
    description: "Slim Shady — Detroit's lyrical miracle who made controversy an art form.",
    imageUrl: "",
    questions: [
      { id: "emn_200_01", categoryId: "mu_eminem", tier: 200, prompt: "What is Eminem's alter ego persona known for dark humor and violent fantasies?", answer: "Slim Shady", acceptableAnswers: ["Slim Shady"], explanation: "The Slim Shady persona lets Eminem explore taboo topics through a fictional character." },
      { id: "emn_200_02", categoryId: "mu_eminem", tier: 200, prompt: "What semi-autobiographical movie did Eminem star in about a rapper trying to make it in Detroit?", answer: "8 Mile", explanation: "The film earned Eminem an Academy Award for 'Lose Yourself.'" },
      { id: "emn_200_03", categoryId: "mu_eminem", tier: 200, prompt: "What city is Eminem most associated with?", answer: "Detroit", acceptableAnswers: ["Detroit, Michigan"], explanation: "Detroit's struggles and resilience are central to Eminem's identity and music." },
      { id: "emn_400_01", categoryId: "mu_eminem", tier: 400, prompt: "What Eminem song tells the story of an obsessed fan who drives off a bridge with his pregnant girlfriend in the trunk?", answer: "Stan", explanation: "Stan became so influential that 'stan' entered the dictionary as a word for an obsessive fan." },
      { id: "emn_400_02", categoryId: "mu_eminem", tier: 400, prompt: "What is the name of Eminem's mentor and record label founder who discovered him?", answer: "Dr. Dre", acceptableAnswers: ["Dre", "Dr. Dre", "Andre Young"], explanation: "Dre signed Eminem to Aftermath Entertainment after hearing a demo tape." },
      { id: "emn_400_03", categoryId: "mu_eminem", tier: 400, prompt: "What was the significance of Eminem being a white rapper in a predominantly Black art form, and how did he address it?", answer: "He acknowledged his racial advantage in getting attention while proving his skill was genuine through freestyle battles and lyricism — he never claimed to be something he wasn't", acceptableAnswers: ["Acknowledged white privilege while proving skill", "Addressed race through authentic skill", "Proved himself through battles despite racial controversy"], explanation: "Eminem navigated race in hip-hop more honestly than most, earning respect through undeniable talent." },
      { id: "emn_600_01", categoryId: "mu_eminem", tier: 600, prompt: "What is the rhyme scheme technique Eminem uses called 'multisyllabic rhyming,' and how does the 'orange' example demonstrate it?", answer: "He rhymes multiple syllables across words rather than just end sounds — he famously showed that 'orange' can rhyme with 'door hinge,' 'four inch,' 'storage,' by matching vowel sounds across syllable clusters", acceptableAnswers: ["Multi-syllable rhyming, orange with door hinge", "Rhyming syllable clusters not just endings", "Orange/door hinge multisyllabic technique"], explanation: "Eminem's multisyllabic technique allows him to maintain complex rhyme patterns across entire verses." },
      { id: "emn_600_02", categoryId: "mu_eminem", tier: 600, prompt: "What happened at the 2000 Grammy Awards that made Eminem's performance with Elton John one of the most culturally significant moments in awards show history?", answer: "Amid massive protests over Eminem's homophobic lyrics, Elton John (an openly gay icon) performed 'Stan' with him and they hugged onstage — it was simultaneously a defense of artistic expression and a challenge to both sides of the culture war", acceptableAnswers: ["Performed Stan with Elton John amid homophobia protests", "Gay icon Elton John performed with him despite controversy", "Elton John duet as statement amid protests"], explanation: "The moment remains one of music's most complex cultural negotiations." },
      { id: "emn_600_03", categoryId: "mu_eminem", tier: 600, prompt: "What is the 'Rap God' section where Eminem raps at supersonic speed, and approximately how many words does he deliver per second in the fastest section?", answer: "The 'supersonic' section delivers approximately 6.5 words per second (97 words in 15 seconds), setting a Guinness World Record at the time for fastest rap in a hit single", acceptableAnswers: ["6+ words per second", "97 words in 15 seconds", "Guinness record fastest rap section"], explanation: "The technical feat demonstrated Eminem's rhythmic precision at an inhuman pace." },
    ],
  },
  {
    id: "mu_electronic_music",
    group: "music",
    name: "Electronic Music History",
    culture: "universal",
    description: "From Kraftwerk to EDM — the machines that made us dance.",
    imageUrl: "",
    questions: [
      { id: "elm_200_01", categoryId: "mu_electronic_music", tier: 200, prompt: "What German band, known for songs like 'Autobahn' and 'The Robots,' is considered the godfather of electronic music?", answer: "Kraftwerk", explanation: "Kraftwerk's pioneering synth-based music in the 1970s influenced virtually every electronic genre." },
      { id: "elm_200_02", categoryId: "mu_electronic_music", tier: 200, prompt: "What French electronic duo known for robot helmets created hits like 'Get Lucky,' 'Around the World,' and 'One More Time'?", answer: "Daft Punk", explanation: "Daft Punk's blend of house, funk, and pop made electronic music mainstream." },
      { id: "elm_200_03", categoryId: "mu_electronic_music", tier: 200, prompt: "What does 'EDM' stand for, and what decade saw it become a massive commercial force in American music?", answer: "Electronic Dance Music — it exploded commercially in the 2010s", acceptableAnswers: ["Electronic Dance Music, 2010s", "Electronic Dance Music"], explanation: "EDM festivals like Electric Daisy Carnival and Ultra became multi-million dollar events." },
      { id: "elm_400_01", categoryId: "mu_electronic_music", tier: 400, prompt: "What city is considered the birthplace of techno music, and which three producers are credited as its originators?", answer: "Detroit — Juan Atkins, Derrick May, and Kevin Saunderson (the Belleville Three)", acceptableAnswers: ["Detroit, Belleville Three", "Detroit — Atkins May Saunderson", "Detroit techno"], explanation: "Three high school friends from Belleville, Michigan invented techno in the mid-1980s." },
      { id: "elm_400_02", categoryId: "mu_electronic_music", tier: 400, prompt: "What is the difference between 'house' and 'techno' music in terms of their origins and sound?", answer: "House originated in Chicago (1980s), based on disco with soulful vocals and 4-on-the-floor beats; techno originated in Detroit, more industrial, mechanical, and stripped-down with fewer vocals", acceptableAnswers: ["House = Chicago soulful, Techno = Detroit industrial", "Chicago house vs Detroit techno", "Disco-based house vs industrial techno"], explanation: "Despite constant blending, the distinction between Chicago house and Detroit techno remains foundational." },
      { id: "elm_400_03", categoryId: "mu_electronic_music", tier: 400, prompt: "What synthesizer, released by Roland in 1981, became the defining sound of acid house and remains one of the most influential instruments in electronic music?", answer: "Roland TB-303", acceptableAnswers: ["TB-303", "Roland TB-303 Bass Line"], explanation: "Originally designed to simulate bass guitar, the 303's squelchy sound accidentally created acid house." },
      { id: "elm_600_01", categoryId: "mu_electronic_music", tier: 600, prompt: "What was the UK's Criminal Justice and Public Order Act 1994, and how did it specifically target electronic music?", answer: "The law defined illegal gatherings as events with 'sounds wholly or predominantly characterised by the emission of a succession of repetitive beats' — literally criminalizing raves by defining the music itself as illegal", acceptableAnswers: ["Banned repetitive beats at gatherings", "Criminalized raves by defining repetitive beats as illegal", "UK law targeting rave music specifically"], explanation: "The act's definition of banned music ('repetitive beats') was so absurd it became a rallying cry for the rave movement." },
      { id: "elm_600_02", categoryId: "mu_electronic_music", tier: 600, prompt: "What was the 'Second Summer of Love' in 1988-89 Britain, and how did acid house and MDMA transform British youth culture?", answer: "Inspired by Ibiza's club scene, British youth embraced acid house and ecstasy, creating massive illegal raves that united people across class and racial lines — it was the biggest youth culture explosion since punk", acceptableAnswers: ["Acid house rave movement in UK 1988-89", "Ibiza-inspired rave culture with ecstasy", "UK rave explosion uniting classes"], explanation: "The Second Summer of Love transformed British culture, fashion, and music permanently." },
      { id: "elm_600_03", categoryId: "mu_electronic_music", tier: 600, prompt: "How did the Roland TR-808 drum machine, a commercial failure upon release, become the most influential instrument in hip-hop and pop music history?", answer: "The 808 was discontinued in 1983 as a failure, but its deep analog bass drum became the foundation of Miami bass, trap, and modern hip-hop after producers bought them cheaply secondhand — its bass sound now defines mainstream pop", acceptableAnswers: ["Commercial failure bought cheap, became hip-hop foundation", "Failed drum machine became trap/hip-hop standard", "Cheap discontinued machine defined modern bass"], explanation: "The 808's bass kick is arguably the single most heard sound in 21st-century popular music." },
    ],
  },
  {
    id: "vg_bioshock",
    group: "video_games",
    name: "BioShock",
    culture: "universal",
    description: "Would you kindly... explore the ruins of Rapture and Columbia.",
    imageUrl: "",
    questions: [
      { id: "bio_200_01", categoryId: "vg_bioshock", tier: 200, prompt: "What is the name of the underwater city where the first BioShock takes place?", answer: "Rapture", explanation: "Rapture was built by Andrew Ryan as an objectivist utopia that collapsed into chaos." },
      { id: "bio_200_02", categoryId: "vg_bioshock", tier: 200, prompt: "What substance do players inject to gain superpowers like telekinesis and fire in BioShock?", answer: "Plasmids (using ADAM)", acceptableAnswers: ["Plasmids", "ADAM", "Plasmids via ADAM"], explanation: "Plasmids are genetic modifications powered by ADAM, a substance harvested from Little Sisters." },
      { id: "bio_200_03", categoryId: "vg_bioshock", tier: 200, prompt: "What massive diving-suit creatures protect the Little Sisters throughout Rapture?", answer: "Big Daddies", acceptableAnswers: ["Big Daddy", "Big Daddies"], explanation: "Big Daddies are genetically modified humans bonded to Little Sisters as protectors." },
      { id: "bio_400_01", categoryId: "vg_bioshock", tier: 400, prompt: "What is the famous twist in BioShock 1 involving the phrase 'Would you kindly'?", answer: "The player discovers that 'would you kindly' is a mind-control trigger phrase — Atlas/Fontaine has been controlling the player character the entire game through this phrase, meaning every instruction the player followed was compelled", acceptableAnswers: ["Mind control trigger phrase", "Player was being mind controlled", "Would you kindly is hypnotic command"], explanation: "The twist is also a meta-commentary on how players blindly follow instructions in games." },
      { id: "bio_400_02", categoryId: "vg_bioshock", tier: 400, prompt: "What political philosophy inspired Andrew Ryan's creation of Rapture, and which real-world philosopher is he a reference to?", answer: "Objectivism — Ryan is based on Ayn Rand (Andrew Ryan is an anagram of 'Ayn Rand' with extra letters). Rapture represents the failure of unregulated individualism", acceptableAnswers: ["Ayn Rand objectivism", "Objectivism, based on Ayn Rand", "Ayn Rand's philosophy"], explanation: "BioShock is fundamentally a critique of Ayn Rand's philosophy taken to its logical extreme." },
      { id: "bio_400_03", categoryId: "vg_bioshock", tier: 400, prompt: "In BioShock Infinite, what is the floating city of Columbia, and what ideology does it represent?", answer: "A city floating in the sky, founded on American exceptionalism and religious extremism by the prophet Comstock — it represents theocratic nationalism and racism", acceptableAnswers: ["Floating city of religious nationalism", "Sky city of American exceptionalism", "Theocratic nationalist floating city"], explanation: "Columbia is a dark mirror of early 20th century American imperialism and racial ideology." },
      { id: "bio_600_01", categoryId: "vg_bioshock", tier: 600, prompt: "What is the multiverse twist at the end of BioShock Infinite, and how does it connect to the original BioShock?", answer: "Booker DeWitt IS Comstock in another timeline — the 'baptism' is the branching point. Elizabeth drowns Booker at the baptism to eliminate all Comstock timelines. The Rapture DLC reveals the games share a multiverse", acceptableAnswers: ["Booker is Comstock, drowned at baptism", "Same person in different timelines", "Booker and Comstock are the same person"], explanation: "The ending collapses infinite timelines into a single moment of choice." },
      { id: "bio_600_02", categoryId: "vg_bioshock", tier: 600, prompt: "How does BioShock's 'Would you kindly' twist function as a critique of video game design itself?", answer: "It points out that players always follow quest markers and NPC instructions without question — the mind control in the story IS the player's relationship with the game. Every game controls you through 'would you kindly' instructions; BioShock just made it explicit", acceptableAnswers: ["Meta-critique of player obedience in games", "Players always follow game instructions like mind control", "Games control players just like Atlas controlled Jack"], explanation: "BioShock uses its narrative twist to ask whether players have ever truly had agency in a game." },
      { id: "bio_600_03", categoryId: "vg_bioshock", tier: 600, prompt: "What is the moral dilemma of the Little Sisters, and how did the developers' original plan for consequences differ from the final game?", answer: "Players choose to harvest (kill) or rescue Little Sisters for ADAM; originally, rescuing was meant to be significantly harder, making the moral choice mechanically punishing. The final game barely punishes rescuing, undermining the dilemma — Levine later admitted this was a design compromise", acceptableAnswers: ["Harvest vs rescue, meant to be harder to rescue", "Kill or save choice was meant to be more punishing", "Moral choice undermined by weak consequences"], explanation: "The rescue path giving nearly as much ADAM as harvesting weakened what could have been gaming's hardest moral choice." },
    ],
  },
  {
    id: "vg_pokemon_deep",
    group: "video_games",
    name: "Pokémon Deep Cuts",
    culture: "universal",
    description: "Beyond the Pokédex — competitive secrets, cut content, and pocket monster lore.",
    imageUrl: "",
    questions: [
      { id: "pkd_200_01", categoryId: "vg_pokemon_deep", tier: 200, prompt: "What are the original three starter Pokémon from Generation 1?", answer: "Bulbasaur, Charmander, and Squirtle", acceptableAnswers: ["Bulbasaur Charmander Squirtle"], explanation: "The grass/fire/water starter triangle has been a Pokémon tradition since 1996." },
      { id: "pkd_200_02", categoryId: "vg_pokemon_deep", tier: 200, prompt: "What glitch Pokémon appears when players perform the Cinnabar Island coast trick in Red and Blue?", answer: "MissingNo.", acceptableAnswers: ["MissingNo", "Missing No", "Missingno"], explanation: "MissingNo. is gaming's most famous glitch — it duplicates items and scrambles graphics." },
      { id: "pkd_200_03", categoryId: "vg_pokemon_deep", tier: 200, prompt: "How many original Pokémon were in Generation 1?", answer: "151", explanation: "The original 151 Pokémon, from Bulbasaur (#1) to Mew (#151)." },
      { id: "pkd_400_01", categoryId: "vg_pokemon_deep", tier: 400, prompt: "What are EVs and IVs in competitive Pokémon, and why do they matter?", answer: "IVs (Individual Values) are hidden stats determined at encounter; EVs (Effort Values) are earned by battling specific Pokémon. Together they determine a Pokémon's actual stats beyond its species base stats", acceptableAnswers: ["Hidden stat modifiers from birth and training", "Individual and Effort Values affecting stats", "IVs at birth, EVs from training"], explanation: "Competitive players breed for perfect IVs and carefully train EVs for optimal builds." },
      { id: "pkd_400_02", categoryId: "vg_pokemon_deep", tier: 400, prompt: "What dark Pokédex entry describes Phantump, and what does it imply happened to create this Pokémon?", answer: "Phantump is said to be the spirit of a child who died while lost in a forest — one of Pokémon's darkest lore entries", acceptableAnswers: ["Dead child's spirit", "Ghost of a lost child", "Child who died in the forest"], explanation: "Pokémon's Pokédex entries are surprisingly dark, especially for Ghost types." },
      { id: "pkd_400_03", categoryId: "vg_pokemon_deep", tier: 400, prompt: "What is the Masuda Method in Pokémon breeding, and what does it increase the chances of?", answer: "Breeding two Pokémon from different language games increases the chance of hatching a shiny Pokémon — named after Game Freak director Junichi Masuda who programmed it", acceptableAnswers: ["Cross-language breeding for shinies", "Foreign Pokémon breeding for shiny odds", "Different language breeding increases shiny rate"], explanation: "The Masuda Method is the primary way competitive players hunt for shiny Pokémon." },
      { id: "pkd_600_01", categoryId: "vg_pokemon_deep", tier: 600, prompt: "What was the 'Mew under the truck' rumor, and what actually happens at that location in Pokémon Red/Blue?", answer: "Players believed Mew was hidden under a truck near the S.S. Anne; the truck exists but does nothing — it's one of gaming's most persistent false rumors. Mew was actually accessible only through a glitch or official events", acceptableAnswers: ["Truck exists but no Mew, it's a false rumor", "Urban legend about truck hiding Mew", "Mew truck rumor was false"], explanation: "The truck is real but meaningless — generations of players tried Strength on it anyway." },
      { id: "pkd_600_02", categoryId: "vg_pokemon_deep", tier: 600, prompt: "What is the 'Pomeg Berry glitch' in Pokémon Emerald, and what exploit does it enable?", answer: "Using a Pomeg Berry when a Pokémon has 1-2 HP causes HP to underflow to 65535 — this creates a glitched 'egg' state that allows arbitrary code execution and cloning", acceptableAnswers: ["HP underflow glitch enabling code execution", "Berry causing HP underflow to 65535", "Stat underflow enabling arbitrary code execution"], explanation: "The Pomeg glitch chain eventually lets players manipulate the game's memory directly." },
      { id: "pkd_600_03", categoryId: "vg_pokemon_deep", tier: 600, prompt: "What was the 'Spaceworld 1997' demo leak, and what cut Pokémon designs were revealed?", answer: "A leaked early build of Pokémon Gold/Silver showed over 60 unused Pokémon designs including baby versions of existing Pokémon, scrapped evolutions, and entirely different starter designs — revealing how dramatically Gen 2 changed during development", acceptableAnswers: ["Leaked Gold/Silver beta with 60+ cut Pokémon", "Early Gen 2 build with unused designs", "Spaceworld demo showing scrapped Pokémon"], explanation: "The leak revealed a completely different version of Gen 2 with many Pokémon that never made it to release." },
    ],
  },
  {
    id: "mv_thriller",
    group: "movies",
    name: "Thriller & Mystery Films",
    culture: "universal",
    description: "Twists, suspense, and the films that keep you guessing until the last frame.",
    imageUrl: "",
    questions: [
      { id: "thr_200_01", categoryId: "mv_thriller", tier: 200, prompt: "In 'The Sixth Sense,' what famous twist is revealed about Bruce Willis's character at the end?", answer: "He has been dead the entire movie — he's a ghost who doesn't realize he died", acceptableAnswers: ["He's dead", "He was dead the whole time", "He's a ghost"], explanation: "M. Night Shyamalan's twist made audiences immediately want to rewatch for missed clues." },
      { id: "thr_200_02", categoryId: "mv_thriller", tier: 200, prompt: "What Alfred Hitchcock film features a man confined to a wheelchair who believes he witnessed a murder through his apartment window?", answer: "Rear Window", explanation: "Jimmy Stewart's voyeuristic thriller is a masterclass in suspense filmmaking." },
      { id: "thr_200_03", categoryId: "mv_thriller", tier: 200, prompt: "In 'Se7en,' what are the murders based on?", answer: "The seven deadly sins", acceptableAnswers: ["Seven deadly sins", "7 deadly sins"], explanation: "Each of John Doe's murders corresponds to a deadly sin: gluttony, greed, sloth, lust, pride, envy, and wrath." },
      { id: "thr_400_01", categoryId: "mv_thriller", tier: 400, prompt: "In 'Fight Club,' what is the twist about Tyler Durden's identity?", answer: "Tyler Durden and the Narrator are the same person — Tyler is the Narrator's dissociative alter personality", acceptableAnswers: ["Same person", "Tyler is the narrator's split personality", "Tyler doesn't exist, he's the narrator"], explanation: "The twist recontextualizes every scene in the film." },
      { id: "thr_400_02", categoryId: "mv_thriller", tier: 400, prompt: "In 'Memento,' what unique narrative structure does Christopher Nolan use to put the audience in the protagonist's shoes?", answer: "The story is told in reverse chronological order — each scene shows what happened BEFORE the previous scene, mimicking the protagonist's short-term memory loss", acceptableAnswers: ["Reverse chronological order", "Backwards narrative", "Scenes play in reverse order"], explanation: "The reverse structure means the audience, like Leonard, never knows what just happened." },
      { id: "thr_400_03", categoryId: "mv_thriller", tier: 400, prompt: "What is the final twist in 'The Usual Suspects' involving Keyser Söze?", answer: "Verbal Kint IS Keyser Söze — he fabricated his entire testimony to the police using names and details he spotted around the detective's office", acceptableAnswers: ["Verbal Kint is Keyser Söze", "He made up the story from office details", "Kint was Söze all along"], explanation: "Kevin Spacey's performance and the coffee cup reveal became one of cinema's greatest twists." },
      { id: "thr_600_01", categoryId: "mv_thriller", tier: 600, prompt: "In 'Se7en,' what was originally in the box, and how did David Fincher fight the studio to keep the ending?", answer: "The box contains Tracy's (Gwyneth Paltrow's) severed head; the studio wanted to cut this ending but Fincher and Brad Pitt both threatened to leave the project if it was changed", acceptableAnswers: ["Tracy's head, Fincher and Pitt fought to keep it", "Wife's head in box, director fought studio", "Severed head ending saved by Fincher/Pitt threats"], explanation: "The studio wanted a 'chase the villain' ending; Fincher's refusal to compromise created cinema's most devastating climax." },
      { id: "thr_600_02", categoryId: "mv_thriller", tier: 600, prompt: "What is the 'unreliable narrator' technique in 'Gone Girl,' and how does Gillian Flynn use it to manipulate both the characters and the audience?", answer: "Amy's diary entries appear honest but are revealed to be fabricated evidence she planted; the audience is deceived alongside Nick because Flynn withholds that the diary is a prop in Amy's scheme until the midpoint twist", acceptableAnswers: ["Amy's diary is fabricated evidence", "Fake diary entries deceive audience and characters", "Flynn uses planted diary to mislead everyone"], explanation: "Gone Girl's structure makes the audience complicit in Amy's frame job before revealing the deception." },
      { id: "thr_600_03", categoryId: "mv_thriller", tier: 600, prompt: "What is the significance of Denis Villeneuve's 'Prisoners' ending — is Keller Dover found?", answer: "The film ends with Detective Loki hearing a faint whistle from under the ground where Dover is trapped — but cuts to black before showing whether he investigates. The audience never sees the rescue, only the possibility of one", acceptableAnswers: ["Ambiguous ending, Loki may hear him", "Cuts to black before rescue shown", "Whistle heard but outcome unknown"], explanation: "Villeneuve deliberately leaves the audience in the same moral uncertainty the film explores throughout." },
    ],
  },
  {
    id: "his_ancient_greece",
    group: "history",
    name: "Ancient Greece",
    culture: "universal",
    description: "Democracy, philosophy, and the civilization that invented Western thought.",
    imageUrl: "",
    questions: [
      { id: "agr_200_01", categoryId: "his_ancient_greece", tier: 200, prompt: "What form of government did Athens pioneer that is now used around the world?", answer: "Democracy", acceptableAnswers: ["Democracy", "Direct democracy"], explanation: "Athenian democracy, established around 508 BC, was the world's first democratic system." },
      { id: "agr_200_02", categoryId: "his_ancient_greece", tier: 200, prompt: "What ancient sporting competition, held every four years in Greece, was revived in 1896?", answer: "The Olympic Games", acceptableAnswers: ["Olympics", "Olympic Games"], explanation: "The original Olympics were held in Olympia from 776 BC and included events like wrestling and chariot racing." },
      { id: "agr_200_03", categoryId: "his_ancient_greece", tier: 200, prompt: "What Greek philosopher was sentenced to death by drinking hemlock for 'corrupting the youth' of Athens?", answer: "Socrates", explanation: "Socrates chose death over exile, saying 'the unexamined life is not worth living.'" },
      { id: "agr_400_01", categoryId: "his_ancient_greece", tier: 400, prompt: "What was the Battle of Thermopylae, and which king led 300 Spartans in the famous last stand?", answer: "King Leonidas led 300 Spartans (plus allies) against the massive Persian army of Xerxes at the narrow pass of Thermopylae in 480 BC — they held for three days before being betrayed", acceptableAnswers: ["Leonidas and 300 Spartans vs Persians", "300 Spartans at Thermopylae", "Leonidas held the pass against Xerxes"], explanation: "The sacrifice at Thermopylae bought time for Greece to organize and eventually defeat Persia." },
      { id: "agr_400_02", categoryId: "his_ancient_greece", tier: 400, prompt: "What were the key differences between Sparta and Athens in terms of their values and social systems?", answer: "Athens valued democracy, philosophy, arts, and trade; Sparta valued military discipline, physical strength, and communal living — Spartan boys entered military training at age 7", acceptableAnswers: ["Athens = democracy/arts, Sparta = military/discipline", "Culture vs warfare", "Athens intellectual, Sparta militaristic"], explanation: "The Athens-Sparta rivalry shaped Greek history and gave us enduring archetypes." },
      { id: "agr_400_03", categoryId: "his_ancient_greece", tier: 400, prompt: "Who was Alexander the Great, and what did he accomplish before dying at age 32?", answer: "A Macedonian king who conquered an empire stretching from Greece to India — the largest empire the world had seen, spreading Greek culture across the ancient world (Hellenization)", acceptableAnswers: ["Conquered from Greece to India", "Created largest ancient empire", "Macedonian who conquered the known world"], explanation: "Alexander never lost a battle and created an empire that transformed the ancient world." },
      { id: "agr_600_01", categoryId: "his_ancient_greece", tier: 600, prompt: "What was the Antikythera mechanism, and why is it considered the world's first analog computer?", answer: "A corroded bronze device found in a 2000-year-old shipwreck that used over 30 interlocking gears to predict astronomical positions, eclipses, and Olympic game dates — technology this complex didn't appear again for over 1,000 years", acceptableAnswers: ["Ancient gear-based astronomical computer", "2000 year old astronomical prediction device", "Bronze gear computer from shipwreck"], explanation: "The Antikythera mechanism represents a level of technological sophistication we didn't think ancient Greeks possessed." },
      { id: "agr_600_02", categoryId: "his_ancient_greece", tier: 600, prompt: "What was the 'agoge' — the Spartan education system — and what brutal practices did it involve?", answer: "Boys were taken from families at age 7 for military training; they were deliberately underfed (expected to steal food but punished if caught), forced to sleep outdoors, fight each other, and at 18 joined the Krypteia — a secret police that hunted helots (slaves)", acceptableAnswers: ["Military training from age 7, starvation, Krypteia", "Child military indoctrination with starvation and slave hunting", "Boys taken at 7, trained through deprivation"], explanation: "The agoge produced formidable warriors but at the cost of individual freedom and humanity." },
      { id: "agr_600_03", categoryId: "his_ancient_greece", tier: 600, prompt: "What did Eratosthenes calculate in the 3rd century BC using shadows and basic geometry, and how accurate was his result?", answer: "He calculated the circumference of the Earth by comparing shadow angles in two cities at noon — his result (roughly 40,000 km) was within 2% of the actual value, using only sticks and geometry", acceptableAnswers: ["Earth's circumference, within 2% accuracy", "Calculated Earth's size using shadows", "Earth circumference using shadow angles"], explanation: "Over 2,200 years ago, with no technology, Eratosthenes figured out the size of the planet to remarkable accuracy." },
    ],
  },
  {
    id: "sci_quantum",
    group: "science",
    name: "Quantum Physics (Simplified)",
    culture: "universal",
    description: "The weird science that makes reality stranger than fiction.",
    imageUrl: "",
    questions: [
      { id: "qnt_200_01", categoryId: "sci_quantum", tier: 200, prompt: "What famous thought experiment involves a cat that is simultaneously alive and dead until observed?", answer: "Schrödinger's cat", acceptableAnswers: ["Schrodinger's cat", "Schrödinger's Cat"], explanation: "Schrödinger proposed it to illustrate the absurdity of quantum superposition at everyday scales." },
      { id: "qnt_200_02", categoryId: "sci_quantum", tier: 200, prompt: "What physicist is most associated with the theory of relativity and the equation E=mc²?", answer: "Albert Einstein", acceptableAnswers: ["Einstein"], explanation: "Einstein's theories revolutionized our understanding of space, time, and energy." },
      { id: "qnt_200_03", categoryId: "sci_quantum", tier: 200, prompt: "What is the basic idea of 'quantum superposition' — the concept that confused even Einstein?", answer: "A quantum particle can exist in multiple states simultaneously until it is measured/observed, at which point it 'collapses' into one definite state", acceptableAnswers: ["Multiple states until observed", "Particle in all states until measured", "Exists in multiple states simultaneously"], explanation: "Superposition is one of the most counterintuitive but experimentally confirmed phenomena in physics." },
      { id: "qnt_400_01", categoryId: "sci_quantum", tier: 400, prompt: "What is 'quantum entanglement,' which Einstein famously called 'spooky action at a distance'?", answer: "When two particles become entangled, measuring one instantly determines the state of the other regardless of distance — as if they communicate instantaneously", acceptableAnswers: ["Instant correlation between distant particles", "Measuring one particle instantly affects the other", "Connected particles at any distance"], explanation: "Entanglement has been experimentally confirmed and is the basis for quantum computing and encryption." },
      { id: "qnt_400_02", categoryId: "sci_quantum", tier: 400, prompt: "What is Heisenberg's Uncertainty Principle, and what does it say about what we can know about a particle?", answer: "You cannot simultaneously know both the exact position and exact momentum of a particle — the more precisely you measure one, the less precisely you can know the other", acceptableAnswers: ["Can't know position and momentum simultaneously", "Measuring one property makes the other uncertain", "Position and momentum can't both be precise"], explanation: "This isn't a measurement limitation — it's a fundamental property of nature." },
      { id: "qnt_400_03", categoryId: "sci_quantum", tier: 400, prompt: "What is the 'double-slit experiment,' and why does it show that particles behave as both waves and particles?", answer: "Shooting particles through two slits creates an interference pattern (wave behavior), but observing which slit they go through makes the pattern disappear (particle behavior) — observation changes the outcome", acceptableAnswers: ["Particles make wave pattern unless observed", "Observation changes wave to particle behavior", "Two slit interference changes when watched"], explanation: "The double-slit experiment is the most fundamental demonstration of quantum weirdness." },
      { id: "qnt_600_01", categoryId: "sci_quantum", tier: 600, prompt: "What is the 'many-worlds interpretation' of quantum mechanics, and how does it resolve the measurement problem?", answer: "Every quantum measurement causes the universe to split into branches — one for each possible outcome. The cat is alive in one universe and dead in another. There's no 'collapse'; all possibilities actually happen in parallel universes", acceptableAnswers: ["Universe splits at every measurement", "All quantum outcomes happen in parallel universes", "No wave function collapse, all outcomes real"], explanation: "Hugh Everett's interpretation avoids the collapse problem but requires accepting infinite parallel realities." },
      { id: "qnt_600_02", categoryId: "sci_quantum", tier: 600, prompt: "What is 'quantum tunneling,' and what everyday technology depends on it?", answer: "Particles can pass through barriers they classically shouldn't be able to cross, by 'tunneling' through them with a probability. Flash memory, scanning tunneling microscopes, and nuclear fusion in stars all depend on this effect", acceptableAnswers: ["Particles passing through barriers, used in flash memory", "Passing through impossible barriers, needed for nuclear fusion", "Barrier penetration used in electronics and stars"], explanation: "Without quantum tunneling, the Sun couldn't fuse hydrogen — and your USB drive wouldn't work." },
      { id: "qnt_600_03", categoryId: "sci_quantum", tier: 600, prompt: "What is the 'quantum eraser' experiment, and why does it seem to suggest that future choices can affect past events?", answer: "In a modified double-slit experiment, erasing which-path information AFTER a particle has already been detected restores the interference pattern — seemingly changing the past. It's actually about correlations, not time travel, but the implications are deeply strange", acceptableAnswers: ["Erasing info restores interference retroactively", "Future measurement seems to change past result", "Delayed choice appears to alter past outcomes"], explanation: "The quantum eraser doesn't actually change the past, but it demonstrates that quantum correlations defy our intuitions about time." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 72 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
