#!/usr/bin/env python3
"""Insert wave 63 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_succession_deep",
    group: "TV Shows",
    name: "Succession Deep Cuts",
    culture: "american",
    description: "The ruthless Roy family's battle for control of Waystar Royco — deep dives into the characters, themes, and real-world inspirations behind HBO's modern masterpiece.",
    imageUrl: "",
    questions: [
      {
        id: "scd_200_01",
        categoryId: "tv_succession_deep",
        tier: 200,
        prompt: "What is the name of the massive media conglomerate that the Roy family controls in Succession?",
        answer: "Waystar Royco",
        acceptableAnswers: ["Waystar RoyCo"],
      },
      {
        id: "scd_200_02",
        categoryId: "tv_succession_deep",
        tier: 200,
        prompt: "Who plays Logan Roy, the aging patriarch and founder of the Roy media empire?",
        answer: "Brian Cox",
        acceptableAnswers: [],
      },
      {
        id: "scd_200_03",
        categoryId: "tv_succession_deep",
        tier: 200,
        prompt: "How many Roy siblings are in the core succession battle?",
        answer: "Four — Kendall, Siobhan (Shiv), Roman, and Connor",
        acceptableAnswers: ["four", "4"],
      },
      {
        id: "scd_400_01",
        categoryId: "tv_succession_deep",
        tier: 400,
        prompt: "Succession's Logan Roy is widely understood to be inspired by which real-world media mogul?",
        answer: "Rupert Murdoch",
        acceptableAnswers: [],
        explanation: "Creator Jesse Armstrong drew on multiple moguls including Murdoch, Sumner Redstone, and Robert Maxwell, but Murdoch's Fox/News Corp empire is the clearest parallel.",
      },
      {
        id: "scd_400_02",
        categoryId: "tv_succession_deep",
        tier: 400,
        prompt: "In Season 1, Kendall's hostile takeover attempt fails catastrophically. What personal tragedy at the end of the season puts him completely under Logan's control?",
        answer: "He accidentally kills a waiter in a car accident while driving impaired, and Logan covers it up — giving Logan permanent leverage over him",
        acceptableAnswers: ["he kills someone in a car crash", "a car accident where a waiter dies", "he causes a drowning death"],
      },
      {
        id: "scd_400_03",
        categoryId: "tv_succession_deep",
        tier: 400,
        prompt: "What catchphrase does Logan Roy use when he's disgusted with someone, becoming one of the show's most iconic recurring lines?",
        answer: "F**k off",
        acceptableAnswers: ["fuck off"],
        explanation: "Logan's profane dismissals became the show's signature. Brian Cox delivered the line with such varied contempt that each instance carried different weight.",
      },
      {
        id: "scd_600_01",
        categoryId: "tv_succession_deep",
        tier: 600,
        prompt: "The Season 3 episode 'Too Much Birthday' is told primarily through a specific visual and narrative device at Kendall's 40th birthday party. What makes the episode's filmmaking distinctive?",
        answer: "The episode uses disorienting handheld cameras and constantly shifts between the lavish party and Kendall's increasing isolation, mirroring his mental breakdown through spatial storytelling — guests are always far from him",
        acceptableAnswers: ["it isolates Kendall visually from his own party", "the camera work emphasizes his loneliness at his birthday"],
      },
      {
        id: "scd_600_02",
        categoryId: "tv_succession_deep",
        tier: 600,
        prompt: "In the series finale, the siblings must vote on whether to approve the sale of Waystar Royco to GoJo. What decisive moment shatters the siblings' alliance and determines the outcome?",
        answer: "Shiv breaks the pact and votes to approve the deal, unable to accept Kendall as CEO — she touches his hand before voting against him",
        acceptableAnswers: ["Shiv votes against Kendall", "Shiv breaks the alliance and approves the sale"],
        explanation: "The hand touch is one of the most discussed moments in the finale — a gesture of love and destruction simultaneously, as Shiv decides her brother cannot be trusted with power.",
      },
      {
        id: "scd_600_03",
        categoryId: "tv_succession_deep",
        tier: 600,
        prompt: "Jesse Armstrong revealed that the Succession writers' room had a specific rule about the show's ending. What was it?",
        answer: "The ending had to be 'satisfying but not happy' — Armstrong planned from early on that none of the Roy children would end up running the company",
        acceptableAnswers: ["no Roy child would get the company", "none of the kids would win"],
        explanation: "Armstrong said the show was always about the damage of inherited wealth and power. Having any child 'win' would have undermined the entire thesis.",
      },
    ],
  },
  {
    id: "tv_mr_robot_deep",
    group: "TV Shows",
    name: "Mr. Robot Deep Cuts",
    culture: "american",
    description: "Sam Esmail's cyberthriller following Elliot Alderson, an unstable hacker who joins a revolutionary group — deep knowledge of the show's technical accuracy, visual storytelling, and twists.",
    imageUrl: "",
    questions: [
      {
        id: "mrb_200_01",
        categoryId: "tv_mr_robot_deep",
        tier: 200,
        prompt: "Who plays Elliot Alderson, the protagonist hacker in Mr. Robot?",
        answer: "Rami Malek",
        acceptableAnswers: [],
      },
      {
        id: "mrb_200_02",
        categoryId: "tv_mr_robot_deep",
        tier: 200,
        prompt: "What is the name of the hacktivist group that Elliot joins, named after their mysterious leader?",
        answer: "fsociety",
        acceptableAnswers: ["f society"],
      },
      {
        id: "mrb_200_03",
        categoryId: "tv_mr_robot_deep",
        tier: 200,
        prompt: "What massive corporation does fsociety target, aiming to erase all consumer debt?",
        answer: "E Corp (which Elliot's narration always calls 'Evil Corp')",
        acceptableAnswers: ["E Corp", "Evil Corp"],
      },
      {
        id: "mrb_400_01",
        categoryId: "tv_mr_robot_deep",
        tier: 400,
        prompt: "Mr. Robot is praised for its technical accuracy. The show employed a real cybersecurity consultant to ensure the hacking scenes were realistic. What makes the show's depiction of hacking unique compared to most TV shows?",
        answer: "All code, terminals, and hacking techniques shown on screen are real and technically accurate — actual exploits, real Linux commands, and genuine social engineering tactics",
        acceptableAnswers: ["real hacking techniques and code", "technically accurate hacking", "actual working exploits shown on screen"],
      },
      {
        id: "mrb_400_02",
        categoryId: "tv_mr_robot_deep",
        tier: 400,
        prompt: "The Season 1 twist reveals that Mr. Robot, the fsociety leader, is not a real person. Who is he actually?",
        answer: "He's a dissociative identity (alternate personality) of Elliot — a manifestation of Elliot's dead father, Edward Alderson",
        acceptableAnswers: ["Elliot's alternate personality", "Elliot's father in his mind", "a personality of Elliot's based on his dead father"],
      },
      {
        id: "mrb_400_03",
        categoryId: "tv_mr_robot_deep",
        tier: 400,
        prompt: "Sam Esmail uses a distinctive framing technique throughout the series where characters are positioned in an unusual part of the frame. What is this visual signature?",
        answer: "Characters are placed at the extreme bottom or edges of the frame with large amounts of empty space above them, emphasizing their powerlessness and isolation",
        acceptableAnswers: ["characters at the bottom of the frame", "extreme lower-third framing", "lots of headroom, characters pushed to edges"],
      },
      {
        id: "mrb_600_01",
        categoryId: "tv_mr_robot_deep",
        tier: 600,
        prompt: "Season 3, Episode 5 was a technical filmmaking landmark. What was remarkable about how the entire episode was shot?",
        answer: "It appears to be a single continuous take (oner) following multiple characters through the events of the 5/9 hack aftermath in real time",
        acceptableAnswers: ["filmed to look like one continuous shot", "a single-take episode", "it was shot as one long take"],
        explanation: "While it contains hidden cuts, the episode presents as an unbroken shot covering hours of story across multiple locations. Esmail directed the actors and crew through elaborately choreographed sequences.",
      },
      {
        id: "mrb_600_02",
        categoryId: "tv_mr_robot_deep",
        tier: 600,
        prompt: "Season 4, Episode 7 ('Proxy Authentication Required') takes an unexpected creative risk. What makes it structurally unlike any other episode of the series?",
        answer: "The entire episode is a therapy session/play — no hacking, no technology, just Elliot and Krista in a room, structured like a one-act play",
        acceptableAnswers: ["it's a bottle episode that's just a therapy session", "no hacking, just a therapy conversation"],
        explanation: "The episode confines the action to a single room and strips away all the show's technical elements, relying entirely on performance and dialogue to reveal Elliot's deepest trauma.",
      },
      {
        id: "mrb_600_03",
        categoryId: "tv_mr_robot_deep",
        tier: 600,
        prompt: "The series finale reveals that the Elliot we've been watching for four seasons is not the 'real' Elliot. What is the full explanation of the show's identity system?",
        answer: "The Elliot we followed is 'The Mastermind,' an alter personality who took over and locked the real Elliot in a perfect fantasy world (the sitcom-like reality). Other alters include Mr. Robot (protector), the Young Elliot (child), and the Mother (persecutor).",
        acceptableAnswers: ["the Elliot we watched was an alter called the Mastermind", "we were watching an alternate personality, not the real Elliot"],
        explanation: "The revelation recontextualizes the entire series — including why Elliot 'sees' the audience. We were another alter all along.",
      },
    ],
  },
  {
    id: "mv_ridley_scott",
    group: "Movies",
    name: "Ridley Scott",
    culture: "universal",
    description: "The legendary British director behind Alien, Blade Runner, Gladiator, and dozens of visually stunning films spanning every genre.",
    imageUrl: "",
    questions: [
      {
        id: "rsc_200_01",
        categoryId: "mv_ridley_scott",
        tier: 200,
        prompt: "What Ridley Scott film features Russell Crowe as a Roman general who is enslaved and becomes a gladiator seeking revenge?",
        answer: "Gladiator",
        acceptableAnswers: [],
      },
      {
        id: "rsc_200_02",
        categoryId: "mv_ridley_scott",
        tier: 200,
        prompt: "Ridley Scott directed two groundbreaking sci-fi films in the early 1980s: Alien (1979) and which 1982 film starring Harrison Ford?",
        answer: "Blade Runner",
        acceptableAnswers: [],
      },
      {
        id: "rsc_200_03",
        categoryId: "mv_ridley_scott",
        tier: 200,
        prompt: "What genre are most of Ridley Scott's most acclaimed films known for, featuring meticulous visual world-building?",
        answer: "Science fiction (and historical epic)",
        acceptableAnswers: ["sci-fi", "science fiction", "historical epic"],
      },
      {
        id: "rsc_400_01",
        categoryId: "mv_ridley_scott",
        tier: 400,
        prompt: "Before Gladiator, Scott directed a controversial war film in 2001 about a real U.S. military operation in Somalia. What was it?",
        answer: "Black Hawk Down",
        acceptableAnswers: [],
        explanation: "The film depicts the 1993 Battle of Mogadishu. Scott's visceral, documentary-like style made it one of the most intense war films of its era.",
      },
      {
        id: "rsc_400_02",
        categoryId: "mv_ridley_scott",
        tier: 400,
        prompt: "Scott directed a famous Apple Macintosh commercial that aired during the 1984 Super Bowl. What was the ad's concept and why was it groundbreaking?",
        answer: "It depicted a dystopian Orwellian world being shattered by a woman throwing a hammer through a giant screen — announcing the Macintosh as a tool of individual freedom against conformity",
        acceptableAnswers: ["the 1984 Apple ad with the hammer", "Orwellian dystopia ad for Macintosh"],
        explanation: "The ad, inspired by George Orwell's 1984, aired only once during the Super Bowl and is considered the greatest TV commercial ever made.",
      },
      {
        id: "rsc_400_03",
        categoryId: "mv_ridley_scott",
        tier: 400,
        prompt: "Scott's 1991 film 'Thelma & Louise' was a cultural landmark. What controversial ending sparked nationwide debate?",
        answer: "Thelma and Louise drive their car off a cliff into the Grand Canyon rather than surrender to police",
        acceptableAnswers: ["they drive off a cliff", "they drive into the Grand Canyon"],
        explanation: "The ending was debated as either empowering (they chose their fate) or nihilistic. The film launched Brad Pitt's career and became a feminist touchstone.",
      },
      {
        id: "rsc_600_01",
        categoryId: "mv_ridley_scott",
        tier: 600,
        prompt: "Before filmmaking, Ridley Scott had a successful career in another visual medium that heavily influenced his cinematic style. What was it?",
        answer: "He was a prolific TV commercial director — he directed thousands of ads over 15 years at his own production company, Ridley Scott Associates",
        acceptableAnswers: ["TV commercials", "advertising", "commercial directing"],
        explanation: "Scott's commercial background explains his extraordinary visual eye. He could create entire worlds in 30-second spots. His brother Tony Scott also came from the same background.",
      },
      {
        id: "rsc_600_02",
        categoryId: "mv_ridley_scott",
        tier: 600,
        prompt: "The original theatrical cut of 'Kingdom of Heaven' (2005) was considered a critical failure. What happened with the Director's Cut?",
        answer: "The Director's Cut added nearly 50 minutes of footage and was re-evaluated as a masterpiece — it's considered one of the largest quality gaps between a theatrical and director's cut in film history",
        acceptableAnswers: ["the director's cut was much longer and much better received", "50 extra minutes made it a masterpiece"],
        explanation: "The studio cut a subplot about Sibylla's son and much of the political nuance. The Director's Cut restores these and is now considered Scott's best historical epic alongside Gladiator.",
      },
      {
        id: "rsc_600_03",
        categoryId: "mv_ridley_scott",
        tier: 600,
        prompt: "Scott is famous for being exceptionally fast and efficient on set. What nickname have crew members given him due to his pace and his habit of watching multiple camera feeds simultaneously?",
        answer: "He's been called 'The Guv'nor' by British crews. He's also known for using enormous numbers of cameras simultaneously — sometimes 11 or more — and making decisions instantly from a bank of monitors.",
        acceptableAnswers: ["The Guv'nor", "he uses many cameras simultaneously"],
        explanation: "Scott's multi-camera approach lets him shoot coverage incredibly fast. On Napoleon (2023), he used up to 11 cameras simultaneously, a technique that baffles other directors.",
      },
    ],
  },
  {
    id: "mu_alice_in_chains",
    group: "Music",
    name: "Alice in Chains",
    culture: "american",
    description: "The darkest of Seattle's grunge titans, blending heavy metal riffs with haunting vocal harmonies and lyrics steeped in addiction and despair.",
    imageUrl: "",
    questions: [
      {
        id: "aic_200_01",
        categoryId: "mu_alice_in_chains",
        tier: 200,
        prompt: "Who was Alice in Chains' original lead vocalist, known for his haunting voice and tragic struggle with addiction?",
        answer: "Layne Staley",
        acceptableAnswers: ["Staley"],
      },
      {
        id: "aic_200_02",
        categoryId: "mu_alice_in_chains",
        tier: 200,
        prompt: "What Alice in Chains song opens with the lyric 'Yeah, they come to snuff the rooster' and was written about guitarist Jerry Cantrell's father's experience in Vietnam?",
        answer: "Rooster",
        acceptableAnswers: [],
      },
      {
        id: "aic_200_03",
        categoryId: "mu_alice_in_chains",
        tier: 200,
        prompt: "Alice in Chains is part of which music movement from the early 1990s?",
        answer: "Grunge",
        acceptableAnswers: ["Seattle grunge", "alternative rock"],
      },
      {
        id: "aic_400_01",
        categoryId: "mu_alice_in_chains",
        tier: 400,
        prompt: "Alice in Chains' vocal sound is distinctive because of the haunting harmony between Layne Staley and guitarist Jerry Cantrell. What makes their harmonies unusual compared to typical rock vocal harmonies?",
        answer: "They sang in very close intervals (often minor thirds) with a nasal, almost droning quality that created an eerie, dissonant blend rather than a bright pop harmony",
        acceptableAnswers: ["close minor harmonies", "dissonant close intervals", "they harmonized in unusually close and dark intervals"],
      },
      {
        id: "aic_400_02",
        categoryId: "mu_alice_in_chains",
        tier: 400,
        prompt: "The 'Jar of Flies' EP (1994) was groundbreaking. What chart record did it set?",
        answer: "It was the first EP ever to debut at number one on the Billboard 200",
        acceptableAnswers: ["first EP to debut at number one", "first #1 EP on Billboard 200"],
        explanation: "The acoustic-driven EP surprised everyone with its vulnerability. 'No Excuses' and 'I Stay Away' showed the band's range beyond heavy metal.",
      },
      {
        id: "aic_400_03",
        categoryId: "mu_alice_in_chains",
        tier: 400,
        prompt: "What was the last full concert Layne Staley performed with Alice in Chains, and why was it significant?",
        answer: "July 3, 1996, at the Kansas City Sandstone Amphitheater — it was Alice in Chains' final show with Staley, who became increasingly reclusive due to his heroin addiction",
        acceptableAnswers: ["July 1996", "1996, their last show together"],
        explanation: "After this show, Staley essentially withdrew from public life. He wouldn't perform again publicly until the 1996 MTV Unplugged taping.",
      },
      {
        id: "aic_600_01",
        categoryId: "mu_alice_in_chains",
        tier: 600,
        prompt: "Alice in Chains' 1996 MTV Unplugged performance is legendary but heartbreaking. What was visibly apparent about Layne Staley's physical condition during the taping?",
        answer: "Staley was visibly emaciated, had lost teeth, and his skin had deteriorated — the effects of severe heroin addiction were painfully obvious, and the performance had an air of finality",
        acceptableAnswers: ["he was visibly ill from drug addiction", "he looked very sick and thin", "severe physical deterioration from heroin"],
        explanation: "Despite his condition, Staley's vocals were remarkably strong. The performance is considered one of the greatest Unplugged sessions and one of the most poignant concerts ever recorded.",
      },
      {
        id: "aic_600_02",
        categoryId: "mu_alice_in_chains",
        tier: 600,
        prompt: "Layne Staley died on April 5, 2002. Two other major figures in grunge/alternative rock also died on April 5 in different years. Who were they?",
        answer: "Kurt Cobain (April 5, 1994) — making April 5 a doubly tragic date in grunge history",
        acceptableAnswers: ["Kurt Cobain"],
        explanation: "The coincidence of both dates being April 5 has been widely noted. Staley's body wasn't found until April 19, and his death was estimated to have occurred on April 5.",
      },
      {
        id: "aic_600_03",
        categoryId: "mu_alice_in_chains",
        tier: 600,
        prompt: "The self-titled album 'Alice in Chains' (1995, the tripod album) was recorded under extraordinary circumstances due to Staley's condition. What was unique about how the vocals were recorded?",
        answer: "Staley recorded his vocals largely alone, often at odd hours, with the studio left open for him to come in whenever he felt able — the band barely saw him during the process",
        acceptableAnswers: ["Staley recorded alone at odd hours", "he came in sporadically to record vocals", "the studio was left open for him to record whenever"],
        explanation: "Producer Toby Wright left the microphone and equipment set up so Staley could record whenever he showed up. Some of his most powerful vocal performances came from these isolated sessions.",
      },
    ],
  },
  {
    id: "vg_terraria",
    group: "Video Games",
    name: "Terraria",
    culture: "universal",
    description: "The 2D sandbox adventure that started as 'Minecraft in 2D' but evolved into one of gaming's deepest action-exploration experiences with a decade of free updates.",
    imageUrl: "",
    questions: [
      {
        id: "ter_200_01",
        categoryId: "vg_terraria",
        tier: 200,
        prompt: "Terraria is often compared to Minecraft, but what fundamental gameplay difference makes Terraria more of an action-adventure game?",
        answer: "Terraria has a strong focus on combat, boss fights, and progression through increasingly difficult enemies and gear tiers",
        acceptableAnswers: ["more combat and boss fights", "it focuses on combat and bosses", "progression through bosses"],
      },
      {
        id: "ter_200_02",
        categoryId: "vg_terraria",
        tier: 200,
        prompt: "What is the first major boss most players fight in Terraria, a giant floating eyeball?",
        answer: "Eye of Cthulhu",
        acceptableAnswers: ["Eye of Cthulhu"],
      },
      {
        id: "ter_200_03",
        categoryId: "vg_terraria",
        tier: 200,
        prompt: "Terraria has been in active development since 2011 with massive free updates. Who is the game's creator?",
        answer: "Andrew Spinks (Re-Logic)",
        acceptableAnswers: ["Andrew Spinks", "Re-Logic", "Redigit"],
      },
      {
        id: "ter_400_01",
        categoryId: "vg_terraria",
        tier: 400,
        prompt: "Defeating the Wall of Flesh boss triggers a massive game-changing event. What happens to the world?",
        answer: "The world enters Hardmode — new ores appear, biomes start spreading aggressively, much harder enemies spawn, and new bosses become available",
        acceptableAnswers: ["Hardmode begins", "the world enters Hardmode", "everything gets much harder"],
        explanation: "Hardmode essentially doubles the game's content. The Corruption/Crimson and Hallow biomes begin consuming the world, creating urgency.",
      },
      {
        id: "ter_400_02",
        categoryId: "vg_terraria",
        tier: 400,
        prompt: "What are the two opposing evil biomes that can generate in a Terraria world, each with their own unique enemies, resources, and bosses?",
        answer: "The Corruption and the Crimson",
        acceptableAnswers: ["Corruption and Crimson"],
        explanation: "Each world randomly generates one or the other (or players can choose). They have different aesthetics, ores, bosses, and loot, encouraging multiple playthroughs.",
      },
      {
        id: "ter_400_03",
        categoryId: "vg_terraria",
        tier: 400,
        prompt: "Terraria features class-based builds even though there's no formal class system. What are the four main 'classes' the community recognizes?",
        answer: "Melee, Ranged, Magic, and Summoner",
        acceptableAnswers: ["melee, ranged, magic, summoner"],
      },
      {
        id: "ter_600_01",
        categoryId: "vg_terraria",
        tier: 600,
        prompt: "The Moon Lord is Terraria's final boss and has a direct connection to H.P. Lovecraft's mythology. What Lovecraftian entity is the Moon Lord heavily based on?",
        answer: "Cthulhu — the Moon Lord is essentially Cthulhu himself, and several earlier bosses (Eye of Cthulhu, Brain of Cthulhu) are pieces of him",
        acceptableAnswers: ["Cthulhu"],
        explanation: "The lore suggests the Moon Lord/Cthulhu was defeated in an ancient battle that scattered his body parts, which became the game's bosses. The Dryads fought him originally.",
      },
      {
        id: "ter_600_02",
        categoryId: "vg_terraria",
        tier: 600,
        prompt: "Terraria has sold over 58 million copies as of 2024, making it one of the best-selling games ever. The game was famously 'finished' multiple times before receiving more updates. How many times has the final update been announced?",
        answer: "At least three times — the game has repeatedly had 'final' updates (1.3, 1.4, 1.4.4) before Re-Logic came back with more content",
        acceptableAnswers: ["multiple times", "at least three times", "several times"],
        explanation: "The running joke in the Terraria community is that the game can never truly end. Each 'final update' has been followed by another substantial content addition.",
      },
      {
        id: "ter_600_03",
        categoryId: "vg_terraria",
        tier: 600,
        prompt: "Terraria had a brief conflict with Minecraft's creator Notch in the early days. What happened, and how was it resolved?",
        answer: "Notch and Re-Logic were developing a crossover (Steve in Terraria, Terraria characters in Minecraft). After a public disagreement, the crossover was cancelled, but both developers later moved on amicably.",
        acceptableAnswers: ["a cancelled crossover with Minecraft", "planned crossover that fell through"],
        explanation: "Early builds of Terraria actually contained a 'Steve' NPC and creeper costume. The crossover content was removed after the falling out but the relationship between the games' communities remained friendly.",
      },
    ],
  },
  {
    id: "vg_zelda_oot",
    group: "Video Games",
    name: "Zelda: Ocarina of Time",
    culture: "universal",
    description: "The 1998 Nintendo 64 masterpiece that defined 3D adventure gaming — deep knowledge of its design, secrets, and legendary speedrunning scene.",
    imageUrl: "",
    questions: [
      {
        id: "oot_200_01",
        categoryId: "vg_zelda_oot",
        tier: 200,
        prompt: "In Ocarina of Time, Link travels between two time periods. What are they?",
        answer: "Child Link (7 years old) and Adult Link (7 years later)",
        acceptableAnswers: ["child and adult", "past and future", "young Link and adult Link"],
      },
      {
        id: "oot_200_02",
        categoryId: "vg_zelda_oot",
        tier: 200,
        prompt: "What instrument does Link play in Ocarina of Time to trigger various magical effects?",
        answer: "The Ocarina of Time",
        acceptableAnswers: ["an ocarina", "the ocarina"],
      },
      {
        id: "oot_200_03",
        categoryId: "vg_zelda_oot",
        tier: 200,
        prompt: "What is the name of the primary villain in Ocarina of Time, the Gerudo King of Thieves?",
        answer: "Ganondorf",
        acceptableAnswers: ["Ganon"],
      },
      {
        id: "oot_400_01",
        categoryId: "vg_zelda_oot",
        tier: 400,
        prompt: "The Water Temple is infamously difficult and confusing. What specific design element frustrated players the most?",
        answer: "Constantly pausing to equip and unequip the Iron Boots (which were a menu item, not a quick-toggle) and the confusing multi-level water raising puzzle",
        acceptableAnswers: ["equipping iron boots through the menu", "the iron boots and water level changes", "boot swapping through the pause menu"],
        explanation: "The 3DS remake addressed this by making the Iron Boots a quick-equip item and adding visual guides for the water levels.",
      },
      {
        id: "oot_400_02",
        categoryId: "vg_zelda_oot",
        tier: 400,
        prompt: "Ocarina of Time introduced a revolutionary targeting system that became standard for 3D action games. What is it called?",
        answer: "Z-targeting (L-targeting in later versions)",
        acceptableAnswers: ["Z-targeting", "Z targeting", "L-targeting"],
        explanation: "Z-targeting let players lock onto enemies and strafe around them. Before this, 3D combat was chaotic. Nearly every 3D action game since has borrowed this concept.",
      },
      {
        id: "oot_400_03",
        categoryId: "vg_zelda_oot",
        tier: 400,
        prompt: "What is Navi, and why did she become one of the most polarizing characters in gaming history?",
        answer: "Navi is Link's fairy companion who provides hints and targeting assistance. Players found her constant 'Hey! Listen!' interruptions incredibly annoying",
        acceptableAnswers: ["a fairy that says Hey Listen constantly", "Link's annoying fairy guide"],
      },
      {
        id: "oot_600_01",
        categoryId: "vg_zelda_oot",
        tier: 600,
        prompt: "The OoT speedrunning community discovered a glitch called 'Wrong Warp' that allows beating the game in under 10 minutes. How does it work at a high level?",
        answer: "By manipulating the game's internal scene table through specific item and entrance combinations, Link can warp from an early dungeon directly to the Ganon fight credits sequence",
        acceptableAnswers: ["manipulating the scene loading to warp to the end", "wrong warping from Deku Tree to the credits", "glitching the scene transition system"],
        explanation: "Wrong Warp exploits how the game loads scenes. By performing specific actions in Ganondorf's Tower collapse sequence (or earlier dungeons in newer routes), the game loads the wrong destination.",
      },
      {
        id: "oot_600_02",
        categoryId: "vg_zelda_oot",
        tier: 600,
        prompt: "Ocarina of Time originally had more dungeons planned that were cut. Evidence of one cut dungeon was discovered in the game's code. What was it?",
        answer: "The Wind Temple and Ice Temple (remnants found in code), plus a planned Unicorn Fountain that was cut — and the original Temple of Light was planned as a playable dungeon rather than just a cutscene location",
        acceptableAnswers: ["Wind Temple", "Ice Temple", "Temple of Light was supposed to be playable"],
        explanation: "Data miners have found references to cut content including dungeon maps and items. The Temple of Light in the Sacred Realm was originally a full dungeon.",
      },
      {
        id: "oot_600_03",
        categoryId: "vg_zelda_oot",
        tier: 600,
        prompt: "The original N64 version of Ocarina of Time contained content that was changed in later cartridge revisions. What was altered in the Fire Temple and why?",
        answer: "The original Fire Temple music contained sampled Islamic prayer chanting (from a commercial sound library). Nintendo changed it in later cartridge versions (v1.2+) to avoid religious offense.",
        acceptableAnswers: ["Islamic chanting in the Fire Temple music was removed", "the Fire Temple had Muslim prayer samples that were changed"],
        explanation: "Early gold cartridges contain the original chanting. Later grey cartridges and all subsequent versions use different music. Original cartridges are collector's items partly because of this.",
      },
    ],
  },
  {
    id: "his_samurai",
    group: "History",
    name: "Samurai & Feudal Japan",
    culture: "universal",
    description: "The warrior class that shaped Japanese history for centuries — from the rise of the shogunate to bushido, famous battles, and the dramatic end of the samurai era.",
    imageUrl: "",
    questions: [
      {
        id: "sam_200_01",
        categoryId: "his_samurai",
        tier: 200,
        prompt: "What was the code of honor that governed the samurai's way of life, emphasizing loyalty, discipline, and honor in death?",
        answer: "Bushido",
        acceptableAnswers: ["bushido", "the way of the warrior"],
      },
      {
        id: "sam_200_02",
        categoryId: "his_samurai",
        tier: 200,
        prompt: "What is the name of the curved sword that became the iconic weapon of the samurai?",
        answer: "Katana",
        acceptableAnswers: [],
      },
      {
        id: "sam_200_03",
        categoryId: "his_samurai",
        tier: 200,
        prompt: "What was the title of the military dictator who effectively ruled Japan while the Emperor served as a figurehead?",
        answer: "Shogun",
        acceptableAnswers: [],
      },
      {
        id: "sam_400_01",
        categoryId: "his_samurai",
        tier: 400,
        prompt: "Seppuku (ritual suicide) was an important part of samurai culture. Why would a samurai perform seppuku?",
        answer: "To preserve honor after defeat, failure, or disgrace — it was considered more honorable than capture, and could also be ordered as a form of capital punishment",
        acceptableAnswers: ["to preserve honor", "to avoid dishonor after defeat", "honorable death instead of capture"],
      },
      {
        id: "sam_400_02",
        categoryId: "his_samurai",
        tier: 400,
        prompt: "The Battle of Sekigahara in 1600 was the decisive battle that led to the establishment of which shogunate, which would rule Japan for over 250 years?",
        answer: "The Tokugawa Shogunate",
        acceptableAnswers: ["Tokugawa"],
        explanation: "Tokugawa Ieyasu's victory at Sekigahara unified Japan and began the Edo period — 250 years of peace that eventually led to the samurai's obsolescence.",
      },
      {
        id: "sam_400_03",
        categoryId: "his_samurai",
        tier: 400,
        prompt: "Miyamoto Musashi is considered Japan's greatest swordsman. What is the name of his famous treatise on strategy and martial arts?",
        answer: "The Book of Five Rings (Go Rin No Sho)",
        acceptableAnswers: ["The Book of Five Rings", "Go Rin no Sho"],
        explanation: "Written in 1645, the book covers strategy, tactics, and philosophy. Musashi was undefeated in over 60 duels and also developed a two-sword fighting technique.",
      },
      {
        id: "sam_600_01",
        categoryId: "his_samurai",
        tier: 600,
        prompt: "The Satsuma Rebellion of 1877 was the last stand of the samurai against the modernizing Meiji government. Who led the rebellion, and what was his fate?",
        answer: "Saigō Takamori led the rebellion. After the samurai were defeated by the conscript army, he died — traditionally said to have committed seppuku after being wounded",
        acceptableAnswers: ["Saigo Takamori", "Saigo, he died by seppuku"],
        explanation: "Saigō is the inspiration for the film The Last Samurai. Despite being a rebel, he was posthumously pardoned and is celebrated as one of Japan's greatest heroes.",
      },
      {
        id: "sam_600_02",
        categoryId: "his_samurai",
        tier: 600,
        prompt: "The 47 Rōnin incident of 1702-1703 is Japan's most famous tale of samurai loyalty. What happened, and why is it so significant in Japanese culture?",
        answer: "47 masterless samurai spent nearly two years planning revenge for their lord Asano's forced seppuku, then assassinated the official Kira Yoshinaka responsible. They then turned themselves in and were ordered to commit seppuku.",
        acceptableAnswers: ["47 samurai avenged their lord then committed seppuku", "ronin avenged their master's death then were ordered to kill themselves"],
        explanation: "The incident is celebrated as the ultimate example of bushido loyalty. The rōnin are buried at Sengaku-ji temple in Tokyo, which is still visited today.",
      },
      {
        id: "sam_600_03",
        categoryId: "his_samurai",
        tier: 600,
        prompt: "Contrary to popular belief, samurai were not exclusively swordsmen. What ranged weapon did many samurai consider their primary weapon, especially in earlier periods?",
        answer: "The yumi (longbow) — mounted archery (yabusame) was the original elite samurai combat art, predating the katana's cultural prominence",
        acceptableAnswers: ["the bow", "yumi", "longbow", "mounted archery"],
        explanation: "Early samurai were primarily horse archers. The sword became culturally dominant during the Edo period's long peace, when actual battlefield combat was rare.",
      },
    ],
  },
  {
    id: "sci_forensics",
    group: "Science",
    name: "Forensic Science",
    culture: "universal",
    description: "The real science behind crime-solving — from DNA analysis and ballistics to digital forensics and the famous cases that shaped the field.",
    imageUrl: "",
    questions: [
      {
        id: "for_200_01",
        categoryId: "sci_forensics",
        tier: 200,
        prompt: "What type of evidence, unique to every individual except identical twins, revolutionized criminal identification after it was first used in a 1986 UK murder case?",
        answer: "DNA evidence",
        acceptableAnswers: ["DNA", "DNA fingerprinting"],
      },
      {
        id: "for_200_02",
        categoryId: "sci_forensics",
        tier: 200,
        prompt: "What are the unique ridge patterns on the tips of your fingers called, which have been used for criminal identification since the late 1800s?",
        answer: "Fingerprints",
        acceptableAnswers: [],
      },
      {
        id: "for_200_03",
        categoryId: "sci_forensics",
        tier: 200,
        prompt: "What is the study of insects found on decomposing remains called, used to estimate time of death?",
        answer: "Forensic entomology",
        acceptableAnswers: ["entomology"],
      },
      {
        id: "for_400_01",
        categoryId: "sci_forensics",
        tier: 400,
        prompt: "The 'CSI Effect' is a well-documented phenomenon. What is it?",
        answer: "Jurors in real trials expect the same level of forensic evidence shown in TV crime dramas, sometimes acquitting when 'expected' evidence like DNA isn't presented even when other evidence is strong",
        acceptableAnswers: ["jurors expect TV-level forensic evidence", "juries expect CSI-like evidence in real cases"],
      },
      {
        id: "for_400_02",
        categoryId: "sci_forensics",
        tier: 400,
        prompt: "Luminol is a chemical used at crime scenes that reacts with hemoglobin in blood. What does it produce when it contacts blood?",
        answer: "A blue chemiluminescent glow visible in darkness",
        acceptableAnswers: ["it glows blue", "blue glow", "a blue light"],
        explanation: "Luminol can detect blood that has been cleaned or diluted, even years after the fact. However, it can also react with other substances, producing false positives.",
      },
      {
        id: "for_400_03",
        categoryId: "sci_forensics",
        tier: 400,
        prompt: "What are the four primary stages of decomposition that forensic pathologists use to help estimate time of death?",
        answer: "Fresh, bloat, active decay, and skeletonization",
        acceptableAnswers: ["fresh, bloat, decay, skeletonization", "fresh, bloat, active decay, dry/skeletal"],
      },
      {
        id: "for_600_01",
        categoryId: "sci_forensics",
        tier: 600,
        prompt: "Sir Alec Jeffreys developed DNA fingerprinting at the University of Leicester. What was the first criminal case it was used to solve, and what unexpected result did it produce?",
        answer: "The 1986 Enderby murders (Colin Pitchfork case). DNA testing first EXONERATED a suspect who had falsely confessed, then identified the real killer through a mass DNA screening of local men.",
        acceptableAnswers: ["the Colin Pitchfork case", "the Enderby murders, it cleared a false confessor"],
        explanation: "Richard Buckland had confessed but DNA cleared him — the first DNA exoneration. Colin Pitchfork was caught when he convinced someone to take the DNA test in his place.",
      },
      {
        id: "for_600_02",
        categoryId: "sci_forensics",
        tier: 600,
        prompt: "The 'Body Farm' is a famous forensic research facility. What is its official name, where is it located, and what is studied there?",
        answer: "The Anthropological Research Facility at the University of Tennessee, Knoxville — researchers study human decomposition under various conditions to help law enforcement estimate time of death",
        acceptableAnswers: ["University of Tennessee's Anthropological Research Facility", "UTK Body Farm"],
        explanation: "Founded by William Bass in 1981, it was the first facility of its kind. Donated bodies are placed in various conditions and studied as they decompose.",
      },
      {
        id: "for_600_03",
        categoryId: "sci_forensics",
        tier: 600,
        prompt: "Bite mark analysis was once considered reliable forensic evidence but has since been largely discredited. What was the landmark case that helped expose its unreliability?",
        answer: "The case of Ray Krone — convicted partly on bite mark evidence, then exonerated by DNA after 10 years in prison (including time on death row)",
        acceptableAnswers: ["Ray Krone", "multiple wrongful convictions based on bite marks"],
        explanation: "Krone was the 100th person exonerated from death row. His case, along with others, led to the National Academy of Sciences declaring bite mark analysis unreliable in 2009.",
      },
    ],
  },
  {
    id: "cul_whiskey_spirits",
    group: "Culture",
    name: "Whiskey & Spirits",
    culture: "universal",
    description: "The history, craft, and culture of distilled spirits — from Scotch and bourbon to tequila and sake, and the stories behind the world's most iconic drinks.",
    imageUrl: "",
    questions: [
      {
        id: "whs_200_01",
        categoryId: "cul_whiskey_spirits",
        tier: 200,
        prompt: "What is the key legal requirement that distinguishes bourbon from other types of whiskey?",
        answer: "It must be made from at least 51% corn and aged in new charred oak barrels (and made in the United States)",
        acceptableAnswers: ["51% corn", "made from mostly corn in new oak barrels", "51% corn, new charred oak barrels"],
      },
      {
        id: "whs_200_02",
        categoryId: "cul_whiskey_spirits",
        tier: 200,
        prompt: "Scotch whisky and Irish whiskey are spelled differently. Which country spells it without the 'e'?",
        answer: "Scotland (Scotch whisky has no 'e')",
        acceptableAnswers: ["Scotland"],
      },
      {
        id: "whs_200_03",
        categoryId: "cul_whiskey_spirits",
        tier: 200,
        prompt: "What agave-based spirit from Mexico must be produced in specific regions to legally bear its name?",
        answer: "Tequila",
        acceptableAnswers: [],
      },
      {
        id: "whs_400_01",
        categoryId: "cul_whiskey_spirits",
        tier: 400,
        prompt: "Single malt Scotch must come from a single distillery and be made from 100% malted barley. What does the 'age statement' on a bottle (e.g., '12 years') legally guarantee?",
        answer: "The youngest whisky in the blend is at least that age — the bottle may contain older whiskies blended in, but none younger than stated",
        acceptableAnswers: ["the youngest whisky in the bottle is that age", "minimum age of the youngest component"],
      },
      {
        id: "whs_400_02",
        categoryId: "cul_whiskey_spirits",
        tier: 400,
        prompt: "Japanese whisky has won numerous international awards. Which two Scottish-inspired Japanese distilleries are considered the founders of the industry?",
        answer: "Yamazaki (Suntory) and Yoichi (Nikka)",
        acceptableAnswers: ["Yamazaki and Yoichi", "Suntory and Nikka"],
        explanation: "Masataka Taketsuru studied whisky-making in Scotland and founded Nikka. Shinjiro Torii founded Suntory and built Yamazaki. Their rivalry built the industry.",
      },
      {
        id: "whs_400_03",
        categoryId: "cul_whiskey_spirits",
        tier: 400,
        prompt: "What is mezcal's relationship to tequila?",
        answer: "Tequila is a type of mezcal — all tequila is mezcal, but not all mezcal is tequila. Mezcal can be made from any agave; tequila must use blue agave from specific regions.",
        acceptableAnswers: ["tequila is a type of mezcal", "all tequila is mezcal but not vice versa"],
      },
      {
        id: "whs_600_01",
        categoryId: "cul_whiskey_spirits",
        tier: 600,
        prompt: "During American Prohibition (1920-1933), alcohol was still legally available under one specific exemption that was widely exploited. What was it?",
        answer: "Medicinal whiskey — doctors could prescribe whiskey for various ailments, and pharmacies like Walgreens expanded massively by filling these prescriptions",
        acceptableAnswers: ["medicinal prescriptions", "prescription whiskey from doctors", "medical exemption"],
        explanation: "Walgreens grew from 20 stores to over 500 during Prohibition, partly due to filling whiskey prescriptions. The medical exemption was a massive loophole.",
      },
      {
        id: "whs_600_02",
        categoryId: "cul_whiskey_spirits",
        tier: 600,
        prompt: "The 'Angel's Share' is a term used in spirits aging. What does it refer to, and approximately how much is lost per year in different climates?",
        answer: "The portion of spirit that evaporates through the barrel during aging. In Scotland, about 2% per year is lost; in warmer climates like Kentucky or India, losses can be 5-10% annually.",
        acceptableAnswers: ["evaporation from barrels during aging", "spirit lost to evaporation, 2-10% per year depending on climate"],
      },
      {
        id: "whs_600_03",
        categoryId: "cul_whiskey_spirits",
        tier: 600,
        prompt: "Pappy Van Winkle bourbon has become one of the most sought-after and counterfeited spirits in the world. In 2015, a famous theft from the Buffalo Trace distillery made headlines. What happened?",
        answer: "Over 195 barrels of Pappy Van Winkle and Eagle Rare were stolen over several years by a distillery employee (Toby Curtsinger), who ran a theft ring selling barrels to local buyers",
        acceptableAnswers: ["an employee stole barrels over several years", "a distillery worker stole Pappy barrels", "the Pappygate theft"],
        explanation: "The 'Pappygate' scandal revealed that a longtime employee had been stealing barrels for years. He was eventually caught through a network of tipoffs and sentenced to prison.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 63 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
