#!/usr/bin/env python3
"""Insert wave 83 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_white_lotus",
    group: "TV Shows",
    name: "The White Lotus",
    culture: "american",
    description: "Mike White's sharp social satire set at luxury resorts — wealth, privilege, and their consequences",
    imageUrl: "",
    questions: [
      { id: "twl_200_01", categoryId: "tv_white_lotus", tier: 200, prompt: "What type of establishment is 'The White Lotus' in the show?", answer: "A luxury resort/hotel chain", acceptableAnswers: ["Luxury resort", "Hotel", "Luxury hotel", "Resort"], explanation: "Each season is set at a different White Lotus resort, using the hotel as a microcosm of class dynamics." },
      { id: "twl_200_02", categoryId: "tv_white_lotus", tier: 200, prompt: "Where is Season 1 set, and what mystery does the opening scene reveal?", answer: "Hawaii (Maui) — the opening reveals that someone has died at the resort, and the season reveals who and why", acceptableAnswers: ["Hawaii", "Maui", "Hawaii/Maui"], explanation: "The flash-forward murder mystery structure creates tension throughout Season 1's examination of toxic privilege." },
      { id: "twl_200_03", categoryId: "tv_white_lotus", tier: 200, prompt: "What country serves as the setting for Season 2?", answer: "Italy (Sicily)", acceptableAnswers: ["Italy", "Sicily", "Italy/Sicily"], explanation: "Season 2 moves to Sicily, shifting focus from class dynamics to sexual politics and infidelity." },
      { id: "twl_400_01", categoryId: "tv_white_lotus", tier: 400, prompt: "What is the significance of Armond's (the hotel manager) escalating behavior in Season 1, and how does it contrast with the guests' entitlement?", answer: "Armond's relapse into drug use and increasingly erratic behavior mirrors the guests' own destructive entitlement — his breakdown is caused by their impossible demands", acceptableAnswers: ["His breakdown mirrors guest entitlement", "Drug relapse from impossible guest demands", "Staff destruction by guest privilege"], explanation: "Murray Bartlett's performance shows how the hospitality industry's demand for constant deference can destroy those providing it." },
      { id: "twl_400_02", categoryId: "tv_white_lotus", tier: 400, prompt: "In Season 2, what scheme are Quentin and his friends actually running regarding Tanya?", answer: "They're working with Tanya's husband Greg to have her killed, likely for her inheritance/money", acceptableAnswers: ["Plot to kill Tanya for money", "Murder scheme with Greg", "Conspiring with Greg to kill her"], explanation: "The glamorous Italian entourage is actually part of a murder plot, with Quentin's debts motivating his partnership with Greg." },
      { id: "twl_400_03", categoryId: "tv_white_lotus", tier: 400, prompt: "What recurring character appears in both Season 1 and Season 2 before dying?", answer: "Tanya McQuoid (played by Jennifer Coolidge)", acceptableAnswers: ["Tanya", "Tanya McQuoid", "Jennifer Coolidge's character"], explanation: "Tanya's presence across seasons created continuity, and her death in Season 2 was both tragic and darkly comedic." },
      { id: "twl_600_01", categoryId: "tv_white_lotus", tier: 600, prompt: "What specific Mike White interview revelation explains how the show's structure was influenced by the Agatha Christie murder mystery format?", answer: "White described each season as an inverted murder mystery — you know someone dies from the start, and the 'whodunit' is replaced by 'who is it done TO,' focusing on social dynamics that make death inevitable", acceptableAnswers: ["Inverted murder mystery", "Who it's done to not whodunit", "Social dynamics making death inevitable"], explanation: "White's structural innovation — revealing death upfront and spending the season on the social dynamics that produce it — makes the show as much sociological study as thriller." },
      { id: "twl_600_02", categoryId: "tv_white_lotus", tier: 600, prompt: "What is the thematic significance of the 'White Lotus' flower itself, referenced in the show's opening credits animation?", answer: "The white lotus grows from mud — symbolizing how beauty and luxury emerge from ugliness and exploitation; the opening credits show parasites and decay beneath surface beauty", acceptableAnswers: ["Beauty from mud and exploitation", "Parasites beneath beauty", "Luxury built on ugliness"], explanation: "The credits' imagery of parasitic organisms and decomposition beneath tropical beauty perfectly encapsulates the show's thesis about wealth." },
      { id: "twl_600_03", categoryId: "tv_white_lotus", tier: 600, prompt: "What opera does Tanya watch in Season 2's penultimate episode, and how does its plot mirror her own fate?", answer: "Madama Butterfly — about a woman abandoned by a man who only valued her for what she could provide, paralleling Tanya's marriage to Greg", acceptableAnswers: ["Madama Butterfly", "Madame Butterfly"], explanation: "Tanya watches Madama Butterfly and weeps, not realizing the opera is a preview of her own story — a woman used and discarded by a man she trusted." }
    ]
  },
  {
    id: "mu_nine_inch",
    group: "Music",
    name: "Nine Inch Nails",
    culture: "american",
    description: "Trent Reznor's industrial empire — from Pretty Hate Machine to Oscar-winning scores",
    imageUrl: "",
    questions: [
      { id: "nin_200_01", categoryId: "mu_nine_inch", tier: 200, prompt: "What 1994 album is considered Nine Inch Nails' masterpiece, featuring 'Closer' and 'Hurt'?", answer: "The Downward Spiral", explanation: "The Downward Spiral was recorded in the house where the Manson Family murdered Sharon Tate, adding to its dark mythology." },
      { id: "nin_200_02", categoryId: "mu_nine_inch", tier: 200, prompt: "Who is the sole permanent member and creative force behind Nine Inch Nails?", answer: "Trent Reznor", acceptableAnswers: ["Trent Reznor"], explanation: "Reznor writes, performs, and produces virtually everything, making NIN essentially a solo project despite touring with a full band." },
      { id: "nin_200_03", categoryId: "mu_nine_inch", tier: 200, prompt: "What Johnny Cash cover of a NIN song is often considered one of the greatest covers ever recorded?", answer: "Hurt", explanation: "Cash's version recontextualized the song from youthful self-destruction to elderly reflection on mortality; Reznor said 'it's not my song anymore.'" },
      { id: "nin_400_01", categoryId: "mu_nine_inch", tier: 400, prompt: "What Academy Award did Trent Reznor and Atticus Ross win for their first film score together?", answer: "Best Original Score for The Social Network (2010)", acceptableAnswers: ["Best Original Score for The Social Network", "The Social Network", "Oscar for Social Network score"], explanation: "The Social Network score launched Reznor and Ross's second career as acclaimed film composers." },
      { id: "nin_400_02", categoryId: "mu_nine_inch", tier: 400, prompt: "What was the 'Year Zero' ARG (alternate reality game) that accompanied the 2007 album?", answer: "An elaborate multi-platform narrative set in a dystopian 2022 America, involving hidden websites, USB drives left at concerts, and phone numbers embedded in tour merchandise", acceptableAnswers: ["Dystopian ARG with hidden content", "Multi-platform dystopian narrative", "Hidden USBs and websites game"], explanation: "Year Zero's ARG was one of the most ambitious album marketing campaigns ever, creating a fully realized fictional dystopia across dozens of websites and real-world artifacts." },
      { id: "nin_400_03", categoryId: "mu_nine_inch", tier: 400, prompt: "What record label founded by Reznor released Marilyn Manson's early work?", answer: "Nothing Records", acceptableAnswers: ["Nothing Records", "Nothing"], explanation: "Reznor signed and produced Marilyn Manson through Nothing Records before their very public falling-out." },
      { id: "nin_600_01", categoryId: "mu_nine_inch", tier: 600, prompt: "What specific production technique on 'The Downward Spiral' title track involves layered tape manipulation that Reznor has described as the album's most labor-intensive recording?", answer: "Multiple passes of audio recorded to tape, then the tape was physically manipulated (reversed, slowed, spliced) and re-recorded, building up dense layers of processed sound that couldn't be replicated digitally at the time", acceptableAnswers: ["Physical tape manipulation", "Layered tape processing", "Tape splicing and re-recording"], explanation: "The title track's apocalyptic sound was built from dozens of tape manipulation passes, each adding new textural layers to create the album's climactic descent." },
      { id: "nin_600_02", categoryId: "mu_nine_inch", tier: 600, prompt: "What was the significance of Reznor's decision to release 'Ghosts I-IV' and 'The Slip' for free, and how did it influence the music industry?", answer: "After leaving Interscope Records, Reznor self-released Ghosts (pay-what-you-want) and The Slip (completely free) in 2008, predating many artists' experiments with free distribution and proving a major artist could thrive without a label", acceptableAnswers: ["Self-released free/pay-what-you-want", "Left label and released free", "Free releases after leaving Interscope"], explanation: "Ghosts I-IV became the best-selling MP3 album on Amazon despite being available for free, and the experiment influenced how artists approached direct-to-fan distribution." },
      { id: "nin_600_03", categoryId: "mu_nine_inch", tier: 600, prompt: "What is the 'Broken Movie,' and why has it never been officially released?", answer: "A short film accompanying the Broken EP featuring extremely graphic simulated violence (including torture and murder) directed by Peter Christopherson; it circulated as a bootleg VHS and was too disturbing for official release", acceptableAnswers: ["Graphic short film with Broken EP", "Peter Christopherson torture film", "Unreleased extreme violence short film"], explanation: "The Broken Movie was so disturbing that it was reportedly investigated by the FBI as a possible snuff film before being confirmed as fictional — it has never been officially released." }
    ]
  },
  {
    id: "vg_titanfall2",
    group: "Video Games",
    name: "Titanfall 2",
    culture: "universal",
    description: "Respawn's FPS masterpiece with the best campaign nobody played",
    imageUrl: "",
    questions: [
      { id: "tf2_200_01", categoryId: "vg_titanfall2", tier: 200, prompt: "What is the name of the Titan AI companion that becomes your partner after its original pilot dies?", answer: "BT-7274 (BT)", acceptableAnswers: ["BT-7274", "BT", "BT 7274"], explanation: "BT-7274 is a Vanguard-class Titan whose growing bond with pilot Jack Cooper became one of gaming's most beloved relationships." },
      { id: "tf2_200_02", categoryId: "vg_titanfall2", tier: 200, prompt: "What is the name of the player character, a rifleman who unexpectedly becomes a Titan pilot?", answer: "Jack Cooper", acceptableAnswers: ["Jack Cooper", "Cooper"], explanation: "Cooper was a grunt being informally trained by Captain Lastimosa, thrust into the pilot role when Lastimosa dies in the opening mission." },
      { id: "tf2_200_03", categoryId: "vg_titanfall2", tier: 200, prompt: "What major franchise did Respawn Entertainment create after Titanfall, using its movement engine?", answer: "Apex Legends", explanation: "Apex Legends is set in the Titanfall universe and uses a modified version of the Source engine movement system." },
      { id: "tf2_400_01", categoryId: "vg_titanfall2", tier: 400, prompt: "What is the 'Effect and Cause' level, widely considered one of the best FPS levels ever designed?", answer: "A level where Cooper switches between present-day ruins and the same facility in the past using a time-travel wrist device, solving puzzles and fighting enemies across both timelines simultaneously", acceptableAnswers: ["Time travel level", "Switching between past and present", "Time-shift level"], explanation: "Effect and Cause lets you instantly swap between timelines with a button press, creating combat and traversal puzzles that use temporal shifting." },
      { id: "tf2_400_02", categoryId: "vg_titanfall2", tier: 400, prompt: "What is the 'Fold Weapon' that the IMC is trying to use, and what is its purpose?", answer: "A superweapon that can fold spacetime to destroy entire planets, which the IMC plans to use against the Militia's home world Harmony", acceptableAnswers: ["Spacetime folding superweapon", "Planet-destroying fold weapon", "Weapon to destroy Harmony"], explanation: "The Fold Weapon folds space to teleport destructive energy across vast distances, threatening to destroy the Militia planet Harmony." },
      { id: "tf2_400_03", categoryId: "vg_titanfall2", tier: 400, prompt: "What happens to BT at the end of the campaign, and what post-credits detail gives fans hope?", answer: "BT sacrifices himself to destroy the Fold Weapon, but the post-credits scene shows Jack's helmet flickering with BT's neural link signal, suggesting BT uploaded himself", acceptableAnswers: ["BT sacrifices himself but helmet signal hints survival", "Self-sacrifice but post-credits hint at survival", "BT dies but helmet flickers"], explanation: "BT's sacrifice is one of gaming's most emotional moments, and the post-credits helmet flicker ('Jack?') left fans hoping for a sequel." },
      { id: "tf2_600_01", categoryId: "vg_titanfall2", tier: 600, prompt: "What specific EA release window decision is widely blamed for Titanfall 2's poor sales despite critical acclaim?", answer: "EA released it on October 28, 2016, sandwiched between Battlefield 1 (EA's own game, October 21) and Call of Duty: Infinite Warfare (November 4), cannibalizing its own product", acceptableAnswers: ["Sandwiched between Battlefield 1 and CoD", "Released between BF1 and CoD", "October 2016 between two shooters"], explanation: "The catastrophic release window meant Titanfall 2 competed with two massive FPS franchises simultaneously, including EA's own Battlefield — many consider it one of gaming's worst scheduling decisions." },
      { id: "tf2_600_02", categoryId: "vg_titanfall2", tier: 600, prompt: "What movement technique called 'slidehopping' emerged from the community and became central to high-level play?", answer: "Chaining slides and jumps to maintain and build momentum beyond normal sprint speed, exploiting the Source engine's air-strafe mechanics", acceptableAnswers: ["Slide-jump chaining for speed", "Slidehopping", "Slide and jump momentum chaining"], explanation: "Slidehopping evolved from Titanfall 1's bunnyhopping and became the foundation of the game's incredibly fast competitive movement meta." },
      { id: "tf2_600_03", categoryId: "vg_titanfall2", tier: 600, prompt: "What design philosophy did Respawn call 'Action Blocks,' and how did it make every campaign level feel unique?", answer: "Each campaign level introduces a unique mechanic (time travel, assembly line, arc tool) that is fully explored and then discarded for the next level — no mechanic outstays its welcome", acceptableAnswers: ["Unique mechanic per level then discarded", "One mechanic per level philosophy", "Introduce-explore-discard per level"], explanation: "The Action Block approach meant no two levels play the same way, giving the 6-hour campaign more mechanical variety than most 20-hour games." }
    ]
  },
  {
    id: "vg_pathologic",
    group: "Video Games",
    name: "Pathologic 2",
    culture: "universal",
    description: "The Russian survival horror game about a plague, a town, and impossible choices",
    imageUrl: "",
    questions: [
      { id: "pat_200_01", categoryId: "vg_pathologic", tier: 200, prompt: "What is the central crisis facing the Town-on-Gorkhon that the player must navigate?", answer: "A deadly plague / pestilence called the Sand Pest that is killing the town's population", acceptableAnswers: ["A plague", "The Sand Pest", "Deadly plague", "Pestilence"], explanation: "The Sand Pest is a mysterious disease spreading through the steppe town, and you have 12 in-game days to find a cure while surviving yourself." },
      { id: "pat_200_02", categoryId: "vg_pathologic", tier: 200, prompt: "What profession is the player character Artemy Burakh trained in?", answer: "Surgeon / haruspex (one who reads organs)", acceptableAnswers: ["Surgeon", "Haruspex", "Doctor", "Surgeon/haruspex"], explanation: "Artemy is both a trained surgeon and a traditional haruspex (organ-reader) of the steppe people, blending modern medicine with folk tradition." },
      { id: "pat_200_03", categoryId: "vg_pathologic", tier: 200, prompt: "What makes Pathologic 2 deliberately uncomfortable as a survival game?", answer: "Constant hunger, exhaustion, thirst, and infection threaten you; resources are extremely scarce and the game is designed to make you feel desperate and powerless", acceptableAnswers: ["Extreme resource scarcity", "Constant survival pressure", "Deliberate discomfort and scarcity"], explanation: "The game intentionally makes survival grueling so that the moral choices you face — trading food for medicine, helping one person over another — feel genuinely desperate." },
      { id: "pat_400_01", categoryId: "vg_pathologic", tier: 400, prompt: "What metatextual element does Pathologic 2 use, with theatrical characters who acknowledge the game's nature?", answer: "The game is framed as a theater performance — characters called 'Tragedians' and an 'Executor' directly address the player and discuss the game as a staged production", acceptableAnswers: ["Theater framing device", "Tragedians and Executor", "Metatextual theater performance"], explanation: "Pathologic 2 constantly reminds you it's a performance, with masked theater characters questioning your role and the nature of the story being told." },
      { id: "pat_400_02", categoryId: "vg_pathologic", tier: 400, prompt: "What is the significance of the Polyhedron, the impossible structure that towers over the town?", answer: "A physically impossible building (a child's tower of imagination made real) that may hold the key to salvation but whose existence may be causing the plague", acceptableAnswers: ["Impossible building connected to plague", "Children's tower possibly causing plague", "Impossible structure key to salvation or plague source"], explanation: "The Polyhedron represents pure imagination — built by children — but may be parasitically drawing life from the earth, potentially causing the very plague destroying the town." },
      { id: "pat_400_03", categoryId: "vg_pathologic", tier: 400, prompt: "What impossible choice does the game force at its conclusion regarding the Polyhedron and the town?", answer: "Destroy the Polyhedron to save the town's earth and tradition, or preserve the Polyhedron and let the old town die to save the children's impossible dream", acceptableAnswers: ["Destroy Polyhedron or save it", "Town vs Polyhedron", "Earth/tradition vs imagination/children"], explanation: "Neither choice is 'right' — destroying imagination to preserve tradition or letting tradition die for imagination represents the game's central philosophical dilemma." },
      { id: "pat_600_01", categoryId: "vg_pathologic", tier: 600, prompt: "What is developer Ice-Pick Lodge's stated design philosophy about player suffering and how games should make you feel?", answer: "Games should be 'inoculations' — small doses of suffering that build emotional resilience; the player should experience genuine discomfort to understand the themes, not just observe them from a comfortable distance", acceptableAnswers: ["Games as inoculations", "Suffering for understanding", "Inoculation through discomfort"], explanation: "Ice-Pick Lodge believes that making players actually suffer (hunger, time pressure, impossible choices) creates understanding that comfortable observation never can." },
      { id: "pat_600_02", categoryId: "vg_pathologic", tier: 600, prompt: "How does Pathologic 2 relate to the original 2005 Pathologic — is it a sequel, remake, or something else entirely?", answer: "It's simultaneously a remake, sequel, and metatextual continuation — characters reference the events of the first game as if they happened, and the theater framing suggests this is a 'second performance' of the same story", acceptableAnswers: ["Remake and sequel simultaneously", "Second performance of same story", "Meta-sequel referencing first game"], explanation: "The game's relationship to its predecessor is intentionally ambiguous — it retells the story while acknowledging the first telling happened, creating a recursive narrative loop." },
      { id: "pat_600_03", categoryId: "vg_pathologic", tier: 600, prompt: "What is the significance of the game's real-time 12-day structure, and what happens to characters and storylines you cannot reach in time?", answer: "The 12 days play out in real time regardless of your actions — characters die, events resolve, and storylines close permanently if you don't reach them; the game is designed to be impossible to 'complete' in a single playthrough", acceptableAnswers: ["Real-time events proceed without you", "Characters die permanently if missed", "Impossible to see everything in one playthrough"], explanation: "The real-time structure means every hour spent trading for food is an hour someone else dies — the game guarantees you will fail some people, making triage the core experience." }
    ]
  },
  {
    id: "mv_park_chan",
    group: "Movies",
    name: "Park Chan-wook Films",
    culture: "universal",
    description: "The Korean master of revenge, beauty, and moral complexity",
    imageUrl: "",
    questions: [
      { id: "pcw_200_01", categoryId: "mv_park_chan", tier: 200, prompt: "What 2003 film about a man imprisoned for 15 years without knowing why is considered Park's masterpiece?", answer: "Oldboy", explanation: "Oldboy won the Grand Prix at Cannes and became one of the most influential Asian films worldwide." },
      { id: "pcw_200_02", categoryId: "mv_park_chan", tier: 200, prompt: "What trilogy of films explores the theme of revenge, including Sympathy for Mr. Vengeance, Oldboy, and Lady Vengeance?", answer: "The Vengeance Trilogy", acceptableAnswers: ["Vengeance Trilogy", "The Vengeance Trilogy", "Revenge Trilogy"], explanation: "The three films don't share characters but explore different facets of revenge — its futility, its horror, and its moral cost." },
      { id: "pcw_200_03", categoryId: "mv_park_chan", tier: 200, prompt: "What 2022 romantic thriller earned Park his first Best Director award at Cannes?", answer: "Decision to Leave", explanation: "Decision to Leave is a Hitchcockian romance-thriller about a detective who falls for a murder suspect." },
      { id: "pcw_400_01", categoryId: "mv_park_chan", tier: 400, prompt: "In Oldboy, what is the devastating truth about the relationship between Oh Dae-su and the young woman Mi-do?", answer: "Mi-do is Oh Dae-su's daughter — the villain orchestrated their meeting and romantic relationship as the ultimate revenge", acceptableAnswers: ["She's his daughter", "Mi-do is his daughter", "Incestuous relationship with his daughter"], explanation: "The twist that Dae-su has been manipulated into a romantic relationship with his own daughter is one of cinema's most disturbing revelations." },
      { id: "pcw_400_02", categoryId: "mv_park_chan", tier: 400, prompt: "What 2016 film set in Japanese-occupied Korea involves an elaborate con game between a handmaiden, a pickpocket, and a collector?", answer: "The Handmaiden", explanation: "The Handmaiden adapted Sarah Waters' Fingersmith, transposing it to 1930s Korea and adding layers of eroticism and deception." },
      { id: "pcw_400_03", categoryId: "mv_park_chan", tier: 400, prompt: "What iconic scene in Oldboy features Dae-su fighting dozens of men in a hallway, and what technique was it filmed with?", answer: "A continuous side-scrolling single-take shot filmed in a narrow corridor, with Oh Dae-su fighting through increasingly exhausted opponents", acceptableAnswers: ["Continuous side-scrolling hallway fight", "Single-take corridor fight", "One-shot hallway fight"], explanation: "The hallway fight was shot in a single continuous take from a side angle, resembling a side-scrolling video game and becoming one of cinema's most referenced fight scenes." },
      { id: "pcw_600_01", categoryId: "mv_park_chan", tier: 600, prompt: "What structural technique in The Handmaiden divides the film into three parts, each revealing how the previous part's events were perceived differently by different characters?", answer: "A Rashomon-like three-part structure where Part 1 shows events from the handmaiden Sook-hee's perspective, Part 2 reveals Lady Hideko's hidden perspective and double-crosses, and Part 3 resolves the true alliances", acceptableAnswers: ["Three-part perspective shifts", "Three perspectives revealing deceptions", "Rashomon structure with three parts"], explanation: "Each part recontextualizes what you thought was happening, turning apparent victims into schemers and schemers into lovers in an elaborate narrative shell game." },
      { id: "pcw_600_02", categoryId: "mv_park_chan", tier: 600, prompt: "What specific visual motif does Park use across his films involving the framing of characters within frames (doors, windows, screens)?", answer: "Characters are constantly framed within secondary frames — viewed through doorways, reflected in mirrors, seen through windows — creating a voyeuristic, trapped aesthetic that reinforces themes of observation and imprisonment", acceptableAnswers: ["Frames within frames", "Characters in secondary frames", "Voyeuristic framing through doors and windows"], explanation: "Park's 'frame within a frame' technique makes the audience complicit voyeurs — we watch characters who are themselves being watched, creating layers of observation and control." },
      { id: "pcw_600_03", categoryId: "mv_park_chan", tier: 600, prompt: "What is Park's stated philosophy about the relationship between beauty and violence in cinema?", answer: "Beauty and violence are inseparable — making violence beautiful forces the audience to confront their own attraction to it rather than dismissing it as merely horrific; aestheticizing cruelty is more honest than pretending audiences don't derive pleasure from screen violence", acceptableAnswers: ["Beauty and violence are inseparable", "Aestheticizing violence confronts audience attraction", "Beautiful violence forces self-confrontation"], explanation: "Park's philosophy explains why his films pair exquisite cinematography with extreme violence — the contrast forces viewers to examine their own complicity in consuming beautiful brutality." }
    ]
  },
  {
    id: "his_maya",
    group: "History & Culture",
    name: "Ancient Maya Civilization",
    culture: "universal",
    description: "The great Mesoamerican civilization of pyramids, hieroglyphs, and astronomical precision",
    imageUrl: "",
    questions: [
      { id: "may_200_01", categoryId: "his_maya", tier: 200, prompt: "What mathematical concept did the Maya independently develop, crucial for their calendar and astronomical calculations?", answer: "The concept of zero", acceptableAnswers: ["Zero", "The number zero", "The concept of zero"], explanation: "The Maya were among the first civilizations to independently develop and use zero as a placeholder, centuries before it reached Europe." },
      { id: "may_200_02", categoryId: "his_maya", tier: 200, prompt: "What type of writing system did the Maya develop — the most sophisticated in the pre-Columbian Americas?", answer: "Hieroglyphic writing / logosyllabic script", acceptableAnswers: ["Hieroglyphic", "Hieroglyphs", "Logosyllabic", "Maya hieroglyphs"], explanation: "Maya script used both logograms (symbols for whole words) and syllabic signs, capable of expressing anything in the spoken language." },
      { id: "may_200_03", categoryId: "his_maya", tier: 200, prompt: "What ancient Maya city in Guatemala features some of the tallest pre-Columbian structures in the Americas?", answer: "Tikal", acceptableAnswers: ["Tikal"], explanation: "Tikal's temples rise above the rainforest canopy, with Temple IV reaching 65 meters — one of the tallest pre-Columbian structures ever built." },
      { id: "may_400_01", categoryId: "his_maya", tier: 400, prompt: "What happened in the 'Maya Collapse' of the 9th century, and what factors likely caused it?", answer: "Major cities in the southern lowlands were abandoned; likely caused by a combination of prolonged drought, overpopulation, environmental degradation, and intensified warfare", acceptableAnswers: ["Cities abandoned due to drought and war", "Southern lowland collapse from drought", "Drought, war, and environmental collapse"], explanation: "The collapse wasn't a single event but a century-long decline, and importantly, it didn't end Maya civilization — northern cities like Chichén Itzá flourished afterward." },
      { id: "may_400_02", categoryId: "his_maya", tier: 400, prompt: "What bloodletting ritual was performed by Maya royalty, and what body parts were typically pierced?", answer: "Kings and queens pierced their tongues, earlobes, and genitals with stingray spines or obsidian blades, using the blood-soaked paper to communicate with ancestors and gods", acceptableAnswers: ["Tongue and genital piercing", "Royal blood-letting with stingray spines", "Self-piercing for divine communication"], explanation: "Royal bloodletting was considered essential for maintaining cosmic order — the blood offerings fed the gods and opened a portal to communicate with ancestors." },
      { id: "may_400_03", categoryId: "his_maya", tier: 400, prompt: "What astronomical achievement did the Maya accomplish regarding the planet Venus?", answer: "They calculated Venus's synodic period (584 days) to within hours of modern measurements, and created a Venus calendar that tracked its cycles for ritual and warfare planning", acceptableAnswers: ["Calculated Venus's cycle accurately", "Venus synodic period calculation", "584-day Venus cycle"], explanation: "Maya astronomers observed Venus for centuries, achieving remarkable precision — their calculations rival modern astronomical measurements." },
      { id: "may_600_01", categoryId: "his_maya", tier: 600, prompt: "What breakthrough by Yuri Knorozov in the 1950s began the modern decipherment of Maya hieroglyphs, and why was his work initially rejected by Western scholars?", answer: "Knorozov demonstrated that Maya script was phonetic/syllabic (not purely logographic), using Diego de Landa's 'alphabet'; Cold War politics led Western scholars like Eric Thompson to reject a Soviet researcher's work for decades", acceptableAnswers: ["Proved script was phonetic/syllabic", "Soviet linguist proved phonetic nature", "Knorozov's syllabic reading rejected due to Cold War"], explanation: "Knorozov's key insight — that Landa's 'alphabet' recorded syllables, not letters — unlocked Maya script, but Cold War bias delayed acceptance for 20+ years." },
      { id: "may_600_02", categoryId: "his_maya", tier: 600, prompt: "What recent LiDAR discoveries in the Guatemalan jungle revealed about the scale of Maya civilization?", answer: "LiDAR surveys in 2018 revealed over 60,000 previously hidden structures beneath the jungle canopy, indicating the Maya lowlands supported 10-15 million people — far more than previously estimated", acceptableAnswers: ["60,000 hidden structures found", "LiDAR revealed massive hidden cities", "10-15 million population revealed"], explanation: "LiDAR technology penetrated the dense canopy to reveal extensive road networks, irrigation systems, and defensive fortifications, completely rewriting population estimates." },
      { id: "may_600_03", categoryId: "his_maya", tier: 600, prompt: "What is the Maya Long Count calendar's relationship to the 2012 apocalypse myth, and what did it actually represent?", answer: "December 21, 2012 marked the end of the 13th b'ak'tun (a cycle of about 5,125 years), which was a period ending similar to a millennium turning — not an apocalypse; the calendar continues to the next cycle, and Maya texts reference dates far beyond 2012", acceptableAnswers: ["End of a cycle not apocalypse", "13th b'ak'tun ending, calendar continues", "Period ending not end of world"], explanation: "The 2012 phenomenon was entirely a modern Western invention — no Maya text predicts an apocalypse, and inscriptions at Palenque reference dates 4,000 years in the future." }
    ]
  },
  {
    id: "sci_deep_ocean",
    group: "Science & Nature",
    name: "Deep Ocean Ecosystems",
    culture: "universal",
    description: "Life in the abyss — hydrothermal vents, bioluminescence, and the last frontier on Earth",
    imageUrl: "",
    questions: [
      { id: "doc_200_01", categoryId: "sci_deep_ocean", tier: 200, prompt: "What is the name for the deepest zone of the ocean, found in trenches below 6,000 meters?", answer: "The hadal zone / hadopelagic zone", acceptableAnswers: ["Hadal zone", "Hadopelagic zone", "Hadal"], explanation: "Named after Hades, the hadal zone includes ocean trenches where pressures exceed 1,000 atmospheres." },
      { id: "doc_200_02", categoryId: "sci_deep_ocean", tier: 200, prompt: "What is bioluminescence, the ability many deep-sea creatures use to produce their own light?", answer: "The production of light by living organisms through chemical reactions (typically luciferin + luciferase)", acceptableAnswers: ["Chemical light production", "Living things making their own light", "Biological light production"], explanation: "Up to 90% of deep-sea organisms produce bioluminescence — it's the rule, not the exception, in the deep ocean." },
      { id: "doc_200_03", categoryId: "sci_deep_ocean", tier: 200, prompt: "What are hydrothermal vents, the deep-sea features that support life without sunlight?", answer: "Fissures in the ocean floor that release superheated mineral-rich water, supporting chemosynthetic ecosystems independent of photosynthesis", acceptableAnswers: ["Hot water vents on ocean floor", "Volcanic vents supporting life", "Seafloor vents with chemosynthetic life"], explanation: "Discovered in 1977, hydrothermal vents revolutionized biology by proving that life could exist entirely without sunlight." },
      { id: "doc_400_01", categoryId: "sci_deep_ocean", tier: 400, prompt: "What is chemosynthesis, and how does it differ from photosynthesis as a basis for an ecosystem?", answer: "Chemosynthetic bacteria use chemical energy from hydrogen sulfide or methane (instead of sunlight) to produce organic molecules, forming the base of vent food chains", acceptableAnswers: ["Chemical energy instead of light", "Using hydrogen sulfide for energy", "Chemical-based food production"], explanation: "Chemosynthesis proved that sunlight isn't necessary for complex ecosystems, revolutionizing our understanding of where life can exist — including potentially on other worlds." },
      { id: "doc_400_02", categoryId: "sci_deep_ocean", tier: 400, prompt: "What is a 'whale fall,' and why is it an important deep-sea ecosystem?", answer: "A whale carcass that sinks to the deep ocean floor, creating a localized ecosystem that can sustain specialized organisms for 50-100 years through progressive decomposition stages", acceptableAnswers: ["Sunken whale carcass ecosystem", "Dead whale creating ocean floor ecosystem", "Whale carcass supporting life for decades"], explanation: "Whale falls go through stages: first scavengers strip the flesh, then smaller organisms colonize the bones, and finally chemosynthetic bacteria break down the lipid-rich skeleton." },
      { id: "doc_400_03", categoryId: "sci_deep_ocean", tier: 400, prompt: "What deep-sea creature can withstand extreme heat, extreme cold, and crushing pressure, making it a candidate for studying extraterrestrial life?", answer: "Giant tube worms (Riftia pachyptila) at hydrothermal vents", acceptableAnswers: ["Giant tube worms", "Riftia pachyptila", "Tube worms"], explanation: "Giant tube worms have no mouth, gut, or anus — they survive entirely through symbiotic chemosynthetic bacteria living inside their bodies." },
      { id: "doc_600_01", categoryId: "sci_deep_ocean", tier: 600, prompt: "What is the 'iron hypothesis' regarding deep-sea hydrothermal vents and the origin of life on Earth?", answer: "Iron-sulfur minerals at alkaline hydrothermal vents could have catalyzed the first organic reactions, creating natural electrochemical gradients similar to those used by all living cells for energy production", acceptableAnswers: ["Iron-sulfur catalysis at vents started life", "Alkaline vent origin of life", "Electrochemical gradients from vents creating first life"], explanation: "The alkaline hydrothermal vent theory (by Mike Russell and Bill Martin) proposes that life began at deep-sea vents where natural proton gradients across mineral walls drove the first biochemistry." },
      { id: "doc_600_02", categoryId: "sci_deep_ocean", tier: 600, prompt: "What specific adaptation allows the Mariana snailfish to survive at nearly 8,200 meters depth, and what biochemical modification makes this possible?", answer: "High concentrations of trimethylamine N-oxide (TMAO) stabilize its proteins against crushing pressure; its bones are barely mineralized and its skull is not fully closed, reducing rigid structures that pressure could damage", acceptableAnswers: ["TMAO protein stabilization", "TMAO and reduced bone mineralization", "Trimethylamine N-oxide for pressure resistance"], explanation: "TMAO acts as a 'chemical chaperone' that prevents proteins from being crushed into non-functional shapes by the immense pressure — the deeper the fish, the higher the TMAO concentration." },
      { id: "doc_600_03", categoryId: "sci_deep_ocean", tier: 600, prompt: "What controversy surrounds deep-sea mining of polymetallic nodules, and what specific ecosystem would be destroyed?", answer: "Nodules containing manganese, nickel, cobalt, and rare earths sit on abyssal plains and take millions of years to form; mining would destroy the organisms that live on and around them — a slow-growing ecosystem that may take centuries or millennia to recover, if ever", acceptableAnswers: ["Mining slow-forming nodules destroys irreplaceable ecosystems", "Polymetallic nodule mining vs abyssal ecosystems", "Million-year-old nodules supporting unique life"], explanation: "The ISA is considering allowing deep-sea mining despite scientists warning that abyssal ecosystems are so slow to develop that any destruction is effectively permanent on human timescales." }
    ]
  },
  {
    id: "sci_time",
    group: "Science & Nature",
    name: "The Physics of Time",
    culture: "universal",
    description: "What is time? Relativity, entropy, and the arrow that points only one way",
    imageUrl: "",
    questions: [
      { id: "ptm_200_01", categoryId: "sci_time", tier: 200, prompt: "According to Einstein's theory of relativity, what happens to time as you approach the speed of light?", answer: "Time slows down (time dilation) — a clock moving at high speed ticks slower relative to a stationary observer", acceptableAnswers: ["Time slows down", "Time dilation", "Time goes slower"], explanation: "Time dilation is not just theoretical — GPS satellites must correct for both special and general relativistic time effects to maintain accuracy." },
      { id: "ptm_200_02", categoryId: "sci_time", tier: 200, prompt: "What concept from thermodynamics explains why time seems to flow in only one direction?", answer: "Entropy / the second law of thermodynamics — entropy always increases, giving time its 'arrow'", acceptableAnswers: ["Entropy", "Second law of thermodynamics", "Arrow of time from entropy"], explanation: "The 'arrow of time' comes from entropy — the universe moves from ordered to disordered states, and this asymmetry is why we remember the past but not the future." },
      { id: "ptm_200_03", categoryId: "sci_time", tier: 200, prompt: "What effect does gravity have on time, according to general relativity?", answer: "Stronger gravity causes time to pass more slowly — clocks near massive objects tick slower than those in weaker gravitational fields", acceptableAnswers: ["Gravity slows time", "Stronger gravity means slower time", "Gravitational time dilation"], explanation: "A clock on Earth's surface runs slightly slower than one in orbit — this gravitational time dilation was directly measured by the Pound-Rebka experiment." },
      { id: "ptm_400_01", categoryId: "sci_time", tier: 400, prompt: "What is the 'twin paradox,' and how does special relativity resolve it?", answer: "If one twin travels at near-light speed and returns, they'll have aged less than the stay-at-home twin; it's resolved because the traveling twin accelerates/decelerates, breaking the symmetry", acceptableAnswers: ["Traveling twin ages less", "Acceleration breaks the symmetry", "Space-traveling twin returns younger"], explanation: "The paradox isn't actually paradoxical — the asymmetry of acceleration means both twins agree on who traveled and who aged more." },
      { id: "ptm_400_02", categoryId: "sci_time", tier: 400, prompt: "What is a 'block universe,' the philosophical interpretation of time suggested by general relativity?", answer: "The idea that past, present, and future all exist simultaneously — time is a dimension like space, and the flow of time is an illusion of consciousness", acceptableAnswers: ["Past present future exist simultaneously", "Time as a dimension like space", "All of time exists at once"], explanation: "In the block universe (eternalism), the Big Bang and the heat death of the universe both 'exist' — our experience of time flowing is subjective, not fundamental." },
      { id: "ptm_400_03", categoryId: "sci_time", tier: 400, prompt: "What is Planck time, and why is it significant as a potential smallest unit of time?", answer: "Approximately 5.39 × 10^-44 seconds — the shortest meaningful duration in physics, below which our current understanding of time breaks down", acceptableAnswers: ["5.39 x 10^-44 seconds", "Shortest meaningful time unit", "Planck time ~10^-44 seconds"], explanation: "Below Planck time, quantum gravity effects dominate and our current theories cannot describe what 'time' even means — it may not exist as a continuous flow." },
      { id: "ptm_600_01", categoryId: "sci_time", tier: 600, prompt: "What does Carlo Rovelli's loop quantum gravity theory propose about the fundamental nature of time?", answer: "Time does not exist at the fundamental level — it's an emergent property arising from thermodynamic relations between quantum gravitational degrees of freedom; what we call 'time' is our perspective on the increase of entropy", acceptableAnswers: ["Time doesn't fundamentally exist", "Time is emergent from thermodynamics", "Time emerges from entropy relations"], explanation: "Rovelli's radical proposal — that the fundamental equations of physics need no time variable — challenges our deepest intuitions about reality." },
      { id: "ptm_600_02", categoryId: "sci_time", tier: 600, prompt: "What is the Wheeler-DeWitt equation, and what does its most striking feature suggest about time at the quantum level?", answer: "The fundamental equation of quantum gravity that contains no time variable at all — suggesting that at the deepest level, the universe is timeless and 'time' only emerges at larger scales", acceptableAnswers: ["Quantum gravity equation without time", "Timeless fundamental equation", "No time variable in quantum gravity equation"], explanation: "The 'problem of time' in quantum gravity — that the most fundamental equation has no time — remains one of physics' deepest unsolved puzzles." },
      { id: "ptm_600_03", categoryId: "sci_time", tier: 600, prompt: "What specific experiment by Hafele and Keating in 1971 directly measured relativistic time dilation, and what were the results?", answer: "They flew atomic clocks around the world on commercial airliners and compared them to ground clocks; eastward-flying clocks lost 59±10 nanoseconds and westward-flying clocks gained 273±7 nanoseconds, matching GR and SR predictions", acceptableAnswers: ["Atomic clocks on airplanes", "Flew clocks on planes measuring time differences", "Hafele-Keating airplane clock experiment"], explanation: "The Hafele-Keating experiment was the first direct verification of both special and general relativistic time dilation using portable atomic clocks — the results matched Einstein's predictions within experimental error." }
    ]
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 83 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
