#!/usr/bin/env python3
"""Insert wave 59 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_twin_peaks",
    group: "TV Shows",
    name: "Twin Peaks",
    culture: "american",
    description: "David Lynch and Mark Frost's surreal mystery series set in a small Pacific Northwest town where nothing is as it seems.",
    imageUrl: "",
    questions: [
      {
        id: "twp_200_01",
        categoryId: "tv_twin_peaks",
        tier: 200,
        prompt: "What is the name of the murdered homecoming queen whose death sets the plot of Twin Peaks in motion?",
        answer: "Laura Palmer",
        acceptableAnswers: ["Laura"],
        explanation: "The central mystery — 'Who killed Laura Palmer?' — became one of the most iconic hooks in television history.",
      },
      {
        id: "twp_200_02",
        categoryId: "tv_twin_peaks",
        tier: 200,
        prompt: "Which FBI agent arrives in Twin Peaks to investigate the murder, famously recording voice memos to a never-seen colleague named Diane?",
        answer: "Dale Cooper",
        acceptableAnswers: ["Agent Cooper", "Special Agent Dale Cooper"],
      },
      {
        id: "twp_200_03",
        categoryId: "tv_twin_peaks",
        tier: 200,
        prompt: "What is the name of the diner where much of Twin Peaks' social life revolves, known for its coffee and cherry pie?",
        answer: "The Double R Diner",
        acceptableAnswers: ["Double R", "Double R Diner", "The RR Diner"],
      },
      {
        id: "twp_400_01",
        categoryId: "tv_twin_peaks",
        tier: 400,
        prompt: "In the show's mythology, what extradimensional location is represented by red curtains and a chevron-patterned floor?",
        answer: "The Black Lodge",
        acceptableAnswers: ["Black Lodge", "The Red Room"],
        explanation: "The Black Lodge, often entered through the Red Room, is a supernatural realm where spirits and doppelgängers reside.",
      },
      {
        id: "twp_400_02",
        categoryId: "tv_twin_peaks",
        tier: 400,
        prompt: "What malevolent entity possesses Leland Palmer and is ultimately revealed to be Laura's killer?",
        answer: "BOB",
        acceptableAnswers: ["Bob", "Killer BOB"],
        explanation: "BOB is a parasitic spirit from the Black Lodge who feeds on fear and suffering, inhabiting Leland for years.",
      },
      {
        id: "twp_400_03",
        categoryId: "tv_twin_peaks",
        tier: 400,
        prompt: "The Log Lady carries a log she believes communicates spiritual messages to her. What is the actress's name who played this iconic role?",
        answer: "Catherine Coulson",
        acceptableAnswers: ["Catherine E. Coulson"],
        explanation: "Catherine Coulson played Margaret Lanterman (the Log Lady) across all three seasons, filming her final scenes while terminally ill for The Return.",
      },
      {
        id: "twp_600_01",
        categoryId: "tv_twin_peaks",
        tier: 600,
        prompt: "In Twin Peaks: The Return (Season 3), Cooper spends most of the season in a catatonic alter ego after escaping the Lodge. What name does this persona go by?",
        answer: "Dougie Jones",
        acceptableAnswers: ["Dougie"],
        explanation: "Cooper's consciousness is fractured upon leaving the Lodge, and he inhabits the life of Dougie Jones — a tulpa created by his doppelgänger — for most of The Return's 18 episodes.",
      },
      {
        id: "twp_600_02",
        categoryId: "tv_twin_peaks",
        tier: 600,
        prompt: "Episode 8 of The Return is considered one of the most experimental hours in TV history. What real-world event does it depict as the origin of supernatural evil in Twin Peaks' mythology?",
        answer: "The Trinity nuclear test",
        acceptableAnswers: ["the first nuclear bomb test", "Trinity test", "nuclear detonation", "the atomic bomb test"],
        explanation: "The episode portrays the 1945 Trinity test as the event that birthed BOB and tore open the barrier between our world and the Lodge dimensions.",
      },
      {
        id: "twp_600_03",
        categoryId: "tv_twin_peaks",
        tier: 600,
        prompt: "In the original series, the Giant gives Cooper three clues during a vision. One of them — 'The owls are not what they seem' — becomes a recurring motif. What do the owls represent in the show's mythology?",
        answer: "They are vessels or disguises for Lodge spirits observing the town",
        acceptableAnswers: ["Lodge spirits", "spirits from the Black Lodge", "supernatural entities", "Woodsmen or Lodge entities"],
        explanation: "The owls serve as surveillance for extradimensional beings. Their presence signals that Lodge entities are watching or that a portal is nearby.",
      },
    ],
  },
  {
    id: "tv_atlanta",
    group: "TV Shows",
    name: "Atlanta",
    culture: "american",
    description: "Donald Glover's genre-defying FX series following Earn and Paper Boi navigating Atlanta's rap scene, blending surrealism with sharp social commentary.",
    imageUrl: "",
    questions: [
      {
        id: "atl_200_01",
        categoryId: "tv_atlanta",
        tier: 200,
        prompt: "Who created, wrote, and stars in Atlanta as the protagonist Earn Marks?",
        answer: "Donald Glover",
        acceptableAnswers: ["Childish Gambino"],
      },
      {
        id: "atl_200_02",
        categoryId: "tv_atlanta",
        tier: 200,
        prompt: "What is the stage name of Earn's cousin Alfred, whose rising rap career drives much of the show's plot?",
        answer: "Paper Boi",
        acceptableAnswers: ["Paperboi", "Paper Boy"],
      },
      {
        id: "atl_200_03",
        categoryId: "tv_atlanta",
        tier: 200,
        prompt: "What city and state does the show take place in?",
        answer: "Atlanta, Georgia",
        acceptableAnswers: ["Atlanta"],
      },
      {
        id: "atl_400_01",
        categoryId: "tv_atlanta",
        tier: 400,
        prompt: "In the Season 1 episode 'B.A.N.,' Paper Boi appears on a fictional talk show. What makes this episode structurally unique compared to the rest of the series?",
        answer: "It plays out as a complete fake TV broadcast with fictional commercials and talk show segments",
        acceptableAnswers: ["it's structured like a TV broadcast", "fake TV show with fake commercials", "fictional BET-style talk show episode"],
        explanation: "The episode parodies cable news and BET-style programming with fake commercials for products like 'Swisher Sweets' and a transracial debate segment.",
      },
      {
        id: "atl_400_02",
        categoryId: "tv_atlanta",
        tier: 400,
        prompt: "Darius, played by Lakeith Stanfield, is known for his philosophical non sequiturs. In Season 1, what does he invest in at a shooting range that he believes will appreciate in value?",
        answer: "A dog",
        acceptableAnswers: ["a breeding dog", "a Catahoula dog"],
        explanation: "Darius trades a samurai sword for a dog at the shooting range, explaining his long-term breeding investment theory in a signature Darius moment.",
      },
      {
        id: "atl_400_03",
        categoryId: "tv_atlanta",
        tier: 400,
        prompt: "Season 3 takes the cast to Europe. What city serves as the primary setting for most of the European season?",
        answer: "Amsterdam",
        acceptableAnswers: ["Amsterdam, Netherlands"],
        explanation: "Season 3 follows Paper Boi's European tour, with Amsterdam as the main hub, allowing the show to explore race and identity in a European context.",
      },
      {
        id: "atl_600_01",
        categoryId: "tv_atlanta",
        tier: 600,
        prompt: "In the surreal Season 2 episode 'Teddy Perkins,' Donald Glover plays a reclusive, disfigured musician in whiteface prosthetics. What real-life figure is Teddy Perkins widely understood to be based on?",
        answer: "Michael Jackson",
        acceptableAnswers: ["MJ", "Joe Jackson and Michael Jackson"],
        explanation: "Teddy Perkins references Michael Jackson's changing appearance and the cycle of abuse from his father Joe. Glover reportedly stayed in character on set, and the episode is shot like a horror film.",
      },
      {
        id: "atl_600_02",
        categoryId: "tv_atlanta",
        tier: 600,
        prompt: "In Season 4's 'It Was All a Dream,' the show imagines an alternate reality where a white family discovers that a famous person from history was actually Black. Who is that historical figure in the episode?",
        answer: "It's a reparations-themed episode where a white family is assigned to a Black family",
        acceptableAnswers: ["reparations episode", "the episode is about reparations, not a historical figure"],
        explanation: "Season 4 features several standalone anthology episodes exploring race in America. The reparations episode follows a white family court-ordered to serve a Black family.",
      },
      {
        id: "atl_600_03",
        categoryId: "tv_atlanta",
        tier: 600,
        prompt: "Atlanta's Season 3 episode 'Cancer Attack' features a surreal sequence at a film festival party. What horror-adjacent event happens to Earn that blurs the line between social anxiety and actual danger?",
        answer: "He is trapped in an increasingly hostile and racially charged party that escalates into surreal violence",
        acceptableAnswers: ["a party that becomes threatening and surreal", "a dinner party that turns into a racial horror scenario"],
        explanation: "The episode uses the European art-world party as a vehicle for exploring how racial dynamics create genuine danger disguised as polite social gatherings.",
      },
    ],
  },
  {
    id: "tv_barry",
    group: "TV Shows",
    name: "Barry",
    culture: "american",
    description: "Bill Hader's dark HBO comedy about a hitman who discovers a passion for acting in an LA theater class, struggling to leave his violent past behind.",
    imageUrl: "",
    questions: [
      {
        id: "bry_200_01",
        categoryId: "tv_barry",
        tier: 200,
        prompt: "What is Barry Berkman's day job when he's not attending acting class?",
        answer: "He's a hitman",
        acceptableAnswers: ["hitman", "assassin", "contract killer"],
      },
      {
        id: "bry_200_02",
        categoryId: "tv_barry",
        tier: 200,
        prompt: "Who plays the role of Barry Berkman and also co-created the show?",
        answer: "Bill Hader",
        acceptableAnswers: [],
      },
      {
        id: "bry_200_03",
        categoryId: "tv_barry",
        tier: 200,
        prompt: "What is the name of the eccentric acting teacher who runs the theater class Barry joins?",
        answer: "Gene Cousineau",
        acceptableAnswers: ["Gene", "Mr. Cousineau"],
        explanation: "Played by Henry Winkler in an Emmy-winning performance, Gene is a washed-up actor who genuinely believes in the transformative power of the craft.",
      },
      {
        id: "bry_400_01",
        categoryId: "tv_barry",
        tier: 400,
        prompt: "NoHo Hank, the cheerful Chechen mob boss, is one of the show's breakout characters. What actor plays him?",
        answer: "Anthony Carrigan",
        acceptableAnswers: [],
        explanation: "Carrigan's portrayal of Hank as warm, upbeat, and oddly endearing despite being a crime lord became a fan favorite and earned multiple Emmy nominations.",
      },
      {
        id: "bry_400_02",
        categoryId: "tv_barry",
        tier: 400,
        prompt: "In the critically acclaimed Season 1 episode 'Chapter Five: Do Your Job,' Barry is sent to kill a man in a remote location. What makes the sequence a landmark moment in the series' tonal balance?",
        answer: "Barry massacres an entire group of Bolivian cartel members in a brutal, extended action sequence that contrasts sharply with the show's comedy",
        acceptableAnswers: ["he kills a group of Bolivians in a long action scene", "the Bolivian stash house massacre"],
        explanation: "The sequence shocked audiences by revealing the full extent of Barry's lethal capabilities, establishing that the show would never let viewers forget what he really is.",
      },
      {
        id: "bry_400_03",
        categoryId: "tv_barry",
        tier: 400,
        prompt: "What is the name of the aspiring actress and Barry's love interest whose discovery of his true nature becomes a central conflict?",
        answer: "Sally Reed",
        acceptableAnswers: ["Sally"],
        explanation: "Played by Sarah Goldberg, Sally's ambition and self-absorption make her both sympathetic and frustrating as she orbits Barry's increasingly dangerous life.",
      },
      {
        id: "bry_600_01",
        categoryId: "tv_barry",
        tier: 600,
        prompt: "Season 3 features a near-silent episode where Barry pursues a target through the mountains. What makes this episode's visual storytelling distinctive from any other episode in the series?",
        answer: "It is shot almost entirely without dialogue, playing like a survival thriller with minimal music",
        acceptableAnswers: ["almost no dialogue", "silent episode in the mountains", "minimal dialogue survival thriller"],
        explanation: "The episode strips Barry down to pure predator-prey tension, with Hader directing long sequences of tracking and violence in near-total silence.",
      },
      {
        id: "bry_600_02",
        categoryId: "tv_barry",
        tier: 600,
        prompt: "In the series finale, how does Barry ultimately meet his end?",
        answer: "Gene Cousineau shoots and kills him",
        acceptableAnswers: ["Gene shoots him", "Cousineau kills him", "shot by Gene"],
        explanation: "After Barry threatens Gene's family, Cousineau — the man who once tried to mentor him — shoots Barry in his own home, ending the cycle.",
      },
      {
        id: "bry_600_03",
        categoryId: "tv_barry",
        tier: 600,
        prompt: "The series finale includes a flash-forward epilogue. In it, Barry's son watches a movie about the events of the show. What crucial detail does the in-universe film get completely wrong?",
        answer: "The film portrays Barry as a hero and Gene Cousineau as the villain",
        acceptableAnswers: ["it makes Barry the hero", "Barry is shown as heroic and Gene as evil", "the movie reverses who was good and evil"],
        explanation: "The finale's bitter irony: history rewrites Barry as a patriotic hero and Gene as a monster, showing how narratives are distorted over time.",
      },
    ],
  },
  {
    id: "tv_ted_lasso",
    group: "TV Shows",
    name: "Ted Lasso",
    culture: "american",
    description: "An optimistic American college football coach is hired to manage a struggling English Premier League team despite having no soccer experience.",
    imageUrl: "",
    questions: [
      {
        id: "tls_200_01",
        categoryId: "tv_ted_lasso",
        tier: 200,
        prompt: "What is the name of the fictional English football club Ted Lasso is hired to coach?",
        answer: "AFC Richmond",
        acceptableAnswers: ["Richmond"],
      },
      {
        id: "tls_200_02",
        categoryId: "tv_ted_lasso",
        tier: 200,
        prompt: "Who plays Ted Lasso in the series and also co-created the show?",
        answer: "Jason Sudeikis",
        acceptableAnswers: [],
      },
      {
        id: "tls_200_03",
        categoryId: "tv_ted_lasso",
        tier: 200,
        prompt: "What homemade treat does Ted regularly bring to the team owner Rebecca, eventually winning her over?",
        answer: "Biscuits",
        acceptableAnswers: ["shortbread biscuits", "cookies", "biscuits with the boss"],
        explanation: "Ted's 'Biscuits with the Boss' ritual becomes a symbol of his disarming sincerity and a turning point in his relationship with Rebecca.",
      },
      {
        id: "tls_400_01",
        categoryId: "tv_ted_lasso",
        tier: 400,
        prompt: "Rebecca Welton initially hires Ted specifically to sabotage the team as revenge against her ex-husband. Who is her ex-husband?",
        answer: "Rupert Mannion",
        acceptableAnswers: ["Rupert"],
        explanation: "Rupert, played by Anthony Head, owned AFC Richmond before their divorce. Rebecca's initial scheme drives the Season 1 plot.",
      },
      {
        id: "tls_400_02",
        categoryId: "tv_ted_lasso",
        tier: 400,
        prompt: "Jamie Tartt's character arc across the series transforms him from a selfish star striker into a team player. What is the name of the rival club he is loaned to in Season 1?",
        answer: "Manchester City",
        acceptableAnswers: ["Man City"],
        explanation: "Jamie's ego leads to a loan to Man City, but his humbling experiences there and Ted's influence eventually reshape his character.",
      },
      {
        id: "tls_400_03",
        categoryId: "tv_ted_lasso",
        tier: 400,
        prompt: "What is the 'Diamond Dogs' in the context of the show?",
        answer: "A support group where Ted, Coach Beard, Nate, and Higgins discuss personal problems",
        acceptableAnswers: ["Ted's informal support group", "a group of coaches who discuss personal issues", "an informal therapy circle"],
        explanation: "The Diamond Dogs howl before each session, providing a space for emotional vulnerability among the male characters.",
      },
      {
        id: "tls_600_01",
        categoryId: "tv_ted_lasso",
        tier: 600,
        prompt: "The character of Ted Lasso originated from a promotional video for NBC Sports' Premier League coverage. In that original sketch, which real Premier League club was Ted shown coaching?",
        answer: "Tottenham Hotspur",
        acceptableAnswers: ["Tottenham", "Spurs"],
        explanation: "Jason Sudeikis first played Ted Lasso in 2013 NBC Sports promos where Ted was hired to coach Tottenham, years before the character became an Apple TV+ series.",
      },
      {
        id: "tls_600_02",
        categoryId: "tv_ted_lasso",
        tier: 600,
        prompt: "Nate Shelley's transformation from meek kit man to bitter antagonist is a central arc. What symbolic act in the Season 2 finale cements his betrayal of Ted?",
        answer: "He tears up the 'BELIEVE' sign that Ted hung in the locker room",
        acceptableAnswers: ["rips the Believe sign", "tears the Believe sign", "destroys the Believe poster"],
        explanation: "The BELIEVE sign is Ted's most iconic symbol of optimism. Nate ripping it in half is the show's most visceral moment of betrayal.",
      },
      {
        id: "tls_600_03",
        categoryId: "tv_ted_lasso",
        tier: 600,
        prompt: "Ted's panic attacks are a recurring plot thread. In Season 2, he begins seeing a team therapist. What is the therapist's name, and what breakthrough does Ted eventually have about the root of his anxiety?",
        answer: "Dr. Sharon Fieldstone — Ted's anxiety stems from his father's suicide when Ted was sixteen",
        acceptableAnswers: ["Dr. Sharon — his dad's suicide", "Sharon Fieldstone, his father killed himself", "Dr. Sharon, his dad committed suicide"],
        explanation: "Ted's relentless positivity is revealed to be partly a defense mechanism against the trauma of finding his father after his suicide, giving the character unexpected depth.",
      },
    ],
  },
  {
    id: "tv_arcane",
    group: "TV Shows",
    name: "Arcane",
    culture: "universal",
    description: "A visually stunning animated series set in the League of Legends universe, following sisters Vi and Jinx on opposite sides of a conflict between the utopian city of Piltover and the oppressed undercity of Zaun.",
    imageUrl: "",
    questions: [
      {
        id: "arc_200_01",
        categoryId: "tv_arcane",
        tier: 200,
        prompt: "What popular multiplayer game is Arcane based on?",
        answer: "League of Legends",
        acceptableAnswers: ["LoL"],
      },
      {
        id: "arc_200_02",
        categoryId: "tv_arcane",
        tier: 200,
        prompt: "What are the names of the two sister protagonists whose broken bond drives the central conflict of Arcane?",
        answer: "Vi and Jinx",
        acceptableAnswers: ["Vi and Powder", "Violet and Jinx"],
      },
      {
        id: "arc_200_03",
        categoryId: "tv_arcane",
        tier: 200,
        prompt: "What are the two opposing cities in Arcane — one wealthy and above ground, the other impoverished and below?",
        answer: "Piltover and Zaun",
        acceptableAnswers: ["Piltover and the Undercity"],
      },
      {
        id: "arc_400_01",
        categoryId: "tv_arcane",
        tier: 400,
        prompt: "What volatile, glowing purple substance drives much of the conflict in Arcane and serves as both a power source and a dangerous drug?",
        answer: "Shimmer",
        acceptableAnswers: [],
        explanation: "Shimmer grants superhuman abilities but causes addiction and physical mutation. Silco uses it to control Zaun's population while funding his revolution.",
      },
      {
        id: "arc_400_02",
        categoryId: "tv_arcane",
        tier: 400,
        prompt: "What is Jinx's original name before she adopts her chaotic new identity?",
        answer: "Powder",
        acceptableAnswers: [],
        explanation: "The transformation from Powder to Jinx — triggered by a traumatic accident that kills her adopted family — is the emotional core of Season 1.",
      },
      {
        id: "arc_400_03",
        categoryId: "tv_arcane",
        tier: 400,
        prompt: "Which French animation studio produced Arcane's distinctive art style that blends 3D CGI with hand-painted textures?",
        answer: "Fortiche Production",
        acceptableAnswers: ["Fortiche"],
        explanation: "Fortiche developed a unique pipeline blending 3D animation with 2D painted elements, giving Arcane a look unlike any other animated series.",
      },
      {
        id: "arc_600_01",
        categoryId: "tv_arcane",
        tier: 600,
        prompt: "Silco serves as the main antagonist of Season 1 but has a complex relationship with Jinx. In the Season 1 finale, what does Silco say to Jinx as he dies that reframes his entire character?",
        answer: "He tells her he would never have given her up — 'Don't cry. You're perfect.'",
        acceptableAnswers: ["you're perfect", "don't cry you're perfect", "he says she's perfect and he'd never give her up"],
        explanation: "Silco's final words reveal that despite his villainy, his love for Jinx was genuine — mirroring Vander's parental sacrifice and making him one of the show's most nuanced characters.",
      },
      {
        id: "arc_600_02",
        categoryId: "tv_arcane",
        tier: 600,
        prompt: "Arcane took approximately how many years to produce before its 2021 premiere, making it one of the longest production cycles for an animated series of its kind?",
        answer: "Six years",
        acceptableAnswers: ["6 years", "about 6 years"],
        explanation: "Production began around 2015 with Riot Games and Fortiche. The unusually long development allowed the team to develop its groundbreaking visual style.",
      },
      {
        id: "arc_600_03",
        categoryId: "tv_arcane",
        tier: 600,
        prompt: "In Season 2, Jinx fires a rocket at the Piltover council chamber. Which champion from League of Legends lore intervenes in the aftermath and becomes a major Season 2 character tied to the Hextech storyline?",
        answer: "Warwick",
        acceptableAnswers: ["Warwick (formerly Vander)"],
        explanation: "Season 2 reveals that Vander was transformed into Warwick through Singed's experiments, connecting the show's emotional core to League of Legends lore.",
      },
    ],
  },
  {
    id: "mv_alien_franchise",
    group: "Movies",
    name: "Alien Franchise",
    culture: "universal",
    description: "Ridley Scott's sci-fi horror masterpiece and its sequels, following humanity's terrifying encounters with the perfect organism — the Xenomorph.",
    imageUrl: "",
    questions: [
      {
        id: "aln_200_01",
        categoryId: "mv_alien_franchise",
        tier: 200,
        prompt: "In the original 1979 film Alien, what is the name of the spaceship whose crew encounters the Xenomorph?",
        answer: "The Nostromo",
        acceptableAnswers: ["Nostromo", "USCSS Nostromo"],
      },
      {
        id: "aln_200_02",
        categoryId: "mv_alien_franchise",
        tier: 200,
        prompt: "Who plays Ellen Ripley, the franchise's iconic protagonist?",
        answer: "Sigourney Weaver",
        acceptableAnswers: [],
      },
      {
        id: "aln_200_03",
        categoryId: "mv_alien_franchise",
        tier: 200,
        prompt: "What is the tagline of the original 1979 Alien film that became one of the most famous movie taglines ever?",
        answer: "In space, no one can hear you scream",
        acceptableAnswers: [],
      },
      {
        id: "aln_400_01",
        categoryId: "mv_alien_franchise",
        tier: 400,
        prompt: "In Alien, the crew discovers that their science officer Ash is not human. What is he?",
        answer: "An android (synthetic)",
        acceptableAnswers: ["android", "robot", "synthetic", "an android"],
        explanation: "Ash was secretly placed by the Weyland-Yutani corporation to ensure the alien specimen was brought back, crew expendable.",
      },
      {
        id: "aln_400_02",
        categoryId: "mv_alien_franchise",
        tier: 400,
        prompt: "James Cameron directed the 1986 sequel Aliens, which shifted the genre from horror to action. What is the name of the elite military unit sent to investigate the colony on LV-426?",
        answer: "The Colonial Marines",
        acceptableAnswers: ["Colonial Marines", "United States Colonial Marines"],
      },
      {
        id: "aln_400_03",
        categoryId: "mv_alien_franchise",
        tier: 400,
        prompt: "What is the name of the massive corporation that repeatedly tries to weaponize the Xenomorphs throughout the franchise?",
        answer: "Weyland-Yutani",
        acceptableAnswers: ["Weyland-Yutani Corporation", "The Company"],
        explanation: "Often referred to simply as 'The Company,' Weyland-Yutani's corporate greed is the franchise's true recurring villain.",
      },
      {
        id: "aln_600_01",
        categoryId: "mv_alien_franchise",
        tier: 600,
        prompt: "The iconic chestburster scene in the original Alien was famously shot with the cast not knowing exactly what would happen. Which actor's genuine shock reaction is most visible in the final cut?",
        answer: "Veronica Cartwright",
        acceptableAnswers: ["Veronica Cartwright (Lambert)"],
        explanation: "Cartwright was hit with a spray of stage blood and her horrified, screaming reaction was completely genuine. Ridley Scott kept the details secret to capture authentic fear.",
      },
      {
        id: "aln_600_02",
        categoryId: "mv_alien_franchise",
        tier: 600,
        prompt: "H.R. Giger designed the Xenomorph. What was the name of his art book that caught Ridley Scott's attention and led to Giger being hired for the film?",
        answer: "Necronomicon",
        acceptableAnswers: ["H.R. Giger's Necronomicon", "Giger's Necronomicon"],
        explanation: "Giger's Necronomicon (1977) showcased his biomechanical art style. Scott saw it during pre-production and immediately knew Giger should design the alien creature.",
      },
      {
        id: "aln_600_03",
        categoryId: "mv_alien_franchise",
        tier: 600,
        prompt: "In Aliens, the power loader that Ripley uses in the climactic battle was a practical, full-scale prop. How was the effect of it walking achieved on set?",
        answer: "Sigourney Weaver was strapped into the prop and a stunt performer hidden behind her operated the legs",
        acceptableAnswers: ["a stunt person walked behind her operating the legs", "hidden operator behind Weaver", "someone hidden inside operated it like a puppet"],
        explanation: "The power loader was not CGI — it was a full practical rig with a hidden operator. The shot framing carefully concealed the person walking the prop from behind.",
      },
    ],
  },
  {
    id: "mv_blade_runner",
    group: "Movies",
    name: "Blade Runner",
    culture: "universal",
    description: "Ridley Scott's neo-noir sci-fi masterpiece exploring what it means to be human through a detective hunting rogue androids in a rain-soaked dystopian Los Angeles.",
    imageUrl: "",
    questions: [
      {
        id: "blr_200_01",
        categoryId: "mv_blade_runner",
        tier: 200,
        prompt: "In Blade Runner, what are the bioengineered beings that the protagonist hunts called?",
        answer: "Replicants",
        acceptableAnswers: [],
      },
      {
        id: "blr_200_02",
        categoryId: "mv_blade_runner",
        tier: 200,
        prompt: "Who plays Rick Deckard, the blade runner tasked with hunting down escaped replicants?",
        answer: "Harrison Ford",
        acceptableAnswers: [],
      },
      {
        id: "blr_200_03",
        categoryId: "mv_blade_runner",
        tier: 200,
        prompt: "What year is the original Blade Runner set in?",
        answer: "2019",
        acceptableAnswers: ["November 2019"],
      },
      {
        id: "blr_400_01",
        categoryId: "mv_blade_runner",
        tier: 400,
        prompt: "Roy Batty delivers a famous dying monologue that begins 'I've seen things you people wouldn't believe.' What actor played Roy Batty?",
        answer: "Rutger Hauer",
        acceptableAnswers: [],
        explanation: "Hauer famously improvised parts of the 'Tears in Rain' monologue, condensing a longer scripted speech into one of cinema's most iconic death scenes.",
      },
      {
        id: "blr_400_02",
        categoryId: "mv_blade_runner",
        tier: 400,
        prompt: "What test does Deckard administer to determine whether someone is a replicant, based on measuring involuntary emotional responses?",
        answer: "The Voigt-Kampff test",
        acceptableAnswers: ["Voight-Kampff", "VK test"],
        explanation: "The test measures pupil dilation, blush response, and other biometrics during emotionally provocative questioning.",
      },
      {
        id: "blr_400_03",
        categoryId: "mv_blade_runner",
        tier: 400,
        prompt: "What Philip K. Dick novel is Blade Runner based on?",
        answer: "Do Androids Dream of Electric Sheep?",
        acceptableAnswers: ["Do Androids Dream of Electric Sheep"],
      },
      {
        id: "blr_600_01",
        categoryId: "mv_blade_runner",
        tier: 600,
        prompt: "Blade Runner has had multiple official cuts released. How many distinct versions exist, and which one is considered the definitive version by Ridley Scott?",
        answer: "Seven versions exist, and the Final Cut (2007) is Scott's definitive version",
        acceptableAnswers: ["7 versions, the Final Cut", "seven, the Final Cut is definitive"],
        explanation: "The seven versions include the workprint, US theatrical, international theatrical, Director's Cut (1992), and the 2007 Final Cut, among others.",
      },
      {
        id: "blr_600_02",
        categoryId: "mv_blade_runner",
        tier: 600,
        prompt: "In Blade Runner 2049, K discovers a wooden horse toy that becomes key evidence. What is carved into the bottom of the horse?",
        answer: "A date — 6-10-21",
        acceptableAnswers: ["a date", "6-10-21", "June 10 2021"],
        explanation: "The date corresponds to the birth of Deckard and Rachael's child, making the horse a crucial piece of evidence in K's investigation.",
      },
      {
        id: "blr_600_03",
        categoryId: "mv_blade_runner",
        tier: 600,
        prompt: "Vangelis composed Blade Runner's iconic synthesizer score, but the official soundtrack wasn't released until over a decade after the film. Why was the release delayed so long?",
        answer: "A legal dispute between Vangelis and the studio over rights and Vangelis's dissatisfaction with the proposed album format",
        acceptableAnswers: ["legal and creative disputes", "rights dispute with Vangelis", "contractual issues with Vangelis"],
        explanation: "The official Vangelis soundtrack wasn't released until 1994, twelve years after the film. In the interim, a 'New American Orchestra' cover album was released instead, frustrating fans.",
      },
    ],
  },
  {
    id: "mv_spielberg",
    group: "Movies",
    name: "Steven Spielberg",
    culture: "universal",
    description: "The filmography and legacy of Steven Spielberg, one of cinema's most influential directors — from blockbusters like Jaws and Jurassic Park to dramas like Schindler's List.",
    imageUrl: "",
    questions: [
      {
        id: "spb_200_01",
        categoryId: "mv_spielberg",
        tier: 200,
        prompt: "Which 1975 Spielberg film about a great white shark terrorizing a beach town is often credited as the first modern blockbuster?",
        answer: "Jaws",
        acceptableAnswers: [],
      },
      {
        id: "spb_200_02",
        categoryId: "mv_spielberg",
        tier: 200,
        prompt: "Spielberg directed the original Jurassic Park. What author wrote the novel it was based on?",
        answer: "Michael Crichton",
        acceptableAnswers: [],
      },
      {
        id: "spb_200_03",
        categoryId: "mv_spielberg",
        tier: 200,
        prompt: "What is the name of the friendly alien in Spielberg's 1982 film who just wants to phone home?",
        answer: "E.T.",
        acceptableAnswers: ["ET", "E.T. the Extra-Terrestrial"],
      },
      {
        id: "spb_400_01",
        categoryId: "mv_spielberg",
        tier: 400,
        prompt: "Spielberg released both Jurassic Park and Schindler's List in the same year. What year was that remarkable double release?",
        answer: "1993",
        acceptableAnswers: [],
        explanation: "Spielberg released the highest-grossing film of the year AND won the Best Picture and Best Director Oscars in the same year — an unprecedented achievement.",
      },
      {
        id: "spb_400_02",
        categoryId: "mv_spielberg",
        tier: 400,
        prompt: "In Saving Private Ryan, the opening D-Day sequence at Omaha Beach is considered one of the greatest battle scenes ever filmed. How long does that opening sequence last?",
        answer: "Approximately 27 minutes",
        acceptableAnswers: ["about 25 minutes", "about 27 minutes", "around 25-27 minutes", "roughly 27 minutes"],
        explanation: "The sequence was so realistic that it triggered PTSD responses in actual World War II veterans who watched it.",
      },
      {
        id: "spb_400_03",
        categoryId: "mv_spielberg",
        tier: 400,
        prompt: "The mechanical shark in Jaws was notoriously unreliable during filming. What did the crew nickname the shark?",
        answer: "Bruce",
        acceptableAnswers: [],
        explanation: "Named after Spielberg's lawyer Bruce Ramer, the constantly malfunctioning shark forced Spielberg to show less of it — accidentally making the film scarier.",
      },
      {
        id: "spb_600_01",
        categoryId: "mv_spielberg",
        tier: 600,
        prompt: "Spielberg was rejected from USC's film school multiple times. Which university did he actually attend before dropping out to pursue filmmaking?",
        answer: "California State University, Long Beach",
        acceptableAnswers: ["Cal State Long Beach", "CSULB"],
        explanation: "Spielberg was famously rejected by USC two or three times. He attended Cal State Long Beach but left to take a TV directing contract at Universal.",
      },
      {
        id: "spb_600_02",
        categoryId: "mv_spielberg",
        tier: 600,
        prompt: "Spielberg has said he regrets a specific change he made to a re-release of E.T. What did he digitally alter that he later reversed for the anniversary edition?",
        answer: "He replaced the FBI agents' guns with walkie-talkies",
        acceptableAnswers: ["changed guns to walkie-talkies", "digitally removed guns and added walkie-talkies"],
        explanation: "For the 2002 re-release, Spielberg digitally replaced the agents' shotguns with walkie-talkies. He later called it a mistake and restored the original for the Blu-ray.",
      },
      {
        id: "spb_600_03",
        categoryId: "mv_spielberg",
        tier: 600,
        prompt: "During the filming of Schindler's List in Poland, Spielberg was so emotionally overwhelmed that he called a friend each evening to cheer him up. Who was that friend?",
        answer: "Robin Williams",
        acceptableAnswers: [],
        explanation: "Robin Williams would call Spielberg and do comedy bits to help him cope with the emotionally devastating material he was filming each day.",
      },
    ],
  },
  {
    id: "mv_pixar_deep",
    group: "Movies",
    name: "Pixar Deep Cuts",
    culture: "universal",
    description: "Deep knowledge of Pixar Animation Studios — from production secrets and Easter eggs to the hidden connections across their filmography.",
    imageUrl: "",
    questions: [
      {
        id: "pxr_200_01",
        categoryId: "mv_pixar_deep",
        tier: 200,
        prompt: "What was Pixar's first feature-length film, released in 1995?",
        answer: "Toy Story",
        acceptableAnswers: [],
      },
      {
        id: "pxr_200_02",
        categoryId: "mv_pixar_deep",
        tier: 200,
        prompt: "In Inside Out, what are the names of the five core emotions personified inside Riley's mind?",
        answer: "Joy, Sadness, Anger, Fear, and Disgust",
        acceptableAnswers: ["Joy, Sadness, Anger, Fear, Disgust"],
      },
      {
        id: "pxr_200_03",
        categoryId: "mv_pixar_deep",
        tier: 200,
        prompt: "What is the name of the pizza restaurant chain that appears as an Easter egg in almost every Pixar film?",
        answer: "Pizza Planet",
        acceptableAnswers: [],
      },
      {
        id: "pxr_400_01",
        categoryId: "mv_pixar_deep",
        tier: 400,
        prompt: "The Pixar Theory suggests all Pixar films exist in the same universe. Which film is theorized to take place furthest in the future in this timeline?",
        answer: "Monsters, Inc.",
        acceptableAnswers: ["Monsters Inc"],
        explanation: "In the Pixar Theory, monsters are mutated post-apocalyptic humans, and the doors are time portals — placing Monsters, Inc. at the far end of the timeline.",
      },
      {
        id: "pxr_400_02",
        categoryId: "mv_pixar_deep",
        tier: 400,
        prompt: "What is the code A113 that appears hidden in nearly every Pixar film a reference to?",
        answer: "A classroom at the California Institute of the Arts where many Pixar animators studied",
        acceptableAnswers: ["a CalArts classroom", "classroom A113 at CalArts", "a room at California Institute of the Arts"],
      },
      {
        id: "pxr_400_03",
        categoryId: "mv_pixar_deep",
        tier: 400,
        prompt: "Pixar nearly lost all of Toy Story 2 during production due to a catastrophic data loss. How was the film saved?",
        answer: "A technical director who was working from home on maternity leave had a recent backup on her home computer",
        acceptableAnswers: ["an employee had a backup at home", "someone working from home had a copy", "a home backup saved it"],
        explanation: "Galyn Susman had been working remotely and had a near-complete copy. Without her backup, months of work would have been permanently lost.",
      },
      {
        id: "pxr_600_01",
        categoryId: "mv_pixar_deep",
        tier: 600,
        prompt: "Before Toy Story, Pixar produced a short film that became the first CGI film to be nominated for an Academy Award. What was it called?",
        answer: "Luxo Jr.",
        acceptableAnswers: ["Luxo Junior"],
        explanation: "The 1986 short featuring a parent and child desk lamp established Pixar's ability to create emotional storytelling with CGI. The Luxo lamp became Pixar's mascot.",
      },
      {
        id: "pxr_600_02",
        categoryId: "mv_pixar_deep",
        tier: 600,
        prompt: "Pixar was originally a hardware company selling the Pixar Image Computer. Which company owned it before Steve Jobs bought it in 1986?",
        answer: "Lucasfilm",
        acceptableAnswers: ["Lucasfilm Ltd", "George Lucas"],
        explanation: "Pixar began as the Graphics Group within Lucasfilm's Computer Division. Jobs bought it for $5 million plus $5 million in capital, eventually seeing it become worth billions.",
      },
      {
        id: "pxr_600_03",
        categoryId: "mv_pixar_deep",
        tier: 600,
        prompt: "During the development of the original Toy Story, Disney executives ordered a retool after seeing a story reel that made Woody deeply unlikable. What is this infamous version known as internally?",
        answer: "Black Friday",
        acceptableAnswers: ["the Black Friday reel", "Black Friday screening"],
        explanation: "The November 19, 1993 screening showed a sarcastic, mean Woody that horrified Disney. Production was shut down and the team rewrote the story, making Woody the lovable character we know.",
      },
    ],
  },
  {
    id: "mu_queen",
    group: "Music",
    name: "Queen",
    culture: "universal",
    description: "The legendary British rock band known for operatic harmonies, stadium anthems, and Freddie Mercury's unparalleled showmanship.",
    imageUrl: "",
    questions: [
      {
        id: "que_200_01",
        categoryId: "mu_queen",
        tier: 200,
        prompt: "What is the name of Queen's iconic six-minute rock opera that features the famous headbanging section?",
        answer: "Bohemian Rhapsody",
        acceptableAnswers: [],
      },
      {
        id: "que_200_02",
        categoryId: "mu_queen",
        tier: 200,
        prompt: "Who was Queen's legendary lead vocalist known for his extraordinary vocal range?",
        answer: "Freddie Mercury",
        acceptableAnswers: ["Freddie", "Farrokh Bulsara"],
      },
      {
        id: "que_200_03",
        categoryId: "mu_queen",
        tier: 200,
        prompt: "Which Queen song features the instantly recognizable stomp-stomp-clap rhythm and has become one of the most played stadium anthems of all time?",
        answer: "We Will Rock You",
        acceptableAnswers: [],
      },
      {
        id: "que_400_01",
        categoryId: "mu_queen",
        tier: 400,
        prompt: "Brian May, Queen's guitarist, built his iconic guitar with his father as a teenager. What is this homemade guitar called?",
        answer: "The Red Special",
        acceptableAnswers: ["Red Special"],
        explanation: "May and his father built the Red Special from an old fireplace mantel and other household materials. He has played it on virtually every Queen recording.",
      },
      {
        id: "que_400_02",
        categoryId: "mu_queen",
        tier: 400,
        prompt: "Queen's 1985 Live Aid performance at Wembley Stadium is considered one of the greatest live performances in rock history. Approximately how many people watched the global broadcast?",
        answer: "Approximately 1.9 billion",
        acceptableAnswers: ["1.9 billion", "nearly 2 billion", "about 2 billion", "1.5 billion"],
        explanation: "Queen's 20-minute set, with Mercury commanding the crowd through call-and-response, is often cited as the single greatest live rock performance ever.",
      },
      {
        id: "que_400_03",
        categoryId: "mu_queen",
        tier: 400,
        prompt: "The album 'A Night at the Opera,' which contains Bohemian Rhapsody, takes its name from a film by which comedy act?",
        answer: "The Marx Brothers",
        acceptableAnswers: ["Marx Brothers"],
        explanation: "Both 'A Night at the Opera' and its sequel 'A Day at the Races' are named after Marx Brothers films, reflecting the band's theatrical sensibility.",
      },
      {
        id: "que_600_01",
        categoryId: "mu_queen",
        tier: 600,
        prompt: "Freddie Mercury's birth name was Farrokh Bulsara. He was born on the island of Zanzibar and grew up partly in which country, where he attended a British-style boarding school?",
        answer: "India",
        acceptableAnswers: ["India (Panchgani)"],
        explanation: "Mercury attended St. Peter's School in Panchgani, India, where he formed his first band, The Hectics, at age twelve.",
      },
      {
        id: "que_600_02",
        categoryId: "mu_queen",
        tier: 600,
        prompt: "Queen and David Bowie collaborated on 'Under Pressure.' The famous bassline was created during an improvised jam session. Which Queen member played it, and why was there later a dispute about the song?",
        answer: "John Deacon played the bassline. Bowie and Queen disagreed over mixing and creative control, with Bowie insisting on his own vocal approach",
        acceptableAnswers: ["John Deacon, and Bowie and Mercury clashed over the mix", "Deacon played it, there were disputes over creative control"],
        explanation: "The legendary bassline was improvised by Deacon during the session. Bowie reportedly wanted more control over the final mix, leading to tension with Mercury.",
      },
      {
        id: "que_600_03",
        categoryId: "mu_queen",
        tier: 600,
        prompt: "Brian May holds a PhD in astrophysics, completing his thesis decades after starting it. What was the specific subject of his doctoral thesis?",
        answer: "Radial velocities in the zodiacal dust cloud",
        acceptableAnswers: ["zodiacal dust cloud", "dust in the solar system", "zodiacal light"],
        explanation: "May began his PhD at Imperial College London in the 1970s but abandoned it when Queen took off. He returned and completed it in 2007, over 30 years later.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 59 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
