#!/usr/bin/env python3
"""Insert wave 61 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "his_aztec_empire",
    group: "History",
    name: "Aztec Empire",
    culture: "universal",
    description: "The rise and fall of the Mexica people who built Tenochtitlan into the most powerful city in Mesoamerica before the Spanish conquest.",
    imageUrl: "",
    questions: [
      {
        id: "azt_200_01",
        categoryId: "his_aztec_empire",
        tier: 200,
        prompt: "What was the name of the Aztec capital city, built on an island in Lake Texcoco, which is now the site of Mexico City?",
        answer: "Tenochtitlan",
        acceptableAnswers: [],
      },
      {
        id: "azt_200_02",
        categoryId: "his_aztec_empire",
        tier: 200,
        prompt: "Which Spanish conquistador led the expedition that conquered the Aztec Empire in 1521?",
        answer: "Hernán Cortés",
        acceptableAnswers: ["Cortes", "Hernando Cortes"],
      },
      {
        id: "azt_200_03",
        categoryId: "his_aztec_empire",
        tier: 200,
        prompt: "What was the name of the last Aztec emperor who was captured by the Spanish?",
        answer: "Montezuma II (Moctezuma)",
        acceptableAnswers: ["Montezuma", "Moctezuma", "Moctezuma II"],
      },
      {
        id: "azt_400_01",
        categoryId: "his_aztec_empire",
        tier: 400,
        prompt: "The Aztecs practiced large-scale human sacrifice. At the re-dedication of the Great Temple (Templo Mayor) in 1487, how many people were reportedly sacrificed over four days?",
        answer: "Approximately 20,000 (some sources claim up to 80,000, though modern estimates vary widely)",
        acceptableAnswers: ["20,000", "thousands", "tens of thousands"],
        explanation: "While exact numbers are debated, the scale was enormous and served both religious and political purposes — demonstrating the empire's power to visiting dignitaries.",
      },
      {
        id: "azt_400_02",
        categoryId: "his_aztec_empire",
        tier: 400,
        prompt: "The Aztec Empire was actually a Triple Alliance of three city-states. Tenochtitlan was one. Name either of the other two.",
        answer: "Texcoco and Tlacopan",
        acceptableAnswers: ["Texcoco", "Tlacopan", "Tacuba"],
        explanation: "The alliance was formed in 1428, but Tenochtitlan gradually became the dominant partner, with Texcoco as the cultural center and Tlacopan as the junior partner.",
      },
      {
        id: "azt_400_03",
        categoryId: "his_aztec_empire",
        tier: 400,
        prompt: "What agricultural technique did the Aztecs use to farm on the lake, creating artificial islands of crops that amazed the Spanish upon arrival?",
        answer: "Chinampas (floating gardens)",
        acceptableAnswers: ["chinampas", "floating gardens"],
        explanation: "Chinampas were rectangular areas of fertile land created by layering mud, vegetation, and soil on shallow lake beds, anchored by willow trees.",
      },
      {
        id: "azt_600_01",
        categoryId: "his_aztec_empire",
        tier: 600,
        prompt: "Cortés's conquest was aided by a woman who served as translator and advisor. Known by multiple names, what are her most common names in Mexican and Spanish historical accounts?",
        answer: "La Malinche (also called Doña Marina or Malintzin)",
        acceptableAnswers: ["La Malinche", "Malinche", "Dona Marina", "Malintzin"],
        explanation: "Malinche is one of the most controversial figures in Mexican history — seen as both a traitor and a survivor. Her multilingual abilities were crucial to the conquest.",
      },
      {
        id: "azt_600_02",
        categoryId: "his_aztec_empire",
        tier: 600,
        prompt: "The Aztec calendar system used two interlocking calendars. One was the 365-day solar calendar (Xiuhpohualli). What was the other ritual calendar called, and how many days was its cycle?",
        answer: "The Tonalpohualli — a 260-day ritual calendar",
        acceptableAnswers: ["Tonalpohualli, 260 days", "Tonalpohualli"],
        explanation: "The two calendars interlocked to create a 52-year 'Calendar Round.' The end of each 52-year cycle was marked by the New Fire ceremony, a critical religious event.",
      },
      {
        id: "azt_600_03",
        categoryId: "his_aztec_empire",
        tier: 600,
        prompt: "A disease brought by the Spanish played a devastating role in the fall of Tenochtitlan, killing a large portion of the population including a key Aztec leader. What was the disease, and which leader did it kill?",
        answer: "Smallpox — it killed Cuitláhuac, Moctezuma's successor, after only 80 days of rule",
        acceptableAnswers: ["smallpox killed Cuitlahuac", "smallpox, Cuitlahuac"],
        explanation: "Cuitláhuac had successfully driven the Spanish out during La Noche Triste but died of smallpox before he could consolidate the defense, critically weakening Aztec leadership.",
      },
    ],
  },
  {
    id: "his_inca_empire",
    group: "History",
    name: "Inca Empire",
    culture: "universal",
    description: "The largest empire in pre-Columbian America, stretching along the Andes from Colombia to Chile, connected by an extraordinary network of roads and organized without a writing system.",
    imageUrl: "",
    questions: [
      {
        id: "inc_200_01",
        categoryId: "his_inca_empire",
        tier: 200,
        prompt: "What is the name of the famous 'Lost City of the Incas' rediscovered by Hiram Bingham in 1911, perched high in the Andes Mountains of Peru?",
        answer: "Machu Picchu",
        acceptableAnswers: [],
      },
      {
        id: "inc_200_02",
        categoryId: "his_inca_empire",
        tier: 200,
        prompt: "What was the Inca capital city, located in modern-day Peru?",
        answer: "Cusco",
        acceptableAnswers: ["Cuzco"],
      },
      {
        id: "inc_200_03",
        categoryId: "his_inca_empire",
        tier: 200,
        prompt: "Which Spanish conquistador conquered the Inca Empire?",
        answer: "Francisco Pizarro",
        acceptableAnswers: ["Pizarro"],
      },
      {
        id: "inc_400_01",
        categoryId: "his_inca_empire",
        tier: 400,
        prompt: "The Incas had no written language but used a recording system made of knotted strings. What was this device called?",
        answer: "Quipu (or Khipu)",
        acceptableAnswers: ["quipu", "khipu"],
        explanation: "Quipus used colored strings with knots at different positions to record numerical data, census information, and possibly narratives. Their full complexity is still being decoded.",
      },
      {
        id: "inc_400_02",
        categoryId: "his_inca_empire",
        tier: 400,
        prompt: "Pizarro captured the Inca emperor Atahualpa at the Battle of Cajamarca. What enormous ransom did Atahualpa offer for his freedom?",
        answer: "A room filled once with gold and twice with silver",
        acceptableAnswers: ["a room full of gold", "gold and silver to fill a room", "a ransom room of gold and silver"],
        explanation: "Atahualpa offered to fill a room approximately 22 feet long and 17 feet wide with gold, and fill it twice more with silver. Pizarro accepted the ransom but executed him anyway.",
      },
      {
        id: "inc_400_03",
        categoryId: "his_inca_empire",
        tier: 400,
        prompt: "The Inca road system, called Qhapaq Ñan, was one of the most extensive in the pre-industrial world. Approximately how long was the total road network?",
        answer: "About 40,000 kilometers (25,000 miles)",
        acceptableAnswers: ["40,000 km", "25,000 miles", "about 25,000 miles", "around 40,000 kilometers"],
        explanation: "The network connected the entire empire through mountains and deserts, featuring suspension bridges, tunnels, and relay stations called tambos.",
      },
      {
        id: "inc_600_01",
        categoryId: "his_inca_empire",
        tier: 600,
        prompt: "The Inca practiced a labor tax system instead of monetary taxation. What was this system called, and how did it work?",
        answer: "Mit'a — citizens owed a set period of labor to the state, used for construction, military service, farming, and mining",
        acceptableAnswers: ["mit'a", "mita", "the mita labor system"],
        explanation: "The mit'a system was later brutally exploited by the Spanish, who used it to force indigenous labor in silver mines like Potosí.",
      },
      {
        id: "inc_600_02",
        categoryId: "his_inca_empire",
        tier: 600,
        prompt: "Inca stonework at sites like Sacsayhuamán is famous for fitting massive stones together without mortar so precisely that a knife blade cannot fit between them. What technique did they use?",
        answer: "Trial-and-error grinding and fitting — stones were shaped by repeatedly placing them, marking high points, and grinding them down until they fit perfectly",
        acceptableAnswers: ["grinding and fitting", "trial fitting and grinding", "they ground stones to fit perfectly"],
        explanation: "This technique, combined with the polygonal shapes of the stones, created walls that have survived centuries of earthquakes — outperforming Spanish colonial buildings built above them.",
      },
      {
        id: "inc_600_03",
        categoryId: "his_inca_empire",
        tier: 600,
        prompt: "After the fall of Cusco, a rump Inca state survived for decades in a remote jungle fortress. What was this last stronghold called, and when did it finally fall?",
        answer: "Vilcabamba — it fell in 1572 when the last Inca emperor Túpac Amaru was captured and executed by the Spanish",
        acceptableAnswers: ["Vilcabamba", "Vilcabamba in 1572"],
        explanation: "The Neo-Inca State at Vilcabamba resisted for 36 years after the fall of Cusco. Túpac Amaru's public execution in Cusco's main plaza was meant to end Inca resistance permanently.",
      },
    ],
  },
  {
    id: "his_pirate_golden_age",
    group: "History",
    name: "Golden Age of Piracy",
    culture: "universal",
    description: "The legendary era of piracy from roughly 1650 to 1730, when buccaneers, privateers, and outlaws terrorized the Caribbean, Atlantic, and Indian Ocean.",
    imageUrl: "",
    questions: [
      {
        id: "pir_200_01",
        categoryId: "his_pirate_golden_age",
        tier: 200,
        prompt: "Which feared pirate was known as 'Blackbeard' and terrorized the American colonies and Caribbean before being killed in 1718?",
        answer: "Edward Teach",
        acceptableAnswers: ["Edward Thatch", "Blackbeard"],
      },
      {
        id: "pir_200_02",
        categoryId: "his_pirate_golden_age",
        tier: 200,
        prompt: "What was the skull-and-crossbones pirate flag commonly called?",
        answer: "Jolly Roger",
        acceptableAnswers: [],
      },
      {
        id: "pir_200_03",
        categoryId: "his_pirate_golden_age",
        tier: 200,
        prompt: "What Caribbean island city, destroyed by an earthquake in 1692, was known as 'the wickedest city on Earth' and served as a pirate haven?",
        answer: "Port Royal",
        acceptableAnswers: ["Port Royal, Jamaica"],
      },
      {
        id: "pir_400_01",
        categoryId: "his_pirate_golden_age",
        tier: 400,
        prompt: "Pirates often operated under written codes of conduct that all crew members signed. What were these agreements called?",
        answer: "Articles of Agreement (pirate codes or ship's articles)",
        acceptableAnswers: ["articles", "pirate code", "ship's articles", "articles of agreement"],
        explanation: "These surprisingly democratic documents specified profit shares, compensation for injuries, rules of conduct, and voting rights — making pirate ships among the most egalitarian organizations of their era.",
      },
      {
        id: "pir_400_02",
        categoryId: "his_pirate_golden_age",
        tier: 400,
        prompt: "What was the difference between a pirate and a privateer?",
        answer: "A privateer carried a government-issued letter of marque authorizing them to attack enemy ships — making their raiding legal under that nation's flag",
        acceptableAnswers: ["privateers had government permission", "privateers had a letter of marque", "privateers were legal, pirates were not"],
      },
      {
        id: "pir_400_03",
        categoryId: "his_pirate_golden_age",
        tier: 400,
        prompt: "Bartholomew Roberts (Black Bart) is considered the most successful pirate of the Golden Age. Approximately how many ships did he capture during his career?",
        answer: "Over 400 ships",
        acceptableAnswers: ["400", "about 400", "over 400"],
        explanation: "Roberts captured more ships than any other pirate in history. He was also known for his flamboyant dress and strict personal code — he reportedly didn't drink.",
      },
      {
        id: "pir_600_01",
        categoryId: "his_pirate_golden_age",
        tier: 600,
        prompt: "The Republic of Pirates was a loose pirate haven established in Nassau, Bahamas. Which former privateer established it as a base, and who was the British governor sent to end it?",
        answer: "Benjamin Hornigold helped establish the Nassau base; Woodes Rogers was sent as governor to suppress piracy in 1718",
        acceptableAnswers: ["Hornigold and Woodes Rogers", "Benjamin Hornigold, Woodes Rogers"],
        explanation: "Rogers offered pardons to pirates who surrendered and hanged those who didn't. Ironically, Hornigold accepted the pardon and became a pirate hunter for Rogers.",
      },
      {
        id: "pir_600_02",
        categoryId: "his_pirate_golden_age",
        tier: 600,
        prompt: "Ching Shih commanded the largest pirate fleet in history in the South China Sea. At her peak, how many ships were under her command, and how did her career end?",
        answer: "She commanded about 1,800 ships and 70,000-80,000 pirates. She negotiated amnesty with the Chinese government and retired wealthy, opening a gambling house.",
        acceptableAnswers: ["1800 ships, she negotiated retirement", "over 1500 ships and retired through amnesty"],
        explanation: "Ching Shih is arguably the most successful pirate in history. She maintained strict discipline with a written code and defeated every fleet sent against her.",
      },
      {
        id: "pir_600_03",
        categoryId: "his_pirate_golden_age",
        tier: 600,
        prompt: "The capture and trial of Captain William Kidd is one of the most controversial episodes in pirate history. Why do many historians argue Kidd was not actually a pirate?",
        answer: "Kidd was a licensed privateer who captured a ship (the Quedagh Merchant) that was sailing under French passes, making it a legal prize — but political enemies used the incident against him",
        acceptableAnswers: ["he was a privateer with a legal commission", "he had a letter of marque and his captures were arguably legal", "political enemies framed him"],
        explanation: "Kidd's backers in the English government abandoned him when the captures became politically embarrassing. His 1701 execution was likely a miscarriage of justice.",
      },
    ],
  },
  {
    id: "sci_volcanology",
    group: "Science",
    name: "Volcanology",
    culture: "universal",
    description: "The science of volcanoes — from explosive eruptions and lava flows to supervolcanoes and their impact on climate and civilization.",
    imageUrl: "",
    questions: [
      {
        id: "vol_200_01",
        categoryId: "sci_volcanology",
        tier: 200,
        prompt: "What famous volcano buried the Roman city of Pompeii in 79 AD?",
        answer: "Mount Vesuvius",
        acceptableAnswers: ["Vesuvius"],
      },
      {
        id: "vol_200_02",
        categoryId: "sci_volcanology",
        tier: 200,
        prompt: "What is the molten rock called when it is underground versus when it flows on the surface?",
        answer: "Magma underground, lava on the surface",
        acceptableAnswers: ["magma and lava"],
      },
      {
        id: "vol_200_03",
        categoryId: "sci_volcanology",
        tier: 200,
        prompt: "The 'Ring of Fire' is a zone of intense volcanic and earthquake activity. Which ocean does it encircle?",
        answer: "The Pacific Ocean",
        acceptableAnswers: ["Pacific"],
      },
      {
        id: "vol_400_01",
        categoryId: "sci_volcanology",
        tier: 400,
        prompt: "The 1883 eruption of Krakatoa was one of the loudest sounds in recorded history. How far away was the sound heard?",
        answer: "Over 3,000 miles (nearly 5,000 km) — it was heard in Australia and the island of Rodrigues near Mauritius",
        acceptableAnswers: ["3000 miles", "over 3000 miles", "thousands of miles"],
        explanation: "The eruption generated a pressure wave that circled the globe multiple times and was recorded on barographs worldwide.",
      },
      {
        id: "vol_400_02",
        categoryId: "sci_volcanology",
        tier: 400,
        prompt: "What is a pyroclastic flow, and why is it considered the deadliest volcanic hazard?",
        answer: "A fast-moving current of hot gas and volcanic matter that races down the slopes at up to 700 km/h and temperatures over 700°C — essentially unsurvivable",
        acceptableAnswers: ["a fast hot cloud of gas and rock", "a superheated flow of gas and debris", "fast-moving hot gas and volcanic material"],
      },
      {
        id: "vol_400_03",
        categoryId: "sci_volcanology",
        tier: 400,
        prompt: "The 1815 eruption of Mount Tambora in Indonesia led to global climate effects. What was the following year, 1816, called due to widespread crop failures?",
        answer: "The Year Without a Summer",
        acceptableAnswers: ["year without a summer"],
        explanation: "Tambora ejected so much ash into the stratosphere that global temperatures dropped, causing frost in June across New England and Europe and widespread famine.",
      },
      {
        id: "vol_600_01",
        categoryId: "sci_volcanology",
        tier: 600,
        prompt: "Yellowstone National Park sits atop a supervolcano. What is the approximate size of the Yellowstone caldera, and when was its last supereruption?",
        answer: "The caldera is roughly 45 by 34 miles (72 by 55 km). The last supereruption was approximately 640,000 years ago",
        acceptableAnswers: ["about 45 by 34 miles, 640,000 years ago", "640,000 years ago"],
        explanation: "Yellowstone has had three supereruptions: 2.1 million, 1.3 million, and 640,000 years ago. A future eruption would have continental-scale effects.",
      },
      {
        id: "vol_600_02",
        categoryId: "sci_volcanology",
        tier: 600,
        prompt: "The Volcanic Explosivity Index (VEI) measures eruption magnitude on a scale of 0-8. What is the only eruption in recorded human history to reach VEI 7?",
        answer: "The 1815 eruption of Mount Tambora",
        acceptableAnswers: ["Tambora", "Mount Tambora 1815"],
        explanation: "Tambora's eruption ejected roughly 160 cubic kilometers of material — the largest eruption in recorded history. No VEI 8 event has occurred in human history.",
      },
      {
        id: "vol_600_03",
        categoryId: "sci_volcanology",
        tier: 600,
        prompt: "In 1943, a farmer in Mexico watched a volcano literally grow from a crack in his cornfield. What is the name of this volcano, and how tall did it eventually grow?",
        answer: "Parícutin — it grew to about 424 meters (1,391 feet) above the original ground level over nine years",
        acceptableAnswers: ["Paricutin", "Parícutin"],
        explanation: "Parícutin is one of the most documented volcanic births in history. Farmer Dionisio Pulido watched the ground crack open and within a week it was a 50-meter cone.",
      },
    ],
  },
  {
    id: "sci_virology",
    group: "Science",
    name: "Virology",
    culture: "universal",
    description: "The fascinating and terrifying world of viruses — from pandemics that shaped history to the cutting-edge science of how these tiny replicators work.",
    imageUrl: "",
    questions: [
      {
        id: "vir_200_01",
        categoryId: "sci_virology",
        tier: 200,
        prompt: "What type of virus caused the COVID-19 pandemic that began in 2019?",
        answer: "A coronavirus (SARS-CoV-2)",
        acceptableAnswers: ["coronavirus", "SARS-CoV-2"],
      },
      {
        id: "vir_200_02",
        categoryId: "sci_virology",
        tier: 200,
        prompt: "What is the only human disease to have been completely eradicated through vaccination?",
        answer: "Smallpox",
        acceptableAnswers: [],
      },
      {
        id: "vir_200_03",
        categoryId: "sci_virology",
        tier: 200,
        prompt: "Are antibiotics effective against viruses?",
        answer: "No — antibiotics only work against bacteria, not viruses",
        acceptableAnswers: ["no"],
      },
      {
        id: "vir_400_01",
        categoryId: "sci_virology",
        tier: 400,
        prompt: "Viruses are not considered 'alive' by most biologists. What key biological capability do they lack that prevents them from being classified as living organisms?",
        answer: "They cannot reproduce on their own — they must hijack a host cell's machinery to replicate",
        acceptableAnswers: ["they can't replicate independently", "they need a host cell to reproduce", "they can't reproduce on their own"],
      },
      {
        id: "vir_400_02",
        categoryId: "sci_virology",
        tier: 400,
        prompt: "The 1918 influenza pandemic is estimated to have killed 50-100 million people. What was it commonly (and misleadingly) called, and why was the name misleading?",
        answer: "The Spanish Flu — it was misleading because Spain wasn't the origin; Spain simply reported on it freely while WWI combatant nations censored their press",
        acceptableAnswers: ["Spanish Flu, Spain was just the first to report it", "Spanish Flu, it didn't originate in Spain"],
      },
      {
        id: "vir_400_03",
        categoryId: "sci_virology",
        tier: 400,
        prompt: "What does mRNA stand for, and how do mRNA vaccines (like the Pfizer COVID-19 vaccine) work?",
        answer: "Messenger RNA — the vaccine delivers mRNA instructions that teach cells to produce a harmless piece of the virus's spike protein, triggering an immune response",
        acceptableAnswers: ["messenger RNA, it instructs cells to make spike protein", "messenger RNA, teaches cells to make viral protein"],
      },
      {
        id: "vir_600_01",
        categoryId: "sci_virology",
        tier: 600,
        prompt: "Bacteriophages are viruses that infect bacteria, not humans. Why are they receiving renewed scientific interest as a potential medical tool?",
        answer: "Phage therapy — using bacteriophages to treat antibiotic-resistant bacterial infections as an alternative to failing antibiotics",
        acceptableAnswers: ["phage therapy", "to fight antibiotic-resistant bacteria", "as an alternative to antibiotics"],
        explanation: "With antibiotic resistance growing, phage therapy is being revisited. It was used in the Soviet Union for decades but was sidelined in the West in favor of antibiotics.",
      },
      {
        id: "vir_600_02",
        categoryId: "sci_virology",
        tier: 600,
        prompt: "Approximately what percentage of the human genome is composed of sequences derived from ancient retroviruses (endogenous retroviruses)?",
        answer: "About 8%",
        acceptableAnswers: ["8%", "around 8 percent", "5-8%"],
        explanation: "Over millions of years, retroviruses have integrated their DNA into our genome. Some of these viral sequences have been repurposed — syncytin, essential for placenta formation, comes from an ancient retrovirus.",
      },
      {
        id: "vir_600_03",
        categoryId: "sci_virology",
        tier: 600,
        prompt: "The Ebola virus is named after a river near the site of the first recognized outbreak in 1976. In which country was that outbreak, and why did the discoverer choose the river name instead of the village name?",
        answer: "The Democratic Republic of the Congo (then Zaire). Peter Piot chose the Ebola River name to avoid stigmatizing the village of Yambuku where the outbreak occurred.",
        acceptableAnswers: ["Zaire/DRC, to avoid stigmatizing the village", "Congo, to protect the village from stigma"],
        explanation: "Piot and colleagues deliberately picked a nearby river rather than naming it 'Yambuku virus' to protect the community — an early example of ethical disease naming.",
      },
    ],
  },
  {
    id: "sci_botany",
    group: "Science",
    name: "Botany",
    culture: "universal",
    description: "The science of plants — from photosynthesis and plant intelligence to the crops that shaped civilizations and the bizarre extremes of the plant kingdom.",
    imageUrl: "",
    questions: [
      {
        id: "bot_200_01",
        categoryId: "sci_botany",
        tier: 200,
        prompt: "What process do plants use to convert sunlight, water, and carbon dioxide into energy and oxygen?",
        answer: "Photosynthesis",
        acceptableAnswers: [],
      },
      {
        id: "bot_200_02",
        categoryId: "sci_botany",
        tier: 200,
        prompt: "What is the largest flower in the world, known for its massive size and terrible smell?",
        answer: "Rafflesia arnoldii",
        acceptableAnswers: ["Rafflesia", "corpse flower"],
      },
      {
        id: "bot_200_03",
        categoryId: "sci_botany",
        tier: 200,
        prompt: "What part of a plant absorbs water and nutrients from the soil?",
        answer: "The roots",
        acceptableAnswers: ["roots"],
      },
      {
        id: "bot_400_01",
        categoryId: "sci_botany",
        tier: 400,
        prompt: "The Venus flytrap is one of the few carnivorous plants that actively traps prey. How does the trap mechanism know to close — what prevents it from wasting energy on non-food triggers?",
        answer: "The trap requires two trigger hair contacts within about 20 seconds — a single touch won't trigger it, preventing false closures from raindrops or debris",
        acceptableAnswers: ["two touches within 20 seconds", "needs two trigger hair stimulations", "double-touch mechanism"],
      },
      {
        id: "bot_400_02",
        categoryId: "sci_botany",
        tier: 400,
        prompt: "What is mycorrhiza, and why is it considered one of the most important symbiotic relationships in nature?",
        answer: "A partnership between plant roots and fungi where the fungus extends the plant's nutrient absorption in exchange for sugars — connecting over 90% of plant species",
        acceptableAnswers: ["a symbiosis between plant roots and fungi", "fungal-root partnership", "fungi help plants absorb nutrients in exchange for sugar"],
      },
      {
        id: "bot_400_03",
        categoryId: "sci_botany",
        tier: 400,
        prompt: "The Irish Potato Famine (1845-1852) was caused by a plant disease. What organism caused the blight, and why was the Irish potato crop so vulnerable?",
        answer: "The oomycete Phytophthora infestans — the crop was vulnerable because nearly all Irish potatoes were a single variety (the Lumper), creating a genetic monoculture",
        acceptableAnswers: ["Phytophthora infestans, monoculture", "potato blight, lack of genetic diversity"],
      },
      {
        id: "bot_600_01",
        categoryId: "sci_botany",
        tier: 600,
        prompt: "Research has shown that plants can communicate through underground fungal networks, sharing nutrients and chemical warning signals. What has this network been nicknamed?",
        answer: "The Wood Wide Web",
        acceptableAnswers: ["wood wide web"],
        explanation: "Coined by Suzanne Simard, the term describes how mycorrhizal networks allow trees to share carbon, water, and defense chemicals — with 'mother trees' supporting saplings.",
      },
      {
        id: "bot_600_02",
        categoryId: "sci_botany",
        tier: 600,
        prompt: "What is the oldest known individual living organism on Earth, and approximately how old is it?",
        answer: "A Great Basin bristlecone pine named Methuselah, approximately 4,855 years old (though an older unnamed tree was found nearby)",
        acceptableAnswers: ["Methuselah", "a bristlecone pine", "bristlecone pine, about 4800-5000 years old"],
        explanation: "Methuselah lives in the White Mountains of California. Its exact location is kept secret to prevent vandalism.",
      },
      {
        id: "bot_600_03",
        categoryId: "sci_botany",
        tier: 600,
        prompt: "In 2023, scientists grew a plant from a seed that had been preserved for an extraordinary length of time. What was the plant, and how was the seed preserved?",
        answer: "A Judean date palm was grown from 2,000-year-old seeds found in ancient jars near the Dead Sea in Israel",
        acceptableAnswers: ["Judean date palm from 2000-year-old seeds", "a date palm from ancient seeds"],
        explanation: "The seeds, nicknamed Methuselah (male) and Hannah (female), were found during archaeological excavations and successfully germinated, reviving an extinct variety.",
      },
    ],
  },
  {
    id: "cul_coffee_history",
    group: "Culture",
    name: "Coffee History",
    culture: "universal",
    description: "The global story of coffee — from Ethiopian legend to the coffeehouses that fueled revolutions, and the modern specialty coffee movement.",
    imageUrl: "",
    questions: [
      {
        id: "cof_200_01",
        categoryId: "cul_coffee_history",
        tier: 200,
        prompt: "Which country is traditionally credited as the birthplace of coffee, where legend says a goat herder named Kaldi noticed his goats became energetic after eating certain berries?",
        answer: "Ethiopia",
        acceptableAnswers: [],
      },
      {
        id: "cof_200_02",
        categoryId: "cul_coffee_history",
        tier: 200,
        prompt: "An espresso is the foundation of many coffee drinks. What Italian word does 'espresso' translate to in English?",
        answer: "Pressed out (or express)",
        acceptableAnswers: ["pressed out", "express", "fast", "pressed"],
      },
      {
        id: "cof_200_03",
        categoryId: "cul_coffee_history",
        tier: 200,
        prompt: "What is the name of the most widely consumed coffee species, accounting for about 60-70% of world production?",
        answer: "Arabica (Coffea arabica)",
        acceptableAnswers: ["Arabica"],
      },
      {
        id: "cof_400_01",
        categoryId: "cul_coffee_history",
        tier: 400,
        prompt: "European coffeehouses in the 17th and 18th centuries were nicknamed 'penny universities.' Why?",
        answer: "For the price of a penny cup of coffee, anyone could sit and engage in intellectual discussion, hear news, and debate ideas",
        acceptableAnswers: ["cheap access to intellectual discussion", "you could learn and discuss for the price of a coffee"],
      },
      {
        id: "cof_400_02",
        categoryId: "cul_coffee_history",
        tier: 400,
        prompt: "What is the world's most expensive coffee, made from beans that have been eaten and excreted by a civet cat?",
        answer: "Kopi Luwak",
        acceptableAnswers: ["kopi luwak", "civet coffee"],
        explanation: "The civet's digestive enzymes supposedly alter the beans' flavor profile. However, the industry has been criticized for animal cruelty and caged civet farming.",
      },
      {
        id: "cof_400_03",
        categoryId: "cul_coffee_history",
        tier: 400,
        prompt: "The Ottoman Empire played a crucial role in spreading coffee culture. What was the Turkish word for coffeehouse, and what cultural role did these establishments serve?",
        answer: "Kahvehane — they served as centers of social life, news, music, chess, and political discussion",
        acceptableAnswers: ["kahvehane", "kavehane"],
        explanation: "Ottoman authorities periodically banned coffeehouses fearing they were breeding grounds for political dissent — a pattern that would repeat across Europe.",
      },
      {
        id: "cof_600_01",
        categoryId: "cul_coffee_history",
        tier: 600,
        prompt: "Brazil dominates global coffee production, but coffee is not native there. How did coffee arrive in Brazil, according to the popular historical account involving a Portuguese officer?",
        answer: "Lieutenant Colonel Francisco de Melo Palheta was sent to French Guiana to mediate a border dispute and smuggled coffee seeds back, allegedly hidden in a bouquet of flowers given to him by the French governor's wife",
        acceptableAnswers: ["smuggled from French Guiana", "Palheta smuggled seeds in flowers", "seeds hidden in a bouquet from French Guiana"],
        explanation: "The 1727 incident is part legend, part history, but coffee cultivation in Brazil grew from these smuggled seeds into the world's largest coffee industry.",
      },
      {
        id: "cof_600_02",
        categoryId: "cul_coffee_history",
        tier: 600,
        prompt: "The 'Third Wave' of coffee refers to a movement that treats coffee as an artisanal product. What were the 'First Wave' and 'Second Wave'?",
        answer: "First Wave was the mass commoditization of coffee (Folgers, Maxwell House). Second Wave was the rise of espresso-based drinks and coffeehouse culture (Starbucks, Peet's).",
        acceptableAnswers: ["first wave was mass market coffee, second wave was Starbucks-style", "commodity coffee then specialty chains"],
      },
      {
        id: "cof_600_03",
        categoryId: "cul_coffee_history",
        tier: 600,
        prompt: "Coffee leaf rust (Hemileia vastatrix) devastated the world's coffee industry in the 19th century, permanently changing a major empire's drinking habits. What happened?",
        answer: "Coffee rust destroyed Ceylon's (Sri Lanka's) coffee plantations in the 1870s, causing the British Empire to shift from coffee to tea — making tea Britain's national drink",
        acceptableAnswers: ["it destroyed Ceylon's coffee and Britain switched to tea", "Sri Lanka's coffee was destroyed, Britain became a tea-drinking nation"],
        explanation: "Ceylon was one of the world's top coffee producers until rust wiped out the crops. Planters replaced coffee with tea, and Britain's cultural identity as tea-drinkers was cemented.",
      },
    ],
  },
  {
    id: "myth_japanese",
    group: "Culture",
    name: "Japanese Mythology",
    culture: "universal",
    description: "The rich mythological tradition of Japan — from the creation myths of Shinto to the yōkai spirits that still permeate Japanese pop culture.",
    imageUrl: "",
    questions: [
      {
        id: "jpm_200_01",
        categoryId: "myth_japanese",
        tier: 200,
        prompt: "In Japanese mythology, what is the name of the sun goddess who is considered the principal deity of Shinto and the mythical ancestor of the Japanese imperial line?",
        answer: "Amaterasu",
        acceptableAnswers: ["Amaterasu Omikami"],
      },
      {
        id: "jpm_200_02",
        categoryId: "myth_japanese",
        tier: 200,
        prompt: "What are the supernatural creatures and spirits of Japanese folklore collectively called?",
        answer: "Yōkai",
        acceptableAnswers: ["yokai"],
      },
      {
        id: "jpm_200_03",
        categoryId: "myth_japanese",
        tier: 200,
        prompt: "What type of gate, usually painted red-orange, marks the entrance to Shinto shrines and is one of Japan's most recognizable symbols?",
        answer: "Torii",
        acceptableAnswers: ["torii gate"],
      },
      {
        id: "jpm_400_01",
        categoryId: "myth_japanese",
        tier: 400,
        prompt: "In the creation myth, which two deities were tasked with creating the Japanese islands, stirring the ocean with a jeweled spear?",
        answer: "Izanagi and Izanami",
        acceptableAnswers: ["Izanagi and Izanami no Mikoto"],
        explanation: "Izanagi and Izanami stood on the Floating Bridge of Heaven and stirred the primordial sea. Drops falling from the spear formed the first island, Onogoro.",
      },
      {
        id: "jpm_400_02",
        categoryId: "myth_japanese",
        tier: 400,
        prompt: "The kitsune is a fox spirit with magical powers in Japanese mythology. What ability do kitsune gain as they grow older and more powerful, visually represented by a change in appearance?",
        answer: "They grow additional tails — up to nine tails — with each tail representing greater age, wisdom, and power",
        acceptableAnswers: ["they grow more tails", "additional tails up to nine", "nine tails"],
        explanation: "A nine-tailed fox (kyūbi no kitsune) is the most powerful form. This concept heavily influenced anime — most famously Naruto's Nine-Tailed Fox.",
      },
      {
        id: "jpm_400_03",
        categoryId: "myth_japanese",
        tier: 400,
        prompt: "Susanoo, the storm god and brother of Amaterasu, was banished from heaven for his chaotic behavior. What heroic deed did he perform after his banishment?",
        answer: "He slew the eight-headed serpent Yamata no Orochi to save a maiden, and found the legendary sword Kusanagi inside the serpent's body",
        acceptableAnswers: ["killed Yamata no Orochi", "slew the eight-headed serpent", "defeated the eight-headed dragon"],
      },
      {
        id: "jpm_600_01",
        categoryId: "myth_japanese",
        tier: 600,
        prompt: "The tale of Amaterasu hiding in a cave plunged the world into darkness. What creative strategy did the other gods use to lure her out?",
        answer: "The goddess Ame-no-Uzume performed a provocative, comedic dance that made all the other gods laugh uproariously. Amaterasu's curiosity about the laughter drew her to peek out, and a mirror placed at the cave entrance captivated her.",
        acceptableAnswers: ["a dance and a mirror", "Ame-no-Uzume danced and a mirror was used", "a comedic dance and a mirror at the cave mouth"],
        explanation: "The mirror used — Yata no Kagami — became one of the three Imperial Regalia of Japan, along with the sword Kusanagi and the jewel Yasakani no Magatama.",
      },
      {
        id: "jpm_600_02",
        categoryId: "myth_japanese",
        tier: 600,
        prompt: "Izanagi traveled to Yomi (the land of the dead) to retrieve Izanami after she died giving birth to the fire god. What happened when he saw her there, and what was the consequence?",
        answer: "He lit a fire and saw her rotting, maggot-covered corpse. She was furious and chased him. He sealed the entrance to Yomi with a boulder, and she vowed to kill 1,000 people per day — he countered that 1,500 would be born.",
        acceptableAnswers: ["he saw her decaying body and fled, she vowed to kill 1000 daily", "he sealed Yomi and they argued about life and death"],
        explanation: "This myth explains both death and population growth. The sealed entrance to Yomi is traditionally identified with a boulder at Yomotsu Hirasaka in Shimane Prefecture.",
      },
      {
        id: "jpm_600_03",
        categoryId: "myth_japanese",
        tier: 600,
        prompt: "The Hyakki Yagyō (Night Parade of One Hundred Demons) is a famous concept in Japanese folklore. What was believed to happen if a human encountered the parade?",
        answer: "The person would die or be spirited away unless they were protected by specific Buddhist or onmyōdō prayers and charms",
        acceptableAnswers: ["they would die", "death or being spirited away", "death unless protected by prayers"],
        explanation: "The Night Parade inspired countless works, from Toriyama Sekien's 18th-century yōkai encyclopedias to Nura: Rise of the Yokai Clan. Onmyōji were said to predict which nights the parade would occur.",
      },
    ],
  },
  {
    id: "his_board_games",
    group: "Culture",
    name: "Board Game History",
    culture: "universal",
    description: "The surprisingly dramatic history of board games — from ancient civilizations playing Senet to the modern tabletop renaissance.",
    imageUrl: "",
    questions: [
      {
        id: "bgm_200_01",
        categoryId: "his_board_games",
        tier: 200,
        prompt: "What classic board game involves buying properties, building houses and hotels, and bankrupting your opponents?",
        answer: "Monopoly",
        acceptableAnswers: [],
      },
      {
        id: "bgm_200_02",
        categoryId: "his_board_games",
        tier: 200,
        prompt: "What strategic board game, originating in Germany in 1995, involves settling an island by trading resources like wood, brick, and sheep?",
        answer: "Catan (Settlers of Catan)",
        acceptableAnswers: ["Settlers of Catan", "Catan"],
      },
      {
        id: "bgm_200_03",
        categoryId: "his_board_games",
        tier: 200,
        prompt: "What is the oldest board game still played today, originating in China over 2,500 years ago and considered the most complex traditional strategy game?",
        answer: "Go",
        acceptableAnswers: ["Weiqi", "Baduk"],
      },
      {
        id: "bgm_400_01",
        categoryId: "his_board_games",
        tier: 400,
        prompt: "Monopoly's true origin is controversial. Who actually invented the game's core mechanics decades before Parker Brothers published it, and what was her original version called?",
        answer: "Elizabeth Magie created The Landlord's Game in 1903 to demonstrate the problems of land monopolism",
        acceptableAnswers: ["Elizabeth Magie", "Lizzie Magie", "The Landlord's Game"],
        explanation: "Magie's game was designed to teach the economic theories of Henry George. Charles Darrow later sold a derivative version to Parker Brothers and was credited as the inventor.",
      },
      {
        id: "bgm_400_02",
        categoryId: "his_board_games",
        tier: 400,
        prompt: "What board game, designed by Klaus Teuber, won the prestigious Spiel des Jahres award in 1995 and is widely credited with launching the modern board game renaissance in the West?",
        answer: "The Settlers of Catan",
        acceptableAnswers: ["Catan", "Settlers of Catan"],
        explanation: "Catan introduced millions of Western players to Euro-style game design — where strategy, trading, and resource management replaced dice-rolling elimination.",
      },
      {
        id: "bgm_400_03",
        categoryId: "his_board_games",
        tier: 400,
        prompt: "The Royal Game of Ur is one of the oldest known board games, discovered in ancient Mesopotamia. Approximately when was it played, and how do we know its rules?",
        answer: "Dating to about 2600 BC, its rules were decoded from a cuneiform tablet written by a Babylonian scribe around 177 BC",
        acceptableAnswers: ["about 2600 BC, rules from cuneiform tablets", "4600 years old, rules decoded from clay tablets"],
        explanation: "Irving Finkel of the British Museum deciphered the rules from a clay tablet, allowing the game to be played again after thousands of years.",
      },
      {
        id: "bgm_600_01",
        categoryId: "his_board_games",
        tier: 600,
        prompt: "During the Cold War, the British Secret Intelligence Service (MI6) reportedly used a modified version of which board game to help train agents and smuggle escape tools to POWs?",
        answer: "Monopoly — specially marked sets contained hidden maps, compasses, and real money smuggled to POWs through fake charity organizations (during WWII)",
        acceptableAnswers: ["Monopoly"],
        explanation: "Working with John Waddington Ltd, MI6 created Monopoly sets with silk maps, tiny compasses, and real currency hidden inside. They were sent to POW camps via fake charities.",
      },
      {
        id: "bgm_600_02",
        categoryId: "his_board_games",
        tier: 600,
        prompt: "Dungeons & Dragons, created by Gary Gygax and Dave Arneson in 1974, invented the tabletop RPG genre. What earlier miniature wargame by Gygax directly evolved into D&D?",
        answer: "Chainmail",
        acceptableAnswers: [],
        explanation: "Chainmail (1971) was a medieval miniatures wargame. Arneson adapted its combat rules for his Blackmoor campaign, adding individual character progression — the seed that became D&D.",
      },
      {
        id: "bgm_600_03",
        categoryId: "his_board_games",
        tier: 600,
        prompt: "The 'German-style' or 'Euro game' design philosophy differs fundamentally from traditional American board games. What are the key design principles that define Euro games?",
        answer: "Indirect competition over direct conflict, no player elimination, limited randomness, resource management and optimization as core mechanics, and the game ending at a set time with the highest score winning",
        acceptableAnswers: ["no player elimination, less luck, resource management", "indirect competition, no elimination, less randomness"],
        explanation: "The distinction emerged in the 1990s as German designers like Reiner Knizia and Klaus Teuber created games focused on strategic depth without the 'feel bad' moments of elimination-style games.",
      },
    ],
  },
  {
    id: "sci_deep_time",
    group: "Science",
    name: "Deep Time & Geology",
    culture: "universal",
    description: "Earth's 4.5 billion year history — mass extinctions, continental drift, ice ages, and the mind-bending timescales that shaped our planet.",
    imageUrl: "",
    questions: [
      {
        id: "dtm_200_01",
        categoryId: "sci_deep_time",
        tier: 200,
        prompt: "Approximately how old is planet Earth?",
        answer: "About 4.5 billion years",
        acceptableAnswers: ["4.5 billion years", "4.6 billion years"],
      },
      {
        id: "dtm_200_02",
        categoryId: "sci_deep_time",
        tier: 200,
        prompt: "What cataclysmic event approximately 66 million years ago caused the extinction of the non-avian dinosaurs?",
        answer: "An asteroid impact (the Chicxulub impactor)",
        acceptableAnswers: ["asteroid impact", "meteorite impact", "an asteroid"],
      },
      {
        id: "dtm_200_03",
        categoryId: "sci_deep_time",
        tier: 200,
        prompt: "What is the name of the supercontinent that existed approximately 335-175 million years ago before breaking apart into the continents we know today?",
        answer: "Pangaea",
        acceptableAnswers: ["Pangea"],
      },
      {
        id: "dtm_400_01",
        categoryId: "sci_deep_time",
        tier: 400,
        prompt: "There have been five major mass extinctions in Earth's history. Which was the largest, killing approximately 96% of all marine species?",
        answer: "The Permian-Triassic extinction event (the Great Dying), approximately 252 million years ago",
        acceptableAnswers: ["the Permian extinction", "the Great Dying", "Permian-Triassic"],
        explanation: "The Great Dying was likely caused by massive volcanic eruptions in Siberia (the Siberian Traps) that triggered catastrophic climate change.",
      },
      {
        id: "dtm_400_02",
        categoryId: "sci_deep_time",
        tier: 400,
        prompt: "The Cambrian Explosion, approximately 540 million years ago, was a pivotal event in life's history. What happened during this period?",
        answer: "Most major animal body plans appeared in the fossil record within a relatively short geological period of about 20-25 million years",
        acceptableAnswers: ["rapid appearance of most animal groups", "most animal phyla appeared rapidly", "explosion of complex animal life"],
      },
      {
        id: "dtm_400_03",
        categoryId: "sci_deep_time",
        tier: 400,
        prompt: "Alfred Wegener proposed continental drift in 1912 but was ridiculed. What key evidence eventually proved him right decades later?",
        answer: "The discovery of seafloor spreading and magnetic striping patterns on the ocean floor in the 1960s",
        acceptableAnswers: ["seafloor spreading", "magnetic striping on the ocean floor", "mid-ocean ridge evidence"],
        explanation: "Harry Hess and others showed that new crust forms at mid-ocean ridges and pushes continents apart. Symmetrical magnetic reversal patterns in ocean floor rock confirmed it.",
      },
      {
        id: "dtm_600_01",
        categoryId: "sci_deep_time",
        tier: 600,
        prompt: "The Great Oxygenation Event approximately 2.4 billion years ago was caused by cyanobacteria producing oxygen. Why was this event catastrophic for most life on Earth at the time?",
        answer: "Most existing life was anaerobic — oxygen was toxic to them, causing a mass extinction. The event also triggered a global glaciation (Snowball Earth) as oxygen reacted with atmospheric methane, removing a key greenhouse gas.",
        acceptableAnswers: ["oxygen was poison to existing life", "it killed anaerobic organisms and caused an ice age", "oxygen poisoned most life and caused Snowball Earth"],
      },
      {
        id: "dtm_600_02",
        categoryId: "sci_deep_time",
        tier: 600,
        prompt: "The Chicxulub crater from the dinosaur-killing asteroid is buried under sediment in which modern-day location? And who discovered it, and how?",
        answer: "The Yucatán Peninsula in Mexico. It was discovered by geophysicists Glen Penfield and Antonio Camargo in 1978 while analyzing gravity anomaly data for an oil company.",
        acceptableAnswers: ["Yucatan Peninsula, discovered through gravity anomalies", "Mexico's Yucatan, found by Penfield"],
        explanation: "Penfield noticed a massive semicircular gravity anomaly while doing petroleum surveys. It took over a decade for the scientific community to accept it as an impact crater.",
      },
      {
        id: "dtm_600_03",
        categoryId: "sci_deep_time",
        tier: 600,
        prompt: "Zircon crystals are used to date the oldest material on Earth. The oldest known zircons, found in Jack Hills, Western Australia, are approximately how old, and what do they tell us about early Earth?",
        answer: "About 4.4 billion years old — they contain evidence that liquid water existed on Earth's surface far earlier than previously thought, within 100-150 million years of Earth's formation",
        acceptableAnswers: ["4.4 billion years, evidence of early liquid water", "about 4.4 billion years old"],
        explanation: "Oxygen isotope ratios in these zircons suggest liquid water was present, meaning early Earth wasn't the hellscape scientists once assumed — it cooled faster than expected.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 61 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
