#!/usr/bin/env python3
"""Insert wave 75 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_chernobyl",
    group: "tv",
    name: "Chernobyl (HBO)",
    culture: "universal",
    description: "The cost of lies — the nuclear disaster miniseries that shook the world.",
    imageUrl: "",
    questions: [
      { id: "chb_200_01", categoryId: "tv_chernobyl", tier: 200, prompt: "In what year and country did the Chernobyl nuclear disaster occur?", answer: "1986, Soviet Union (modern-day Ukraine)", acceptableAnswers: ["1986", "1986 USSR", "1986 Soviet Union"], explanation: "The Chernobyl disaster was the worst nuclear accident in history." },
      { id: "chb_200_02", categoryId: "tv_chernobyl", tier: 200, prompt: "What type of nuclear event occurred at Chernobyl — an explosion, meltdown, or both?", answer: "A steam explosion followed by a reactor fire that released massive amounts of radiation — essentially both", acceptableAnswers: ["Explosion and meltdown", "Steam explosion and fire", "Both"], explanation: "The explosion blew the roof off Reactor 4, exposing the core." },
      { id: "chb_200_03", categoryId: "tv_chernobyl", tier: 200, prompt: "What is the opening line of the HBO series that frames the entire story?", answer: "What is the cost of lies?", acceptableAnswers: ["What is the cost of lies"], explanation: "Legasov's question sets up the show's theme: institutional dishonesty caused the disaster." },
      { id: "chb_400_01", categoryId: "tv_chernobyl", tier: 400, prompt: "What did the Soviet officials initially refuse to believe about the reactor, despite evidence from radiation readings?", answer: "That the reactor core had exploded — they insisted the readings were wrong because an RBMK reactor 'cannot explode' (their dosimeters only read up to 3.6 roentgen)", acceptableAnswers: ["Core exploded but they denied it", "RBMK cannot explode denial", "Refused to believe core explosion"], explanation: "The 3.6 roentgen reading became a meme — 'Not great, not terrible' — because the meters couldn't read higher." },
      { id: "chb_400_02", categoryId: "tv_chernobyl", tier: 400, prompt: "Who were the 'liquidators' and 'bio-robots' who cleaned the reactor roof, and why couldn't actual robots do the job?", answer: "Soviet soldiers and workers who manually shoveled radioactive graphite off the roof — radiation destroyed the electronic circuits of robots, so human 'bio-robots' were given 90 seconds each on the roof", acceptableAnswers: ["Soldiers shoveling radioactive debris by hand", "Human workers replacing failed robots", "Men given 90 seconds on radioactive roof"], explanation: "Each worker could only spend 90 seconds on the roof before receiving their lifetime dose of radiation." },
      { id: "chb_400_03", categoryId: "tv_chernobyl", tier: 400, prompt: "What is the 'Elephant's Foot' found in the Chernobyl basement?", answer: "A massive formation of cooled corium (melted nuclear fuel mixed with concrete and sand) that was so radioactive it could kill a person in minutes of exposure — it's still dangerous today", acceptableAnswers: ["Solidified nuclear fuel blob", "Corium mass of melted reactor fuel", "Deadly radioactive lava formation"], explanation: "When first discovered, standing near the Elephant's Foot for 30 seconds would be lethal." },
      { id: "chb_600_01", categoryId: "tv_chernobyl", tier: 600, prompt: "What specific design flaw of the RBMK reactor caused the explosion, and why was this information classified?", answer: "The graphite-tipped control rods — when inserted during an emergency, they initially INCREASED reactivity before decreasing it (the 'positive void coefficient'). This flaw was known but classified because admitting it would have indicted the entire Soviet nuclear program", acceptableAnswers: ["Graphite-tipped control rods increased reactivity", "Positive void coefficient in control rods", "Control rods boosted reaction before stopping it"], explanation: "The AZ-5 emergency button, meant to stop the reaction, actually triggered the explosion." },
      { id: "chb_600_02", categoryId: "tv_chernobyl", tier: 600, prompt: "What did the three divers (Ananenko, Bespalov, and Baranov) do to prevent a potentially larger steam explosion, and what happened to them?", answer: "They waded through radioactive water beneath the reactor to open valves and drain water before melting fuel reached it — preventing a potential steam explosion that could have devastated much of Europe. Contrary to popular myth, all three survived initially (two are still alive as of recent reports)", acceptableAnswers: ["Drained water under reactor to prevent steam explosion", "Swam through radioactive water to open valves", "Prevented larger explosion by draining water pool"], explanation: "The popular narrative that they all died immediately is incorrect — at least two survived for decades." },
      { id: "chb_600_03", categoryId: "tv_chernobyl", tier: 600, prompt: "What literary and narrative liberties did HBO's Chernobyl take, and why did creator Craig Mazin defend them?", answer: "The character Ulana Khomyuk is fictional (representing many real scientists); timelines were compressed; some events were dramatized or reordered. Mazin argued these changes served the truth of what happened — institutional lies killed people — even when specific details were simplified for dramatic clarity", acceptableAnswers: ["Fictional composite characters and compressed timeline", "Khomyuk is fictional, events reordered for drama", "Composite characters serving larger truth"], explanation: "Mazin maintained that dramatic truth and factual truth can coexist when the core message is honest." },
    ],
  },
  {
    id: "tv_ted_lasso",
    group: "tv",
    name: "Ted Lasso",
    culture: "american",
    description: "An American football coach in English soccer — kindness as a superpower.",
    imageUrl: "",
    questions: [
      { id: "tdl_200_01", categoryId: "tv_ted_lasso", tier: 200, prompt: "What sport does Ted Lasso coach despite having no experience with it?", answer: "Soccer (football/association football)", acceptableAnswers: ["Soccer", "Football", "English football"], explanation: "Ted is an American college football coach hired to manage an English Premier League team." },
      { id: "tdl_200_02", categoryId: "tv_ted_lasso", tier: 200, prompt: "What is the name of the English football club Ted is hired to coach?", answer: "AFC Richmond", acceptableAnswers: ["Richmond", "AFC Richmond"], explanation: "The fictional club plays in the English Premier League." },
      { id: "tdl_200_03", categoryId: "tv_ted_lasso", tier: 200, prompt: "What is Ted Lasso's defining character trait that surprises everyone around him?", answer: "Relentless optimism and genuine kindness — he believes in people even when they don't believe in themselves", acceptableAnswers: ["Optimism", "Kindness", "Relentless positivity", "Believing in people"], explanation: "Ted's kindness isn't naivety — it's a deliberate choice that transforms everyone around him." },
      { id: "tdl_400_01", categoryId: "tv_ted_lasso", tier: 400, prompt: "Why does Rebecca Welton hire Ted in the first place, and how does her plan backfire?", answer: "She hires an incompetent American coach specifically to sabotage the team and hurt her ex-husband who gave her the club in the divorce — but Ted's genuine goodness wins her over and she genuinely starts caring about the team", acceptableAnswers: ["To sabotage the team to spite her ex-husband", "Revenge against ex-husband, plan backfires", "Hired to fail but his kindness changes her"], explanation: "Rebecca's arc from villain to Ted's biggest ally is the show's first great transformation." },
      { id: "tdl_400_02", categoryId: "tv_ted_lasso", tier: 400, prompt: "What is the 'BELIEVE' sign, and what does it represent in the show?", answer: "A hand-written sign Ted puts above the locker room door — it becomes the symbol of his philosophy that belief in yourself and your team matters more than tactics or talent", acceptableAnswers: ["Sign above locker room door", "Handwritten sign representing Ted's philosophy", "Locker room belief sign"], explanation: "The BELIEVE sign becomes the show's central symbol — when it's torn, the team is broken." },
      { id: "tdl_400_03", categoryId: "tv_ted_lasso", tier: 400, prompt: "What mental health issue does Ted deal with in Season 2 that deepens his character beyond simple positivity?", answer: "Panic attacks and anxiety — he begins seeing a therapist, revealing that his relentless optimism partly masks deep personal pain from his father's suicide", acceptableAnswers: ["Panic attacks and anxiety", "Anxiety from father's suicide", "Mental health struggles behind optimism"], explanation: "The show earned praise for depicting a male character seeking therapy without stigma." },
      { id: "tdl_600_01", categoryId: "tv_ted_lasso", tier: 600, prompt: "What is the 'dart scene' in Season 1, and how does it demonstrate Ted's philosophy through the concept of curiosity vs. judgment?", answer: "Rupert challenges Ted to darts expecting to humiliate him. Ted delivers a monologue about people underestimating him his whole life, quoting Walt Whitman: 'Be curious, not judgmental.' He then reveals he's actually excellent at darts and wins — the scene argues that people who judge others miss what's right in front of them", acceptableAnswers: ["Darts game with be curious not judgmental speech", "Beat Rupert at darts with curiosity vs judgment theme", "Whitman quote while winning at darts"], explanation: "The dart scene is the show's thesis statement — be curious about people instead of dismissing them." },
      { id: "tdl_600_02", categoryId: "tv_ted_lasso", tier: 600, prompt: "How did the character of Ted Lasso originate before becoming a TV show?", answer: "Ted Lasso began as a character in NBC Sports promotional videos in 2013, where Jason Sudeikis played an American football coach hired by Tottenham Hotspur. The ads were so popular that Bill Lawrence and Sudeikis developed them into the Apple TV+ series years later", acceptableAnswers: ["NBC Sports promotional ads from 2013", "Tottenham Hotspur promo videos", "NBC Sports ads with Sudeikis"], explanation: "The character evolved from a 5-minute comedy ad into one of the most beloved shows of the 2020s." },
      { id: "tdl_600_03", categoryId: "tv_ted_lasso", tier: 600, prompt: "What makes Jamie Tartt's character arc across all three seasons considered one of TV's best redemption arcs?", answer: "Jamie starts as an arrogant, selfish star player who alienates teammates. Over three seasons he confronts his abusive father, learns vulnerability from Ted, and transforms into a selfless team player — his growth is earned through specific moments of failure and humility rather than a sudden change", acceptableAnswers: ["From arrogant star to selfless teammate via earned growth", "Overcame abusive father, learned vulnerability", "Gradual redemption through failure and humility"], explanation: "Jamie's arc works because the show takes three seasons to earn his transformation." },
    ],
  },
  {
    id: "mu_stevie_wonder",
    group: "music",
    name: "Stevie Wonder",
    culture: "american",
    description: "The genius of Motown — blind since birth, visionary forever.",
    imageUrl: "",
    questions: [
      { id: "stw_200_01", categoryId: "mu_stevie_wonder", tier: 200, prompt: "At what remarkably young age did Stevie Wonder sign with Motown Records?", answer: "11 years old", acceptableAnswers: ["11", "Age 11"], explanation: "Stevie was billed as 'Little Stevie Wonder' and had his first #1 hit at age 13." },
      { id: "stw_200_02", categoryId: "mu_stevie_wonder", tier: 200, prompt: "What physical condition has Stevie Wonder had since birth?", answer: "He is blind", acceptableAnswers: ["Blind", "Blindness", "He's blind since birth"], explanation: "Wonder's blindness from birth never limited his musical genius — he plays multiple instruments by ear." },
      { id: "stw_200_03", categoryId: "mu_stevie_wonder", tier: 200, prompt: "What Stevie Wonder song, featuring a chromatic harmonica intro, celebrates the joy of a new baby and contains the lyric 'I just called to say I love you'?", answer: "Those are two different songs — 'Isn't She Lovely' (baby celebration with harmonica) and 'I Just Called to Say I Love You' (love ballad)", acceptableAnswers: ["Isn't She Lovely and I Just Called to Say I Love You", "Two different songs"], explanation: "Both are among Stevie's most well-known songs." },
      { id: "stw_400_01", categoryId: "mu_stevie_wonder", tier: 400, prompt: "What unprecedented deal did Stevie Wonder negotiate with Motown when he turned 21 that changed the music industry?", answer: "He demanded and received full creative control over his music — choosing his own songs, production, and arrangements. This was virtually unheard of at Motown, where Berry Gordy controlled everything", acceptableAnswers: ["Full creative control at Motown", "Complete artistic control over his music", "Creative independence from Motown"], explanation: "Wonder's creative freedom produced his 'classic period' — five masterpiece albums in five years." },
      { id: "stw_400_02", categoryId: "mu_stevie_wonder", tier: 400, prompt: "What is the 'classic period' of five consecutive albums that many consider the greatest run in popular music history?", answer: "Music of My Mind, Talking Book, Innervisions, Fulfillingness' First Finale, and Songs in the Key of Life (1972-1976)", acceptableAnswers: ["1972-1976 albums", "Music of My Mind through Songs in the Key of Life", "Five albums from 72 to 76"], explanation: "Five albums in five years, each a masterpiece — a run unmatched in popular music." },
      { id: "stw_400_03", categoryId: "mu_stevie_wonder", tier: 400, prompt: "What political cause did Stevie Wonder champion that resulted in a federal holiday being established?", answer: "He led the campaign to make Martin Luther King Jr.'s birthday a national holiday, including writing the song 'Happy Birthday' for the cause — the holiday was signed into law in 1983", acceptableAnswers: ["MLK Day holiday campaign", "Martin Luther King Jr. holiday", "Campaigned for MLK birthday holiday"], explanation: "Wonder's activism was instrumental in creating the federal holiday." },
      { id: "stw_600_01", categoryId: "mu_stevie_wonder", tier: 600, prompt: "What synthesizer technology did Stevie Wonder pioneer in the early 1970s, and how did it change popular music?", answer: "Wonder was among the first pop artists to extensively use the Moog and ARP synthesizers, the clavinet (heard in 'Superstition'), and later the Yamaha CS-80 — he essentially created the template for how synthesizers would be used in R&B, funk, and pop for the next 50 years", acceptableAnswers: ["Pioneered Moog/ARP synths in pop", "Early synth adopter who defined synth-pop sound", "Moog and clavinet pioneer in R&B"], explanation: "Wonder didn't just use synthesizers — he defined how they'd sound in Black music." },
      { id: "stw_600_02", categoryId: "mu_stevie_wonder", tier: 600, prompt: "What is remarkable about how 'Songs in the Key of Life' was recorded, and why did it take two years to complete?", answer: "Wonder played most instruments himself, recorded at multiple studios simultaneously, and amassed so much material that it became a double album plus a bonus EP — over 100 songs were recorded, with the label eventually sending a bumper sticker saying 'We're almost finished' to radio stations tired of waiting", acceptableAnswers: ["Played most instruments, recorded 100+ songs", "Double album plus EP from massive sessions", "Two years of solo multi-instrumental recording"], explanation: "The perfectionism produced what many consider the greatest album ever made." },
      { id: "stw_600_03", categoryId: "mu_stevie_wonder", tier: 600, prompt: "How did a near-fatal car accident in 1973 affect Stevie Wonder's music and outlook?", answer: "He was in a coma for four days after a logging truck accident; the experience deepened his spiritual perspective and directly influenced 'Fulfillingness' First Finale' and 'Songs in the Key of Life.' His friend kept singing 'Higher Ground' into his ear — his first response from the coma was tapping the rhythm", acceptableAnswers: ["Coma from car crash, deepened spiritual music", "Near-death influenced later albums", "Responded to Higher Ground while in coma"], explanation: "The accident transformed Wonder's already profound music into something even more spiritually searching." },
    ],
  },
  {
    id: "vg_sekiro",
    group: "video_games",
    name: "Sekiro: Shadows Die Twice",
    culture: "universal",
    description: "The one-armed wolf — FromSoftware's shinobi precision combat masterpiece.",
    imageUrl: "",
    questions: [
      { id: "sek_200_01", categoryId: "vg_sekiro", tier: 200, prompt: "What setting and time period is Sekiro set in?", answer: "Sengoku-era Japan (late 1500s feudal Japan)", acceptableAnswers: ["Feudal Japan", "Sengoku Japan", "1500s Japan"], explanation: "Sekiro draws from Japanese mythology and the warring states period." },
      { id: "sek_200_02", categoryId: "vg_sekiro", tier: 200, prompt: "What prosthetic tool replaces the protagonist's lost arm and gives the game its name?", answer: "A shinobi prosthetic arm — 'Shadows Die Twice' refers to the resurrection mechanic", acceptableAnswers: ["Prosthetic arm", "Shinobi prosthetic", "Mechanical arm"], explanation: "The prosthetic can be fitted with various tools like shuriken, firecrackers, and an axe." },
      { id: "sek_200_03", categoryId: "vg_sekiro", tier: 200, prompt: "What studio developed Sekiro, known for the Dark Souls and Bloodborne series?", answer: "FromSoftware", acceptableAnswers: ["FromSoftware", "From Software"], explanation: "FromSoftware and director Hidetaka Miyazaki created a new combat system for Sekiro." },
      { id: "sek_400_01", categoryId: "vg_sekiro", tier: 400, prompt: "What is the 'posture' system in Sekiro, and how does it change combat compared to Dark Souls?", answer: "Instead of depleting health bars, combat focuses on breaking an enemy's posture through perfect deflects and aggression — a filled posture bar allows a 'Deathblow' instant kill. This rewards offense over dodge-rolling", acceptableAnswers: ["Break posture through deflects for instant kills", "Posture bar system replacing health-focused combat", "Deflection-based combat for deathblows"], explanation: "The posture system makes Sekiro's combat feel like a rhythmic sword duel rather than dodge-and-hit." },
      { id: "sek_400_02", categoryId: "vg_sekiro", tier: 400, prompt: "What is the 'Divine Child' and 'Dragon's Heritage' in Sekiro's lore?", answer: "The Dragon's Heritage grants immortality through resurrection — the Divine Child Kuro carries this blood, and Wolf (Sekiro) is bound to protect him. The story explores whether immortality is a gift or a curse", acceptableAnswers: ["Kuro's immortality blood that Wolf protects", "Dragon blood granting resurrection", "Immortality heritage Wolf must protect"], explanation: "The central narrative asks whether defying death corrupts those it touches." },
      { id: "sek_400_03", categoryId: "vg_sekiro", tier: 400, prompt: "Why can't players level up traditional stats or summon help in Sekiro, unlike other FromSoftware games?", answer: "Sekiro has no RPG stat leveling, no armor choices, and no multiplayer — it forces every player to learn the combat system personally. You can't outlevel or outsummon a boss; you must master deflection", acceptableAnswers: ["No leveling, no summons, must learn combat", "Can't outlevel bosses, pure skill", "No RPG stats or multiplayer assistance"], explanation: "This design choice makes Sekiro the most purely skill-based FromSoftware game." },
      { id: "sek_600_01", categoryId: "vg_sekiro", tier: 600, prompt: "What is the Isshin Ashina/Isshin the Sword Saint fight, and why do players consider it FromSoftware's finest boss design?", answer: "The final boss has multiple phases spanning different weapon styles (sword, spear, gun, lightning) — each phase teaches a new combat lesson that tests everything you've learned. Sword Saint Isshin is considered the ultimate test because he requires mastery of every mechanic in the game", acceptableAnswers: ["Multi-phase boss testing all game mechanics", "Final boss with sword spear gun lightning phases", "Ultimate skill test using everything learned"], explanation: "Beating Sword Saint Isshin is often cited as the most satisfying accomplishment in gaming." },
      { id: "sek_600_02", categoryId: "vg_sekiro", tier: 600, prompt: "What does the 'Shura' ending represent, and how does it invert the entire game's moral framework?", answer: "If Wolf obeys his father Owl and betrays Kuro, he becomes a Shura — a demon of war consumed by bloodlust. The game becomes about slaughtering former allies. It's the 'bad' ending that asks whether obedience to a corrupt authority is worse than rebellion", acceptableAnswers: ["Betraying Kuro turns you into a war demon", "Obedience to Owl leads to becoming Shura", "Bad ending of choosing loyalty over morality"], explanation: "The Shura ending is deliberately unsatisfying — you 'win' but lose everything that mattered." },
      { id: "sek_600_03", categoryId: "vg_sekiro", tier: 600, prompt: "How does Sekiro's 'Dragonrot' mechanic create a moral consequence for dying repeatedly?", answer: "Each resurrection spreads Dragonrot to NPCs, making them sick and locking out their questlines. The game literally punishes you for dying too much by harming the characters you've befriended — creating guilt about using the resurrection safety net", acceptableAnswers: ["Dying spreads disease to NPCs", "Resurrection sickness locks NPC quests", "Deaths harm NPCs through spreading illness"], explanation: "Dragonrot makes death feel consequential beyond losing progress — your failures hurt others." },
    ],
  },
  {
    id: "mv_david_lynch",
    group: "movies",
    name: "David Lynch",
    culture: "american",
    description: "The owls are not what they seem — surrealism, nightmares, and cherry pie.",
    imageUrl: "",
    questions: [
      { id: "lyn_200_01", categoryId: "mv_david_lynch", tier: 200, prompt: "What groundbreaking TV series created by David Lynch features FBI Agent Dale Cooper investigating a murder in a small Pacific Northwest town?", answer: "Twin Peaks", explanation: "Twin Peaks (1990) asked 'Who killed Laura Palmer?' and changed television forever." },
      { id: "lyn_200_02", categoryId: "mv_david_lynch", tier: 200, prompt: "What surreal 2001 David Lynch film, originally a TV pilot, follows a woman with amnesia and an aspiring actress through a nightmarish Los Angeles?", answer: "Mulholland Drive", acceptableAnswers: ["Mulholland Dr.", "Mulholland Drive"], explanation: "Mulholland Drive is frequently voted the best film of the 21st century in critics' polls." },
      { id: "lyn_200_03", categoryId: "mv_david_lynch", tier: 200, prompt: "What term describes David Lynch's unique filmmaking style that blends the mundane with the horrifying?", answer: "Lynchian (or surrealism)", acceptableAnswers: ["Lynchian", "Surrealism", "Lynchian surrealism"], explanation: "'Lynchian' has entered the cultural lexicon to describe anything uncannily strange beneath a normal surface." },
      { id: "lyn_400_01", categoryId: "mv_david_lynch", tier: 400, prompt: "In Twin Peaks, what is the Black Lodge, and what happens to those who enter it?", answer: "A supernatural realm accessible through a portal in the woods — it exists outside of time, contains doppelgängers, and traps souls. The floors are zigzag chevron, inhabitants speak backwards, and it operates on dream logic", acceptableAnswers: ["Supernatural realm with backwards-speaking doppelgangers", "Otherworldly dimension trapping souls", "Dream-logic spirit realm with chevron floors"], explanation: "The Black Lodge sequences are some of the most disturbing and iconic in television history." },
      { id: "lyn_400_02", categoryId: "mv_david_lynch", tier: 400, prompt: "What 1977 debut film by Lynch, shot over five years, features a man caring for a mutant baby in an industrial hellscape?", answer: "Eraserhead", explanation: "Lynch financed the film partly by delivering newspapers while shooting on weekends." },
      { id: "lyn_400_03", categoryId: "mv_david_lynch", tier: 400, prompt: "What is Agent Cooper's favorite food and drink combination that became iconic to Twin Peaks fans?", answer: "Cherry pie and 'damn fine coffee'", acceptableAnswers: ["Coffee and cherry pie", "Damn fine coffee and cherry pie", "Coffee and pie"], explanation: "Cooper's enthusiastic love of coffee and pie became as iconic as any plot element." },
      { id: "lyn_600_01", categoryId: "mv_david_lynch", tier: 600, prompt: "What is the 'Diane' theory about Mulholland Drive — the widely accepted interpretation of the film's structure?", answer: "The first two-thirds are a dream by Diane Selwyn (Naomi Watts), reimagining her life as she wanted it — she's actually a failed actress who hired a hitman to kill her successful ex-lover. The dream collapses in the final act when reality (guilt, failure, murder) intrudes. The blue box is the mechanism of waking up", acceptableAnswers: ["First part is dream, last part is reality of failed actress", "Diane dreams a better life, reality is she's a murderer", "Dream/reality split with blue box as threshold"], explanation: "Lynch never confirmed this reading, but the clues make it the most coherent interpretation." },
      { id: "lyn_600_02", categoryId: "mv_david_lynch", tier: 600, prompt: "What was 'Twin Peaks: The Return' (2017), and why is Part 8 — the atomic bomb episode — considered one of the most avant-garde things ever shown on television?", answer: "An 18-episode continuation on Showtime. Part 8 depicts the 1945 Trinity nuclear test as literally birthing evil into the world, using experimental imagery (Penderecki music, black-and-white, nine minutes inside the nuclear explosion) to show BOB's origin — it's essentially an art film within a TV series", acceptableAnswers: ["18-episode revival with avant-garde atomic bomb origin episode", "Nuclear test creates evil in experimental art episode", "Part 8 shows BOB born from atomic blast"], explanation: "Part 8 is unlike anything else in television history — Lynch used network TV to make pure experimental cinema." },
      { id: "lyn_600_03", categoryId: "mv_david_lynch", tier: 600, prompt: "What is the significance of Lynch's refusal to explain his films, and how did he respond when asked what his movies 'mean'?", answer: "Lynch consistently refuses to explain, saying 'the film is the thing' — he believes explanations destroy the viewer's personal experience. He's compared his films to abstract paintings: asking what they 'mean' misunderstands the medium. The intuitive feeling IS the meaning", acceptableAnswers: ["Refuses to explain, film is the experience", "Meaning is the feeling, not an explanation", "Won't explain because interpretation is personal"], explanation: "Lynch's refusal to interpret his own work empowers audiences to find their own meaning — which is the point." },
    ],
  },
  {
    id: "his_renaissance",
    group: "history",
    name: "The Renaissance",
    culture: "universal",
    description: "The rebirth — art, science, and humanism transforming Europe.",
    imageUrl: "",
    questions: [
      { id: "ren_200_01", categoryId: "his_renaissance", tier: 200, prompt: "What does 'Renaissance' literally mean, and what was being 'reborn'?", answer: "Rebirth — it refers to the revival of interest in classical Greek and Roman art, philosophy, and learning after the Middle Ages", acceptableAnswers: ["Rebirth", "Rebirth of classical learning", "Revival of Greek and Roman culture"], explanation: "The Renaissance began in Italy in the 14th century and spread across Europe." },
      { id: "ren_200_02", categoryId: "his_renaissance", tier: 200, prompt: "Who painted the Mona Lisa and is often called the ultimate 'Renaissance man'?", answer: "Leonardo da Vinci", acceptableAnswers: ["Da Vinci", "Leonardo"], explanation: "Da Vinci was a painter, sculptor, architect, musician, mathematician, engineer, and anatomist." },
      { id: "ren_200_03", categoryId: "his_renaissance", tier: 200, prompt: "What Italian city is considered the birthplace of the Renaissance?", answer: "Florence", acceptableAnswers: ["Florence", "Firenze"], explanation: "Florence's wealthy Medici family patronized many of the Renaissance's greatest artists." },
      { id: "ren_400_01", categoryId: "his_renaissance", tier: 400, prompt: "What did Michelangelo paint on the ceiling of the Sistine Chapel, and how long did it take?", answer: "Biblical scenes including the Creation of Adam — it took approximately four years (1508-1512), mostly painted lying on his back on scaffolding", acceptableAnswers: ["Biblical scenes, about 4 years", "Creation of Adam etc, 4 years", "Sistine Chapel ceiling, 1508-1512"], explanation: "Michelangelo actually stood and painted above his head — the 'lying down' story is a myth, but the conditions were grueling." },
      { id: "ren_400_02", categoryId: "his_renaissance", tier: 400, prompt: "What invention by Johannes Gutenberg around 1440 revolutionized the spread of knowledge during the Renaissance?", answer: "The movable type printing press", acceptableAnswers: ["Printing press", "Movable type", "Gutenberg printing press"], explanation: "The printing press made books affordable, spreading ideas and literacy across Europe." },
      { id: "ren_400_03", categoryId: "his_renaissance", tier: 400, prompt: "Who was Niccolò Machiavelli, and what did his book 'The Prince' argue about political power?", answer: "A Florentine diplomat who wrote that effective rulers must be willing to act immorally when necessary — 'the ends justify the means.' His name became synonymous with cunning political manipulation", acceptableAnswers: ["Political philosopher who said ends justify means", "Argued rulers must use any means necessary", "Author advocating pragmatic ruthless leadership"], explanation: "The Prince was revolutionary because it described how power actually works rather than how it should work." },
      { id: "ren_600_01", categoryId: "his_renaissance", tier: 600, prompt: "What was the role of the Medici family in the Renaissance, and how did banking and art patronage connect?", answer: "The Medici were Florence's wealthiest banking family who used art patronage to legitimize their power — commissioning works from Botticelli, Michelangelo, and others. Their spending transformed Florence into Europe's cultural capital, but it was also political strategy: art demonstrated wealth, taste, and divine favor", acceptableAnswers: ["Banker-patrons using art for political power", "Florence banking family funding art as power display", "Art patronage as political legitimacy strategy"], explanation: "Without Medici money, many of the Renaissance's greatest works would never have been created." },
      { id: "ren_600_02", categoryId: "his_renaissance", tier: 600, prompt: "What was Leonardo da Vinci's relationship with his notebooks, and what did they reveal when finally studied centuries later?", answer: "Da Vinci kept over 7,000 pages of notebooks written in mirror script (right to left) covering anatomy, engineering, optics, and more. They revealed he had designed helicopters, tanks, solar power, and the double helix — centuries before these were 'invented.' Most were hidden for 200+ years after his death", acceptableAnswers: ["7000 pages of mirror-script inventions centuries ahead", "Notebooks with futuristic designs hidden for centuries", "Mirror-written notebooks predicting future inventions"], explanation: "Da Vinci's notebooks prove he understood principles of flight, hydraulics, and anatomy far ahead of his time." },
      { id: "ren_600_03", categoryId: "his_renaissance", tier: 600, prompt: "How did the Black Death (1347-1351) paradoxically help cause the Renaissance?", answer: "The plague killed 30-60% of Europe's population, creating labor shortages that gave survivors more economic power. Wealth concentrated among fewer people, the Church's authority weakened (it couldn't explain or stop the plague), and the trauma prompted a cultural shift toward humanism — valuing earthly life rather than just preparing for the afterlife", acceptableAnswers: ["Plague gave survivors more wealth and weakened Church authority", "Labor shortage plus weakened Church enabled humanism", "Death created wealth concentration and secular thinking"], explanation: "The Renaissance was partially born from catastrophe — the plague shattered medieval assumptions." },
    ],
  },
  {
    id: "sci_genetics",
    group: "science",
    name: "Genetics & DNA",
    culture: "universal",
    description: "The code of life — from Mendel's peas to CRISPR gene editing.",
    imageUrl: "",
    questions: [
      { id: "gen_200_01", categoryId: "sci_genetics", tier: 200, prompt: "What molecule carries the genetic instructions for all living organisms?", answer: "DNA (deoxyribonucleic acid)", acceptableAnswers: ["DNA", "Deoxyribonucleic acid"], explanation: "DNA's double helix structure stores the blueprint for building and maintaining organisms." },
      { id: "gen_200_02", categoryId: "sci_genetics", tier: 200, prompt: "What shape is a DNA molecule — the structure discovered by Watson and Crick?", answer: "A double helix (twisted ladder)", acceptableAnswers: ["Double helix", "Twisted ladder", "Spiral"], explanation: "Watson and Crick's 1953 discovery of the double helix was one of science's greatest breakthroughs." },
      { id: "gen_200_03", categoryId: "sci_genetics", tier: 200, prompt: "What are genes, and approximately how many does a human have?", answer: "Segments of DNA that code for proteins/traits — humans have approximately 20,000-25,000 genes", acceptableAnswers: ["DNA segments for traits, about 20000-25000", "About 20000 genes", "20-25 thousand"], explanation: "Surprisingly, humans have roughly the same number of genes as a mouse." },
      { id: "gen_400_01", categoryId: "sci_genetics", tier: 400, prompt: "What is CRISPR-Cas9, and why is it considered revolutionary for genetics?", answer: "A gene-editing tool that can precisely cut and modify DNA at specific locations — it's faster, cheaper, and more accurate than any previous method, enabling targeted treatment of genetic diseases", acceptableAnswers: ["Precise gene editing tool", "DNA cutting and editing technology", "Targeted gene modification tool"], explanation: "CRISPR has been compared to 'molecular scissors' that let scientists edit the code of life." },
      { id: "gen_400_02", categoryId: "sci_genetics", tier: 400, prompt: "What did the Human Genome Project accomplish, and when was it completed?", answer: "It mapped the entire human genome (all 3 billion base pairs of human DNA) — completed in 2003 after 13 years of international collaboration", acceptableAnswers: ["Mapped all human DNA, completed 2003", "Sequenced 3 billion base pairs by 2003", "Complete human genome map in 2003"], explanation: "The project cost $2.7 billion; today the same sequencing costs under $1,000." },
      { id: "gen_400_03", categoryId: "sci_genetics", tier: 400, prompt: "What is epigenetics, and how does it challenge the idea that 'DNA is destiny'?", answer: "Epigenetics studies how behaviors and environment can change the way genes are expressed without altering the DNA sequence — genes can be turned on or off by experiences, diet, stress, and even trauma, and some of these changes can be inherited", acceptableAnswers: ["Gene expression changes without DNA changes", "Environment affecting gene activation", "Genes turned on/off by experience"], explanation: "Epigenetics shows that nature AND nurture work together through gene expression." },
      { id: "gen_600_01", categoryId: "sci_genetics", tier: 600, prompt: "What was Rosalind Franklin's contribution to discovering DNA's structure, and why is her story considered one of science's greatest injustices?", answer: "Franklin's X-ray crystallography image ('Photo 51') provided the crucial evidence for DNA's helical structure — Watson and Crick used her data (shown to them by her colleague Wilkins without her knowledge) but she received no credit. She died of cancer at 37, and the Nobel Prize went to Watson, Crick, and Wilkins", acceptableAnswers: ["Photo 51 used without credit, no Nobel", "X-ray image proving helix used without permission", "Franklin's data taken, Nobel went to Watson/Crick"], explanation: "Franklin's exclusion from recognition is one of the most cited examples of women's contributions being erased from science." },
      { id: "gen_600_02", categoryId: "sci_genetics", tier: 600, prompt: "What is the 'junk DNA' controversy, and how did the ENCODE project challenge the idea that 98% of DNA is useless?", answer: "Only ~2% of DNA codes for proteins, so the rest was called 'junk.' The ENCODE project (2012) claimed ~80% of DNA has some biochemical function. This remains controversial — critics argue ENCODE's definition of 'function' was too broad, and much of the genome may indeed be non-functional evolutionary leftovers", acceptableAnswers: ["98% was called junk, ENCODE said 80% has function, still debated", "Non-coding DNA debate between junk and function", "ENCODE claimed most DNA functional, still controversial"], explanation: "The debate reveals how much we still don't understand about our own genome." },
      { id: "gen_600_03", categoryId: "sci_genetics", tier: 600, prompt: "What was the 'He Jiankui affair' in 2018, and why did it shock the scientific world?", answer: "Chinese scientist He Jiankui used CRISPR to edit the embryos of twin girls (Lulu and Nana) to resist HIV — creating the world's first gene-edited humans. He was universally condemned because: the procedure was medically unnecessary, consent was questionable, the editing was imprecise with potential off-target effects, and he acted secretly without peer review. He was imprisoned for three years", acceptableAnswers: ["Created first gene-edited babies, was imprisoned", "CRISPR babies condemned as unethical", "Edited embryos for HIV resistance, imprisoned"], explanation: "The incident forced a global reckoning about the ethics of human germline editing." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 75 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
