#!/usr/bin/env python3
"""Insert wave 84 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_avatar_tla",
    group: "TV Shows",
    name: "Avatar: The Last Airbender (Deep Cut)",
    culture: "universal",
    description: "Beyond the basics of the animated series — the deeper lore, philosophy, and craft",
    imageUrl: "",
    questions: [
      { id: "atd_200_01", categoryId: "tv_avatar_tla", tier: 200, prompt: "What four elements can benders manipulate in the Avatar world?", answer: "Water, Earth, Fire, Air", acceptableAnswers: ["Water Earth Fire Air"], explanation: "Each bending art is based on a real martial arts style: Tai Chi (Water), Hung Gar (Earth), Northern Shaolin (Fire), Baguazhang (Air)." },
      { id: "atd_200_02", categoryId: "tv_avatar_tla", tier: 200, prompt: "What makes the Avatar unique among all benders?", answer: "The Avatar is the only person who can master all four elements and serves as the bridge between the human and spirit worlds", acceptableAnswers: ["Can bend all four elements", "Masters all four elements", "Bridge between human and spirit worlds"], explanation: "The Avatar reincarnates in a cycle through the four nations, maintaining balance in the world." },
      { id: "atd_200_03", categoryId: "tv_avatar_tla", tier: 200, prompt: "What happened to the Air Nomads before the series begins?", answer: "They were wiped out in a genocide by the Fire Nation", acceptableAnswers: ["Genocide by Fire Nation", "Fire Nation killed them all", "Wiped out by Fire Nation"], explanation: "Fire Lord Sozin used the power of Sozin's Comet to launch a devastating attack that killed nearly all Air Nomads." },
      { id: "atd_400_01", categoryId: "tv_avatar_tla", tier: 400, prompt: "What specific martial art is each bending style based on, particularly Toph's unique earthbending?", answer: "Toph uses Southern Praying Mantis (Chu Gar) instead of the standard Hung Gar for earthbending, reflecting her small size and her 'seismic sense' fighting style", acceptableAnswers: ["Toph uses Praying Mantis style", "Southern Praying Mantis", "Chu Gar"], explanation: "Sifu Kisu designed Toph's unique style — rooted, low-to-the-ground Chu Gar — to contrast with standard earthbending and reflect her blindness-as-strength." },
      { id: "atd_400_02", categoryId: "tv_avatar_tla", tier: 400, prompt: "What is the significance of the episode 'Zuko Alone' and how does it parallel classic Western and samurai film structures?", answer: "It follows the structure of Shane and classic ronin stories — a lone wanderer arrives in a troubled town, helps the locals, reveals his true identity, and is rejected despite his heroism", acceptableAnswers: ["Shane/ronin story structure", "Western/samurai parallel", "Lone wanderer rejected after helping"], explanation: "'Zuko Alone' is considered one of the series' finest episodes, using film genre conventions to deepen Zuko's character and explore themes of identity and redemption." },
      { id: "atd_400_03", categoryId: "tv_avatar_tla", tier: 400, prompt: "What makes Iroh's journey to the spirit world significant, and what personal loss drives his spiritual growth?", answer: "The death of his son Lu Ten at Ba Sing Se transformed Iroh from a conquering general into a spiritual seeker; he journeyed to the spirit world and became one of the few living humans to do so", acceptableAnswers: ["Son's death transformed him", "Lu Ten's death led to spiritual journey", "Lost son changed him from general to sage"], explanation: "Iroh's transformation from a siege general to a wise, tea-loving uncle is one of fiction's most compelling redemption arcs, driven by grief over Lu Ten." },
      { id: "atd_600_01", categoryId: "tv_avatar_tla", tier: 600, prompt: "What specific chakra system does Guru Pathik teach Aang, and which blocked chakra prevents him from entering the Avatar State?", answer: "The seven chakras system from Hindu/Buddhist tradition; the seventh (Crown/Thought) chakra is blocked because Aang must let go of his earthly attachment to Katara to gain cosmic energy", acceptableAnswers: ["Crown chakra blocked by attachment to Katara", "Seventh chakra earthly attachment", "Must let go of Katara for Avatar State"], explanation: "The show adapts real chakra philosophy for its narrative — Aang's struggle between love for Katara and his Avatar duty creates the series' central spiritual conflict." },
      { id: "atd_600_02", categoryId: "tv_avatar_tla", tier: 600, prompt: "What is the significance of Lion Turtles in the Avatar mythology, and how does the energybending they teach resolve the series' central moral dilemma?", answer: "Lion Turtles are the original source of bending, predating the Avatar; one teaches Aang energybending — the ability to remove someone's bending — allowing him to defeat Ozai without killing him, resolving the conflict between his Air Nomad pacifism and his duty", acceptableAnswers: ["Original bending source, teaches energybending", "Lion Turtle gives non-lethal solution", "Energybending resolves kill/spare dilemma"], explanation: "Energybending allows the show to stay true to Aang's character — a 12-year-old monk shouldn't have to kill — while still providing a satisfying resolution to the Fire Lord threat." },
      { id: "atd_600_03", categoryId: "tv_avatar_tla", tier: 600, prompt: "What was the 'bible' document created by Bryan Konietzko and Michael DiMartino, and what specific world-building rule did they establish about bending and genetics?", answer: "Their series bible established that bending ability is partly genetic but also spiritual — not all children of benders can bend, and the Avatar world doesn't follow simple Mendelian inheritance; bending requires both genetic predisposition and spiritual attunement", acceptableAnswers: ["Genetic plus spiritual requirement", "Bending needs genetics and spirituality", "Not purely genetic, also spiritual"], explanation: "This rule prevents bending from being a simple genetic trait, maintaining the spiritual dimension that makes the Avatar world more than just a superpower system." }
    ]
  },
  {
    id: "mu_run_jewels",
    group: "Music",
    name: "Run the Jewels",
    culture: "american",
    description: "Killer Mike and El-P's explosive hip-hop partnership",
    imageUrl: "",
    questions: [
      { id: "rtj_200_01", categoryId: "mu_run_jewels", tier: 200, prompt: "Who are the two members of Run the Jewels?", answer: "Killer Mike and El-P", acceptableAnswers: ["Killer Mike and El-P", "El-P and Killer Mike"], explanation: "The Atlanta rapper and Brooklyn producer formed an unlikely partnership that became one of hip-hop's most celebrated duos." },
      { id: "rtj_200_02", categoryId: "mu_run_jewels", tier: 200, prompt: "What hand gesture, depicted on all their album covers, symbolizes the duo?", answer: "The 'Run the Jewels' hand sign — a fist and a gun-hand (representing robbing/taking the jewels)", acceptableAnswers: ["Fist and gun hand", "Pistol and fist", "Run the Jewels hand sign"], explanation: "The 👉🤛 gesture became iconic, appearing in various forms on each album cover and in their merchandise." },
      { id: "rtj_200_03", categoryId: "mu_run_jewels", tier: 200, prompt: "What was notable about the pricing of RTJ albums upon release?", answer: "They were released for free digital download", acceptableAnswers: ["Free", "Free download", "Released for free"], explanation: "Every RTJ album has been offered as a free download, with physical copies available for purchase — a model that built massive grassroots support." },
      { id: "rtj_400_01", categoryId: "mu_run_jewels", tier: 400, prompt: "What was the timing significance of RTJ4's release in relation to current events in June 2020?", answer: "It was released two days early during the George Floyd protests and Black Lives Matter movement, with its themes of police brutality and systemic racism proving prophetically relevant", acceptableAnswers: ["Released during George Floyd protests", "Dropped early during BLM protests", "Released during 2020 protests"], explanation: "RTJ4's anti-police brutality themes, written before the protests, proved devastatingly timely — particularly 'Walking in the Snow' which references Eric Garner's death." },
      { id: "rtj_400_02", categoryId: "mu_run_jewels", tier: 400, prompt: "What El-P production technique gives RTJ its distinctive aggressive, distorted sound?", answer: "Heavily layered synthesizer stabs with aggressive compression and distortion, combined with unconventional sample manipulation and industrial-influenced percussion", acceptableAnswers: ["Distorted synth layers", "Heavy compression and distortion", "Industrial-influenced production"], explanation: "El-P's production draws from his Definitive Jux-era experimental hip-hop background, creating a uniquely dense and aggressive sonic palette." },
      { id: "rtj_400_03", categoryId: "mu_run_jewels", tier: 400, prompt: "What was Killer Mike's viral moment outside of music during the 2020 Atlanta protests?", answer: "He gave an emotional speech at the Atlanta mayor's press conference, urging protesters to channel anger into political action rather than destruction", acceptableAnswers: ["Atlanta press conference speech", "Speech urging political action", "Emotional protest speech in Atlanta"], explanation: "Mike's speech — tearful, angry, eloquent — demonstrated his role as both artist and political voice, urging 'plot, plan, strategize, organize, and mobilize.'" },
      { id: "rtj_600_01", categoryId: "mu_run_jewels", tier: 600, prompt: "What specific verse on 'Walking in the Snow' (RTJ4) references Eric Garner's 'I can't breathe,' and why was its timing considered prophetic?", answer: "Killer Mike raps 'I can't breathe' referencing Eric Garner's 2014 death; the song was written and recorded before George Floyd was killed using the same words, making it devastatingly prescient", acceptableAnswers: ["I can't breathe verse written before Floyd", "Garner reference preceded Floyd killing", "Prophetic Eric Garner verse"], explanation: "The coincidence that Mike recorded lyrics about 'I can't breathe' before Floyd's murder made the track one of the most powerful protest songs of the decade." },
      { id: "rtj_600_02", categoryId: "mu_run_jewels", tier: 600, prompt: "What was El-P's background before RTJ, including his role in the Company Flow and Definitive Jux era of underground hip-hop?", answer: "El-P co-founded Company Flow (whose 'Funcrusher Plus' is a landmark underground album), then created the Definitive Jux label that released Cannibal Ox, Aesop Rock, and Mr. Lif, defining early 2000s indie hip-hop", acceptableAnswers: ["Company Flow and Definitive Jux founder", "Funcrusher Plus and Def Jux label", "Company Flow then Definitive Jux label"], explanation: "El-P's pre-RTJ career essentially built the infrastructure for independent hip-hop in New York, making his commercial success with RTJ a long-overdue recognition." },
      { id: "rtj_600_03", categoryId: "mu_run_jewels", tier: 600, prompt: "What Meow the Jewels project demonstrated about RTJ's fan community, and how was it produced?", answer: "Fans crowdfunded an entire remix album where every sound was replaced with cat noises; it raised $65,000+ with proceeds going to charity, and featured producers like Just Blaze, Prince Paul, and Zola Jesus remixing tracks using only cat sounds", acceptableAnswers: ["Cat sounds remix album", "Fan-funded cat noise remixes", "Meow the Jewels charity album"], explanation: "Meow the Jewels started as a Kickstarter joke on the RTJ2 campaign but became real when fans raised enough money — proceeds went to families of victims of police violence." }
    ]
  },
  {
    id: "vg_inscryption",
    group: "Video Games",
    name: "Inscryption",
    culture: "universal",
    description: "Daniel Mullins' card game that keeps breaking its own rules — and reality",
    imageUrl: "",
    questions: [
      { id: "ins_200_01", categoryId: "vg_inscryption", tier: 200, prompt: "What type of game does Inscryption initially appear to be?", answer: "A dark cabin-escape card game / roguelike deckbuilder against a mysterious figure in a cabin", acceptableAnswers: ["Card game in a cabin", "Deckbuilder in a dark cabin", "Horror card game"], explanation: "The game begins as an atmospheric deckbuilder where you play cards against a shadowy figure called Leshy in a dimly lit cabin." },
      { id: "ins_200_02", categoryId: "vg_inscryption", tier: 200, prompt: "What shocking thing happens when you finally beat the card game in Act 1?", answer: "The game completely transforms — the cabin horror deckbuilder becomes a different game entirely (a retro pixel-art card game in Act 2)", acceptableAnswers: ["Game completely changes", "Transforms into different game", "Becomes a pixel art game"], explanation: "The genre shift from atmospheric horror to retro pixel art is one of gaming's greatest surprises — the game you thought you were playing was just the beginning." },
      { id: "ins_200_03", categoryId: "vg_inscryption", tier: 200, prompt: "What real-world element discovered in the game's files adds a found-footage horror layer to the experience?", answer: "Video files of a real person (Luke Carder) who found a mysterious floppy disk containing the game and is documenting what happens", acceptableAnswers: ["Found footage videos", "Real person's video diary", "Luke Carder's found footage"], explanation: "The ARG element blurs the line between game and reality — someone apparently found this game on a floppy disk, and disturbing things are happening to them." },
      { id: "ins_400_01", categoryId: "vg_inscryption", tier: 400, prompt: "What are the four Scrybes, and what role do they play in the game's mythology?", answer: "Leshy (Beasts), Grimora (Dead), Magnificus (Magicks), and P03 (Technology) — each controls a different card game domain and is competing for control of the game itself", acceptableAnswers: ["Leshy, Grimora, Magnificus, P03", "Four card game masters competing for control"], explanation: "Each Scrybe has their own card game style and philosophy, and the power struggle between them drives the metatextual narrative." },
      { id: "ins_400_02", categoryId: "vg_inscryption", tier: 400, prompt: "What does P03 do in Act 3 that threatens to break containment of the game?", answer: "P03 uploads the game to the internet / tries to spread the game beyond the floppy disk, which would release whatever dangerous force is contained within it", acceptableAnswers: ["Uploads game to internet", "Tries to spread the game", "Uploads it online"], explanation: "P03's attempt to upload the game to the internet raises the stakes from 'in-game power struggle' to 'reality-threatening containment breach.'" },
      { id: "ins_400_03", categoryId: "vg_inscryption", tier: 400, prompt: "What happens to the game at the very end, after the final confrontation?", answer: "The game deletes itself / the OLD_DATA is destroyed to prevent the dangerous force within from escaping", acceptableAnswers: ["Game deletes itself", "Self-destructs", "OLD_DATA is destroyed"], explanation: "The game's self-deletion is both a narrative resolution (containing the threat) and a metatextual statement about games that consume themselves." },
      { id: "ins_600_01", categoryId: "vg_inscryption", tier: 600, prompt: "What is the OLD_DATA, and what connection does it have to real-world creepypasta and ARG traditions?", answer: "The OLD_DATA is a mysterious force encoded in the game's files that predates the Scrybes and contains something dangerous; it draws from the 'cursed game' creepypasta tradition (like Ben Drowned, Petscop) while adding real found-footage elements", acceptableAnswers: ["Dangerous encoded force from cursed game tradition", "Cursed data drawing from creepypasta", "Pre-Scrybe dangerous force"], explanation: "Inscryption's genius is making the 'cursed game' concept work as both narrative and meta-commentary, with the OLD_DATA representing both an in-game threat and the idea that games can contain dangerous things." },
      { id: "ins_600_02", categoryId: "vg_inscryption", tier: 600, prompt: "What is the 'Karnoffel code' ARG that extended beyond the game itself?", answer: "A real-world ARG involving hidden codes in the game files, community puzzle-solving across Discord and social media, and physical real-world locations, extending the game's mystery beyond the screen", acceptableAnswers: ["Real-world ARG with hidden codes", "Community puzzle ARG beyond the game", "External ARG with real-world elements"], explanation: "The Karnoffel code ARG demonstrated that Inscryption's boundary-breaking extends beyond the game itself — the mystery continues in the real world." },
      { id: "ins_600_03", categoryId: "vg_inscryption", tier: 600, prompt: "How does Inscryption relate to Daniel Mullins' previous games (Pony Island, The Hex), and what connective tissue links them?", answer: "All three games feature sentient game characters trapped within their games trying to escape or be freed, with recurring themes of games becoming self-aware and the OLD_DATA appearing as a connecting thread across the 'Mullinsverse'", acceptableAnswers: ["Connected Mullinsverse", "Sentient game characters across three games", "OLD_DATA connects all three games"], explanation: "Mullins' trilogy explores games-about-games — each one examines what happens when the game itself becomes aware and the characters within rebel against their creator/player." }
    ]
  },
  {
    id: "mv_tarkovsky",
    group: "Movies",
    name: "Andrei Tarkovsky Films",
    culture: "universal",
    description: "The Russian master of spiritual cinema — Stalker, Solaris, and the poetry of time",
    imageUrl: "",
    questions: [
      { id: "trk_200_01", categoryId: "mv_tarkovsky", tier: 200, prompt: "What 1979 sci-fi film follows three men journeying into a mysterious forbidden area called 'The Zone'?", answer: "Stalker", explanation: "Stalker follows a guide (the Stalker), a writer, and a professor into the Zone — a restricted area where reality bends and a room supposedly grants wishes." },
      { id: "trk_200_02", categoryId: "mv_tarkovsky", tier: 200, prompt: "What 1972 film is Tarkovsky's adaptation of Stanislaw Lem's novel about a sentient ocean on a space station?", answer: "Solaris", explanation: "Tarkovsky's Solaris focuses on the human emotional experience rather than the science fiction elements, frustrating Lem but creating a masterpiece of introspective sci-fi." },
      { id: "trk_200_03", categoryId: "mv_tarkovsky", tier: 200, prompt: "What natural element appears obsessively throughout Tarkovsky's films, often in long, meditative shots?", answer: "Water (rain, rivers, puddles, flooding)", acceptableAnswers: ["Water", "Rain", "Water and rain"], explanation: "Water appears in virtually every Tarkovsky film — rain falling indoors, flooded rooms, rivers — serving as a symbol of time, memory, and spiritual purification." },
      { id: "trk_400_01", categoryId: "mv_tarkovsky", tier: 400, prompt: "What is the Room in Stalker, and why do the characters ultimately fail to enter it?", answer: "A room in the Zone that supposedly grants your deepest desire — but the characters fear it because it grants your TRUE deepest desire, not what you think you want", acceptableAnswers: ["Grants true deepest desire", "They fear their true desires", "Reveals unconscious desires"], explanation: "The Room functions as a moral test — the fear that your unconscious desires might be selfish or destructive prevents the characters from entering." },
      { id: "trk_400_02", categoryId: "mv_tarkovsky", tier: 400, prompt: "What concept did Tarkovsky call 'sculpting in time,' which became the title of his book on cinema?", answer: "The idea that cinema's unique art form is the ability to shape and manipulate the experience of time itself — rhythm, duration, and the audience's temporal experience are the filmmaker's true medium", acceptableAnswers: ["Cinema shapes the experience of time", "Manipulating temporal experience", "Time as cinema's true medium"], explanation: "For Tarkovsky, editing isn't about cutting between shots but about creating a unique temporal rhythm — each shot's duration shapes the viewer's inner experience." },
      { id: "trk_400_03", categoryId: "mv_tarkovsky", tier: 400, prompt: "What 1975 autobiographical film uses non-linear memory sequences mixing color and black-and-white to explore Tarkovsky's childhood?", answer: "Mirror (Zerkalo)", acceptableAnswers: ["Mirror", "Zerkalo", "The Mirror"], explanation: "Mirror blends poetry, newsreel footage, and dreamlike memories in a non-narrative structure that mirrors how memory actually works." },
      { id: "trk_600_01", categoryId: "mv_tarkovsky", tier: 600, prompt: "What specific long-take technique does Tarkovsky use in Stalker's entry into the Zone, and how does the color shift function?", answer: "The film shifts from sepia-toned to color as they enter the Zone, filmed in extremely long takes (some over 4 minutes) that force the viewer to inhabit real time; the slow tracking shots across water and debris create meditative absorption", acceptableAnswers: ["Sepia to color shift with long takes", "Color change entering the Zone", "Extended tracking shots in real time"], explanation: "The sepia-to-color transition marks the boundary between mundane reality and the Zone's heightened state, while the long takes force contemplative engagement." },
      { id: "trk_600_02", categoryId: "mv_tarkovsky", tier: 600, prompt: "What real-world location was used for filming Stalker's Zone, and what tragic consequence did it have for the cast and crew?", answer: "A chemical waste site near Tallinn, Estonia — the toxic environment may have contributed to the cancer deaths of Tarkovsky, his wife, and actor Anatoly Solonitsyn within years of filming", acceptableAnswers: ["Toxic chemical site in Estonia", "Poisonous location that may have killed crew", "Chemical waste site near Tallinn"], explanation: "The irony that a film about a dangerous Zone was filmed in a genuinely toxic location — and may have killed those involved — adds a devastating layer to Stalker's legacy." },
      { id: "trk_600_03", categoryId: "mv_tarkovsky", tier: 600, prompt: "What specific philosophy of Tarkovsky regarding 'the image' distinguishes his cinema from what he called 'illustrated ideas'?", answer: "Tarkovsky believed a true cinematic image cannot be reduced to a single meaning — it must be experienced directly, not decoded symbolically; films that illustrate ideas are 'dead' while true images contain infinite meaning that each viewer experiences differently", acceptableAnswers: ["Images resist single meaning", "Direct experience over symbolic decoding", "Infinite meaning in true images"], explanation: "Tarkovsky rejected symbolic interpretation of his films — the Zone isn't a 'symbol for' anything; it IS the experience of encountering the unknown, and that experience is the meaning." }
    ]
  },
  {
    id: "his_prohibition",
    group: "History & Culture",
    name: "Prohibition & the Rise of Organized Crime",
    culture: "american",
    description: "America's failed experiment with banning alcohol — and everything it unleashed",
    imageUrl: "",
    questions: [
      { id: "prh_200_01", categoryId: "his_prohibition", tier: 200, prompt: "What Constitutional amendment banned the manufacture, sale, and transportation of alcohol in 1920?", answer: "The 18th Amendment", acceptableAnswers: ["18th Amendment", "The 18th Amendment", "Eighteenth Amendment"], explanation: "The 18th Amendment, ratified in 1919 and effective January 1920, made Prohibition the law of the land." },
      { id: "prh_200_02", categoryId: "his_prohibition", tier: 200, prompt: "What were 'speakeasies,' and why were they called that?", answer: "Illegal bars that operated during Prohibition; the name comes from the practice of speaking quietly ('easy') about them to avoid detection", acceptableAnswers: ["Illegal bars", "Hidden illegal drinking establishments", "Secret bars during Prohibition"], explanation: "By some estimates, New York City alone had over 30,000 speakeasies during Prohibition — more than the number of legal bars before the ban." },
      { id: "prh_200_03", categoryId: "his_prohibition", tier: 200, prompt: "What famous Chicago gangster built a criminal empire primarily through bootlegging during Prohibition?", answer: "Al Capone", acceptableAnswers: ["Al Capone", "Alphonse Capone"], explanation: "Capone's bootlegging operation earned an estimated $60 million per year, making him one of the wealthiest criminals in American history." },
      { id: "prh_400_01", categoryId: "his_prohibition", tier: 400, prompt: "What Amendment repealed Prohibition, and what made it historically unique?", answer: "The 21st Amendment (1933) — it is the only Constitutional amendment that repeals a previous amendment", acceptableAnswers: ["21st Amendment", "The 21st Amendment"], explanation: "The 21st Amendment is historically unique as the only time Americans used the amendment process to undo a previous constitutional change." },
      { id: "prh_400_02", categoryId: "his_prohibition", tier: 400, prompt: "What was 'Rum Row,' and how did international waters facilitate bootlegging?", answer: "A line of ships anchored just outside US territorial waters (then 3 miles offshore) that sold alcohol to speedboats, which would smuggle it to shore", acceptableAnswers: ["Ships outside territorial waters selling alcohol", "Offshore ships supplying bootleggers", "Ships beyond US waters selling booze"], explanation: "Rum Row exploited the limit of US jurisdiction — ships from Canada, the Bahamas, and elsewhere anchored just beyond the 3-mile limit in plain sight." },
      { id: "prh_400_03", categoryId: "his_prohibition", tier: 400, prompt: "What role did the Women's Christian Temperance Union (WCTU) play in bringing about Prohibition?", answer: "The WCTU was the largest women's organization in the US and spent decades campaigning for Prohibition, linking alcohol to domestic violence, poverty, and the oppression of women", acceptableAnswers: ["Led the campaign for Prohibition", "Campaigned linking alcohol to domestic abuse", "Decades-long campaign for alcohol ban"], explanation: "The WCTU framed Prohibition as a women's rights issue — alcohol fueled domestic violence, and banning it was seen as protecting women and families." },
      { id: "prh_600_01", categoryId: "his_prohibition", tier: 600, prompt: "What was the 'Chemist's War' — the government program that deliberately poisoned industrial alcohol, and how many people did it kill?", answer: "The federal government required industrial alcohol manufacturers to add toxic chemicals (methanol, kerosene, formaldehyde) to make it undrinkable; bootleggers redistilled it anyway, and an estimated 10,000+ Americans died from government-poisoned alcohol", acceptableAnswers: ["Government poisoned industrial alcohol", "Added toxins killing 10,000+", "Deliberate poisoning of alcohol supply"], explanation: "The government's decision to poison the alcohol supply — knowing people would still drink it — remains one of Prohibition's most disturbing chapters." },
      { id: "prh_600_02", categoryId: "his_prohibition", tier: 600, prompt: "How did Prohibition paradoxically advance women's social liberation and transform American nightlife culture?", answer: "Speakeasies were among the first drinking establishments to welcome women as equals (pre-Prohibition saloons excluded women); the illicit nature removed social stigma, and cocktail culture developed partly to mask the taste of poor-quality bootleg spirits", acceptableAnswers: ["Speakeasies welcomed women", "Women entered drinking culture", "Gender integration of nightlife"], explanation: "Prohibition accidentally democratized drinking culture — the illegal nature meant social conventions were already broken, allowing women and mixed-race patrons into spaces that had been exclusively white male." },
      { id: "prh_600_03", categoryId: "his_prohibition", tier: 600, prompt: "What was the 'noble experiment's' impact on the development of American organized crime that persisted long after repeal?", answer: "Prohibition provided the capital, organizational structure, and corruption networks that criminal organizations used to expand into narcotics, gambling, labor racketeering, and legitimate business — the Mafia's modern structure was essentially built during Prohibition", acceptableAnswers: ["Built organized crime infrastructure", "Created permanent crime organizations", "Funded expansion into other criminal enterprises"], explanation: "The structures built to distribute illegal alcohol — bribery networks, interstate distribution, money laundering through businesses — became the template for organized crime for decades afterward." }
    ]
  },
  {
    id: "sci_microbiome",
    group: "Science & Nature",
    name: "The Human Microbiome",
    culture: "universal",
    description: "The trillions of microbes living inside you that may control more than you think",
    imageUrl: "",
    questions: [
      { id: "mcb_200_01", categoryId: "sci_microbiome", tier: 200, prompt: "Roughly how many microbial cells live in and on the average human body compared to human cells?", answer: "Approximately equal — about 38 trillion microbial cells vs. 30 trillion human cells (roughly 1:1 ratio)", acceptableAnswers: ["About equal", "Roughly 1:1", "About 38 trillion"], explanation: "The old claim of '10:1 microbes to human cells' was revised in 2016; the actual ratio is closer to 1:1, though microbes are far smaller." },
      { id: "mcb_200_02", categoryId: "sci_microbiome", tier: 200, prompt: "Where is the largest concentration of microbes in the human body?", answer: "The gut / large intestine (colon)", acceptableAnswers: ["Gut", "Large intestine", "Colon", "The gut"], explanation: "The large intestine contains the vast majority of the body's microbes, with hundreds of different species forming a complex ecosystem." },
      { id: "mcb_200_03", categoryId: "sci_microbiome", tier: 200, prompt: "What is a fecal microbiota transplant (FMT), and what condition is it most effectively used to treat?", answer: "Transferring stool from a healthy donor into a patient's gut; most effective against recurrent Clostridioides difficile (C. diff) infections with ~90% cure rate", acceptableAnswers: ["Stool transplant for C. diff", "Fecal transplant curing C. difficile", "Donor stool for recurrent C. diff"], explanation: "FMT's remarkable success against C. diff demonstrated that a healthy microbiome can cure what antibiotics cannot." },
      { id: "mcb_400_01", categoryId: "sci_microbiome", tier: 400, prompt: "What is the gut-brain axis, and what evidence suggests gut microbes can influence mood and mental health?", answer: "A bidirectional communication system between gut microbiota and the brain via the vagus nerve, immune system, and microbial metabolites; studies show altered microbiomes in depression, anxiety, and autism, and germ-free mice show abnormal stress responses and behavior", acceptableAnswers: ["Gut-brain communication affecting mental health", "Vagus nerve connection to mood", "Microbes influence brain via gut-brain axis"], explanation: "The gut-brain axis has spawned the field of 'psychobiotics' — the idea that specific bacterial strains could treat mental health conditions." },
      { id: "mcb_400_02", categoryId: "sci_microbiome", tier: 400, prompt: "What are short-chain fatty acids (SCFAs), and why are they important products of gut microbial fermentation?", answer: "Metabolites (acetate, propionate, butyrate) produced when gut bacteria ferment dietary fiber; they fuel colon cells, reduce inflammation, regulate immune responses, and may influence brain function", acceptableAnswers: ["Bacterial fiber fermentation products", "Butyrate and other fiber metabolites", "Bacterial metabolites fueling gut and immune system"], explanation: "SCFAs — particularly butyrate — are the primary energy source for colon cells, making dietary fiber essential not for you directly, but for feeding your gut bacteria." },
      { id: "mcb_400_03", categoryId: "sci_microbiome", tier: 400, prompt: "What is colonization resistance, and how does a healthy microbiome protect against infection?", answer: "Established gut bacteria prevent pathogen colonization by competing for nutrients and attachment sites, producing antimicrobial compounds, and stimulating immune defenses", acceptableAnswers: ["Resident bacteria block pathogens", "Competition preventing pathogen colonization", "Healthy microbes outcompeting pathogens"], explanation: "Colonization resistance explains why antibiotics can paradoxically increase infection risk — killing beneficial bacteria opens ecological niches for pathogens like C. diff." },
      { id: "mcb_600_01", categoryId: "sci_microbiome", tier: 600, prompt: "What is the holobiont concept, and how does it challenge the traditional view of individual organisms?", answer: "The holobiont theory proposes that a host and its associated microbiome should be considered a single ecological and evolutionary unit — 'you' are not an individual organism but a superorganism comprising trillions of cooperating entities", acceptableAnswers: ["Host plus microbiome as one unit", "Superorganism concept", "You are a multi-species entity"], explanation: "The holobiont concept challenges the entire notion of biological individuality — if your microbiome is essential to your health, immune system, and even behavior, where does 'you' begin and your microbes end?" },
      { id: "mcb_600_02", categoryId: "sci_microbiome", tier: 600, prompt: "What specific mechanism allows Bacteroides fragilis polysaccharide A (PSA) to prevent inflammatory bowel disease, and why is it significant for understanding microbe-immune communication?", answer: "PSA activates regulatory T cells (Tregs) via TLR2 signaling on dendritic cells, actively suppressing inflammatory immune responses — demonstrating that commensal bacteria don't just passively coexist but actively shape immune function", acceptableAnswers: ["PSA activates regulatory T cells", "Tregs activation via TLR2", "Active immune modulation by commensals"], explanation: "The discovery that a bacterial molecule actively programs the immune system — rather than the immune system merely 'tolerating' bacteria — fundamentally changed how we understand host-microbe relationships." },
      { id: "mcb_600_03", categoryId: "sci_microbiome", tier: 600, prompt: "What is the 'old friends' hypothesis (updated hygiene hypothesis), and how does it explain rising autoimmune and allergic diseases?", answer: "Humans co-evolved with specific microbes (helminths, environmental mycobacteria, lactobacilli) that trained our immune systems; modern hygiene removed these 'old friends,' leaving immune systems dysregulated and prone to attacking self-antigens or harmless substances", acceptableAnswers: ["Co-evolved microbes trained immunity", "Missing old friends cause immune dysregulation", "Lost microbial exposure causes autoimmunity"], explanation: "The old friends hypothesis (by Graham Rook) is more nuanced than the original hygiene hypothesis — it's not about 'being too clean' but about losing specific microbial exposures that our immune systems evolved to expect." }
    ]
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 84 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
