#!/usr/bin/env python3
"""Insert wave 65 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_sopranos_deep",
    group: "TV Shows",
    name: "The Sopranos Deep Cuts",
    culture: "american",
    description: "The show that started the Golden Age of Television — deep knowledge of Tony Soprano's therapy, the real-world mob parallels, and the controversies behind the scenes.",
    imageUrl: "",
    questions: [
      {
        id: "spd_200_01",
        categoryId: "tv_sopranos_deep",
        tier: 200,
        prompt: "Who plays Tony Soprano, the New Jersey mob boss who sees a therapist?",
        answer: "James Gandolfini",
        acceptableAnswers: ["Gandolfini"],
      },
      {
        id: "spd_200_02",
        categoryId: "tv_sopranos_deep",
        tier: 200,
        prompt: "What is the name of Tony's psychiatrist whom he sees throughout the series?",
        answer: "Dr. Jennifer Melfi",
        acceptableAnswers: ["Dr. Melfi", "Jennifer Melfi"],
      },
      {
        id: "spd_200_03",
        categoryId: "tv_sopranos_deep",
        tier: 200,
        prompt: "The Sopranos aired on which premium cable network, launching what many call the Golden Age of Television?",
        answer: "HBO",
        acceptableAnswers: [],
      },
      {
        id: "spd_400_01",
        categoryId: "tv_sopranos_deep",
        tier: 400,
        prompt: "The series uses ducks as a recurring symbolic element starting from the pilot. What do the ducks represent in the context of Tony's therapy?",
        answer: "Family and Tony's fear of losing his family — his panic attack in the pilot is triggered by ducks leaving his pool, which Dr. Melfi interprets as separation anxiety",
        acceptableAnswers: ["fear of losing family", "family and loss", "Tony's fear of his family leaving"],
      },
      {
        id: "spd_400_02",
        categoryId: "tv_sopranos_deep",
        tier: 400,
        prompt: "Christopher Moltisanti has a recurring dream and aspiration beyond the mob. What does he want to be, and how does this manifest in the show?",
        answer: "He wants to be a Hollywood screenwriter — he writes a screenplay and later produces a horror film called 'Cleaver' that thinly mirrors his life and relationship with Tony",
        acceptableAnswers: ["a Hollywood screenwriter", "he writes screenplays", "a filmmaker, he makes a movie called Cleaver"],
      },
      {
        id: "spd_400_03",
        categoryId: "tv_sopranos_deep",
        tier: 400,
        prompt: "Creator David Chase wrote the series partly as a metaphor for a specific personal relationship. What relationship inspired the Tony-Livia dynamic?",
        answer: "Chase's own relationship with his mother — Livia Soprano is based on Chase's mother, and the therapy element came from his own experience in therapy discussing her",
        acceptableAnswers: ["his relationship with his own mother", "based on Chase's mother"],
      },
      {
        id: "spd_600_01",
        categoryId: "tv_sopranos_deep",
        tier: 600,
        prompt: "The series finale's controversial cut to black has been debated for decades. In 2021, David Chase appeared to accidentally confirm the ending's meaning. What did he say?",
        answer: "In an interview, Chase initially said the cut to black meant Tony died, saying 'I had that death scene...' before catching himself. He later backtracked, but the slip was widely reported as confirmation.",
        acceptableAnswers: ["he accidentally said Tony died", "Chase slipped and confirmed Tony's death"],
        explanation: "The Hollywood Reporter interviewer caught the moment. Chase's representatives disputed the interpretation, but the exchange strongly suggests Tony was killed in the diner.",
      },
      {
        id: "spd_600_02",
        categoryId: "tv_sopranos_deep",
        tier: 600,
        prompt: "James Gandolfini's preparation for the role of Tony was remarkably intense. What unusual personal technique did he reportedly use to stay in an agitated emotional state between takes?",
        answer: "He would reportedly pinch himself, listen to aggressive music, and stay in a state of agitation between takes. He also refused to read ahead in scripts so his reactions would be genuine.",
        acceptableAnswers: ["he would agitate himself between takes", "kept himself angry and didn't read ahead in scripts"],
        explanation: "Gandolfini's method approach took a physical and emotional toll. He reportedly struggled with the darkness of the character and the blurring of art and life.",
      },
      {
        id: "spd_600_03",
        categoryId: "tv_sopranos_deep",
        tier: 600,
        prompt: "The Sopranos' opening credits drive from New York to New Jersey. The sequence was deliberately shot to show a specific visual journey. What landmarks appear, and what does the journey symbolize?",
        answer: "It shows Tony driving through the Lincoln Tunnel, past the NJ Turnpike, industrial landscapes, and into suburban North Jersey — symbolizing the transition from the glamour of organized crime to the mundane suburban reality of Tony's double life",
        acceptableAnswers: ["Lincoln Tunnel to suburbs, showing Tony's dual life", "the drive from NYC to NJ suburbia representing his two worlds"],
      },
    ],
  },
  {
    id: "mv_coen_brothers_deep",
    group: "Movies",
    name: "Coen Brothers Deep Cuts",
    culture: "american",
    description: "The filmography of Joel and Ethan Coen — from Fargo and No Country for Old Men to The Big Lebowski and their signature blend of dark humor and violence.",
    imageUrl: "",
    questions: [
      {
        id: "cnd_200_01",
        categoryId: "mv_coen_brothers_deep",
        tier: 200,
        prompt: "In The Big Lebowski, what does Jeff 'The Dude' Lebowski's favorite drink consist of?",
        answer: "A White Russian (vodka, coffee liqueur, and cream)",
        acceptableAnswers: ["White Russian"],
      },
      {
        id: "cnd_200_02",
        categoryId: "mv_coen_brothers_deep",
        tier: 200,
        prompt: "Which Coen Brothers film is set in snowy Minnesota and features a pregnant police chief investigating a kidnapping gone wrong?",
        answer: "Fargo",
        acceptableAnswers: [],
      },
      {
        id: "cnd_200_03",
        categoryId: "mv_coen_brothers_deep",
        tier: 200,
        prompt: "What Coen Brothers film won four Academy Awards in 2008 including Best Picture, featuring Javier Bardem as the terrifying Anton Chigurh?",
        answer: "No Country for Old Men",
        acceptableAnswers: [],
      },
      {
        id: "cnd_400_01",
        categoryId: "mv_coen_brothers_deep",
        tier: 400,
        prompt: "Anton Chigurh's signature weapon in No Country for Old Men is unconventional. What does he use, and what is it actually designed for?",
        answer: "A captive bolt pistol (cattle gun) — designed for slaughtering livestock, he uses it to kill people and blow out door locks",
        acceptableAnswers: ["captive bolt gun", "cattle gun", "bolt gun"],
        explanation: "The weapon is a real slaughterhouse tool. Its use by Chigurh reinforces his view of humans as no different from cattle — something to be dispatched without emotion.",
      },
      {
        id: "cnd_400_02",
        categoryId: "mv_coen_brothers_deep",
        tier: 400,
        prompt: "Fargo opens with the text 'This is a true story.' Is this claim actually true?",
        answer: "No — the Coens fabricated the 'true story' claim entirely. It was a deliberate stylistic choice to make the audience accept the story's absurd events as plausible.",
        acceptableAnswers: ["no, it's fictional", "no, they made it up"],
        explanation: "The Coens have admitted it's fiction. The disclaimer was a creative decision that brilliantly primes audiences to accept the film's increasingly wild plot as reality.",
      },
      {
        id: "cnd_400_03",
        categoryId: "mv_coen_brothers_deep",
        tier: 400,
        prompt: "The Coens' first film, Blood Simple (1984), established many of their trademarks. How did they fund this ultra-low-budget debut?",
        answer: "They created a two-minute trailer (before making the actual film) and used it to raise money from investors, mostly in their home state of Minnesota",
        acceptableAnswers: ["made a trailer first to raise money", "raised money from investors using a fake trailer"],
        explanation: "The trailer-first approach was innovative for indie filmmaking at the time. They raised about $1.5 million from investors who'd never funded a film before.",
      },
      {
        id: "cnd_600_01",
        categoryId: "mv_coen_brothers_deep",
        tier: 600,
        prompt: "The Big Lebowski was a box office disappointment upon release but became one of cinema's greatest cult films. What annual event celebrates the film and its philosophy?",
        answer: "Lebowski Fest — an annual convention/bowling party that began in Louisville, Kentucky in 2002 and has spread worldwide. There's also Dudeism, an actual registered religion based on The Dude's philosophy.",
        acceptableAnswers: ["Lebowski Fest", "Dudeism", "an annual bowling festival"],
      },
      {
        id: "cnd_600_02",
        categoryId: "mv_coen_brothers_deep",
        tier: 600,
        prompt: "The Coens use a specific pseudonym when they edit their own films. What name do they credit themselves under?",
        answer: "Roderick Jaynes",
        acceptableAnswers: [],
        explanation: "Roderick Jaynes is a fictional person. The Coens have maintained the fiction for decades — Jaynes has even been nominated for Academy Awards, with the Coens providing fake bios and quotes.",
      },
      {
        id: "cnd_600_03",
        categoryId: "mv_coen_brothers_deep",
        tier: 600,
        prompt: "In Barton Fink (1991), the mysterious contents of a box that Charlie Meadows gives Barton is never revealed. What is the prevailing interpretation of what's in the box?",
        answer: "Most interpretations suggest it contains a severed head (Charlie is revealed to be a serial killer). The box's contents — like the film itself — represent the unknowable horror that Barton refuses to confront about the real world.",
        acceptableAnswers: ["a severed head", "most people think it's a severed head"],
        explanation: "The Coens have never confirmed the contents. The box serves as the film's central metaphor for the gap between artistic pretension and brutal reality.",
      },
    ],
  },
  {
    id: "mu_reggae_roots",
    group: "Music",
    name: "Reggae Roots & Dub",
    culture: "universal",
    description: "The deep roots of Jamaican music — from ska and rocksteady to roots reggae, dub, and dancehall, and the cultural revolution they sparked worldwide.",
    imageUrl: "",
    questions: [
      {
        id: "reg_200_01",
        categoryId: "mu_reggae_roots",
        tier: 200,
        prompt: "Who is considered the 'King of Reggae' and brought the genre to worldwide attention with albums like 'Exodus'?",
        answer: "Bob Marley",
        acceptableAnswers: [],
      },
      {
        id: "reg_200_02",
        categoryId: "mu_reggae_roots",
        tier: 200,
        prompt: "Reggae music is closely associated with which spiritual movement from Jamaica?",
        answer: "Rastafari",
        acceptableAnswers: ["Rastafarianism", "Rasta"],
      },
      {
        id: "reg_200_03",
        categoryId: "mu_reggae_roots",
        tier: 200,
        prompt: "What is the characteristic rhythmic pattern of reggae guitar, where the emphasis falls on the offbeat?",
        answer: "The skank (offbeat chucking rhythm)",
        acceptableAnswers: ["offbeat rhythm", "the skank", "offbeat guitar"],
      },
      {
        id: "reg_400_01",
        categoryId: "mu_reggae_roots",
        tier: 400,
        prompt: "Reggae evolved through two earlier Jamaican genres before taking its final form. What were they, and in what order did they develop?",
        answer: "Ska (late 1950s-mid 1960s) → Rocksteady (1966-1968) → Reggae (late 1960s onward)",
        acceptableAnswers: ["ska then rocksteady then reggae", "ska and rocksteady"],
      },
      {
        id: "reg_400_02",
        categoryId: "mu_reggae_roots",
        tier: 400,
        prompt: "What is dub music, and who is considered its pioneer?",
        answer: "Dub is a subgenre of reggae created by remixing existing tracks — stripping out vocals, emphasizing bass and drums, and adding heavy reverb and delay effects. King Tubby is considered the pioneer.",
        acceptableAnswers: ["remixed reggae with heavy effects, King Tubby", "King Tubby pioneered dub"],
      },
      {
        id: "reg_400_03",
        categoryId: "mu_reggae_roots",
        tier: 400,
        prompt: "The sound system culture of Jamaica was crucial to reggae's development. What is a sound system?",
        answer: "A mobile DJ setup with massive speakers, a selector (DJ), and a deejay (MC/toaster) that would play at outdoor street parties — they were the primary way Jamaicans consumed music",
        acceptableAnswers: ["mobile DJ setup with huge speakers for street parties", "large outdoor music system with DJs"],
      },
      {
        id: "reg_600_01",
        categoryId: "mu_reggae_roots",
        tier: 600,
        prompt: "Lee 'Scratch' Perry is one of reggae's most influential and eccentric producers. What was the name of his famous studio, and what did he eventually do to it?",
        answer: "The Black Ark studio — he burned it down in the late 1970s, reportedly during a period of mental instability, claiming the studio was possessed by demons",
        acceptableAnswers: ["Black Ark, he burned it down", "he set fire to the Black Ark"],
        explanation: "Before its destruction, the Black Ark produced some of reggae's most innovative recordings using primitive equipment. Perry's production techniques influenced dub, punk, and hip-hop.",
      },
      {
        id: "reg_600_02",
        categoryId: "mu_reggae_roots",
        tier: 600,
        prompt: "The Wailers (Bob Marley's band) originally included two other members who were stars in their own right. Who were they, and why did they eventually leave?",
        answer: "Peter Tosh and Bunny Wailer. They left partly due to Marley receiving disproportionate attention from Island Records' Chris Blackwell, and partly over creative differences and reluctance to tour.",
        acceptableAnswers: ["Peter Tosh and Bunny Wailer", "Tosh and Bunny left over Marley getting more attention"],
      },
      {
        id: "reg_600_03",
        categoryId: "mu_reggae_roots",
        tier: 600,
        prompt: "In 1976, an assassination attempt was made on Bob Marley just days before a planned 'Smile Jamaica' concert. What happened, and what did Marley do?",
        answer: "Gunmen entered his home and shot Marley, his wife Rita, and manager Don Taylor. Despite being wounded in the arm and chest, Marley performed at the concert two days later — famously showing the crowd his bandaged wound.",
        acceptableAnswers: ["he was shot but still performed", "shot at home, played the concert anyway with his wounds"],
        explanation: "The attack was politically motivated — the concert was seen as supporting the ruling party. Marley left Jamaica for London soon after and didn't return for over a year.",
      },
    ],
  },
  {
    id: "vg_hollow_knight_deep",
    group: "Video Games",
    name: "Hollow Knight Deep Cuts",
    culture: "universal",
    description: "The hand-drawn Metroidvania masterpiece set in the ruined insect kingdom of Hallownest — deep lore, hidden bosses, and the mysteries beneath the surface.",
    imageUrl: "",
    questions: [
      {
        id: "hkd_200_01",
        categoryId: "vg_hollow_knight_deep",
        tier: 200,
        prompt: "What is the name of the ruined underground insect kingdom where Hollow Knight takes place?",
        answer: "Hallownest",
        acceptableAnswers: [],
      },
      {
        id: "hkd_200_02",
        categoryId: "vg_hollow_knight_deep",
        tier: 200,
        prompt: "What small studio developed Hollow Knight, launching it via Kickstarter?",
        answer: "Team Cherry",
        acceptableAnswers: [],
      },
      {
        id: "hkd_200_03",
        categoryId: "vg_hollow_knight_deep",
        tier: 200,
        prompt: "The Knight (the player character) attacks with a weapon called what?",
        answer: "A nail (a sword-like weapon in this world of insects)",
        acceptableAnswers: ["a nail", "nail"],
      },
      {
        id: "hkd_400_01",
        categoryId: "vg_hollow_knight_deep",
        tier: 400,
        prompt: "The Pale King created vessels (including the player character) for a specific purpose. What was he trying to contain?",
        answer: "The Radiance — a moth goddess of light and dreams whose infection was driving the bugs of Hallownest mad",
        acceptableAnswers: ["the Radiance", "the infection", "a goddess called the Radiance"],
        explanation: "The Pale King created hundreds of void-born vessels in the Abyss, seeking one with 'no mind to think, no will to break' — a pure vessel to seal the Radiance.",
      },
      {
        id: "hkd_400_02",
        categoryId: "vg_hollow_knight_deep",
        tier: 400,
        prompt: "What is the Grimm Troupe, and what does its ritual (the Ritual of the Flame) require the player to do?",
        answer: "A traveling troupe of nightmare beings led by Troupe Master Grimm. The ritual requires collecting flames from fallen Grimmkin across Hallownest to empower the Nightmare Lantern.",
        acceptableAnswers: ["a traveling troupe, you collect flames for them", "nightmare beings whose ritual needs flames"],
      },
      {
        id: "hkd_400_03",
        categoryId: "vg_hollow_knight_deep",
        tier: 400,
        prompt: "The game has multiple endings. What determines which ending you get?",
        answer: "Your choices and items obtained — specifically whether you acquire the Void Heart (by completing the Abyss), which unlocks the true endings where you confront the Radiance directly rather than just sealing it",
        acceptableAnswers: ["whether you get the Void Heart", "which items you have and whether you enter the dream"],
      },
      {
        id: "hkd_600_01",
        categoryId: "vg_hollow_knight_deep",
        tier: 600,
        prompt: "The Pantheon of Hallownest is the game's ultimate challenge, added in the Godmaster DLC. What does it require, and why is it considered one of the hardest challenges in gaming?",
        answer: "It's a boss rush of ALL 42 bosses back-to-back with no saving — including the hardest boss in the game (Absolute Radiance) as the final fight. A single death sends you back to the start.",
        acceptableAnswers: ["42 boss rush with no saves", "all bosses back to back ending with Absolute Radiance"],
        explanation: "Completing the Pantheon of Hallownest is estimated to take over an hour per attempt, with Absolute Radiance at the end being one of the hardest bosses in any game.",
      },
      {
        id: "hkd_600_02",
        categoryId: "vg_hollow_knight_deep",
        tier: 600,
        prompt: "Team Cherry is famously small. How many core developers made Hollow Knight, and what makes this remarkable given the game's scope?",
        answer: "Three core developers — Ari Gibson (art/design), William Pellen (programming), and David Kazi (music/SFX initially, with Christopher Larkin composing the score). The game has over 140 enemies, 40+ bosses, and 15+ areas.",
        acceptableAnswers: ["three people", "3 core developers"],
      },
      {
        id: "hkd_600_03",
        categoryId: "vg_hollow_knight_deep",
        tier: 600,
        prompt: "Mr. Mushroom is one of the game's most mysterious NPCs. After finding all his locations, what does he say that has fueled fan theories about the game's meta-narrative?",
        answer: "He speaks in cryptic riddles that appear to break the fourth wall — his final appearance after completing certain endings shows him flying away from Hallownest, and his dialogue hints at knowledge of the game being a game and references cycles of creation",
        acceptableAnswers: ["fourth-wall-breaking dialogue about cycles", "he breaks the fourth wall and flies away", "cryptic meta dialogue about the nature of the game"],
      },
    ],
  },
  {
    id: "sci_psychology_experiments",
    group: "Science",
    name: "Famous Psychology Experiments",
    culture: "universal",
    description: "The landmark experiments that revealed the hidden mechanics of human behavior — from obedience and conformity to memory and perception.",
    imageUrl: "",
    questions: [
      {
        id: "pse_200_01",
        categoryId: "sci_psychology_experiments",
        tier: 200,
        prompt: "Stanley Milgram's famous experiment tested how far people would go when ordered by an authority figure. What did participants believe they were doing?",
        answer: "Administering increasingly painful electric shocks to a 'learner' in another room (who was actually an actor)",
        acceptableAnswers: ["giving electric shocks", "shocking another person when told to"],
      },
      {
        id: "pse_200_02",
        categoryId: "sci_psychology_experiments",
        tier: 200,
        prompt: "What psychological concept does Pavlov's dog experiment demonstrate — where a neutral stimulus (a bell) triggers a response (salivation) after being paired with food?",
        answer: "Classical conditioning",
        acceptableAnswers: ["conditioning", "Pavlovian conditioning"],
      },
      {
        id: "pse_200_03",
        categoryId: "sci_psychology_experiments",
        tier: 200,
        prompt: "The Stanford Prison Experiment divided participants into guards and prisoners. What happened that caused it to be shut down early?",
        answer: "The 'guards' became sadistic and the 'prisoners' became psychologically distressed — the experiment spiraled out of control in less than a week",
        acceptableAnswers: ["guards became abusive", "it became too psychologically harmful", "guards turned sadistic"],
      },
      {
        id: "pse_400_01",
        categoryId: "sci_psychology_experiments",
        tier: 400,
        prompt: "Solomon Asch's conformity experiment used a simple line-length comparison task. What was the shocking finding about how often people conformed to an obviously wrong group answer?",
        answer: "About 75% of participants conformed to the group's clearly wrong answer at least once, and overall conformity rate was about 33% across all trials",
        acceptableAnswers: ["about 75% conformed at least once", "roughly a third of the time people went along with the wrong answer"],
        explanation: "Participants knew the answer was wrong but went along with the group anyway. When even one other person gave the correct answer, conformity dropped dramatically.",
      },
      {
        id: "pse_400_02",
        categoryId: "sci_psychology_experiments",
        tier: 400,
        prompt: "The 'bystander effect' was studied by Darley and Latané after the murder of Kitty Genovese. What does the bystander effect predict?",
        answer: "The more people who witness an emergency, the less likely any individual is to help — each person assumes someone else will intervene",
        acceptableAnswers: ["more witnesses means less chance of help", "people are less likely to help when others are present"],
        explanation: "The original Genovese story (38 witnesses did nothing) was later found to be exaggerated by the New York Times, but the psychological principle was validated by subsequent research.",
      },
      {
        id: "pse_400_03",
        categoryId: "sci_psychology_experiments",
        tier: 400,
        prompt: "The Marshmallow Test, conducted by Walter Mischel at Stanford, gave children a choice between one marshmallow now or two later. What did the long-term follow-up supposedly show?",
        answer: "Children who could delay gratification had better life outcomes years later (SAT scores, education, health). However, later replications with larger and more diverse samples found the effect was much smaller and largely explained by socioeconomic background.",
        acceptableAnswers: ["delayed gratification predicted success, but later studies found it was mostly about socioeconomic status", "kids who waited did better but it was really about wealth"],
      },
      {
        id: "pse_600_01",
        categoryId: "sci_psychology_experiments",
        tier: 600,
        prompt: "The Stanford Prison Experiment is widely cited but has faced serious criticism in recent years. What specific ethical and methodological problems have been uncovered?",
        answer: "Zimbardo actively coached the guards to be cruel, demand characteristics influenced behavior, sample was self-selected, and recently released audio recordings show Zimbardo's assistants instructing guards on how to behave — it was less a spontaneous emergence of evil than a directed performance",
        acceptableAnswers: ["Zimbardo coached the guards", "the experimenter influenced the results", "it was manipulated by Zimbardo"],
        explanation: "Thibault Le Texier's 2018 book 'History of a Lie' used archival materials to show extensive experimenter interference. Many psychologists now consider it more theater than science.",
      },
      {
        id: "pse_600_02",
        categoryId: "sci_psychology_experiments",
        tier: 600,
        prompt: "The 'Little Albert' experiment (1920) by John Watson conditioned a baby to fear white rats. What happened to Little Albert, and why is this experiment considered deeply unethical?",
        answer: "The fear was never deconditioned — Watson simply stopped the experiment when Albert's mother removed him from the hospital. Albert was never treated or followed up with. His real identity was only discovered in 2009 (Douglas Merritte), and he died at age 6 of hydrocephalus.",
        acceptableAnswers: ["the fear was never removed and the child was never treated", "Watson never deconditioned the fear, the boy died young"],
      },
      {
        id: "pse_600_03",
        categoryId: "sci_psychology_experiments",
        tier: 600,
        prompt: "The replication crisis has challenged many famous psychology findings. What is the replication crisis, and what landmark 2015 study quantified the problem?",
        answer: "The Reproducibility Project (Open Science Collaboration, 2015) attempted to replicate 100 published psychology studies and found that only about 36-39% could be successfully replicated — meaning the majority of published results may not be reliable",
        acceptableAnswers: ["only about 36% of 100 studies replicated", "the 2015 Reproducibility Project found most studies didn't replicate"],
        explanation: "The project was a watershed moment for psychology. It revealed that publication bias, small sample sizes, and p-hacking had inflated the literature with unreliable findings.",
      },
    ],
  },
  {
    id: "cul_tea_culture",
    group: "Culture",
    name: "Tea Culture",
    culture: "universal",
    description: "The world's most consumed beverage after water — from Chinese tea ceremonies and Japanese matcha to British afternoon tea and Indian chai.",
    imageUrl: "",
    questions: [
      {
        id: "tea_200_01",
        categoryId: "cul_tea_culture",
        tier: 200,
        prompt: "All true tea — black, green, white, oolong — comes from the same plant. What is it?",
        answer: "Camellia sinensis",
        acceptableAnswers: ["camellia sinensis", "the tea plant"],
      },
      {
        id: "tea_200_02",
        categoryId: "cul_tea_culture",
        tier: 200,
        prompt: "What is the main difference between black tea and green tea, if they come from the same plant?",
        answer: "The level of oxidation — black tea is fully oxidized while green tea is minimally oxidized, giving them different flavors, colors, and chemical profiles",
        acceptableAnswers: ["oxidation level", "black tea is oxidized, green tea isn't"],
      },
      {
        id: "tea_200_03",
        categoryId: "cul_tea_culture",
        tier: 200,
        prompt: "Which country is the world's largest producer of tea?",
        answer: "China",
        acceptableAnswers: [],
      },
      {
        id: "tea_400_01",
        categoryId: "cul_tea_culture",
        tier: 400,
        prompt: "The Boston Tea Party of 1773 was a pivotal moment in American history. What specific tax policy were the colonists protesting?",
        answer: "The Tea Act, which gave the British East India Company a monopoly on tea sales in the colonies — the issue was 'taxation without representation,' not the tax amount itself",
        acceptableAnswers: ["the Tea Act", "taxation without representation"],
      },
      {
        id: "tea_400_02",
        categoryId: "cul_tea_culture",
        tier: 400,
        prompt: "Japanese matcha is prepared differently from other teas. What makes its cultivation and preparation unique?",
        answer: "The tea plants are shaded for weeks before harvest (increasing chlorophyll and amino acids), then the leaves are ground into a fine powder that is whisked directly into water rather than steeped",
        acceptableAnswers: ["shade-grown and ground into powder", "it's a powder whisked into water, not steeped"],
      },
      {
        id: "tea_400_03",
        categoryId: "cul_tea_culture",
        tier: 400,
        prompt: "Pu-erh tea is unique among teas. What makes it special, and how does it differ from other teas?",
        answer: "It undergoes microbial fermentation and aging — some pu-erh cakes are aged for decades and improve with time, like wine. It's the only tea that is truly fermented (most 'fermented' teas are actually oxidized).",
        acceptableAnswers: ["it's fermented and aged", "aged tea that improves over time", "microbially fermented and aged like wine"],
      },
      {
        id: "tea_600_01",
        categoryId: "cul_tea_culture",
        tier: 600,
        prompt: "The Opium Wars (1839-1860) were fundamentally about tea. How did Britain's demand for Chinese tea lead to two wars?",
        answer: "Britain was spending enormous amounts of silver buying Chinese tea but China wanted nothing in return. The British East India Company began selling Indian opium to China to balance trade. When China tried to stop the opium flow, Britain went to war.",
        acceptableAnswers: ["Britain sold opium to pay for tea, China tried to stop it", "trade imbalance led to opium sales which led to war"],
      },
      {
        id: "tea_600_02",
        categoryId: "cul_tea_culture",
        tier: 600,
        prompt: "Robert Fortune carried out one of history's most consequential acts of industrial espionage. What did he do, and how did it reshape the global tea trade?",
        answer: "In 1848, the Scottish botanist disguised himself as a Chinese merchant, infiltrated tea-producing regions, and smuggled tea plants, seeds, and production knowledge to British India — breaking China's tea monopoly and establishing the Indian tea industry",
        acceptableAnswers: ["stole tea plants from China for India", "smuggled tea plants to British India", "broke China's tea monopoly by stealing plants"],
      },
      {
        id: "tea_600_03",
        categoryId: "cul_tea_culture",
        tier: 600,
        prompt: "The Japanese tea ceremony (chanoyu or sadō) was heavily influenced by Zen Buddhism and codified by a specific tea master in the 16th century. Who was he, and how did he die?",
        answer: "Sen no Rikyū codified the ceremony's philosophy of wabi-sabi (rustic simplicity). He was ordered to commit seppuku by the warlord Toyotomi Hideyoshi in 1591, possibly over a political or personal dispute.",
        acceptableAnswers: ["Sen no Rikyu, ordered to commit seppuku", "Rikyu, killed by Hideyoshi"],
        explanation: "Rikyū's death remains one of Japanese history's great mysteries. His philosophy — that beauty lies in imperfection and simplicity — became the foundation of Japanese aesthetics.",
      },
    ],
  },
  {
    id: "his_ancient_greece_deep",
    group: "History",
    name: "Ancient Greece Deep Cuts",
    culture: "universal",
    description: "Beyond the basics of Athens and Sparta — the lesser-known stories, battles, thinkers, and cultural innovations of the ancient Greek world.",
    imageUrl: "",
    questions: [
      {
        id: "agd_200_01",
        categoryId: "his_ancient_greece_deep",
        tier: 200,
        prompt: "What form of government did Athens pioneer that is now the foundation of Western political systems?",
        answer: "Democracy",
        acceptableAnswers: ["direct democracy"],
      },
      {
        id: "agd_200_02",
        categoryId: "his_ancient_greece_deep",
        tier: 200,
        prompt: "The Battle of Thermopylae in 480 BC is legendary for a small Greek force holding off a massive Persian army. How many Spartan soldiers made the famous last stand?",
        answer: "300",
        acceptableAnswers: [],
      },
      {
        id: "agd_200_03",
        categoryId: "his_ancient_greece_deep",
        tier: 200,
        prompt: "What was the name of the multi-day athletic competition held every four years in honor of Zeus, which inspired the modern Olympics?",
        answer: "The Olympic Games (at Olympia)",
        acceptableAnswers: ["the Olympics", "Olympic Games"],
      },
      {
        id: "agd_400_01",
        categoryId: "his_ancient_greece_deep",
        tier: 400,
        prompt: "Athenian democracy was radical but limited. Which groups were excluded from participating in the democratic process?",
        answer: "Women, slaves, and foreign residents (metics) — only adult male citizens could vote, which was roughly 10-20% of the total population",
        acceptableAnswers: ["women, slaves, and foreigners", "only male citizens could vote"],
      },
      {
        id: "agd_400_02",
        categoryId: "his_ancient_greece_deep",
        tier: 400,
        prompt: "The Antikythera mechanism, discovered in a shipwreck in 1901, is considered the world's first analog computer. What was it designed to do?",
        answer: "Predict astronomical positions, eclipses, and calendar cycles — including the timing of the Olympic Games",
        acceptableAnswers: ["predict astronomical events", "calculate eclipses and astronomical positions", "an astronomical calculator"],
        explanation: "Dating to around 100 BC, the mechanism's complexity wasn't matched until medieval astronomical clocks over a thousand years later.",
      },
      {
        id: "agd_400_03",
        categoryId: "his_ancient_greece_deep",
        tier: 400,
        prompt: "Ostracism was a unique Athenian democratic practice. How did it work?",
        answer: "Citizens could vote to exile any person for 10 years by scratching their name on a pottery shard (ostrakon). It was designed to prevent tyranny — anyone perceived as too powerful could be banished.",
        acceptableAnswers: ["voting to exile someone for 10 years", "citizens wrote names on pottery to banish people"],
      },
      {
        id: "agd_600_01",
        categoryId: "his_ancient_greece_deep",
        tier: 600,
        prompt: "Eratosthenes calculated the circumference of the Earth around 240 BC with remarkable accuracy. How did he do it using only shadows and geometry?",
        answer: "He knew that at noon on the summer solstice in Syene (Aswan), the sun cast no shadow (it was directly overhead). In Alexandria, it cast a shadow of about 7.2 degrees. He measured the distance between the cities and used the angle to calculate the full circumference — arriving at approximately 40,000 km, which is remarkably close to the actual value.",
        acceptableAnswers: ["compared shadow angles between two cities", "used shadow measurements in Syene and Alexandria"],
      },
      {
        id: "agd_600_02",
        categoryId: "his_ancient_greece_deep",
        tier: 600,
        prompt: "The Sacred Band of Thebes was an elite military unit that defeated the supposedly invincible Spartans at the Battle of Leuctra in 371 BC. What was unique about its composition?",
        answer: "It was composed of 150 pairs of male lovers. The theory was that soldiers would fight harder to protect their beloved, and the shame of cowardice before a lover was the strongest motivator.",
        acceptableAnswers: ["pairs of male lovers", "150 couples of male lovers", "an army of gay couples"],
        explanation: "The Sacred Band was undefeated for decades until destroyed by Philip II and Alexander the Great at Chaeronea in 338 BC. Philip reportedly wept when he saw their bodies.",
      },
      {
        id: "agd_600_03",
        categoryId: "his_ancient_greece_deep",
        tier: 600,
        prompt: "Diogenes of Sinope, the Cynic philosopher, is famous for his provocative stunts. What did he reportedly do when Alexander the Great visited him and offered to grant any wish?",
        answer: "He asked Alexander to move out of his sunlight. Alexander was so impressed that he reportedly said, 'If I were not Alexander, I would wish to be Diogenes.'",
        acceptableAnswers: ["told Alexander to stop blocking his sunlight", "asked him to move out of his sun"],
        explanation: "Diogenes lived in a ceramic jar in the marketplace, carried a lantern in daylight 'looking for an honest man,' and publicly mocked wealth, power, and social convention.",
      },
    ],
  },
  {
    id: "mu_grunge_deep",
    group: "Music",
    name: "Grunge Movement",
    culture: "american",
    description: "The Seattle explosion that killed hair metal and redefined rock — the bands, the labels, the fashion, and the cultural moment that changed everything.",
    imageUrl: "",
    questions: [
      {
        id: "grd_200_01",
        categoryId: "mu_grunge_deep",
        tier: 200,
        prompt: "Which Nirvana album, released in 1991, is considered the album that brought grunge to the mainstream?",
        answer: "Nevermind",
        acceptableAnswers: [],
      },
      {
        id: "grd_200_02",
        categoryId: "mu_grunge_deep",
        tier: 200,
        prompt: "What independent Seattle record label signed many early grunge bands including Nirvana, Soundgarden, and Mudhoney?",
        answer: "Sub Pop",
        acceptableAnswers: ["Sub Pop Records"],
      },
      {
        id: "grd_200_03",
        categoryId: "mu_grunge_deep",
        tier: 200,
        prompt: "What city is considered the birthplace of grunge?",
        answer: "Seattle, Washington",
        acceptableAnswers: ["Seattle"],
      },
      {
        id: "grd_400_01",
        categoryId: "mu_grunge_deep",
        tier: 400,
        prompt: "Grunge fashion became a mainstream trend, but the musicians themselves didn't intend it as fashion. Why did they dress in flannel shirts, ripped jeans, and thrift store clothes?",
        answer: "It wasn't a fashion statement — they were broke musicians in a rainy, cold city buying cheap clothes from thrift stores. The flannel and layers were practical for Seattle weather.",
        acceptableAnswers: ["they were poor and it was practical", "cheap thrift store clothes for Seattle weather", "poverty and cold weather, not fashion"],
      },
      {
        id: "grd_400_02",
        categoryId: "mu_grunge_deep",
        tier: 400,
        prompt: "Mudhoney is often called 'the godfathers of grunge.' Their frontman Mark Arm is credited with first using the word 'grunge' in a musical context. Where did he use it?",
        answer: "In a 1981 letter to the Seattle fanzine Desperate Times, where he described his band Mr. Epp and the Calculations as 'pure grunge! pure noise! pure shit!'",
        acceptableAnswers: ["in a letter to a fanzine", "in a letter describing his band's music"],
      },
      {
        id: "grd_400_03",
        categoryId: "mu_grunge_deep",
        tier: 400,
        prompt: "The moment grunge 'killed' hair metal is often pinpointed to a specific chart event. What happened?",
        answer: "Nirvana's Nevermind knocked Michael Jackson's Dangerous off the #1 spot on the Billboard 200 in January 1992, symbolizing a generational shift in popular music",
        acceptableAnswers: ["Nevermind hit #1 over Michael Jackson", "Nirvana knocked MJ off number one"],
      },
      {
        id: "grd_600_01",
        categoryId: "mu_grunge_deep",
        tier: 600,
        prompt: "Sub Pop Records was nearly bankrupt before Nirvana's success. How did the label's co-founders, Bruce Pavitt and Jonathan Poneman, use a marketing trick involving a British journalist to generate hype?",
        answer: "They flew Everett True from Melody Maker to Seattle to write about the scene, essentially creating the narrative of a 'Seattle sound' for the British music press — which then reflected back to America and created the grunge explosion",
        acceptableAnswers: ["flew a British journalist to Seattle to create hype", "used Melody Maker to create the Seattle scene narrative"],
        explanation: "The Sub Pop Singles Club and the Melody Maker coverage created a mythology around Seattle before most Americans had heard the music. It was one of indie music's greatest marketing coups.",
      },
      {
        id: "grd_600_02",
        categoryId: "mu_grunge_deep",
        tier: 600,
        prompt: "The New York Times published a notorious article in 1992 about grunge fashion, including a glossary of 'grunge slang' terms. What was the scandal behind this article?",
        answer: "The 'grunge slang' glossary was entirely fabricated by a Sub Pop employee (Megan Jasper) who made up fake terms on the spot as a joke. The Times published them as real, embarrassing the paper.",
        acceptableAnswers: ["the slang was fake, made up by a Sub Pop employee", "Megan Jasper pranked the NYT with fake grunge slang"],
        explanation: "Terms like 'swingin' on the flippity-flop' (hanging out) and 'lamestain' (uncool person) were pure fiction. The incident became a legendary example of mainstream media cluelessness about youth culture.",
      },
      {
        id: "grd_600_03",
        categoryId: "mu_grunge_deep",
        tier: 600,
        prompt: "Kurt Cobain's suicide note, read publicly by Courtney Love, quotes a specific Neil Young lyric. What was the quote, and how did Neil Young respond?",
        answer: "Cobain quoted 'It's better to burn out than to fade away' from Neil Young's 'My My, Hey Hey.' Young was reportedly devastated and later said he felt partly responsible, writing the song 'Sleeps with Angels' in response.",
        acceptableAnswers: ["better to burn out than fade away, Young wrote Sleeps with Angels", "a Neil Young lyric, Young felt guilty and wrote an album about it"],
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 65 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
