#!/usr/bin/env python3
"""Insert wave 79 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_legion",
    group: "TV Shows",
    name: "Legion",
    culture: "universal",
    description: "Noah Hawley's psychedelic X-Men series about the most powerful mutant alive",
    imageUrl: "",
    questions: [
      { id: "lgn_200_01", categoryId: "tv_legion", tier: 200, prompt: "What is the real name of the protagonist who has been misdiagnosed with schizophrenia his entire life?", answer: "David Haller", acceptableAnswers: ["David Haller", "David", "Legion"], explanation: "David Haller discovers his mental illness is actually the manifestation of immense mutant powers." },
      { id: "lgn_200_02", categoryId: "tv_legion", tier: 200, prompt: "Which famous X-Men villain is revealed to be David's father?", answer: "Professor X / Charles Xavier", acceptableAnswers: ["Professor X", "Charles Xavier", "Xavier"], explanation: "David is the son of Charles Xavier, making him one of the most powerful mutants in existence." },
      { id: "lgn_200_03", categoryId: "tv_legion", tier: 200, prompt: "What parasitic mutant entity has been living inside David's mind since childhood, feeding on his power?", answer: "Amahl Farouk / The Shadow King", acceptableAnswers: ["Shadow King", "Amahl Farouk", "The Shadow King"], explanation: "The Shadow King implanted himself in David as an infant and has been feeding on his vast psychic powers ever since." },
      { id: "lgn_400_01", categoryId: "tv_legion", tier: 400, prompt: "What eerie children's book villain, the 'Devil with the Yellow Eyes,' is the Shadow King's visual manifestation in Season 1?", answer: "The Devil with the Yellow Eyes / The World's Angriest Boy in the World", acceptableAnswers: ["Devil with the Yellow Eyes", "World's Angriest Boy in the World", "The Angriest Boy"], explanation: "The Shadow King appears as terrifying childhood imagery — a grotesquely fat figure with yellow eyes and a storybook monster." },
      { id: "lgn_400_02", categoryId: "tv_legion", tier: 400, prompt: "What organization hunts mutants throughout the series, operating from a facility called Division 3?", answer: "Division 3", acceptableAnswers: ["Division 3", "Division Three"], explanation: "Division 3 is a government organization that initially hunts David but later becomes reluctant allies against the Shadow King." },
      { id: "lgn_400_03", categoryId: "tv_legion", tier: 400, prompt: "In Season 3, what does David attempt to do using time travel that makes him the season's antagonist?", answer: "Go back in time to prevent the Shadow King from ever possessing him / rewrite his history", acceptableAnswers: ["Time travel to change his past", "Prevent Shadow King possession", "Rewrite his own history"], explanation: "David's increasingly desperate attempts to rewrite history make him the villain, as the show questions whether he's a hero or a god complex run amok." },
      { id: "lgn_600_01", categoryId: "tv_legion", tier: 600, prompt: "What specific Bolero by Ravel sequence in Season 1 Episode 7 was filmed as an elaborate dance battle representing a psychic duel?", answer: "The astral plane dance battle between David and the Shadow King set to Ravel's Bolero", acceptableAnswers: ["Bolero dance battle", "Psychic dance battle", "Ravel Bolero sequence"], explanation: "The sequence reimagined a psychic battle as a choreographed dance set to Bolero, exemplifying the show's avant-garde storytelling." },
      { id: "lgn_600_02", categoryId: "tv_legion", tier: 600, prompt: "What silent film-inspired episode in Season 1 takes place almost entirely in the astral plane and features no dialogue for extended sequences?", answer: "Chapter 7", acceptableAnswers: ["Chapter 7", "Episode 7"], explanation: "Chapter 7 used silent film techniques, shifting aspect ratios, and experimental sound design to portray the astral plane battle." },
      { id: "lgn_600_03", categoryId: "tv_legion", tier: 600, prompt: "What philosopher's concept of the 'maze of the mind' does Noah Hawley explicitly reference in the show's exploration of David's fractured psyche?", answer: "Oliver Sacks / neurological case studies", acceptableAnswers: ["Oliver Sacks", "Sacks"], explanation: "Hawley drew on Oliver Sacks' neurological case studies to ground David's surreal experiences in real psychological phenomena." }
    ]
  },
  {
    id: "tv_utopia",
    group: "TV Shows",
    name: "Utopia (UK)",
    culture: "universal",
    description: "The Channel 4 conspiracy thriller with a distinctive visual style and shocking violence",
    imageUrl: "",
    questions: [
      { id: "utp_200_01", categoryId: "tv_utopia", tier: 200, prompt: "What mysterious graphic novel manuscript drives the entire conspiracy in the series?", answer: "The Utopia Experiments", acceptableAnswers: ["Utopia Experiments", "The Utopia Experiments", "The manuscript"], explanation: "The Utopia Experiments is a graphic novel whose pages contain encoded information about a deadly conspiracy." },
      { id: "utp_200_02", categoryId: "tv_utopia", tier: 200, prompt: "What is the name of the shadowy organization that pursues the manuscript and its holders throughout the series?", answer: "The Network", acceptableAnswers: ["The Network"], explanation: "The Network is a powerful shadow organization willing to kill anyone who gets close to the Utopia manuscript." },
      { id: "utp_200_03", categoryId: "tv_utopia", tier: 200, prompt: "What makes the show's visual style immediately distinctive from other British dramas?", answer: "Hyper-saturated, vivid colors with a yellow-dominated color palette", acceptableAnswers: ["Bright saturated colors", "Yellow color palette", "Vivid colors", "Hyper-saturated colors"], explanation: "Cinematographer Ole Bratt Birkeland created a striking visual style using heavily saturated primary colors rarely seen in British TV." },
      { id: "utp_400_01", categoryId: "tv_utopia", tier: 400, prompt: "What is the true purpose of the Janus project that the Network has been developing?", answer: "A protein embedded in a vaccine that causes targeted sterilization to reduce the global population", acceptableAnswers: ["Sterilization through vaccines", "Population control via vaccine", "Janus protein sterilization"], explanation: "Janus is designed to sterilize specific ethnic groups through a flu vaccine, presented as a utilitarian solution to overpopulation." },
      { id: "utp_400_02", categoryId: "tv_utopia", tier: 400, prompt: "What traumatic event in Jessica Hyde's childhood connects her directly to the creation of the Utopia manuscript?", answer: "She was experimented on as a child; her father Philip Carvel created the manuscript based on his work and her DNA", acceptableAnswers: ["Experimented on as a child", "Her father created the manuscript", "Childhood experiments"], explanation: "Jessica Hyde was the test subject for her father's research, making her both the victim and the key to the conspiracy." },
      { id: "utp_400_03", categoryId: "tv_utopia", tier: 400, prompt: "What controversial scene involving children at a school caused significant media backlash when the show aired?", answer: "The school shooting scene", acceptableAnswers: ["School shooting", "The school shooting", "Shooting at the school"], explanation: "The scene was deliberately shocking and controversial, contributing to discussions about the limits of violence on television." },
      { id: "utp_600_01", categoryId: "tv_utopia", tier: 600, prompt: "What specific technique did director Marc Munden use for the torture scene in Episode 1, involving a spoon and bleach, that set the show's unflinching tone?", answer: "Showing the torture in bright, well-lit closeup with no cutaways or relief, forcing the audience to watch", acceptableAnswers: ["No cutaway technique", "Bright lit unbroken shots", "Unflinching continuous shots"], explanation: "The refusal to use conventional editing shortcuts (cutting away, dimming lights) made the violence more disturbing and established the show's uncompromising approach." },
      { id: "utp_600_02", categoryId: "tv_utopia", tier: 600, prompt: "What real-world scientific concept does Philip Carvel's work draw on regarding amino acid sequences and population genetics?", answer: "Targeted genetic sterilization through protein engineering / synthetic biology targeting specific genetic markers", acceptableAnswers: ["Protein engineering for genetic targeting", "Synthetic biology targeting genetics", "Targeted protein sterilization"], explanation: "The show's science fiction is grounded in real concepts about how engineered proteins could theoretically interact with specific genetic variations." },
      { id: "utp_600_03", categoryId: "tv_utopia", tier: 600, prompt: "What composer created the show's distinctive soundtrack using primarily a solo violin and electronics, and what technique made it so unsettling?", answer: "Cristobal Tapia de Veer, using extended techniques like col legno and prepared violin with electronic processing", acceptableAnswers: ["Cristobal Tapia de Veer", "Tapia de Veer"], explanation: "Tapia de Veer's score used unconventional violin techniques and vocal samples to create one of TV's most distinctive and disturbing soundtracks." }
    ]
  },
  {
    id: "mu_joy_div",
    group: "Music",
    name: "Joy Division & New Order",
    culture: "universal",
    description: "From post-punk darkness to electronic dance music — Manchester's most influential bands",
    imageUrl: "",
    questions: [
      { id: "jdn_200_01", categoryId: "mu_joy_div", tier: 200, prompt: "What was the name of Joy Division's lead singer who died by suicide in May 1980 at age 23?", answer: "Ian Curtis", explanation: "Ian Curtis's death on the eve of their first American tour transformed Joy Division from a cult band into a legend." },
      { id: "jdn_200_02", categoryId: "mu_joy_div", tier: 200, prompt: "What iconic Joy Division album cover, designed by Peter Saville, shows a pulsar signal plotted as stacked radio waves?", answer: "Unknown Pleasures", explanation: "The CP 1919 pulsar chart became one of music's most recognizable and most bootlegged images." },
      { id: "jdn_200_03", categoryId: "mu_joy_div", tier: 200, prompt: "After Ian Curtis's death, the remaining members reformed under what name?", answer: "New Order", explanation: "Bernard Sumner, Peter Hook, and Stephen Morris continued as New Order, adding Gillian Gilbert and pioneering electronic dance music." },
      { id: "jdn_400_01", categoryId: "mu_joy_div", tier: 400, prompt: "What New Order single, released in 1983, became the best-selling 12-inch single of all time?", answer: "Blue Monday", explanation: "Blue Monday's iconic sequencer riff and Peter Saville's die-cut sleeve (which cost more to produce than the retail price) defined the '80s." },
      { id: "jdn_400_02", categoryId: "mu_joy_div", tier: 400, prompt: "What legendary Manchester club did New Order co-own, which became the epicenter of the acid house movement?", answer: "The Haçienda", acceptableAnswers: ["The Hacienda", "Haçienda", "Hacienda", "FAC 51 The Haçienda"], explanation: "The Haçienda (FAC 51) was funded largely by New Order's record sales and became ground zero for British rave culture." },
      { id: "jdn_400_03", categoryId: "mu_joy_div", tier: 400, prompt: "What Factory Records catalog number was assigned to Tony Wilson's coffin when he died in 2007?", answer: "FAC 501", acceptableAnswers: ["FAC 501"], explanation: "True to Factory's obsessive cataloging of everything, Tony Wilson's coffin was assigned a Factory catalog number." },
      { id: "jdn_600_01", categoryId: "mu_joy_div", tier: 600, prompt: "What specific drum machine and programming technique did Stephen Morris use on 'Blue Monday' that created its iconic rhythm?", answer: "Oberheim DMX programmed with a deliberately unquantized, slightly off-grid feel", acceptableAnswers: ["Oberheim DMX", "DMX drum machine"], explanation: "Morris programmed the DMX with intentional imperfections, giving Blue Monday its distinctive human-machine hybrid groove." },
      { id: "jdn_600_02", categoryId: "mu_joy_div", tier: 600, prompt: "What Martin Hannett production technique on Unknown Pleasures involved recording drums in an elevator shaft and using digital delay on the hi-hat?", answer: "Recording the drums with extreme separation, using the elevator shaft for natural reverb and AMS delay on individual drum hits", acceptableAnswers: ["Elevator shaft reverb", "AMS delay on drums", "Extreme drum separation"], explanation: "Hannett's obsessive production alienated the band but created Unknown Pleasures' signature cavernous, haunted sound." },
      { id: "jdn_600_03", categoryId: "mu_joy_div", tier: 600, prompt: "What specific astronomical source produced the radio signal plotted on the Unknown Pleasures cover, and who originally published the data?", answer: "Pulsar CP 1919 (PSR B1919+21), first published by Harold Craft in his 1970 PhD thesis at Cornell", acceptableAnswers: ["CP 1919", "PSR B1919+21", "Harold Craft's thesis"], explanation: "Peter Saville found the image in the Cambridge Encyclopedia of Astronomy; it originated from Harold Craft's doctoral research on pulsar emissions." }
    ]
  },
  {
    id: "mu_tool",
    group: "Music",
    name: "Tool",
    culture: "american",
    description: "The progressive metal band known for complex time signatures, visual art, and 13-year album gaps",
    imageUrl: "",
    questions: [
      { id: "tol_200_01", categoryId: "mu_tool", tier: 200, prompt: "What 2001 album containing 'Schism' and 'Lateralus' is widely considered Tool's masterpiece?", answer: "Lateralus", explanation: "Lateralus reached #1 on the Billboard 200 and is celebrated for its musical complexity and philosophical depth." },
      { id: "tol_200_02", categoryId: "mu_tool", tier: 200, prompt: "Who is Tool's lead singer, also known for fronting A Perfect Circle and Puscifer?", answer: "Maynard James Keenan", acceptableAnswers: ["Maynard James Keenan", "Maynard Keenan", "MJK"], explanation: "Keenan is unique in maintaining three simultaneous musical projects while also running a successful winery." },
      { id: "tol_200_03", categoryId: "mu_tool", tier: 200, prompt: "How many years did fans wait between 10,000 Days (2006) and Fear Inoculum (2019)?", answer: "13 years", acceptableAnswers: ["13", "13 years", "Thirteen years"], explanation: "The 13-year gap between albums became legendary, with fans creating elaborate theories about the delay." },
      { id: "tol_400_01", categoryId: "mu_tool", tier: 400, prompt: "What mathematical sequence is embedded in the time signatures of the title track 'Lateralus'?", answer: "The Fibonacci sequence", acceptableAnswers: ["Fibonacci sequence", "Fibonacci", "The Fibonacci sequence"], explanation: "The syllable counts in Maynard's lyrics follow the Fibonacci sequence (1,1,2,3,5,8,13), and the time signatures shift between 9/8, 8/8, and 7/8 in Fibonacci patterns." },
      { id: "tol_400_02", categoryId: "mu_tool", tier: 400, prompt: "What artist creates Tool's album artwork, music videos, and stage visuals, known for his anatomical and surrealist style?", answer: "Alex Grey", acceptableAnswers: ["Alex Grey"], explanation: "Alex Grey's visionary art — featuring transparent bodies with visible energy systems — became inseparable from Tool's identity." },
      { id: "tol_400_03", categoryId: "mu_tool", tier: 400, prompt: "What concept album tells the story of a person's emotional journey through the five stages of grief after a loss?", answer: "10,000 Days (referencing the approximate duration of his mother's paralysis/illness)", acceptableAnswers: ["10,000 Days"], explanation: "10,000 Days (approximately 27 years) refers to the length of time Maynard's mother Judith Marie lived with paralysis before dying." },
      { id: "tol_600_01", categoryId: "mu_tool", tier: 600, prompt: "What specific polyrhythmic technique does drummer Danny Carey use in 'Pneuma' where his limbs each play in different time signatures simultaneously?", answer: "Polymetric independence — playing in 7 with one hand, 4 with the other, and a different pattern with feet", acceptableAnswers: ["Polymetric independence", "Limb independence in different meters", "Polyrhythmic limb independence"], explanation: "Carey's ability to independently coordinate four limbs in different time signatures makes him one of rock's most technically accomplished drummers." },
      { id: "tol_600_02", categoryId: "mu_tool", tier: 600, prompt: "What hidden track on Lateralus is created by rearranging the album's track order according to the Fibonacci sequence (the 'Holy Gift' theory)?", answer: "The 'Holy Gift' resequencing — tracks reordered as 6,7,5,8,4,9,13,1,12,2,11,3,10 reveal thematic connections", acceptableAnswers: ["The Holy Gift", "Holy Gift resequencing"], explanation: "Fans discovered that reordering Lateralus tracks by Fibonacci sequence creates new thematic connections and musical flow, though the band never confirmed it was intentional." },
      { id: "tol_600_03", categoryId: "mu_tool", tier: 600, prompt: "What specific tuning does Adam Jones use on most Tool songs, and how does it differ from standard guitar tuning?", answer: "Drop D (DADGBE) and Drop B, using heavy gauge strings for extended low-end range", acceptableAnswers: ["Drop D", "Drop D tuning", "DADGBE"], explanation: "Jones primarily uses Drop D tuning with occasional lower tunings, paired with a specific signal chain of Diezel amps and minimal effects." }
    ]
  },
  {
    id: "vg_subnautica",
    group: "Video Games",
    name: "Subnautica",
    culture: "universal",
    description: "The underwater survival game on an alien ocean planet that turns beauty into terror",
    imageUrl: "",
    questions: [
      { id: "sub_200_01", categoryId: "vg_subnautica", tier: 200, prompt: "What is the name of the spacecraft that crashes on Planet 4546B at the beginning of the game?", answer: "The Aurora", acceptableAnswers: ["Aurora", "The Aurora"], explanation: "The Aurora's crash landing strands the player on an alien ocean world, and the ship's wreckage becomes a key exploration site." },
      { id: "sub_200_02", categoryId: "vg_subnautica", tier: 200, prompt: "What massive predator patrols the edges of the map and is the most feared creature in the game?", answer: "Reaper Leviathan", acceptableAnswers: ["Reaper Leviathan", "Reaper", "The Reaper"], explanation: "The Reaper Leviathan's distant roars and ability to grab your submarine made it one of gaming's most terrifying creatures." },
      { id: "sub_200_03", categoryId: "vg_subnautica", tier: 200, prompt: "What bacterial infection affects the player and all native life on the planet?", answer: "Kharaa / the Kharaa bacterium", acceptableAnswers: ["Kharaa", "Kharaa bacterium", "The infection"], explanation: "The Kharaa bacterium is a deadly alien plague that has wiped out previous civilizations and drives the main plot." },
      { id: "sub_400_01", categoryId: "vg_subnautica", tier: 400, prompt: "What ancient alien race built the massive facilities found deep underwater, including the Disease Research Facility?", answer: "The Precursors / Architects", acceptableAnswers: ["Precursors", "The Precursors", "Architects"], explanation: "The Precursors came to 4546B to research Kharaa and built massive facilities, including the gun that shoots down any ships trying to leave." },
      { id: "sub_400_02", categoryId: "vg_subnautica", tier: 400, prompt: "What giant creature in the deepest biome is revealed to be friendly and helps cure the player?", answer: "Sea Emperor Leviathan", acceptableAnswers: ["Sea Emperor", "Sea Emperor Leviathan", "The Sea Emperor"], explanation: "The Sea Emperor Leviathan has been imprisoned by the Precursors and produces Enzyme 42, the cure for Kharaa." },
      { id: "sub_400_03", categoryId: "vg_subnautica", tier: 400, prompt: "What is the name of the deepest biome in the game, a volcanic area near the planet's core?", answer: "Lava Zone / Inactive Lava Zone / Active Lava Zone", acceptableAnswers: ["Lava Zone", "Inactive Lava Zone", "Active Lava Zone", "The Lava Zone"], explanation: "The Lava Zones contain the Primary Containment Facility and the Sea Emperor, requiring a Cyclops and PRAWN suit to reach safely." },
      { id: "sub_600_01", categoryId: "vg_subnautica", tier: 600, prompt: "What is the exact depth in meters of the deepest explorable point in the base game, located in the Active Lava Zone?", answer: "Approximately 1700 meters", acceptableAnswers: ["1700 meters", "1700m", "About 1700 meters"], explanation: "The Active Lava Zone bottoms out around 1700m depth, where the Primary Containment Facility houses the Sea Emperor." },
      { id: "sub_600_02", categoryId: "vg_subnautica", tier: 600, prompt: "What is Enzyme 42, and why can only the Sea Emperor produce it?", answer: "A unique enzyme that cures Kharaa; only the Sea Emperor's biology can synthesize it due to its ancient evolutionary adaptation", acceptableAnswers: ["Enzyme that cures Kharaa", "Kharaa cure enzyme", "The cure produced only by Sea Emperor"], explanation: "Enzyme 42 breaks down the Kharaa bacterium, and the Sea Emperor's unique biology — evolved over thousands of years — is the only source." },
      { id: "sub_600_03", categoryId: "vg_subnautica", tier: 600, prompt: "What is the significance of the Degasi crew's three bases, and how do their locations represent the escalating conflict between Bart, Marguerit, and Paul Torgal?", answer: "The three bases (island surface, Jellyshroom Cave, Deep Grand Reef) show their descent deeper as Marguerit pushed for exploration while Paul wanted safety, with Bart caught between them", acceptableAnswers: ["Three bases showing escalating conflict", "Descent from island to deep reef", "Marguerit vs Paul conflict through base locations"], explanation: "Each Degasi base goes deeper and more dangerous, mirroring the crew's deteriorating relationships and Marguerit's reckless drive to explore." }
    ]
  },
  {
    id: "vg_outer_wilds_d",
    group: "Video Games",
    name: "Outer Wilds (Deep Cut)",
    culture: "universal",
    description: "The time-loop space exploration mystery — for those who've solved it all",
    imageUrl: "",
    questions: [
      { id: "owd_200_01", categoryId: "vg_outer_wilds_d", tier: 200, prompt: "What species are the player character and the other travelers in Outer Wilds?", answer: "Hearthians", acceptableAnswers: ["Hearthians", "Hearthian"], explanation: "The Hearthians are a four-eyed amphibian species who built a space program using wooden ships and determination." },
      { id: "owd_200_02", categoryId: "vg_outer_wilds_d", tier: 200, prompt: "What event causes the time loop that resets every 22 minutes?", answer: "The sun goes supernova / explodes", acceptableAnswers: ["Sun explodes", "Supernova", "The sun goes supernova", "Sun supernova"], explanation: "Every loop ends with the sun exploding, killing the player and resetting time — the central mystery is discovering why." },
      { id: "owd_200_03", categoryId: "vg_outer_wilds_d", tier: 200, prompt: "What ancient alien species left ruins and writings throughout the solar system?", answer: "The Nomai", acceptableAnswers: ["Nomai", "The Nomai"], explanation: "The Nomai were brilliant, curious aliens whose writings guide the player to understand the nature of the universe and the time loop." },
      { id: "owd_400_01", categoryId: "vg_outer_wilds_d", tier: 400, prompt: "What is the Ash Twin Project and what role does it play in the time loop?", answer: "A Nomai facility on Ash Twin that sends memories back in time using the energy of the supernova, creating the time loop", acceptableAnswers: ["Sends memories back in time", "Memory projection using supernova", "Nomai facility creating the loop"], explanation: "The Ash Twin Project harnesses the supernova's energy to send the player's memories back 22 minutes, creating the subjective experience of a time loop." },
      { id: "owd_400_02", categoryId: "vg_outer_wilds_d", tier: 400, prompt: "What is the Eye of the Universe, and why were the Nomai searching for it?", answer: "An ancient signal older than the universe itself that the Nomai detected and traveled to this solar system to find", acceptableAnswers: ["Signal older than the universe", "Ancient signal the Nomai tracked", "Quantum signal predating the universe"], explanation: "The Eye of the Universe sent a signal predating the Big Bang, and the Nomai's entire journey to this solar system was to locate and understand it." },
      { id: "owd_400_03", categoryId: "vg_outer_wilds_d", tier: 400, prompt: "What happens to Dark Bramble's interior that makes it larger on the inside than the outside?", answer: "It exists in a pocket of warped spacetime / non-Euclidean space where interior dimensions exceed exterior ones", acceptableAnswers: ["Non-Euclidean space", "Larger on the inside", "Warped spacetime"], explanation: "Dark Bramble's seeds contain pocket dimensions larger than the seed itself, creating a terrifying labyrinth infested with anglerfish." },
      { id: "owd_600_01", categoryId: "vg_outer_wilds_d", tier: 600, prompt: "What specific quantum mechanic rule governs the Quantum Moon — why does it change position when you look away?", answer: "It exists in superposition across all planets simultaneously and collapses to one location only when observed, following the game's quantum observation rules", acceptableAnswers: ["Quantum superposition", "Collapses when observed", "Superposition across all planets"], explanation: "The Quantum Moon orbits all planets simultaneously until observed, at which point it 'collapses' to one position — a game mechanic mirroring real quantum physics." },
      { id: "owd_600_02", categoryId: "vg_outer_wilds_d", tier: 600, prompt: "What is the significance of the 'sixth location' of the Quantum Moon, and what do you find there?", answer: "The Eye of the Universe — reaching the Quantum Moon's sixth location (orbiting the Eye) reveals the Nomai Solanum and confirms the Eye's existence", acceptableAnswers: ["The Eye of the Universe", "Sixth location orbits the Eye", "Solanum at the Eye"], explanation: "By reaching the Quantum Moon's sixth location, you meet Solanum, a Nomai who exists in quantum superposition, and confirm the Eye of the Universe is real." },
      { id: "owd_600_03", categoryId: "vg_outer_wilds_d", tier: 600, prompt: "In the Echoes of the Eye DLC, what is the Stranger, and what secret were the Owlks trying to hide from the universe?", answer: "A cloaked ringworld hiding a device that blocked the Eye's signal; the Owlks feared the Eye would end the universe and tried to prevent anyone from reaching it", acceptableAnswers: ["Cloaked ringworld blocking the Eye's signal", "Owlks blocking the Eye", "Device to block Eye signal"], explanation: "The Owlks built a signal blocker after seeing a vision of the universe ending at the Eye, then sealed themselves in a virtual afterlife to guard their secret forever." }
    ]
  },
  {
    id: "mv_horror_mod",
    group: "Movies",
    name: "Modern Horror Cinema",
    culture: "universal",
    description: "The elevated horror renaissance from Hereditary to The Witch and beyond",
    imageUrl: "",
    questions: [
      { id: "mhc_200_01", categoryId: "mv_horror_mod", tier: 200, prompt: "What 2017 Jordan Peele film uses a fictional 'sunken place' to explore racial horror?", answer: "Get Out", explanation: "Get Out's 'sunken place' became a cultural metaphor, and the film earned Peele an Oscar for Best Original Screenplay." },
      { id: "mhc_200_02", categoryId: "mv_horror_mod", tier: 200, prompt: "What Ari Aster film features a family devastated by grief and a grandmother's sinister legacy?", answer: "Hereditary", explanation: "Hereditary's exploration of grief, mental illness, and supernatural horror established Aster as a major voice in the genre." },
      { id: "mhc_200_03", categoryId: "mv_horror_mod", tier: 200, prompt: "What Robert Eggers film set in 1630s New England follows a Puritan family torn apart by a witch in the woods?", answer: "The Witch (The VVitch)", acceptableAnswers: ["The Witch", "The VVitch"], explanation: "The Witch used period-accurate dialogue and slow-burn dread to create an atmosphere of genuine historical horror." },
      { id: "mhc_400_01", categoryId: "mv_horror_mod", tier: 400, prompt: "In Midsommar, what Swedish pagan festival does the group attend, and what happens to the elderly participants during the ättestupa ceremony?", answer: "They jump off a cliff to their deaths as a ritual suicide", acceptableAnswers: ["They jump off a cliff", "Ritual suicide by jumping", "Cliff jumping ritual"], explanation: "The ättestupa scene — where elders willingly leap to their deaths — is the film's most shocking set piece, rooted in Nordic folklore." },
      { id: "mhc_400_02", categoryId: "mv_horror_mod", tier: 400, prompt: "What is the name of the demon/entity that the grandmother's cult worships in Hereditary?", answer: "Paimon", acceptableAnswers: ["Paimon", "King Paimon"], explanation: "Paimon is one of the kings of Hell in demonology, and the grandmother's cult has been orchestrating events to give him a male host body." },
      { id: "mhc_400_03", categoryId: "mv_horror_mod", tier: 400, prompt: "In The Lighthouse, what object at the top of the lighthouse becomes an obsession for Robert Pattinson's character?", answer: "The light / the Fresnel lens / the lantern", acceptableAnswers: ["The light", "The lantern", "The Fresnel lens", "The lighthouse light"], explanation: "The light becomes a symbol of forbidden knowledge, power, and madness — echoing Prometheus stealing fire from the gods." },
      { id: "mhc_600_01", categoryId: "mv_horror_mod", tier: 600, prompt: "What specific camera technique did Ari Aster use for the car scene in Hereditary, and why was the decision to hold on Toni Collette's face controversial?", answer: "Staying on Toni Collette in the back seat rather than showing the accident, then holding on Alex Wolff's face in bed for an extended static shot until morning", acceptableAnswers: ["Holding on faces instead of showing accident", "Static shot through the night", "Not showing the accident directly"], explanation: "Aster's refusal to show the accident directly and instead holding on characters' faces for uncomfortable durations amplified the horror through restraint." },
      { id: "mhc_600_02", categoryId: "mv_horror_mod", tier: 600, prompt: "What specific aspect ratio and film stock did Robert Eggers use for The Lighthouse, and how did it serve the film's themes?", answer: "1.19:1 aspect ratio shot on 35mm black-and-white Kodak Double-X film stock, creating a claustrophobic near-square frame", acceptableAnswers: ["1.19:1 aspect ratio", "Near-square black and white", "1.19:1 on Double-X"], explanation: "The nearly square frame trapped viewers with the characters, while the orthochromatic-look film stock created harsh, period-appropriate contrast." },
      { id: "mhc_600_03", categoryId: "mv_horror_mod", tier: 600, prompt: "What is the 'Babadook as LGBTQ+ icon' phenomenon, and how did it originate?", answer: "Netflix accidentally categorized The Babadook under LGBTQ+ films, and the internet embraced the Babadook as a queer icon during Pride month", acceptableAnswers: ["Netflix miscategorization", "Netflix listed it as LGBTQ film", "Accidental Netflix categorization"], explanation: "The 2017 Netflix glitch spawned memes of the Babadook at Pride, which the film's director Jennifer Kent found amusing and supportive of." }
    ]
  },
  {
    id: "his_cryptography",
    group: "History & Culture",
    name: "History of Cryptography",
    culture: "universal",
    description: "From Caesar ciphers to Enigma to quantum encryption — the art of secret communication",
    imageUrl: "",
    questions: [
      { id: "cry_200_01", categoryId: "his_cryptography", tier: 200, prompt: "What ancient Roman cipher shifts each letter by a fixed number of positions in the alphabet?", answer: "Caesar cipher", acceptableAnswers: ["Caesar cipher", "Caesar shift", "Shift cipher"], explanation: "Julius Caesar reportedly used a shift of 3 to encrypt military messages, making it one of history's earliest known ciphers." },
      { id: "cry_200_02", categoryId: "his_cryptography", tier: 200, prompt: "What German encryption machine used in WWII was famously broken by Allied codebreakers at Bletchley Park?", answer: "Enigma", acceptableAnswers: ["Enigma", "Enigma machine", "The Enigma machine"], explanation: "Breaking Enigma shortened WWII by an estimated two years and saved millions of lives." },
      { id: "cry_200_03", categoryId: "his_cryptography", tier: 200, prompt: "What British mathematician led the team that broke the Enigma code and is considered the father of computer science?", answer: "Alan Turing", acceptableAnswers: ["Alan Turing", "Turing"], explanation: "Turing's work at Bletchley Park and his theoretical contributions to computing changed the course of both the war and technology." },
      { id: "cry_400_01", categoryId: "his_cryptography", tier: 400, prompt: "What type of cipher uses two different keys — one public for encryption and one private for decryption?", answer: "Public-key / asymmetric cryptography", acceptableAnswers: ["Public-key cryptography", "Asymmetric cryptography", "Public key encryption", "RSA"], explanation: "Public-key cryptography, invented in the 1970s, revolutionized secure communication and enables modern internet commerce." },
      { id: "cry_400_02", categoryId: "his_cryptography", tier: 400, prompt: "What Polish mathematicians first broke the Enigma machine before sharing their work with Britain, and what technique did they use?", answer: "Marian Rejewski, Jerzy Różycki, and Henryk Zygalski, using mathematical group theory and the 'bomba' machine", acceptableAnswers: ["Rejewski, Różycki, and Zygalski", "Polish mathematicians with the bomba", "Marian Rejewski"], explanation: "The Polish Cipher Bureau broke Enigma in 1932 using pure mathematics and shared their methods with the British and French just weeks before Germany invaded Poland." },
      { id: "cry_400_03", categoryId: "his_cryptography", tier: 400, prompt: "What ancient Spartan device used a strip of parchment wrapped around a staff of specific diameter to encode messages?", answer: "Scytale", acceptableAnswers: ["Scytale", "Skytale"], explanation: "The scytale is one of the earliest known transposition ciphers — the message was only readable when wrapped around a staff of the exact same diameter." },
      { id: "cry_600_01", categoryId: "his_cryptography", tier: 600, prompt: "What specific flaw in the Enigma machine's design — related to letter substitution — gave codebreakers a crucial advantage?", answer: "A letter could never encrypt to itself (no letter could map to itself in the output)", acceptableAnswers: ["No letter encrypts to itself", "Letter never maps to itself", "Self-reciprocal property preventing self-mapping"], explanation: "This design flaw meant codebreakers could eliminate any position where a plaintext letter matched the ciphertext letter, dramatically reducing possibilities." },
      { id: "cry_600_02", categoryId: "his_cryptography", tier: 600, prompt: "What is the significance of the Venona project, and what major Cold War espionage cases did it reveal?", answer: "A secret US/UK program that partially decrypted Soviet diplomatic communications, revealing spies including the Rosenbergs and Kim Philby", acceptableAnswers: ["Decrypted Soviet communications", "Revealed Soviet spies including Rosenbergs", "US decryption of Soviet messages"], explanation: "Venona ran from 1943-1980 and exploited Soviet reuse of one-time pad pages — a catastrophic operational error — to decrypt thousands of messages." },
      { id: "cry_600_03", categoryId: "his_cryptography", tier: 600, prompt: "What mathematical problem underlies RSA encryption's security, and why does quantum computing threaten it?", answer: "Integer factorization of large semiprimes; Shor's algorithm on a quantum computer could factor these numbers exponentially faster than classical computers", acceptableAnswers: ["Integer factorization", "Large number factorization", "Factoring semiprimes threatened by Shor's algorithm"], explanation: "RSA relies on the difficulty of factoring the product of two large primes. Shor's algorithm could break this in polynomial time, driving the push for post-quantum cryptography." }
    ]
  },
  {
    id: "sci_parasites",
    group: "Science & Nature",
    name: "Parasites & Parasitism",
    culture: "universal",
    description: "The organisms that live in, on, or at the expense of others — nature's most cunning survivors",
    imageUrl: "",
    questions: [
      { id: "par_200_01", categoryId: "sci_parasites", tier: 200, prompt: "What single-celled parasite transmitted by mosquitoes causes malaria, killing hundreds of thousands annually?", answer: "Plasmodium", acceptableAnswers: ["Plasmodium", "Plasmodium falciparum"], explanation: "Plasmodium falciparum is the deadliest of five species causing human malaria, responsible for over 600,000 deaths per year." },
      { id: "par_200_02", categoryId: "sci_parasites", tier: 200, prompt: "What common cat-associated parasite can infect humans and has been linked to behavioral changes in rodents and possibly people?", answer: "Toxoplasma gondii", acceptableAnswers: ["Toxoplasma", "Toxoplasma gondii", "Toxo"], explanation: "Toxoplasma gondii infects roughly one-third of humans worldwide and can only sexually reproduce in cat intestines." },
      { id: "par_200_03", categoryId: "sci_parasites", tier: 200, prompt: "What is the term for an organism that benefits from a host without significantly harming it?", answer: "Commensal / commensalism", acceptableAnswers: ["Commensal", "Commensalism"], explanation: "Commensalism sits on the spectrum between mutualism (both benefit) and parasitism (one benefits at the other's expense)." },
      { id: "par_400_01", categoryId: "sci_parasites", tier: 400, prompt: "What parasitic worm can grow up to 30 feet long inside the human intestine and is contracted from undercooked beef or pork?", answer: "Tapeworm (Taenia saginata or Taenia solium)", acceptableAnswers: ["Tapeworm", "Taenia", "Taenia saginata", "Taenia solium"], explanation: "Tapeworms can live in the human gut for decades, growing segments that are shed and continue the life cycle." },
      { id: "par_400_02", categoryId: "sci_parasites", tier: 400, prompt: "What is the parasitic strategy called where a parasite manipulates its host's behavior to increase its own transmission to the next host?", answer: "Parasite-induced behavioral manipulation / adaptive manipulation", acceptableAnswers: ["Behavioral manipulation", "Parasite manipulation", "Adaptive manipulation", "Host manipulation"], explanation: "Classic examples include Toxoplasma making rats attracted to cats and hairworms driving crickets to drown themselves in water." },
      { id: "par_400_03", categoryId: "sci_parasites", tier: 400, prompt: "What parasitic barnacle hijacks crabs by growing root-like tendrils throughout their body and controlling their behavior, even making male crabs care for parasite eggs?", answer: "Sacculina", acceptableAnswers: ["Sacculina", "Sacculina carcini"], explanation: "Sacculina feminizes male crabs and hijacks their reproductive behavior, making them nurture parasite egg sacs as if they were their own." },
      { id: "par_600_01", categoryId: "sci_parasites", tier: 600, prompt: "What is the Red Queen hypothesis, and how does it explain the evolutionary arms race between parasites and hosts?", answer: "Hosts and parasites must constantly evolve just to maintain their relative fitness, like running to stay in place; this may explain why sexual reproduction persists despite its costs", acceptableAnswers: ["Constant evolution to maintain fitness", "Co-evolutionary arms race", "Running in place evolution"], explanation: "Named after Alice in Wonderland's Red Queen, the hypothesis suggests parasites drive the evolution of sexual reproduction by constantly selecting against common genotypes." },
      { id: "par_600_02", categoryId: "sci_parasites", tier: 600, prompt: "How does the lancet liver fluke (Dicrocoelium dendriticum) complete its three-host life cycle, and what specific ant behavior does it induce?", answer: "It makes infected ants climb to the top of grass blades at night and clamp their jaws shut, making them more likely to be eaten by grazing cattle or sheep", acceptableAnswers: ["Ants climb grass and lock jaws", "Makes ants climb grass blades", "Ant jaw-locking on grass"], explanation: "The fluke's larval stage invades the ant's brain, specifically its subesophageal ganglion, hijacking motor control to position the ant for ingestion by the final host." },
      { id: "par_600_03", categoryId: "sci_parasites", tier: 600, prompt: "What is the hygiene hypothesis in relation to parasites, and what evidence supports the idea that some parasitic infections may prevent autoimmune diseases?", answer: "The absence of parasitic worms in modern sanitized environments may cause the immune system to overreact to self-antigens; clinical trials with Trichuris suis (pig whipworm) showed improvement in inflammatory bowel disease", acceptableAnswers: ["Absence of parasites causes autoimmune overreaction", "Helminth therapy hypothesis", "Worm absence triggers autoimmunity"], explanation: "Helminth therapy trials suggest that co-evolved parasites modulate our immune system, and their absence in developed nations correlates with rising autoimmune diseases." }
    ]
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 79 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
