#!/usr/bin/env python3
"""Insert wave 70 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_true_detective",
    group: "tv",
    name: "True Detective",
    culture: "american",
    description: "Time is a flat circle — existential crime across America's dark corners.",
    imageUrl: "",
    questions: [
      { id: "trd_200_01", categoryId: "tv_true_detective", tier: 200, prompt: "In True Detective Season 1, which two actors play the mismatched detective duo investigating ritualistic murders in Louisiana?", answer: "Matthew McConaughey and Woody Harrelson", acceptableAnswers: ["McConaughey and Harrelson"], explanation: "Their chemistry as Rust Cohle and Marty Hart defined the show." },
      { id: "trd_200_02", categoryId: "tv_true_detective", tier: 200, prompt: "What US state provides the moody bayou setting for True Detective Season 1?", answer: "Louisiana", explanation: "The Louisiana bayou landscape is practically a character in the show." },
      { id: "trd_200_03", categoryId: "tv_true_detective", tier: 200, prompt: "True Detective is an anthology series — what does this mean for its cast and story each season?", answer: "Each season has a new cast and self-contained story", acceptableAnswers: ["New cast and story each season", "Different story per season"], explanation: "Each season tackles different crimes, detectives, and settings." },
      { id: "trd_400_01", categoryId: "tv_true_detective", tier: 400, prompt: "What philosophical concept does Rust Cohle obsessively reference, suggesting that all events repeat eternally?", answer: "Eternal recurrence / 'Time is a flat circle'", acceptableAnswers: ["Time is a flat circle", "Eternal recurrence", "Nietzsche's eternal return"], explanation: "Rust's nihilistic philosophy, drawn from Nietzsche and others, permeates Season 1." },
      { id: "trd_400_02", categoryId: "tv_true_detective", tier: 400, prompt: "What is the name of the mysterious cult or conspiracy that Rust and Marty uncover behind the murders in Season 1?", answer: "The Yellow King / Carcosa cult", acceptableAnswers: ["Yellow King", "Carcosa", "The Tuttle cult"], explanation: "References to the Yellow King and Carcosa draw from Robert W. Chambers' weird fiction." },
      { id: "trd_400_03", categoryId: "tv_true_detective", tier: 400, prompt: "What is the famous six-minute tracking shot in Season 1 Episode 4 that follows Rust through a biker gang raid in a housing project?", answer: "A continuous single-take action sequence following Rust undercover through a chaotic drug raid in the projects", acceptableAnswers: ["Six-minute one-take raid", "Single take tracking shot in episode 4", "Continuous shot through the projects"], explanation: "One of TV's most acclaimed action sequences, filmed to appear as one unbroken take." },
      { id: "trd_600_01", categoryId: "tv_true_detective", tier: 600, prompt: "What literary work by Robert W. Chambers inspired the 'Yellow King' and 'Carcosa' mythology in Season 1?", answer: "The King in Yellow (1895), a collection of short stories about a play that drives readers insane", acceptableAnswers: ["The King in Yellow", "Robert Chambers' The King in Yellow"], explanation: "Chambers' weird fiction, itself influenced by Ambrose Bierce, provided the show's mythological framework." },
      { id: "trd_600_02", categoryId: "tv_true_detective", tier: 600, prompt: "What is the meaning of Rust's final line in Season 1 — 'The light's winning' — and how does it contrast with his character throughout the series?", answer: "The nihilist Rust sees hope after his near-death experience in Carcosa — it's a complete reversal of his worldview, suggesting that even the darkest philosophies can yield to human connection", acceptableAnswers: ["Nihilist finds hope", "His near-death changes his philosophy", "Reversal of his nihilism"], explanation: "The line transforms Rust from a prophet of meaninglessness to someone who found something worth believing in." },
      { id: "trd_600_03", categoryId: "tv_true_detective", tier: 600, prompt: "What narrative device structures Season 1, and how does it create dramatic irony between what Rust and Marty tell investigators and what actually happened?", answer: "The story is told through unreliable police interviews in 2012 while showing flashbacks to 1995 — the detectives are editing their stories, and the gap between testimony and truth drives the tension", acceptableAnswers: ["Unreliable narrator interviews with flashbacks", "Interview/flashback structure with unreliable narration", "Dual timeline with lying interviewees"], explanation: "The interview framing lets viewers catch the detectives lying, adding layers of distrust." },
    ],
  },
  {
    id: "tv_dark",
    group: "tv",
    name: "Dark (German Series)",
    culture: "universal",
    description: "Winden, Germany — where missing children open a time loop spanning three centuries.",
    imageUrl: "",
    questions: [
      { id: "drk_200_01", categoryId: "tv_dark", tier: 200, prompt: "What is the central mystery that begins the series when children start disappearing in the town of Winden?", answer: "Children are vanishing through a time travel portal in caves beneath the town", acceptableAnswers: ["Children disappearing through time portal", "Time travel portal in caves", "Missing children and time travel"], explanation: "The disappearances connect four families across multiple time periods." },
      { id: "drk_200_02", categoryId: "tv_dark", tier: 200, prompt: "What streaming platform produced Dark, making it one of the first major non-English Netflix originals?", answer: "Netflix", explanation: "Dark was one of Netflix's first German-language original series." },
      { id: "drk_200_03", categoryId: "tv_dark", tier: 200, prompt: "What time periods does the show primarily cycle between in Season 1?", answer: "2019, 1986, and 1953", acceptableAnswers: ["2019 1986 1953", "Present, 1986, and 1953", "Three time periods 33 years apart"], explanation: "Each cycle is 33 years apart, creating a web of connections between generations." },
      { id: "drk_400_01", categoryId: "tv_dark", tier: 400, prompt: "What is the significance of the 33-year cycle in Dark, and what astronomical event does it connect to?", answer: "Events repeat every 33 years, connected to the lunar-solar cycle where moon phases realign — this creates the windows for time travel", acceptableAnswers: ["33-year lunar-solar cycle", "Events repeat every 33 years", "Moon cycle alignment"], explanation: "The 33-year cycle is both astronomically real and central to the show's time travel mechanics." },
      { id: "drk_400_02", categoryId: "tv_dark", tier: 400, prompt: "What organization manipulates events across time periods, led by a mysterious priest?", answer: "Sic Mundus (led by Noah / Adam)", acceptableAnswers: ["Sic Mundus", "Noah's group", "Adam's organization"], explanation: "Sic Mundus Creatus Est ('Thus the world was created') operates a time machine beneath the church." },
      { id: "drk_400_03", categoryId: "tv_dark", tier: 400, prompt: "What is the bootstrap paradox that Dark repeatedly demonstrates — for example, with the letter and the time machine?", answer: "An object or information exists in a closed loop with no origin — it was sent back in time to create itself, having no original creation point", acceptableAnswers: ["Object with no origin in a time loop", "Self-creating loop", "Information that creates itself through time travel"], explanation: "Dark explores how causes and effects become circular in a deterministic time loop." },
      { id: "drk_600_01", categoryId: "tv_dark", tier: 600, prompt: "In Season 3, what is the 'origin world' and how does the series resolve the seemingly unbreakable cycle?", answer: "Jonas and Martha's alternate-world counterpart travel to the origin world to prevent the inventor Tannhaus from creating time travel — by saving his son and granddaughter from dying, they remove the motivation that creates both worlds", acceptableAnswers: ["Preventing Tannhaus from inventing time travel", "Saving Tannhaus's family to erase both worlds", "Origin world where time travel is prevented"], explanation: "The resolution erases both parallel worlds, leaving only the origin world where time travel was never invented." },
      { id: "drk_600_02", categoryId: "tv_dark", tier: 600, prompt: "What is the identity of 'Adam' and how does this revelation recontextualize the entire series?", answer: "Adam is the oldest version of Jonas Kahnwald, scarred by decades of time travel — the protagonist becomes the main antagonist", acceptableAnswers: ["Adam is old Jonas", "Jonas becomes Adam", "Oldest version of Jonas"], explanation: "The reveal that Jonas eventually becomes the scarred manipulator Adam is one of the show's biggest twists." },
      { id: "drk_600_03", categoryId: "tv_dark", tier: 600, prompt: "What is 'The Knot' in Dark's mythology, and why can't characters simply change events by traveling through time?", answer: "The Knot is the self-sustaining time loop where every action taken to prevent something actually causes it — determinism means free will is an illusion within the loop", acceptableAnswers: ["Self-sustaining time loop", "Deterministic loop where all changes cause what they try to prevent", "Predestination loop"], explanation: "Dark is rigorously deterministic — everything that happens has already happened and always will." },
    ],
  },
  {
    id: "mu_hip_hop_history",
    group: "music",
    name: "Hip-Hop History",
    culture: "american",
    description: "From block parties in the Bronx to the world's dominant genre.",
    imageUrl: "",
    questions: [
      { id: "hph_200_01", categoryId: "mu_hip_hop_history", tier: 200, prompt: "What New York City borough is considered the birthplace of hip-hop?", answer: "The Bronx", acceptableAnswers: ["Bronx", "South Bronx"], explanation: "Hip-hop emerged from block parties in the South Bronx in the 1970s." },
      { id: "hph_200_02", categoryId: "mu_hip_hop_history", tier: 200, prompt: "Who is known as the 'Godfather of Hip-Hop' for hosting the legendary block parties where the genre was born?", answer: "DJ Kool Herc", acceptableAnswers: ["Kool Herc", "Clive Campbell"], explanation: "Kool Herc's innovation of isolating and extending drum breaks created the foundation for hip-hop." },
      { id: "hph_200_03", categoryId: "mu_hip_hop_history", tier: 200, prompt: "What 1979 song by The Sugarhill Gang is widely considered the first commercially successful hip-hop single?", answer: "Rapper's Delight", acceptableAnswers: ["Rapper's Delight"], explanation: "Rapper's Delight brought hip-hop to mainstream radio and reached #36 on the Billboard Hot 100." },
      { id: "hph_400_01", categoryId: "mu_hip_hop_history", tier: 400, prompt: "What are the four traditional elements of hip-hop culture?", answer: "DJing, MCing (rapping), breaking (breakdancing), and graffiti", acceptableAnswers: ["DJing MCing breaking graffiti", "DJ MC breakdance graffiti"], explanation: "These four pillars define hip-hop as a culture, not just a music genre." },
      { id: "hph_400_02", categoryId: "mu_hip_hop_history", tier: 400, prompt: "What 1988 album by N.W.A brought West Coast gangsta rap to national attention and sparked FBI controversy?", answer: "Straight Outta Compton", explanation: "The FBI sent N.W.A a warning letter over 'F*** tha Police,' making it a free speech landmark." },
      { id: "hph_400_03", categoryId: "mu_hip_hop_history", tier: 400, prompt: "What was the East Coast-West Coast rivalry of the 1990s, and which two rappers became its most prominent figures?", answer: "A feud between East Coast (Bad Boy/Biggie) and West Coast (Death Row/Tupac) hip-hop scenes that ended with both artists murdered", acceptableAnswers: ["Biggie vs Tupac", "Notorious B.I.G. and Tupac", "2Pac and Biggie Smalls"], explanation: "The rivalry culminated in the unsolved murders of both Tupac (1996) and Biggie (1997)." },
      { id: "hph_600_01", categoryId: "mu_hip_hop_history", tier: 600, prompt: "What DJ technique did Grandmaster Flash pioneer that became fundamental to hip-hop DJing?", answer: "Quick Mix Theory — the technique of cutting, scratching, and blending between two copies of the same record to extend breaks and create new compositions", acceptableAnswers: ["Quick Mix Theory", "Cutting and scratching technique", "Punch phrasing and cutting"], explanation: "Flash turned DJing from playing records into a performance art form." },
      { id: "hph_600_02", categoryId: "mu_hip_hop_history", tier: 600, prompt: "What is the significance of the 1977 blackout in New York City to hip-hop's development?", answer: "Widespread looting during the blackout allowed aspiring DJs in the Bronx to steal DJ equipment they couldn't afford, dramatically expanding the number of hip-hop DJs and sound systems", acceptableAnswers: ["DJs looted equipment during blackout", "Stolen DJ gear spread hip-hop", "Blackout looting gave DJs equipment"], explanation: "The influx of equipment after the blackout multiplied the number of block party sound systems across the Bronx." },
      { id: "hph_600_03", categoryId: "mu_hip_hop_history", tier: 600, prompt: "What was the 'Bridge Wars' beef in 1986-87, and why was it significant for the evolution of hip-hop battles?", answer: "A lyrical war between Boogie Down Productions (South Bronx) and the Juice Crew (Queensbridge) over which borough created hip-hop — it established the diss track as a hip-hop art form", acceptableAnswers: ["BDP vs Juice Crew", "South Bronx vs Queensbridge", "KRS-One vs MC Shan bridge war"], explanation: "KRS-One's 'The Bridge Is Over' became the template for hip-hop diss tracks." },
    ],
  },
  {
    id: "mu_david_bowie",
    group: "music",
    name: "David Bowie",
    culture: "universal",
    description: "The chameleon of rock — Ziggy Stardust, the Thin White Duke, and beyond.",
    imageUrl: "",
    questions: [
      { id: "bow_200_01", categoryId: "mu_david_bowie", tier: 200, prompt: "What alien rock star persona did David Bowie create for his 1972 concept album?", answer: "Ziggy Stardust", acceptableAnswers: ["Ziggy Stardust", "Ziggy"], explanation: "The Rise and Fall of Ziggy Stardust and the Spiders from Mars defined glam rock." },
      { id: "bow_200_02", categoryId: "mu_david_bowie", tier: 200, prompt: "What 1969 David Bowie song about an astronaut became his first hit, released to coincide with the Apollo 11 Moon landing?", answer: "Space Oddity", explanation: "BBC played it during their Moon landing broadcast, launching Bowie's career." },
      { id: "bow_200_03", categoryId: "mu_david_bowie", tier: 200, prompt: "What famous physical feature gave David Bowie the appearance of having two different colored eyes?", answer: "A permanently dilated pupil from a childhood fight, making one eye appear darker", acceptableAnswers: ["Permanently dilated pupil", "Anisocoria from a fight", "Different pupil sizes"], explanation: "His friend punched him in the eye at age 15, permanently dilating his left pupil — it wasn't actually different colored irises." },
      { id: "bow_400_01", categoryId: "mu_david_bowie", tier: 400, prompt: "What trilogy of experimental albums did Bowie record in Berlin with Brian Eno in the late 1970s?", answer: "The Berlin Trilogy — Low, Heroes, and Lodger", acceptableAnswers: ["Low Heroes Lodger", "Berlin Trilogy", "Low, \"Heroes\", and Lodger"], explanation: "These albums pioneered ambient and electronic rock while Bowie recovered from addiction." },
      { id: "bow_400_02", categoryId: "mu_david_bowie", tier: 400, prompt: "What Jim Henson film did David Bowie star in as Jareth the Goblin King?", answer: "Labyrinth", acceptableAnswers: ["Labyrinth (1986)"], explanation: "Bowie's performance as the Goblin King became a cult classic beloved by generations." },
      { id: "bow_400_03", categoryId: "mu_david_bowie", tier: 400, prompt: "What is the cold, aristocratic persona Bowie adopted during his 1976 'Station to Station' era?", answer: "The Thin White Duke", acceptableAnswers: ["Thin White Duke"], explanation: "The cocaine-fueled Thin White Duke period was one of Bowie's most controversial and artistically intense." },
      { id: "bow_600_01", categoryId: "mu_david_bowie", tier: 600, prompt: "What is the connection between Bowie's final album 'Blackstar' (2016) and his death?", answer: "Blackstar was released on his 69th birthday, two days before his death from liver cancer — it's an intentional farewell album with lyrics about death and legacy that his collaborators only understood after he died", acceptableAnswers: ["Farewell album released before death", "Released on birthday, died 2 days later", "Intentional goodbye album about death"], explanation: "Bowie kept his cancer secret; Blackstar was his planned artistic farewell." },
      { id: "bow_600_02", categoryId: "mu_david_bowie", tier: 600, prompt: "What controversial statement did Bowie make in a 1976 interview arriving at Victoria Station that nearly ended his career?", answer: "He appeared to give a Nazi salute from an open-top car (though he later blamed it on his cocaine-addled Thin White Duke persona and interest in the occult)", acceptableAnswers: ["Nazi salute at Victoria Station", "Apparent Nazi salute from car", "Fascist-adjacent statements and gestures"], explanation: "The incident, combined with pro-fascism quotes during his cocaine period, haunted Bowie for years." },
      { id: "bow_600_03", categoryId: "mu_david_bowie", tier: 600, prompt: "What innovative financial instrument did David Bowie create in 1997 that was the first of its kind in the music industry?", answer: "Bowie Bonds — asset-backed securities based on future royalties from his pre-1990 catalog, raising $55 million", acceptableAnswers: ["Bowie Bonds", "Royalty-backed bonds", "Asset-backed securities from royalties"], explanation: "Bowie essentially securitized his music catalog, pioneering a financial instrument later copied across the industry." },
    ],
  },
  {
    id: "vg_dark_souls",
    group: "video_games",
    name: "Dark Souls",
    culture: "universal",
    description: "Prepare to die — the series that redefined difficulty and world design.",
    imageUrl: "",
    questions: [
      { id: "dks_200_01", categoryId: "vg_dark_souls", tier: 200, prompt: "What phrase became the unofficial tagline of the Dark Souls series, appearing in marketing materials?", answer: "Prepare to Die", acceptableAnswers: ["Prepare to Die", "Prepare to die"], explanation: "The phrase became synonymous with the game's punishing but fair difficulty." },
      { id: "dks_200_02", categoryId: "vg_dark_souls", tier: 200, prompt: "What do players lose upon death in Dark Souls that they must retrieve from their corpse?", answer: "Souls", acceptableAnswers: ["Souls", "Their souls"], explanation: "Souls serve as both currency and experience points — dying twice without recovery means they're gone." },
      { id: "dks_200_03", categoryId: "vg_dark_souls", tier: 200, prompt: "What safe areas in Dark Souls allow players to rest, level up, and refill their healing flask?", answer: "Bonfires", acceptableAnswers: ["Bonfires"], explanation: "Bonfires also respawn all enemies in the area, creating a risk-reward tension." },
      { id: "dks_400_01", categoryId: "vg_dark_souls", tier: 400, prompt: "What is the name of Dark Souls' interconnected world, and what makes its level design praised by fans?", answer: "Lordran — the entire world connects through shortcuts, elevators, and paths that loop back on themselves without loading screens", acceptableAnswers: ["Lordran", "Lordran with interconnected levels", "Interconnected world of Lordran"], explanation: "Dark Souls 1's world design, where areas connect vertically and horizontally, is considered a masterpiece of game design." },
      { id: "dks_400_02", categoryId: "vg_dark_souls", tier: 400, prompt: "What optional boss in Dark Souls is hidden behind an illusory wall in the Darkroot Garden and is tied to the DLC story?", answer: "Sif, the Great Grey Wolf (guards Artorias's grave)", acceptableAnswers: ["Sif", "Great Grey Wolf Sif"], explanation: "Sif guards the grave of Knight Artorias and must be fought to access the Abyss." },
      { id: "dks_400_03", categoryId: "vg_dark_souls", tier: 400, prompt: "What multiplayer mechanic lets other players leave glowing messages on the ground with pre-written phrases?", answer: "Soapstone messages (orange soapstone)", acceptableAnswers: ["Orange soapstone messages", "Soapstone messages", "Player messages"], explanation: "The asynchronous messaging system creates community guidance (and trolling)." },
      { id: "dks_600_01", categoryId: "vg_dark_souls", tier: 600, prompt: "What is the lore significance of 'going hollow' and how does it mirror the player's real experience?", answer: "In-lore, undead who lose purpose go hollow (mindless); in gameplay, players who give up and stop trying are 'going hollow' — the game's difficulty IS the metaphor for despair", acceptableAnswers: ["Losing purpose = going hollow, mirrors player quitting", "Hollowing = giving up, game difficulty as metaphor", "Gameplay and lore mirror each other"], explanation: "Dark Souls' genius is that its difficulty isn't separate from the story — it IS the story." },
      { id: "dks_600_02", categoryId: "vg_dark_souls", tier: 600, prompt: "What is the 'Pendant' starting gift controversy in Dark Souls, and how did director Miyazaki troll the community?", answer: "Miyazaki said in an interview he'd pick the Pendant as his starting gift; the community spent years trying to find its hidden purpose, but it does absolutely nothing — he was trolling", acceptableAnswers: ["Pendant does nothing, Miyazaki trolled fans", "Useless item Miyazaki recommended as a joke", "Community searched for years, it's useless"], explanation: "One of gaming's greatest trolls — the director sent the entire community on a wild goose chase." },
      { id: "dks_600_03", categoryId: "vg_dark_souls", tier: 600, prompt: "What is the significance of Priscilla's Painting and the Painted World of Ariamis as a meta-commentary on the game itself?", answer: "The Painted World is a hidden world within a world that you can choose to leave or stay in — Priscilla asks why you'd want to come to this cold, dark place, mirroring the question of why players enjoy Dark Souls' suffering", acceptableAnswers: ["Meta commentary on why players seek suffering", "World within a world asking why you came", "Priscilla asks why you'd come here"], explanation: "Priscilla's 'This land is peaceful, its inhabitants kind' is ironic — but also asks why we seek these challenging worlds." },
    ],
  },
  {
    id: "vg_mario_deep",
    group: "video_games",
    name: "Super Mario Deep Cuts",
    culture: "universal",
    description: "Beyond the mushroom — secrets, speedruns, and Mario lore the casual player never sees.",
    imageUrl: "",
    questions: [
      { id: "mrd_200_01", categoryId: "vg_mario_deep", tier: 200, prompt: "What is the name of Mario's brother who is taller and wears green?", answer: "Luigi", explanation: "Luigi has been Mario's sidekick since the original Mario Bros. arcade game." },
      { id: "mrd_200_02", categoryId: "vg_mario_deep", tier: 200, prompt: "What power-up makes Mario grow bigger and allows him to break bricks?", answer: "Super Mushroom", acceptableAnswers: ["Mushroom", "Super Mushroom", "Red mushroom"], explanation: "The Super Mushroom has been a staple since the original Super Mario Bros." },
      { id: "mrd_200_03", categoryId: "vg_mario_deep", tier: 200, prompt: "What is the name of the princess Mario is usually trying to rescue?", answer: "Princess Peach", acceptableAnswers: ["Peach", "Princess Peach", "Princess Toadstool"], explanation: "Originally called Princess Toadstool in English, she's been Peach since Mario 64." },
      { id: "mrd_400_01", categoryId: "vg_mario_deep", tier: 400, prompt: "In Super Mario 64, what is the name of the endless staircase trick that prevents players from reaching the final Bowser fight without enough stars?", answer: "The Endless Stairs — the game loops the staircase geometry using a trick that speedrunners bypass with backwards long jumps", acceptableAnswers: ["Endless Stairs", "Infinite staircase", "BLJ stairs"], explanation: "The Backwards Long Jump (BLJ) exploit lets speedrunners clip through the endless staircase with fewer stars." },
      { id: "mrd_400_02", categoryId: "vg_mario_deep", tier: 400, prompt: "What revolutionary feature made Super Mario Bros. 3 stand out from its predecessor, involving an overworld?", answer: "A world map that players navigate between levels, with branching paths and secret areas", acceptableAnswers: ["World map", "Overworld map", "Map screen between levels"], explanation: "SMB3's world map became a template for platformers for decades." },
      { id: "mrd_400_03", categoryId: "vg_mario_deep", tier: 400, prompt: "What is the 'Minus World' glitch in the original Super Mario Bros.?", answer: "A glitch in World 1-2 that sends players to 'World -1' (displayed as World  -1 with a space), an endless underwater level", acceptableAnswers: ["World -1 glitch", "Endless underwater glitch level", "World negative one"], explanation: "The Minus World is accessed by clipping through the wall at the end of World 1-2." },
      { id: "mrd_600_01", categoryId: "vg_mario_deep", tier: 600, prompt: "What is the current strategy for the Super Mario Bros. any% speedrun world record, and approximately how fast is it completed?", answer: "Under 4 minutes 55 seconds, using frame-perfect wall clips, flagpole glitches, and precise acceleration techniques that manipulate the game's sub-pixel positioning", acceptableAnswers: ["Under 5 minutes with frame-perfect tricks", "Sub-4:55 with wall clips and pixel manipulation", "Around 4:54-4:55 with precise glitches"], explanation: "The SMB1 speedrun has been optimized to near-frame-perfect levels by the community." },
      { id: "mrd_600_02", categoryId: "vg_mario_deep", tier: 600, prompt: "In Super Mario World, what are the 'Special Zone' levels, and what happens to the game's graphics after completing them?", answer: "Secret levels with names like 'Gnarly,' 'Tubular,' and 'Funky' — completing all of them changes the overworld to autumn colors and reskins enemies (Koopas become Mario-faced)", acceptableAnswers: ["Secret hard levels that change the overworld", "Special Zone changes game graphics", "Completes autumn reskin and enemy changes"], explanation: "The Special Zone contains some of the hardest levels and rewards completion with a complete visual overhaul." },
      { id: "mrd_600_03", categoryId: "vg_mario_deep", tier: 600, prompt: "What was the 'SM64 1-0 star' category, and what computational discovery finally proved whether certain stars could be skipped?", answer: "The quest to beat SM64 with zero stars using only glitches; 'parallel universes' (PUs) — exploiting how the game handles Mario's position overflowing past level boundaries — enabled movements previously thought impossible", acceptableAnswers: ["Zero star run using parallel universes", "PU movement for 0-star completion", "Parallel universe glitch for zero stars"], explanation: "Pannenkoek's 'Watch for Rolling Rocks in 0.5x A Presses' video explaining PUs became a famous meme and real CS lesson." },
    ],
  },
  {
    id: "mv_anime_films",
    group: "movies",
    name: "Anime Films",
    culture: "universal",
    description: "Studio Ghibli, Akira, and the animated films that changed cinema.",
    imageUrl: "",
    questions: [
      { id: "anf_200_01", categoryId: "mv_anime_films", tier: 200, prompt: "What Studio Ghibli film follows a girl named Chihiro who must work in a bathhouse for spirits to save her parents?", answer: "Spirited Away", acceptableAnswers: ["Spirited Away", "Sen to Chihiro no Kamikakushi"], explanation: "Spirited Away won the Academy Award for Best Animated Feature in 2003." },
      { id: "anf_200_02", categoryId: "mv_anime_films", tier: 200, prompt: "Who is the legendary animator and co-founder of Studio Ghibli, known as the 'Walt Disney of Japan'?", answer: "Hayao Miyazaki", acceptableAnswers: ["Miyazaki"], explanation: "Miyazaki's films have grossed billions and influenced animators worldwide." },
      { id: "anf_200_03", categoryId: "mv_anime_films", tier: 200, prompt: "What 1988 cyberpunk anime film set in Neo-Tokyo is considered a landmark of animation and influenced countless Western films?", answer: "Akira", explanation: "Katsuhiro Otomo's Akira helped bring anime to Western audiences." },
      { id: "anf_400_01", categoryId: "mv_anime_films", tier: 400, prompt: "What Studio Ghibli film follows a forest spirit named Totoro who befriends two young sisters in rural Japan?", answer: "My Neighbor Totoro", acceptableAnswers: ["Totoro", "My Neighbor Totoro", "Tonari no Totoro"], explanation: "Totoro became Studio Ghibli's mascot and one of anime's most recognizable characters." },
      { id: "anf_400_02", categoryId: "mv_anime_films", tier: 400, prompt: "What Makoto Shinkai film about two teenagers who swap bodies across time became the highest-grossing anime film worldwide at the time?", answer: "Your Name (Kimi no Na wa)", acceptableAnswers: ["Your Name", "Kimi no Na wa"], explanation: "Your Name earned over $380 million worldwide, breaking anime box office records." },
      { id: "anf_400_03", categoryId: "mv_anime_films", tier: 400, prompt: "In 'Princess Mononoke,' what is the central conflict between the human settlement of Iron Town and the forest spirits?", answer: "Industrialization vs nature — Lady Eboshi's iron works destroy the forest, bringing her into conflict with the wolf-raised San and the forest gods", acceptableAnswers: ["Industry vs nature", "Iron Town vs forest spirits", "Humans destroying forest vs gods"], explanation: "Miyazaki refuses to portray either side as purely evil — both have legitimate perspectives." },
      { id: "anf_600_01", categoryId: "mv_anime_films", tier: 600, prompt: "What is the 'Grave of the Fireflies' controversy regarding its pairing with 'My Neighbor Totoro' in Japanese theaters?", answer: "They were released as a double feature — audiences watched the devastating war film Grave of the Fireflies followed by the joyful Totoro, creating an extreme emotional whiplash that is considered one of the boldest programming decisions in film history", acceptableAnswers: ["Double feature with Totoro", "Shown back to back with Totoro in theaters", "Released as double bill causing emotional whiplash"], explanation: "Isao Takahata's heartbreaking war film paired with Miyazaki's gentle fantasy was deliberately jarring." },
      { id: "anf_600_02", categoryId: "mv_anime_films", tier: 600, prompt: "What is the production technique called 'limited animation' that Osamu Tezuka pioneered for TV anime, and why did it become controversial?", answer: "Using fewer frames per second (often 8-12 vs Disney's 24), holding still frames, and reusing animation cycles to reduce costs — Disney animators called it cheap, but it became anime's defining aesthetic", acceptableAnswers: ["Fewer frames and reused animation to cut costs", "Reduced frame animation technique", "Cost-saving animation with fewer frames"], explanation: "Tezuka's cost-cutting innovation became a deliberate artistic style that defines anime to this day." },
      { id: "anf_600_03", categoryId: "mv_anime_films", tier: 600, prompt: "In 'Akira,' what is the significance of the date 2019 and the Neo-Tokyo Olympics, and how did it eerily parallel real events?", answer: "The film (made in 1988) predicted that Tokyo would host the 2020 Olympics, and depicted social unrest and cancellation fears — the real 2020 Tokyo Olympics were disrupted by COVID-19", acceptableAnswers: ["Predicted 2020 Tokyo Olympics and disruption", "1988 film predicted Tokyo Olympics and social unrest", "Neo-Tokyo 2020 Olympics predicted real events"], explanation: "Akira's eerily accurate prediction of a troubled Tokyo Olympics became a viral meme in 2020." },
    ],
  },
  {
    id: "his_cold_war",
    group: "history",
    name: "The Cold War",
    culture: "universal",
    description: "Two superpowers, mutual destruction, and the world held hostage for 45 years.",
    imageUrl: "",
    questions: [
      { id: "cld_200_01", categoryId: "his_cold_war", tier: 200, prompt: "What two superpowers were the primary opponents in the Cold War?", answer: "The United States and the Soviet Union", acceptableAnswers: ["US and USSR", "USA and Soviet Union", "America and Russia"], explanation: "The Cold War lasted from roughly 1947 to 1991." },
      { id: "cld_200_02", categoryId: "his_cold_war", tier: 200, prompt: "What physical barrier divided East and West Berlin from 1961 to 1989?", answer: "The Berlin Wall", acceptableAnswers: ["Berlin Wall"], explanation: "The Wall became the most potent symbol of the Iron Curtain dividing Europe." },
      { id: "cld_200_03", categoryId: "his_cold_war", tier: 200, prompt: "What was the 'Space Race,' and what event is considered its climax?", answer: "Competition between the US and USSR for spaceflight supremacy, climaxing with the Apollo 11 Moon landing in 1969", acceptableAnswers: ["US-USSR space competition, Moon landing", "Race to the Moon", "Space competition ending with Moon landing"], explanation: "The Space Race was both a technological competition and a propaganda battle." },
      { id: "cld_400_01", categoryId: "his_cold_war", tier: 400, prompt: "What was the Cuban Missile Crisis of 1962, and why is it considered the closest the world came to nuclear war?", answer: "The USSR placed nuclear missiles in Cuba; the US imposed a naval blockade; for 13 days, nuclear war seemed imminent before Khrushchev agreed to remove the missiles", acceptableAnswers: ["Soviet missiles in Cuba, 13-day standoff", "Nuclear standoff over Cuba missiles", "USSR put nukes in Cuba, Kennedy blockaded"], explanation: "The crisis brought the world to the brink before both sides backed down." },
      { id: "cld_400_02", categoryId: "his_cold_war", tier: 400, prompt: "What doctrine stated that the US would use military force to prevent the spread of communism worldwide?", answer: "The Truman Doctrine (and later containment policy)", acceptableAnswers: ["Truman Doctrine", "Containment", "Containment policy"], explanation: "Truman's 1947 doctrine committed the US to containing communism wherever it spread." },
      { id: "cld_400_03", categoryId: "his_cold_war", tier: 400, prompt: "What was 'MAD' — the nuclear strategy that paradoxically prevented nuclear war through the threat of total annihilation?", answer: "Mutually Assured Destruction — both sides have enough nuclear weapons to destroy the other even after being attacked first, making a first strike suicidal", acceptableAnswers: ["Mutually Assured Destruction", "Both sides can destroy each other", "Nuclear deterrence through mutual destruction"], explanation: "MAD created a terrifying stability — neither side could attack without ensuring its own destruction." },
      { id: "cld_600_01", categoryId: "his_cold_war", tier: 600, prompt: "What was Operation Gladio, and how did it connect NATO to secret 'stay-behind' armies across Europe?", answer: "A NATO-backed network of secret paramilitary organizations in Western Europe, designed to conduct guerrilla warfare if the Soviets invaded — some were linked to terrorist attacks and political manipulation", acceptableAnswers: ["NATO secret armies in Europe", "Stay-behind paramilitary networks", "Secret NATO guerrilla networks"], explanation: "Gladio's existence was confirmed in 1990 by Italian PM Giulio Andreotti, shocking European politics." },
      { id: "cld_600_02", categoryId: "his_cold_war", tier: 600, prompt: "What was the 1983 Soviet nuclear false alarm incident, and which officer's decision likely prevented nuclear war?", answer: "Stanislav Petrov — a Soviet early warning officer who judged that a satellite alert showing US missile launches was a false alarm and chose not to report it up the chain, preventing a retaliatory strike", acceptableAnswers: ["Stanislav Petrov false alarm", "Petrov ignored false missile warning", "Stanislav Petrov didn't report false alarm"], explanation: "Petrov's decision to trust his judgment over the computer readout may have saved millions of lives." },
      { id: "cld_600_03", categoryId: "his_cold_war", tier: 600, prompt: "What was the Able Archer 83 exercise, and why did it nearly trigger a real Soviet nuclear response?", answer: "A NATO nuclear war simulation exercise so realistic that Soviet leadership believed it might be cover for an actual first strike — they put nuclear forces on high alert", acceptableAnswers: ["NATO exercise Soviets thought was real attack", "War game that almost triggered Soviet nuclear response", "Realistic NATO drill mistaken for real attack prep"], explanation: "Recently declassified documents show the Soviets came closer to launching than was known at the time." },
    ],
  },
  {
    id: "sci_human_body",
    group: "science",
    name: "The Human Body",
    culture: "universal",
    description: "Bones, brains, and biology — the machine you live inside.",
    imageUrl: "",
    questions: [
      { id: "hbd_200_01", categoryId: "sci_human_body", tier: 200, prompt: "What organ pumps blood throughout the entire human body?", answer: "The heart", acceptableAnswers: ["Heart", "The heart"], explanation: "The heart beats about 100,000 times per day, pumping roughly 2,000 gallons of blood." },
      { id: "hbd_200_02", categoryId: "sci_human_body", tier: 200, prompt: "How many bones are in an adult human body?", answer: "206", explanation: "Babies are born with about 270 bones; many fuse together as they grow." },
      { id: "hbd_200_03", categoryId: "sci_human_body", tier: 200, prompt: "What is the largest organ in the human body?", answer: "The skin", acceptableAnswers: ["Skin", "The skin"], explanation: "Skin covers about 20 square feet and accounts for roughly 16% of body weight." },
      { id: "hbd_400_01", categoryId: "sci_human_body", tier: 400, prompt: "What part of the brain is responsible for the 'fight or flight' response?", answer: "The amygdala", acceptableAnswers: ["Amygdala"], explanation: "The amygdala processes fear and triggers the stress response before conscious thought." },
      { id: "hbd_400_02", categoryId: "sci_human_body", tier: 400, prompt: "What is the function of the mitochondria in human cells?", answer: "They produce energy (ATP) for the cell — often called 'the powerhouse of the cell'", acceptableAnswers: ["Produce energy", "Powerhouse of the cell", "Make ATP", "Cellular energy production"], explanation: "Mitochondria convert nutrients into ATP, the energy currency of cells." },
      { id: "hbd_400_03", categoryId: "sci_human_body", tier: 400, prompt: "What is the longest nerve in the human body, running from the brain stem through the face and torso?", answer: "The vagus nerve", acceptableAnswers: ["Vagus nerve", "Vagal nerve"], explanation: "The vagus nerve controls heart rate, digestion, and many involuntary processes." },
      { id: "hbd_600_01", categoryId: "sci_human_body", tier: 600, prompt: "What is the 'gut-brain axis,' and how do the bacteria in your intestines influence your mood and mental health?", answer: "A bidirectional communication system between gut microbiota and the brain via the vagus nerve, immune system, and neurotransmitters — gut bacteria produce about 95% of the body's serotonin", acceptableAnswers: ["Gut bacteria communicate with brain", "Microbiome-brain connection via vagus nerve", "Gut produces serotonin affecting mood"], explanation: "Research increasingly shows that gut health directly impacts mental health through this axis." },
      { id: "hbd_600_02", categoryId: "sci_human_body", tier: 600, prompt: "What is 'proprioception,' and what happens to people who lose this sense?", answer: "The body's ability to sense its own position and movement without looking; without it, people cannot walk, stand, or control movements without constantly watching their limbs", acceptableAnswers: ["Body position sense", "Sensing limb position without looking", "Internal body awareness sense"], explanation: "Proprioception is sometimes called the 'sixth sense' — its loss is devastating and poorly understood." },
      { id: "hbd_600_03", categoryId: "sci_human_body", tier: 600, prompt: "What is the 'homunculus' in neuroscience, and why are the hands and lips disproportionately large in its representation?", answer: "A distorted human figure mapped onto the brain's sensory/motor cortex — hands and lips are huge because they have the most nerve endings and take up the most cortical space", acceptableAnswers: ["Brain map with proportions based on nerve density", "Cortical map showing sensory/motor nerve distribution", "Distorted body map of brain regions"], explanation: "The cortical homunculus shows how the brain allocates processing power — more nerves = more brain space." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 70 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
