#!/usr/bin/env python3
"""Insert wave 58 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_the_bear",
    group: "TV Shows",
    name: "The Bear",
    culture: "american",
    description: "A high-pressure drama following chef Carmen Berzatto as he inherits his late brother's Chicago sandwich shop and fights to transform it into something great.",
    imageUrl: "",
    questions: [
      {
        id: "tbe_200_01",
        categoryId: "tv_the_bear",
        tier: 200,
        prompt: "What is the name of the Chicago sandwich shop that Carmy inherits at the start of the series?",
        answer: "The Original Beef of Chicagoland",
        acceptableAnswers: ["Original Beef", "The Beef"],
        explanation: "The shop, known locally as 'The Beef,' is the chaotic starting point Carmy inherits from his brother Michael.",
      },
      {
        id: "tbe_200_02",
        categoryId: "tv_the_bear",
        tier: 200,
        prompt: "What is the full name of the chef played by Jeremy Allen White in The Bear?",
        answer: "Carmen Berzatto",
        acceptableAnswers: ["Carmy Berzatto", "Carmy"],
      },
      {
        id: "tbe_200_03",
        categoryId: "tv_the_bear",
        tier: 200,
        prompt: "What role does Ayo Edebiri play in The Bear?",
        answer: "Sydney Adamu",
        acceptableAnswers: ["Sydney"],
        explanation: "Sydney is a classically trained chef who becomes Carmy's sous chef and creative partner.",
      },
      {
        id: "tbe_400_01",
        categoryId: "tv_the_bear",
        tier: 400,
        prompt: "Season 1 Episode 7, titled 'Review,' is famous for being filmed almost entirely in a single continuous take. What catastrophic event drives the episode's relentless chaos?",
        answer: "A disastrous lunch service after a scathing online review floods the restaurant with customers",
        acceptableAnswers: ["a bad review causes a rush", "an overwhelming rush after a review", "viral review causes overwhelming rush"],
        explanation: "The episode follows a single relentless shift in near-real-time, widely praised as one of the best single episodes of television in recent years.",
      },
      {
        id: "tbe_400_02",
        categoryId: "tv_the_bear",
        tier: 400,
        prompt: "In Season 2, Richie is sent to stage at a fine dining restaurant in Chicago. What does he discover about himself during that experience?",
        answer: "A capacity for excellence and genuine pride in hospitality",
        acceptableAnswers: ["he finds purpose in service", "he discovers he can be excellent at his job", "he finds his purpose"],
        explanation: "Richie's arc is a fan favorite — his transformation from cynical loudmouth to someone who embraces the discipline of fine dining is the emotional core of Season 2.",
      },
      {
        id: "tbe_400_03",
        categoryId: "tv_the_bear",
        tier: 400,
        prompt: "The Season 2 episode 'Fishes' is a standalone flashback set at Christmas. Which two notable guest stars appear as members of the Berzatto family?",
        answer: "Jamie Lee Curtis and Bob Odenkirk",
        acceptableAnswers: ["Jamie Lee Curtis, Bob Odenkirk"],
        explanation: "'Fishes' is widely considered one of the best episodes of the series, depicting the toxic and loving chaos of the Berzatto family holiday.",
      },
      {
        id: "tbe_600_01",
        categoryId: "tv_the_bear",
        tier: 600,
        prompt: "The Bear set an Emmy record in 2023 when Season 1 won 10 Emmy Awards. What was controversial about the category it was submitted in?",
        answer: "It was submitted as a Comedy Series despite being widely perceived as a drama — and won 10 Emmys in that category, the most ever for a comedy in a single season",
        acceptableAnswers: ["submitted as comedy despite being a drama", "categorized as comedy", "comedy submission controversy"],
        explanation: "FX submitted The Bear as a comedy, allowing it to compete in less competitive categories. Many peers argued it was clearly a drama. The 10-Emmy haul was a record for Outstanding Comedy Series.",
      },
      {
        id: "tbe_600_02",
        categoryId: "tv_the_bear",
        tier: 600,
        prompt: "Who created The Bear, and what was his prior television writing background before developing the show?",
        answer: "Christopher Storer, who previously wrote for Ramy",
        acceptableAnswers: ["Christopher Storer", "Chris Storer"],
        explanation: "Storer was a writer and producer on Ramy before creating The Bear. The show is loosely informed by his own family's history in the restaurant business.",
      },
      {
        id: "tbe_600_03",
        categoryId: "tv_the_bear",
        tier: 600,
        prompt: "The fine dining restaurant that Carmy and Sydney work to open in Season 2 shares its name with the show itself. What is the name of the restaurant?",
        answer: "The Bear",
        acceptableAnswers: [],
        explanation: "The entire second season is structured around the opening of The Bear — a fine dining restaurant built in the space of the original sandwich shop.",
      },
    ],
  },
  {
    id: "tv_arrested_dev",
    group: "TV Shows",
    name: "Arrested Development",
    culture: "american",
    description: "Mitch Hurwitz's densely layered comedy about the Bluth family — a formerly wealthy, spectacularly dysfunctional clan struggling after patriarch George Bluth Sr. is arrested for fraud.",
    imageUrl: "",
    questions: [
      {
        id: "arv_200_01",
        categoryId: "tv_arrested_dev",
        tier: 200,
        prompt: "What is the name of the Bluth family's frozen banana stand, and what famous piece of advice does George Sr. give Michael about it?",
        answer: "There's always money in the banana stand",
        acceptableAnswers: ["always money in the banana stand"],
        explanation: "George Sr. means this literally — he had $250,000 in cash hidden inside the walls of the stand, which Michael burns down before learning the truth.",
      },
      {
        id: "arv_200_02",
        categoryId: "tv_arrested_dev",
        tier: 200,
        prompt: "Which famous filmmaker narrates Arrested Development as an omniscient documentary-style voice throughout the series?",
        answer: "Ron Howard",
        acceptableAnswers: [],
        explanation: "Ron Howard narrates and also serves as an executive producer on the series.",
      },
      {
        id: "arv_200_03",
        categoryId: "tv_arrested_dev",
        tier: 200,
        prompt: "Gob Bluth insists there is an important distinction between what he does and what street performers do. He performs 'illusions' — what word does he refuse to use?",
        answer: "Tricks",
        acceptableAnswers: ["magic tricks"],
        explanation: "'Illusion, Michael. A trick is something a whore does for money.' One of the show's most quoted lines.",
      },
      {
        id: "arv_400_01",
        categoryId: "tv_arrested_dev",
        tier: 400,
        prompt: "Tobias Fünke holds a unique professional distinction: he is the world's first what?",
        answer: "Analyst-therapist (analrapist)",
        acceptableAnswers: ["analrapist", "analyst and therapist combined"],
        explanation: "Tobias coined the portmanteau 'analrapist' for his dual credentials, printed on his business cards, to his perpetual obliviousness about how it reads.",
      },
      {
        id: "arv_400_02",
        categoryId: "tv_arrested_dev",
        tier: 400,
        prompt: "After Fox cancelled Arrested Development following Season 3, which streaming platform revived the show in 2013 for a fourth season?",
        answer: "Netflix",
        acceptableAnswers: [],
        explanation: "Netflix's Season 4 revival in 2013 was one of the earliest high-profile streaming resurrections of a cancelled network show.",
      },
      {
        id: "arv_400_03",
        categoryId: "tv_arrested_dev",
        tier: 400,
        prompt: "The Korean boy the Bluth family adopts says only one word throughout most of his appearances. What is that word, and what does it actually mean?",
        answer: "Annyong, which means 'hello' in Korean",
        acceptableAnswers: ["annyong", "hello"],
        explanation: "The family assumes 'Annyong' is his name. His real name is Hel-loh — a layered joke the show pays off seasons later.",
      },
      {
        id: "arv_600_01",
        categoryId: "tv_arrested_dev",
        tier: 600,
        prompt: "Arrested Development plants jokes that pay off episodes or seasons later. The running background joke about the Bluth stair car being difficult to park sets up what recurring visual gag?",
        answer: "Hop-ons — people hitching rides on the stairs",
        acceptableAnswers: ["hop-ons", "people hopping on the stair car"],
        explanation: "'You're gonna get some hop-ons.' The stair car joke is a masterclass in the show's visual layering, appearing consistently throughout the series.",
      },
      {
        id: "arv_600_02",
        categoryId: "tv_arrested_dev",
        tier: 600,
        prompt: "Who created Arrested Development, and on what network did it originally air before being cancelled after three seasons despite widespread critical acclaim?",
        answer: "Mitch Hurwitz; it aired on Fox",
        acceptableAnswers: ["Mitch Hurwitz on Fox", "Mitchell Hurwitz, Fox"],
        explanation: "Hurwitz's dense, rewarding comedy was notoriously underseen during its Fox run, peaking at around 4-5 million viewers before cancellation.",
      },
      {
        id: "arv_600_03",
        categoryId: "tv_arrested_dev",
        tier: 600,
        prompt: "Tobias has a condition that prevents him from ever being fully unclothed. What is this condition called in the show?",
        answer: "Never-nude",
        acceptableAnswers: ["nevernude"],
        explanation: "Tobias is a never-nude — he always wears cutoff jorts even in the shower. The show reveals there are dozens of them, referencing it as a real (absurd) condition.",
      },
    ],
  },
  {
    id: "tv_fleabag",
    group: "TV Shows",
    name: "Fleabag",
    culture: "universal",
    description: "Phoebe Waller-Bridge's darkly funny and emotionally devastating comedy about a sharp, self-destructive young woman in London dealing with grief and complicated love.",
    imageUrl: "",
    questions: [
      {
        id: "flb_200_01",
        categoryId: "tv_fleabag",
        tier: 200,
        prompt: "Fleabag features a distinctive storytelling technique where the main character looks directly at the camera and speaks to the audience. What is this technique called?",
        answer: "Breaking the fourth wall",
        acceptableAnswers: ["fourth wall breaks", "direct address"],
      },
      {
        id: "flb_200_02",
        categoryId: "tv_fleabag",
        tier: 200,
        prompt: "Who wrote and stars in Fleabag?",
        answer: "Phoebe Waller-Bridge",
        acceptableAnswers: [],
      },
      {
        id: "flb_200_03",
        categoryId: "tv_fleabag",
        tier: 200,
        prompt: "In Season 2, Fleabag falls for a man she cannot have. What is his profession?",
        answer: "Catholic priest",
        acceptableAnswers: ["a priest", "Catholic priest"],
        explanation: "Andrew Scott's 'Hot Priest' became one of television's most talked-about romantic interests of the 2010s.",
      },
      {
        id: "flb_400_01",
        categoryId: "tv_fleabag",
        tier: 400,
        prompt: "At the end of Season 2, the Priest chooses his vocation over Fleabag. In the final scene of the series, Fleabag does something she has never done before with the camera — what is it?",
        answer: "She turns away from the camera and walks off alone, no longer breaking the fourth wall",
        acceptableAnswers: ["she turns away from the camera", "she stops breaking the fourth wall", "she walks away without looking at the camera"],
        explanation: "The moment signals that Fleabag no longer needs the audience as a coping mechanism — she is finally letting herself grieve and move forward alone.",
      },
      {
        id: "flb_400_02",
        categoryId: "tv_fleabag",
        tier: 400,
        prompt: "The main character of Fleabag is never given a real name in the series. By what name is she referred to by fans and in the credits?",
        answer: "Fleabag",
        acceptableAnswers: [],
        explanation: "The deliberate withholding of her name reinforces her role as a confessor and narrator more than a conventional protagonist.",
      },
      {
        id: "flb_400_03",
        categoryId: "tv_fleabag",
        tier: 400,
        prompt: "Fleabag won 6 Emmy Awards in 2019, including Outstanding Comedy Series. Which other major Emmy did Phoebe Waller-Bridge personally win that year for the show?",
        answer: "Outstanding Lead Actress in a Comedy Series",
        acceptableAnswers: ["Lead Actress in a Comedy", "Outstanding Lead Actress"],
        explanation: "Waller-Bridge also won for Outstanding Writing for a Comedy Series, making her one of a rare group to win three Emmys in a single night.",
      },
      {
        id: "flb_600_01",
        categoryId: "tv_fleabag",
        tier: 600,
        prompt: "Before becoming a BBC/Amazon television series, Fleabag originated in what form, and where did it first premiere?",
        answer: "A one-woman stage show that premiered at the Edinburgh Festival Fringe in 2013",
        acceptableAnswers: ["Edinburgh Fringe solo show", "one-woman show at Edinburgh Fringe"],
        explanation: "Waller-Bridge performed the show solo, playing all the characters. Its success at Edinburgh led directly to the BBC commission.",
      },
      {
        id: "flb_600_02",
        categoryId: "tv_fleabag",
        tier: 600,
        prompt: "The Priest notices something unusual about Fleabag that no other character in the show does. What does he observe that reveals he is aware of her fourth wall breaks?",
        answer: "He catches her looking at the camera — he turns and looks in the same direction, asking 'What was that?'",
        acceptableAnswers: ["he sees her look at the camera", "he notices her looking away and asks about it", "he asks 'what was that'"],
        explanation: "This moment — the Priest catching Fleabag mid-break — is one of the most celebrated reveals in the series, suggesting a supernatural or spiritual awareness on his part.",
      },
      {
        id: "flb_600_03",
        categoryId: "tv_fleabag",
        tier: 600,
        prompt: "Andrew Scott's Priest became known by what fan nickname, and who coined or popularized that nickname?",
        answer: "The Hot Priest; the nickname spread virally online after the show aired, with Waller-Bridge herself embracing it",
        acceptableAnswers: ["Hot Priest", "the Hot Priest"],
        explanation: "Waller-Bridge has acknowledged she wrote the character specifically to be someone Fleabag — and the audience — would fall helplessly for, and the 'Hot Priest' label became inescapable.",
      },
    ],
  },
  {
    id: "music_fleetwood_mac",
    group: "Music",
    name: "Fleetwood Mac",
    culture: "universal",
    description: "From British blues roots to Rumours-era drama, the band whose personal chaos became platinum records.",
    imageUrl: "",
    questions: [
      {
        id: "fmc_200_01",
        categoryId: "music_fleetwood_mac",
        tier: 200,
        prompt: "What 1977 Fleetwood Mac album — recorded while all four main members were simultaneously breaking up with each other — became one of the best-selling albums of all time?",
        answer: "Rumours",
        acceptableAnswers: [],
        explanation: "Rumours sold over 40 million copies. Buckingham and Nicks had split, and John and Christine McVie were divorcing — yet they recorded together.",
      },
      {
        id: "fmc_200_02",
        categoryId: "music_fleetwood_mac",
        tier: 200,
        prompt: "Which Fleetwood Mac song went massively viral in 2020 after a video of a man longboarding while drinking cranberry juice was set to it?",
        answer: "Dreams",
        acceptableAnswers: [],
        explanation: "Nathan Apodaca's TikTok video set to 'Dreams' brought the 1977 song back to the charts globally.",
      },
      {
        id: "fmc_200_03",
        categoryId: "music_fleetwood_mac",
        tier: 200,
        prompt: "Stevie Nicks joined Fleetwood Mac in 1974 alongside which guitarist, who was hired first and brought Nicks along as a package deal?",
        answer: "Lindsey Buckingham",
        acceptableAnswers: [],
        explanation: "Fleetwood Mac approached Buckingham; he agreed only if Nicks could join as well.",
      },
      {
        id: "fmc_400_01",
        categoryId: "music_fleetwood_mac",
        tier: 400,
        prompt: "'The Chain' is the only Rumours track credited to all five members as co-writers. Which two members of the classic lineup are rarely credited as songwriters and were the unusual additions to this credit?",
        answer: "Mick Fleetwood and John McVie",
        acceptableAnswers: ["John McVie and Mick Fleetwood"],
        explanation: "Fleetwood and John McVie rarely took writing credits; 'The Chain' remains the unique exception where all five share the credit.",
      },
      {
        id: "fmc_400_02",
        categoryId: "music_fleetwood_mac",
        tier: 400,
        prompt: "Christine McVie wrote 'You Make Loving Fun' about a secret affair — not with her husband John McVie, who played bass on the track. Who was the affair with?",
        answer: "The band's lighting director",
        acceptableAnswers: ["their lighting director", "the lighting director", "Curry Grant the lighting director"],
        explanation: "Christine began an affair with the band's lighting director, Curry Grant, while still married to John McVie, and wrote the song about it — John played bass on the track without knowing.",
      },
      {
        id: "fmc_400_03",
        categoryId: "music_fleetwood_mac",
        tier: 400,
        prompt: "'Go Your Own Way' was Lindsey Buckingham's direct breakup song aimed at Stevie Nicks. What made performing it particularly painful for Nicks night after night?",
        answer: "She was required to sing backing vocals on it every night despite finding its portrayal of her humiliating",
        acceptableAnswers: ["she had to sing it every show", "she had to perform it live even though it was about her"],
        explanation: "Nicks objected to lyrics she felt misrepresented her, but as a band member she was obligated to sing harmonies on the song at every concert.",
      },
      {
        id: "fmc_600_01",
        categoryId: "music_fleetwood_mac",
        tier: 600,
        prompt: "Before Buckingham and Nicks transformed the band's sound, Fleetwood Mac was a British blues outfit. Which founding guitarist — who wrote 'Black Magic Woman' later covered by Santana — suffered a mental breakdown and left, setting the stage for all later lineup changes?",
        answer: "Peter Green",
        acceptableAnswers: [],
        explanation: "Peter Green co-founded the band in 1967 and was its original creative force. His deteriorating mental health led to his departure in 1970. Mick Fleetwood and John McVie held the band together through successive lineup shifts.",
      },
      {
        id: "fmc_600_02",
        categoryId: "music_fleetwood_mac",
        tier: 600,
        prompt: "In 2018 Lindsey Buckingham was fired from — or by his account pushed out of — Fleetwood Mac. He subsequently sued the band. Approximately how much did he sue for, and what was the outcome?",
        answer: "He sued for $14 million and settled out of court",
        acceptableAnswers: ["$14 million, settled", "14 million dollars, settled out of court"],
        explanation: "Buckingham claimed he was wrongfully fired and lost future touring income; the parties reached a private settlement.",
      },
      {
        id: "fmc_600_03",
        categoryId: "music_fleetwood_mac",
        tier: 600,
        prompt: "During the Rumours recording sessions, much of the album was tracked at which California studio — a converted facility where the band essentially lived through the chaotic sessions?",
        answer: "Record Plant",
        acceptableAnswers: ["Record Plant Sausalito", "The Record Plant"],
        explanation: "Much of Rumours was recorded at the Record Plant in Sausalito, California, where the band worked through their personal collapses. Sessions were marked by drug use, infidelity, and the simultaneous romantic breakdowns that fueled the album.",
      },
    ],
  },
  {
    id: "music_springsteen",
    group: "Music",
    name: "Bruce Springsteen",
    culture: "american",
    description: "The Boss, the E Street Band, and the New Jersey mythology behind rock's most celebrated live act.",
    imageUrl: "",
    questions: [
      {
        id: "bsp_200_01",
        categoryId: "music_springsteen",
        tier: 200,
        prompt: "Though often mistaken for a patriotic anthem, 'Born in the USA' (1984) is actually a critique of how America treated which group of veterans?",
        answer: "Vietnam veterans",
        acceptableAnswers: ["Vietnam vets"],
        explanation: "The song follows a Vietnam vet who returns home to poverty and indifference — the ironic, anthemic chorus led many listeners, including Ronald Reagan's campaign, to misread it as a celebration.",
      },
      {
        id: "bsp_200_02",
        categoryId: "music_springsteen",
        tier: 200,
        prompt: "What is the name of Bruce Springsteen's long-running backing group, whose saxophonist Clarence Clemons became one of rock's most iconic sidemen?",
        answer: "The E Street Band",
        acceptableAnswers: ["E Street Band"],
        explanation: "The E Street Band has backed Springsteen since the early 1970s; Clemons, known as 'The Big Man,' was a defining presence until his death in 2011.",
      },
      {
        id: "bsp_200_03",
        categoryId: "music_springsteen",
        tier: 200,
        prompt: "Bruce Springsteen grew up in which New Jersey town — not Long Branch where he was born — that features prominently in his mythology?",
        answer: "Freehold",
        acceptableAnswers: ["Freehold, New Jersey", "Freehold NJ"],
        explanation: "Though born in Long Branch, Springsteen was raised in Freehold, New Jersey, the working-class backdrop that shaped his songwriting.",
      },
      {
        id: "bsp_400_01",
        categoryId: "music_springsteen",
        tier: 400,
        prompt: "'Nebraska' (1982) was recorded as a home demo on a 4-track cassette recorder. How did it end up being released in that raw demo form rather than as a full band record?",
        answer: "The band recorded studio versions but they felt lifeless compared to the demos, so Springsteen released the original 4-track recordings",
        acceptableAnswers: ["the studio versions didn't capture the feel, so they released the demos", "band versions sounded wrong so the demos were released"],
        explanation: "Springsteen sent the 4-track cassette to the E Street Band to learn the songs, but every studio attempt drained the life from the material; ultimately the solo demos were deemed the definitive versions.",
      },
      {
        id: "bsp_400_02",
        categoryId: "music_springsteen",
        tier: 400,
        prompt: "In 1984, Ronald Reagan's campaign tried to use 'Born in the USA' as a campaign song after a surrogate praised it at a rally. How did Springsteen respond?",
        answer: "He publicly rejected the use and made clear the song was not a political endorsement",
        acceptableAnswers: ["he rejected it publicly", "he denied permission and spoke out against it"],
        explanation: "Springsteen took the unusual step for the era of publicly rebuking the campaign, stating the song was not available and that its message was the opposite of what Reagan's team implied.",
      },
      {
        id: "bsp_400_03",
        categoryId: "music_springsteen",
        tier: 400,
        prompt: "Critic Jon Landau wrote the famous line 'I saw rock and roll future and its name is Bruce Springsteen' after seeing him live in 1974. Landau later became Springsteen's manager. What publication did the review appear in?",
        answer: "The Real Paper",
        acceptableAnswers: ["Real Paper", "The Real Paper"],
        explanation: "Landau published the line in the Real Paper in May 1974, before Born to Run was released. He went on to co-produce Born to Run and manage Springsteen for decades.",
      },
      {
        id: "bsp_600_01",
        categoryId: "music_springsteen",
        tier: 600,
        prompt: "'Born to Run' (1975) was described as a make-or-break record because CBS Records was close to dropping Springsteen. Which future record industry titan served as recording engineer on the album, shaping its dense wall-of-sound production?",
        answer: "Jimmy Iovine",
        acceptableAnswers: [],
        explanation: "Jimmy Iovine, later the founder of Interscope Records and co-founder of Beats Electronics, served as recording engineer on Born to Run alongside producer Jon Landau and was deeply involved in shaping the album's layered sound.",
      },
      {
        id: "bsp_600_02",
        categoryId: "music_springsteen",
        tier: 600,
        prompt: "Clarence Clemons died in June 2011. When Springsteen resumed touring, which musician — a nephew of Clemons — took over saxophone duties with the E Street Band as a tribute?",
        answer: "Jake Clemons",
        acceptableAnswers: [],
        explanation: "Jake Clemons joined the E Street Band for the Wrecking Ball Tour in 2012, carrying on his uncle Clarence's saxophone role and performing the parts Clarence had made iconic.",
      },
      {
        id: "bsp_600_03",
        categoryId: "music_springsteen",
        tier: 600,
        prompt: "Springsteen is legendary for concert length — shows regularly run 3-4 hours. But he also holds an endurance record in the studio. After Darkness on the Edge of Town, he spent years and reported millions recording and scrapping material before releasing which ambitious double album in 1980?",
        answer: "The River",
        acceptableAnswers: [],
        explanation: "Springsteen poured enormous effort into The River after Darkness, scrapping multiple nearly-completed albums' worth of songs. The resulting double album — released October 1980 — is one of his most celebrated records.",
      },
    ],
  },
  {
    id: "music_abba",
    group: "Music",
    name: "ABBA",
    culture: "universal",
    description: "The Swedish pop phenomenon whose personal heartbreak, Eurovision triumph, and timeless hooks conquered the world.",
    imageUrl: "",
    questions: [
      {
        id: "abb_200_01",
        categoryId: "music_abba",
        tier: 200,
        prompt: "The name ABBA is an acronym of the four members' first names. What are those four names?",
        answer: "Agnetha, Björn, Benny, Anni-Frid",
        acceptableAnswers: ["Agnetha Bjorn Benny Anni-Frid", "Agnetha Fältskog, Björn Ulvaeus, Benny Andersson, Anni-Frid Lyngstad"],
        explanation: "Each letter corresponds to one member: Agnetha Fältskog, Björn Ulvaeus, Benny Andersson, Anni-Frid Lyngstad.",
      },
      {
        id: "abb_200_02",
        categoryId: "music_abba",
        tier: 200,
        prompt: "ABBA won the Eurovision Song Contest in 1974 representing which country, with the song 'Waterloo'?",
        answer: "Sweden",
        acceptableAnswers: [],
        explanation: "'Waterloo' won Eurovision 1974 for Sweden and launched ABBA to international fame.",
      },
      {
        id: "abb_200_03",
        categoryId: "music_abba",
        tier: 200,
        prompt: "After a 40-year hiatus, ABBA released their comeback album in 2021 alongside a virtual concert residency featuring digital versions of the band. What was the album called?",
        answer: "Voyage",
        acceptableAnswers: [],
        explanation: "Voyage was released in November 2021 and was accompanied by a London residency using photorealistic digital avatars the band called 'ABBAtars.'",
      },
      {
        id: "abb_400_01",
        categoryId: "music_abba",
        tier: 400,
        prompt: "'The Winner Takes It All' (1980) is widely understood to be Björn's song about his divorce from Agnetha, who then had to record the vocal. What has Agnetha said about the experience of singing it?",
        answer: "She has called it the most painful recording of her life",
        acceptableAnswers: ["she found it extremely painful", "she said it was the most painful recording she ever made"],
        explanation: "Björn wrote the song after their divorce and Agnetha performed the lead vocal, reportedly in tears. She has described it as one of the most emotionally devastating things she was asked to do as a performer.",
      },
      {
        id: "abb_400_02",
        categoryId: "music_abba",
        tier: 400,
        prompt: "Madonna sampled which ABBA song for her 2005 track 'Hung Up' — reportedly the first time ABBA's songwriters had ever cleared a sample of their work?",
        answer: "Gimme! Gimme! Gimme! (A Man After Midnight)",
        acceptableAnswers: ["Gimme Gimme Gimme", "Gimme! Gimme! Gimme!"],
        explanation: "Madonna's 'Hung Up' built its main hook around the synth riff from 'Gimme! Gimme! Gimme!' Björn and Benny cleared the sample, which was noted as an exceptional case given their longstanding reluctance to license their music.",
      },
      {
        id: "abb_400_03",
        categoryId: "music_abba",
        tier: 400,
        prompt: "ABBA Gold, the 1992 greatest-hits compilation, became one of the best-selling albums in history. What is remarkable about its chart performance that distinguishes it from most greatest-hits albums?",
        answer: "It has remained in charts consistently for decades after its release, regularly re-entering years after it was issued",
        acceptableAnswers: ["it stayed on charts for decades", "it has never really left the charts since 1992"],
        explanation: "ABBA Gold is a perennial chart presence — it has spent more weeks on the UK albums chart than almost any other album ever released, still appearing regularly more than 30 years after its 1992 release.",
      },
      {
        id: "abb_600_01",
        categoryId: "music_abba",
        tier: 600,
        prompt: "In the 1990s, a promoter reportedly offered ABBA approximately $1 billion to reunite for a world tour. All four members turned it down. What reason have the members most consistently cited?",
        answer: "They did not want to tarnish their legacy or disappoint fans by performing as older versions of their younger selves",
        acceptableAnswers: ["they didn't want to damage their image", "they wanted to protect their legacy", "they felt they couldn't live up to expectations"],
        explanation: "Members have cited a shared reluctance to 'ruin the memory' — Björn and Benny felt that performing the songs live decades later could not match what people remembered.",
      },
      {
        id: "abb_600_02",
        categoryId: "music_abba",
        tier: 600,
        prompt: "The Mamma Mia! stage musical premiered in 1999, but ABBA's relationship to the project was initially hands-off. How did Björn and Benny come to approve the show?",
        answer: "They attended a staged production before it opened in the West End and approved it after watching it performed",
        acceptableAnswers: ["they attended a performance and approved it afterward", "they saw it staged and gave their blessing after seeing it"],
        explanation: "Björn and Benny were not involved in developing the book but attended an early production; they were reportedly moved by how the songs were woven into the story and gave their endorsement.",
      },
      {
        id: "abb_600_03",
        categoryId: "music_abba",
        tier: 600,
        prompt: "Both couples within ABBA divorced — Björn and Agnetha in 1979, Benny and Anni-Frid in 1981. The band continued recording after both divorces but split in 1982. Was there ever a formal dissolution announcement?",
        answer: "No — there was no formal breakup announcement; the band simply stopped working together and the split was only acknowledged gradually in retrospect",
        acceptableAnswers: ["no formal announcement was ever made", "they never officially announced a breakup", "there was no official statement"],
        explanation: "ABBA never issued a press release or statement dissolving the group. Members drifted into solo careers and the collaboration quietly ended, with the breakup only confirmed retrospectively in interviews years later.",
      },
    ],
  },
  {
    id: "mv_wes_anderson",
    group: "Movies & TV",
    name: "Wes Anderson Films",
    culture: "universal",
    description: "The symmetrical, pastel-drenched world of Wes Anderson's meticulously crafted cinema.",
    imageUrl: "",
    questions: [
      {
        id: "wsa_200_01",
        categoryId: "mv_wes_anderson",
        tier: 200,
        prompt: "Wes Anderson's films are instantly recognizable for their perfectly centered, left-right balanced camera shots. What is this compositional technique called?",
        answer: "Symmetrical composition",
        acceptableAnswers: ["symmetry", "centered framing", "symmetrical framing"],
        explanation: "Anderson's obsessive use of symmetrical, head-on framing is one of his most imitated visual signatures, partially inspired by Stanley Kubrick.",
      },
      {
        id: "wsa_200_02",
        categoryId: "mv_wes_anderson",
        tier: 200,
        prompt: "Which 2014 Wes Anderson film — set in a fictional European republic and starring Ralph Fiennes as a legendary concierge — won four Academy Awards?",
        answer: "The Grand Budapest Hotel",
        acceptableAnswers: ["Grand Budapest Hotel"],
        explanation: "The film won Oscars for Production Design, Costume Design, Makeup & Hairstyling, and Original Score.",
      },
      {
        id: "wsa_200_03",
        categoryId: "mv_wes_anderson",
        tier: 200,
        prompt: "Which actor has appeared in virtually every Wes Anderson film and is practically synonymous with his ensemble casts?",
        answer: "Bill Murray",
        acceptableAnswers: ["William Murray"],
        explanation: "Bill Murray has appeared in all of Anderson's films except his debut, Bottle Rocket, making him the closest thing to a recurring Anderson mascot.",
      },
      {
        id: "wsa_400_01",
        categoryId: "mv_wes_anderson",
        tier: 400,
        prompt: "Wes Anderson frequently co-writes his screenplays. Which actor and childhood friend co-wrote Bottle Rocket, Rushmore, and The Royal Tenenbaums with Anderson before their collaboration cooled?",
        answer: "Owen Wilson",
        acceptableAnswers: ["Owen C. Wilson"],
        explanation: "Wilson and Anderson met at the University of Texas at Austin and co-wrote Anderson's first three features together. Wilson also acted in nearly all of Anderson's films.",
      },
      {
        id: "wsa_400_02",
        categoryId: "mv_wes_anderson",
        tier: 400,
        prompt: "Wes Anderson's stop-motion adaptation of 'Fantastic Mr. Fox' faced resistance from the original author's estate, partly because Anderson wasn't British. Whose estate was initially skeptical?",
        answer: "Roald Dahl's estate",
        acceptableAnswers: ["Roald Dahl", "the Dahl estate"],
        explanation: "The Dahl estate was protective of the beloved British children's author's work and initially skeptical of an American director taking on the material.",
      },
      {
        id: "wsa_400_03",
        categoryId: "mv_wes_anderson",
        tier: 400,
        prompt: "Which Wes Anderson film was the first of his to receive an Academy Award nomination for Best Original Screenplay?",
        answer: "Moonrise Kingdom",
        acceptableAnswers: [],
        explanation: "The 2012 film about two young runaways on a New England island earned Anderson and Roman Coppola their first Oscar nomination in that category.",
      },
      {
        id: "wsa_600_01",
        categoryId: "mv_wes_anderson",
        tier: 600,
        prompt: "The Grand Budapest Hotel drew heavily from the writings of a specific Austrian author whose memoir 'The World of Yesterday' Anderson has cited as a primary inspiration. Who was this author?",
        answer: "Stefan Zweig",
        acceptableAnswers: [],
        explanation: "Zweig's elegiac memoir about the vanished world of pre-WWI Europe deeply shaped the film's tone — its sense of a refined civilization lost to rising fascism.",
      },
      {
        id: "wsa_600_02",
        categoryId: "mv_wes_anderson",
        tier: 600,
        prompt: "Anderson's meticulous world-building for The Grand Budapest Hotel included designing numerous props that never appear on screen. Name one category of these unseen props he had fabricated purely for the film's internal reality.",
        answer: "Newspapers",
        acceptableAnswers: ["menus", "hotel stationery", "fake newspapers", "hotel menus", "stationery"],
        explanation: "Anderson had fully designed fake newspapers, menus, and hotel stationery created for the production, even though none of them were ever seen by the camera — purely to make the world feel real to the cast and crew.",
      },
      {
        id: "wsa_600_03",
        categoryId: "mv_wes_anderson",
        tier: 600,
        prompt: "Anderson has said The Royal Tenenbaums was a deeply personal film, with its themes of estrangement and family dysfunction drawn partly from a painful event in his own life. What was that event?",
        answer: "His breakup with his longtime girlfriend",
        acceptableAnswers: ["a breakup", "the end of a long relationship", "breaking up with his girlfriend"],
        explanation: "Anderson was processing the end of a significant romantic relationship while writing the film, which infused its portrait of disconnected, wounded family members with genuine autobiographical grief.",
      },
    ],
  },
  {
    id: "chess_history",
    group: "Games & Strategy",
    name: "Chess History & Culture",
    culture: "universal",
    description: "From ancient Indian battlefields to Cold War proxy matches and AI defeats — the rich history of the royal game.",
    imageUrl: "",
    questions: [
      {
        id: "chs_200_01",
        categoryId: "chess_history",
        tier: 200,
        prompt: "What does the word 'checkmate' literally mean, and from which language does it derive?",
        answer: "From Persian 'shah mat,' meaning 'the king is dead' or 'the king is helpless'",
        acceptableAnswers: ["the king is dead", "the king is helpless", "shah mat"],
        explanation: "The phrase traveled from Persian into Arabic and then into European languages as chess spread westward along trade and conquest routes.",
      },
      {
        id: "chs_200_02",
        categoryId: "chess_history",
        tier: 200,
        prompt: "In 1997, world chess champion Garry Kasparov was defeated in a full match by a computer for the first time. What was the name of IBM's chess-playing machine?",
        answer: "Deep Blue",
        acceptableAnswers: ["IBM Deep Blue"],
        explanation: "Deep Blue's victory was a watershed cultural moment — Kasparov publicly accused IBM of cheating, claiming some moves seemed too human to be purely algorithmic.",
      },
      {
        id: "chs_200_03",
        categoryId: "chess_history",
        tier: 200,
        prompt: "American chess prodigy Bobby Fischer defeated Soviet grandmaster Boris Spassky in 1972 in what was dubbed 'the Match of the Century.' In which city was the match played?",
        answer: "Reykjavik",
        acceptableAnswers: ["Reykjavik, Iceland", "Iceland"],
        explanation: "The match became a Cold War flashpoint. Fischer's erratic demands and behavior before and during the match became as legendary as his play.",
      },
      {
        id: "chs_400_01",
        categoryId: "chess_history",
        tier: 400,
        prompt: "Chess originated in India around the 6th century AD under what name, before traveling to Persia and then the Arab world?",
        answer: "Chaturanga",
        acceptableAnswers: ["chaturanga"],
        explanation: "Chaturanga represented the four divisions of the Indian military: infantry, cavalry, elephants, and chariots — reflected in the game's pieces. In Persia it became 'chatrang,' then 'shatranj' in Arabic.",
      },
      {
        id: "chs_400_02",
        categoryId: "chess_history",
        tier: 400,
        prompt: "The queen piece was originally far weaker — the 'vizier,' able to move only one square diagonally. Around what century did the queen become the most powerful piece on the board, and in what region?",
        answer: "The late 15th century, in Europe",
        acceptableAnswers: ["1475", "late 15th century Europe", "15th century"],
        explanation: "The queen's dramatic power upgrade happened around 1475 in Europe and is speculatively linked to the era of powerful female rulers such as Isabella of Castile. The move made chess a faster, more dynamic game.",
      },
      {
        id: "chs_400_03",
        categoryId: "chess_history",
        tier: 400,
        prompt: "Magnus Carlsen dominated world chess for a decade but withdrew from the World Championship cycle in 2022 without defending his title. What reason did he give?",
        answer: "Loss of motivation",
        acceptableAnswers: ["he lacked motivation", "he was no longer motivated to compete for the title"],
        explanation: "Carlsen stated he simply didn't feel motivated to play the grueling championship format anymore, a stunning admission from the dominant player of his generation.",
      },
      {
        id: "chs_600_01",
        categoryId: "chess_history",
        tier: 600,
        prompt: "The 'Immortal Game,' played in London in 1851 between Adolf Anderssen and Lionel Kieseritzky, is celebrated for an unprecedented sequence of sacrifices. What major pieces did Anderssen sacrifice to secure his victory?",
        answer: "Both rooks, a bishop, and his queen",
        acceptableAnswers: ["his queen, both rooks, and a bishop", "queen and both rooks and a bishop"],
        explanation: "Anderssen won with only three minor pieces remaining after giving up his most powerful material. The game was named 'immortal' by chess journalist Ernst Falkbeer.",
      },
      {
        id: "chs_600_02",
        categoryId: "chess_history",
        tier: 600,
        prompt: "Bobby Fischer forfeited his World Chess Championship title in 1975 rather than defend it. Who was the challenger he refused to play, and how did FIDE respond?",
        answer: "Anatoly Karpov; FIDE awarded Karpov the title by default when Fischer rejected the match conditions",
        acceptableAnswers: ["Anatoly Karpov", "Karpov"],
        explanation: "Fischer made a series of match condition demands that FIDE refused to meet in full. Rather than play under modified rules, he forfeited — one of the most bizarre title transfers in sports history.",
      },
      {
        id: "chs_600_03",
        categoryId: "chess_history",
        tier: 600,
        prompt: "The longest recorded official chess game was played in Belgrade in 1989 between Ivan Nikolic and Goran Arsovic. How many moves did it last, approximately how long did it take, and how did it end?",
        answer: "269 moves, approximately 20 hours, ending in a draw",
        acceptableAnswers: ["269 moves and a draw", "20 hours and a draw", "269 moves"],
        explanation: "The game prompted FIDE to introduce stricter draw rules. It ended in a draw after nearly a full day of play.",
      },
    ],
  },
  {
    id: "tv_doctor_who",
    group: "TV Shows",
    name: "Doctor Who",
    culture: "universal",
    description: "The BBC's legendary time-travel series following an alien Time Lord who explores the universe in a police box.",
    imageUrl: "",
    questions: [
      {
        id: "dwh_200_01",
        categoryId: "tv_doctor_who",
        tier: 200,
        prompt: "What is the name of the Doctor's time-traveling spacecraft, which looks like a blue British police box?",
        answer: "TARDIS",
        acceptableAnswers: ["The TARDIS"],
        explanation: "TARDIS stands for Time and Relative Dimension in Space. Its police box appearance is because the chameleon circuit broke and it got stuck in that form.",
      },
      {
        id: "dwh_200_02",
        categoryId: "tv_doctor_who",
        tier: 200,
        prompt: "On which planet was the Doctor born?",
        answer: "Gallifrey",
        acceptableAnswers: [],
        explanation: "The Doctor is a Time Lord from Gallifrey, a planet whose inhabitants can regenerate into a new body when near death.",
      },
      {
        id: "dwh_200_03",
        categoryId: "tv_doctor_who",
        tier: 200,
        prompt: "What is the name of the Doctor's iconic hand-held tool — famously useless against wood?",
        answer: "Sonic screwdriver",
        acceptableAnswers: ["the sonic screwdriver"],
        explanation: "The sonic screwdriver is the Doctor's multi-purpose gadget. One of the show's running gags is that it cannot affect wood.",
      },
      {
        id: "dwh_400_01",
        categoryId: "tv_doctor_who",
        tier: 400,
        prompt: "What biological trait distinguishes Time Lords from humans — a detail the Doctor has referenced many times on screen?",
        answer: "Two hearts",
        acceptableAnswers: ["they have two hearts", "the Doctor has two hearts"],
        explanation: "Time Lords have a binary vascular system with two hearts, a fact the show has used dramatically in many episodes.",
      },
      {
        id: "dwh_400_02",
        categoryId: "tv_doctor_who",
        tier: 400,
        prompt: "The 2007 episode 'Blink' introduced a monster that freezes into stone when observed but moves when not seen. What are these creatures called?",
        answer: "Weeping Angels",
        acceptableAnswers: ["The Weeping Angels"],
        explanation: "'Blink' is written by Steven Moffat and is frequently cited as one of the scariest episodes in the show's history. The Doctor barely appears in it.",
      },
      {
        id: "dwh_400_03",
        categoryId: "tv_doctor_who",
        tier: 400,
        prompt: "Doctor Who premiered on November 23, 1963 — the day after a major world event suppressed its viewership. What was that event?",
        answer: "The assassination of President John F. Kennedy",
        acceptableAnswers: ["JFK's assassination", "the JFK assassination", "Kennedy's assassination"],
        explanation: "The first episode was delayed 80 seconds and initially drew very low ratings because audiences were glued to news coverage of JFK's assassination the previous day.",
      },
      {
        id: "dwh_600_01",
        categoryId: "tv_doctor_who",
        tier: 600,
        prompt: "The concept of regeneration was invented out of practical necessity. Which original actor's deteriorating health forced the production to devise a way to replace the lead character in 1966?",
        answer: "William Hartnell",
        acceptableAnswers: ["Hartnell"],
        explanation: "William Hartnell, who played the First Doctor, was suffering from arteriosclerosis. Producer Innes Lloyd devised regeneration as a storytelling mechanism, with Patrick Troughton becoming the Second Doctor.",
      },
      {
        id: "dwh_600_02",
        categoryId: "tv_doctor_who",
        tier: 600,
        prompt: "The Daleks are Doctor Who's most iconic villains. Which writer created them, first appearing in the show's second serial in 1963?",
        answer: "Terry Nation",
        acceptableAnswers: [],
        explanation: "Terry Nation created the Daleks for the serial 'The Daleks' (1963-64). He retained significant rights to the characters, which complicated their use in the show over the decades.",
      },
      {
        id: "dwh_600_03",
        categoryId: "tv_doctor_who",
        tier: 600,
        prompt: "The TARDIS's exterior appearance is explained in-universe by a broken device that was supposed to make it blend into surroundings. What is the name of that broken system?",
        answer: "Chameleon circuit",
        acceptableAnswers: ["the chameleon circuit"],
        explanation: "The chameleon circuit is supposed to change the TARDIS's exterior to blend into any environment. It broke, leaving it permanently disguised as a 1960s British police box.",
      },
    ],
  },
  {
    id: "vg_minecraft_deep",
    group: "Video Games",
    name: "Minecraft (Deep Cut)",
    culture: "universal",
    description: "The best-selling video game of all time — a sandbox survival and creation game built block by block.",
    imageUrl: "",
    questions: [
      {
        id: "mcd_200_01",
        categoryId: "vg_minecraft_deep",
        tier: 200,
        prompt: "What is the name of the default player character in Minecraft, recognizable by his pixelated blue shirt?",
        answer: "Steve",
        acceptableAnswers: [],
        explanation: "Steve is the default player skin in Minecraft. A second default skin, Alex, was added in 2014 with a slightly slimmer arm model.",
      },
      {
        id: "mcd_200_02",
        categoryId: "vg_minecraft_deep",
        tier: 200,
        prompt: "What is the name of the green, hissing creature that silently sneaks up on players and explodes?",
        answer: "Creeper",
        acceptableAnswers: ["A Creeper"],
        explanation: "The Creeper is one of gaming's most recognizable enemies and Minecraft's unofficial mascot. It has no arms and explodes when close to a player.",
      },
      {
        id: "mcd_200_03",
        categoryId: "vg_minecraft_deep",
        tier: 200,
        prompt: "Which company originally created Minecraft before Microsoft acquired it for $2.5 billion in 2014?",
        answer: "Mojang",
        acceptableAnswers: ["Mojang Studios", "Mojang AB"],
      },
      {
        id: "mcd_400_01",
        categoryId: "vg_minecraft_deep",
        tier: 400,
        prompt: "Minecraft's Creeper was famously created by accident. What animal was creator Notch originally trying to model when a coding error produced the Creeper?",
        answer: "A pig",
        acceptableAnswers: ["pig"],
        explanation: "Notch accidentally swapped the height and length values while modeling a pig, creating a tall, legless creature. He kept it and added the explosion mechanic.",
      },
      {
        id: "mcd_400_02",
        categoryId: "vg_minecraft_deep",
        tier: 400,
        prompt: "Minecraft's iconic ambient soundtrack — including 'Sweden' and 'Minecraft' — was composed by a musician known by what two-character alias?",
        answer: "C418",
        acceptableAnswers: ["Daniel Rosenfeld"],
        explanation: "Daniel Rosenfeld, known as C418, composed the ambient soundtrack that defines Minecraft's atmosphere.",
      },
      {
        id: "mcd_400_03",
        categoryId: "vg_minecraft_deep",
        tier: 400,
        prompt: "Herobrine — a ghostly, white-eyed figure — is Minecraft's most famous urban legend. What recurring joke appears in nearly every Minecraft patch note as a nod to this legend?",
        answer: "Removed Herobrine",
        acceptableAnswers: ["'Removed Herobrine'", "the 'removed Herobrine' changelog entry"],
        explanation: "Despite Herobrine never existing in the game, Mojang began including 'Removed Herobrine' in official patch notes as a running joke.",
      },
      {
        id: "mcd_600_01",
        categoryId: "vg_minecraft_deep",
        tier: 600,
        prompt: "Before it was called the Nether, Minecraft's hellish underground dimension had an early internal name during development. What was it?",
        answer: "The Slip",
        acceptableAnswers: ["the Slip"],
        explanation: "The Nether was referred to as 'the Slip' during early development. It was introduced in the Halloween Update of 2010.",
      },
      {
        id: "mcd_600_02",
        categoryId: "vg_minecraft_deep",
        tier: 600,
        prompt: "Notch has cited four specific games as direct inspirations for Minecraft's design. Name any two of them.",
        answer: "Infiniminer and Dwarf Fortress",
        acceptableAnswers: [
          "Infiniminer",
          "RollerCoaster Tycoon",
          "Dwarf Fortress",
          "Dungeon Keeper",
          "Infiniminer and RollerCoaster Tycoon",
          "Infiniminer and Dungeon Keeper",
          "RollerCoaster Tycoon and Dwarf Fortress",
          "RollerCoaster Tycoon and Dungeon Keeper",
          "Dwarf Fortress and Dungeon Keeper",
          "Infiniminer and Dwarf Fortress",
        ],
        explanation: "Notch has cited Infiniminer (for the block-mining concept), RollerCoaster Tycoon, Dwarf Fortress, and Dungeon Keeper as key inspirations for Minecraft.",
      },
      {
        id: "mcd_600_03",
        categoryId: "vg_minecraft_deep",
        tier: 600,
        prompt: "Minecraft's annual fan convention was originally called Minecon before being rebranded. What is it called now?",
        answer: "Minecraft Live",
        acceptableAnswers: [],
        explanation: "Minecon ran as an in-person convention from 2010 to 2016 before evolving into the online-only Minecraft Live broadcast format, used to announce major updates.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 58 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
