#!/usr/bin/env python3
"""Insert wave 71 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_sopranos",
    group: "tv",
    name: "The Sopranos",
    culture: "american",
    description: "The show that started the golden age of TV — mob boss meets therapy couch.",
    imageUrl: "",
    questions: [
      { id: "sop_200_01", categoryId: "tv_sopranos", tier: 200, prompt: "What is the name of the New Jersey mob boss and main character of The Sopranos?", answer: "Tony Soprano", acceptableAnswers: ["Tony"], explanation: "James Gandolfini's Tony Soprano redefined the television antihero." },
      { id: "sop_200_02", categoryId: "tv_sopranos", tier: 200, prompt: "What controversial element of Tony Soprano's life drives the show's core structure — something unusual for a mob boss?", answer: "He sees a therapist / goes to therapy", acceptableAnswers: ["Therapy", "He goes to therapy", "Sees a psychiatrist"], explanation: "Tony's sessions with Dr. Jennifer Melfi frame the show's psychological depth." },
      { id: "sop_200_03", categoryId: "tv_sopranos", tier: 200, prompt: "What animal causes Tony Soprano's first panic attack, leading him to therapy?", answer: "Ducks (a family of ducks living in his pool)", acceptableAnswers: ["Ducks", "The ducks", "Ducks in his pool"], explanation: "The ducks leaving Tony's pool symbolize his fear of losing his family." },
      { id: "sop_400_01", categoryId: "tv_sopranos", tier: 400, prompt: "What is the name of Tony's volatile nephew who he grooms as a protégé throughout the series?", answer: "Christopher Moltisanti", acceptableAnswers: ["Christopher", "Chris Moltisanti", "Chrissy"], explanation: "Christopher's addiction and ambition create one of the show's most tragic arcs." },
      { id: "sop_400_02", categoryId: "tv_sopranos", tier: 400, prompt: "What is Bada Bing, and why is it a central location in the show?", answer: "A strip club that serves as the unofficial headquarters for Tony's crew", acceptableAnswers: ["Strip club / crew hangout", "Tony's strip club headquarters", "The crew's strip club meeting place"], explanation: "Bada Bing is where business gets discussed and deals get made." },
      { id: "sop_400_03", categoryId: "tv_sopranos", tier: 400, prompt: "What is the name of Tony's wife, and what internal conflict does she face throughout the series?", answer: "Carmela Soprano — she struggles with benefiting from Tony's criminal life while maintaining Catholic morality", acceptableAnswers: ["Carmela", "Carmela Soprano"], explanation: "Edie Falco's Carmela is complicit in Tony's crimes while wrestling with her conscience." },
      { id: "sop_600_01", categoryId: "tv_sopranos", tier: 600, prompt: "What happens in the final scene of The Sopranos, and why has it been debated for nearly two decades?", answer: "The screen cuts to black mid-scene while Tony sits in a diner with his family — no resolution, no music, just silence. Debate rages over whether Tony was killed or whether the cut represents the end of the audience's access to his life", acceptableAnswers: ["Cut to black", "Screen goes black mid-scene", "Abrupt black screen ending"], explanation: "Creator David Chase has hinted Tony was killed, but the ambiguity is deliberate." },
      { id: "sop_600_02", categoryId: "tv_sopranos", tier: 600, prompt: "What is the significance of the 'Members Only' jacket worn by the man in the diner during the final scene?", answer: "A man in a Members Only jacket enters the bathroom (like the Godfather assassination scene) just before the cut to black — fans believe he emerges to shoot Tony", acceptableAnswers: ["Assassin in Members Only jacket", "Man goes to bathroom like in The Godfather before Tony dies", "Godfather bathroom parallel"], explanation: "The jacket and bathroom mirror Michael Corleone's restaurant hit in The Godfather." },
      { id: "sop_600_03", categoryId: "tv_sopranos", tier: 600, prompt: "What did David Chase reveal in a 2021 interview about the controversial ending that partly resolved the decades-long debate?", answer: "He accidentally said Tony was dead, then tried to walk it back — telling the interviewer 'Well I had that death scene' before catching himself", acceptableAnswers: ["He accidentally confirmed Tony died", "Said there was a death scene then walked it back", "Slipped and said Tony died"], explanation: "Chase's slip confirmed what many fans had theorized — Tony was killed in the final scene." },
    ],
  },
  {
    id: "tv_stranger_things",
    group: "tv",
    name: "Stranger Things",
    culture: "american",
    description: "Hawkins, Indiana — Demogorgons, the Upside Down, and 80s nostalgia.",
    imageUrl: "",
    questions: [
      { id: "sth_200_01", categoryId: "tv_stranger_things", tier: 200, prompt: "What is the name of the parallel dimension that threatens Hawkins throughout the series?", answer: "The Upside Down", acceptableAnswers: ["Upside Down", "The Upside Down"], explanation: "The Upside Down is a dark mirror of the real world, filled with monsters." },
      { id: "sth_200_02", categoryId: "tv_stranger_things", tier: 200, prompt: "What is the name of the girl with telekinetic powers who escapes from a government lab?", answer: "Eleven (El)", acceptableAnswers: ["Eleven", "El", "Jane Hopper"], explanation: "Millie Bobby Brown's Eleven became the show's breakout character." },
      { id: "sth_200_03", categoryId: "tv_stranger_things", tier: 200, prompt: "What 1980s tabletop game do the kids play that mirrors the monsters they face in real life?", answer: "Dungeons & Dragons", acceptableAnswers: ["D&D", "Dungeons and Dragons", "DnD"], explanation: "The kids use D&D terminology to name and understand the real threats they encounter." },
      { id: "sth_400_01", categoryId: "tv_stranger_things", tier: 400, prompt: "What government laboratory opened the first gate to the Upside Down through experiments on children?", answer: "Hawkins National Laboratory (run by Dr. Martin Brenner)", acceptableAnswers: ["Hawkins Lab", "Hawkins National Laboratory", "The lab"], explanation: "Brenner's experiments on Eleven and other children inadvertently opened the portal." },
      { id: "sth_400_02", categoryId: "tv_stranger_things", tier: 400, prompt: "In Season 4, what is the true identity of the villain Vecna, and how does he connect to Eleven's past?", answer: "Vecna is One/Henry Creel/001 — a former test subject at Hawkins Lab who Eleven banished to the Upside Down, where he became its ruler", acceptableAnswers: ["Henry Creel / One / 001", "He's 001 from the lab", "Henry Creel banished to Upside Down"], explanation: "The reveal that Vecna was the first test subject connects all the show's mythology." },
      { id: "sth_400_03", categoryId: "tv_stranger_things", tier: 400, prompt: "What Kate Bush song experienced a massive revival after being featured in Season 4 as a way to save a character from Vecna?", answer: "Running Up That Hill (A Deal with God)", acceptableAnswers: ["Running Up That Hill", "Running Up That Hill by Kate Bush"], explanation: "The song went to #1 on multiple charts, 37 years after its original release." },
      { id: "sth_600_01", categoryId: "tv_stranger_things", tier: 600, prompt: "What is the Duffer Brothers' rule about character deaths that they followed until Season 4, and which major death broke fan expectations?", answer: "They generally protected the core kid group; Eddie Munson's death in Season 4 was devastating because he was a new character fans immediately loved who was sacrificed while the main cast survived", acceptableAnswers: ["Eddie Munson's death", "Core kids protected until Eddie died", "Eddie Munson sacrificed while mains survived"], explanation: "Eddie's heroic sacrifice while playing 'Master of Puppets' became one of the show's most emotional moments." },
      { id: "sth_600_02", categoryId: "tv_stranger_things", tier: 600, prompt: "What real-world government program inspired the Hawkins Lab experiments on children in the show?", answer: "MKUltra — the CIA's real mind control program that experimented on unwitting subjects with LSD and sensory deprivation", acceptableAnswers: ["MKUltra", "Project MKUltra", "CIA MKUltra program"], explanation: "The show explicitly references MKUltra — Eleven's mother was a real test subject in the show's lore." },
      { id: "sth_600_03", categoryId: "tv_stranger_things", tier: 600, prompt: "What is the 'Montauk Project' conspiracy theory that originally inspired Stranger Things, and how did it shape the show's early development?", answer: "A conspiracy theory about secret government experiments at Camp Hero in Montauk, NY involving time travel and psychic powers — the show was originally titled 'Montauk' and set in Long Island before moving to Indiana", acceptableAnswers: ["Montauk Project conspiracy", "Show was originally called Montauk", "Camp Hero conspiracy theory"], explanation: "The show's working title was 'Montauk' and directly drew from the Camp Hero urban legends." },
    ],
  },
  {
    id: "mu_nirvana",
    group: "music",
    name: "Nirvana",
    culture: "american",
    description: "Smells like teen spirit — grunge, angst, and the sound of a generation.",
    imageUrl: "",
    questions: [
      { id: "nir_200_01", categoryId: "mu_nirvana", tier: 200, prompt: "What 1991 Nirvana song is often credited with bringing grunge and alternative rock into the mainstream?", answer: "Smells Like Teen Spirit", explanation: "The song's music video on MTV changed the course of popular music overnight." },
      { id: "nir_200_02", categoryId: "mu_nirvana", tier: 200, prompt: "Who was the lead singer, guitarist, and primary songwriter of Nirvana?", answer: "Kurt Cobain", acceptableAnswers: ["Cobain", "Kurt"], explanation: "Cobain became the reluctant voice of Generation X." },
      { id: "nir_200_03", categoryId: "mu_nirvana", tier: 200, prompt: "What city and music scene did Nirvana emerge from?", answer: "Seattle (the grunge scene)", acceptableAnswers: ["Seattle", "Seattle grunge scene"], explanation: "Seattle's grunge scene included Nirvana, Pearl Jam, Soundgarden, and Alice in Chains." },
      { id: "nir_400_01", categoryId: "mu_nirvana", tier: 400, prompt: "What is the name of Nirvana's landmark 1991 album that contains 'Smells Like Teen Spirit,' 'Come as You Are,' and 'Lithium'?", answer: "Nevermind", explanation: "Nevermind sold over 30 million copies and knocked Michael Jackson off the #1 spot." },
      { id: "nir_400_02", categoryId: "mu_nirvana", tier: 400, prompt: "What acoustic performance show did Nirvana record in 1993 that many consider their finest performance?", answer: "MTV Unplugged in New York", acceptableAnswers: ["MTV Unplugged", "Unplugged in New York"], explanation: "The Unplugged set, released posthumously, showed Nirvana's range beyond heavy grunge." },
      { id: "nir_400_03", categoryId: "mu_nirvana", tier: 400, prompt: "Who is Nirvana's drummer who went on to found the Foo Fighters?", answer: "Dave Grohl", acceptableAnswers: ["Grohl", "Dave Grohl"], explanation: "Grohl became one of rock's biggest stars after Nirvana's end." },
      { id: "nir_600_01", categoryId: "mu_nirvana", tier: 600, prompt: "What was the original title of 'Smells Like Teen Spirit,' and what inspired the song's name?", answer: "A friend (Kathleen Hanna of Bikini Kill) spray-painted 'Kurt smells like Teen Spirit' on his wall — Teen Spirit was a deodorant brand; Kurt didn't know this and thought it was a revolutionary slogan", acceptableAnswers: ["Named after Teen Spirit deodorant", "Kathleen Hanna wrote it on his wall, it was a deodorant", "Teen Spirit deodorant graffiti"], explanation: "The accidental origin story is one of rock's greatest ironies — a revolution named after a deodorant." },
      { id: "nir_600_02", categoryId: "mu_nirvana", tier: 600, prompt: "What was the significance of Nirvana's choice to cover Lead Belly, David Bowie, and Meat Puppets during their MTV Unplugged set instead of playing their hits?", answer: "Kurt deliberately chose obscure covers and deep cuts to redirect attention to artists he admired rather than play the hits MTV wanted — it was an act of anti-commercial defiance", acceptableAnswers: ["Anti-commercial choice to highlight influences", "Refused hits to showcase lesser-known artists", "Deliberate defiance of MTV expectations"], explanation: "The setlist was a statement: Cobain used his biggest platform to promote artists he felt deserved more recognition." },
      { id: "nir_600_03", categoryId: "mu_nirvana", tier: 600, prompt: "What is 'In Utero' and how did its deliberately abrasive production by Steve Albini represent Kurt Cobain's rejection of Nevermind's commercial sound?", answer: "In Utero (1993) was intentionally harsh and unpolished — Cobain hired Steve Albini specifically to create an abrasive, uncommercial sound as a reaction against Nevermind's pop-friendly production by Butch Vig", acceptableAnswers: ["Deliberately harsh album rejecting Nevermind's polish", "Albini hired for anti-commercial sound", "Raw production as rejection of Nevermind"], explanation: "The label forced some remixing, but In Utero remained far rawer than its predecessor." },
    ],
  },
  {
    id: "mu_jazz_legends",
    group: "music",
    name: "Jazz Legends",
    culture: "universal",
    description: "Miles, Coltrane, and the art of musical freedom.",
    imageUrl: "",
    questions: [
      { id: "jzz_200_01", categoryId: "mu_jazz_legends", tier: 200, prompt: "What New Orleans-born trumpeter is often called the most important figure in jazz history and was known as 'Satchmo'?", answer: "Louis Armstrong", acceptableAnswers: ["Armstrong", "Satchmo"], explanation: "Armstrong's innovations in improvisation and vocal style shaped all of popular music." },
      { id: "jzz_200_02", categoryId: "mu_jazz_legends", tier: 200, prompt: "What US city is considered the birthplace of jazz?", answer: "New Orleans", acceptableAnswers: ["New Orleans, Louisiana"], explanation: "Jazz emerged from New Orleans' unique cultural mix of African, Caribbean, and European traditions." },
      { id: "jzz_200_03", categoryId: "mu_jazz_legends", tier: 200, prompt: "What legendary Miles Davis album, often called the best-selling jazz record of all time, features a modal approach to jazz composition?", answer: "Kind of Blue", explanation: "Kind of Blue (1959) has sold over 5 million copies and changed jazz forever." },
      { id: "jzz_400_01", categoryId: "mu_jazz_legends", tier: 400, prompt: "What style of jazz, characterized by fast tempos and complex harmonies, emerged in the 1940s as a reaction against swing?", answer: "Bebop", acceptableAnswers: ["Bebop", "Bop"], explanation: "Charlie Parker and Dizzy Gillespie pioneered bebop, transforming jazz from dance music to art music." },
      { id: "jzz_400_02", categoryId: "mu_jazz_legends", tier: 400, prompt: "What John Coltrane album, featuring extended spiritual improvisations, is considered one of the most important and influential jazz albums ever recorded?", answer: "A Love Supreme", explanation: "A Love Supreme (1964) is Coltrane's spiritual masterpiece, a four-part suite dedicated to God." },
      { id: "jzz_400_03", categoryId: "mu_jazz_legends", tier: 400, prompt: "What female jazz vocalist, known as 'The First Lady of Song,' was famous for her scat singing and perfect pitch?", answer: "Ella Fitzgerald", acceptableAnswers: ["Fitzgerald", "Ella"], explanation: "Fitzgerald's vocal range and improvisational scat singing set the standard for jazz vocalists." },
      { id: "jzz_600_01", categoryId: "mu_jazz_legends", tier: 600, prompt: "What was Miles Davis's 'electric period,' and why did it alienate jazz purists while influencing rock and funk?", answer: "Starting with 'Bitches Brew' (1970), Davis incorporated electric instruments, rock rhythms, and studio processing — jazz purists called it a betrayal, but it created jazz fusion and influenced bands like Radiohead", acceptableAnswers: ["Bitches Brew electric fusion", "Electric instruments starting with Bitches Brew", "Jazz-rock fusion era from 1970"], explanation: "Davis's refusal to look backward made him the genre's most restless innovator." },
      { id: "jzz_600_02", categoryId: "mu_jazz_legends", tier: 600, prompt: "What is 'free jazz,' who pioneered it, and why did it cause literal fistfights at performances?", answer: "Ornette Coleman pioneered free jazz — improvisation with no predetermined chord changes, melody, or tempo. Its radical abandonment of structure caused audience fights and divided the jazz world", acceptableAnswers: ["Ornette Coleman's structureless improvisation", "Coleman's free improvisation without rules", "No-structure jazz by Ornette Coleman"], explanation: "Coleman's 1960 album 'Free Jazz' gave the movement its name and remains controversial." },
      { id: "jzz_600_03", categoryId: "mu_jazz_legends", tier: 600, prompt: "What was Thelonious Monk's unique approach to piano technique that other musicians initially dismissed as incompetent?", answer: "Monk used dissonant clusters, angular melodies, and deliberate 'wrong' notes that sounded like mistakes but were precisely intentional — he'd lift his fingers flat and strike with unusual hand positions", acceptableAnswers: ["Deliberate dissonance and 'wrong' notes", "Angular playing dismissed as mistakes", "Intentional dissonant technique"], explanation: "What critics called incompetence was a revolutionary harmonic approach that influenced all modern jazz." },
    ],
  },
  {
    id: "vg_zelda_deep",
    group: "video_games",
    name: "Zelda: Ocarina & Majora",
    culture: "universal",
    description: "The Hero of Time — two legendary N64 adventures in Hyrule and Termina.",
    imageUrl: "",
    questions: [
      { id: "zom_200_01", categoryId: "vg_zelda_deep", tier: 200, prompt: "In Ocarina of Time, what instrument does Link play that gives the game its name?", answer: "The Ocarina of Time", acceptableAnswers: ["Ocarina", "The Ocarina"], explanation: "The magical ocarina allows Link to travel through time and trigger events." },
      { id: "zom_200_02", categoryId: "vg_zelda_deep", tier: 200, prompt: "In Majora's Mask, how many days does Link have before the moon crashes into Termina?", answer: "Three days", acceptableAnswers: ["3 days", "Three"], explanation: "The 72-hour time loop is the central mechanic — Link must repeatedly reset time." },
      { id: "zom_200_03", categoryId: "vg_zelda_deep", tier: 200, prompt: "What fairy companion follows Link throughout Ocarina of Time, famously saying 'Hey! Listen!'?", answer: "Navi", explanation: "Navi's persistent voice lines became one of gaming's most memorable (and annoying) features." },
      { id: "zom_400_01", categoryId: "vg_zelda_deep", tier: 400, prompt: "In Ocarina of Time, what happens when Link pulls the Master Sword from the Temple of Time?", answer: "He is sealed away for seven years and awakens as an adult, finding Hyrule transformed under Ganondorf's rule", acceptableAnswers: ["He sleeps 7 years and wakes up as an adult", "Time skips 7 years", "Ages to adult, Ganondorf rules"], explanation: "The time skip is one of gaming's most impactful narrative moments." },
      { id: "zom_400_02", categoryId: "vg_zelda_deep", tier: 400, prompt: "In Majora's Mask, what are the transformation masks, and what do they turn Link into?", answer: "Deku Mask (Deku Scrub), Goron Mask (Goron), Zora Mask (Zora) — each species has unique abilities", acceptableAnswers: ["Deku, Goron, and Zora masks", "Three species transformation masks", "Deku Goron Zora"], explanation: "Each mask represents a dead character whose spirit Link inherits." },
      { id: "zom_400_03", categoryId: "vg_zelda_deep", tier: 400, prompt: "What is the Shadow Temple in Ocarina of Time, and what dark history does it reveal about Hyrule?", answer: "A torture chamber and tomb beneath Kakariko Village that reveals Hyrule's royal family used the Sheikah as spies and executioners — it's the darkest dungeon in the game", acceptableAnswers: ["Torture chamber under Kakariko", "Hyrule's dark history of execution", "Sheikah torture/execution facility"], explanation: "The Shadow Temple's imagery of torture and death is unusually dark for a Nintendo game." },
      { id: "zom_600_01", categoryId: "vg_zelda_deep", tier: 600, prompt: "What is the widely-discussed 'Link is dead' theory about Majora's Mask, and what evidence supports it?", answer: "The theory suggests Link died in the Lost Woods and Termina represents the five stages of grief — each region maps to denial, anger, bargaining, depression, and acceptance, with the Skull Kid as death", acceptableAnswers: ["Link is dead, Termina is grief stages", "Five stages of grief theory", "Dead Link grief theory"], explanation: "While not canon, the theory explains the game's dark tone and the persistent theme of loss." },
      { id: "zom_600_02", categoryId: "vg_zelda_deep", tier: 600, prompt: "What speedrun technique in Ocarina of Time called 'Wrong Warp' allows players to skip directly to the final boss?", answer: "By performing a precise series of actions involving Blue Warps (dungeon completion portals) and Farore's Wind, players trick the game into loading the wrong destination — warping to the final Ganon fight from early dungeons", acceptableAnswers: ["Blue Warp manipulation to skip to Ganon", "Tricking warp destinations to reach final boss", "Wrong warp via Blue Warp glitch"], explanation: "Wrong Warping cut the any% speedrun time dramatically and remains the route's core trick." },
      { id: "zom_600_03", categoryId: "vg_zelda_deep", tier: 600, prompt: "In Majora's Mask, what is the Fierce Deity Mask, and what is the disturbing fan theory about its origin?", answer: "The most powerful mask, given by Majora itself before the final fight — fan theory suggests the Fierce Deity contains the combined rage and grief of everyone in Termina, making it potentially more dangerous than Majora", acceptableAnswers: ["Powerful mask from Majora, may contain Termina's combined grief", "Majora gives you a mask of collective rage", "Final mask possibly more evil than Majora"], explanation: "The Fierce Deity's unsettling blank eyes and Majora calling it 'the bad guy' fuel dark theories." },
    ],
  },
  {
    id: "mv_pixar",
    group: "movies",
    name: "Pixar Animation",
    culture: "universal",
    description: "To infinity and beyond — the studio that made computers cry.",
    imageUrl: "",
    questions: [
      { id: "pxr_200_01", categoryId: "mv_pixar", tier: 200, prompt: "What was Pixar's first feature-length film, released in 1995?", answer: "Toy Story", explanation: "Toy Story was the first entirely computer-animated feature film." },
      { id: "pxr_200_02", categoryId: "mv_pixar", tier: 200, prompt: "In 'Finding Nemo,' what type of fish is Nemo?", answer: "Clownfish", acceptableAnswers: ["Clownfish", "Ocellaris clownfish"], explanation: "Nemo is a clownfish who gets captured and taken to a fish tank in a dentist's office." },
      { id: "pxr_200_03", categoryId: "mv_pixar", tier: 200, prompt: "What Pixar film takes place inside the mind of a girl named Riley, personifying her emotions?", answer: "Inside Out", explanation: "Inside Out turned abstract emotions into compelling characters." },
      { id: "pxr_400_01", categoryId: "mv_pixar", tier: 400, prompt: "What is the 'Pixar Easter egg' tradition involving a pizza truck that appears in almost every Pixar film?", answer: "The Pizza Planet truck from Toy Story appears hidden in nearly every Pixar movie", acceptableAnswers: ["Pizza Planet truck", "Pizza Planet delivery truck"], explanation: "Along with A113 and the Luxo Ball, the Pizza Planet truck is Pixar's most famous recurring Easter egg." },
      { id: "pxr_400_02", categoryId: "mv_pixar", tier: 400, prompt: "What catastrophic technical failure almost destroyed Toy Story 2, and how was it saved?", answer: "Someone accidentally ran a command that deleted 90% of the film's files from the server; the film was saved because a technical director had a backup copy on her home computer for remote work", acceptableAnswers: ["Files deleted, saved by home backup", "Accidental deletion saved by home computer", "rm command deleted film, home backup saved it"], explanation: "Galyn Susman's home backup was the only complete copy — without it, the film would have been lost." },
      { id: "pxr_400_03", categoryId: "mv_pixar", tier: 400, prompt: "What is the number 'A113' that appears in every Pixar film, and what does it reference?", answer: "The classroom number at California Institute of the Arts (CalArts) where many Pixar and Disney animators studied", acceptableAnswers: ["CalArts classroom", "California Institute of the Arts classroom", "A113 at CalArts"], explanation: "A113 appears as license plates, room numbers, and codes across Pixar and Disney films." },
      { id: "pxr_600_01", categoryId: "mv_pixar", tier: 600, prompt: "What is the 'Pixar Braintrust,' and how does its feedback process differ from traditional studio notes?", answer: "A group of directors and storytellers who give candid feedback on films in development — crucially, the director is NOT obligated to take their advice, unlike traditional studio mandates", acceptableAnswers: ["Creative feedback group with non-binding notes", "Directors group giving optional candid feedback", "Feedback without authority to mandate changes"], explanation: "The key innovation is that feedback has no authority — the director decides what to use." },
      { id: "pxr_600_02", categoryId: "mv_pixar", tier: 600, prompt: "What is the 'Pixar theory' that connects every Pixar film into a single timeline, and what film is theorized to be the chronological endpoint?", answer: "A fan theory placing all Pixar films in one universe; Monsters, Inc. is theorized to take place in the far future where animals and objects evolved sentience (from Brave's magic) and humans are gone — the doors access past timelines", acceptableAnswers: ["Connected universe theory, Monsters Inc is the future", "All films linked, Monsters Inc as far future", "Pixar connected universe"], explanation: "Jon Negroni's theory maps an elaborate timeline from Brave (earliest) to Monsters, Inc. (latest)." },
      { id: "pxr_600_03", categoryId: "mv_pixar", tier: 600, prompt: "What was the production crisis behind 'Ratatouille' that resulted in director Brad Bird being brought in to essentially remake the film?", answer: "Original director Jan Pinkava was replaced after years of development; Brad Bird rewrote and redirected the film in a compressed timeline, keeping the rat-who-cooks concept but rebuilding virtually everything else", acceptableAnswers: ["Director replaced, Brad Bird rebuilt the film", "Jan Pinkava replaced by Brad Bird who remade it", "Director swap and complete overhaul"], explanation: "Bird's ability to rescue the troubled production while maintaining quality is considered a remarkable feat." },
    ],
  },
  {
    id: "his_world_war_2",
    group: "history",
    name: "World War II",
    culture: "universal",
    description: "The conflict that reshaped the world — 1939 to 1945.",
    imageUrl: "",
    questions: [
      { id: "ww2_200_01", categoryId: "his_world_war_2", tier: 200, prompt: "What was D-Day, and on which beaches in what country did the Allied invasion take place?", answer: "June 6, 1944 — the Allied invasion of Normandy, France across five beaches (Utah, Omaha, Gold, Juno, Sword)", acceptableAnswers: ["Normandy invasion", "June 6 1944 Normandy France", "Allied invasion of France"], explanation: "D-Day was the largest amphibious military operation in history." },
      { id: "ww2_200_02", categoryId: "his_world_war_2", tier: 200, prompt: "What event on December 7, 1941 brought the United States into World War II?", answer: "The Japanese attack on Pearl Harbor", acceptableAnswers: ["Pearl Harbor", "Attack on Pearl Harbor", "Pearl Harbor bombing"], explanation: "The surprise attack on the US naval base in Hawaii killed over 2,400 Americans." },
      { id: "ww2_200_03", categoryId: "his_world_war_2", tier: 200, prompt: "What were the two atomic bombs dropped on Japan called, and on which cities?", answer: "Little Boy on Hiroshima and Fat Man on Nagasaki", acceptableAnswers: ["Hiroshima and Nagasaki", "Little Boy and Fat Man"], explanation: "The bombings in August 1945 led to Japan's surrender and the end of the war." },
      { id: "ww2_400_01", categoryId: "his_world_war_2", tier: 400, prompt: "What was the Battle of Stalingrad, and why is it considered the turning point of the war on the Eastern Front?", answer: "A brutal 5-month battle (1942-43) where the Soviet Union surrounded and destroyed Germany's 6th Army — it was Germany's first major defeat and the beginning of their retreat", acceptableAnswers: ["Soviet victory destroying German 6th Army", "Germany's first major defeat", "5-month siege turning point"], explanation: "Stalingrad was the bloodiest battle in human history, with nearly 2 million casualties." },
      { id: "ww2_400_02", categoryId: "his_world_war_2", tier: 400, prompt: "What was the Enigma machine, and how did its breaking affect the war?", answer: "A German cipher machine used to encrypt military communications; British codebreakers at Bletchley Park (led by Alan Turing) cracked it, giving the Allies access to German plans", acceptableAnswers: ["German code machine cracked by Turing", "Encryption machine broken at Bletchley Park", "Nazi cipher cracked by British"], explanation: "Breaking Enigma is estimated to have shortened the war by two years." },
      { id: "ww2_400_03", categoryId: "his_world_war_2", tier: 400, prompt: "What was the Holocaust, and approximately how many people were systematically murdered?", answer: "The Nazi regime's systematic genocide of six million Jews and millions of others including Roma, disabled people, and political prisoners", acceptableAnswers: ["Nazi genocide of 6 million Jews", "Systematic murder of 6 million Jews and millions of others"], explanation: "The Holocaust was industrialized mass murder on an unprecedented scale." },
      { id: "ww2_600_01", categoryId: "his_world_war_2", tier: 600, prompt: "What was Operation Mincemeat, and how did it use a dead body to deceive the Germans?", answer: "British intelligence dressed a corpse as a fictional officer carrying fake invasion plans suggesting the Allies would invade Greece and Sardinia instead of Sicily — Germany moved troops away from Sicily, enabling the real invasion", acceptableAnswers: ["Fake officer corpse with false invasion plans", "Dead body with fake plans fooled Germany", "Corpse deception for Sicily invasion"], explanation: "One of history's most audacious deceptions, using a dead homeless man to change the war." },
      { id: "ww2_600_02", categoryId: "his_world_war_2", tier: 600, prompt: "What was the 'Ghost Army' in WWII, and what unconventional methods did they use?", answer: "The US 23rd Headquarters Special Troops used inflatable tanks, sound effects broadcast from speakers, and fake radio traffic to simulate entire army divisions and mislead German intelligence", acceptableAnswers: ["Inflatable tanks and fake army", "Deception unit with inflatable equipment", "US unit using rubber tanks and sound effects"], explanation: "The Ghost Army successfully fooled German forces multiple times using theatrical deception." },
      { id: "ww2_600_03", categoryId: "his_world_war_2", tier: 600, prompt: "What was Japan's Unit 731, and why was its post-war handling considered one of history's greatest moral failures?", answer: "A secret Japanese biological warfare unit that conducted lethal human experiments on thousands of prisoners; after the war, the US granted immunity to its scientists in exchange for their research data", acceptableAnswers: ["Japanese biological warfare human experiments, US gave immunity", "Human experiments, scientists got immunity for data", "Biological warfare unit, US traded immunity for research"], explanation: "Unit 731's atrocities were covered up for decades because the US valued the research data." },
    ],
  },
  {
    id: "sci_evolution",
    group: "science",
    name: "Evolution & Natural Selection",
    culture: "universal",
    description: "Darwin's dangerous idea — how life adapts, diversifies, and transforms.",
    imageUrl: "",
    questions: [
      { id: "evo_200_01", categoryId: "sci_evolution", tier: 200, prompt: "Who is the naturalist most associated with the theory of evolution by natural selection?", answer: "Charles Darwin", acceptableAnswers: ["Darwin"], explanation: "Darwin published 'On the Origin of Species' in 1859, revolutionizing biology." },
      { id: "evo_200_02", categoryId: "sci_evolution", tier: 200, prompt: "What is 'natural selection' — the basic mechanism Darwin proposed for how evolution works?", answer: "Organisms with traits better suited to their environment survive and reproduce more, passing those traits to offspring", acceptableAnswers: ["Survival of the fittest", "Better-adapted organisms survive and reproduce more", "Advantageous traits passed to offspring"], explanation: "Natural selection is sometimes simplified as 'survival of the fittest,' though this is incomplete." },
      { id: "evo_200_03", categoryId: "sci_evolution", tier: 200, prompt: "What volcanic island chain did Darwin visit that inspired his theory of evolution through its unique wildlife?", answer: "The Galápagos Islands", acceptableAnswers: ["Galapagos", "Galápagos", "Galapagos Islands"], explanation: "Darwin's observations of finches and tortoises on different islands led to key insights." },
      { id: "evo_400_01", categoryId: "sci_evolution", tier: 400, prompt: "What are 'vestigial structures' — body parts that evolution has made largely useless but that hint at our evolutionary past?", answer: "Structures that had a function in ancestors but no longer serve a purpose, like the human appendix, wisdom teeth, or the coccyx (tailbone)", acceptableAnswers: ["Useless inherited body parts", "Remnant organs from ancestors", "Appendix, tailbone, wisdom teeth"], explanation: "Vestigial structures are some of the strongest evidence for common descent." },
      { id: "evo_400_02", categoryId: "sci_evolution", tier: 400, prompt: "What is 'convergent evolution,' and what is a famous example involving eyes?", answer: "When unrelated species independently evolve similar traits — eyes evolved independently over 40 times in different animal lineages", acceptableAnswers: ["Independent evolution of similar traits", "Unrelated species evolving same features", "Eyes evolving independently many times"], explanation: "Octopus and human eyes evolved independently but arrived at remarkably similar solutions." },
      { id: "evo_400_03", categoryId: "sci_evolution", tier: 400, prompt: "What did the discovery of DNA and genetics add to Darwin's original theory that he couldn't explain?", answer: "The mechanism of inheritance — Darwin knew traits were passed down but didn't know how; DNA explained that mutations provide the variation that natural selection acts on", acceptableAnswers: ["Mechanism of inheritance via DNA", "How traits are inherited through genes", "DNA mutations as source of variation"], explanation: "The 'Modern Synthesis' merged Darwin's natural selection with Mendelian genetics." },
      { id: "evo_600_01", categoryId: "sci_evolution", tier: 600, prompt: "What is 'punctuated equilibrium,' proposed by Gould and Eldredge, and how does it challenge traditional Darwinian gradualism?", answer: "Species remain stable for long periods (stasis) then evolve rapidly in short bursts, often during environmental crises — challenging the idea that evolution is always slow and gradual", acceptableAnswers: ["Long stasis with rapid evolution bursts", "Species stable then rapidly change", "Evolution in quick bursts not gradual"], explanation: "The fossil record shows more sudden changes than Darwin's gradualism predicted." },
      { id: "evo_600_02", categoryId: "sci_evolution", tier: 600, prompt: "What is 'horizontal gene transfer,' and why does it complicate the traditional 'tree of life' model?", answer: "Organisms can transfer genes directly between species (not just parent to offspring) — especially common in bacteria. This means the tree of life is more like a web, with branches reconnecting", acceptableAnswers: ["Gene transfer between species", "Genes moving between unrelated organisms", "Non-vertical gene sharing creating a web not tree"], explanation: "HGT means evolution isn't purely tree-shaped — species can acquire traits from completely unrelated organisms." },
      { id: "evo_600_03", categoryId: "sci_evolution", tier: 600, prompt: "What is the 'Red Queen Hypothesis,' and how does it explain why sexual reproduction exists despite its evolutionary costs?", answer: "Species must constantly evolve just to maintain fitness against co-evolving parasites and predators — sexual reproduction generates genetic diversity faster than asexual reproduction, helping organisms stay ahead of parasites", acceptableAnswers: ["Constant evolution to keep up with parasites", "Sexual reproduction for genetic diversity against co-evolving threats", "Running to stay in place against evolving enemies"], explanation: "Named after the Red Queen in Alice in Wonderland: 'It takes all the running you can do to keep in the same place.'" },
    ],
  },
  {
    id: "cul_mythology_greek",
    group: "culture",
    name: "Greek Mythology",
    culture: "universal",
    description: "Gods, heroes, and monsters — the stories that built Western storytelling.",
    imageUrl: "",
    questions: [
      { id: "grm_200_01", categoryId: "cul_mythology_greek", tier: 200, prompt: "Who is the king of the Greek gods, wielding thunderbolts from atop Mount Olympus?", answer: "Zeus", explanation: "Zeus overthrew his father Kronos to become ruler of the gods." },
      { id: "grm_200_02", categoryId: "cul_mythology_greek", tier: 200, prompt: "What Greek hero is known for his extraordinary strength and his twelve labors?", answer: "Heracles (Hercules)", acceptableAnswers: ["Heracles", "Hercules"], explanation: "The Twelve Labors were penance for killing his family in a madness sent by Hera." },
      { id: "grm_200_03", categoryId: "cul_mythology_greek", tier: 200, prompt: "What wooden construction did the Greeks use to infiltrate and conquer the city of Troy?", answer: "The Trojan Horse", acceptableAnswers: ["Trojan Horse"], explanation: "Greek soldiers hid inside the horse, which the Trojans brought inside their walls." },
      { id: "grm_400_01", categoryId: "cul_mythology_greek", tier: 400, prompt: "What is the Underworld in Greek mythology, and which god rules it?", answer: "The realm of the dead, ruled by Hades", acceptableAnswers: ["Hades rules the Underworld", "The Underworld ruled by Hades"], explanation: "Hades wasn't evil — he simply ruled the necessary realm where all mortals eventually went." },
      { id: "grm_400_02", categoryId: "cul_mythology_greek", tier: 400, prompt: "What is the myth of Icarus, and what moral lesson does it teach?", answer: "Icarus flew too close to the sun with wings made of wax and feathers; the wax melted and he fell to his death — a warning against hubris and ignoring wise counsel", acceptableAnswers: ["Flew too close to sun, wax wings melted", "Wax wings melted from sun, died from hubris"], explanation: "Daedalus warned his son not to fly too high, but Icarus's overconfidence killed him." },
      { id: "grm_400_03", categoryId: "cul_mythology_greek", tier: 400, prompt: "What is the story of Orpheus and Eurydice, and what condition does Hades place on Orpheus's attempt to rescue her?", answer: "Orpheus goes to the Underworld to retrieve his dead wife Eurydice; Hades agrees but says Orpheus must not look back at her until they reach the surface — he looks back, losing her forever", acceptableAnswers: ["Cannot look back, he does and loses her", "Must not look back at Eurydice", "Fails by looking back at her"], explanation: "The myth explores love, trust, and the impossibility of undoing death." },
      { id: "grm_600_01", categoryId: "cul_mythology_greek", tier: 600, prompt: "What is the myth of Prometheus, and what punishment does Zeus inflict on him for helping humanity?", answer: "Prometheus stole fire from the gods and gave it to humanity; Zeus chained him to a rock where an eagle ate his liver daily, which regrew each night — an eternal punishment", acceptableAnswers: ["Stole fire, liver eaten daily by eagle forever", "Eternal liver-eating punishment for giving fire", "Chained to rock, eagle eats regenerating liver"], explanation: "Prometheus's punishment represents the cost of defying divine authority to help mankind." },
      { id: "grm_600_02", categoryId: "cul_mythology_greek", tier: 600, prompt: "What is the 'Oedipus complex' in psychology, and how does the original Greek myth of Oedipus differ from Freud's interpretation?", answer: "Freud used Oedipus to describe a child's unconscious desire for the opposite-sex parent; but in Sophocles' play, Oedipus doesn't know Jocasta is his mother — the tragedy is about fate and the impossibility of escaping prophecy, not desire", acceptableAnswers: ["Freud's theory vs actual myth about fate not desire", "Oedipus didn't know, myth is about fate", "Freud misapplied it — myth is about prophecy"], explanation: "The original myth is about the horror of fulfilled prophecy, not subconscious desire." },
      { id: "grm_600_03", categoryId: "cul_mythology_greek", tier: 600, prompt: "What is the 'Titanomachy,' and how does the division of the cosmos among Zeus, Poseidon, and Hades reflect Greek ideas about power and order?", answer: "The ten-year war between the Olympian gods and the Titans; after victory, the three brothers drew lots — Zeus got the sky, Poseidon the sea, Hades the underworld, and Earth was shared — reflecting Greek values of divine order through consent rather than pure conquest", acceptableAnswers: ["War against Titans, cosmos divided by lots", "Olympians vs Titans, then lots for realms", "Ten-year god war, realms assigned by drawing lots"], explanation: "The lot-drawing suggests even among gods, power must be distributed — a proto-democratic impulse in Greek thought." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 71 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
