#!/usr/bin/env python3
"""Insert wave 57 categories into categories.ts"""

import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_simpsons",
    group: "TV Shows",
    name: "The Simpsons",
    culture: "american",
    description: "Springfield's eternally dysfunctional first family and the longest-running American animated series.",
    imageUrl: "",
    questions: [
      {
        id: "sim_200_01",
        categoryId: "tv_simpsons",
        tier: 200,
        prompt: "What is Homer Simpson's official job title at the Springfield Nuclear Power Plant?",
        answer: "Nuclear Safety Inspector",
        acceptableAnswers: ["safety inspector", "nuclear safety inspector", "nuclear power plant safety inspector"],
      },
      {
        id: "sim_200_02",
        categoryId: "tv_simpsons",
        tier: 200,
        prompt: "What is the name of the seedy bar Homer and his regulars frequent, run by a bitter, lovesick bartender?",
        answer: "Moe's Tavern",
        acceptableAnswers: ["Moe's Tavern", "Moe's", "Moe's Bar"],
      },
      {
        id: "sim_200_03",
        categoryId: "tv_simpsons",
        tier: 200,
        prompt: "Bart Simpson is perennially sent to the principal's office. What is the principal's name?",
        answer: "Principal Skinner",
        acceptableAnswers: ["Principal Skinner", "Seymour Skinner", "Skinner", "Armin Tamzarian"],
      },
      {
        id: "sim_400_01",
        categoryId: "tv_simpsons",
        tier: 400,
        prompt: "In the Emmy-winning episode 'Homer's Phobia' (Season 8), which cult filmmaker guest-starred as a flamboyantly gay antiques dealer named John — whose friendship with Homer causes Homer to panic about Bart's sexuality?",
        answer: "John Waters",
        acceptableAnswers: ["John Waters"],
        explanation: "Waters plays John, a camp antiques dealer Homer initially adores before learning he's gay. The episode won the Outstanding Animated Program Emmy in 1997 and was notable for its sympathetic portrayal of a gay character at the time.",
      },
      {
        id: "sim_400_02",
        categoryId: "tv_simpsons",
        tier: 400,
        prompt: "The Simpsons debuted two years before it became a standalone series, appearing as animated shorts on which variety show starting in 1987?",
        answer: "The Tracey Ullman Show",
        acceptableAnswers: ["The Tracey Ullman Show", "Tracey Ullman Show"],
        explanation: "Matt Groening pitched the family in a Fox executive's waiting room rather than hand over the Life in Hell rights. The shorts ran 48 episodes before the spin-off premiered in December 1989.",
      },
      {
        id: "sim_400_03",
        categoryId: "tv_simpsons",
        tier: 400,
        prompt: "In 'Homer's Enemy' (Season 8), new plant employee Frank Grimes is driven to a breakdown by Homer's inexplicable success. What nickname does the entire office use for Grimes — which he explicitly hates?",
        answer: "Grimey",
        acceptableAnswers: ["Grimey"],
        explanation: "Written by John Swartzwelder, the episode is considered the series' darkest hour — it ends with Grimes dying at his own breakdown and Homer falling asleep at the funeral. Grimes is the only person in Springfield who treats Homer's incompetence as the real-world tragedy it would be.",
      },
      {
        id: "sim_600_01",
        categoryId: "tv_simpsons",
        tier: 600,
        prompt: "In 'Stark Raving Dad' (Season 3, 1991), Homer meets a large white man in a mental institution who claims to be Michael Jackson. Jackson actually provided the voice under a pseudonym to avoid publicizing the cameo. What was that pseudonym?",
        answer: "John Jay Smith",
        acceptableAnswers: ["John Jay Smith"],
        explanation: "Jackson insisted on the pseudonym and went uncredited. The episode was pulled from rotation by the family estate in 2019 following the Leaving Neverland documentary. His speaking voice is Jackson; his singing parts were performed by a soundalike.",
      },
      {
        id: "sim_600_02",
        categoryId: "tv_simpsons",
        tier: 600,
        prompt: "Simpsons writer John Swartzwelder — who wrote more credited episodes than anyone else — maintained a famously reclusive public profile and a rigid writing ritual. What did he do when California banned indoor smoking at restaurants, threatening his routine?",
        answer: "He purchased his regular diner booth and installed it in his home so he could keep writing in the same environment",
        acceptableAnswers: ["bought his diner booth", "bought the booth and put it in his house", "installed a diner booth at home"],
        explanation: "Swartzwelder had written dozens of scripts from a specific booth while smoking. Rather than adapt, he bought the booth. He credits the physical setup as essential to his process. He has given almost no interviews in his career.",
      },
      {
        id: "sim_600_03",
        categoryId: "tv_simpsons",
        tier: 600,
        prompt: "The Simpsons episode '22 Short Films About Springfield' (Season 7) uses a non-linear anthology structure cutting between unrelated Springfield characters, directly parodying which 1994 film?",
        answer: "Pulp Fiction",
        acceptableAnswers: ["Pulp Fiction", "Quentin Tarantino's Pulp Fiction"],
        explanation: "The episode title itself references '32 Short Films About Glenn Gould' (1993), but the episode's non-linear multi-story structure is a direct Pulp Fiction parody — including the Pulp Fiction-style basement scene involving Groundskeeper Willie instead of Zed.",
      },
    ],
  },
  {
    id: "tv_south_park",
    group: "TV Shows",
    name: "South Park",
    culture: "american",
    description: "Trey Parker and Matt Stone's foul-mouthed Colorado mountain town where nothing is sacred and everything is satirized.",
    imageUrl: "",
    questions: [
      {
        id: "spk_200_01",
        categoryId: "tv_south_park",
        tier: 200,
        prompt: "In South Park's early seasons, which main character dies in almost every episode — only to be alive again with no explanation the following week?",
        answer: "Kenny McCormick",
        acceptableAnswers: ["Kenny", "Kenny McCormick"],
      },
      {
        id: "spk_200_02",
        categoryId: "tv_south_park",
        tier: 200,
        prompt: "Before South Park was a show, Trey Parker and Matt Stone made a crude animated Christmas short called 'The Spirit of Christmas.' Who commissioned and distributed it — launching the show's development?",
        answer: "Brian Graden",
        acceptableAnswers: ["Brian Graden", "Fox executive Brian Graden"],
        explanation: "Fox executive Brian Graden paid $1,250 for the short as a video Christmas card to send to friends. It spread virally on early internet, Comedy Central saw it, and greenlit South Park. Graden later became president of MTV.",
      },
      {
        id: "spk_200_03",
        categoryId: "tv_south_park",
        tier: 200,
        prompt: "Eric Cartman's schemes and insults are almost always directed at which Jewish classmate, whose patience he constantly exhausts?",
        answer: "Kyle Broflovski",
        acceptableAnswers: ["Kyle", "Kyle Broflovski"],
      },
      {
        id: "spk_400_01",
        categoryId: "tv_south_park",
        tier: 400,
        prompt: "In 'Scott Tenorman Must Die' (Season 5), Cartman takes revenge on an older kid who humiliated him. What is Cartman's final, devastating act of revenge?",
        answer: "He arranges for Scott's parents to be killed, then serves them to Scott as chili at a festival — making Scott eat his own parents",
        acceptableAnswers: ["he fed Scott his parents in chili", "made Scott eat his own parents", "had Scott's parents killed and put in chili", "Scott's parents were turned into chili"],
        explanation: "Often cited as the moment the show revealed Cartman's true sociopathic depths. He also arranges for Radiohead to show up and call Scott a crybaby. The episode recontextualized Cartman from comic buffoon to genuine monster.",
      },
      {
        id: "spk_400_02",
        categoryId: "tv_south_park",
        tier: 400,
        prompt: "In the episode 'Trapped in the Closet' (Season 9), the plot directly presents the foundational beliefs of which religion as literal on-screen text — ending with Tom Cruise refusing to come out of a closet?",
        answer: "Scientology",
        acceptableAnswers: ["Scientology", "the Church of Scientology"],
        explanation: "The episode presented Scientology's Xenu creation narrative with the on-screen caption 'THIS IS WHAT SCIENTOLOGISTS ACTUALLY BELIEVE.' The episode drew real legal threats, and Comedy Central limited its reruns.",
      },
      {
        id: "spk_400_03",
        categoryId: "tv_south_park",
        tier: 400,
        prompt: "After 'Trapped in the Closet' aired, which beloved voice actor quietly resigned from the show — citing the episode's mockery of his personal religious beliefs?",
        answer: "Isaac Hayes",
        acceptableAnswers: ["Isaac Hayes", "the voice of Chef", "Isaac Hayes who voiced Chef"],
        explanation: "Hayes had voiced Chef since the pilot and was a founding cast member. He was a practicing Scientologist and issued a statement calling the episode 'bigotry and intolerance.' Parker and Stone pointed out that Hayes had stayed through episodes mocking every other religion. Chef was killed off in Season 10's 'The Return of Chef.'",
      },
      {
        id: "spk_600_01",
        categoryId: "tv_south_park",
        tier: 600,
        prompt: "In 'Casa Bonita' (Season 7), Cartman traps Butters to steal his spot at the real-life Casa Bonita restaurant. What happened to the actual Casa Bonita in Lakewood, Colorado in the years following?",
        answer: "Trey Parker and Matt Stone purchased the real Casa Bonita after it closed during the COVID-19 pandemic and renovated and reopened it in 2023",
        acceptableAnswers: ["Parker and Stone bought it", "Trey Parker and Matt Stone purchased and reopened it", "they bought Casa Bonita"],
        explanation: "The real Casa Bonita closed in April 2020. Parker and Stone, who grew up loving it, bought it in 2021. After extensive renovation, it reopened in June 2023. It's a working restaurant in Lakewood, Colorado with the original cliff-divers, Black Bart's Cave, and arcade.",
      },
      {
        id: "spk_600_02",
        categoryId: "tv_south_park",
        tier: 600,
        prompt: "South Park's 'Cartoon Wars' two-parter (Season 10) contains a direct creative attack on another animated series — arguing it steals from The Simpsons and uses random idea generation instead of real writing. Which show?",
        answer: "Family Guy",
        acceptableAnswers: ["Family Guy", "Seth MacFarlane's Family Guy"],
        explanation: "The episode features Cartman trying to get Family Guy cancelled by claiming a Muhammad scene will endanger America, but the subplot is a pointed critique of Family Guy's cutaway gag structure. A character literally shows manatees in a tank pushing 'idea balls' together to generate jokes.",
      },
      {
        id: "spk_600_03",
        categoryId: "tv_south_park",
        tier: 600,
        prompt: "South Park's episode '201' (Season 14) was effectively censored by Comedy Central — not only bleeping Muhammad's depiction but also bleeping an entire final speech. Parker and Stone later revealed what that speech actually said. What was the speech about?",
        answer: "Kyle's closing moral speech was about how surrendering to fear and intimidation means you can never stand up for what you believe in — Parker and Stone said Comedy Central bleeped it because they were afraid of terrorist threats, making the censorship itself prove Kyle's point",
        acceptableAnswers: ["Kyle's speech about not surrendering to fear", "the speech was about intimidation and fear", "about not giving in to threats"],
        explanation: "Parker and Stone were outraged that Comedy Central bleeped not just Muhammad's image but also Kyle's straightforward moral about courage against threats. They stated publicly that the censorship perfectly illustrated the episode's point.",
      },
    ],
  },
  {
    id: "tv_futurama",
    group: "TV Shows",
    name: "Futurama",
    culture: "american",
    description: "Matt Groening's sci-fi comedy following a hapless pizza guy frozen in 1999 and thawed out in the year 3000.",
    imageUrl: "",
    questions: [
      {
        id: "ftm_200_01",
        categoryId: "tv_futurama",
        tier: 200,
        prompt: "Philip J. Fry is accidentally cryogenically frozen on New Year's Eve 1999. In what year does he wake up?",
        answer: "3000",
        acceptableAnswers: ["3000", "the year 3000"],
      },
      {
        id: "ftm_200_02",
        categoryId: "tv_futurama",
        tier: 200,
        prompt: "What is the name of the foul-mouthed bending robot who becomes Fry's best friend, known for his love of alcohol, cigars, and the catchphrase 'Bite my shiny metal ass'?",
        answer: "Bender",
        acceptableAnswers: ["Bender", "Bender Bending Rodriguez"],
      },
      {
        id: "ftm_200_03",
        categoryId: "tv_futurama",
        tier: 200,
        prompt: "The Planet Express crew works for which senile, ancient professor who is actually Fry's very distant descendant?",
        answer: "Professor Hubert J. Farnsworth",
        acceptableAnswers: ["Professor Farnsworth", "Professor Hubert J. Farnsworth", "Farnsworth", "the Professor"],
      },
      {
        id: "ftm_400_01",
        categoryId: "tv_futurama",
        tier: 400,
        prompt: "The episode 'The Prisoner of Benda' (Season 6) required solving a real mathematical problem about body-switching. A Futurama writer with a PhD in Applied Mathematics actually proved a new theorem for the episode. Who was he?",
        answer: "Ken Keeler",
        acceptableAnswers: ["Ken Keeler"],
        explanation: "The 'Futurama Theorem' (also called the Bodyswitch Theorem) proves that any number of mind-body swaps can be undone using exactly two previously unswapped individuals, regardless of how many switches occurred. Ken Keeler (PhD, Applied Mathematics, Harvard) proved it specifically for the episode.",
      },
      {
        id: "ftm_400_02",
        categoryId: "tv_futurama",
        tier: 400,
        prompt: "The pompous space captain Zapp Brannigan was written with a specific comedian in mind who was supposed to voice him. Who was the intended voice actor, and what prevented him from taking the role?",
        answer: "Phil Hartman — he was murdered in May 1998 before the show premiered; Billy West took over and styled the voice as a tribute to Hartman's comedic timing",
        acceptableAnswers: ["Phil Hartman", "Phil Hartman was murdered", "Phil Hartman died before the show aired"],
        explanation: "Phil Hartman was set to voice Zapp Brannigan when he was killed in May 1998. Billy West consciously patterned his Zapp voice on Hartman's cadence and delivery as a tribute. The character became one of West's most celebrated performances.",
      },
      {
        id: "ftm_400_03",
        categoryId: "tv_futurama",
        tier: 400,
        prompt: "Futurama's first Emmy for Outstanding Animated Program went to the episode 'Roswell That Ends Well,' in which the crew lands in 1947. What disturbing truth about his family does Fry discover there?",
        answer: "Fry is his own grandfather — his actual grandfather is killed in an explosion, and Fry ends up sleeping with his grandmother, biologically making himself his own ancestor",
        acceptableAnswers: ["Fry is his own grandfather", "he slept with his grandmother", "he became his own grandfather"],
      },
      {
        id: "ftm_600_01",
        categoryId: "tv_futurama",
        tier: 600,
        prompt: "Futurama's 'The Luck of the Fryish' (Season 3) features a twist that recontextualizes the whole episode emotionally. Fry resents his brother for seemingly stealing his lucky seven-leaf clover and taking his name for his son. What does Fry discover at the end?",
        answer: "His brother named his son Philip in honor of Fry after he disappeared — he missed Fry deeply and preserved the clover as a tribute, burying it with the nephew named after him",
        acceptableAnswers: ["his brother named his son after him", "Philip was named in Fry's honor", "his brother missed him and named his son Philip", "the son was named after Fry"],
        explanation: "The ending cuts between Fry's past jealousy of his brother and the revelation that his brother grieved his disappearance. The name Philip was a tribute. It's often cited as the episode that proved Futurama could do genuine emotional depth, not just jokes.",
      },
      {
        id: "ftm_600_02",
        categoryId: "tv_futurama",
        tier: 600,
        prompt: "The Futurama Theorem (proven for 'The Prisoner of Benda') states that any sequence of mind-body switches can always be resolved without repeating any pair. The fix requires how many additional, previously unswapped people?",
        answer: "Two",
        acceptableAnswers: ["two", "2", "exactly two"],
        explanation: "The theorem proves that no matter how many people have swapped bodies, exactly 2 'clean' (unswapped) individuals can undo the entire permutation. In the episode, the Harlem Globetrotters serve as the two clean individuals to sort out the Professor's crew.",
      },
      {
        id: "ftm_600_03",
        categoryId: "tv_futurama",
        tier: 600,
        prompt: "Futurama's 'Jurassic Bark' (Season 4) has an ending widely considered one of the most devastating in animated TV. What happens to Fry's dog Seymour that causes the emotional gut-punch?",
        answer: "A freeze frame montage reveals that Seymour waited outside the pizza restaurant for Fry for 12 years — sitting in the same spot until he died of old age, never knowing Fry was frozen",
        acceptableAnswers: ["Seymour waited for Fry until he died", "the dog waited 12 years for Fry", "Seymour died waiting for Fry"],
        explanation: "The ending was later partially retconned in 'Game of Tones' (Season 7), which implies Seymour may have eventually moved on. But the original episode's implication — loyal dog dying alone — made it a cultural touchstone for animated tragedy.",
      },
    ],
  },
  {
    id: "tv_curb",
    group: "TV Shows",
    name: "Curb Your Enthusiasm",
    culture: "american",
    description: "Larry David playing a version of himself stumbling through Los Angeles's social minefield with no filter and infinite grievances.",
    imageUrl: "",
    questions: [
      {
        id: "curb_200_01",
        categoryId: "tv_curb",
        tier: 200,
        prompt: "Curb Your Enthusiasm stars which Seinfeld co-creator playing a fictionalized version of himself navigating awkward social situations in Los Angeles?",
        answer: "Larry David",
        acceptableAnswers: ["Larry David"],
      },
      {
        id: "curb_200_02",
        categoryId: "tv_curb",
        tier: 200,
        prompt: "Unlike most TV comedies, Curb Your Enthusiasm doesn't use a traditional script. How do the actors prepare and perform each scene?",
        answer: "From detailed outlines — actors improvise all dialogue within scripted scene frameworks",
        acceptableAnswers: ["they improvise", "no script, just outlines", "improvised from outlines", "actors improvise from scene outlines"],
      },
      {
        id: "curb_200_03",
        categoryId: "tv_curb",
        tier: 200,
        prompt: "What is the name of Larry's loyal but long-suffering business manager and best friend on the show, played by Jeff Garlin?",
        answer: "Jeff Greene",
        acceptableAnswers: ["Jeff Greene", "Jeff Garlin's character", "Jeff"],
      },
      {
        id: "curb_400_01",
        categoryId: "tv_curb",
        tier: 400,
        prompt: "Season 7 of Curb featured the actual Seinfeld cast — Jerry Seinfeld, Julia Louis-Dreyfus, Jason Alexander, and Michael Richards — appearing together on screen. What was Larry's in-show motivation for organizing this reunion?",
        answer: "Larry wrote and pitched a Seinfeld reunion episode as a scheme to win back his ex-wife Cheryl, who would play George Costanza's love interest",
        acceptableAnswers: ["to win back Cheryl", "Larry wrote a Seinfeld reunion to win back his ex-wife", "the reunion was Larry's scheme to get Cheryl back"],
      },
      {
        id: "curb_400_02",
        categoryId: "tv_curb",
        tier: 400,
        prompt: "The most explosively hostile recurring character on Curb is Larry's nemesis who delivers legendary rants against him. What is her name and who plays her?",
        answer: "Susie Greene, played by Susie Essman",
        acceptableAnswers: ["Susie Greene", "Susie Essman", "Susie Essman as Susie Greene"],
      },
      {
        id: "curb_400_03",
        categoryId: "tv_curb",
        tier: 400,
        prompt: "After Hurricane Katrina, Larry takes in a displaced family and gains a smooth-talking roommate who becomes one of the show's most beloved recurring characters. What is his name and who plays him?",
        answer: "Leon Black, played by JB Smoove",
        acceptableAnswers: ["Leon Black", "Leon", "JB Smoove", "JB Smoove as Leon"],
      },
      {
        id: "curb_600_01",
        categoryId: "tv_curb",
        tier: 600,
        prompt: "Season 7's Seinfeld reunion storyline also directly addressed the real-life Laugh Factory incident. Which cast member's 2006 racist outburst at a comedy club was woven into the show's plot, and how did Curb handle the real event?",
        answer: "Michael Richards — the Season 7 story uses the fictional Seinfeld reunion as a frame for Richards' character dealing with the fallout from his racial slur tirade, allowing the real incident to be addressed through comedy without being trivialized",
        acceptableAnswers: ["Michael Richards", "Michael Richards and the Laugh Factory incident", "Richards' racist outburst"],
        explanation: "Richards' November 2006 tirade at the Laugh Factory went viral and effectively ended his career. Season 7 uses the reunion plot to give the event a comedic, somewhat cathartic on-screen treatment — Richards plays himself trying to make amends in increasingly uncomfortable situations.",
      },
      {
        id: "curb_600_02",
        categoryId: "tv_curb",
        tier: 600,
        prompt: "Curb Your Enthusiasm grew from a 1999 HBO special. What was unusual about the format of that special — and how did it establish the approach the series would use?",
        answer: "It was a mockumentary special following Larry David supposedly preparing for a stand-up comeback — using a fake documentary format that made improvised situations feel candid; the series adopted this style of semi-scripted, improvised realism",
        acceptableAnswers: ["mockumentary", "fake documentary about Larry's stand-up comeback", "1999 HBO mockumentary special", "documentary-style improvised format"],
        explanation: "The hour-long special 'Larry David: Curb Your Enthusiasm' (1999) followed Larry preparing for a stand-up return using documentary crew footage. It showed the template: real locations, no scripted dialogue, plausible celebrity cameos. HBO ordered the series based on it.",
      },
      {
        id: "curb_600_03",
        categoryId: "tv_curb",
        tier: 600,
        prompt: "In Season 11, Larry opens a coffee shop directly across the street from a cafe whose owner wronged him — purely out of spite. What is the name of Larry's deliberately antagonistic coffee shop?",
        answer: "Latte Larry's",
        acceptableAnswers: ["Latte Larry's"],
        explanation: "The nemesis coffee shop is 'Mocha Joe's,' run by a man named Mocha Joe who persistently serves Larry bad coffee and oversized chairs. Larry's response is to open Latte Larry's across the street and systematically steal every customer. The spite store became an iconic Curb storyline.",
      },
    ],
  },
  {
    id: "tv_always_sunny",
    group: "TV Shows",
    name: "It's Always Sunny in Philadelphia",
    culture: "american",
    description: "Five sociopathic friends running a failing South Philly bar into ever-deepening moral catastrophe since 2005.",
    imageUrl: "",
    questions: [
      {
        id: "sun_200_01",
        categoryId: "tv_always_sunny",
        tier: 200,
        prompt: "It's Always Sunny in Philadelphia follows a group of self-absorbed friends who own and poorly run a bar in South Philadelphia. What is the bar's name?",
        answer: "Paddy's Pub",
        acceptableAnswers: ["Paddy's Pub", "Paddy's"],
      },
      {
        id: "sun_200_02",
        categoryId: "tv_always_sunny",
        tier: 200,
        prompt: "Which Oscar-winning actor joined the Always Sunny cast in Season 2 as Frank Reynolds, the father of twins Dennis and Dee, dramatically expanding the show's budget and profile?",
        answer: "Danny DeVito",
        acceptableAnswers: ["Danny DeVito", "Danny DeVito as Frank Reynolds"],
      },
      {
        id: "sun_200_03",
        categoryId: "tv_always_sunny",
        tier: 200,
        prompt: "In 'The DENNIS System' (Season 5), Dennis reveals his step-by-step methodology for seducing and then discarding romantic partners. What does the acronym D.E.N.N.I.S. stand for?",
        answer: "Demonstrate value, Engage physically, Nurture dependence, Neglect emotionally, Inspire hope, Separate entirely",
        acceptableAnswers: ["Demonstrate value Engage physically Nurture dependence Neglect emotionally Inspire hope Separate entirely", "D.E.N.N.I.S.", "Demonstrate value, Engage physically, Nurture dependence, Neglect emotionally, Inspire hope, Separate entirely"],
      },
      {
        id: "sun_400_01",
        categoryId: "tv_always_sunny",
        tier: 400,
        prompt: "The episode 'Charlie Work' (Season 10) follows Charlie executing a health inspection in a single continuous take while the gang runs a scheme behind him. Which 2014 Best Picture winner does its one-shot style directly parody?",
        answer: "Birdman (or The Unexpected Virtue of Ignorance)",
        acceptableAnswers: ["Birdman", "Birdman (or the Unexpected Virtue of Ignorance)"],
        explanation: "Birdman won Best Picture at the 2015 Oscars for its apparent continuous-take cinematography. 'Charlie Work' aired in 2015 and explicitly mimics the style — the camera follows Charlie through the bar without visible cuts as he heroically keeps the inspection going while the gang sabotages everything.",
      },
      {
        id: "sun_400_02",
        categoryId: "tv_always_sunny",
        tier: 400,
        prompt: "Rob McElhenney (Mac) pulled off one of TV's most committed physical comedy bits between seasons. What did he do to his body between Season 6 and Season 7 — and why?",
        answer: "He deliberately gained 60 pounds of fat — not muscle — purely as a comedic bit, with no plot justification; he then lost it all for Season 8",
        acceptableAnswers: ["gained 60 pounds", "Rob McElhenney gained 60 pounds", "Mac gained 60 pounds for a joke"],
        explanation: "McElhenney decided that TV characters always get more attractive over time, which is unrealistic. He gained approximately 60 pounds of fat specifically to subvert that trend. The show's other characters barely acknowledge it, which was part of the joke.",
      },
      {
        id: "sun_400_03",
        categoryId: "tv_always_sunny",
        tier: 400,
        prompt: "Always Sunny's original pilot was made on an extremely low budget by Rob McElhenney and friends before any network was involved. What did it cost to produce?",
        answer: "Approximately $200 — shot by McElhenney on a consumer camera with his friends as actors",
        acceptableAnswers: ["$200", "two hundred dollars", "about $200"],
        explanation: "McElhenney shot the original pilot in his apartment for roughly $200, used his friends as cast, and submitted it to FX. The network liked the concept enough to greenlight a full pilot with a real budget and eventually add Danny DeVito.",
      },
      {
        id: "sun_600_01",
        categoryId: "tv_always_sunny",
        tier: 600,
        prompt: "Dennis Reynolds has become a canonical fictional example of Narcissistic Personality Disorder in internet fan analysis. Which specific chilling line does Dennis deliver — admitting he seeks a particular look from romantic partners — that fans cite as the clearest on-screen evidence of his pathology?",
        answer: "He says he wants 'the look of pure unadulterated terror' or 'sheer panic' in a woman's eyes — admitting he derives satisfaction from having absolute power over them",
        acceptableAnswers: ["the look of pure terror", "sheer panic in her eyes", "pure unadulterated terror", "he wants panic in their eyes"],
        explanation: "The line is delivered completely straight by Glenn Howerton, with no comedic undercutting. Dennis frames it as perfectly normal attraction. The show never diagnoses him but the writers have acknowledged they wrote him as a likely sociopath and NPD case.",
      },
      {
        id: "sun_600_02",
        categoryId: "tv_always_sunny",
        tier: 600,
        prompt: "In 'The Nightman Cometh' (Season 4), Charlie stages an elaborate musical he wrote. The episode reveals something genuinely touching about why Charlie wrote it. What is his actual motivation?",
        answer: "Charlie wrote the musical as an elaborate proposal to the Waitress — the musical's climax has the Day Man asking the 'pretty flower lady' (the Waitress) to marry him",
        acceptableAnswers: ["to propose to the Waitress", "the musical was a marriage proposal", "Charlie used it to propose to the Waitress"],
        explanation: "The Waitress says no. The episode is also the origin of 'Day Man' and 'Night Man' as fan-favorite songs from the show. The songs had appeared in an earlier episode where Charlie banged on a keyboard and sang — the musical formalizes them.",
      },
      {
        id: "sun_600_03",
        categoryId: "tv_always_sunny",
        tier: 600,
        prompt: "The episode 'The Gang Beats Boggs' (Season 10) has the gang trying to beat an aviation alcohol record on a cross-country flight. Which real baseball Hall of Famer is famous for allegedly drinking an extraordinary number of beers on a flight — and what was the claimed number?",
        answer: "Wade Boggs, who claimed to have consumed 64 beers on a cross-country flight",
        acceptableAnswers: ["Wade Boggs", "Wade Boggs and 64 beers", "64 beers"],
        explanation: "Wade Boggs became a folk legend in baseball for his prodigious beer consumption — teammates and Boggs himself have confirmed a number in the 50-70 range on flights. The Always Sunny episode treats his record as a sacred achievement to be beaten.",
      },
    ],
  },
  {
    id: "mv_star_trek",
    group: "TV Shows",
    name: "Star Trek",
    culture: "universal",
    description: "Gene Roddenberry's optimistic vision of humanity's future, carried across seven decades of series, films, and cultural impact.",
    imageUrl: "",
    questions: [
      {
        id: "stk_200_01",
        categoryId: "mv_star_trek",
        tier: 200,
        prompt: "Who is the captain of the USS Enterprise in Star Trek: The Original Series?",
        answer: "Captain James T. Kirk",
        acceptableAnswers: ["Kirk", "James T. Kirk", "Captain Kirk", "James Kirk"],
      },
      {
        id: "stk_200_02",
        categoryId: "mv_star_trek",
        tier: 200,
        prompt: "Mr. Spock is half-human, half-Vulcan. What is the Vulcan salutation he popularized — accompanied by a specific hand gesture?",
        answer: "Live long and prosper",
        acceptableAnswers: ["Live long and prosper", "live long and prosper"],
      },
      {
        id: "stk_200_03",
        categoryId: "mv_star_trek",
        tier: 200,
        prompt: "In the Original Series, the Enterprise famously couldn't land on planets — so crew members were beamed between ship and surface. What was the in-universe name for this transportation system?",
        answer: "The transporter",
        acceptableAnswers: ["the transporter", "transporter"],
      },
      {
        id: "stk_400_01",
        categoryId: "mv_star_trek",
        tier: 400,
        prompt: "Star Trek III: The Search for Spock introduced the Klingon language as a fully speakable tongue. Which linguist was hired to develop it into a complete language — and went on to write a Klingon dictionary?",
        answer: "Marc Okrand",
        acceptableAnswers: ["Marc Okrand"],
        explanation: "Okrand had originally devised fragments of Klingon for Star Trek II. For The Search for Spock, he developed it into a systematic language with grammar, syntax, and vocabulary. His 'The Klingon Dictionary' (1985) sold 300,000+ copies. Klingon is now one of the world's most-studied constructed languages.",
      },
      {
        id: "stk_400_02",
        categoryId: "mv_star_trek",
        tier: 400,
        prompt: "The Original Series episode 'Space Seed' introduced Star Trek's greatest recurring villain, later the subject of a 1982 film. Who is this villain?",
        answer: "Khan Noonien Singh",
        acceptableAnswers: ["Khan", "Khan Noonien Singh"],
        explanation: "'Space Seed' aired in 1967. Ricardo Montalban played Khan as a genetically engineered 20th-century tyrant revived from cryosleep. He returned in Star Trek II: The Wrath of Khan (1982), widely considered the franchise's best film.",
      },
      {
        id: "stk_400_03",
        categoryId: "mv_star_trek",
        tier: 400,
        prompt: "The transporter was actually invented as a practical production solution rather than pure storytelling invention. What budget problem did it solve for the Original Series?",
        answer: "The show couldn't afford to film the Enterprise landing on a planet in every episode — the transporter eliminated the need for expensive landing sequences",
        acceptableAnswers: ["couldn't afford landing sequences", "budget constraint about landing the ship", "too expensive to film the ship landing"],
        explanation: "Gene Roddenberry and the production team devised the transporter to avoid the logistical and financial cost of showing a shuttle or ship landing on location each episode. It became one of the franchise's most iconic elements despite being born of budget necessity.",
      },
      {
        id: "stk_600_01",
        categoryId: "mv_star_trek",
        tier: 600,
        prompt: "Nichelle Nichols, who played Lt. Uhura, nearly left the show after Season 1. Which civil rights icon personally persuaded her to stay — and what argument did he make about why her role was historically important?",
        answer: "Dr. Martin Luther King Jr. — he told her that Uhura was the first Black character on American TV in a non-subservient role, and that her presence on screen showed Black Americans and the world what the future could look like",
        acceptableAnswers: ["Martin Luther King Jr.", "MLK", "Dr. King told her to stay"],
        explanation: "King specifically said that he and his wife watched Star Trek as the one show they allowed their children to watch late because of Uhura. Nichols later worked with NASA to recruit minority and female astronauts, including Sally Ride and Guion Bluford. The story of King's intervention has been confirmed by Nichols in multiple interviews.",
      },
      {
        id: "stk_600_02",
        categoryId: "mv_star_trek",
        tier: 600,
        prompt: "After NBC threatened cancellation following Season 2, Star Trek was saved by one of TV's first organized fan letter-writing campaigns. Approximately how many letters did NBC receive — and what did they do with the show?",
        answer: "NBC received over 100,000 letters (some accounts say up to 1 million over both campaigns) — they renewed the show for a third season but moved it to a death-slot Friday night timeslot, which effectively killed it anyway",
        acceptableAnswers: ["over 100,000 letters", "a massive letter-writing campaign saved it", "fans wrote over 100,000 letters"],
        explanation: "The campaign, largely organized by Bjo Trimble, was unprecedented in TV history. NBC announced the renewal on air mid-episode as a direct result. However, the move to Friday nights at 10pm (a death slot for their audience) ensured cancellation after Season 3.",
      },
      {
        id: "stk_600_03",
        categoryId: "mv_star_trek",
        tier: 600,
        prompt: "Gene Roddenberry's ashes were launched into space twice. What were the two missions, and why is the second launch considered particularly fitting for Star Trek's creator?",
        answer: "A portion of his ashes were launched aboard a Pegasus rocket in 1997. A second portion was carried aboard SpaceX's Falcon 9 Falcon Heavy in 2018 on a mission to deep space — a commercial spaceflight that represented the private space industry Roddenberry's stories helped inspire",
        acceptableAnswers: ["two space launches of his ashes", "1997 and 2018 launches", "Pegasus rocket and SpaceX Falcon Heavy"],
        explanation: "Roddenberry died in 1991. The 1997 Celestis mission orbited Earth. His ashes were among those launched on the 2018 Orbital Test Flight which went to heliocentric orbit — true deep space, like the voyages he depicted.",
      },
    ],
  },
  {
    id: "music_rolling_stones",
    group: "Music",
    name: "The Rolling Stones",
    culture: "universal",
    description: "The world's greatest rock and roll band — six decades of swagger, blues, scandal, and survival.",
    imageUrl: "",
    questions: [
      {
        id: "rst_200_01",
        categoryId: "music_rolling_stones",
        tier: 200,
        prompt: "Mick Jagger and Keith Richards had a famous reunion as young men after a chance encounter on a train platform. What did Richards see Jagger carrying that revealed their shared obsession?",
        answer: "Jagger was carrying Muddy Waters and Chuck Berry records — imported American blues and R&B albums that Richards also loved",
        acceptableAnswers: ["blues records", "Muddy Waters records", "Chuck Berry records", "American blues records"],
        explanation: "Jagger and Richards had grown up near each other in Dartford and known each other as boys, then lost touch. Their 1961 chance meeting at Dartford station — Richards spotting Jagger's Chess Records imports — restarted the friendship that created the Rolling Stones.",
      },
      {
        id: "rst_200_02",
        categoryId: "music_rolling_stones",
        tier: 200,
        prompt: "Which Rolling Stones song begins with the line 'Please allow me to introduce myself, I'm a man of wealth and taste'?",
        answer: "Sympathy for the Devil",
        acceptableAnswers: ["Sympathy for the Devil"],
      },
      {
        id: "rst_200_03",
        categoryId: "music_rolling_stones",
        tier: 200,
        prompt: "The Rolling Stones took their name from a song by which American blues legend?",
        answer: "Muddy Waters",
        acceptableAnswers: ["Muddy Waters", "Muddy Waters' 'Rollin' Stone'"],
        explanation: "The name comes from Muddy Waters' 1950 song 'Rollin' Stone.' Brian Jones named the group after the song when asked by a journalist on short notice. The same song later inspired the name of Rolling Stone magazine.",
      },
      {
        id: "rst_400_01",
        categoryId: "music_rolling_stones",
        tier: 400,
        prompt: "Which guitarist replaced founding member Brian Jones in 1969 and is widely credited with elevating the Stones' playing to its creative peak on albums like 'Sticky Fingers' and 'Exile on Main St.'?",
        answer: "Mick Taylor",
        acceptableAnswers: ["Mick Taylor"],
        explanation: "Taylor joined at 20 years old, directly from John Mayall's Bluesbreakers. His fluid, melodic style is all over the classic 1969–1974 period. He left in 1974 and was replaced by Ronnie Wood. Keith Richards has called this era the Stones' finest musically.",
      },
      {
        id: "rst_400_02",
        categoryId: "music_rolling_stones",
        tier: 400,
        prompt: "Keith Richards was arrested in Toronto in February 1977 on heroin trafficking charges that could have meant years in prison. What unusual condition was attached to his eventual sentence?",
        answer: "He was given a suspended sentence and required to perform a benefit concert for blind people in Canada — he played with his band the New Barbarians for the Canadian National Institute for the Blind",
        acceptableAnswers: ["benefit concert for the blind", "CNIB concert", "perform for the blind", "charity concert for blind people as part of sentencing"],
        explanation: "Judge Lloyd Graburn concluded that Richards' talent meant he could do more good through music than prison. The CNIB benefit at Oshawa, Ontario (April 1979) drew 2,000 fans. Richards has said the experience permanently changed his relationship with heroin.",
      },
      {
        id: "rst_400_03",
        categoryId: "music_rolling_stones",
        tier: 400,
        prompt: "Andrew Loog Oldham managed the Rolling Stones in their early years and deliberately shaped their image in opposition to The Beatles. What specific public persona did he construct for them?",
        answer: "He refused matching outfits, encouraged them to be surly and unsmiling in photos and interviews, and planted the famous ad line 'Would you let your daughter go with a Rolling Stone?' — positioning them as dangerous and antisocial versus the clean-cut Beatles",
        acceptableAnswers: ["the bad boy image", "surly and antisocial versus Beatles", "he made them the anti-Beatles", "refused matching suits and encouraged rebellion"],
        explanation: "Oldham was just 19 when he took them on. He understood that if the Beatles owned 'nice,' the Stones could own 'dangerous.' He also locked Jagger and Richards in a room and told them not to come out until they'd written a song — producing their first originals.",
      },
      {
        id: "rst_600_01",
        categoryId: "music_rolling_stones",
        tier: 600,
        prompt: "'Sympathy for the Devil' began in the studio as an acoustic folk song before transforming into the samba-driven track we know. Which percussionist introduced the rhythm that changed the song — and what is his name?",
        answer: "Rocky Dijon (later known as Rocky Keïta) — he introduced the conga/samba rhythm that converted the song from folk to the Latin-inflected rock track",
        acceptableAnswers: ["Rocky Dijon", "Rocky Keïta", "Rocky Dijon introduced the samba rhythm"],
        explanation: "The entire transformation of 'Sympathy for the Devil' is documented in Jean-Luc Godard's 1968 film 'One Plus One' (Sympathy for the Devil), which filmed multiple recording sessions. You can watch the song evolve from Dylan-esque folk to its final form. Dijon's arrival changes everything.",
      },
      {
        id: "rst_600_02",
        categoryId: "music_rolling_stones",
        tier: 600,
        prompt: "'You Can't Always Get What You Want' (1969) opens with a choral passage that sounds unlike anything else in Stones' output. Which specific choir recorded that opening — and why is their involvement considered an unlikely pairing?",
        answer: "The London Bach Choir — a classical choral organization not associated with rock music — sang the opening 'Oh yeah' passage at producer Jimmy Miller's suggestion",
        acceptableAnswers: ["London Bach Choir", "the London Bach Choir"],
        explanation: "The London Bach Choir was brought in by producer Jimmy Miller. Their conductor initially had no idea they were recording for the Rolling Stones. The choir members reportedly found out halfway through and had mixed feelings — but the performance became iconic.",
      },
      {
        id: "rst_600_03",
        categoryId: "music_rolling_stones",
        tier: 600,
        prompt: "'Exile on Main St.' (1972) was recorded under unusual circumstances. Where did the sessions take place, and why was that location necessary?",
        answer: "At Keith Richards' rented villa Nellcôte in Villefranche-sur-Mer, France — the band had moved there as tax exiles to avoid Britain's 83% supertax on high earners",
        acceptableAnswers: ["Nellcôte in France", "Keith Richards' villa in France", "tax exile in France", "Villefranche-sur-Mer"],
        explanation: "The Inland Revenue had made it financially impossible for the Stones to remain in Britain. They moved to the south of France, where Richards installed a mobile recording studio in Nellcôte's basement. The chaotic, decadent sessions — often starting near midnight — defined the album's raw, loose sound.",
      },
    ],
  },
  {
    id: "music_wu_tang",
    group: "Music",
    name: "Wu-Tang Clan",
    culture: "american",
    description: "Nine MCs from Staten Island who built a mythology out of kung fu films, chess strategy, and five-percent philosophy.",
    imageUrl: "",
    questions: [
      {
        id: "wut_200_01",
        categoryId: "music_wu_tang",
        tier: 200,
        prompt: "The Wu-Tang Clan came up from which New York City borough, often overlooked in the hip-hop geography of Manhattan, Brooklyn, and the Bronx?",
        answer: "Staten Island",
        acceptableAnswers: ["Staten Island", "Staten Island, New York"],
      },
      {
        id: "wut_200_02",
        categoryId: "music_wu_tang",
        tier: 200,
        prompt: "What does C.R.E.A.M. stand for in the Wu-Tang Clan's 1994 classic track from 'Enter the Wu-Tang (36 Chambers)'?",
        answer: "Cash Rules Everything Around Me",
        acceptableAnswers: ["Cash Rules Everything Around Me"],
      },
      {
        id: "wut_200_03",
        categoryId: "music_wu_tang",
        tier: 200,
        prompt: "How many members make up the Wu-Tang Clan?",
        answer: "Nine",
        acceptableAnswers: ["9", "nine", "9 members"],
      },
      {
        id: "wut_400_01",
        categoryId: "music_wu_tang",
        tier: 400,
        prompt: "RZA produced virtually all of Wu-Tang's classic-era beats from a single sampler that became his signature instrument. What machine is it?",
        answer: "The Ensoniq ASR-10",
        acceptableAnswers: ["Ensoniq ASR-10", "ASR-10"],
        explanation: "The Ensoniq ASR-10 was a sampling keyboard popular in early-90s hip-hop. RZA used it to build the dusty, cinematic, lo-fi sound of the Wu-Tang universe. He has said the ASR-10's particular sound — slightly degraded, warm — was integral to the Clan's aesthetic.",
      },
      {
        id: "wut_400_02",
        categoryId: "music_wu_tang",
        tier: 400,
        prompt: "At the 1998 Grammy Awards, Ol' Dirty Bastard crashed the stage when Wu-Tang lost Best Rap Album. What did he say in his rambling, interrupted acceptance speech?",
        answer: "He declared 'Wu-Tang is for the children' — arguing the Grammys should have given Wu-Tang the award because their music was made for the youth",
        acceptableAnswers: ["Wu-Tang is for the children", "he said Wu-Tang is for the children"],
        explanation: "ODB walked on stage mid-ceremony, took the mic, and delivered one of rap's most famous impromptu speeches. He had personally bought outfits for himself and his children to attend, expecting a win. The speech ended with security ushering him offstage. 'Wu-Tang is for the children' became one of hip-hop's most quoted lines.",
      },
      {
        id: "wut_400_03",
        categoryId: "music_wu_tang",
        tier: 400,
        prompt: "Wu-Tang Clan pressed a single physical copy of their secret album 'Once Upon a Time in Shaolin' and sold it for $2 million in 2015. Who bought it — and what happened to it after his criminal conviction?",
        answer: "Martin Shkreli (the pharmaceutical executive who raised drug prices by 5,000%) bought it; it was seized by the U.S. government as part of his securities fraud asset forfeiture and later sold at auction",
        acceptableAnswers: ["Martin Shkreli", "Shkreli", "the government seized it from Shkreli"],
        explanation: "The sale terms included a clause that prevented Shkreli from releasing it commercially for 88 years. After his 2017 fraud conviction, the government seized it. It was eventually sold to a collective called PleasrDAO in 2021 for an undisclosed amount (reported around $4 million).",
      },
      {
        id: "wut_600_01",
        categoryId: "music_wu_tang",
        tier: 600,
        prompt: "Raekwon's 1995 solo debut 'Only Built 4 Cuban Linx...' is credited with pioneering what specific hip-hop subgenre — blending Mafia film aesthetics, luxury brand references, and street crime narrative?",
        answer: "Mafioso rap",
        acceptableAnswers: ["mafioso rap", "mafioso hip-hop", "mob rap", "mafia rap"],
        explanation: "Cuban Linx arrived alongside Nas' 'Illmatic' as a defining document of mid-90s East Coast hip-hop, but its specific contribution was the cinematic crime aesthetic — Mafia nicknames, Scarface references, designer brands as status symbols. It directly influenced Jay-Z, Pusha T, and a generation of rap.",
      },
      {
        id: "wut_600_02",
        categoryId: "music_wu_tang",
        tier: 600,
        prompt: "The entire Wu-Tang mythology is built around a martial arts film whose title inspired the group's name. Which 1983 kung fu film gave the clan their name?",
        answer: "Shaolin and Wu Tang (also known as Shaolin vs. Wu Tang)",
        acceptableAnswers: ["Shaolin and Wu Tang", "Shaolin vs. Wu Tang", "Shaolin vs Wu Tang"],
        explanation: "The 1983 Gordon Liu film 'Shaolin and Wu Tang' (directed by Gordon Liu) dramatizes the rivalry between two martial arts styles. RZA and the Staten Island crew built their concept around the two-school mythology — Staten Island as Shaolin, their collective as Wu-Tang. The 36 Chambers refer to the 36 chambers of the Shaolin Temple.",
      },
      {
        id: "wut_600_03",
        categoryId: "music_wu_tang",
        tier: 600,
        prompt: "Wu-Tang Clan negotiated an unprecedented business structure for a rap act — allowing each member individual freedom while preserving the collective brand. What exactly did this arrangement allow?",
        answer: "Each member could sign solo deals with any label they chose while the Wu-Tang group brand remained collectively owned — Method Man signed to Def Jam, ODB to Elektra, Ghostface to Epic, and so on, while Wu-Tang albums were separate group enterprises",
        acceptableAnswers: ["each member signed solo deals with different labels", "solo label independence", "members could sign to different labels independently"],
        explanation: "This was a radical model in 1993. RZA spent two years building hype before the debut, then leveraged that hype to get individual deals for each member. The arrangement made Wu-Tang one of the first rap collectives to function as both a group and a sovereign business entity.",
      },
    ],
  },
  {
    id: "mu_taylor_swift",
    group: "Music",
    name: "Taylor Swift",
    culture: "american",
    description: "The most culturally dominant artist of her generation — country prodigy turned pop superstar turned industry force.",
    imageUrl: "",
    questions: [
      {
        id: "tay_200_01",
        categoryId: "mu_taylor_swift",
        tier: 200,
        prompt: "Taylor Swift launched her career as a teenager in which music genre before crossing over into pop?",
        answer: "Country music",
        acceptableAnswers: ["country", "country music"],
      },
      {
        id: "tay_200_02",
        categoryId: "mu_taylor_swift",
        tier: 200,
        prompt: "What is the official name for Taylor Swift's fanbase?",
        answer: "Swifties",
        acceptableAnswers: ["Swifties"],
      },
      {
        id: "tay_200_03",
        categoryId: "mu_taylor_swift",
        tier: 200,
        prompt: "Taylor Swift has re-recorded her first six albums to reclaim artistic and financial control. What phrase does she add to each re-recorded album's title to distinguish it from the originals?",
        answer: "(Taylor's Version)",
        acceptableAnswers: ["Taylor's Version", "(Taylor's Version)"],
      },
      {
        id: "tay_400_01",
        categoryId: "mu_taylor_swift",
        tier: 400,
        prompt: "In 2019, manager Scooter Braun acquired Taylor Swift's first six album masters without her knowledge. What was Taylor's public and creative response?",
        answer: "She announced she would re-record all six albums as 'Taylor's Version' — so that fans streaming or licensing her music would use versions she owned, effectively devaluing the original masters",
        acceptableAnswers: ["she re-recorded the albums as Taylor's Version", "Taylor's Version response", "she publicly denounced him and re-recorded"],
        explanation: "Swift called the acquisition her 'worst case scenario' and accused Braun of years of bullying. The re-recording campaign has been commercially successful — 'Fearless (Taylor's Version)' debuted at #1. The move sparked industry-wide conversation about artist ownership of master recordings.",
      },
      {
        id: "tay_400_02",
        categoryId: "mu_taylor_swift",
        tier: 400,
        prompt: "Taylor Swift's 2020 album 'folklore' was an unexpected pivot from glossy pop. Primarily produced with Aaron Dessner of which indie rock band, the album earned Swift her fourth Album of the Year Grammy?",
        answer: "The National",
        acceptableAnswers: ["The National", "Aaron Dessner of The National"],
        explanation: "Dessner and Swift worked remotely during COVID lockdown. 'folklore' was announced with 12 hours' notice and released the same day. It debuted at #1 in 35 countries and won the Album of the Year Grammy (2021), making Swift the first woman to win the award three times.",
      },
      {
        id: "tay_400_03",
        categoryId: "mu_taylor_swift",
        tier: 400,
        prompt: "Swift's early country songwriting was shaped by a co-writer who worked with her on many hits including 'You Belong With Me.' Who is this songwriter?",
        answer: "Liz Rose",
        acceptableAnswers: ["Liz Rose"],
        explanation: "Liz Rose co-wrote some of Swift's most enduring early tracks, including 'You Belong With Me,' 'White Horse,' and 'Tim McGraw.' Rose has described the sessions as flowing effortlessly, with Swift often arriving with nearly complete songs. Rose won a Grammy for their collaboration.",
      },
      {
        id: "tay_600_01",
        categoryId: "mu_taylor_swift",
        tier: 600,
        prompt: "The 2023-2024 Eras Tour's Ticketmaster presale collapse became a political event, not just a cultural one. What real government action did the ticketing chaos trigger?",
        answer: "U.S. Senate Judiciary Committee hearings on antitrust and the live music monopoly — senators directly questioned Live Nation and Ticketmaster executives about their monopoly control, using the Eras Tour as the primary exhibit",
        acceptableAnswers: ["Senate antitrust hearings", "Senate Judiciary Committee hearings", "Congress investigated Ticketmaster", "antitrust hearings on Live Nation"],
        explanation: "The presale in November 2022 saw Ticketmaster's systems collapse under demand. Artists, fans, and legislators cited it as proof of monopoly harm. The DOJ later filed an antitrust lawsuit against Live Nation in 2024 seeking to break up the company.",
      },
      {
        id: "tay_600_02",
        categoryId: "mu_taylor_swift",
        tier: 600,
        prompt: "Taylor Swift's most important producer collaborator — who shaped '1989,' 'reputation,' 'Lover,' and 'folklore/evermore' — was previously a member of which indie pop band?",
        answer: "fun. (the band) — Jack Antonoff was the drummer and co-founder of fun. before becoming Swift's primary creative partner",
        acceptableAnswers: ["fun.", "the band fun.", "Jack Antonoff was in fun."],
        explanation: "Jack Antonoff rose to fame as a member of fun. ('We Are Young,' 'Some Nights') and Steel Train before pivoting to production. His work with Swift, Lorde, Lana Del Rey, and St. Vincent made him the defining pop producer of the 2010s-2020s.",
      },
      {
        id: "tay_600_03",
        categoryId: "mu_taylor_swift",
        tier: 600,
        prompt: "On 'Red (Taylor's Version),' one track was released in its complete original length after being cut for the original 2012 album. What is the song's full title, and why does the 10-minute version matter to fans beyond just length?",
        answer: "'All Too Well (10 Minute Version) (Taylor's Version)' — the full version had been a mythologized 'lost' recording circulating in fan lore for years; Swift releasing it was a statement of artistic reclamation, accompanied by a short film she wrote and directed",
        acceptableAnswers: ["All Too Well", "All Too Well 10 Minute Version", "All Too Well (10 Minute Version) (Taylor's Version)"],
        explanation: "Fan accounts of Swift performing a longer version of 'All Too Well' at concerts in 2012 had circulated for nearly a decade. The re-release confirmed the legend. The short film starred Sadie Sink and Dylan O'Brien. 'All Too Well (10 Minute Version)' became the longest song to hit #1 on the Billboard Hot 100.",
      },
    ],
  },
  {
    id: "music_metallica",
    group: "Music",
    name: "Metallica",
    culture: "american",
    description: "Thrash metal's biggest band — from Bay Area speed demons to stadium conquerors, with every controversy in between.",
    imageUrl: "",
    questions: [
      {
        id: "mtl_200_01",
        categoryId: "music_metallica",
        tier: 200,
        prompt: "Metallica is one of the 'Big Four' of thrash metal. Name the other three bands in that group.",
        answer: "Megadeth, Slayer, and Anthrax",
        acceptableAnswers: ["Megadeth, Slayer, Anthrax", "Megadeth Slayer Anthrax"],
      },
      {
        id: "mtl_200_02",
        categoryId: "music_metallica",
        tier: 200,
        prompt: "What is the name of Metallica's 1986 album whose title track is a metaphor for addiction's control over a person — widely considered one of metal's greatest songs?",
        answer: "Master of Puppets",
        acceptableAnswers: ["Master of Puppets"],
      },
      {
        id: "mtl_200_03",
        categoryId: "music_metallica",
        tier: 200,
        prompt: "Metallica's beloved bassist Cliff Burton died in a tragic accident in 1986. In what country did the tour bus crash occur?",
        answer: "Sweden",
        acceptableAnswers: ["Sweden"],
        explanation: "The crash occurred near Ljungby, Sweden in the early hours of September 27, 1986. Burton was thrown through a window when the bus overturned on an icy road. He was 24. His death remains one of metal's greatest tragedies.",
      },
      {
        id: "mtl_400_01",
        categoryId: "music_metallica",
        tier: 400,
        prompt: "Metallica's original lead guitarist was fired in 1983 due to alcohol problems and personality clashes. He went on to found one of metal's most technically acclaimed bands. Who is he?",
        answer: "Dave Mustaine",
        acceptableAnswers: ["Dave Mustaine"],
        explanation: "Mustaine was driven from New York to San Francisco and told the band via a note. He has spoken extensively about the rejection fueling decades of competitive rage. His band Megadeth has sold over 50 million albums — directly motivated, Mustaine says, by his desire to outdo Metallica.",
      },
      {
        id: "mtl_400_02",
        categoryId: "music_metallica",
        tier: 400,
        prompt: "In 2000, Metallica sued Napster for copyright infringement. Lars Ulrich famously submitted a list to Napster of users who had shared Metallica songs. How many specific usernames were on that list?",
        answer: "317,377",
        acceptableAnswers: ["317,377", "317377", "over 300,000 usernames", "around 317,000"],
        explanation: "Lars Ulrich personally delivered the list — compiled by NetPD on Metallica's behalf — to Napster's offices in a large box. The gesture was meant to demonstrate the scale of the infringement and force Napster to ban the users. It became one of the most mocked moments in rock history, cementing Metallica's reputation as anti-fan.",
      },
      {
        id: "mtl_400_03",
        categoryId: "music_metallica",
        tier: 400,
        prompt: "'One' from '...And Justice for All' was Metallica's first music video. What acclaimed anti-war film did they license footage from to create the video?",
        answer: "Johnny Got His Gun (1971), based on Dalton Trumbo's 1939 novel",
        acceptableAnswers: ["Johnny Got His Gun", "Dalton Trumbo's Johnny Got His Gun"],
        explanation: "The film depicts a quadruple amputee veteran who has lost his arms, legs, sight, hearing, and speech but remains conscious. Its imagery perfectly matched the song's subject — a soldier who survives a landmine explosion and wants to die. Metallica liked the film so much they helped finance its theatrical re-release.",
      },
      {
        id: "mtl_600_01",
        categoryId: "music_metallica",
        tier: 600,
        prompt: "'...And Justice for All' (1988) is notorious for one controversial production decision that fans still argue about. What happened to Jason Newsted's bass on the album?",
        answer: "Newsted's bass was mixed almost completely out of the album — virtually inaudible throughout — widely attributed to deliberate hazing by James Hetfield and Lars Ulrich against the new bassist who replaced the beloved Cliff Burton",
        acceptableAnswers: ["bass was mixed out", "Jason's bass can't be heard", "bass buried in the mix", "bass was intentionally silenced as hazing"],
        explanation: "Newsted has confirmed the hazing was real. Producers have since said they were told to minimize his contribution. The album's dry, bass-less sound is now considered both iconic and a regrettable statement of internal band politics. A fan-made 'Metallica Justice for All' bass remix went viral in 2010.",
      },
      {
        id: "mtl_600_02",
        categoryId: "music_metallica",
        tier: 600,
        prompt: "Metallica's 2004 documentary 'Some Kind of Monster' captured the band in crisis during the recording of 'St. Anger.' What therapeutic intervention did the entire band undergo during those sessions?",
        answer: "Extended group therapy with performance coach Phil Towle, who sat in on band rehearsals and recording sessions for months — addressing James Hetfield's addiction/rehab, the firing of bassist Jason Newsted, and the ego conflicts between Lars and James",
        acceptableAnswers: ["group therapy with Phil Towle", "band therapy", "they underwent group therapy", "Phil Towle as band therapist"],
        explanation: "Towle was originally hired for a short engagement and ended up staying for over two years. The documentary captures extraordinary footage of multi-millionaire rock stars in therapy arguing about feelings. Towle's continued presence eventually became its own source of conflict.",
      },
      {
        id: "mtl_600_03",
        categoryId: "music_metallica",
        tier: 600,
        prompt: "In 'St. Anger' (2003), Lars Ulrich made a specific drum production choice that became one of the most divisive sounds in metal history. What did he do with his snare drum?",
        answer: "He left the snare untightened and unpadded, producing a loud, clanging, trash-can-like metallic ring on every hit instead of the standard tight snare crack",
        acceptableAnswers: ["the snare sounds like a trash can", "Lars didn't tune the snare", "loose snare producing a tinny ring", "trash can snare sound"],
        explanation: "Ulrich wanted the drums to sound 'live' and 'real' — raw and unprocessed. The result is a snare tone almost universally described as a garbage can lid. Metallica has since acknowledged it was a mistake. The St. Anger snare became an internet meme and shorthand for bad production decisions.",
      },
    ],
  },
  {
    id: "mv_harry_potter",
    group: "Movies & TV",
    name: "Harry Potter",
    culture: "universal",
    description: "J.K. Rowling's wizarding world — from a boy living under the stairs to the most widely read fantasy series in history.",
    imageUrl: "",
    questions: [
      {
        id: "hpt_200_01",
        categoryId: "mv_harry_potter",
        tier: 200,
        prompt: "What is the name of the fictional sport played on broomsticks in Harry Potter, where players try to score through hoops while the Seeker chases a winged golden ball?",
        answer: "Quidditch",
        acceptableAnswers: ["Quidditch"],
      },
      {
        id: "hpt_200_02",
        categoryId: "mv_harry_potter",
        tier: 200,
        prompt: "Harry Potter is marked by Voldemort's attack as an infant with a distinctive scar. What shape is it?",
        answer: "Lightning bolt",
        acceptableAnswers: ["lightning bolt", "a lightning bolt", "lightning bolt shape"],
      },
      {
        id: "hpt_200_03",
        categoryId: "mv_harry_potter",
        tier: 200,
        prompt: "Name all four houses at Hogwarts School of Witchcraft and Wizardry.",
        answer: "Gryffindor, Slytherin, Ravenclaw, and Hufflepuff",
        acceptableAnswers: ["Gryffindor, Slytherin, Ravenclaw, Hufflepuff", "Gryffindor Slytherin Ravenclaw Hufflepuff"],
      },
      {
        id: "hpt_400_01",
        categoryId: "mv_harry_potter",
        tier: 400,
        prompt: "In Harry Potter and the Deathly Hallows, Voldemort created seven Horcruxes — objects containing hidden pieces of his soul. Name all seven.",
        answer: "Tom Riddle's Diary, Marvolo Gaunt's Ring, Slytherin's Locket, Hufflepuff's Cup, Ravenclaw's Diadem, Nagini the snake, and Harry Potter himself (an unintentional Horcrux created when Voldemort failed to kill Harry)",
        acceptableAnswers: ["Tom Riddle's Diary, Gaunt's Ring, Slytherin's Locket, Hufflepuff's Cup, Ravenclaw's Diadem, Nagini, Harry Potter", "diary ring locket cup diadem Nagini Harry", "all seven horcruxes"],
      },
      {
        id: "hpt_400_02",
        categoryId: "mv_harry_potter",
        tier: 400,
        prompt: "In the Triwizard Tournament (Goblet of Fire), Hogwarts competes against two other wizarding schools. Name them both.",
        answer: "Beauxbatons Academy of Magic and Durmstrang Institute",
        acceptableAnswers: ["Beauxbatons and Durmstrang", "Beauxbatons Academy of Magic and Durmstrang Institute"],
        explanation: "Beauxbatons is described as located in the French Pyrenees (later films implied Southern France). Durmstrang is set in Scandinavia or Northern Europe and is known for teaching the Dark Arts. Viktor Krum and Fleur Delacour represent these schools.",
      },
      {
        id: "hpt_400_03",
        categoryId: "mv_harry_potter",
        tier: 400,
        prompt: "In Prisoner of Azkaban, Hermione uses a magical device to attend extra classes that would otherwise conflict with each other. What is this object, and what does it do?",
        answer: "A Time-Turner — it allows the user to reverse time by hours, enabling them to be in two places at once",
        acceptableAnswers: ["Time-Turner", "time turner"],
      },
      {
        id: "hpt_600_01",
        categoryId: "mv_harry_potter",
        tier: 600,
        prompt: "Snape's true role is only revealed in the final book. What are the two key reasons Dumbledore trusted Snape with the most dangerous double-agent assignment in the war against Voldemort?",
        answer: "1) Snape loved Lily Potter and felt guilty for inadvertently causing her death — having overheard and reported the prophecy to Voldemort; 2) Snape killed Dumbledore on Dumbledore's own orders — a mercy killing that preserved Snape's cover as Voldemort's most loyal servant",
        acceptableAnswers: ["love for Lily and mercy killing Dumbledore on orders", "guilt over Lily's death and Dumbledore's instruction to kill him", "Snape loved Lily and killed Dumbledore on purpose per Dumbledore's request"],
      },
      {
        id: "hpt_600_02",
        categoryId: "mv_harry_potter",
        tier: 600,
        prompt: "J.K. Rowling later introduced the American wizarding school Ilvermorny, with its own four houses. Name all four.",
        answer: "Horned Serpent, Wampus, Thunderbird, and Pukwudgie",
        acceptableAnswers: ["Horned Serpent, Wampus, Thunderbird, Pukwudgie", "Horned Serpent Wampus Thunderbird Pukwudgie"],
        explanation: "Ilvermorny was founded on Mount Greylock in Massachusetts. The four houses are named after creatures from Native American legend: the Horned Serpent (scholars), Wampus (warriors), Thunderbird (adventurers), and Pukwudgie (healers).",
      },
      {
        id: "hpt_600_03",
        categoryId: "mv_harry_potter",
        tier: 600,
        prompt: "In the Fantastic Beasts prequel series, Dumbledore cannot confront Grindelwald directly due to something they did as young men. What bound them — and what was the nature of their relationship at the time?",
        answer: "They made a blood pact as teenagers — a magical oath binding each not to move against the other; they were also in a romantic relationship during their summer together in Godric's Hollow before the tragedy involving Ariana Dumbledore",
        acceptableAnswers: ["a blood pact not to fight each other", "blood oath preventing them from fighting", "they swore a blood pact and were romantically involved"],
        explanation: "Rowling confirmed Dumbledore and Grindelwald's romantic relationship, describing it as an 'all-consuming' first love. The blood pact is a vial-like object that Newt Scamander destroys in The Crimes of Grindelwald, theoretically freeing Dumbledore to act against him.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending. File may have already been modified.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 57 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
