#!/usr/bin/env python3
"""Insert wave 77 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_euphoria",
    group: "tv",
    name: "Euphoria",
    culture: "american",
    description: "Glitter, trauma, and Gen Z — high school through a neon-drenched lens.",
    imageUrl: "",
    questions: [
      { id: "eup_200_01", categoryId: "tv_euphoria", tier: 200, prompt: "Who plays the lead role of Rue Bennett, a teenager struggling with drug addiction?", answer: "Zendaya", explanation: "Zendaya won two Emmy Awards for her portrayal of Rue." },
      { id: "eup_200_02", categoryId: "tv_euphoria", tier: 200, prompt: "What visual style is Euphoria known for, setting it apart from other teen dramas?", answer: "Cinematic, neon-lit visuals with elaborate makeup, bold camera work, and a film-quality aesthetic rarely seen in TV", acceptableAnswers: ["Cinematic neon visuals", "Neon-lit film quality cinematography", "Bold cinematic visual style"], explanation: "Euphoria's visual language — shot by Marcel Rev — looks more like art cinema than teen TV." },
      { id: "eup_200_03", categoryId: "tv_euphoria", tier: 200, prompt: "What is the central struggle that Rue faces throughout both seasons?", answer: "Opioid addiction — specifically relapsing after leaving rehab and trying to stay clean while dealing with trauma and depression", acceptableAnswers: ["Drug addiction", "Opioid addiction and relapse", "Staying clean from drugs"], explanation: "Euphoria's depiction of addiction is widely praised as one of TV's most honest." },
      { id: "eup_400_01", categoryId: "tv_euphoria", tier: 400, prompt: "What is the structure of each episode's opening, where Rue narrates different characters' backstories?", answer: "Each episode typically opens with Rue narrating a deep dive into a supporting character's history and psychology, providing context for their current behavior — functioning as mini-documentaries within the show", acceptableAnswers: ["Rue narrates character backstory openings", "Narrated character history segments", "Mini-documentary backstory openings"], explanation: "These narrated sections give every character psychological depth beyond typical teen drama." },
      { id: "eup_400_02", categoryId: "tv_euphoria", tier: 400, prompt: "What makes the Season 2 intervention scene between Rue and her family one of TV's most intense sequences?", answer: "A nearly 20-minute sequence where Rue's addiction is confronted — she lashes out at her mother, sister, and friends with increasingly cruel truths while trying to escape. It's shot in long, claustrophobic takes and Zendaya's performance is devastatingly raw", acceptableAnswers: ["20-minute intervention with cruel outbursts", "Rue attacks family during intervention sequence", "Extended raw intervention scene"], explanation: "The intervention sequence is widely considered the show's peak — and one of the best-acted scenes on TV." },
      { id: "eup_400_03", categoryId: "tv_euphoria", tier: 400, prompt: "Who is the show's creator, and how does his personal background inform the show's authenticity about addiction?", answer: "Sam Levinson — he is a recovering drug addict himself, and has said the show draws from his own experiences with substance abuse during his youth", acceptableAnswers: ["Sam Levinson, recovering addict", "Levinson based it on his own addiction", "Creator is a former addict"], explanation: "Levinson's personal experience gives the show's addiction portrayal an authenticity that's hard to fake." },
      { id: "eup_600_01", categoryId: "tv_euphoria", tier: 600, prompt: "What are the two 'special episodes' that aired between Seasons 1 and 2 during COVID, and why are they considered some of the show's best work?", answer: "Two bottle episodes — one with Rue talking to her sponsor Ali, one with Jules in therapy — filmed during COVID with minimal crew. Both are essentially two-person dialogue scenes that achieve more emotional depth than most full episodes through pure performance and writing", acceptableAnswers: ["COVID bottle episodes with Rue/Ali and Jules therapy", "Two-person dialogue specials filmed during pandemic", "Ali conversation and Jules therapy episodes"], explanation: "The constraints of COVID produced two of the show's most intimate and powerful episodes." },
      { id: "eup_600_02", categoryId: "tv_euphoria", tier: 600, prompt: "What is the 'Lexi's play' episode in Season 2, and how does it function as meta-commentary on the show itself?", answer: "Lexi stages a play based on her friends' lives — the audience (both in-show and real) watches a theatrical retelling of events we've already seen, with characters reacting to seeing themselves portrayed. It's the show commenting on its own storytelling: who has the right to tell other people's stories?", acceptableAnswers: ["Play retelling the show's events as meta-commentary", "Lexi's play about friends as story-within-story", "Meta play questioning who owns others' stories"], explanation: "The play episode asks whether Euphoria itself — dramatizing real teen suffering — is exploitative." },
      { id: "eup_600_03", categoryId: "tv_euphoria", tier: 600, prompt: "What production controversy surrounded Season 3's development, and what concerns did cast members reportedly raise?", answer: "Season 3 faced years of delays, with reports of Sam Levinson rewriting scripts repeatedly, creative disagreements with HBO, and some cast members reportedly uncomfortable with the direction. Concerns included whether the show glamorizes the behavior it claims to critique, and the power dynamic of a male creator dictating vulnerable scenes", acceptableAnswers: ["Years of delays, rewrites, cast concerns about direction", "Production turmoil and glamorization debate", "Levinson rewrites and power dynamic concerns"], explanation: "The behind-the-scenes struggles mirror the show's themes of control and vulnerability." },
    ],
  },
  {
    id: "mu_johnny_cash_deep",
    group: "music",
    name: "Johnny Cash Deep Cuts",
    culture: "american",
    description: "The Man in Black — prison concerts, American Recordings, and a life of contradictions.",
    imageUrl: "",
    questions: [
      { id: "jcd_200_01", categoryId: "mu_johnny_cash_deep", tier: 200, prompt: "What was Johnny Cash's signature look that he adopted early in his career?", answer: "All black clothing — he became known as 'The Man in Black'", acceptableAnswers: ["All black", "Man in Black", "Wearing all black"], explanation: "Cash said he wore black for 'the poor and beaten down' and those in prison." },
      { id: "jcd_200_02", categoryId: "mu_johnny_cash_deep", tier: 200, prompt: "What famous live album was recorded at a California prison in 1968?", answer: "At Folsom Prison", acceptableAnswers: ["At Folsom Prison", "Johnny Cash at Folsom Prison"], explanation: "The album revived Cash's career and became one of the greatest live albums ever." },
      { id: "jcd_200_03", categoryId: "mu_johnny_cash_deep", tier: 200, prompt: "What country music legend was Johnny Cash married to for 35 years?", answer: "June Carter Cash", acceptableAnswers: ["June Carter", "June Carter Cash"], explanation: "Their love story is one of music's most famous romances." },
      { id: "jcd_400_01", categoryId: "mu_johnny_cash_deep", tier: 400, prompt: "What was the Million Dollar Quartet, and where did it happen?", answer: "A spontaneous jam session at Sun Records in Memphis on December 4, 1956, featuring Johnny Cash, Elvis Presley, Jerry Lee Lewis, and Carl Perkins — four future legends in one room", acceptableAnswers: ["Cash, Elvis, Lewis, Perkins at Sun Records", "Four legends jamming at Sun Studios", "Spontaneous Sun Records session with Elvis Cash Lewis Perkins"], explanation: "Sam Phillips happened to leave the tape rolling, capturing one of music's most legendary moments." },
      { id: "jcd_400_02", categoryId: "mu_johnny_cash_deep", tier: 400, prompt: "What was Cash's relationship with drugs and his eventual recovery?", answer: "He was severely addicted to amphetamines and barbiturates for over a decade — his addiction nearly destroyed his career and marriage. June Carter and her family helped him get clean, and he credited his faith and June for saving his life", acceptableAnswers: ["Amphetamine and barbiturate addiction, June helped recovery", "Years of pill addiction, saved by June Carter", "Drug addiction nearly destroyed him, June helped him recover"], explanation: "Cash's openness about addiction made him a pioneer in destigmatizing substance abuse." },
      { id: "jcd_400_03", categoryId: "mu_johnny_cash_deep", tier: 400, prompt: "What was the Johnny Cash Show (1969-1971), and why was it culturally significant?", answer: "A prime-time ABC variety show where Cash invited guests ranging from Bob Dylan to Louis Armstrong to Neil Young — he used his platform to showcase diverse artists and openly supported civil rights and prison reform on national TV", acceptableAnswers: ["TV variety show with diverse guests and political statements", "ABC show featuring diverse artists and social causes", "Cash's TV show promoting civil rights and reform"], explanation: "Cash used his mainstream platform for radical inclusion at a time when that was genuinely risky." },
      { id: "jcd_600_01", categoryId: "mu_johnny_cash_deep", tier: 600, prompt: "What is the story behind the American Recordings album series with Rick Rubin, and how did it save Cash from irrelevance?", answer: "After Nashville abandoned Cash in the 80s-90s, producer Rick Rubin recorded him solo with just an acoustic guitar, covering songs by Nine Inch Nails, Soundgarden, Tom Petty, and Depeche Mode. The stripped-down approach made Cash relevant to younger generations and produced the iconic 'Hurt' video — filmed shortly before his death, it became one of the most emotionally devastating music videos ever made", acceptableAnswers: ["Rubin solo recordings with rock covers, Hurt video near death", "Nashville abandoned him, Rubin revived with stripped covers", "American Recordings acoustic covers saved his legacy"], explanation: "Trent Reznor said Cash's 'Hurt' cover made the song feel like it had always been Cash's." },
      { id: "jcd_600_02", categoryId: "mu_johnny_cash_deep", tier: 600, prompt: "What is the truth about whether Johnny Cash actually served time in prison, despite his famous prison concerts?", answer: "He never served a prison sentence — he was arrested seven times (mostly for drug-related offenses and minor incidents) but only spent a few nights in jail. His prison concerts came from genuine empathy for inmates, not personal experience. He spent decades advocating for prison reform without having been an inmate himself", acceptableAnswers: ["Never served time, only brief jail stays", "No prison sentence despite image", "Arrested but never imprisoned, advocated for prisoners"], explanation: "The gap between Cash's image and reality makes his advocacy more remarkable — he championed prisoners from choice, not shared experience." },
      { id: "jcd_600_03", categoryId: "mu_johnny_cash_deep", tier: 600, prompt: "What happened in the final months of Cash's life, including his relationship with June's death and his final recordings?", answer: "June died on May 15, 2003; Cash was devastated but continued recording, saying June would have wanted him to keep making music. He died four months later on September 12, 2003. In those final months, he recorded some of his most powerful material, including 'Hurt' and other American Recordings tracks — working through grief and his own mortality with unflinching honesty", acceptableAnswers: ["June died first, he recorded through grief until dying 4 months later", "Kept recording after June's death, died months later", "Recorded powerful material between June's death and his own"], explanation: "Cash's final work, created while dying and grieving, represents art at its most raw and human." },
    ],
  },
  {
    id: "vg_witcher3_deep",
    group: "video_games",
    name: "The Witcher 3 Deep Cuts",
    culture: "universal",
    description: "White Wolf — monster contracts, moral grey areas, and Gwent.",
    imageUrl: "",
    questions: [
      { id: "w3d_200_01", categoryId: "vg_witcher3_deep", tier: 200, prompt: "What is a 'Witcher' in the game's world?", answer: "A professional monster hunter — humans who undergo dangerous mutations as children, gaining enhanced abilities to fight supernatural creatures for pay", acceptableAnswers: ["Professional monster hunter", "Mutated monster hunter", "Enhanced human monster slayer"], explanation: "Witchers are outsiders — feared and distrusted despite protecting communities from monsters." },
      { id: "w3d_200_02", categoryId: "vg_witcher3_deep", tier: 200, prompt: "What is the name of the card game within The Witcher 3 that became so popular it spawned its own standalone game?", answer: "Gwent", explanation: "Gwent became so beloved that CD Projekt Red released it as a standalone free-to-play game." },
      { id: "w3d_200_03", categoryId: "vg_witcher3_deep", tier: 200, prompt: "Who is Geralt searching for throughout the main story of The Witcher 3?", answer: "Ciri (Cirilla) — his adopted daughter who possesses Elder Blood powers and is being hunted by the Wild Hunt", acceptableAnswers: ["Ciri", "Cirilla", "His adopted daughter Ciri"], explanation: "The search for Ciri frames the entire main quest across multiple regions." },
      { id: "w3d_400_01", categoryId: "vg_witcher3_deep", tier: 400, prompt: "What is the 'Bloody Baron' questline, and why is it considered one of gaming's greatest quest designs?", answer: "A morally complex quest where Geralt helps a drunken, abusive warlord find his missing wife and daughter — the Baron is sympathetic and monstrous simultaneously, and the quest has multiple outcomes where there's no clear 'good' choice", acceptableAnswers: ["Morally grey quest about an abusive father", "Complex baron quest with no good outcome", "Abusive baron questline with difficult moral choices"], explanation: "The Bloody Baron quest is the gold standard for morally grey storytelling in games." },
      { id: "w3d_400_02", categoryId: "vg_witcher3_deep", tier: 400, prompt: "What makes the 'Hearts of Stone' DLC villain Gaunter O'Dimm one of gaming's most terrifying antagonists?", answer: "He appears as a harmless traveling merchant but is essentially the Devil — he grants wishes that twist against the wisher, stops time, and is seemingly omnipotent. His calm demeanor and nursery rhyme make him scarier than any monster", acceptableAnswers: ["Devil figure disguised as merchant", "Omnipotent wish-granting trickster", "Calm all-powerful evil hiding as normal man"], explanation: "O'Dimm is terrifying because he's unfailingly polite while being genuinely unstoppable." },
      { id: "w3d_400_03", categoryId: "vg_witcher3_deep", tier: 400, prompt: "What are the three possible endings for Ciri, and what determines which one occurs?", answer: "Ciri lives as a Witcher (best), Ciri becomes Empress of Nilfgaard (bittersweet), or Ciri dies (worst) — determined not by big decisions but by small supportive moments: did you let her make her own choices, did you cheer her up, did you trust her?", acceptableAnswers: ["Witcher, Empress, or death based on emotional support", "Three endings based on how you treated Ciri", "Parenting choices determine Ciri's fate"], explanation: "The endings are decided by parenting decisions, not combat or quests — a brilliant design choice." },
      { id: "w3d_600_01", categoryId: "vg_witcher3_deep", tier: 600, prompt: "What makes the 'Blood and Wine' DLC's fairy tale world of the Land of a Thousand Fables so remarkable in game design?", answer: "An entire fairy tale dimension where classic stories have gone wrong — Jack and the Beanstalk Jack is a skeleton, Rapunzel hanged herself with her hair, the Three Bears ate Goldilocks. It uses familiar childhood stories to create horror, commenting on how innocence decays", acceptableAnswers: ["Corrupted fairy tales creating horror", "Dark twisted versions of children's stories", "Fairy tale world gone wrong with dark twists"], explanation: "The Land of a Thousand Fables turns childhood nostalgia into sophisticated horror commentary." },
      { id: "w3d_600_02", categoryId: "vg_witcher3_deep", tier: 600, prompt: "How does The Witcher 3 handle the 'lesser evil' theme from the original books, and what is Geralt's actual philosophy?", answer: "Geralt claims neutrality — 'Evil is evil, lesser, greater, middling — makes no difference.' But the game constantly forces him to choose between evils, showing his neutrality is impossible. Every major choice has negative consequences for someone. The game argues that refusing to choose IS a choice, and often the worst one", acceptableAnswers: ["Forced to choose between evils despite claiming neutrality", "Neutrality is impossible, every choice harms someone", "Evil is evil philosophy constantly challenged by forced choices"], explanation: "The game's moral framework is built on the impossibility of moral purity in a corrupt world." },
      { id: "w3d_600_03", categoryId: "vg_witcher3_deep", tier: 600, prompt: "What was the controversy around CD Projekt Red's crunch culture during The Witcher 3's development, and how did it contradict the company's public image?", answer: "Despite marketing itself as a pro-developer 'gamers' company, CDPR enforced severe crunch — developers worked 100+ hour weeks for months. Employees reported burnout, health problems, and broken relationships. The irony: a game about exploitation and moral grey areas was built through exploitation of its own workers", acceptableAnswers: ["100+ hour weeks despite pro-developer image", "Severe crunch contradicting company values", "Workers exploited to make game about exploitation"], explanation: "The crunch revelations challenged the industry narrative that 'passion' justifies unsustainable working conditions." },
    ],
  },
  {
    id: "mv_christopher_nolan",
    group: "movies",
    name: "Christopher Nolan",
    culture: "universal",
    description: "Time, obsession, and IMAX — the architect of modern blockbuster cinema.",
    imageUrl: "",
    questions: [
      { id: "nln_200_01", categoryId: "mv_christopher_nolan", tier: 200, prompt: "What Christopher Nolan trilogy redefined superhero films with a dark, realistic take on Batman?", answer: "The Dark Knight Trilogy (Batman Begins, The Dark Knight, The Dark Knight Rises)", acceptableAnswers: ["The Dark Knight trilogy", "Batman trilogy", "Dark Knight"], explanation: "Heath Ledger's Joker in The Dark Knight is considered one of cinema's greatest performances." },
      { id: "nln_200_02", categoryId: "mv_christopher_nolan", tier: 200, prompt: "What Nolan film involves entering people's dreams to plant an idea in someone's mind?", answer: "Inception", explanation: "Inception's spinning top ending became one of cinema's most debated final shots." },
      { id: "nln_200_03", categoryId: "mv_christopher_nolan", tier: 200, prompt: "What film format does Nolan champion, shooting many of his films on 70mm?", answer: "IMAX (and 70mm film)", acceptableAnswers: ["IMAX", "70mm IMAX", "70mm film"], explanation: "Nolan is the biggest advocate for shooting on physical film rather than digital." },
      { id: "nln_400_01", categoryId: "mv_christopher_nolan", tier: 400, prompt: "What is the time structure of 'Dunkirk,' and how does it create tension through non-linear storytelling?", answer: "Three storylines running on different timescales simultaneously — the beach (one week), the sea (one day), the air (one hour). They converge at the climax, creating escalating tension from the compression of time", acceptableAnswers: ["Three timescales: week, day, hour converging", "Non-linear three-timeline structure", "Beach week, sea day, air hour"], explanation: "Dunkirk's structure makes the audience experience time subjectively, matching the characters' desperation." },
      { id: "nln_400_02", categoryId: "mv_christopher_nolan", tier: 400, prompt: "What is the central concept of 'Tenet,' and what word describes the time-manipulation technology?", answer: "Inversion — objects and people can have their entropy reversed, moving backwards through time while the rest of the world moves forward. The film's action sequences feature forward and reverse time simultaneously", acceptableAnswers: ["Inversion / reversed entropy", "Time inversion", "Entropy reversal moving backward through time"], explanation: "Tenet is Nolan's most complex film — many viewers needed multiple viewings to understand it." },
      { id: "nln_400_03", categoryId: "mv_christopher_nolan", tier: 400, prompt: "What recurring theme appears across almost all Nolan films, from Memento to Oppenheimer?", answer: "Obsession — protagonists consumed by a singular pursuit that blinds them to consequences. Cobb's guilt (Inception), Cooper's mission (Interstellar), Oppenheimer's science — all are driven beyond reason by their obsessions", acceptableAnswers: ["Obsession driving protagonists", "Characters consumed by singular pursuits", "Obsessive protagonists blind to consequences"], explanation: "Nolan's heroes aren't heroic because they're good — they're compelling because they can't stop." },
      { id: "nln_600_01", categoryId: "mv_christopher_nolan", tier: 600, prompt: "What was the challenge of filming the Trinity nuclear test in 'Oppenheimer' without CGI, and how did Nolan achieve it?", answer: "Nolan refused to use CGI for the bomb — his team created a practical explosion effect using a combination of gasoline, propane, aluminum powder, and magnesium, filmed in IMAX at extremely high frame rates. The result is a visceral, physical depiction of nuclear detonation that feels more real than any digital effect", acceptableAnswers: ["Practical explosion without CGI", "Real explosion with gasoline and magnesium in IMAX", "No CGI bomb, practical effects at high frame rates"], explanation: "The practical Trinity test shot is one of the most impressive visual effects achievements in modern cinema." },
      { id: "nln_600_02", categoryId: "mv_christopher_nolan", tier: 600, prompt: "How does 'The Prestige' use its own structure as the magic trick it describes, and what are the three parts?", answer: "The film follows the three acts of a magic trick: the Pledge (showing something ordinary), the Turn (making it extraordinary), and the Prestige (the twist). The film itself IS a magic trick — it shows you clues throughout (the Pledge), presents mystery (the Turn), and delivers a twist ending that recontextualizes everything (the Prestige). Nolan literally tells you how the trick works in the opening, and you still don't see it", acceptableAnswers: ["Film structure mirrors the three-part magic trick", "Pledge Turn Prestige structure applied to the film itself", "Movie is the trick it describes, hiding answer in plain sight"], explanation: "The Prestige is Nolan's most structurally brilliant film — it's about deception while deceiving you." },
      { id: "nln_600_03", categoryId: "mv_christopher_nolan", tier: 600, prompt: "What is the 'Nolan dialogue problem,' and how does his deliberate sound mixing philosophy divide audiences?", answer: "Nolan intentionally mixes dialogue low relative to music and sound effects — viewers complain they can't hear what characters are saying. Nolan argues this is deliberate: not every word needs to be understood, the emotional experience matters more than verbal information. He said 'I don't agree with the idea that you should always be able to hear dialogue clearly'", acceptableAnswers: ["Deliberately quiet dialogue mixing is intentional", "Low dialogue vs loud music is a conscious choice", "Can't hear dialogue because Nolan prioritizes emotion over clarity"], explanation: "The sound mixing debate reveals Nolan's philosophy: cinema is felt first, understood second." },
    ],
  },
  {
    id: "his_ottoman_empire",
    group: "history",
    name: "The Ottoman Empire",
    culture: "universal",
    description: "600 years — from Osman's dream to Atatürk's republic.",
    imageUrl: "",
    questions: [
      { id: "ott_200_01", categoryId: "his_ottoman_empire", tier: 200, prompt: "What was the capital of the Ottoman Empire after the conquest of Constantinople in 1453?", answer: "Constantinople (later renamed Istanbul)", acceptableAnswers: ["Constantinople", "Istanbul", "Constantinople/Istanbul"], explanation: "The Ottomans renamed Constantinople to Istanbul, making it one of the world's great cities." },
      { id: "ott_200_02", categoryId: "his_ottoman_empire", tier: 200, prompt: "What title did the Ottoman ruler hold, equivalent to emperor?", answer: "Sultan", explanation: "The Sultan held both political and religious authority as leader of the Islamic world." },
      { id: "ott_200_03", categoryId: "his_ottoman_empire", tier: 200, prompt: "Approximately how long did the Ottoman Empire last?", answer: "About 600 years (1299-1922)", acceptableAnswers: ["600 years", "Over 600 years", "1299 to 1922"], explanation: "One of the longest-lasting empires in history, spanning three continents." },
      { id: "ott_400_01", categoryId: "his_ottoman_empire", tier: 400, prompt: "What was the 'millet system,' and how did it allow the Ottoman Empire to govern diverse religious communities?", answer: "A system where non-Muslim communities (Christians, Jews) governed their own internal affairs — including education, religious practice, and family law — under their own religious leaders, while paying a special tax (jizya)", acceptableAnswers: ["Religious communities governing themselves under own leaders", "Self-governance for non-Muslim communities with tax", "Minority religious autonomy system"], explanation: "The millet system allowed remarkable religious diversity within an Islamic empire." },
      { id: "ott_400_02", categoryId: "his_ottoman_empire", tier: 400, prompt: "What was the Janissary corps, and what controversial recruitment method created it?", answer: "The Sultan's elite infantry — originally recruited through the devshirme system, where Christian boys from the Balkans were taken, converted to Islam, and trained as soldiers or administrators. They became the empire's most powerful military force", acceptableAnswers: ["Christian boys taken and converted into elite soldiers", "Devshirme system creating elite troops", "Converted Christian boys as Sultan's army"], explanation: "The Janissaries evolved from slaves into the empire's most influential political-military force." },
      { id: "ott_400_03", categoryId: "his_ottoman_empire", tier: 400, prompt: "Who was Suleiman the Magnificent, and why is his reign considered the Ottoman golden age?", answer: "Sultan who reigned 1520-1566, expanding the empire to its greatest extent, reforming law, and patronizing art and architecture — under him, the empire reached from Hungary to Yemen and North Africa", acceptableAnswers: ["Greatest sultan, expanded empire and reformed law", "Golden age ruler 1520-1566", "Sultan who brought empire to its peak"], explanation: "In the Islamic world, he's known as Suleiman the Lawgiver for his legal reforms." },
      { id: "ott_600_01", categoryId: "his_ottoman_empire", tier: 600, prompt: "What was the 'Kafes' (the Cage), and how did it affect Ottoman succession?", answer: "After fratricide among princes became too destabilizing, later sultans locked potential heirs in isolated palace apartments (the Kafes) for years or decades. Many went insane from confinement. When a sultan died, the heir emerged from the Cage often mentally broken, contributing to the empire's decline", acceptableAnswers: ["Imprisoned princes in palace isolation causing insanity", "Heirs locked away going mad from confinement", "Royal cage system producing mentally broken sultans"], explanation: "The Kafes solved the problem of succession warfare but created a new one: insane rulers." },
      { id: "ott_600_02", categoryId: "his_ottoman_empire", tier: 600, prompt: "What was the 'Tanzimat' reform period (1839-1876), and why did it ultimately fail to save the empire?", answer: "A series of modernizing reforms guaranteeing equality regardless of religion, modernizing education, and creating constitutional government. It failed because conservative religious elements resisted secularization, European powers used minority rights as pretexts for intervention, and reforms came too late to counter nationalist movements in the Balkans and Middle East", acceptableAnswers: ["Modernization reforms undermined by resistance and nationalism", "Failed modernization due to conservative and nationalist opposition", "Too-late reforms couldn't stop nationalist breakaway"], explanation: "The Tanzimat represents the empire's last serious attempt to reinvent itself before collapse." },
      { id: "ott_600_03", categoryId: "his_ottoman_empire", tier: 600, prompt: "How did the Ottoman Empire's entry into World War I lead to its dissolution, and what modern nations emerged from its collapse?", answer: "The Ottomans allied with Germany and lost — the Treaty of Sèvres (1920) carved the empire into mandates and spheres of influence. Modern Turkey (under Atatürk), Iraq, Syria, Lebanon, Jordan, Palestine/Israel, Saudi Arabia, and others all emerged from Ottoman territory. The arbitrary borders drawn by Britain and France continue to cause conflict today", acceptableAnswers: ["Allied with Germany, lost, carved into modern nations", "WWI loss led to Middle East borders still causing conflict", "Empire carved into modern states with problematic borders"], explanation: "The Sykes-Picot Agreement and Sèvres partition created the modern Middle East's political geography." },
    ],
  },
  {
    id: "sci_neuroscience",
    group: "science",
    name: "Neuroscience & the Brain",
    culture: "universal",
    description: "The three-pound universe — consciousness, memory, and the mind's mysteries.",
    imageUrl: "",
    questions: [
      { id: "neu_200_01", categoryId: "sci_neuroscience", tier: 200, prompt: "Approximately how many neurons does the human brain contain?", answer: "About 86 billion", acceptableAnswers: ["86 billion", "About 86 billion", "Roughly 100 billion"], explanation: "Each neuron can form thousands of connections, creating trillions of synapses." },
      { id: "neu_200_02", categoryId: "sci_neuroscience", tier: 200, prompt: "What is the 'fight or flight' response, and which part of the nervous system controls it?", answer: "An automatic stress response preparing the body for danger (increased heart rate, adrenaline release) — controlled by the sympathetic nervous system", acceptableAnswers: ["Automatic stress response from sympathetic nervous system", "Sympathetic nervous system danger response", "Stress response with adrenaline and elevated heart rate"], explanation: "The fight-or-flight response evolved to help us survive predators but now activates for work emails." },
      { id: "neu_200_03", categoryId: "sci_neuroscience", tier: 200, prompt: "What chemical messengers carry signals between neurons in the brain?", answer: "Neurotransmitters (such as serotonin, dopamine, and norepinephrine)", acceptableAnswers: ["Neurotransmitters", "Chemical messengers like serotonin and dopamine"], explanation: "Imbalances in neurotransmitters are linked to conditions like depression, anxiety, and ADHD." },
      { id: "neu_400_01", categoryId: "sci_neuroscience", tier: 400, prompt: "What is neuroplasticity, and why does it challenge the old belief that adult brains can't change?", answer: "The brain's ability to reorganize itself by forming new neural connections throughout life — damaged areas can sometimes be compensated for, and learning physically changes brain structure", acceptableAnswers: ["Brain can reorganize and form new connections", "Brain changes structure through learning", "Neural rewiring throughout life"], explanation: "Neuroplasticity means your brain is literally different after learning something new." },
      { id: "neu_400_02", categoryId: "sci_neuroscience", tier: 400, prompt: "What is the difference between the left and right brain hemispheres, and is the 'left brain/right brain' personality theory accurate?", answer: "The hemispheres do have some specialization (language tends to be left, spatial processing right), but the popular theory that people are 'left-brained' (logical) or 'right-brained' (creative) is a myth. Both hemispheres work together for virtually all tasks", acceptableAnswers: ["Some specialization but personality theory is a myth", "Left/right brain personality is false", "Both work together, personality theory is wrong"], explanation: "Brain imaging studies show both hemispheres are active in both logical and creative tasks." },
      { id: "neu_400_03", categoryId: "sci_neuroscience", tier: 400, prompt: "What is the 'default mode network' — the brain system that activates when you're not focused on the outside world?", answer: "A network of brain regions that becomes active during daydreaming, self-reflection, and mind-wandering — it's involved in imagination, planning, and thinking about yourself and others. It's basically your brain's 'screensaver'", acceptableAnswers: ["Brain network active during daydreaming", "Mind-wandering and self-reflection network", "Brain activity during unfocused thought"], explanation: "The DMN shows that your brain is never truly 'resting' — it's always processing something." },
      { id: "neu_600_01", categoryId: "sci_neuroscience", tier: 600, prompt: "What is the 'hard problem of consciousness' as defined by David Chalmers, and why can't neuroscience solve it?", answer: "Why do physical brain processes give rise to subjective experience (qualia)? We can explain WHAT the brain does but not WHY it feels like something to be conscious. The 'easy problems' (how the brain processes information) are solvable; the hard problem (why there is subjective experience at all) may not be", acceptableAnswers: ["Why brain processes create subjective experience", "Why consciousness feels like something", "Explaining subjective experience from physical processes"], explanation: "We can map every neuron and still not explain why seeing red FEELS like something." },
      { id: "neu_600_02", categoryId: "sci_neuroscience", tier: 600, prompt: "What did the split-brain experiments by Roger Sperry reveal about consciousness, and what happened when the two hemispheres couldn't communicate?", answer: "When the corpus callosum connecting hemispheres was severed (treating epilepsy), each hemisphere developed independent awareness. The left brain would confabulate (make up) explanations for actions initiated by the right brain — suggesting that our sense of unified consciousness is partially an illusion constructed by the left hemisphere's 'interpreter'", acceptableAnswers: ["Split hemispheres developed separate consciousness", "Left brain fabricated explanations for right brain actions", "Two independent consciousnesses in one brain"], explanation: "Split-brain research suggests our feeling of being one unified 'self' may be more constructed than real." },
      { id: "neu_600_03", categoryId: "sci_neuroscience", tier: 600, prompt: "What is the 'free will' debate in neuroscience, triggered by Benjamin Libet's experiments?", answer: "Libet showed that brain activity preparing for an action (the 'readiness potential') occurs about 350ms BEFORE the person consciously 'decides' to act — suggesting the brain initiates actions before we're aware of deciding. This raises the question: if the brain decides before 'you' do, does free will exist? The debate remains unresolved, with some arguing the conscious mind can still veto actions", acceptableAnswers: ["Brain decides before conscious awareness", "Readiness potential before conscious decision", "Brain acts before you decide, challenging free will"], explanation: "Libet's experiments opened one of neuroscience's most profound and unsettling questions." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 77 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
