#!/usr/bin/env python3
"""Insert wave 64 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_the_wire_deep",
    group: "TV Shows",
    name: "The Wire Deep Cuts",
    culture: "american",
    description: "Deep knowledge of David Simon's sprawling Baltimore epic — the institutions, the corners, the docks, the schools, and the newspaper.",
    imageUrl: "",
    questions: [
      {
        id: "wrd_200_01",
        categoryId: "tv_the_wire_deep",
        tier: 200,
        prompt: "The Wire is set in which American city, exploring its institutions through the lens of the drug trade?",
        answer: "Baltimore",
        acceptableAnswers: ["Baltimore, Maryland"],
      },
      {
        id: "wrd_200_02",
        categoryId: "tv_the_wire_deep",
        tier: 200,
        prompt: "Which character, played by Dominic West, is the hard-drinking, rule-breaking detective at the center of The Wire?",
        answer: "Jimmy McNulty",
        acceptableAnswers: ["McNulty"],
      },
      {
        id: "wrd_200_03",
        categoryId: "tv_the_wire_deep",
        tier: 200,
        prompt: "Which beloved character, known for his shotgun and his whistle, robs drug dealers while living by a strict personal code?",
        answer: "Omar Little",
        acceptableAnswers: ["Omar"],
      },
      {
        id: "wrd_400_01",
        categoryId: "tv_the_wire_deep",
        tier: 400,
        prompt: "Each season of The Wire focuses on a different institution in Baltimore. What are the five institutions covered across the five seasons?",
        answer: "Season 1: the drug trade/police, Season 2: the port/unions, Season 3: city politics, Season 4: the school system, Season 5: the media/newspaper",
        acceptableAnswers: ["drugs, docks, politics, schools, media"],
      },
      {
        id: "wrd_400_02",
        categoryId: "tv_the_wire_deep",
        tier: 400,
        prompt: "David Simon, The Wire's creator, was not a TV writer by trade. What was his previous career, and what book did he write that became the show's foundation?",
        answer: "He was a journalist at the Baltimore Sun. His book 'Homicide: A Year on the Killing Streets' (and later 'The Corner') formed the basis for the show.",
        acceptableAnswers: ["journalist, Homicide: A Year on the Killing Streets", "newspaper reporter, The Corner and Homicide"],
      },
      {
        id: "wrd_400_03",
        categoryId: "tv_the_wire_deep",
        tier: 400,
        prompt: "Avon Barksdale and Stringer Bell represent two different approaches to the drug trade. What is the fundamental tension between them?",
        answer: "Avon is a street warrior who values territory and reputation above all, while Stringer wants to run the drug trade like a legitimate business — studying economics and pursuing real estate",
        acceptableAnswers: ["Avon is street, Stringer is business", "Avon values corners, Stringer wants to go corporate"],
      },
      {
        id: "wrd_600_01",
        categoryId: "tv_the_wire_deep",
        tier: 600,
        prompt: "Many actors in The Wire were real Baltimore residents with criminal or street backgrounds. Which character was played by a former drug dealer who was also a real-life associate of the people who inspired the show?",
        answer: "Felicia 'Snoop' Pearson played herself-named character Snoop — she was discovered by Michael K. Williams at a Baltimore nightclub and had served time for second-degree murder as a teenager",
        acceptableAnswers: ["Snoop (Felicia Pearson)", "Felicia Pearson"],
        explanation: "Pearson's authenticity made Snoop one of the most chilling characters on television. She brought real street knowledge to the role.",
      },
      {
        id: "wrd_600_02",
        categoryId: "tv_the_wire_deep",
        tier: 600,
        prompt: "The Wire was a ratings failure during its original HBO run and was nearly cancelled multiple times. What saved it from cancellation?",
        answer: "HBO executives, particularly Chris Albrecht, kept it alive because of critical acclaim and because it was the most rented DVD series at the time — home video saved it",
        acceptableAnswers: ["DVD rentals and critical support", "it was popular on DVD despite low ratings", "HBO kept it for prestige despite low viewership"],
        explanation: "The Wire never averaged more than 4 million viewers per episode. Its reputation grew primarily through DVD box sets and later streaming, becoming an all-time great retroactively.",
      },
      {
        id: "wrd_600_03",
        categoryId: "tv_the_wire_deep",
        tier: 600,
        prompt: "In one of the show's most celebrated scenes, McNulty and Bunk investigate an old crime scene using almost nothing but variations of one word. What is the word, and why is the scene praised?",
        answer: "They say only variations of 'f**k' for an entire scene while reconstructing a murder using only crime scene evidence — demonstrating brilliant detective work through pure physical storytelling with no exposition",
        acceptableAnswers: ["they only say fuck for an entire scene", "the f-word scene"],
        explanation: "The scene lasts about four minutes with the two detectives communicating complex forensic deductions using nothing but profanity and physical investigation.",
      },
    ],
  },
  {
    id: "mv_studio_ghibli_deep",
    group: "Movies",
    name: "Studio Ghibli Deep Cuts",
    culture: "universal",
    description: "Deep knowledge of Hayao Miyazaki's legendary animation studio — from production secrets and lesser-known films to the philosophy behind Ghibli's enduring magic.",
    imageUrl: "",
    questions: [
      {
        id: "ghd_200_01",
        categoryId: "mv_studio_ghibli_deep",
        tier: 200,
        prompt: "Which Studio Ghibli film won the Academy Award for Best Animated Feature in 2003, featuring a girl trapped in a spirit world?",
        answer: "Spirited Away",
        acceptableAnswers: ["Sen to Chihiro no Kamikakushi"],
      },
      {
        id: "ghd_200_02",
        categoryId: "mv_studio_ghibli_deep",
        tier: 200,
        prompt: "Who is the co-founder and primary director of Studio Ghibli, considered one of the greatest animators in history?",
        answer: "Hayao Miyazaki",
        acceptableAnswers: ["Miyazaki"],
      },
      {
        id: "ghd_200_03",
        categoryId: "mv_studio_ghibli_deep",
        tier: 200,
        prompt: "What soot-like creatures appear in multiple Ghibli films (Spirited Away and My Neighbor Totoro) as small, round, fuzzy black beings?",
        answer: "Soot Sprites (Susuwatari)",
        acceptableAnswers: ["soot sprites", "susuwatari", "makkuro kurosuke"],
      },
      {
        id: "ghd_400_01",
        categoryId: "mv_studio_ghibli_deep",
        tier: 400,
        prompt: "Miyazaki has a famous philosophy about animation that sets Ghibli apart from most studios. What does he insist on regarding the animation process?",
        answer: "He insists on hand-drawn animation, personally drawing or correcting key frames himself, and rejects over-reliance on CGI",
        acceptableAnswers: ["hand-drawn animation", "he draws key frames himself", "no CGI, hand-drawn only"],
        explanation: "Miyazaki has been known to personally redraw scenes he's unsatisfied with. Studio Ghibli uses minimal CGI, primarily for subtle environmental effects.",
      },
      {
        id: "ghd_400_02",
        categoryId: "mv_studio_ghibli_deep",
        tier: 400,
        prompt: "Isao Takahata, Ghibli's other co-founder, directed which devastating 1988 war film that is considered one of the saddest animated films ever made?",
        answer: "Grave of the Fireflies",
        acceptableAnswers: ["Hotaru no Haka"],
        explanation: "The film follows two children during the firebombing of Kobe in WWII. It was released as a double feature with My Neighbor Totoro — perhaps the most emotionally extreme double bill in cinema history.",
      },
      {
        id: "ghd_400_03",
        categoryId: "mv_studio_ghibli_deep",
        tier: 400,
        prompt: "In Princess Mononoke, what does Lady Eboshi represent thematically, and why is she not a simple villain?",
        answer: "She represents industrialization and progress — she employs lepers and former brothel workers, giving them dignity and purpose, while simultaneously destroying the forest. She's sympathetic because she genuinely cares for her people.",
        acceptableAnswers: ["she's a complex character who helps marginalized people but destroys nature", "industrialization that isn't purely evil"],
      },
      {
        id: "ghd_600_01",
        categoryId: "mv_studio_ghibli_deep",
        tier: 600,
        prompt: "Miyazaki has 'retired' multiple times. How many times has he announced his retirement, and what brought him back most recently?",
        answer: "He has announced retirement at least seven times throughout his career. Most recently he came back to direct 'The Boy and the Heron' (2023), partly driven by wanting to leave a final film for his grandson.",
        acceptableAnswers: ["many times, at least 5-7 times", "multiple retirements, came back for The Boy and the Heron"],
      },
      {
        id: "ghd_600_02",
        categoryId: "mv_studio_ghibli_deep",
        tier: 600,
        prompt: "Studio Ghibli's name comes from an unusual source. What does 'Ghibli' mean and where does the word originate?",
        answer: "It's the Italian name for the hot Saharan wind (also spelled 'Ghibili') — Miyazaki chose it because he wanted to 'blow a hot wind through the anime industry.' It's also the name of an Italian WWII reconnaissance aircraft, the Caproni Ca.309 Ghibli.",
        acceptableAnswers: ["a hot Saharan wind", "Italian word for a desert wind", "a hot wind from the Sahara"],
      },
      {
        id: "ghd_600_03",
        categoryId: "mv_studio_ghibli_deep",
        tier: 600,
        prompt: "Spirited Away's bathhouse was inspired by a real architectural tradition. What was it, and what deeper metaphor does the bathhouse serve in the film?",
        answer: "The bathhouse is inspired by traditional Japanese onsen (hot spring) architecture, particularly the Dōgo Onsen in Ehime. Metaphorically, it represents Japan's bubble economy excess and the sex industry — Yubaba's exploitation of workers mirrors both.",
        acceptableAnswers: ["Japanese onsen/bathhouse tradition, metaphor for economic excess", "inspired by Dogo Onsen, represents the bubble economy"],
        explanation: "Miyazaki has confirmed the bathhouse as a metaphor for the sex industry and economic exploitation, with Chihiro's journey representing maintaining identity under dehumanizing conditions.",
      },
    ],
  },
  {
    id: "mu_rage_against",
    group: "Music",
    name: "Rage Against the Machine",
    culture: "american",
    description: "The explosive fusion of hip-hop and heavy metal that became the soundtrack to political dissent, powered by Tom Morello's revolutionary guitar innovations.",
    imageUrl: "",
    questions: [
      {
        id: "rat_200_01",
        categoryId: "mu_rage_against",
        tier: 200,
        prompt: "What Rage Against the Machine song opens with the lyrics 'Some of those that work forces are the same that burn crosses'?",
        answer: "Killing in the Name",
        acceptableAnswers: ["Killing in the Name Of"],
      },
      {
        id: "rat_200_02",
        categoryId: "mu_rage_against",
        tier: 200,
        prompt: "Who is RATM's guitarist, known for creating bizarre sounds using turntable-like techniques on a standard electric guitar?",
        answer: "Tom Morello",
        acceptableAnswers: [],
      },
      {
        id: "rat_200_03",
        categoryId: "mu_rage_against",
        tier: 200,
        prompt: "What political ideology does Rage Against the Machine openly advocate?",
        answer: "Far-left/revolutionary socialist politics, including anti-capitalism, anti-imperialism, and support for workers' movements",
        acceptableAnswers: ["socialist", "anti-capitalist", "left-wing revolutionary politics", "communist"],
      },
      {
        id: "rat_400_01",
        categoryId: "mu_rage_against",
        tier: 400,
        prompt: "Tom Morello created his signature guitar sounds without effects pedals in the traditional sense. What techniques does he use to make his guitar sound like a DJ scratching records?",
        answer: "He uses the toggle switch to rapidly cut signal on and off while manipulating the whammy bar, creating a scratching effect — combined with a DigiTech Whammy pedal for pitch shifting",
        acceptableAnswers: ["toggle switch and whammy pedal", "kill switch technique with the toggle", "rapid toggle switching"],
      },
      {
        id: "rat_400_02",
        categoryId: "mu_rage_against",
        tier: 400,
        prompt: "The cover of RATM's self-titled debut album features a famous historical photograph. What does it depict?",
        answer: "Thich Quang Duc, a Vietnamese Buddhist monk, self-immolating on a Saigon street in 1963 to protest the persecution of Buddhists by the South Vietnamese government",
        acceptableAnswers: ["a monk burning himself", "the burning monk", "Thich Quang Duc's self-immolation"],
      },
      {
        id: "rat_400_03",
        categoryId: "mu_rage_against",
        tier: 400,
        prompt: "Zack de la Rocha left RATM in 2000. What supergroup did the remaining three members form with a new vocalist?",
        answer: "Audioslave, with Chris Cornell (Soundgarden) on vocals",
        acceptableAnswers: ["Audioslave", "Audioslave with Chris Cornell"],
      },
      {
        id: "rat_600_01",
        categoryId: "mu_rage_against",
        tier: 600,
        prompt: "Tom Morello holds a degree from an Ivy League university. What university, and what did he study?",
        answer: "Harvard University — he graduated with a BA in Political Science",
        acceptableAnswers: ["Harvard, political science", "Harvard"],
        explanation: "Morello has spoken about the disconnect between his Harvard education and his experience as a biracial person in America. He worked as a Senate aide before pursuing music.",
      },
      {
        id: "rat_600_02",
        categoryId: "mu_rage_against",
        tier: 600,
        prompt: "In 2009, a UK Facebook campaign pushed 'Killing in the Name' to the Christmas number one spot, dethroning the expected winner. What were they protesting?",
        answer: "The dominance of X Factor/Simon Cowell winners on the UK Christmas charts — the campaign successfully made 'Killing in the Name' the Christmas #1, beating X Factor winner Joe McElderry",
        acceptableAnswers: ["X Factor dominance of Christmas charts", "Simon Cowell and X Factor"],
        explanation: "The campaign by Jon and Tracy Morter became a cultural moment. RATM performed a free concert in London to celebrate, and the victory became a symbol of people vs. corporate pop.",
      },
      {
        id: "rat_600_03",
        categoryId: "mu_rage_against",
        tier: 600,
        prompt: "RATM performed a legendary protest concert in 2000 outside the Democratic National Convention in Los Angeles. What happened during and after the performance?",
        answer: "Police in riot gear fired rubber bullets and tear gas at the crowd. The band was playing 'Guerrilla Radio' when police shut down the concert, and a near-riot ensued in the streets",
        acceptableAnswers: ["police fired rubber bullets and tear gas", "riot police shut them down with rubber bullets"],
        explanation: "The DNC 2000 concert became one of the most politically charged live performances in rock history. Footage of the police response was widely broadcast.",
      },
    ],
  },
  {
    id: "vg_slay_the_spire",
    group: "Video Games",
    name: "Slay the Spire",
    culture: "universal",
    description: "The roguelike deckbuilder that spawned an entire genre, combining strategic card game mechanics with procedural dungeon crawling.",
    imageUrl: "",
    questions: [
      {
        id: "sts_200_01",
        categoryId: "vg_slay_the_spire",
        tier: 200,
        prompt: "What two game genres does Slay the Spire combine to create its signature gameplay?",
        answer: "Roguelike (permadeath dungeon crawling) and deckbuilding card game",
        acceptableAnswers: ["roguelike and deckbuilder", "card game and roguelike"],
      },
      {
        id: "sts_200_02",
        categoryId: "vg_slay_the_spire",
        tier: 200,
        prompt: "How many acts (floors) must you climb through to complete a standard run in Slay the Spire?",
        answer: "Three acts (plus a hidden fourth act for advanced players)",
        acceptableAnswers: ["3", "three", "3 or 4"],
      },
      {
        id: "sts_200_03",
        categoryId: "vg_slay_the_spire",
        tier: 200,
        prompt: "What is the name of the first playable character, a knight who uses strength-based attacks and defensive cards?",
        answer: "The Ironclad",
        acceptableAnswers: ["Ironclad"],
      },
      {
        id: "sts_400_01",
        categoryId: "vg_slay_the_spire",
        tier: 400,
        prompt: "Experienced Slay the Spire players know that one of the most important strategic decisions is removing cards from your deck rather than adding them. Why is a smaller deck often better?",
        answer: "A smaller deck means you draw your best cards more frequently and more reliably, creating consistent combos rather than diluting your deck with mediocre options",
        acceptableAnswers: ["draw good cards more often", "consistency and reliability", "less dilution of strong cards"],
      },
      {
        id: "sts_400_02",
        categoryId: "vg_slay_the_spire",
        tier: 400,
        prompt: "What are relics in Slay the Spire, and why are they considered as important as the cards themselves?",
        answer: "Relics are passive items that provide permanent bonuses throughout the run. They fundamentally shape strategy because some relics make entire deck archetypes viable that wouldn't otherwise work.",
        acceptableAnswers: ["passive permanent bonuses", "items that give permanent effects and define your strategy"],
      },
      {
        id: "sts_400_03",
        categoryId: "vg_slay_the_spire",
        tier: 400,
        prompt: "The Watcher (the fourth character) is considered the most powerful but also the most dangerous to play. What unique mechanic makes her both powerful and risky?",
        answer: "Stance switching — she can enter Wrath (double damage dealt AND received) or Calm (gain energy when leaving). Mismanaging stances means taking lethal damage.",
        acceptableAnswers: ["stance system with Wrath and Calm", "Wrath doubles damage taken and dealt"],
      },
      {
        id: "sts_600_01",
        categoryId: "vg_slay_the_spire",
        tier: 600,
        prompt: "Slay the Spire essentially created the roguelike deckbuilder genre. Before its success, what game was the closest precursor, and how did Slay the Spire improve on the concept?",
        answer: "Dream Quest (2014) by Peter Whalen combined roguelike elements with deckbuilding first, but with primitive art. Slay the Spire refined the core loop, added relics, and polished the presentation. Whalen later joined Blizzard to work on Hearthstone.",
        acceptableAnswers: ["Dream Quest", "Dream Quest by Peter Whalen"],
        explanation: "Dream Quest proved the concept was fun despite looking like crayon drawings. Slay the Spire's success spawned hundreds of imitators including Monster Train, Inscryption, and Balatro.",
      },
      {
        id: "sts_600_02",
        categoryId: "vg_slay_the_spire",
        tier: 600,
        prompt: "Ascension levels are Slay the Spire's difficulty scaling system. What is the maximum Ascension level, and what does the hardest Ascension modifier add?",
        answer: "Ascension 20 is the max. Each level adds cumulative handicaps: enemies have more HP, hit harder, elite fights are tougher, and at A20 specifically, the boss on Act 3 is a double boss fight.",
        acceptableAnswers: ["Ascension 20", "A20, double boss fight"],
      },
      {
        id: "sts_600_03",
        categoryId: "vg_slay_the_spire",
        tier: 600,
        prompt: "Slay the Spire's developers (Mega Crit) made a controversial decision about modding. What did they do, and how did the community respond?",
        answer: "They officially supported and encouraged modding through Steam Workshop integration, leading to thousands of mods including new characters, cards, and total conversions — the Downfall mod is essentially a full expansion",
        acceptableAnswers: ["they embraced modding", "official mod support through Steam Workshop"],
        explanation: "The modding community has kept the game alive for years beyond its release. The Downfall mod, where you play as the bosses, is considered almost a full game in itself.",
      },
    ],
  },
  {
    id: "his_viking_deep",
    group: "History",
    name: "Viking Age Deep Cuts",
    culture: "universal",
    description: "Beyond the horned helmets (they didn't wear them) — the real history of Norse exploration, settlement, trade, and warfare from 793 to 1066.",
    imageUrl: "",
    questions: [
      {
        id: "vkd_200_01",
        categoryId: "his_viking_deep",
        tier: 200,
        prompt: "The Viking Age is traditionally dated as beginning with the raid on which English monastery in 793 AD?",
        answer: "Lindisfarne",
        acceptableAnswers: ["Lindisfarne monastery"],
      },
      {
        id: "vkd_200_02",
        categoryId: "his_viking_deep",
        tier: 200,
        prompt: "Which Viking explorer is credited with reaching North America roughly 500 years before Christopher Columbus?",
        answer: "Leif Erikson",
        acceptableAnswers: ["Leif Eriksson", "Leif Ericson"],
      },
      {
        id: "vkd_200_03",
        categoryId: "his_viking_deep",
        tier: 200,
        prompt: "Despite popular culture depicting Vikings with horned helmets, this is historically inaccurate. What did Viking helmets actually look like?",
        answer: "Simple rounded iron or leather helmets, sometimes with a nose guard (nasal) — no horns or wings",
        acceptableAnswers: ["plain helmets with no horns", "simple metal or leather helmets"],
      },
      {
        id: "vkd_400_01",
        categoryId: "his_viking_deep",
        tier: 400,
        prompt: "The Norse established a settlement in North America. What is the archaeological site in Newfoundland, Canada, that confirmed their presence?",
        answer: "L'Anse aux Meadows",
        acceptableAnswers: [],
        explanation: "Discovered by Helge and Anne Stine Ingstad in 1960, L'Anse aux Meadows contains the remains of eight Norse-style buildings and is a UNESCO World Heritage Site.",
      },
      {
        id: "vkd_400_02",
        categoryId: "his_viking_deep",
        tier: 400,
        prompt: "The Varangian Guard was an elite unit in the Byzantine Empire composed primarily of Norse warriors. What was their role, and why did Byzantine emperors prefer foreign bodyguards?",
        answer: "They served as the personal bodyguard of the Byzantine Emperor. Foreign guards were preferred because they had no local political allegiances or ties to rival factions",
        acceptableAnswers: ["imperial bodyguards, no local political ties", "Byzantine emperor's guard, trusted because they were foreigners"],
      },
      {
        id: "vkd_400_03",
        categoryId: "his_viking_deep",
        tier: 400,
        prompt: "The Danegeld was a significant aspect of Viking-era politics. What was it?",
        answer: "A tax or tribute paid by English and Frankish kingdoms to Viking raiders to prevent attacks — essentially protection money",
        acceptableAnswers: ["payment to Vikings to stop raids", "protection money paid to Norsemen", "tax paid to prevent Viking attacks"],
        explanation: "The Danegeld became a regular English tax. The policy was controversial even then — paying it often just attracted more raiders looking for easy wealth.",
      },
      {
        id: "vkd_600_01",
        categoryId: "his_viking_deep",
        tier: 600,
        prompt: "The Rus' people, who gave Russia its name, have a disputed origin. What is the scholarly debate about who they were?",
        answer: "The Normanist theory argues the Rus' were Scandinavian Vikings (Varangians) who established trade routes and political power in Eastern Europe. The anti-Normanist view argues they were primarily Slavic. Most modern scholars accept significant Norse involvement.",
        acceptableAnswers: ["debate over whether they were Norse or Slavic", "Normanist vs anti-Normanist debate", "whether Vikings or Slavs founded Russian states"],
      },
      {
        id: "vkd_600_02",
        categoryId: "his_viking_deep",
        tier: 600,
        prompt: "Harald Hardrada's failed invasion of England in 1066 is often cited as the end of the Viking Age. He died at which battle, just days before another famous 1066 battle?",
        answer: "The Battle of Stamford Bridge (September 25, 1066) — Harold Godwinson then had to march south to fight William the Conqueror at the Battle of Hastings (October 14, 1066)",
        acceptableAnswers: ["Stamford Bridge", "Battle of Stamford Bridge"],
        explanation: "Harold Godwinson's exhausted army marching 250 miles from Stamford Bridge to Hastings in under three weeks is considered a key factor in his defeat by William.",
      },
      {
        id: "vkd_600_03",
        categoryId: "his_viking_deep",
        tier: 600,
        prompt: "Norse women had significantly more rights than women in most other medieval European societies. What specific legal rights did Norse women possess?",
        answer: "They could own property, request divorce, reclaim their dowry, inherit land, and operate businesses. A divorced woman kept her property and could remarry freely.",
        acceptableAnswers: ["could own property and divorce", "property rights, divorce rights, inheritance rights"],
        explanation: "These rights were remarkable for the era. The Icelandic sagas feature many powerful women making independent decisions, reflecting real social norms.",
      },
    ],
  },
  {
    id: "sci_space_oddities",
    group: "Science",
    name: "Space Oddities",
    culture: "universal",
    description: "The strangest, most mind-bending facts about space — from rogue planets and magnetars to the bizarre experiences of astronauts and the weirdest discoveries in our universe.",
    imageUrl: "",
    questions: [
      {
        id: "spo_200_01",
        categoryId: "sci_space_oddities",
        tier: 200,
        prompt: "What happens to an astronaut's height in space, and why?",
        answer: "They grow up to 2 inches taller because without gravity, the spinal discs expand",
        acceptableAnswers: ["they get taller", "they grow taller in microgravity"],
      },
      {
        id: "spo_200_02",
        categoryId: "sci_space_oddities",
        tier: 200,
        prompt: "What is a neutron star — the remnant left behind when a massive star dies?",
        answer: "An incredibly dense stellar remnant where a teaspoon of material would weigh about a billion tons on Earth",
        acceptableAnswers: ["extremely dense star remnant", "collapsed star core", "super dense remnant of a dead star"],
      },
      {
        id: "spo_200_03",
        categoryId: "sci_space_oddities",
        tier: 200,
        prompt: "What is a 'rogue planet'?",
        answer: "A planet that does not orbit any star — it floats freely through interstellar space",
        acceptableAnswers: ["a planet without a star", "a free-floating planet"],
      },
      {
        id: "spo_400_01",
        categoryId: "sci_space_oddities",
        tier: 400,
        prompt: "There is a massive cloud of alcohol floating in space. How much alcohol does it contain?",
        answer: "The cloud Sagittarius B2 near the center of the Milky Way contains enough ethyl alcohol to fill 400 trillion trillion pints of beer",
        acceptableAnswers: ["trillions of trillions of pints", "an enormous amount near the galactic center", "Sagittarius B2"],
      },
      {
        id: "spo_400_02",
        categoryId: "sci_space_oddities",
        tier: 400,
        prompt: "Astronauts on the ISS witness approximately how many sunrises and sunsets per day?",
        answer: "16 — the ISS orbits Earth approximately every 90 minutes",
        acceptableAnswers: ["16", "about 16"],
      },
      {
        id: "spo_400_03",
        categoryId: "sci_space_oddities",
        tier: 400,
        prompt: "What is the 'Overview Effect' that many astronauts report experiencing?",
        answer: "A profound cognitive shift and sense of awe when seeing Earth from space — many astronauts describe a deep understanding of the fragility and unity of life on Earth",
        acceptableAnswers: ["a shift in perspective from seeing Earth from space", "awe at seeing Earth from orbit"],
      },
      {
        id: "spo_600_01",
        categoryId: "sci_space_oddities",
        tier: 600,
        prompt: "A magnetar is one of the most extreme objects in the universe. How strong is a magnetar's magnetic field, and what would happen if one passed within half the distance of the Moon?",
        answer: "A magnetar's field is about a quadrillion (10^15) times stronger than Earth's. At half the Moon's distance, it would erase every credit card on Earth and pull the iron from your blood",
        acceptableAnswers: ["quadrillion times Earth's field, would erase credit cards and affect metal on Earth", "incredibly powerful, would be devastating from lunar distance"],
      },
      {
        id: "spo_600_02",
        categoryId: "sci_space_oddities",
        tier: 600,
        prompt: "There is a planet made largely of diamond. What is it called, and how was it formed?",
        answer: "55 Cancri e (Janssen) — a super-Earth whose carbon-rich composition and extreme pressure create a planet that may be up to one-third diamond",
        acceptableAnswers: ["55 Cancri e", "Janssen"],
        explanation: "The planet orbits so close to its star that one side is permanently molten. It's about twice the size of Earth and eight times its mass.",
      },
      {
        id: "spo_600_03",
        categoryId: "sci_space_oddities",
        tier: 600,
        prompt: "The Boötes Void is one of the most unsettling discoveries in cosmology. What is it?",
        answer: "A roughly spherical region of space about 330 million light-years in diameter that contains almost no galaxies — it should contain about 2,000 galaxies but has only about 60",
        acceptableAnswers: ["a giant empty region of space", "a supervoid with almost no galaxies", "a 330 million light-year void with very few galaxies"],
        explanation: "Sometimes called 'the Great Nothing,' the Boötes Void challenges our understanding of large-scale cosmic structure. Its existence is difficult to explain with standard cosmological models.",
      },
    ],
  },
  {
    id: "cul_perfume_fragrance",
    group: "Culture",
    name: "Perfume & Fragrance",
    culture: "universal",
    description: "The art and science of fragrance — from ancient incense to modern niche perfumery, the chemistry of scent, and the stories behind iconic perfumes.",
    imageUrl: "",
    questions: [
      {
        id: "pfm_200_01",
        categoryId: "cul_perfume_fragrance",
        tier: 200,
        prompt: "What is the most famous perfume in the world, launched by Coco Chanel in 1921?",
        answer: "Chanel No. 5",
        acceptableAnswers: ["No. 5", "Chanel 5"],
      },
      {
        id: "pfm_200_02",
        categoryId: "cul_perfume_fragrance",
        tier: 200,
        prompt: "Perfumes are structured in 'notes' that unfold over time. What are the three layers called?",
        answer: "Top notes (initial scent), heart/middle notes (the core), and base notes (long-lasting foundation)",
        acceptableAnswers: ["top, middle, base", "top, heart, base"],
      },
      {
        id: "pfm_200_03",
        categoryId: "cul_perfume_fragrance",
        tier: 200,
        prompt: "What is the difference between Eau de Toilette and Eau de Parfum?",
        answer: "Eau de Parfum has a higher concentration of fragrance oils (15-20%) than Eau de Toilette (5-15%), making it longer-lasting and more intense",
        acceptableAnswers: ["parfum has more fragrance oil", "EDT is lighter, EDP is stronger"],
      },
      {
        id: "pfm_400_01",
        categoryId: "cul_perfume_fragrance",
        tier: 400,
        prompt: "Ambergris is one of the most valuable ingredients in perfumery. What is it, and where does it come from?",
        answer: "A waxy substance produced in the intestines of sperm whales, expelled into the ocean where it ages and develops a unique musky-sweet scent used as a fixative in perfumes",
        acceptableAnswers: ["whale intestine secretion", "comes from sperm whales", "a substance from sperm whale digestive systems"],
      },
      {
        id: "pfm_400_02",
        categoryId: "cul_perfume_fragrance",
        tier: 400,
        prompt: "Grasse, a town in southern France, is known as the world capital of perfumery. What made it the center of the perfume industry?",
        answer: "It began as a leather tanning town that used fragrant oils to mask the smell of leather goods. Its climate is ideal for growing jasmine, roses, and other fragrance plants.",
        acceptableAnswers: ["ideal climate for fragrance plants", "started as leather town that used scents", "perfect growing conditions for perfume ingredients"],
      },
      {
        id: "pfm_400_03",
        categoryId: "cul_perfume_fragrance",
        tier: 400,
        prompt: "What is an 'oud' (agarwood) in perfumery, and why is it one of the most expensive raw materials in the world?",
        answer: "Oud is the resinous heartwood produced when Aquilaria trees are infected by a specific mold. Only about 2% of trees develop it naturally, making genuine oud worth more than gold by weight.",
        acceptableAnswers: ["infected wood from Aquilaria trees", "resin from infected trees, very rare", "agarwood from a fungal infection in trees"],
      },
      {
        id: "pfm_600_01",
        categoryId: "cul_perfume_fragrance",
        tier: 600,
        prompt: "Chanel No. 5 was revolutionary when it launched because of a specific chemical innovation. What made it different from every perfume before it?",
        answer: "It was the first commercially successful perfume to use aldehydes (synthetic molecules) prominently — giving it an abstract, non-floral character that didn't try to smell like a single natural thing",
        acceptableAnswers: ["first to use aldehydes", "synthetic aldehydes giving it an abstract quality"],
        explanation: "Perfumer Ernest Beaux used aldehydes to create a scent that was modern and abstract rather than mimicking a flower. Some accounts suggest the high aldehyde dose was accidental.",
      },
      {
        id: "pfm_600_02",
        categoryId: "cul_perfume_fragrance",
        tier: 600,
        prompt: "The term 'sillage' is important in perfume evaluation. What does it mean, and how is it different from 'projection'?",
        answer: "Sillage (from the French word for 'wake') is the scent trail a perfume leaves behind the wearer as they move through a space. Projection is how far the scent radiates from the wearer while stationary.",
        acceptableAnswers: ["the scent trail left behind vs how far it radiates", "sillage is the trail, projection is the radius"],
      },
      {
        id: "pfm_600_03",
        categoryId: "cul_perfume_fragrance",
        tier: 600,
        prompt: "The ancient Egyptians are credited with developing perfumery. What was Kyphi, and what role did it play?",
        answer: "Kyphi was an ancient Egyptian incense made from 16 ingredients (including honey, wine, raisins, and resins) that was burned at sunset in temples. It served religious, medicinal, and social purposes.",
        acceptableAnswers: ["an Egyptian incense burned in temples", "a 16-ingredient sacred incense"],
        explanation: "Recipes for Kyphi were inscribed on temple walls at Edfu and Philae. Greek and Roman writers also documented it, and modern perfumers have attempted to recreate it.",
      },
    ],
  },
  {
    id: "his_espionage",
    group: "History",
    name: "History of Espionage",
    culture: "universal",
    description: "Real-world spies, intelligence operations, and covert actions that shaped history — from ancient deception to Cold War tradecraft and modern cyber espionage.",
    imageUrl: "",
    questions: [
      {
        id: "esp_200_01",
        categoryId: "his_espionage",
        tier: 200,
        prompt: "What was the name of the British intelligence service that broke the German Enigma code during World War II?",
        answer: "Bletchley Park (Government Code and Cypher School / GC&CS)",
        acceptableAnswers: ["Bletchley Park", "GC&CS"],
      },
      {
        id: "esp_200_02",
        categoryId: "his_espionage",
        tier: 200,
        prompt: "What is the CIA's full name?",
        answer: "Central Intelligence Agency",
        acceptableAnswers: [],
      },
      {
        id: "esp_200_03",
        categoryId: "his_espionage",
        tier: 200,
        prompt: "What was the KGB?",
        answer: "The Soviet Union's main intelligence and security agency, equivalent to a combined CIA and FBI",
        acceptableAnswers: ["Soviet intelligence agency", "the Soviet secret police and intelligence service"],
      },
      {
        id: "esp_400_01",
        categoryId: "his_espionage",
        tier: 400,
        prompt: "The Cambridge Five were a ring of British double agents who spied for the Soviet Union. Name any two of the five members.",
        answer: "Kim Philby, Guy Burgess, Donald Maclean, Anthony Blunt, and John Cairncross",
        acceptableAnswers: ["Philby and Burgess", "any two of the five"],
        explanation: "The Cambridge Five penetrated the highest levels of British intelligence. Kim Philby was the most damaging — he was head of the anti-Soviet section of MI6 while secretly working for Moscow.",
      },
      {
        id: "esp_400_02",
        categoryId: "his_espionage",
        tier: 400,
        prompt: "What is a 'dead drop' in espionage tradecraft?",
        answer: "A method of passing information between agents without meeting in person — items are left at a pre-arranged secret location for the other person to retrieve later",
        acceptableAnswers: ["a secret location for exchanging information", "leaving items at a hidden spot for another agent"],
      },
      {
        id: "esp_400_03",
        categoryId: "his_espionage",
        tier: 400,
        prompt: "During the Cold War, the CIA and MI6 dug a tunnel under East Berlin to tap Soviet communication lines. What was this operation called?",
        answer: "Operation Gold (also known as Operation Stopwatch by MI6)",
        acceptableAnswers: ["Operation Gold", "Operation Stopwatch"],
        explanation: "The tunnel was operational from 1955-1956. What the West didn't know was that the Soviets already knew about the tunnel from a mole — George Blake — but allowed it to continue to protect his identity.",
      },
      {
        id: "esp_600_01",
        categoryId: "his_espionage",
        tier: 600,
        prompt: "Aldrich Ames was one of the most damaging moles in CIA history. How much information did he compromise, and what was his motivation?",
        answer: "He revealed the identities of virtually every CIA agent operating in the Soviet Union — at least 10 were executed. His primary motivation was money (he received over $4.6 million from the KGB).",
        acceptableAnswers: ["he revealed all CIA agents in the USSR for money", "compromised CIA agents in Russia, motivated by money"],
        explanation: "Ames began spying in 1985 partly to cover debts from his expensive lifestyle. He was arrested in 1994 and sentenced to life without parole.",
      },
      {
        id: "esp_600_02",
        categoryId: "his_espionage",
        tier: 600,
        prompt: "Operation Mincemeat is considered one of the most creative deception operations in military history. What was the plan?",
        answer: "British intelligence dressed a corpse as a Royal Marines officer, planted fake invasion plans on him, and dropped the body off the coast of Spain — tricking the Germans into diverting forces away from the real Allied invasion target of Sicily",
        acceptableAnswers: ["fake documents on a corpse to mislead Germany", "planted a body with fake invasion plans"],
        explanation: "The operation, conceived by Ewen Montagu and Charles Cholmondeley, successfully convinced Hitler that the Allies would invade Sardinia and Greece instead of Sicily.",
      },
      {
        id: "esp_600_03",
        categoryId: "his_espionage",
        tier: 600,
        prompt: "Oleg Penkovsky was a Soviet military intelligence (GRU) officer who spied for the West during the Cuban Missile Crisis. Why was his intelligence considered the most valuable of the entire Cold War?",
        answer: "He provided technical details of Soviet missile capabilities that allowed Kennedy to call Khrushchev's bluff during the Cuban Missile Crisis — proving the Soviets' nuclear capability was weaker than they claimed",
        acceptableAnswers: ["he proved Soviet missiles were weaker than claimed", "gave missile intelligence during the Cuban crisis", "revealed Soviet nuclear weakness during Cuba crisis"],
        explanation: "Penkovsky's intelligence may have prevented nuclear war. He was caught in 1962 and executed in 1963. His handler Greville Wynne was imprisoned but later exchanged.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 64 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
