#!/usr/bin/env python3
"""Insert wave 74 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_office",
    group: "tv",
    name: "The Office (US)",
    culture: "american",
    description: "That's what she said — Dunder Mifflin's finest paper salespeople.",
    imageUrl: "",
    questions: [
      { id: "ofc_200_01", categoryId: "tv_office", tier: 200, prompt: "What type of company is Dunder Mifflin, where the show takes place?", answer: "A paper company", acceptableAnswers: ["Paper company", "Paper sales company"], explanation: "The mundane setting of a paper company makes the character comedy shine." },
      { id: "ofc_200_02", categoryId: "tv_office", tier: 200, prompt: "Who is the regional manager of the Scranton branch known for his cringe-worthy humor and catchphrase 'That's what she said'?", answer: "Michael Scott", acceptableAnswers: ["Michael", "Michael Scott"], explanation: "Steve Carell's Michael Scott became one of TV's most beloved comedy characters." },
      { id: "ofc_200_03", categoryId: "tv_office", tier: 200, prompt: "What filming style does The Office use, where characters talk directly to the camera?", answer: "Mockumentary / talking heads format", acceptableAnswers: ["Mockumentary", "Documentary style", "Talking heads"], explanation: "The documentary format allows characters to break the fourth wall with confessionals." },
      { id: "ofc_400_01", categoryId: "tv_office", tier: 400, prompt: "What is Dwight Schrute's farm called, and what crop does he primarily grow?", answer: "Schrute Farms — he grows beets", acceptableAnswers: ["Schrute Farms, beets", "Beet farm"], explanation: "Dwight's beet farm and his martial arts obsession define his eccentric character." },
      { id: "ofc_400_02", categoryId: "tv_office", tier: 400, prompt: "What is the name of the annual office awards ceremony Michael creates, which always goes terribly wrong?", answer: "The Dundies", acceptableAnswers: ["Dundies", "The Dundie Awards"], explanation: "The Dundies episodes showcase Michael's desperate need to be loved by his employees." },
      { id: "ofc_400_03", categoryId: "tv_office", tier: 400, prompt: "What elaborate prank does Jim pull on Dwight involving the CIA and a murder mystery in the 'Murder' episode?", answer: "Various pranks — but the most famous running prank is Jim putting Dwight's stapler in Jello, followed by increasingly elaborate schemes throughout the series", acceptableAnswers: ["Stapler in Jello", "Jim's escalating pranks on Dwight", "Various pranks like stapler in Jello"], explanation: "Jim's pranks on Dwight are a series highlight — from Jello staplers to impersonating Dwight." },
      { id: "ofc_600_01", categoryId: "tv_office", tier: 600, prompt: "What is the 'Scott's Tots' episode, and why do fans consider it the most unwatchable episode of television ever made?", answer: "Michael promised a class of third-graders he'd pay their college tuition, then ten years later has to tell the now-high-schoolers he can't afford it — the cringe is so severe many fans physically cannot watch it", acceptableAnswers: ["Michael can't pay promised college tuition", "Promised kids tuition, couldn't pay", "Most cringe episode about broken tuition promise"], explanation: "r/CantWatchScottsTots is a real subreddit for people who skip the episode on rewatches." },
      { id: "ofc_600_02", categoryId: "tv_office", tier: 600, prompt: "In the series finale, what emotional moment occurs when Dwight asks Michael (who returns for the wedding) to be his 'Bestest Mensch'?", answer: "Michael returns for Dwight's wedding and serves as his best man — when Dwight calls him his best friend, Michael simply says 'That's what she said' one final time, getting the biggest laugh and emotional reaction of the series", acceptableAnswers: ["Michael returns for wedding, final that's what she said", "Best man at Dwight's wedding with final catchphrase", "Michael's emotional return and final TWSS"], explanation: "The moment perfectly encapsulates Michael and Dwight's relationship." },
      { id: "ofc_600_03", categoryId: "tv_office", tier: 600, prompt: "What was the behind-the-scenes reason Steve Carell left the show after Season 7, and how did NBC reportedly handle it?", answer: "Reports suggest NBC never formally asked Carell to stay or offered him a new contract — he expected negotiations that never came. He later said he would have stayed if asked, making his departure one of TV's biggest missed opportunities", acceptableAnswers: ["NBC didn't offer a contract renewal", "Never formally asked him to stay", "NBC failed to negotiate his return"], explanation: "The show ran four more seasons without its star, with many fans considering it a significant decline." },
    ],
  },
  {
    id: "tv_fleabag",
    group: "tv",
    name: "Fleabag",
    culture: "universal",
    description: "Breaking the fourth wall and your heart — Phoebe Waller-Bridge's masterpiece.",
    imageUrl: "",
    questions: [
      { id: "flb_200_01", categoryId: "tv_fleabag", tier: 200, prompt: "Who created, wrote, and stars in Fleabag?", answer: "Phoebe Waller-Bridge", acceptableAnswers: ["Waller-Bridge", "Phoebe Waller-Bridge"], explanation: "Waller-Bridge adapted her one-woman stage show into the acclaimed TV series." },
      { id: "flb_200_02", categoryId: "tv_fleabag", tier: 200, prompt: "What narrative technique does Fleabag use where the main character directly addresses the viewer?", answer: "Breaking the fourth wall — she looks at and talks to the camera/audience throughout", acceptableAnswers: ["Breaking the fourth wall", "Talking to camera", "Direct address to audience"], explanation: "Fleabag's asides to the audience create intimacy and dark comedy simultaneously." },
      { id: "flb_200_03", categoryId: "tv_fleabag", tier: 200, prompt: "How many seasons does Fleabag have, and why was this significant?", answer: "Two seasons — Waller-Bridge deliberately ended it at its peak rather than continuing", acceptableAnswers: ["Two seasons", "2 seasons, ended at its peak"], explanation: "Fleabag's two-season run is praised as a perfect, complete story." },
      { id: "flb_400_01", categoryId: "tv_fleabag", tier: 400, prompt: "In Season 2, what character does Fleabag fall for, and why is the relationship impossible?", answer: "The 'Hot Priest' — a Catholic priest played by Andrew Scott. Their romance is doomed because he chooses his faith over her", acceptableAnswers: ["The Hot Priest", "A Catholic priest", "Andrew Scott's priest character"], explanation: "The chemistry between Fleabag and the Priest became one of TV's most talked-about romances." },
      { id: "flb_400_02", categoryId: "tv_fleabag", tier: 400, prompt: "What devastating secret about Fleabag's best friend Boo is gradually revealed throughout Season 1?", answer: "Boo died — and Fleabag is partly responsible, as an affair Fleabag had contributed to the events leading to Boo's death", acceptableAnswers: ["Boo died partly because of Fleabag", "Fleabag's role in Boo's death", "Best friend died and Fleabag is partly responsible"], explanation: "The gradual reveal of Fleabag's guilt transforms the show from comedy to tragedy." },
      { id: "flb_400_03", categoryId: "tv_fleabag", tier: 400, prompt: "What makes Olivia Colman's character (the Godmother) so brilliantly terrible?", answer: "She's passive-aggressive, narcissistic, and cruel while maintaining a veneer of warmth — she's marrying Fleabag's father and replacing their dead mother while pretending to be supportive", acceptableAnswers: ["Passive-aggressive stepmother figure", "Cruel while pretending to be kind", "Narcissistic replacement for dead mother"], explanation: "Colman makes the Godmother horrifying precisely because she seems so nice on the surface." },
      { id: "flb_600_01", categoryId: "tv_fleabag", tier: 600, prompt: "What is the significance of the moment in Season 2 when the Priest NOTICES Fleabag looking at the camera and asks 'Where did you just go?'", answer: "He's the first character to perceive her fourth-wall breaks — he can sense when she retreats to talk to the audience, breaking her protective barrier. It means he truly sees her in a way no one else can, making their connection unique and the audience's exclusive relationship with Fleabag suddenly vulnerable", acceptableAnswers: ["He notices her talking to camera", "First character to see her fourth-wall breaks", "He perceives her audience asides"], explanation: "This moment is one of TV's most inventive uses of the fourth wall — someone inside the story notices the storytelling device." },
      { id: "flb_600_02", categoryId: "tv_fleabag", tier: 600, prompt: "How does the final scene of the series use the fourth-wall device to deliver its emotional gut punch?", answer: "After the Priest chooses God over her, Fleabag walks away. She looks at the camera one last time, then shakes her head slightly — telling the audience not to follow her. She walks off screen, and the show ends. She's letting go of us too", acceptableAnswers: ["She tells the audience not to follow", "Shakes head at camera and walks away", "Breaks up with the audience"], explanation: "Fleabag's final fourth-wall break is a goodbye to the viewer — she no longer needs our company." },
      { id: "flb_600_03", categoryId: "tv_fleabag", tier: 600, prompt: "What was the original one-woman stage show version of Fleabag, and how does the 'guinea pig café' monologue function differently in live performance versus the TV show?", answer: "The stage show is a 65-minute monologue where the guinea pig café is central — Fleabag's café is failing because 'people didn't want to go to a café with guinea pigs because guinea pigs don't go with coffee.' In the show it's a background detail, but on stage it's the framing device for her unraveling, and the audience IS the fourth wall", acceptableAnswers: ["One-woman monologue, guinea pig café is central", "Stage show where café frames the story", "65-minute monologue with café as framing device"], explanation: "The stage version is rawer and more confessional — the TV show diffused the monologue across episodes." },
    ],
  },
  {
    id: "mu_beatles",
    group: "music",
    name: "The Beatles",
    culture: "universal",
    description: "The Fab Four — from Liverpool to legend in eight years.",
    imageUrl: "",
    questions: [
      { id: "btl_200_01", categoryId: "mu_beatles", tier: 200, prompt: "What city in England are The Beatles from?", answer: "Liverpool", explanation: "The Beatles formed in Liverpool and got their start playing clubs in the city and Hamburg, Germany." },
      { id: "btl_200_02", categoryId: "mu_beatles", tier: 200, prompt: "Who are the four members of The Beatles?", answer: "John Lennon, Paul McCartney, George Harrison, and Ringo Starr", acceptableAnswers: ["Lennon McCartney Harrison Starr", "John Paul George Ringo"], explanation: "Together they became the most influential and commercially successful band in history." },
      { id: "btl_200_03", categoryId: "mu_beatles", tier: 200, prompt: "What is the cultural phenomenon called 'Beatlemania' that swept the world in the 1960s?", answer: "The unprecedented fan hysteria surrounding The Beatles — screaming crowds, fainting fans, and massive media attention wherever they went", acceptableAnswers: ["Fan hysteria and mania around The Beatles", "Massive fan obsession", "Worldwide fan frenzy"], explanation: "Beatlemania was so intense that the band eventually stopped touring because they couldn't hear themselves play." },
      { id: "btl_400_01", categoryId: "mu_beatles", tier: 400, prompt: "What groundbreaking 1967 album is considered rock's first concept album and features songs like 'Lucy in the Sky with Diamonds' and 'A Day in the Life'?", answer: "Sgt. Pepper's Lonely Hearts Club Band", acceptableAnswers: ["Sgt. Pepper's", "Sgt Pepper", "Sgt. Pepper's Lonely Hearts Club Band"], explanation: "Sgt. Pepper's changed what an album could be — it was art, not just a collection of singles." },
      { id: "btl_400_02", categoryId: "mu_beatles", tier: 400, prompt: "What was the famous 'rooftop concert' and why was it significant?", answer: "The Beatles' final live performance, played unannounced on the roof of Apple Corps headquarters in London on January 30, 1969 — police eventually shut it down", acceptableAnswers: ["Final live performance on Apple Corps roof", "Last Beatles concert on a rooftop", "Rooftop at Apple HQ, last performance"], explanation: "The rooftop concert ended with John Lennon saying 'I'd like to say thank you on behalf of the group and ourselves and I hope we've passed the audition.'" },
      { id: "btl_400_03", categoryId: "mu_beatles", tier: 400, prompt: "What was the role of producer George Martin, often called 'the Fifth Beatle'?", answer: "Martin was their producer at Abbey Road Studios who arranged their orchestral elements, helped shape their experimental sound, and translated their ideas into reality — he was crucial to their evolution from pop to art", acceptableAnswers: ["Producer who shaped their sound", "Fifth Beatle producer at Abbey Road", "Arranged orchestrations and experimental production"], explanation: "Without Martin's classical music training and studio innovations, the Beatles' later work wouldn't have been possible." },
      { id: "btl_600_01", categoryId: "mu_beatles", tier: 600, prompt: "What studio techniques pioneered during the 'Revolver' and 'Sgt. Pepper's' sessions fundamentally changed recording technology?", answer: "Automatic double tracking (ADT), tape loops, backwards recording, varispeed tape manipulation, and close-miking techniques — many invented by engineer Ken Townsend and used for the first time on these albums", acceptableAnswers: ["ADT, tape loops, backwards recording", "Pioneering studio techniques with Ken Townsend", "Tape manipulation and recording innovations"], explanation: "The Beatles and their engineers essentially invented modern studio production during these sessions." },
      { id: "btl_600_02", categoryId: "mu_beatles", tier: 600, prompt: "What is the 'Paul is Dead' conspiracy theory, and what supposed 'clues' do believers point to?", answer: "A theory that Paul McCartney died in 1966 and was replaced by a lookalike — 'clues' include the Abbey Road cover (Paul barefoot = corpse), 'I buried Paul' heard in 'Strawberry Fields Forever' (actually 'cranberry sauce'), and backmasked messages", acceptableAnswers: ["Paul died and was replaced theory", "Replaced by lookalike, Abbey Road barefoot clue", "Death replacement conspiracy with album clues"], explanation: "Despite being thoroughly debunked, the conspiracy theory became one of rock's most enduring myths." },
      { id: "btl_600_03", categoryId: "tv_fleabag", tier: 600, prompt: "What was the 'Get Back' project (now the Peter Jackson documentary), and what did it reveal about the Beatles' breakup that contradicted decades of narrative?", answer: "Let It Be film (1970) portrayed the sessions as miserable and the band falling apart. Peter Jackson's 'Get Back' (2021) used 60 hours of unseen footage to show the Beatles were often joyful, collaborative, and creative — the breakup narrative was largely an editing choice by the original filmmakers", acceptableAnswers: ["Jackson doc showed Beatles were happier than believed", "60 hours of footage contradicted breakup narrative", "Original Let It Be misrepresented the sessions"], explanation: "Get Back fundamentally changed how people understand the Beatles' final days together." },
    ],
  },
  {
    id: "mu_country_outlaws",
    group: "music",
    name: "Outlaw Country",
    culture: "american",
    description: "Nashville rebels — Willie, Waylon, and the movement that broke Music Row's rules.",
    imageUrl: "",
    questions: [
      { id: "olc_200_01", categoryId: "mu_country_outlaws", tier: 200, prompt: "Which country music legend known for braids and marijuana advocacy recorded 'On the Road Again' and 'Blue Eyes Crying in the Rain'?", answer: "Willie Nelson", acceptableAnswers: ["Willie", "Willie Nelson"], explanation: "Willie Nelson has been a country icon for over 60 years." },
      { id: "olc_200_02", categoryId: "mu_country_outlaws", tier: 200, prompt: "What does 'Outlaw Country' refer to in the music world?", answer: "A movement in the 1970s where country artists rejected Nashville's polished studio system and took creative control of their own music", acceptableAnswers: ["Rejection of Nashville establishment", "Artists taking creative control from Nashville", "Anti-Nashville country movement"], explanation: "Outlaw country was a rebellion against Music Row's formulaic approach to country music." },
      { id: "olc_200_03", categoryId: "mu_country_outlaws", tier: 200, prompt: "Who is the 'Man in Black' — the country legend known for performing at prisons and songs like 'Ring of Fire' and 'Folsom Prison Blues'?", answer: "Johnny Cash", acceptableAnswers: ["Cash", "Johnny Cash"], explanation: "Cash's concerts at Folsom Prison and San Quentin became legendary live albums." },
      { id: "olc_400_01", categoryId: "mu_country_outlaws", tier: 400, prompt: "What was the landmark 1976 album 'Wanted! The Outlaws,' and why was it historically significant?", answer: "A compilation featuring Waylon Jennings, Willie Nelson, Jessi Colter, and Tompall Glaser — it became country music's first platinum-certified album", acceptableAnswers: ["First platinum country album", "Waylon Willie Jessi Tompall compilation", "First country album to go platinum"], explanation: "The album proved that country music made outside Nashville's control could achieve massive commercial success." },
      { id: "olc_400_02", categoryId: "mu_country_outlaws", tier: 400, prompt: "What did Waylon Jennings famously demand from his record label RCA that was unprecedented for a Nashville artist?", answer: "Full artistic control — he demanded to choose his own songs, musicians, and studio, rather than using Nashville's session players and A&R-chosen material", acceptableAnswers: ["Full creative control", "Choose his own songs and musicians", "Artistic control over recordings"], explanation: "Jennings' insistence on creative freedom was the spark that ignited the Outlaw movement." },
      { id: "olc_400_03", categoryId: "mu_country_outlaws", tier: 400, prompt: "What is the tragic backstory behind the song 'He Stopped Loving Her Today' by George Jones, often called the greatest country song ever recorded?", answer: "A song about a man whose love only ends when he dies — Jones initially didn't want to record it and took over a year to finish vocals due to his severe alcoholism and cocaine addiction", acceptableAnswers: ["About love ending only in death, Jones struggled recording it", "Man loves until death, Jones fought addiction during recording", "Greatest country song, Jones nearly couldn't record it"], explanation: "The production difficulties mirrored the song's devastating subject matter." },
      { id: "olc_600_01", categoryId: "mu_country_outlaws", tier: 600, prompt: "What was the relationship between Johnny Cash and the Nashville establishment, and how did the 'American Recordings' albums with Rick Rubin reinvent his career?", answer: "Nashville had largely abandoned Cash by the 1980s-90s. Rick Rubin recorded him solo with just an acoustic guitar, covering songs by Nine Inch Nails, Soundgarden, and Depeche Mode — the stripped-down approach made Cash relevant to a new generation and produced the iconic 'Hurt' video shortly before his death", acceptableAnswers: ["Rubin revived Cash with stripped-down covers", "American Recordings with rock covers saved his career", "Nashville abandoned him, Rubin revived with NIN covers"], explanation: "Cash's cover of 'Hurt' by Nine Inch Nails became one of the most powerful music videos ever made." },
      { id: "olc_600_02", categoryId: "mu_country_outlaws", tier: 600, prompt: "What did Waylon Jennings narrowly avoid by giving up his seat on a plane, and how did the tragedy affect his life?", answer: "Jennings gave his seat on the plane to J.P. 'The Big Bopper' Richardson on the flight that killed Buddy Holly, Ritchie Valens, and the Big Bopper — 'the day the music died.' The survivor's guilt haunted Jennings for the rest of his life", acceptableAnswers: ["Gave seat to Big Bopper on Buddy Holly's plane", "Survived the Buddy Holly plane crash", "Day the music died, gave up his seat"], explanation: "Jennings had jokingly told Holly he hoped the plane crashed; when it did, the guilt was devastating." },
      { id: "olc_600_03", categoryId: "mu_country_outlaws", tier: 600, prompt: "How does the modern 'alt-country' and 'Americana' movement trace its lineage to the Outlaws, and what artist bridge connects them?", answer: "Townes Van Zandt and Guy Clark mentored both the original outlaws and later alt-country artists like Steve Earle — the lineage runs from Jennings/Nelson through Van Zandt to Earle, Lucinda Williams, and modern Americana. The common thread is songwriting authenticity over commercial formula", acceptableAnswers: ["Van Zandt and Clark bridged outlaws to Americana", "Townes Van Zandt connects outlaws to alt-country", "Songwriting lineage through Van Zandt to modern Americana"], explanation: "The Outlaw spirit — artistic integrity over commercial formula — defines Americana to this day." },
    ],
  },
  {
    id: "vg_hades",
    group: "video_games",
    name: "Hades",
    culture: "universal",
    description: "Escape the Underworld, die, repeat — with style, story, and Supergiant's magic.",
    imageUrl: "",
    questions: [
      { id: "hds_200_01", categoryId: "vg_hades", tier: 200, prompt: "In Hades, who is the main character trying to escape the Underworld, and who is his father?", answer: "Zagreus, son of Hades", acceptableAnswers: ["Zagreus", "Zagreus son of Hades"], explanation: "Zagreus repeatedly escapes the Underworld, dying and returning to try again." },
      { id: "hds_200_02", categoryId: "vg_hades", tier: 200, prompt: "What genre is Hades — a type of game where each death sends you back to the start with some permanent upgrades?", answer: "Roguelike (or roguelite)", acceptableAnswers: ["Roguelike", "Roguelite", "Rogue-like"], explanation: "Hades is credited with bringing roguelikes to mainstream audiences through its story integration." },
      { id: "hds_200_03", categoryId: "vg_hades", tier: 200, prompt: "What do the Olympian gods give Zagreus during each escape attempt to power him up?", answer: "Boons — divine power-ups that modify his abilities", acceptableAnswers: ["Boons", "Divine boons", "God boons"], explanation: "Each Olympian offers different boon types — Zeus gives lightning, Ares gives blades, etc." },
      { id: "hds_400_01", categoryId: "vg_hades", tier: 400, prompt: "What innovative feature does Hades use to make death feel meaningful narratively, unlike most roguelikes?", answer: "Every death returns Zagreus to the House of Hades where NPCs have new dialogue, relationships advance, and the story progresses — dying IS the story progression mechanic", acceptableAnswers: ["Death advances story and NPC dialogue", "NPCs update after each death", "Story progresses through dying"], explanation: "Hades solved the roguelike narrative problem by making failure part of the story." },
      { id: "hds_400_02", categoryId: "vg_hades", tier: 400, prompt: "What are the Infernal Arms that Zagreus can wield, and how do their 'Aspects' change gameplay?", answer: "Six weapons (blade, bow, spear, shield, rail gun, fists) — each has multiple Aspects that fundamentally change how the weapon plays, named after mythological figures", acceptableAnswers: ["Six weapons with multiple Aspects each", "Blade bow spear shield gun fists with variant forms", "Weapons with mythological aspect variants"], explanation: "The Aspect system multiplies the weapon count, giving massive variety across runs." },
      { id: "hds_400_03", categoryId: "vg_hades", tier: 400, prompt: "Who does Zagreus discover is his true mother, and what drives his escape attempts?", answer: "Persephone — she left the Underworld before Zagreus was told about her. His escape attempts are motivated by finding her", acceptableAnswers: ["Persephone", "His mother Persephone"], explanation: "The family drama between Hades, Persephone, and Zagreus provides emotional depth rare in action games." },
      { id: "hds_600_01", categoryId: "vg_hades", tier: 600, prompt: "What happens after you 'beat' Hades for the first time, and how many escapes does the true ending require?", answer: "The first escape isn't the end — Zagreus reaches the surface but is pulled back because he can't survive outside the Underworld. The true ending requires roughly 10 successful escapes to fully resolve the family storyline, plus many more for epilogue content", acceptableAnswers: ["First escape isn't the end, needs ~10 for true ending", "Gets pulled back, needs many escapes for full story", "Surface kills him, true ending after ~10 clears"], explanation: "Hades uses repeated escapes as narrative acts — the story unfolds over dozens of runs." },
      { id: "hds_600_02", categoryId: "vg_hades", tier: 600, prompt: "What is the 'Pact of Punishment' system, and how does it enable endless replayability while maintaining narrative purpose?", answer: "After first clearing, the Pact adds modifiable difficulty conditions (extra enemy health, boss patterns, time limits) that increase 'Heat' — higher Heat unlocks new rewards and dialogue. It gives mechanical challenge a narrative wrapper: Zagreus is making escape harder on purpose", acceptableAnswers: ["Modular difficulty modifiers with narrative justification", "Heat system adding difficulty for new rewards", "Customizable challenge increasing for new content"], explanation: "The Pact elegantly solves the 'why keep playing' problem by tying difficulty to content unlocks." },
      { id: "hds_600_03", categoryId: "vg_hades", tier: 600, prompt: "How did Supergiant Games' Early Access development of Hades differ from typical Early Access, and what impact did it have on the game?", answer: "They released the game in Early Access specifically to develop the narrative — player feedback shaped romance options, NPC arcs, and dialogue. The roguelike loop meant players naturally replayed content, providing massive testing data. The story was essentially co-developed with the community over two years", acceptableAnswers: ["Story developed with player feedback during Early Access", "Community shaped narrative through 2-year EA", "Used EA to co-develop story with players"], explanation: "Hades' EA approach was uniquely suited to a roguelike — repetition naturally tested the game's systems." },
    ],
  },
  {
    id: "mv_martin_scorsese",
    group: "movies",
    name: "Martin Scorsese",
    culture: "american",
    description: "Mean streets, wise guys, and cinema's greatest living director.",
    imageUrl: "",
    questions: [
      { id: "sco_200_01", categoryId: "mv_martin_scorsese", tier: 200, prompt: "What 1990 Scorsese film follows Henry Hill's rise and fall in the New York mafia?", answer: "Goodfellas", explanation: "Based on Nicholas Pileggi's book 'Wiseguy,' Goodfellas is considered the greatest mob film alongside The Godfather." },
      { id: "sco_200_02", categoryId: "mv_martin_scorsese", tier: 200, prompt: "Which actor has appeared in the most Martin Scorsese films, starring in classics like 'Taxi Driver,' 'Raging Bull,' and 'Goodfellas'?", answer: "Robert De Niro", acceptableAnswers: ["De Niro", "Robert De Niro"], explanation: "The Scorsese-De Niro partnership produced some of cinema's greatest performances." },
      { id: "sco_200_03", categoryId: "mv_martin_scorsese", tier: 200, prompt: "What 2006 Scorsese film about an undercover cop and a mole in the Boston mob finally won him the Best Director Oscar?", answer: "The Departed", explanation: "Based on the Hong Kong film 'Infernal Affairs,' The Departed won Scorsese his long-overdue Oscar." },
      { id: "sco_400_01", categoryId: "mv_martin_scorsese", tier: 400, prompt: "What is the famous tracking shot in 'Goodfellas' that follows Henry and Karen through a nightclub's back entrance?", answer: "The Copacabana shot — a nearly 3-minute unbroken Steadicam shot following them through the kitchen, hallways, and into the club, showing Henry's power and seductiveness", acceptableAnswers: ["Copa shot", "Copacabana tracking shot", "Copa long take through kitchen"], explanation: "The shot puts the audience in Karen's shoes — seduced by Henry's world just as she is." },
      { id: "sco_400_02", categoryId: "mv_martin_scorsese", tier: 400, prompt: "In 'Taxi Driver,' what famous line does Travis Bickle say to himself in the mirror?", answer: "You talkin' to me?", acceptableAnswers: ["You talking to me", "You talkin to me"], explanation: "De Niro improvised the iconic mirror scene, which wasn't in the original screenplay." },
      { id: "sco_400_03", categoryId: "mv_martin_scorsese", tier: 400, prompt: "What is Scorsese's relationship with Leonardo DiCaprio, and how many films have they made together?", answer: "DiCaprio became Scorsese's new muse after De Niro, collaborating on films including Gangs of New York, The Aviator, The Departed, Shutter Island, The Wolf of Wall Street, and Killers of the Flower Moon — six films and counting", acceptableAnswers: ["Six+ films together", "New muse after De Niro, 6+ films", "Long partnership of 6+ films"], explanation: "The DiCaprio era brought Scorsese to new generations of audiences." },
      { id: "sco_600_01", categoryId: "mv_martin_scorsese", tier: 600, prompt: "What was the controversy around Scorsese's comments about Marvel movies not being 'cinema,' and what was his actual argument?", answer: "Scorsese said Marvel films aren't cinema but 'theme parks' — his actual point was about the business model: when theaters only show franchise content, there's no room for diverse filmmaking. He wasn't attacking quality but lamenting the ecosystem that squeezes out mid-budget adult dramas", acceptableAnswers: ["Theme parks comment about business model not quality", "Argued franchise dominance kills diverse filmmaking", "Not attacking Marvel quality but industry ecosystem"], explanation: "The nuanced argument was reduced to 'old man yells at Marvel' in most coverage." },
      { id: "sco_600_02", categoryId: "mv_martin_scorsese", tier: 600, prompt: "What makes the 'Layla' sequence in Goodfellas — where bodies are discovered while Derek and the Dominos play — considered a masterclass in editing?", answer: "The piano coda of 'Layla' plays over a montage of dead bodies being discovered in various locations — the beautiful, melancholic music creates devastating irony against the violence. The editing rhythm matches the music perfectly, making murder feel elegant and horrifying simultaneously", acceptableAnswers: ["Bodies discovered to beautiful Layla music", "Ironic juxtaposition of beauty and violence", "Piano coda over murder discovery montage"], explanation: "The sequence demonstrates Scorsese's signature technique of using pop music to create complex emotional responses to violence." },
      { id: "sco_600_03", categoryId: "mv_martin_scorsese", tier: 600, prompt: "What is the significance of 'The Irishman' (2019) using de-aging technology, and how does the film's final act comment on the entire gangster genre?", answer: "De-aging lets De Niro, Pesci, and Pacino play their characters across decades — but the final act shows Frank Sheeran old, alone, abandoned, and forgotten, unable to close his own door. After decades of glamorizing mob life, Scorsese's final gangster film is a meditation on the emptiness of violence and the loneliness of outliving everyone you killed or betrayed", acceptableAnswers: ["De-aged actors showing emptiness of mob life", "Final gangster film about loneliness after violence", "Deglamorizing mob genre with old lonely Sheeran"], explanation: "The Irishman is Scorsese's deliberate dismantling of the very genre he defined." },
    ],
  },
  {
    id: "his_philosophy",
    group: "history",
    name: "Great Philosophers",
    culture: "universal",
    description: "From Socrates to Nietzsche — the thinkers who questioned everything.",
    imageUrl: "",
    questions: [
      { id: "phi_200_01", categoryId: "his_philosophy", tier: 200, prompt: "What ancient Greek philosopher is famous for his method of teaching through asking questions rather than giving answers?", answer: "Socrates", explanation: "The Socratic method — teaching through questions — is still used in law schools and classrooms." },
      { id: "phi_200_02", categoryId: "his_philosophy", tier: 200, prompt: "What French philosopher said 'I think, therefore I am' (Cogito ergo sum)?", answer: "René Descartes", acceptableAnswers: ["Descartes"], explanation: "Descartes used radical doubt to find the one thing he couldn't doubt — his own thinking." },
      { id: "phi_200_03", categoryId: "his_philosophy", tier: 200, prompt: "What German philosopher declared 'God is dead' and wrote about the 'Übermensch' (Superman)?", answer: "Friedrich Nietzsche", acceptableAnswers: ["Nietzsche"], explanation: "Nietzsche's 'God is dead' wasn't a celebration but a warning about what happens when society loses shared meaning." },
      { id: "phi_400_01", categoryId: "his_philosophy", tier: 400, prompt: "What is Plato's 'Allegory of the Cave,' and what does it represent?", answer: "Prisoners chained in a cave see only shadows on the wall and think that's reality. One escapes and sees the real world — it represents the difference between perception and truth, and the philosopher's duty to enlighten others", acceptableAnswers: ["Prisoners seeing shadows mistake them for reality", "Cave shadows vs real world representing perception vs truth", "Prisoners think shadows are reality"], explanation: "The Cave is philosophy's most famous thought experiment about the nature of knowledge." },
      { id: "phi_400_02", categoryId: "his_philosophy", tier: 400, prompt: "What is the 'trolley problem' in ethics, and what two moral frameworks does it test?", answer: "Should you divert a trolley to kill one person instead of five? It tests utilitarianism (greatest good for greatest number = divert) vs deontological ethics (actively killing someone is always wrong = don't divert)", acceptableAnswers: ["Divert trolley killing one to save five", "Utilitarianism vs deontological ethics", "Kill one to save five moral dilemma"], explanation: "The trolley problem reveals fundamental disagreements about whether outcomes or actions determine morality." },
      { id: "phi_400_03", categoryId: "his_philosophy", tier: 400, prompt: "What did existentialist Jean-Paul Sartre mean by 'existence precedes essence'?", answer: "Humans have no predetermined purpose or nature — we exist first, then define ourselves through our choices. We are 'condemned to be free' because we must create our own meaning", acceptableAnswers: ["We exist before having purpose", "No predetermined nature, we create meaning", "Humans define themselves through choices"], explanation: "Sartre's existentialism puts radical responsibility on the individual to create their own meaning." },
      { id: "phi_600_01", categoryId: "his_philosophy", tier: 600, prompt: "What is Wittgenstein's 'language game' theory, and how did it revolutionize philosophy?", answer: "Wittgenstein argued that words don't have fixed meanings — their meaning comes from how they're used in context, like moves in a game. Different communities play different 'language games.' This dissolved many philosophical problems by showing they were caused by misusing language across different contexts", acceptableAnswers: ["Words mean their usage not fixed definitions", "Meaning comes from contextual use like games", "Language meaning is use-based, dissolving philosophical confusion"], explanation: "Wittgenstein argued most philosophical problems aren't real problems — they're language confusion." },
      { id: "phi_600_02", categoryId: "his_philosophy", tier: 600, prompt: "What is Simone de Beauvoir's argument in 'The Second Sex' that 'one is not born, but rather becomes, a woman'?", answer: "Gender is constructed by society, not biology — women aren't born into a subordinate role but are shaped into one by social expectations, education, and cultural norms. She distinguished between biological sex and the social construction of femininity", acceptableAnswers: ["Gender is socially constructed not biological", "Woman is a social construction", "Femininity is made by society not nature"], explanation: "Published in 1949, The Second Sex laid the groundwork for modern feminism and gender theory." },
      { id: "phi_600_03", categoryId: "his_philosophy", tier: 600, prompt: "What is the 'veil of ignorance' thought experiment by John Rawls, and what principles of justice does it produce?", answer: "Imagine designing society without knowing what position you'd occupy in it (race, wealth, ability). Rawls argues rational people behind this 'veil' would choose: equal basic liberties for all, and inequalities only if they benefit the least advantaged members — because you might BE the least advantaged", acceptableAnswers: ["Design society not knowing your position in it", "Equal liberties plus inequality only if it helps the worst-off", "Ignorance of position leads to fairness"], explanation: "Rawls' thought experiment provides a powerful framework for evaluating whether social systems are just." },
    ],
  },
  {
    id: "sci_ai",
    group: "science",
    name: "Artificial Intelligence",
    culture: "universal",
    description: "From Turing tests to transformers — the quest to build thinking machines.",
    imageUrl: "",
    questions: [
      { id: "aai_200_01", categoryId: "sci_ai", tier: 200, prompt: "What test, proposed by Alan Turing in 1950, evaluates whether a machine can exhibit intelligent behavior indistinguishable from a human?", answer: "The Turing Test", acceptableAnswers: ["Turing Test", "Imitation Game"], explanation: "Turing asked: if a machine can fool a human into thinking it's also human, can it 'think'?" },
      { id: "aai_200_02", categoryId: "sci_ai", tier: 200, prompt: "What does 'AI' stand for?", answer: "Artificial Intelligence", explanation: "The term was coined at the 1956 Dartmouth Conference." },
      { id: "aai_200_03", categoryId: "sci_ai", tier: 200, prompt: "What AI system developed by DeepMind defeated the world champion at the ancient board game Go in 2016?", answer: "AlphaGo", acceptableAnswers: ["AlphaGo"], explanation: "AlphaGo's victory over Lee Sedol was considered a landmark moment — Go was thought too complex for AI." },
      { id: "aai_400_01", categoryId: "sci_ai", tier: 400, prompt: "What is 'machine learning,' and how does it differ from traditional programming?", answer: "Instead of being explicitly programmed with rules, ML systems learn patterns from data — they improve through experience rather than human-written instructions", acceptableAnswers: ["Learning from data instead of explicit rules", "Systems that learn from data", "Pattern recognition from data vs programmed rules"], explanation: "Machine learning lets systems handle problems too complex to program with explicit rules." },
      { id: "aai_400_02", categoryId: "sci_ai", tier: 400, prompt: "What is a 'neural network' in AI, and what biological system inspired its design?", answer: "A computing system inspired by the human brain's neurons — layers of interconnected nodes process information, with each connection having adjustable weights that change during training", acceptableAnswers: ["Brain-inspired layered computing nodes", "Interconnected nodes inspired by brain neurons", "Artificial neurons in connected layers"], explanation: "Neural networks loosely mimic how biological neurons connect and signal each other." },
      { id: "aai_400_03", categoryId: "sci_ai", tier: 400, prompt: "What is a 'large language model' (LLM), and what is the basic principle behind how it generates text?", answer: "An AI trained on massive text datasets that generates text by predicting the most likely next word/token in a sequence — it's essentially very sophisticated pattern matching and prediction at an enormous scale", acceptableAnswers: ["Text prediction model trained on massive data", "Next-word prediction at massive scale", "Predicts next token from training patterns"], explanation: "LLMs like GPT and Claude generate text by predicting what comes next based on patterns in training data." },
      { id: "aai_600_01", categoryId: "sci_ai", tier: 600, prompt: "What is the 'alignment problem' in AI safety, and why do researchers consider it an existential challenge?", answer: "The difficulty of ensuring AI systems actually do what humans intend — even well-specified goals can lead to harmful behavior if the AI finds unexpected ways to maximize its objective. A misaligned superintelligent AI could pursue goals catastrophically mismatched with human values", acceptableAnswers: ["Ensuring AI does what humans actually intend", "AI pursuing unintended harmful strategies", "Matching AI goals to human values"], explanation: "The alignment problem is considered one of the most important unsolved problems in AI research." },
      { id: "aai_600_02", categoryId: "sci_ai", tier: 600, prompt: "What is the 'transformer architecture' introduced in the 2017 paper 'Attention Is All You Need,' and why did it revolutionize AI?", answer: "Transformers use 'self-attention' to process all parts of input simultaneously rather than sequentially — this parallelization enabled training on vastly larger datasets and produced breakthroughs in language, vision, and beyond. Virtually all modern AI (GPT, Claude, etc.) is built on transformers", acceptableAnswers: ["Self-attention processing all input simultaneously", "Parallel processing architecture replacing sequential", "Attention mechanism enabling modern AI"], explanation: "The transformer paper is arguably the most influential AI paper of the 21st century." },
      { id: "aai_600_03", categoryId: "sci_ai", tier: 600, prompt: "What is the 'Chinese Room' thought experiment by John Searle, and what does it argue about AI understanding?", answer: "A person in a room follows rules to respond to Chinese characters without understanding Chinese — Searle argues this is what AI does: manipulating symbols without genuine understanding. Even a perfect simulation of intelligence isn't actual intelligence or consciousness", acceptableAnswers: ["Following rules without understanding proves AI doesn't think", "Symbol manipulation without comprehension", "Simulating intelligence isn't real understanding"], explanation: "The Chinese Room challenges whether any computational system can truly 'understand' rather than just process." },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print(f"SUCCESS: Wave 74 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
