#!/usr/bin/env python3
"""Insert wave 66 categories into categories.ts"""
import sys

CATEGORIES_PATH = "C:/Users/janti/downloads/Data-Model-Home/Data-Model-Home/artifacts/renegade/constants/categories.ts"

NEW_CATEGORIES = r"""
  {
    id: "tv_hannibal",
    group: "TV Shows",
    name: "Hannibal (NBC)",
    culture: "american",
    description: "Bryan Fuller's visually stunning reimagining of the Hannibal Lecter story — a psychological horror series disguised as a network procedural.",
    imageUrl: "",
    questions: [
      {
        id: "han_200_01",
        categoryId: "tv_hannibal",
        tier: 200,
        prompt: "Who plays Hannibal Lecter in the NBC series Hannibal?",
        answer: "Mads Mikkelsen",
        acceptableAnswers: [],
      },
      {
        id: "han_200_02",
        categoryId: "tv_hannibal",
        tier: 200,
        prompt: "What is the name of the FBI profiler whose empathic abilities draw him into a dangerous relationship with Hannibal?",
        answer: "Will Graham",
        acceptableAnswers: [],
      },
      {
        id: "han_200_03",
        categoryId: "tv_hannibal",
        tier: 200,
        prompt: "What is Hannibal Lecter's day job that gives him access to the FBI investigation?",
        answer: "He is a psychiatrist — specifically, he is Will Graham's therapist and an FBI consultant",
        acceptableAnswers: ["psychiatrist", "therapist"],
      },
      {
        id: "han_400_01",
        categoryId: "tv_hannibal",
        tier: 400,
        prompt: "Hannibal is famous for its elaborate meal preparation scenes. What is the dark irony of these beautifully presented dishes?",
        answer: "Hannibal is serving his guests human flesh, prepared as haute cuisine — and they unknowingly eat it and compliment it",
        acceptableAnswers: ["he's feeding them human meat", "the food is made from people"],
      },
      {
        id: "han_400_02",
        categoryId: "tv_hannibal",
        tier: 400,
        prompt: "The show's murder tableaux are extraordinarily artistic. Who served as the food stylist, and what made the food photography distinctive?",
        answer: "Janice Poon was the food stylist. Every dish was designed to look both beautiful and subtly disturbing, and she maintained a blog documenting the creative process behind each 'cannibal' meal.",
        acceptableAnswers: ["Janice Poon", "a dedicated food stylist who blogged about it"],
      },
      {
        id: "han_400_03",
        categoryId: "tv_hannibal",
        tier: 400,
        prompt: "The Season 2 finale features a devastating scene where Hannibal attacks multiple characters. What classical music piece plays during this sequence?",
        answer: "The aria 'Vide Cor Meum' and Bach's Goldberg Variations feature in the show's key scenes, but the Season 2 finale massacre is set to a haunting operatic score",
        acceptableAnswers: ["classical music accompanies the violence", "operatic music during the attack"],
        explanation: "The juxtaposition of elegant classical music with extreme violence became the show's signature — Hannibal's cultured exterior masking his monstrous nature.",
      },
      {
        id: "han_600_01",
        categoryId: "tv_hannibal",
        tier: 600,
        prompt: "Bryan Fuller has described the relationship between Hannibal and Will Graham using a specific term. What does he call it, and how does the series finale embody it?",
        answer: "He calls it a 'love story' and a 'bromance to romance.' The finale has Hannibal and Will embrace while falling off a cliff together — a consummation of their relationship through shared violence.",
        acceptableAnswers: ["a love story, they fall off a cliff together", "romantic, the cliff embrace in the finale"],
      },
      {
        id: "han_600_02",
        categoryId: "tv_hannibal",
        tier: 600,
        prompt: "The show aired on NBC, a broadcast network, yet contained some of the most graphic imagery ever on network TV. How did the show get away with showing such extreme content?",
        answer: "NBC's standards department allowed the violence because it was so stylized and artistically presented that it didn't register as 'realistic' gore — bodies were posed as art installations, making them more surreal than gratuitous",
        acceptableAnswers: ["the violence was so artistically stylized it passed censors", "it was too artistic to be considered realistic gore"],
        explanation: "Paradoxically, making the murders MORE elaborate and artistic made them MORE acceptable to network censors than simple realistic violence would have been.",
      },
      {
        id: "han_600_03",
        categoryId: "tv_hannibal",
        tier: 600,
        prompt: "Hannibal was cancelled after three seasons despite critical acclaim. What unique fan campaign tried to save it, and what streaming platform nearly picked it up?",
        answer: "Fans (called 'Fannibals') organized elaborate campaigns including sending animal hearts to NBC executives. Amazon and Netflix both explored picking up the show, but rights issues with the Silence of the Lambs characters (held by MGM) prevented continuation.",
        acceptableAnswers: ["fans sent animal hearts to NBC, Amazon/Netflix nearly picked it up", "Fannibals campaigned, rights issues prevented continuation"],
      },
    ],
  },
  {
    id: "tv_leftovers",
    group: "TV Shows",
    name: "The Leftovers",
    culture: "american",
    description: "Damon Lindelof's HBO masterpiece about a world struggling to cope after 2% of the global population vanishes without explanation.",
    imageUrl: "",
    questions: [
      {
        id: "lft_200_01",
        categoryId: "tv_leftovers",
        tier: 200,
        prompt: "What catastrophic event kicks off The Leftovers — the 'Sudden Departure'?",
        answer: "2% of the world's population (approximately 140 million people) vanish simultaneously without explanation",
        acceptableAnswers: ["2% of people disappear", "millions of people vanish", "the Sudden Departure"],
      },
      {
        id: "lft_200_02",
        categoryId: "tv_leftovers",
        tier: 200,
        prompt: "Who plays Kevin Garvey, the police chief at the center of The Leftovers?",
        answer: "Justin Theroux",
        acceptableAnswers: [],
      },
      {
        id: "lft_200_03",
        categoryId: "tv_leftovers",
        tier: 200,
        prompt: "What is the name of the cult whose members dress in all white, chain-smoke, take vows of silence, and serve as 'living reminders' of the departed?",
        answer: "The Guilty Remnant",
        acceptableAnswers: ["GR"],
      },
      {
        id: "lft_400_01",
        categoryId: "tv_leftovers",
        tier: 400,
        prompt: "The show is based on a novel by Tom Perrotta. How does the show's scope differ from the book?",
        answer: "The book only covers Season 1's story. Seasons 2 and 3 are entirely original, moving the story to Jarden, Texas and then to Australia — widely considered superior to the source material.",
        acceptableAnswers: ["the book only covers season 1", "seasons 2 and 3 are original"],
      },
      {
        id: "lft_400_02",
        categoryId: "tv_leftovers",
        tier: 400,
        prompt: "Season 2 moves to the town of Jarden, Texas, which has a special significance. What makes Jarden unique?",
        answer: "Not a single person from Jarden departed — making it a miracle town renamed 'Miracle' that becomes a pilgrimage destination and gated community",
        acceptableAnswers: ["no one departed from there", "zero departures, called Miracle"],
      },
      {
        id: "lft_400_03",
        categoryId: "tv_leftovers",
        tier: 400,
        prompt: "The show's use of music is legendary. What song by the band Iris DeMent plays over the Season 2 opening credits and became synonymous with the show?",
        answer: "'Let the Mystery Be'",
        acceptableAnswers: ["Let the Mystery Be"],
        explanation: "The song's message — accepting that some questions have no answers — perfectly encapsulates the show's philosophy of living with ambiguity.",
      },
      {
        id: "lft_600_01",
        categoryId: "tv_leftovers",
        tier: 600,
        prompt: "The episode 'International Assassin' (Season 2, Episode 8) is widely considered one of the greatest TV episodes ever made. What happens in it?",
        answer: "Kevin dies and enters a purgatory-like hotel where he must assassinate a presidential candidate (who is actually Patti Levin from the Guilty Remnant) to return to life — blending genres from spy thriller to religious allegory",
        acceptableAnswers: ["Kevin goes to a hotel afterlife and must kill Patti", "he dies and enters a purgatory hotel"],
        explanation: "The episode completely shifts genres mid-series. Kevin wakes up in a bathtub in a hotel, dressed as an assassin, in a surreal afterlife that became the show's most discussed sequence.",
      },
      {
        id: "lft_600_02",
        categoryId: "tv_leftovers",
        tier: 600,
        prompt: "The series finale features Nora telling Kevin a story about what happened to the departed. Does the show confirm whether her story is true?",
        answer: "No — and that's the point. Nora claims she crossed over and found the departed living in a parallel world where 98% vanished, but chose to come back. The show deliberately leaves it ambiguous whether she's telling the truth or a comforting lie.",
        acceptableAnswers: ["no, it's left ambiguous", "it never confirms her story"],
        explanation: "Lindelof designed the finale so viewers must choose to believe or not — mirroring the show's central theme of faith versus empiricism.",
      },
      {
        id: "lft_600_03",
        categoryId: "tv_leftovers",
        tier: 600,
        prompt: "Damon Lindelof created The Leftovers partly as a response to criticisms of his previous show. What was that show, and what specific criticism did The Leftovers address?",
        answer: "Lost — Lindelof was heavily criticized for the Lost finale not answering enough mysteries. The Leftovers explicitly states from the beginning that the Departure will NEVER be explained, forcing viewers to accept ambiguity rather than expecting answers.",
        acceptableAnswers: ["Lost, he addressed complaints about unanswered mysteries", "response to Lost's finale backlash"],
      },
    ],
  },
  {
    id: "mv_godfather",
    group: "Movies",
    name: "The Godfather Trilogy",
    culture: "american",
    description: "Francis Ford Coppola's epic saga of the Corleone crime family — the making, the mythology, and the cultural impact of cinema's greatest gangster story.",
    imageUrl: "",
    questions: [
      {
        id: "gdf_200_01",
        categoryId: "mv_godfather",
        tier: 200,
        prompt: "Who plays Vito Corleone, the Godfather, in the original 1972 film?",
        answer: "Marlon Brando",
        acceptableAnswers: [],
      },
      {
        id: "gdf_200_02",
        categoryId: "mv_godfather",
        tier: 200,
        prompt: "What famous line does Vito Corleone say about the kind of offer he makes?",
        answer: "I'm gonna make him an offer he can't refuse",
        acceptableAnswers: ["an offer he can't refuse"],
      },
      {
        id: "gdf_200_03",
        categoryId: "mv_godfather",
        tier: 200,
        prompt: "Which of Vito's sons takes over the family business and becomes the new Don in The Godfather?",
        answer: "Michael Corleone",
        acceptableAnswers: ["Michael"],
      },
      {
        id: "gdf_400_01",
        categoryId: "mv_godfather",
        tier: 400,
        prompt: "The studio originally did not want Al Pacino for Michael Corleone and fought Coppola over the casting. Who did Paramount Pictures prefer for the role?",
        answer: "Robert Redford, Ryan O'Neal, and Warren Beatty were all considered. The studio wanted a bigger star — Pacino was relatively unknown at the time.",
        acceptableAnswers: ["Robert Redford", "a bigger star, Pacino was unknown"],
      },
      {
        id: "gdf_400_02",
        categoryId: "mv_godfather",
        tier: 400,
        prompt: "Marlon Brando's famous mumbling voice as Vito Corleone was achieved through a specific physical technique. What did he do?",
        answer: "He stuffed cotton balls (later replaced by a dental prosthetic) into his cheeks to create the heavy jowled, mumbling voice of the aging Don",
        acceptableAnswers: ["cotton balls in his cheeks", "a dental prosthetic in his mouth", "stuffed his cheeks"],
      },
      {
        id: "gdf_400_03",
        categoryId: "mv_godfather",
        tier: 400,
        prompt: "The baptism scene at the end of The Godfather is considered one of cinema's greatest sequences. What makes it so powerful structurally?",
        answer: "It cross-cuts between Michael renouncing Satan during his nephew's baptism and the simultaneous assassination of all five rival family heads — his words of faith juxtaposed with acts of murder he ordered",
        acceptableAnswers: ["baptism intercut with murders", "Michael renouncing evil while committing evil"],
      },
      {
        id: "gdf_600_01",
        categoryId: "mv_godfather",
        tier: 600,
        prompt: "Brando won the Best Actor Oscar for The Godfather but refused it. Who did he send in his place, and what was the political statement?",
        answer: "He sent Sacheen Littlefeather, a Native American actress and activist, who declined the award on his behalf to protest Hollywood's treatment of Native Americans",
        acceptableAnswers: ["Sacheen Littlefeather", "a Native American woman protesting Hollywood's treatment of Native Americans"],
        explanation: "Littlefeather was booed by parts of the audience. In 2022, the Academy formally apologized to her, 50 years later — just months before she died.",
      },
      {
        id: "gdf_600_02",
        categoryId: "mv_godfather",
        tier: 600,
        prompt: "Coppola was nearly fired during production multiple times. What was the studio's main complaint, and who did they consider replacing him with?",
        answer: "The studio thought Coppola was shooting too slowly and the footage was too dark. They considered replacing him with Elia Kazan. Producer Robert Evans was receiving daily pressure to fire Coppola.",
        acceptableAnswers: ["too slow and dark footage, nearly replaced by Elia Kazan", "the studio thought it was too dark and slow"],
      },
      {
        id: "gdf_600_03",
        categoryId: "mv_godfather",
        tier: 600,
        prompt: "The horse head scene — where a movie producer wakes up with a severed horse head in his bed — used a real horse head. Where did they get it?",
        answer: "From a dog food factory near the set. Coppola used a real horse head because a prop version looked too fake. The actor John Marley's scream of horror was partially genuine.",
        acceptableAnswers: ["a real horse head from a dog food factory", "a real horse head, the actor's reaction was partly real"],
      },
    ],
  },
  {
    id: "mu_bjork",
    group: "Music",
    name: "Björk",
    culture: "universal",
    description: "The Icelandic avant-garde artist who transcended every genre — from post-punk beginnings to electronic opera, VR albums, and a career of relentless innovation.",
    imageUrl: "",
    questions: [
      {
        id: "bjk_200_01",
        categoryId: "mu_bjork",
        tier: 200,
        prompt: "What country is Björk from?",
        answer: "Iceland",
        acceptableAnswers: [],
      },
      {
        id: "bjk_200_02",
        categoryId: "mu_bjork",
        tier: 200,
        prompt: "What was the name of Björk's alternative rock band before she went solo, known for songs like 'Birthday' and 'Hit'?",
        answer: "The Sugarcubes",
        acceptableAnswers: ["Sugarcubes"],
      },
      {
        id: "bjk_200_03",
        categoryId: "mu_bjork",
        tier: 200,
        prompt: "Which Björk music video features her as an android being assembled, set to a song about a love so powerful it could detonate a bomb?",
        answer: "All Is Full of Love",
        acceptableAnswers: [],
      },
      {
        id: "bjk_400_01",
        categoryId: "mu_bjork",
        tier: 400,
        prompt: "Björk's album 'Biophilia' (2011) was groundbreaking for a reason beyond music. What technology did it pioneer?",
        answer: "It was the first album released as a series of interactive apps — each song had its own iPad app combining music, education, and interactive visuals",
        acceptableAnswers: ["interactive iPad apps", "first album as apps", "each song was an interactive app"],
        explanation: "Biophilia explored the intersection of music, nature, and technology. It was inducted into the Museum of Modern Art's permanent collection.",
      },
      {
        id: "bjk_400_02",
        categoryId: "mu_bjork",
        tier: 400,
        prompt: "Björk starred in a Lars von Trier film that won the Palme d'Or at Cannes. What was the film, and what happened between Björk and von Trier during production?",
        answer: "Dancer in the Dark (2000). The production was extremely difficult — Björk and von Trier clashed severely, and she has said the experience was traumatic. She reportedly tried to eat her costume out of frustration.",
        acceptableAnswers: ["Dancer in the Dark, they had a terrible relationship on set", "Dancer in the Dark"],
      },
      {
        id: "bjk_400_03",
        categoryId: "mu_bjork",
        tier: 400,
        prompt: "Björk's 'Homogenic' album cover and the album's sound were inspired by a specific natural feature of her homeland. What was it?",
        answer: "Iceland's volcanic landscape — the album blends electronic beats with sweeping strings to evoke the collision of fire and ice, tradition and technology",
        acceptableAnswers: ["Icelandic volcanoes", "Iceland's volcanic landscape"],
      },
      {
        id: "bjk_600_01",
        categoryId: "mu_bjork",
        tier: 600,
        prompt: "Björk released her first album at what age, and in what language — long before international fame?",
        answer: "She released a self-titled album at age 11 in Icelandic, which went platinum in Iceland. It included covers of popular songs and one original composition.",
        acceptableAnswers: ["11 years old, in Icelandic", "age 11"],
      },
      {
        id: "bjk_600_02",
        categoryId: "mu_bjork",
        tier: 600,
        prompt: "In 1996, a disturbed fan named Ricardo López created an acid bomb intended to kill Björk. What happened, and how was the plot discovered?",
        answer: "López mailed the bomb to Björk's London home and then killed himself on camera. Police found his video diary before the package was delivered and intercepted it. His obsessive video diaries documented months of planning.",
        acceptableAnswers: ["a fan mailed a bomb and killed himself, police intercepted it", "Ricardo Lopez sent an acid bomb but police stopped it"],
      },
      {
        id: "bjk_600_03",
        categoryId: "mu_bjork",
        tier: 600,
        prompt: "Björk's 'Vulnicura' (2015) is considered one of the greatest breakup albums ever made. The album documents her separation from which longtime partner, and what mathematical structure does the album follow?",
        answer: "Her breakup with artist Matthew Barney. The album is structured symmetrically around the moment of the breakup — songs count down months before it, hit the moment of rupture, then count months of aftermath.",
        acceptableAnswers: ["Matthew Barney, structured symmetrically around the breakup", "Barney, songs are arranged by time before and after the split"],
      },
    ],
  },
  {
    id: "mu_radiohead_deep",
    group: "Music",
    name: "Radiohead Deep Cuts",
    culture: "universal",
    description: "Beyond OK Computer and Kid A — deep knowledge of Radiohead's artistic evolution, recording secrets, political activism, and boundary-pushing experiments.",
    imageUrl: "",
    questions: [
      {
        id: "rhd_200_01",
        categoryId: "mu_radiohead_deep",
        tier: 200,
        prompt: "What Radiohead album, released in 1997, is often cited as one of the greatest albums of all time and features songs like 'Paranoid Android' and 'Karma Police'?",
        answer: "OK Computer",
        acceptableAnswers: [],
      },
      {
        id: "rhd_200_02",
        categoryId: "mu_radiohead_deep",
        tier: 200,
        prompt: "Who is Radiohead's lead singer?",
        answer: "Thom Yorke",
        acceptableAnswers: ["Yorke"],
      },
      {
        id: "rhd_200_03",
        categoryId: "mu_radiohead_deep",
        tier: 200,
        prompt: "What was Radiohead's breakthrough hit from 1992 that the band later grew to resent?",
        answer: "Creep",
        acceptableAnswers: [],
      },
      {
        id: "rhd_400_01",
        categoryId: "mu_radiohead_deep",
        tier: 400,
        prompt: "Kid A (2000) was a radical departure from guitar rock. The band was influenced by electronic music. Which specific genres and artists most influenced the album?",
        answer: "Warp Records artists (Aphex Twin, Autechre), Krautrock (Can), jazz (Charles Mingus), and Olivier Messiaen's classical compositions",
        acceptableAnswers: ["electronic music, Aphex Twin, Autechre", "Warp Records artists and Krautrock"],
      },
      {
        id: "rhd_400_02",
        categoryId: "mu_radiohead_deep",
        tier: 400,
        prompt: "In 2007, Radiohead released 'In Rainbows' using a revolutionary distribution model. What was it?",
        answer: "They offered the album as a pay-what-you-want digital download, with no minimum price — fans could pay anything including nothing",
        acceptableAnswers: ["pay what you want", "name your price download", "pay what you want download"],
        explanation: "Despite many people paying nothing, the album was commercially successful. The average payment was estimated at several dollars, and physical sales were strong.",
      },
      {
        id: "rhd_400_03",
        categoryId: "mu_radiohead_deep",
        tier: 400,
        prompt: "Radiohead's guitarist Jonny Greenwood has become a celebrated film composer. Which Paul Thomas Anderson film earned him his first Oscar nomination?",
        answer: "There Will Be Blood",
        acceptableAnswers: [],
        explanation: "Greenwood scored multiple PTA films including Phantom Thread, The Master, and The Power of the Dog. He was also nominated for Spencer and eventually won acclaim as one of cinema's finest modern composers.",
      },
      {
        id: "rhd_600_01",
        categoryId: "mu_radiohead_deep",
        tier: 600,
        prompt: "During the OK Computer sessions, the band recorded in a specific unusual location that influenced the album's cold, alienated sound. Where was it?",
        answer: "St Catherine's Court, a haunted 15th-century manor house near Bath owned by actress Jane Seymour — the band set up in the ballroom and various rooms of the mansion",
        acceptableAnswers: ["a mansion near Bath", "Jane Seymour's mansion", "St Catherine's Court"],
        explanation: "The cavernous rooms created natural reverb that defined the album's sound. The band reportedly experienced strange occurrences and found the atmosphere both inspiring and unsettling.",
      },
      {
        id: "rhd_600_02",
        categoryId: "mu_radiohead_deep",
        tier: 600,
        prompt: "The track 'Everything in Its Right Place' (opening Kid A) was created using a specific unconventional technique with Thom Yorke's voice. What was it?",
        answer: "Yorke's vocals were chopped into fragments, loaded into a sampler, and replayed as a keyboard instrument — the stuttering, glitchy vocal sounds are his voice being 'played' like a synthesizer",
        acceptableAnswers: ["his voice was sampled and played on a keyboard", "vocal samples played as an instrument"],
      },
      {
        id: "rhd_600_03",
        categoryId: "mu_radiohead_deep",
        tier: 600,
        prompt: "Radiohead's 2016 album 'A Moon Shaped Pool' features a reworked version of a song the band had been playing live for over 20 years. What song, and what personal event made its lyrics newly devastating?",
        answer: "'True Love Waits' — first performed live in 1995 but never studio-recorded. Its lyrics about 'don't leave' gained devastating new context after Thom Yorke's separation from his partner Rachel Owen (who later died in 2016).",
        acceptableAnswers: ["True Love Waits, his breakup/partner's death", "True Love Waits, recorded after his separation"],
      },
    ],
  },
  {
    id: "vg_outer_wilds_deep",
    group: "Video Games",
    name: "Outer Wilds Deep Cuts",
    culture: "universal",
    description: "Mobius Digital's time-loop space exploration masterpiece — a game about curiosity, mortality, and the joy of discovery in a hand-crafted solar system.",
    imageUrl: "",
    questions: [
      {
        id: "owd_200_01",
        categoryId: "vg_outer_wilds_deep",
        tier: 200,
        prompt: "What happens every 22 minutes in Outer Wilds that resets the game?",
        answer: "The sun goes supernova and destroys the solar system, sending you back to the start of the loop",
        acceptableAnswers: ["the sun explodes", "the sun goes supernova", "the solar system is destroyed"],
      },
      {
        id: "owd_200_02",
        categoryId: "vg_outer_wilds_deep",
        tier: 200,
        prompt: "What alien civilization's ruins do you explore throughout Outer Wilds?",
        answer: "The Nomai",
        acceptableAnswers: [],
      },
      {
        id: "owd_200_03",
        categoryId: "vg_outer_wilds_deep",
        tier: 200,
        prompt: "What species is the player character in Outer Wilds?",
        answer: "Hearthian (a four-eyed alien species from the planet Timber Hearth)",
        acceptableAnswers: ["Hearthian"],
      },
      {
        id: "owd_400_01",
        categoryId: "vg_outer_wilds_deep",
        tier: 400,
        prompt: "The planet Brittle Hollow has a unique and terrifying geological feature. What happens to it over the course of each loop?",
        answer: "Its surface is constantly breaking apart and falling into the black hole at its center, eventually leaving the planet as an empty shell around a singularity",
        acceptableAnswers: ["it collapses into its own black hole", "the surface falls into the black hole inside it"],
      },
      {
        id: "owd_400_02",
        categoryId: "vg_outer_wilds_deep",
        tier: 400,
        prompt: "What is unique about Outer Wilds' progression system — what does the player actually 'collect' that carries over between loops?",
        answer: "Only knowledge. There are no upgrades, items, or abilities that persist — the only thing that changes is what the player knows. The game is 'completed' entirely through understanding.",
        acceptableAnswers: ["only knowledge carries over", "just information, no upgrades", "knowledge is the only progression"],
      },
      {
        id: "owd_400_03",
        categoryId: "vg_outer_wilds_deep",
        tier: 400,
        prompt: "Dark Bramble is one of the game's most terrifying locations. What makes it so dangerous?",
        answer: "It contains anglerfish that will instantly kill you if they hear your ship's thrust — you must drift through silently with engines off to survive",
        acceptableAnswers: ["anglerfish that detect sound", "giant anglerfish you must sneak past silently"],
      },
      {
        id: "owd_600_01",
        categoryId: "vg_outer_wilds_deep",
        tier: 600,
        prompt: "The Eye of the Universe is the game's ultimate destination. What is it, and what philosophical theme does the ending convey?",
        answer: "The Eye is a quantum object older than the universe itself that can collapse possibility into reality. The ending shows the creation of a new universe after yours dies — conveying that endings are natural and beautiful, and that curiosity and connection give existence meaning.",
        acceptableAnswers: ["a quantum object that creates a new universe, the theme is accepting death", "it creates a new universe, about finding meaning in finite existence"],
      },
      {
        id: "owd_600_02",
        categoryId: "vg_outer_wilds_deep",
        tier: 600,
        prompt: "Outer Wilds uses quantum mechanics as an actual gameplay mechanic. What rule governs quantum objects in the game?",
        answer: "Quantum objects change state when not being observed — they move, shift, or transform whenever you look away from them, following a game-logic version of the quantum observer effect",
        acceptableAnswers: ["they change when not observed", "objects move when you're not looking at them"],
        explanation: "The Quantum Moon is the largest example — it orbits different planets depending on where you observe it from, and reaching its south pole requires understanding quantum rules.",
      },
      {
        id: "owd_600_03",
        categoryId: "vg_outer_wilds_deep",
        tier: 600,
        prompt: "The Outer Wilds DLC 'Echoes of the Eye' introduces a new mystery. What is the Stranger, and how does it change the game's tone?",
        answer: "The Stranger is a massive, cloaked alien ringworld hidden in the solar system. It shifts the game's tone to cosmic horror — featuring a dark, decaying civilization, a simulated dream world, and stealth sequences against hostile inhabitants.",
        acceptableAnswers: ["a hidden ringworld with horror elements", "a cloaked alien structure with a horror tone"],
        explanation: "Echoes of the Eye is often considered scarier than most horror games. Its integration with the base game's story reveals that another civilization discovered the Eye and tried to hide it from everyone.",
      },
    ],
  },
  {
    id: "his_silk_road_deep",
    group: "History",
    name: "Silk Road Deep Cuts",
    culture: "universal",
    description: "The ancient network of trade routes connecting East and West — beyond silk and spices to the exchange of ideas, religions, diseases, and technologies that shaped the world.",
    imageUrl: "",
    questions: [
      {
        id: "srd_200_01",
        categoryId: "his_silk_road_deep",
        tier: 200,
        prompt: "The Silk Road connected China with which region of the world through overland trade routes?",
        answer: "The Mediterranean / Roman Empire (and later Europe and the Middle East)",
        acceptableAnswers: ["Europe", "Rome", "the Mediterranean", "the Roman Empire"],
      },
      {
        id: "srd_200_02",
        categoryId: "his_silk_road_deep",
        tier: 200,
        prompt: "Despite its name, the Silk Road traded far more than silk. What were some of the other major goods traded?",
        answer: "Spices, precious metals, gemstones, glassware, horses, paper, gunpowder, and tea among many others",
        acceptableAnswers: ["spices, gold, horses, paper", "many goods including spices and precious metals"],
      },
      {
        id: "srd_200_03",
        categoryId: "his_silk_road_deep",
        tier: 200,
        prompt: "Who was the famous Venetian merchant who traveled the Silk Road to China and wrote about his experiences at the court of Kublai Khan?",
        answer: "Marco Polo",
        acceptableAnswers: [],
      },
      {
        id: "srd_400_01",
        categoryId: "his_silk_road_deep",
        tier: 400,
        prompt: "The term 'Silk Road' was not used by the people who traveled it. Who coined the term, and when?",
        answer: "German geographer Ferdinand von Richthofen coined 'Seidenstraße' (Silk Road) in 1877 — the ancient traders themselves had no single name for the routes",
        acceptableAnswers: ["Ferdinand von Richthofen in 1877", "a German geographer in the 1800s"],
      },
      {
        id: "srd_400_02",
        categoryId: "his_silk_road_deep",
        tier: 400,
        prompt: "Buddhism spread from India to China primarily through the Silk Road. What city served as a crucial gateway for this transmission?",
        answer: "Dunhuang — a Silk Road oasis city whose Mogao Caves contain thousands of Buddhist paintings and manuscripts spanning a millennium",
        acceptableAnswers: ["Dunhuang", "the Dunhuang oasis"],
        explanation: "The Mogao Caves (also known as the Thousand Buddha Caves) contain 492 temples with wall paintings and sculptures spanning from the 4th to 14th centuries.",
      },
      {
        id: "srd_400_03",
        categoryId: "his_silk_road_deep",
        tier: 400,
        prompt: "The Black Death that devastated Europe in the 14th century likely traveled along Silk Road routes. How did it spread so effectively along trade networks?",
        answer: "Infected fleas on rats traveled with merchant caravans and ships. The same trade infrastructure that moved goods also moved disease — from Central Asia through the Middle East to European ports",
        acceptableAnswers: ["rats and fleas along trade routes", "disease traveled with traders and their cargo"],
      },
      {
        id: "srd_600_01",
        categoryId: "his_silk_road_deep",
        tier: 600,
        prompt: "China guarded the secret of silk production for centuries, making it one of history's longest-kept industrial secrets. How did the secret eventually reach the Byzantine Empire?",
        answer: "According to the historian Procopius, two Nestorian monks smuggled silkworm eggs out of China hidden inside hollow bamboo canes around 552 AD, bringing them to Emperor Justinian I",
        acceptableAnswers: ["monks smuggled silkworm eggs in bamboo", "hidden in walking sticks by monks"],
        explanation: "Whether the story is exactly true is debated, but silk production did reach Byzantium in the 6th century, ending China's monopoly and transforming the Mediterranean economy.",
      },
      {
        id: "srd_600_02",
        categoryId: "his_silk_road_deep",
        tier: 600,
        prompt: "The Sogdians were the dominant merchant class of the Silk Road for centuries but are largely forgotten today. Who were they?",
        answer: "An Iranian people based in Central Asia (modern Uzbekistan/Tajikistan) who controlled the overland trade for nearly a millennium. They were multilingual middlemen whose trading networks extended from China to Byzantium.",
        acceptableAnswers: ["Iranian merchants from Central Asia", "Central Asian traders who controlled Silk Road commerce"],
        explanation: "The Sogdian language was the lingua franca of the Silk Road. Their letters, discovered in a watchtower on the Great Wall, provide some of the earliest accounts of Silk Road commerce.",
      },
      {
        id: "srd_600_03",
        categoryId: "his_silk_road_deep",
        tier: 600,
        prompt: "Paper is one of the most consequential technologies transmitted along the Silk Road. How did the secret of papermaking travel from China to the Islamic world?",
        answer: "After the Battle of Talas in 751 AD, the Abbasid Caliphate captured Chinese papermakers who were among the prisoners of war. They established paper mills in Samarkand, from which the technology spread throughout the Islamic world and eventually to Europe.",
        acceptableAnswers: ["captured Chinese prisoners taught papermaking after the Battle of Talas", "Battle of Talas, captured papermakers"],
        explanation: "This technology transfer is one of history's most consequential. Islamic scholars used paper to preserve and transmit knowledge during the Golden Age, centuries before Europe adopted it.",
      },
    ],
  },
  {
    id: "sci_ocean_depths",
    group: "Science",
    name: "Ocean Depths & Marine Science",
    culture: "universal",
    description: "The last frontier on Earth — deep sea exploration, bizarre creatures of the abyss, hydrothermal vents, and the ocean science that rewrites what we thought possible.",
    imageUrl: "",
    questions: [
      {
        id: "ocd_200_01",
        categoryId: "sci_ocean_depths",
        tier: 200,
        prompt: "What is the deepest point in the Earth's oceans, located in the Mariana Trench?",
        answer: "Challenger Deep",
        acceptableAnswers: [],
      },
      {
        id: "ocd_200_02",
        categoryId: "sci_ocean_depths",
        tier: 200,
        prompt: "Approximately what percentage of the ocean floor has been mapped in high resolution?",
        answer: "About 25% (we have better maps of Mars and the Moon than our own ocean floor)",
        acceptableAnswers: ["about 20-25%", "less than 25%", "around 20%"],
      },
      {
        id: "ocd_200_03",
        categoryId: "sci_ocean_depths",
        tier: 200,
        prompt: "What do deep-sea creatures use to produce their own light in the pitch-black depths?",
        answer: "Bioluminescence",
        acceptableAnswers: [],
      },
      {
        id: "ocd_400_01",
        categoryId: "sci_ocean_depths",
        tier: 400,
        prompt: "Hydrothermal vents, discovered in 1977, shattered a fundamental assumption about life on Earth. What did they prove?",
        answer: "Life can exist without sunlight — vent ecosystems are powered by chemosynthesis (bacteria converting chemical energy from the vents), not photosynthesis",
        acceptableAnswers: ["life doesn't need sunlight", "chemosynthesis-based life", "life can survive without the sun"],
      },
      {
        id: "ocd_400_02",
        categoryId: "sci_ocean_depths",
        tier: 400,
        prompt: "The giant squid was considered a myth for centuries. When was the first footage of a living giant squid captured in its natural deep-sea habitat?",
        answer: "2012 — by a team led by Tsunemi Kubodera using a specialized submersible camera in the Pacific Ocean near Japan",
        acceptableAnswers: ["2012", "around 2012"],
        explanation: "Despite centuries of washed-up specimens and sperm whale stomach contents, no one had filmed a living giant squid in the deep ocean until a Japanese-led expedition succeeded.",
      },
      {
        id: "ocd_400_03",
        categoryId: "sci_ocean_depths",
        tier: 400,
        prompt: "What is the 'hadal zone' of the ocean?",
        answer: "The deepest ocean zone, below 6,000 meters (20,000 feet), found primarily in deep ocean trenches. It's named after Hades, the Greek god of the underworld.",
        acceptableAnswers: ["ocean below 6000 meters", "the deepest zone, in ocean trenches"],
      },
      {
        id: "ocd_600_01",
        categoryId: "sci_ocean_depths",
        tier: 600,
        prompt: "Only three people have reached the bottom of Challenger Deep. Who were the first two, and in what year?",
        answer: "Jacques Piccard (Swiss) and Don Walsh (American) reached the bottom on January 23, 1960, in the bathyscaphe Trieste. James Cameron made the third solo descent in 2012.",
        acceptableAnswers: ["Piccard and Walsh in 1960", "Jacques Piccard and Don Walsh, 1960"],
        explanation: "Victor Vescovo later made multiple dives to Challenger Deep in 2019, but Piccard and Walsh's achievement in the Trieste — essentially a pressurized steel ball suspended under a gasoline-filled float — remains one of exploration's greatest feats.",
      },
      {
        id: "ocd_600_02",
        categoryId: "sci_ocean_depths",
        tier: 600,
        prompt: "The 'bloop' was a mysterious ultra-low-frequency sound detected by NOAA hydrophones in 1997. What was it eventually determined to be?",
        answer: "An icequake — the sound of a large iceberg cracking and scraping along the ocean floor in Antarctica",
        acceptableAnswers: ["an iceberg", "ice breaking or cracking", "an icequake"],
        explanation: "The Bloop was originally mysterious because it was far louder than any known biological source. For years, it fueled speculation about undiscovered marine megafauna before NOAA matched it to ice seismology.",
      },
      {
        id: "ocd_600_03",
        categoryId: "sci_ocean_depths",
        tier: 600,
        prompt: "In 2020, scientists discovered plastic pollution had reached the deepest point of every ocean. What specific item was found at the bottom of the Mariana Trench?",
        answer: "A plastic bag was found at approximately 10,975 meters (36,000 feet) — the deepest known piece of plastic waste",
        acceptableAnswers: ["a plastic bag", "plastic bags and microplastics"],
        explanation: "The Deep-Sea Debris Database documented over 3,000 pieces of human-made debris in the deep ocean. The finding demonstrated that no place on Earth remains untouched by human pollution.",
      },
    ],
  },
  {
    id: "cul_tattoo_history",
    group: "Culture",
    name: "Tattoo History & Culture",
    culture: "universal",
    description: "The ancient and global history of tattooing — from Ötzi the Iceman to Japanese irezumi, Polynesian ta moko, and the modern tattoo renaissance.",
    imageUrl: "",
    questions: [
      {
        id: "tat_200_01",
        categoryId: "cul_tattoo_history",
        tier: 200,
        prompt: "The oldest known tattooed human is a 5,300-year-old mummified man found in the Alps. What is he commonly called?",
        answer: "Ötzi the Iceman",
        acceptableAnswers: ["Otzi", "the Iceman", "Ötzi"],
      },
      {
        id: "tat_200_02",
        categoryId: "cul_tattoo_history",
        tier: 200,
        prompt: "What is the traditional Japanese style of full-body tattooing called?",
        answer: "Irezumi",
        acceptableAnswers: ["horimono"],
      },
      {
        id: "tat_200_03",
        categoryId: "cul_tattoo_history",
        tier: 200,
        prompt: "The word 'tattoo' entered the English language from which culture's word?",
        answer: "Polynesian — from the Samoan 'tatau' (or Tahitian 'tatu'), introduced to English by Captain James Cook's voyages",
        acceptableAnswers: ["Polynesian", "Samoan", "Tahitian"],
      },
      {
        id: "tat_400_01",
        categoryId: "cul_tattoo_history",
        tier: 400,
        prompt: "Ötzi the Iceman has 61 tattoos. What is significant about their placement on his body?",
        answer: "They are located on joints and areas of physical strain (lower back, ankles, knees, wrists) — suggesting they were therapeutic, possibly an early form of acupuncture or pain treatment",
        acceptableAnswers: ["on joints and pain points", "therapeutic placement for pain relief", "on areas of strain, probably medicinal"],
      },
      {
        id: "tat_400_02",
        categoryId: "cul_tattoo_history",
        tier: 400,
        prompt: "The Māori tradition of tā moko (facial tattooing) is fundamentally different from decorative tattoos. What makes moko unique?",
        answer: "Moko patterns are unique to each individual and encode their ancestry, tribal affiliation, social rank, and personal achievements — they are essentially a visual biography and are considered taonga (sacred treasure)",
        acceptableAnswers: ["each is unique and encodes identity and genealogy", "they tell your personal history and lineage"],
      },
      {
        id: "tat_400_03",
        categoryId: "cul_tattoo_history",
        tier: 400,
        prompt: "In Japan, tattoos became associated with criminality. What historical practice created this stigma?",
        answer: "During the Edo period, criminals were tattooed as punishment (irebokuro) — marks on the forehead or arm identified them permanently. This penal practice merged in public perception with the decorative irezumi tradition.",
        acceptableAnswers: ["criminal punishment tattooing in the Edo period", "criminals were forcibly tattooed as punishment"],
      },
      {
        id: "tat_600_01",
        categoryId: "cul_tattoo_history",
        tier: 600,
        prompt: "The modern tattoo machine evolved from which famous inventor's creation, patented for a completely different purpose?",
        answer: "Thomas Edison's electric pen (patented 1876). Samuel O'Reilly modified it in 1891 to create the first electric tattoo machine by adding an ink reservoir and tube system.",
        acceptableAnswers: ["Thomas Edison's electric pen", "Edison's electric pen, modified by O'Reilly"],
      },
      {
        id: "tat_600_02",
        categoryId: "cul_tattoo_history",
        tier: 600,
        prompt: "Sailor Jerry (Norman Collins) revolutionized American traditional tattooing in Honolulu. What specific technical innovations did he introduce?",
        answer: "He was the first American to use the Japanese technique of shading with color, developed new pigment formulas (including purples that held), used single-needle outlines for finer detail, and sterilized his equipment — rare at the time",
        acceptableAnswers: ["better pigments and Japanese techniques", "incorporated Japanese shading and sterilized equipment"],
      },
      {
        id: "tat_600_03",
        categoryId: "cul_tattoo_history",
        tier: 600,
        prompt: "The Russian criminal tattoo tradition (used extensively in the Gulag system) created an elaborate visual language. What role did tattoos serve in the Russian prison system?",
        answer: "They were a codified hierarchy — specific symbols communicated rank, criminal specialty, number of convictions, and allegiance. Unauthorized tattoos (claiming unearned status) could be punished by death or forced removal.",
        acceptableAnswers: ["they encoded criminal rank and history", "a coded system showing status, crimes, and hierarchy", "communicated rank and criminal record"],
        explanation: "Danzig Baldaev, a prison guard, documented thousands of these tattoos over decades, publishing the 'Russian Criminal Tattoo Encyclopaedia' — now a major art book.",
      },
    ],
  },
  {
    id: "his_cold_war_proxy",
    group: "History",
    name: "Cold War Proxy Wars",
    culture: "universal",
    description: "The conflicts where the US and USSR fought through allies and surrogates — from Korea and Vietnam to Angola, Afghanistan, and the covert operations that shaped the modern world.",
    imageUrl: "",
    questions: [
      {
        id: "cwp_200_01",
        categoryId: "his_cold_war_proxy",
        tier: 200,
        prompt: "The Korean War (1950-1953) divided Korea along which parallel, which remains the border today?",
        answer: "The 38th parallel",
        acceptableAnswers: ["38th parallel"],
      },
      {
        id: "cwp_200_02",
        categoryId: "his_cold_war_proxy",
        tier: 200,
        prompt: "The Soviet-Afghan War (1979-1989) is often called 'the Soviet Union's Vietnam.' What happened?",
        answer: "The Soviet Union invaded Afghanistan to prop up a communist government and fought a decade-long guerrilla war against the US-backed mujahideen before withdrawing in defeat",
        acceptableAnswers: ["Soviets invaded Afghanistan and lost to the mujahideen", "a failed Soviet invasion of Afghanistan"],
      },
      {
        id: "cwp_200_03",
        categoryId: "his_cold_war_proxy",
        tier: 200,
        prompt: "What was the 'Domino Theory' that drove US involvement in multiple Cold War conflicts?",
        answer: "The belief that if one country fell to communism, neighboring countries would follow like dominoes — justifying intervention to stop the 'spread' of communism",
        acceptableAnswers: ["if one country became communist, others would follow", "countries falling to communism would cause neighbors to fall too"],
      },
      {
        id: "cwp_400_01",
        categoryId: "his_cold_war_proxy",
        tier: 400,
        prompt: "The CIA-backed coup in Iran in 1953 (Operation Ajax) overthrew which democratically elected leader, and what were the long-term consequences?",
        answer: "Mohammad Mosaddegh was overthrown for nationalizing Iranian oil. The Shah was reinstalled, leading to 26 years of authoritarian rule and eventually the 1979 Islamic Revolution — the consequences still shape Middle Eastern politics today.",
        acceptableAnswers: ["Mosaddegh, led to the Shah's dictatorship and eventually the Islamic Revolution", "Mohammad Mosaddegh was overthrown"],
      },
      {
        id: "cwp_400_02",
        categoryId: "his_cold_war_proxy",
        tier: 400,
        prompt: "During the Soviet-Afghan War, the US provided the mujahideen with a specific weapon system that proved decisive. What was it?",
        answer: "FIM-92 Stinger missiles — shoulder-fired anti-aircraft missiles that neutralized Soviet helicopter superiority and changed the course of the war",
        acceptableAnswers: ["Stinger missiles", "Stinger anti-aircraft missiles"],
      },
      {
        id: "cwp_400_03",
        categoryId: "his_cold_war_proxy",
        tier: 400,
        prompt: "The Angolan Civil War (1975-2002) featured an unusual alignment of Cold War proxies. What made it particularly complex?",
        answer: "Cuban troops fought alongside the Soviet-backed MPLA government, while the US and apartheid South Africa backed UNITA rebels — creating a rare case where the US allied with apartheid South Africa against Cuban forces",
        acceptableAnswers: ["Cuba fought for the government, US and South Africa backed rebels", "the US was allied with apartheid South Africa"],
      },
      {
        id: "cwp_600_01",
        categoryId: "his_cold_war_proxy",
        tier: 600,
        prompt: "Operation Cyclone was the CIA's covert program to arm the Afghan mujahideen. It became the agency's longest and most expensive covert operation. What was its approximate cost, and what controversial long-term consequence did it produce?",
        answer: "Approximately $630 million per year at peak (matched by Saudi Arabia). The weapons and training provided to mujahideen fighters later contributed to the rise of the Taliban and al-Qaeda — blowback that led to 9/11.",
        acceptableAnswers: ["over $600 million/year, contributed to the rise of al-Qaeda and Taliban", "billions total, blowback leading to terrorism"],
      },
      {
        id: "cwp_600_02",
        categoryId: "his_cold_war_proxy",
        tier: 600,
        prompt: "The Battle of Cuito Cuanavale (1987-1988) in Angola is considered one of the largest battles in Africa since World War II. Why is it historically significant beyond the military outcome?",
        answer: "The battle, where Cuban and Angolan forces repelled a South African-UNITA offensive, is credited with helping end apartheid — the South African military's inability to achieve victory undermined the apartheid regime's credibility and contributed to negotiations for Namibian independence and South African political reform",
        acceptableAnswers: ["it helped end apartheid", "South Africa's failure there weakened the apartheid regime"],
        explanation: "Nelson Mandela called Cuba's role in Angola 'a turning point for the liberation of our continent.' Fidel Castro considered it one of Cuba's proudest military achievements.",
      },
      {
        id: "cwp_600_03",
        categoryId: "his_cold_war_proxy",
        tier: 600,
        prompt: "Operation Condor was a covert Cold War intelligence operation in South America. What was it, and which countries participated?",
        answer: "A US-backed campaign of political repression and state terror coordinated between the military dictatorships of Argentina, Chile, Uruguay, Paraguay, Bolivia, and Brazil in the 1970s-80s. They shared intelligence to track and assassinate political dissidents across borders.",
        acceptableAnswers: ["coordinated repression by South American dictatorships backed by the US", "a US-supported campaign of state terror by Latin American dictatorships"],
        explanation: "Operation Condor is estimated to have resulted in 60,000-80,000 deaths. CIA involvement was confirmed through declassified documents released in the 1990s and 2000s.",
      },
    ],
  },
"""

def main():
    with open(CATEGORIES_PATH, 'r', encoding='utf-8') as f:
        content = f.read()

    old_ending = "\n];\n\nexport default CATEGORIES;\n"
    new_ending = NEW_CATEGORIES + "\n];\n\nexport default CATEGORIES;\n"

    if old_ending not in content:
        print("ERROR: Could not find expected file ending.")
        print(f"Last 200 chars: {repr(content[-200:])}")
        sys.exit(1)

    count = content.count(old_ending)
    if count != 1:
        print(f"ERROR: Found {count} occurrences of the ending pattern. Expected exactly 1.")
        sys.exit(1)

    new_content = content.replace(old_ending, new_ending)

    with open(CATEGORIES_PATH, 'w', encoding='utf-8') as f:
        f.write(new_content)

    print("SUCCESS: Wave 66 categories inserted.")
    print(f"File size: {len(new_content)} characters")

if __name__ == "__main__":
    main()
