import fs from 'node:fs';
// Produces a markdown inventory of categories that don't yet meet the board's minimum
// content bar (6 questions total, ≥2 per tier), so the content gap can be worked
// deliberately instead of papered over with invented trivia. Read-only — writes only
// the report file, never touches constants/categories.ts.

const src = fs.readFileSync(new URL('../constants/categories.ts', import.meta.url), 'utf8')
  .replace(/^import[^\n]*\n/m, '').replace(/const CATEGORIES:\s*Category\[\]\s*=/, 'const CATEGORIES =')
  .replace(/export default CATEGORIES;?\s*$/m, '');
const CATEGORIES = new Function(src + '\nreturn CATEGORIES;')();

const TIERS = [200, 400, 600];
const rows = [];
for (const c of CATEGORIES) {
  const tierCount = { 200: 0, 400: 0, 600: 0 };
  for (const q of c.questions || []) if (TIERS.includes(q.tier)) tierCount[q.tier]++;
  const total = (c.questions || []).length;
  const tierGap = TIERS.reduce((sum, t) => sum + Math.max(0, 2 - tierCount[t]), 0);
  if (total < 6 || tierGap > 0) {
    rows.push({
      id: c.id, name: c.name, group: c.group || '—', culture: c.culture,
      total, needed: Math.max(0, 6 - total),
      tierCount, tierGap,
    });
  }
}

rows.sort((a, b) => a.total - b.total || a.id.localeCompare(b.id));

const zero = rows.filter(r => r.total === 0);
const byGroup = new Map();
for (const r of rows) { const g = r.group; if (!byGroup.has(g)) byGroup.set(g, []); byGroup.get(g).push(r); }

const lines = [];
lines.push('# Content gap inventory: under-filled categories');
lines.push('');
lines.push(`Generated by \`scripts/thin_category_inventory.mjs\` from \`constants/categories.ts\`.`);
lines.push('');
lines.push(`The board needs 6 questions per category (2 per tier: 200/400/600) to deal a full`);
lines.push(`tile set. **${rows.length} of ${CATEGORIES.length} categories** currently fall short —`);
lines.push(`either under 6 questions total, or with a tier holding fewer than 2. No questions were`);
lines.push(`fabricated to close these gaps; this is a work list for deliberate content authoring.`);
lines.push('');
lines.push(`- **${zero.length} categories have zero questions**: ${zero.map(r => `\`${r.id}\``).join(', ') || '(none)'}`);
lines.push(`- **${rows.length - zero.length} categories are partially filled** (have some questions, but not enough per-tier or in total)`);
lines.push(`- Total additional questions needed to bring every category to ≥6: **${rows.reduce((s, r) => s + r.needed, 0)}** (a floor — doesn't count tier-balance-only gaps where the total is already ≥6 but one tier is thin)`);
lines.push('');
lines.push('## By category, grouped by app section');
lines.push('');
lines.push('Sorted fewest-questions-first within each group. "Tier gap" = additional questions needed in that tier to reach 2.');
lines.push('');

for (const [group, list] of [...byGroup.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  lines.push(`### ${group} (${list.length} categories)`);
  lines.push('');
  lines.push('| id | name | culture | total | need (to 6) | 200 | 400 | 600 |');
  lines.push('|---|---|---|---|---|---|---|---|');
  for (const r of list) {
    const cell = (t) => r.tierCount[t] < 2 ? `**${r.tierCount[t]}**` : `${r.tierCount[t]}`;
    lines.push(`| \`${r.id}\` | ${r.name} | ${r.culture} | ${r.total} | ${r.needed} | ${cell(200)} | ${cell(400)} | ${cell(600)} |`);
  }
  lines.push('');
}

lines.push('## Summary by culture');
lines.push('');
const byCulture = new Map();
for (const r of rows) byCulture.set(r.culture, (byCulture.get(r.culture) || 0) + 1);
lines.push('| culture | thin categories |');
lines.push('|---|---|');
for (const [culture, n] of [...byCulture.entries()].sort((a, b) => b[1] - a[1])) lines.push(`| ${culture} | ${n} |`);
lines.push('');

const outPath = new URL('../CONTENT_GAPS.md', import.meta.url);
fs.writeFileSync(outPath, lines.join('\n'));
console.log(`categories short of the 6-question / 2-per-tier bar: ${rows.length} (of ${CATEGORIES.length})`);
console.log(`  zero-question categories: ${zero.length}`);
console.log(`  additional questions needed to reach 6 everywhere (floor): ${rows.reduce((s, r) => s + r.needed, 0)}`);
console.log('report: CONTENT_GAPS.md');
