kind = "mobile"
previewPath = "/"
title = "Renegade"
version = "1.0.0"
id = "artifacts/renegade"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19623

[services.development]
run = "pnpm --filter @workspace/renegade run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/renegade", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/renegade", "run", "serve" ]

[services.env]
PORT = "19623"
BASE_PATH = "/"
