import { Question } from "@/types/game";

// Draft-only internal topic packs for History categories.
// Covers Ancient History, Medieval History, and Modern History at all three tiers.
// Do not import this file into shipping category data until reviewed/playtested.

export interface HistoryTopicPack {
    topicId: string;
    displayName: string;
    parentCategoryId: "history";
    questions: Question[];
}

const HISTORY_TOPIC_PACKS_DRAFT: HistoryTopicPack[] = [
  {
        topicId: "ancient_history",
        displayName: "Ancient History",
        parentCategoryId: "history",
        questions: [
          {
                    id: "anc_200_01",
                    categoryId: "history",
                    tier: 200,
                    prompt: "What ancient civilization built the Great Pyramid of Giza?",
                    answer: "Egypt",
                    acceptableAnswers: ["Egypt", "Ancient Egypt", "Egyptians"],
                              explanation: "The Great Pyramid was built around 2560 BCE during the reign of Pharaoh Khufu.",
          },
          {
                    id: "anc_200_02",
                    categoryId: "history",
                    tier: 200,
                    prompt: "Which empire was ruled by Julius Caesar?",
                    answer: "Roman Empire",
                    acceptableAnswers: ["Roman Empire", "Rome", "Romans"],
                              explanation: "Caesar was dictator of Rome until his assassination on the Ides of March, 44 BCE.",
          },
          {
                    id: "anc_200_03",
                    categoryId: "history",
                    tier: 200,
                    prompt: "What ancient Greek city-state was known for its powerful navy and democratic government?",
                    answer: "Athens",
                    acceptableAnswers: ["Athens"],
                              explanation: "Athens developed the world's first known democracy in the 5th century BCE.",
          },
          {
                    id: "anc_400_01",
                    categoryId: "history",
                    tier: 400,
                    prompt: "What was the name of the writing system used in ancient Mesopotamia, consisting of wedge-shaped marks?",
                    answer: "Cuneiform",
                    acceptableAnswers: ["Cuneiform"],
                              explanation: "Cuneiform was developed by the Sumerians around 3400 BCE and is one of the earliest writing systems.",
          },
          {
                    id: "anc_400_02",
                    categoryId: "history",
                    tier: 400,
                    prompt: "Which Carthaginian general crossed the Alps with war elephants to invade Italy?",
                    answer: "Hannibal",
                    acceptableAnswers: ["Hannibal", "Hannibal Barca"],
                              explanation: "Hannibal's crossing of the Alps in 218 BCE is considered one of the greatest military feats in history.",
          },
          {
                    id: "anc_400_03",
                    categoryId: "history",
                    tier: 400,
                    prompt: "What Persian king launched the first invasion of Greece in 490 BCE?",
                    answer: "Darius I",
                    acceptableAnswers: ["Darius I", "Darius the Great", "Darius"],
                              explanation: "Darius I's invasion led to the famous Battle of Marathon, where the Athenians achieved a decisive victory.",
          },
          {
                    id: "anc_600_01",
                    categoryId: "history",
                    tier: 600,
                    prompt: "What was the name of the legal code established by the Babylonian king Hammurabi, one of the earliest known written legal codes?",
                    answer: "Code of Hammurabi",
                    acceptableAnswers: ["Code of Hammurabi", "Hammurabi's Code"],
                              explanation: "Dating to about 1754 BCE, it contained 282 laws covering everything from property rights to trade.",
          },
          {
                    id: "anc_600_02",
                    categoryId: "history",
                    tier: 600,
                    prompt: "Which ancient city, located in modern-day Jordan, was the capital of the Nabataean Kingdom and is famous for its rock-cut architecture?",
                    answer: "Petra",
                    acceptableAnswers: ["Petra"],
                              explanation: "Petra thrived as a trading hub from the 4th century BCE to the 2nd century CE.",
          },
          {
                    id: "anc_600_03",
                    categoryId: "history",
                    tier: 600,
                    prompt: "What was the name of the Athenian statesman who reformed the constitution in 508 BCE, establishing the foundations of Athenian democracy?",
                    answer: "Cleisthenes",
                    acceptableAnswers: ["Cleisthenes", "Kleisthenes"],
                              explanation: "Cleisthenes is often called the 'father of Athenian democracy' for reorganizing citizens into ten tribes.",
          },
              ],
  },
  {
        topicId: "medieval_history",
        displayName: "Medieval History",
        parentCategoryId: "history",
        questions: [
          {
                    id: "med_200_01",
                    categoryId: "history",
                    tier: 200,
                    prompt: "What document did King John of England sign in 1215, limiting royal power?",
                    answer: "Magna Carta",
                    acceptableAnswers: ["Magna Carta", "The Magna Carta"],
                              explanation: "The Magna Carta established the principle that everyone, including the king, was subject to the law.",
          },
          {
                    id: "med_200_02",
                    categoryId: "history",
                    tier: 200,
                    prompt: "What devastating plague killed roughly one-third of Europe's population in the 14th century?",
                    answer: "The Black Death",
                    acceptableAnswers: ["Black Death", "The Black Death", "Bubonic Plague", "Black Plague"],
                              explanation: "The Black Death peaked in Europe between 1347 and 1351, killing an estimated 25-30 million people.",
          },
          {
                    id: "med_200_03",
                    categoryId: "history",
                    tier: 200,
                    prompt: "Which French peasant girl led armies during the Hundred Years' War and was later canonized as a saint?",
                    answer: "Joan of Arc",
                    acceptableAnswers: ["Joan of Arc", "Jeanne d'Arc"],
                              explanation: "Joan of Arc led the French army to several victories before being captured and burned at the stake in 1431.",
          },
          {
                    id: "med_400_01",
                    categoryId: "history",
                    tier: 400,
                    prompt: "What was the name of the medieval code of conduct for knights that emphasized honor, bravery, and service?",
                    answer: "Chivalry",
                    acceptableAnswers: ["Chivalry", "Code of Chivalry"],
                              explanation: "Chivalry evolved from the 11th to 13th centuries and shaped ideals of knighthood across Western Europe.",
          },
          {
                    id: "med_400_02",
                    categoryId: "history",
                    tier: 400,
                    prompt: "Which Holy Roman Emperor called the Diet of Worms in 1521 to address Martin Luther's teachings?",
                    answer: "Charles V",
                    acceptableAnswers: ["Charles V", "Charles the Fifth", "Emperor Charles V"],
                              explanation: "At the Diet of Worms, Luther refused to recant his writings, leading to his excommunication.",
          },
          {
                    id: "med_400_03",
                    categoryId: "history",
                    tier: 400,
                    prompt: "What was the name of the Viking explorer who is credited with establishing the first Norse settlement in Greenland?",
                    answer: "Erik the Red",
                    acceptableAnswers: ["Erik the Red", "Eric the Red", "Eirikr Thorvaldsson"],
                              explanation: "Erik the Red founded the first Norse settlement in Greenland around 985 CE after being exiled from Iceland.",
          },
          {
                    id: "med_600_01",
                    categoryId: "history",
                    tier: 600,
                    prompt: "What was the name of the 1054 event that permanently split Christianity into the Roman Catholic and Eastern Orthodox churches?",
                    answer: "The Great Schism",
                    acceptableAnswers: ["Great Schism", "The Great Schism", "East-West Schism"],
                              explanation: "The schism resulted from centuries of theological, political, and cultural differences between Rome and Constantinople.",
          },
          {
                    id: "med_600_02",
                    categoryId: "history",
                    tier: 600,
                    prompt: "Which Byzantine emperor codified Roman law into the Corpus Juris Civilis, forming the basis of civil law in many modern countries?",
                    answer: "Justinian I",
                    acceptableAnswers: ["Justinian I", "Justinian", "Justinian the Great"],
                              explanation: "The Corpus Juris Civilis, compiled between 529-534 CE, remains one of the most influential legal documents in history.",
          },
          {
                    id: "med_600_03",
                    categoryId: "history",
                    tier: 600,
                    prompt: "What was the name of the medieval Islamic center of learning in Baghdad that translated and preserved Greek philosophical texts?",
                    answer: "House of Wisdom",
                    acceptableAnswers: ["House of Wisdom", "Bayt al-Hikma"],
                              explanation: "Founded during the Abbasid Caliphate in the 8th century, it was a major intellectual center until the Mongol siege of 1258.",
          },
              ],
  },
  {
        topicId: "modern_history",
        displayName: "Modern History",
        parentCategoryId: "history",
        questions: [
          {
                    id: "mod_200_01",
                    categoryId: "history",
                    tier: 200,
                    prompt: "What event triggered the start of World War I in 1914?",
                    answer: "Assassination of Archduke Franz Ferdinand",
                    acceptableAnswers: ["Assassination of Archduke Franz Ferdinand", "Franz Ferdinand assassination", "Assassination of Franz Ferdinand"],
                              explanation: "Gavrilo Princip assassinated Archduke Franz Ferdinand of Austria-Hungary in Sarajevo on June 28, 1914.",
          },
          {
                    id: "mod_200_02",
                    categoryId: "history",
                    tier: 200,
                    prompt: "What year did the Berlin Wall fall?",
                    answer: "1989",
                    acceptableAnswers: ["1989"],
                              explanation: "The Berlin Wall fell on November 9, 1989, symbolizing the end of the Cold War era.",
          },
          {
                    id: "mod_200_03",
                    categoryId: "history",
                    tier: 200,
                    prompt: "Which country was the first to put a human in space?",
                    answer: "Soviet Union",
                    acceptableAnswers: ["Soviet Union", "USSR", "Russia"],
                              explanation: "Yuri Gagarin became the first human in space on April 12, 1961, aboard Vostok 1.",
          },
          {
                    id: "mod_400_01",
                    categoryId: "history",
                    tier: 400,
                    prompt: "What treaty ended World War I and imposed heavy reparations on Germany?",
                    answer: "Treaty of Versailles",
                    acceptableAnswers: ["Treaty of Versailles", "Versailles Treaty"],
                              explanation: "Signed on June 28, 1919, its harsh terms are widely seen as contributing to the rise of Nazi Germany.",
          },
          {
                    id: "mod_400_02",
                    categoryId: "history",
                    tier: 400,
                    prompt: "What was the name of the US policy aimed at preventing the spread of communism during the Cold War?",
                    answer: "Containment",
                    acceptableAnswers: ["Containment", "Containment policy", "Truman Doctrine"],
                              explanation: "First articulated by George Kennan in 1947, containment shaped US foreign policy for decades.",
          },
          {
                    id: "mod_400_03",
                    categoryId: "history",
                    tier: 400,
                    prompt: "What was the codename for the Allied invasion of Normandy on June 6, 1944?",
                    answer: "Operation Overlord",
                    acceptableAnswers: ["Operation Overlord", "D-Day", "Overlord"],
                              explanation: "Operation Overlord was the largest seaborne invasion in history, involving over 156,000 troops.",
          },
          {
                    id: "mod_600_01",
                    categoryId: "history",
                    tier: 600,
                    prompt: "What 1955 conference of Asian and African nations in Indonesia promoted decolonization and non-alignment?",
                    answer: "Bandung Conference",
                    acceptableAnswers: ["Bandung Conference", "Asian-African Conference"],
                              explanation: "The Bandung Conference brought together 29 nations and laid the groundwork for the Non-Aligned Movement.",
          },
          {
                    id: "mod_600_02",
                    categoryId: "history",
                    tier: 600,
                    prompt: "What was the name of the Soviet policy of political openness introduced by Mikhail Gorbachev in the 1980s?",
                    answer: "Glasnost",
                    acceptableAnswers: ["Glasnost"],
                              explanation: "Glasnost, meaning 'openness', along with Perestroika ('restructuring'), were key reforms that preceded the fall of the Soviet Union.",
          },
          {
                    id: "mod_600_03",
                    categoryId: "history",
                    tier: 600,
                    prompt: "Which 1884-1885 conference formalized European colonization of Africa by establishing rules for territorial claims?",
                    answer: "Berlin Conference",
                    acceptableAnswers: ["Berlin Conference", "Congo Conference", "Berlin West Africa Conference"],
                              explanation: "Organized by Otto von Bismarck, the conference divided Africa among European powers with no African representation.",
          },
              ],
  },
  ];

export default HISTORY_TOPIC_PACKS_DRAFT;
