import { Question } from "@/types/game";

// Draft-only internal topic packs for Literature categories.
// Covers Classic Literature, Modern Fiction, and Poetry at all three tiers.
// Do not import this file into shipping category data until reviewed/playtested.

export interface LiteratureTopicPack {
  topicId: string;
  displayName: string;
  parentCategoryId: "literature";
  questions: Question[];
}

const LITERATURE_TOPIC_PACKS_DRAFT: LiteratureTopicPack[] = [
  {
    topicId: "classic_literature",
    displayName: "Classic Literature",
    parentCategoryId: "literature",
    questions: [
      {
        id: "classic_200_01",
        categoryId: "literature",
        tier: 200,
        prompt: "What Charles Dickens novel opens with the line 'It was the best of times, it was the worst of times'?",
        answer: "A Tale of Two Cities",
        acceptableAnswers: ["A Tale of Two Cities"],
        explanation: "Published in 1859, A Tale of Two Cities is set during the French Revolution and is one of the best-selling novels of all time.",
      },
      {
        id: "classic_200_02",
        categoryId: "literature",
        tier: 200,
        prompt: "What Mark Twain novel follows the adventures of a boy who fakes his own death and travels down the Mississippi River?",
        answer: "Adventures of Huckleberry Finn",
        acceptableAnswers: ["Adventures of Huckleberry Finn", "Huckleberry Finn", "Huck Finn"],
        explanation: "Published in 1884, Huckleberry Finn is considered one of the great American novels and a landmark of realist literature.",
      },
      {
        id: "classic_200_03",
        categoryId: "literature",
        tier: 200,
        prompt: "What Jane Austen novel features protagonist Elizabeth Bennet and Mr. Darcy?",
        answer: "Pride and Prejudice",
        acceptableAnswers: ["Pride and Prejudice"],
        explanation: "Published in 1813, Pride and Prejudice is Austen's most popular novel, opening with one of literature's most famous lines.",
      },
      {
        id: "classic_400_01",
        categoryId: "literature",
        tier: 400,
        prompt: "What Russian novelist wrote War and Peace and Anna Karenina?",
        answer: "Leo Tolstoy",
        acceptableAnswers: ["Leo Tolstoy", "Tolstoy", "Lev Tolstoy"],
        explanation: "Tolstoy (1828–1910) is widely considered one of the greatest novelists; War and Peace, at ~580,000 words, is among the longest novels ever written.",
      },
      {
        id: "classic_400_02",
        categoryId: "literature",
        tier: 400,
        prompt: "What Herman Melville novel, published in 1851, follows Captain Ahab's obsessive hunt for a white whale?",
        answer: "Moby-Dick",
        acceptableAnswers: ["Moby-Dick", "Moby Dick"],
        explanation: "Initially a commercial failure, Moby-Dick is now considered a masterpiece of American Romanticism and symbolism.",
      },
      {
        id: "classic_400_03",
        categoryId: "literature",
        tier: 400,
        prompt: "What Fyodor Dostoevsky novel explores guilt and redemption through protagonist Raskolnikov, a student who murders a pawnbroker?",
        answer: "Crime and Punishment",
        acceptableAnswers: ["Crime and Punishment"],
        explanation: "Published in 1866, Crime and Punishment is a foundational work of psychological realism, exploring morality, free will, and redemption.",
      },
      {
        id: "classic_600_01",
        categoryId: "literature",
        tier: 600,
        prompt: "What 18th-century satirical novel by Voltaire follows the naive hero Candide through a series of catastrophes, mocking Leibnizian optimism?",
        answer: "Candide",
        acceptableAnswers: ["Candide"],
        explanation: "Published in 1759, Candide was immediately banned for its satirical attacks on religion, governments, and philosophy, yet became a bestseller.",
      },
      {
        id: "classic_600_02",
        categoryId: "literature",
        tier: 600,
        prompt: "What epic poem by Dante Alighieri, written in the early 14th century, describes a journey through Hell, Purgatory, and Heaven?",
        answer: "The Divine Comedy",
        acceptableAnswers: ["The Divine Comedy", "Divine Comedy", "La Divina Commedia"],
        explanation: "The Divine Comedy (c. 1308–1320) consists of three canticles: Inferno, Purgatorio, and Paradiso, and established Tuscan as the Italian literary language.",
      },
      {
        id: "classic_600_03",
        categoryId: "literature",
        tier: 600,
        prompt: "What technique, pioneered by Virginia Woolf and James Joyce, attempts to capture the continuous flow of a character's thoughts without conventional narrative structure?",
        answer: "Stream of consciousness",
        acceptableAnswers: ["Stream of consciousness", "Stream-of-consciousness"],
        explanation: "The term was coined by William James in 1890; writers like Joyce (Ulysses) and Woolf (Mrs Dalloway) elevated it into a defining modernist technique.",
      },
    ],
  },
  {
    topicId: "modern_fiction",
    displayName: "Modern Fiction",
    parentCategoryId: "literature",
    questions: [
      {
        id: "modfic_200_01",
        categoryId: "literature",
        tier: 200,
        prompt: "What dystopian novel by George Orwell, published in 1949, features the totalitarian 'Big Brother' surveillance state?",
        answer: "Nineteen Eighty-Four",
        acceptableAnswers: ["Nineteen Eighty-Four", "1984", "Nineteen Eighty Four"],
        explanation: "Orwell wrote 1984 as a warning against totalitarianism; it coined terms like 'doublethink', 'thoughtcrime', and 'Newspeak' that entered the English language.",
      },
      {
        id: "modfic_200_02",
        categoryId: "literature",
        tier: 200,
        prompt: "What J.K. Rowling novel series begins with 'Harry Potter and the Philosopher's Stone'?",
        answer: "Harry Potter",
        acceptableAnswers: ["Harry Potter", "Harry Potter series"],
        explanation: "The seven-book series (1997–2007) has sold over 600 million copies worldwide, becoming the best-selling book series in history.",
      },
      {
        id: "modfic_200_03",
        categoryId: "literature",
        tier: 200,
        prompt: "What Cormac McCarthy novel, adapted into a 2007 film starring Javier Bardem, follows a hitman pursuing a man who stumbles upon drug money?",
        answer: "No Country for Old Men",
        acceptableAnswers: ["No Country for Old Men"],
        explanation: "Published in 2005, the novel won the Pulitzer Prize for Fiction in 2007 alongside McCarthy's The Road — both were adapted into acclaimed films.",
      },
      {
        id: "modfic_400_01",
        categoryId: "literature",
        tier: 400,
        prompt: "What Gabriel García Márquez novel, the defining work of magical realism, chronicles seven generations of the Buendía family in Macondo?",
        answer: "One Hundred Years of Solitude",
        acceptableAnswers: ["One Hundred Years of Solitude", "Cien años de soledad"],
        explanation: "Published in 1967, One Hundred Years of Solitude sold 50 million copies and earned García Márquez the Nobel Prize in Literature in 1982.",
      },
      {
        id: "modfic_400_02",
        categoryId: "literature",
        tier: 400,
        prompt: "What Toni Morrison novel, winner of the 1988 Pulitzer Prize, tells the story of escaped slave Sethe haunted by the ghost of her dead baby?",
        answer: "Beloved",
        acceptableAnswers: ["Beloved"],
        explanation: "Beloved was initially rejected by the Book-of-the-Month Club but won the Pulitzer; Morrison later won the Nobel Prize in Literature in 1993.",
      },
      {
        id: "modfic_400_03",
        categoryId: "literature",
        tier: 400,
        prompt: "What Kazuo Ishiguro novel, narrated by a butler reflecting on his career serving a morally compromised English lord, won the 1989 Booker Prize?",
        answer: "The Remains of the Day",
        acceptableAnswers: ["The Remains of the Day"],
        explanation: "Ishiguro's novel explores duty, repressed emotion, and regret through unreliable narrator Stevens; Ishiguro won the Nobel Prize in Literature in 2017.",
      },
      {
        id: "modfic_600_01",
        categoryId: "literature",
        tier: 600,
        prompt: "What David Foster Wallace novel, often called the 'most unfinishable' yet essential American novel, follows residents of a tennis academy and a halfway house?",
        answer: "Infinite Jest",
        acceptableAnswers: ["Infinite Jest"],
        explanation: "Published in 1996 at 1,079 pages (with 96 pages of footnotes), Infinite Jest satirizes entertainment addiction and American consumerism.",
      },
      {
        id: "modfic_600_02",
        categoryId: "literature",
        tier: 600,
        prompt: "What literary technique, used by Nabokov in Pale Fire, presents a novel as a poem with an obsessive, unreliable scholarly commentary?",
        answer: "Metafiction",
        acceptableAnswers: ["Metafiction", "Unreliable narrator", "Paratextual fiction"],
        explanation: "Pale Fire (1962) blurs the line between text and commentary, making the reader question who is telling the truth — a landmark of postmodern metafiction.",
      },
      {
        id: "modfic_600_03",
        categoryId: "literature",
        tier: 600,
        prompt: "What Roberto Bolaño novel, published posthumously in 2004, is structured in five parts and named after a city on the Mexico-US border where women are being murdered?",
        answer: "2666",
        acceptableAnswers: ["2666"],
        explanation: "2666, named after a fictional year of apocalypse, is set in the fictional Santa Teresa (based on Ciudad Juárez) and is widely considered Bolaño's masterpiece.",
      },
    ],
  },
  {
    topicId: "poetry",
    displayName: "Poetry",
    parentCategoryId: "literature",
    questions: [
      {
        id: "poetry_200_01",
        categoryId: "literature",
        tier: 200,
        prompt: "What American poet wrote 'I heard a Fly buzz – when I died' and 'Because I could not stop for Death'?",
        answer: "Emily Dickinson",
        acceptableAnswers: ["Emily Dickinson", "Dickinson"],
        explanation: "Dickinson (1830–1886) wrote nearly 1,800 poems but published fewer than 12 in her lifetime; most were discovered after her death.",
      },
      {
        id: "poetry_200_02",
        categoryId: "literature",
        tier: 200,
        prompt: "What Walt Whitman poetry collection, containing 'Song of Myself', was first published in 1855?",
        answer: "Leaves of Grass",
        acceptableAnswers: ["Leaves of Grass"],
        explanation: "Whitman self-published Leaves of Grass at age 36 and revised it throughout his life; it is considered a foundational American literary work.",
      },
      {
        id: "poetry_200_03",
        categoryId: "literature",
        tier: 200,
        prompt: "What poem by Robert Frost, ending with 'I took the one less traveled by, / And that has made all the difference', is often misread as advocating nonconformity?",
        answer: "The Road Not Taken",
        acceptableAnswers: ["The Road Not Taken"],
        explanation: "Frost wrote the poem as gentle mockery of his indecisive friend; both roads in the poem are described as 'really about the same', making it an ironic commentary on self-justification.",
      },
      {
        id: "poetry_400_01",
        categoryId: "literature",
        tier: 400,
        prompt: "What T.S. Eliot poem, opening 'April is the cruellest month', is considered the defining work of modernist poetry?",
        answer: "The Waste Land",
        acceptableAnswers: ["The Waste Land"],
        explanation: "Published in 1922, the same year as Joyce's Ulysses, The Waste Land is a fragmented meditation on post-WWI disillusionment, blending multiple languages and literary allusions.",
      },
      {
        id: "poetry_400_02",
        categoryId: "literature",
        tier: 400,
        prompt: "What 14-line poetic form, popularized by Shakespeare, consists of three quatrains and a closing couplet in iambic pentameter?",
        answer: "Shakespearean sonnet",
        acceptableAnswers: ["Shakespearean sonnet", "English sonnet", "sonnet"],
        explanation: "Shakespeare wrote 154 sonnets; the form follows an ABAB CDCD EFEF GG rhyme scheme, distinct from the earlier Petrarchan sonnet.",
      },
      {
        id: "poetry_400_03",
        categoryId: "literature",
        tier: 400,
        prompt: "What Beat Generation poet wrote 'Howl' (1956), whose publication led to an obscenity trial that became a landmark for free speech?",
        answer: "Allen Ginsberg",
        acceptableAnswers: ["Allen Ginsberg", "Ginsberg"],
        explanation: "City Lights Books publisher Lawrence Ferlinghetti was arrested for selling Howl; Judge Clayton Horn ruled it not obscene, vindicating the Beat movement.",
      },
      {
        id: "poetry_600_01",
        categoryId: "literature",
        tier: 600,
        prompt: "What Ancient Greek epic poem, attributed to Homer, recounts the fall of Troy through the wrath of Achilles?",
        answer: "The Iliad",
        acceptableAnswers: ["The Iliad", "Iliad"],
        explanation: "The Iliad (c. 8th century BCE) is one of the oldest works of Western literature; along with The Odyssey, it shaped the foundation of European literary tradition.",
      },
      {
        id: "poetry_600_02",
        categoryId: "literature",
        tier: 600,
        prompt: "What Sylvia Plath collection, published in 1965 two years after her death, is considered a cornerstone of confessional poetry?",
        answer: "Ariel",
        acceptableAnswers: ["Ariel"],
        explanation: "Ariel contains poems written in the last months of Plath's life, including 'Lady Lazarus' and 'Daddy', and cemented her status as a major 20th-century poet.",
      },
      {
        id: "poetry_600_03",
        categoryId: "literature",
        tier: 600,
        prompt: "What Japanese poetic form, consisting of 17 syllables in a 5-7-5 structure, was perfected by master Matsuo Bashō in the 17th century?",
        answer: "Haiku",
        acceptableAnswers: ["Haiku"],
        explanation: "Bashō elevated haiku from playful wordplay into a serious literary form; his most famous haiku — 'furuike ya / kawazu tobikomu / mizu no oto' (old pond, frog jumps, sound of water) — is iconic.",
      },
    ],
  },
];

export default LITERATURE_TOPIC_PACKS_DRAFT;
