import { Question } from "@/types/game";

// Draft-only internal topic packs for the generic "Movies" category.
// These cover both film and TV franchises for now; split later if the app adds a TV category.
// Do not import this file into shipping category data until reviewed/playtested.

export interface MoviesTvTopicPack {
  topicId: string;
  displayName: string;
  parentCategoryId: "movies";
  questions: Question[];
}

const MOVIES_TV_TOPIC_PACKS_DRAFT: MoviesTvTopicPack[] = [
  {
    topicId: "game_of_thrones",
    displayName: "Game of Thrones",
    parentCategoryId: "movies",
    questions: [
      {
        id: "got_200_01",
        categoryId: "movies",
        tier: 200,
        prompt: "Which noble family rules the North from Winterfell at the start of Game of Thrones?",
        answer: "House Stark",
        acceptableAnswers: ["Stark", "House Stark", "The Starks"],
        source: "https://www.sky.com/watch/game-of-thrones/houses",
      },
      {
        id: "got_200_02",
        categoryId: "movies",
        tier: 200,
        prompt: "What throne is the central political prize in Game of Thrones?",
        answer: "The Iron Throne",
        acceptableAnswers: ["Iron Throne", "The Iron Throne"],
        source: "https://www.hbo.com/series/genre/drama",
      },
      {
        id: "got_400_01",
        categoryId: "movies",
        tier: 400,
        prompt: "What phrase is the motto of House Stark?",
        answer: "Winter is Coming",
        acceptableAnswers: ["Winter is Coming"],
        source: "Game of Thrones / A Song of Ice and Fire house motto; verify against official HBO materials before shipping.",
      },
      {
        id: "got_400_02",
        categoryId: "movies",
        tier: 400,
        prompt: "What is the name of Arya Stark's small sword?",
        answer: "Needle",
        acceptableAnswers: ["Needle"],
        source: "Game of Thrones season/book canon; verify before shipping.",
      },
      {
        id: "got_600_01",
        categoryId: "movies",
        tier: 600,
        prompt: "What phrase must a Faceless Man hear before the response 'All men must serve'?",
        answer: "Valar morghulis",
        acceptableAnswers: ["Valar morghulis"],
        explanation: "Deep fans know the paired Braavosi phrases and the response structure.",
        source: "Game of Thrones / A Song of Ice and Fire Braavos lore; verify before shipping.",
      },
      {
        id: "got_600_02",
        categoryId: "movies",
        tier: 600,
        prompt: "What Targaryen king is known as the first Targaryen ruler of Westeros and the conqueror tied to the Iron Throne's origin?",
        answer: "Aegon the Conqueror",
        acceptableAnswers: ["Aegon I", "Aegon Targaryen", "Aegon the Conqueror"],
        source: "https://www.sky.com/watch/game-of-thrones/houses",
      },
    ],
  },
  {
    topicId: "lord_of_the_rings",
    displayName: "The Lord of the Rings",
    parentCategoryId: "movies",
    questions: [
      {
        id: "lotr_200_01",
        categoryId: "movies",
        tier: 200,
        prompt: "What hobbit is chosen to carry the One Ring toward Mordor?",
        answer: "Frodo Baggins",
        acceptableAnswers: ["Frodo", "Frodo Baggins"],
        source: "https://lotr.fandom.com/wiki/Frodo_Baggins",
      },
      {
        id: "lotr_200_02",
        categoryId: "movies",
        tier: 200,
        prompt: "What volcano is the only place where the One Ring can be destroyed?",
        answer: "Mount Doom",
        acceptableAnswers: ["Mount Doom", "Orodruin"],
        source: "https://lotr.fandom.com/wiki/Mount_Doom",
      },
      {
        id: "lotr_400_01",
        categoryId: "movies",
        tier: 400,
        prompt: "What was Gollum's original name before the Ring corrupted him?",
        answer: "Smeagol",
        acceptableAnswers: ["Smeagol", "Sméagol"],
        source: "https://lotr.fandom.com/wiki/Gollum",
      },
      {
        id: "lotr_400_02",
        categoryId: "movies",
        tier: 400,
        prompt: "What giant spider attacks Frodo near Cirith Ungol?",
        answer: "Shelob",
        acceptableAnswers: ["Shelob"],
        source: "https://lotr.fandom.com/wiki/One_Ring",
      },
      {
        id: "lotr_600_01",
        categoryId: "movies",
        tier: 600,
        prompt: "What was the name of the cousin Gollum murdered after the One Ring was found in the Gladden Fields?",
        answer: "Deagol",
        acceptableAnswers: ["Deagol", "Déagol"],
        source: "https://lotr.fandom.com/wiki/Gollum",
      },
      {
        id: "lotr_600_02",
        categoryId: "movies",
        tier: 600,
        prompt: "What chamber inside Mount Doom is also called the Cracks of Doom, where Frodo claims the Ring?",
        answer: "Sammath Naur",
        acceptableAnswers: ["Sammath Naur", "Cracks of Doom"],
        source: "https://lotr.fandom.com/wiki/Cracks_of_Doom",
      },
    ],
  },
  {
    topicId: "harry_potter",
    displayName: "Harry Potter",
    parentCategoryId: "movies",
    questions: [
      {
        id: "hp_200_01",
        categoryId: "movies",
        tier: 200,
        prompt: "What school of witchcraft and wizardry does Harry Potter attend?",
        answer: "Hogwarts",
        acceptableAnswers: ["Hogwarts", "Hogwarts School of Witchcraft and Wizardry"],
        source: "Harry Potter series premise; verify against official Wizarding World material before shipping.",
      },
      {
        id: "hp_200_02",
        categoryId: "movies",
        tier: 200,
        prompt: "What house are Harry, Ron, and Hermione sorted into?",
        answer: "Gryffindor",
        acceptableAnswers: ["Gryffindor"],
        source: "Harry Potter series canon; verify before shipping.",
      },
      {
        id: "hp_400_01",
        categoryId: "movies",
        tier: 400,
        prompt: "What three magical objects make up the Deathly Hallows?",
        answer: "Elder Wand, Resurrection Stone, and Invisibility Cloak",
        acceptableAnswers: [
          "The Elder Wand, the Resurrection Stone, and the Invisibility Cloak",
          "Elder Wand Resurrection Stone Invisibility Cloak",
        ],
        source: "https://harrypotter.fandom.com/wiki/Deathly_Hallows",
      },
      {
        id: "hp_400_02",
        categoryId: "movies",
        tier: 400,
        prompt: "What object is both a Horcrux and the hiding place of the Resurrection Stone?",
        answer: "Marvolo Gaunt's ring",
        acceptableAnswers: ["Gaunt's ring", "Marvolo Gaunt's ring", "The ring"],
        source: "https://harrypotter.fandom.com/wiki/Deathly_Hallows",
      },
      {
        id: "hp_600_01",
        categoryId: "movies",
        tier: 600,
        prompt: "What four nicknames appear on the Marauder's Map for Moony, Wormtail, Padfoot, and Prongs?",
        answer: "Lupin, Pettigrew, Sirius, and James",
        acceptableAnswers: [
          "Remus Lupin, Peter Pettigrew, Sirius Black, James Potter",
          "Lupin Pettigrew Sirius James",
        ],
        source: "Harry Potter and the Prisoner of Azkaban canon; verify before shipping.",
      },
      {
        id: "hp_600_02",
        categoryId: "movies",
        tier: 600,
        prompt: "What house-elf memory helps reveal that Voldemort stole both Hufflepuff's cup and Slytherin's locket?",
        answer: "Hokey",
        acceptableAnswers: ["Hokey", "Hokey's memory"],
        source: "Harry Potter and the Half-Blood Prince canon; verify before shipping.",
      },
    ],
  },
  {
    topicId: "star_wars",
    displayName: "Star Wars",
    parentCategoryId: "movies",
    questions: [
      {
        id: "sw_200_01",
        categoryId: "movies",
        tier: 200,
        prompt: "What weapon is famously used by Jedi and Sith?",
        answer: "Lightsaber",
        acceptableAnswers: ["Lightsaber", "Light saber"],
        source: "Star Wars franchise canon; verify against official StarWars.com before shipping.",
      },
      {
        id: "sw_200_02",
        categoryId: "movies",
        tier: 200,
        prompt: "What desert planet is Luke Skywalker's childhood home?",
        answer: "Tatooine",
        acceptableAnswers: ["Tatooine"],
        source: "Star Wars: A New Hope canon; verify before shipping.",
      },
      {
        id: "sw_400_01",
        categoryId: "movies",
        tier: 400,
        prompt: "What is the name of Han Solo's ship?",
        answer: "Millennium Falcon",
        acceptableAnswers: ["The Millennium Falcon", "Millennium Falcon"],
        source: "Star Wars original trilogy canon; verify before shipping.",
      },
      {
        id: "sw_400_02",
        categoryId: "movies",
        tier: 400,
        prompt: "What clone protocol commands troopers to execute the Jedi?",
        answer: "Order 66",
        acceptableAnswers: ["Order 66", "Execute Order 66"],
        source: "Star Wars: Revenge of the Sith canon; verify before shipping.",
      },
      {
        id: "sw_600_01",
        categoryId: "movies",
        tier: 600,
        prompt: "What Sith title does Sheev Palpatine use while secretly controlling the Republic and Separatists?",
        answer: "Darth Sidious",
        acceptableAnswers: ["Sidious", "Darth Sidious"],
        source: "Star Wars prequel trilogy canon; verify before shipping.",
      },
      {
        id: "sw_600_02",
        categoryId: "movies",
        tier: 600,
        prompt: "What bounty hunter serves as the genetic template for the Republic's clone army?",
        answer: "Jango Fett",
        acceptableAnswers: ["Jango", "Jango Fett"],
        source: "Star Wars: Attack of the Clones canon; verify before shipping.",
      },
    ],
  },
];

export default MOVIES_TV_TOPIC_PACKS_DRAFT;
