import { Question } from "@/types/game";

// Draft-only internal topic packs for Technology categories.
// Covers Programming, The Internet, and Consumer Tech at all three tiers.
// Do not import this file into shipping category data until reviewed/playtested.

export interface TechnologyTopicPack {
  topicId: string;
  displayName: string;
  parentCategoryId: "technology";
  questions: Question[];
}

const TECHNOLOGY_TOPIC_PACKS_DRAFT: TechnologyTopicPack[] = [
  {
    topicId: "programming",
    displayName: "Programming",
    parentCategoryId: "technology",
    questions: [
      {
        id: "prog_200_01",
        categoryId: "technology",
        tier: 200,
        prompt: "What programming language, created by Guido van Rossum, is named after a British comedy group?",
        answer: "Python",
        acceptableAnswers: ["Python"],
        explanation: "Python was named after Monty Python's Flying Circus. Van Rossum was reading the published scripts when he chose the name.",
      },
      {
        id: "prog_200_02",
        categoryId: "technology",
        tier: 200,
        prompt: "What does 'HTML' stand for?",
        answer: "HyperText Markup Language",
        acceptableAnswers: ["HyperText Markup Language", "Hypertext Markup Language"],
        explanation: "HTML is the standard markup language for creating web pages, first proposed by Tim Berners-Lee in 1989.",
      },
      {
        id: "prog_200_03",
        categoryId: "technology",
        tier: 200,
        prompt: "What symbol is used to declare a variable in most JavaScript code as of ES6+?",
        answer: "let or const",
        acceptableAnswers: ["let", "const", "let or const", "let/const"],
        explanation: "ES6 introduced 'let' (block-scoped mutable) and 'const' (block-scoped immutable) as modern replacements for 'var'.",
      },
      {
        id: "prog_400_01",
        categoryId: "technology",
        tier: 400,
        prompt: "What sorting algorithm, with average O(n log n) complexity, partitions an array around a pivot element?",
        answer: "Quicksort",
        acceptableAnswers: ["Quicksort", "Quick sort", "Quick Sort"],
        explanation: "Quicksort, developed by Tony Hoare in 1959, is one of the most efficient general-purpose sorting algorithms in practice.",
      },
      {
        id: "prog_400_02",
        categoryId: "technology",
        tier: 400,
        prompt: "What data structure uses LIFO (Last In, First Out) ordering, like a stack of plates?",
        answer: "Stack",
        acceptableAnswers: ["Stack", "A stack"],
        explanation: "Stacks support push (add to top) and pop (remove from top) operations, fundamental to recursion and expression evaluation.",
      },
      {
        id: "prog_400_03",
        categoryId: "technology",
        tier: 400,
        prompt: "In object-oriented programming, what principle means a class should inherit from only one concrete parent, promoting code reuse through a hierarchy?",
        answer: "Inheritance",
        acceptableAnswers: ["Inheritance", "Single inheritance"],
        explanation: "Inheritance allows classes to derive properties and methods from parent classes, a cornerstone of OOP alongside encapsulation and polymorphism.",
      },
      {
        id: "prog_600_01",
        categoryId: "technology",
        tier: 600,
        prompt: "What theorem, proven by Alan Turing in 1936, states that no algorithm can determine whether an arbitrary program will halt or run forever?",
        answer: "The Halting Problem",
        acceptableAnswers: ["The Halting Problem", "Halting Problem"],
        explanation: "Turing proved the halting problem is undecidable via a diagonalization argument, establishing fundamental limits of computation.",
      },
      {
        id: "prog_600_02",
        categoryId: "technology",
        tier: 600,
        prompt: "What design pattern ensures a class has only one instance and provides a global access point to it?",
        answer: "Singleton",
        acceptableAnswers: ["Singleton", "Singleton pattern"],
        explanation: "The Singleton pattern is one of the 23 classic Gang of Four design patterns, useful for managing shared resources like config or logging.",
      },
      {
        id: "prog_600_03",
        categoryId: "technology",
        tier: 600,
        prompt: "What Big O notation describes an algorithm whose runtime doubles with each additional input element, such as naive recursive Fibonacci?",
        answer: "O(2^n)",
        acceptableAnswers: ["O(2^n)", "O(2 to the n)", "Exponential"],
        explanation: "Exponential time algorithms become impractical quickly — for n=40 inputs, O(2^n) requires over a trillion operations.",
      },
    ],
  },
  {
    topicId: "internet",
    displayName: "The Internet",
    parentCategoryId: "technology",
    questions: [
      {
        id: "net_200_01",
        categoryId: "technology",
        tier: 200,
        prompt: "What does 'WWW' stand for in a web address?",
        answer: "World Wide Web",
        acceptableAnswers: ["World Wide Web"],
        explanation: "The World Wide Web was invented by Tim Berners-Lee in 1989 at CERN as a way to share information over the internet.",
      },
      {
        id: "net_200_02",
        categoryId: "technology",
        tier: 200,
        prompt: "What social media platform, founded in 2004 by Mark Zuckerberg, was originally called 'TheFacebook'?",
        answer: "Facebook",
        acceptableAnswers: ["Facebook", "Meta"],
        explanation: "Zuckerberg launched TheFacebook.com from his Harvard dorm room in February 2004, dropping 'The' from the name in 2005.",
      },
      {
        id: "net_200_03",
        categoryId: "technology",
        tier: 200,
        prompt: "What does 'URL' stand for?",
        answer: "Uniform Resource Locator",
        acceptableAnswers: ["Uniform Resource Locator"],
        explanation: "A URL is the complete web address of a resource, including the protocol (https://), domain, and path.",
      },
      {
        id: "net_400_01",
        categoryId: "technology",
        tier: 400,
        prompt: "What protocol, running on port 443, encrypts data between a browser and web server using TLS?",
        answer: "HTTPS",
        acceptableAnswers: ["HTTPS", "HTTPS (TLS)", "TLS/HTTPS"],
        explanation: "HTTPS (HTTP Secure) uses Transport Layer Security to encrypt traffic, indicated by the padlock icon in browsers.",
      },
      {
        id: "net_400_02",
        categoryId: "technology",
        tier: 400,
        prompt: "What 1990s technology, allowing interactive content in browsers, was famously deprecated by Apple when the iPhone launched in 2007?",
        answer: "Adobe Flash",
        acceptableAnswers: ["Adobe Flash", "Flash", "Flash Player", "Macromedia Flash"],
        explanation: "Steve Jobs refused to support Flash on the iPhone, citing security and performance issues; Adobe ended Flash support on December 31, 2020.",
      },
      {
        id: "net_400_03",
        categoryId: "technology",
        tier: 400,
        prompt: "What does 'DNS' stand for, referring to the system that translates domain names into IP addresses?",
        answer: "Domain Name System",
        acceptableAnswers: ["Domain Name System", "Domain Name Service"],
        explanation: "DNS acts as the internet's phone book, converting human-readable addresses like google.com into machine-readable IP addresses.",
      },
      {
        id: "net_600_01",
        categoryId: "technology",
        tier: 600,
        prompt: "What 1969 DARPA project, considered the precursor to the internet, successfully sent the first message between UCLA and Stanford?",
        answer: "ARPANET",
        acceptableAnswers: ["ARPANET"],
        explanation: "ARPANET sent its first message on October 29, 1969 — 'lo' (the system crashed after two letters of 'login') — connecting four university nodes.",
      },
      {
        id: "net_600_02",
        categoryId: "technology",
        tier: 600,
        prompt: "What internet routing protocol, used by ISPs to exchange routing information between autonomous systems, is considered the 'glue' of the internet?",
        answer: "BGP",
        acceptableAnswers: ["BGP", "Border Gateway Protocol"],
        explanation: "Border Gateway Protocol (BGP) determines how data packets travel across the internet; a BGP misconfiguration can accidentally route entire countries' traffic.",
      },
      {
        id: "net_600_03",
        categoryId: "technology",
        tier: 600,
        prompt: "What decentralized file-sharing protocol, created by Bram Cohen in 2001, splits files into pieces distributed across many peers?",
        answer: "BitTorrent",
        acceptableAnswers: ["BitTorrent", "Bittorrent"],
        explanation: "BitTorrent's peer-to-peer design means download speed often increases with more users, the opposite of traditional client-server downloads.",
      },
    ],
  },
  {
    topicId: "consumer_tech",
    displayName: "Consumer Tech",
    parentCategoryId: "technology",
    questions: [
      {
        id: "ctech_200_01",
        categoryId: "technology",
        tier: 200,
        prompt: "What company, founded by Steve Jobs and Steve Wozniak in 1976, makes the iPhone?",
        answer: "Apple",
        acceptableAnswers: ["Apple", "Apple Inc."],
        explanation: "Apple was founded on April 1, 1976, and became one of the most valuable companies in history with the iPhone launch in 2007.",
      },
      {
        id: "ctech_200_02",
        categoryId: "technology",
        tier: 200,
        prompt: "What video game console, released by Sony in 2013, competed directly with the Xbox One?",
        answer: "PlayStation 4",
        acceptableAnswers: ["PlayStation 4", "PS4"],
        explanation: "The PS4 sold over 117 million units, making it one of the best-selling consoles of all time, outselling the Xbox One throughout its lifecycle.",
      },
      {
        id: "ctech_200_03",
        categoryId: "technology",
        tier: 200,
        prompt: "What streaming service, launched in 2007, began as a DVD mail rental company in 1997?",
        answer: "Netflix",
        acceptableAnswers: ["Netflix"],
        explanation: "Netflix was founded by Reed Hastings and Marc Randolph and pivoted from DVD-by-mail to streaming, launching its first original series 'House of Cards' in 2013.",
      },
      {
        id: "ctech_400_01",
        categoryId: "technology",
        tier: 400,
        prompt: "What wireless communication standard, often called 'near-field communication', allows devices to exchange data by touching or being within a few centimeters?",
        answer: "NFC",
        acceptableAnswers: ["NFC", "Near Field Communication", "Near-field communication"],
        explanation: "NFC is used for contactless payments (Apple Pay, Google Pay), transit cards, and data sharing between phones.",
      },
      {
        id: "ctech_400_02",
        categoryId: "technology",
        tier: 400,
        prompt: "What Intel processor feature, introduced in 2006, allowed a single chip to run two processor cores simultaneously, doubling throughput for multi-threaded tasks?",
        answer: "Dual-core",
        acceptableAnswers: ["Dual-core", "Dual core", "multi-core"],
        explanation: "Intel's Core 2 Duo marked the mainstream shift to dual-core CPUs, enabling better performance without purely increasing clock speed.",
      },
      {
        id: "ctech_400_03",
        categoryId: "technology",
        tier: 400,
        prompt: "What display technology, used in most modern smartphones, emits light per-pixel and produces perfect blacks by turning pixels off entirely?",
        answer: "OLED",
        acceptableAnswers: ["OLED", "AMOLED", "Organic LED"],
        explanation: "OLED (Organic Light-Emitting Diode) screens have higher contrast ratios than LCD because dark pixels are fully off; Apple first used OLED in the iPhone X in 2017.",
      },
      {
        id: "ctech_600_01",
        categoryId: "technology",
        tier: 600,
        prompt: "What 1965 prediction by Gordon Moore — that transistor count on a chip would double roughly every two years — guided semiconductor development for decades?",
        answer: "Moore's Law",
        acceptableAnswers: ["Moore's Law", "Moores Law"],
        explanation: "Moore's Law drove exponential computing improvements for ~50 years; by the 2020s, physical limits of silicon have slowed the pace significantly.",
      },
      {
        id: "ctech_600_02",
        categoryId: "technology",
        tier: 600,
        prompt: "What IBM computer defeated world chess champion Garry Kasparov in a six-game match in 1997?",
        answer: "Deep Blue",
        acceptableAnswers: ["Deep Blue", "IBM Deep Blue"],
        explanation: "Deep Blue evaluated 200 million positions per second. Kasparov had won the 1996 rematch but lost the 1997 six-game series 2.5–3.5.",
      },
      {
        id: "ctech_600_03",
        categoryId: "technology",
        tier: 600,
        prompt: "What storage interface standard, replacing SATA for SSDs, uses PCIe lanes to achieve speeds over 5x faster than traditional SATA SSDs?",
        answer: "NVMe",
        acceptableAnswers: ["NVMe", "NVM Express", "Non-Volatile Memory Express"],
        explanation: "NVMe (Non-Volatile Memory Express) was designed specifically for flash storage, achieving sequential read speeds of 7,000+ MB/s vs SATA's ~550 MB/s cap.",
      },
    ],
  },
];

export default TECHNOLOGY_TOPIC_PACKS_DRAFT;
