import { Question } from "@/types/game";

// Draft-only Video Games question bank.
// Do not import into shipping category data until reviewed and playtested.

const VIDEO_GAMES_DRAFT_QUESTIONS: Question[] = [
  {
    id: "vg_200_01",
    categoryId: "video_games",
    tier: 200,
    prompt: "In Minecraft, what green enemy silently walks toward players and explodes?",
    answer: "Creeper",
    acceptableAnswers: ["A Creeper", "Creeper"],
    explanation: "Creepers are one of Minecraft's most recognizable mobs because they punish players who stop paying attention.",
    source: "Minecraft in-game enemy and official Minecraft materials.",
  },
  {
    id: "vg_200_02",
    categoryId: "video_games",
    tier: 200,
    prompt: "Which Nintendo series follows Link as he repeatedly battles Ganon and protects Hyrule?",
    answer: "The Legend of Zelda",
    acceptableAnswers: ["Zelda", "Legend of Zelda", "The Legend of Zelda"],
    source: "The Legend of Zelda series premise.",
  },
  {
    id: "vg_200_03",
    categoryId: "video_games",
    tier: 200,
    prompt: "In Halo, what is the name of the armored super-soldier known by the service number John-117?",
    answer: "Master Chief",
    acceptableAnswers: ["The Master Chief", "Master Chief", "John-117"],
    source: "Halo: Combat Evolved and official Halo character materials.",
  },
  {
    id: "vg_200_04",
    categoryId: "video_games",
    tier: 200,
    prompt: "Which battle royale game became famous for letting players build walls, ramps, and towers during fights?",
    answer: "Fortnite",
    source: "Fortnite core gameplay.",
  },
  {
    id: "vg_200_05",
    categoryId: "video_games",
    tier: 200,
    prompt: "In Pokemon, what three starter types are traditionally offered at the beginning of a mainline game?",
    answer: "Grass, Fire, and Water",
    acceptableAnswers: ["Fire, Water, Grass", "Grass Fire Water", "Grass, Fire, Water"],
    source: "Pokemon mainline starter pattern.",
  },
  {
    id: "vg_200_06",
    categoryId: "video_games",
    tier: 200,
    prompt: "What puzzle game has players rotate falling tetromino blocks to clear horizontal lines?",
    answer: "Tetris",
    source: "Tetris core gameplay.",
  },
  {
    id: "vg_200_07",
    categoryId: "video_games",
    tier: 200,
    prompt: "In Super Mario games, what green pipes does Mario often use to travel between areas?",
    answer: "Warp Pipes",
    acceptableAnswers: ["Pipes", "Green pipes", "Warp pipe", "Warp Pipes"],
    source: "Super Mario Bros. and later Super Mario games.",
  },
  {
    id: "vg_200_08",
    categoryId: "video_games",
    tier: 200,
    prompt: "Which game series features the assassin Ezio Auditore da Firenze?",
    answer: "Assassin's Creed",
    acceptableAnswers: ["Assassins Creed", "Assassin's Creed"],
    source: "Assassin's Creed II character and series.",
  },
  {
    id: "vg_200_09",
    categoryId: "video_games",
    tier: 200,
    prompt: "In The Last of Us, what type of real-world fungus inspires the infection that turns people into monsters?",
    answer: "Cordyceps",
    acceptableAnswers: ["Cordyceps fungus", "Cordyceps"],
    source: "The Last of Us story premise.",
  },
  {
    id: "vg_200_10",
    categoryId: "video_games",
    tier: 200,
    prompt: "Which Sega mascot is a blue hedgehog known for running at extreme speed?",
    answer: "Sonic the Hedgehog",
    acceptableAnswers: ["Sonic", "Sonic the Hedgehog"],
    source: "Sonic the Hedgehog series.",
  },
  {
    id: "vg_400_01",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Portal, what company runs the test chambers where Chell is guided by GLaDOS?",
    answer: "Aperture Science",
    acceptableAnswers: ["Aperture", "Aperture Laboratories", "Aperture Science"],
    explanation: "Aperture Science is the fictional research company behind Portal's test chambers.",
    source: "Portal in-game story and environment text.",
  },
  {
    id: "vg_400_02",
    categoryId: "video_games",
    tier: 400,
    prompt: "In League of Legends, what structure must a team destroy to win the match?",
    answer: "The Nexus",
    acceptableAnswers: ["Nexus", "The Nexus"],
    source: "League of Legends core objective.",
  },
  {
    id: "vg_400_03",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Elden Ring, what item does the player use to level up at a Site of Grace?",
    answer: "Runes",
    acceptableAnswers: ["Rune", "Runes"],
    source: "Elden Ring progression system.",
  },
  {
    id: "vg_400_04",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Counter-Strike, what map is famous for the callouts Long A, Catwalk, B Tunnels, and Mid Doors?",
    answer: "Dust II",
    acceptableAnswers: ["Dust 2", "de_dust2", "Dust II"],
    source: "Counter-Strike map de_dust2.",
  },
  {
    id: "vg_400_05",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Skyrim, what shout is made from the words Fus, Ro, and Dah?",
    answer: "Unrelenting Force",
    acceptableAnswers: ["Fus Ro Dah", "Unrelenting Force"],
    source: "The Elder Scrolls V: Skyrim shout system.",
  },
  {
    id: "vg_400_06",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Kingdom Hearts, what weapon shaped like an oversized key is wielded by Sora?",
    answer: "Keyblade",
    acceptableAnswers: ["The Keyblade", "Keyblade"],
    source: "Kingdom Hearts series.",
  },
  {
    id: "vg_400_07",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Overwatch, what support hero says 'Heroes never die' when using her ultimate ability?",
    answer: "Mercy",
    acceptableAnswers: ["Mercy", "Angela Ziegler"],
    source: "Overwatch hero voice line and ultimate.",
  },
  {
    id: "vg_400_08",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Super Smash Bros. Melee, what defensive technique slides a character backward after a perfect shield input?",
    answer: "Wavedash",
    acceptableAnswers: ["Wavedashing", "Wavedash"],
    source: "Super Smash Bros. Melee competitive technique.",
  },
  {
    id: "vg_400_09",
    categoryId: "video_games",
    tier: 400,
    prompt: "In BioShock, what phrase is used to control Jack and reveal the game's central twist?",
    answer: "Would you kindly",
    acceptableAnswers: ["Would you kindly?", "Would you kindly"],
    source: "BioShock story reveal.",
  },
  {
    id: "vg_400_10",
    categoryId: "video_games",
    tier: 400,
    prompt: "In Dark Souls, what bonfire-adjacent item is consumed to restore health from the player's flask?",
    answer: "Estus Flask",
    acceptableAnswers: ["Estus", "Estus Flask"],
    source: "Dark Souls healing system.",
  },
  {
    id: "vg_600_01",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Ocarina of Time speedrunning, what glitch lets Link store an action for later and use it to trigger major sequence breaks?",
    answer: "Bottle Adventure",
    acceptableAnswers: ["Bottle Adventure", "BA"],
    explanation: "Bottle Adventure is a famous Ocarina of Time glitch category tool used to manipulate item and action behavior.",
    source: "Ocarina of Time speedrunning community terminology.",
  },
  {
    id: "vg_600_02",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Halo 2, what skull makes enemies throw grenades much more often and became infamous in Legendary challenge runs?",
    answer: "Catch",
    acceptableAnswers: ["Catch skull", "Catch"],
    source: "Halo 2 skull modifiers.",
  },
  {
    id: "vg_600_03",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Dark Souls, which hidden boss is found behind an illusory wall in Darkroot Garden after entering the Artorias of the Abyss route?",
    answer: "Great Grey Wolf Sif",
    acceptableAnswers: ["Sif", "Great Grey Wolf Sif"],
    source: "Dark Souls boss and Darkroot Garden location.",
  },
  {
    id: "vg_600_04",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Metal Gear Solid 3, what boss can be defeated early by shooting him at the Ponizovje warehouse docks before his sniper duel?",
    answer: "The End",
    acceptableAnswers: ["The End"],
    explanation: "The End is famous for several unusual solutions, including defeating him before the expected boss fight.",
    source: "Metal Gear Solid 3 gameplay sequence.",
  },
  {
    id: "vg_600_05",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Pokemon Red and Blue, what glitch Pokemon is famously encountered by manipulating the old man tutorial and Cinnabar Island coast?",
    answer: "MissingNo.",
    acceptableAnswers: ["MissingNo", "MissingNo.", "Missing Number"],
    source: "Pokemon Red/Blue MissingNo. glitch.",
  },
  {
    id: "vg_600_06",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Final Fantasy VII, what optional boss located in the desert around Gold Saucer is known for its huge health pool and Aire Tam Storm attack?",
    answer: "Ruby Weapon",
    acceptableAnswers: ["Ruby", "Ruby Weapon"],
    source: "Final Fantasy VII optional superboss.",
  },
  {
    id: "vg_600_07",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Celeste, what advanced movement technique combines a dash and jump to launch Madeline farther and faster, becoming central to high-level play?",
    answer: "Wave dash",
    acceptableAnswers: ["Wavedash", "Wave dash", "Wavedashing"],
    source: "Celeste advanced movement mechanics.",
  },
  {
    id: "vg_600_08",
    categoryId: "video_games",
    tier: 600,
    prompt: "In The Binding of Isaac, what item rerolls the current room's pedestal items and became one of the game's most iconic run-defining pickups?",
    answer: "The D6",
    acceptableAnswers: ["D6", "The D6"],
    source: "The Binding of Isaac item behavior.",
  },
  {
    id: "vg_600_09",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Hollow Knight, what dream boss version of the False Knight is fought after using the Dream Nail on his corpse?",
    answer: "Failed Champion",
    acceptableAnswers: ["The Failed Champion", "Failed Champion"],
    source: "Hollow Knight dream boss encounters.",
  },
  {
    id: "vg_600_10",
    categoryId: "video_games",
    tier: 600,
    prompt: "In Undertale's Genocide Route, what boss fight uses the song 'Megalovania' and is built around dodging bone and Gaster Blaster attacks?",
    answer: "Sans",
    acceptableAnswers: ["Sans"],
    source: "Undertale Genocide Route boss fight.",
  },
];

export default VIDEO_GAMES_DRAFT_QUESTIONS;
