import { Question } from "@/types/game";

// Draft-only internal topic packs for the generic "Video Games" category.
// These are NOT top-level app categories. Keep category tiles generic for v1.
// Do not import this file into shipping category data until reviewed/playtested.

export interface VideoGameTopicPack {
  topicId: string;
  displayName: string;
  parentCategoryId: "video_games";
  questions: Question[];
}

const VIDEO_GAME_TOPIC_PACKS_DRAFT: VideoGameTopicPack[] = [
  {
    topicId: "call_of_duty",
    displayName: "Call of Duty",
    parentCategoryId: "video_games",
    questions: [
      {
        id: "cod_200_01",
        categoryId: "video_games",
        tier: 200,
        prompt: "In Call of Duty Zombies, what machine is famous for upgrading a weapon's firepower?",
        answer: "Pack-a-Punch",
        acceptableAnswers: ["Pack-a-Punch", "Pack a Punch", "Pack-a-Punch Machine"],
        source: "https://www.callofduty.com/guides/zombies/call-of-duty-guide-modern-warfare-zombies-tactics",
      },
      {
        id: "cod_200_02",
        categoryId: "video_games",
        tier: 200,
        prompt: "Which Call of Duty subseries centers on operators like Captain Price, Soap, Ghost, and Gaz?",
        answer: "Modern Warfare",
        acceptableAnswers: ["Call of Duty: Modern Warfare", "Modern Warfare"],
        source: "https://www.callofduty.com/modernwarfare2/home",
      },
      {
        id: "cod_400_01",
        categoryId: "video_games",
        tier: 400,
        prompt: "Which studio introduced Zombies in Call of Duty: World at War before it became a major part of the series?",
        answer: "Treyarch",
        source: "https://www.callofduty.com/uk/en/blog/archives/call-of-duty-black-ops-4-zombies-details",
      },
      {
        id: "cod_400_02",
        categoryId: "video_games",
        tier: 400,
        prompt: "In Modern Warfare Zombies, what currency is spent to Pack-a-Punch a weapon?",
        answer: "Essence",
        acceptableAnswers: ["Essence"],
        source: "https://www.callofduty.com/guides/zombies/call-of-duty-guide-modern-warfare-zombies-tactics",
      },
      {
        id: "cod_600_01",
        categoryId: "video_games",
        tier: 600,
        prompt: "What was the first Zombies map, unlocked after the World at War campaign and set in a ruined bunker?",
        answer: "Nacht der Untoten",
        acceptableAnswers: ["Nacht der Untoten", "Nacht"],
        explanation: "This is the original seed of Treyarch Zombies before the mode became a full franchise pillar.",
        source: "Call of Duty: World at War Zombies mode; verify against in-game map list before shipping.",
      },
      {
        id: "cod_600_02",
        categoryId: "video_games",
        tier: 600,
        prompt: "In classic Zombies, what four-character crew includes Richtofen, Dempsey, Takeo, and Nikolai?",
        answer: "Primis",
        acceptableAnswers: ["Primis", "Ultimis"],
        explanation: "Host note: accept either Primis or Ultimis depending on the specific storyline wording players argue from; this needs fan review.",
        source: "Call of Duty Zombies Aether storyline; needs fan verification before shipping.",
      },
    ],
  },
  {
    topicId: "valorant",
    displayName: "VALORANT",
    parentCategoryId: "video_games",
    questions: [
      {
        id: "val_200_01",
        categoryId: "video_games",
        tier: 200,
        prompt: "In VALORANT, what object do attackers plant and defenders try to defuse?",
        answer: "The Spike",
        acceptableAnswers: ["Spike", "The Spike"],
        source: "VALORANT core game mode; verify against official beginner materials before shipping.",
      },
      {
        id: "val_200_02",
        categoryId: "video_games",
        tier: 200,
        prompt: "Which VALORANT agent from South Korea is known for quick movement and knife highlights?",
        answer: "Jett",
        acceptableAnswers: ["Jett"],
        source: "https://playvalorant.com/en-us/agents/jett/",
      },
      {
        id: "val_400_01",
        categoryId: "video_games",
        tier: 400,
        prompt: "On VALORANT's map Bind, what unique feature lets players rotate using one-way shortcuts?",
        answer: "Teleporters",
        acceptableAnswers: ["Teleporters", "One-way teleporters", "TPs"],
        source: "https://playvalorant.com/en-gb/maps/",
      },
      {
        id: "val_400_02",
        categoryId: "video_games",
        tier: 400,
        prompt: "What is Killjoy's VALORANT role?",
        answer: "Sentinel",
        acceptableAnswers: ["Sentinel"],
        source: "https://playvalorant.com/en-us/agents/killjoy",
      },
      {
        id: "val_600_01",
        categoryId: "video_games",
        tier: 600,
        prompt: "In VALORANT patch 4.08, which Jett ability was changed so she had to activate a short dash window before actually dashing?",
        answer: "Tailwind",
        acceptableAnswers: ["Tailwind", "Dash"],
        explanation: "This is a real-fan/pro-play balance memory question, not a basic agent kit question.",
        source: "https://playvalorant.com/en-us/news/game-updates/valorant-jett-changes-for-patch-4-08/",
      },
      {
        id: "val_600_02",
        categoryId: "video_games",
        tier: 600,
        prompt: "In VALORANT patch 1.09, which sniper rifle had its price raised from 4500 to 5000 credits?",
        answer: "Operator",
        acceptableAnswers: ["The Operator", "Op", "Operator"],
        source: "https://playvalorant.com/en-us/news/game-updates/valorant-patch-notes-1-09/",
      },
    ],
  },
  {
    topicId: "minecraft",
    displayName: "Minecraft",
    parentCategoryId: "video_games",
    questions: [
      {
        id: "mc_200_01",
        categoryId: "video_games",
        tier: 200,
        prompt: "In Minecraft, what block must players mine to get diamonds?",
        answer: "Diamond Ore",
        acceptableAnswers: ["Diamond ore", "Deepslate diamond ore"],
        source: "Minecraft in-game block progression; verify against Minecraft materials before shipping.",
      },
      {
        id: "mc_200_02",
        categoryId: "video_games",
        tier: 200,
        prompt: "What hostile Minecraft mob explodes after silently walking close to the player?",
        answer: "Creeper",
        acceptableAnswers: ["Creeper", "A Creeper"],
        source: "Minecraft in-game mob behavior.",
      },
      {
        id: "mc_400_01",
        categoryId: "video_games",
        tier: 400,
        prompt: "What Nether structure is made largely from blackstone and basalt, full of piglins, and does not spawn in basalt deltas?",
        answer: "Bastion Remnant",
        acceptableAnswers: ["Bastion", "Bastion Remnant", "Bastion remnants"],
        source: "https://www.minecraft.net/fr-fr/article/bastion-remnant",
      },
      {
        id: "mc_400_02",
        categoryId: "video_games",
        tier: 400,
        prompt: "What ore-like block smelts into netherite scrap and is famous for floating in lava?",
        answer: "Ancient Debris",
        acceptableAnswers: ["Ancient Debris"],
        source: "https://www.minecraft.net/ko-kr/article/taking-inventory--netherite-scrap",
      },
      {
        id: "mc_600_01",
        categoryId: "video_games",
        tier: 600,
        prompt: "In Minecraft speedrunning, what barter item from piglins is prized because it helps players find strongholds?",
        answer: "Ender Pearls",
        acceptableAnswers: ["Ender Pearls", "Pearls"],
        source: "Minecraft speedrunning community strategy; verify against speedrun route notes before shipping.",
      },
      {
        id: "mc_600_02",
        categoryId: "video_games",
        tier: 600,
        prompt: "What block do players use with a bed in the Nether or End to intentionally create an explosion for boss or mining strategies?",
        answer: "Bed",
        acceptableAnswers: ["Beds", "A bed", "Bed"],
        explanation: "Beds explode when used outside the Overworld, which advanced players use intentionally.",
        source: "Minecraft in-game bed behavior; verify against current official wiki/materials before shipping.",
      },
    ],
  },
  {
    topicId: "fortnite",
    displayName: "Fortnite",
    parentCategoryId: "video_games",
    questions: [
      {
        id: "fn_200_01",
        categoryId: "video_games",
        tier: 200,
        prompt: "What phrase describes winning a Fortnite Battle Royale match?",
        answer: "Victory Royale",
        acceptableAnswers: ["Victory Royale"],
        source: "Fortnite Battle Royale win screen terminology.",
      },
      {
        id: "fn_200_02",
        categoryId: "video_games",
        tier: 200,
        prompt: "What flying vehicle do Fortnite players jump from at the start of a Battle Royale match?",
        answer: "Battle Bus",
        acceptableAnswers: ["The Battle Bus", "Battle Bus"],
        source: "Fortnite Battle Royale match start.",
      },
      {
        id: "fn_400_01",
        categoryId: "video_games",
        tier: 400,
        prompt: "What Fortnite setting lets players hold the build input to continuously place structures?",
        answer: "Turbo Building",
        acceptableAnswers: ["Turbo Build", "Turbo Building"],
        source: "https://www.fortnite.com/news/building-improvements?lang=en-US",
      },
      {
        id: "fn_400_02",
        categoryId: "video_games",
        tier: 400,
        prompt: "What no-build Fortnite mode gives every player a rechargeable Overshield as a first layer of defense?",
        answer: "Zero Build",
        acceptableAnswers: ["Fortnite Zero Build", "Zero Build"],
        source: "https://www.fortnite.com/news/fortnite-zero-build-take-the-offensive-in-this-no-build-battle-royale?lang=pt-BR",
      },
      {
        id: "fn_600_01",
        categoryId: "video_games",
        tier: 600,
        prompt: "In Fortnite build fights, what player-made upward structure is usually targeted at its base so the whole climb collapses?",
        answer: "Sky ramp",
        acceptableAnswers: ["Sky ramp", "Ramp", "Build ramp"],
        explanation: "Fortnite's own build notes describe unsupported sky ramps falling if their terrain or floor connection is destroyed.",
        source: "https://www.fortnite.com/news/building-improvements?lang=en-US",
      },
      {
        id: "fn_600_02",
        categoryId: "video_games",
        tier: 600,
        prompt: "What Fortnite Creative event asked players to rebuild Tilted Towers by submitting block designs for community voting?",
        answer: "The Block 2.0",
        acceptableAnswers: ["The Block 2.0", "Block 2.0"],
        source: "https://www.fortnite.com/news/theblock2-0",
      },
    ],
  },
  {
    topicId: "league_of_legends",
    displayName: "League of Legends",
    parentCategoryId: "video_games",
    questions: [
      {
        id: "lol_200_01",
        categoryId: "video_games",
        tier: 200,
        prompt: "In League of Legends, what structure must a team destroy to win a standard match?",
        answer: "Nexus",
        acceptableAnswers: ["The Nexus", "Nexus"],
        source: "https://wiki.leagueoflegends.com/en-us/Nexus",
      },
      {
        id: "lol_200_02",
        categoryId: "video_games",
        tier: 200,
        prompt: "What is the main 5v5 map in League of Legends called?",
        answer: "Summoner's Rift",
        acceptableAnswers: ["Summoners Rift", "Summoner's Rift"],
        source: "https://wiki.leagueoflegends.com/en-us/League_of_Legends",
      },
      {
        id: "lol_400_01",
        categoryId: "video_games",
        tier: 400,
        prompt: "What two base structures sit before each Nexus and must usually be destroyed before finishing the game?",
        answer: "Nexus turrets",
        acceptableAnswers: ["Nexus turrets", "Turrets", "The two Nexus turrets"],
        source: "https://wiki.leagueoflegends.com/en-us/Nexus",
      },
      {
        id: "lol_400_02",
        categoryId: "video_games",
        tier: 400,
        prompt: "Which neutral monster is fought in the pit near top side river and is famous for the purple team-wide buff?",
        answer: "Baron Nashor",
        acceptableAnswers: ["Baron", "Baron Nashor"],
        source: "League of Legends Summoner's Rift gameplay; verify against Riot beginner/game guide before shipping.",
      },
      {
        id: "lol_600_01",
        categoryId: "video_games",
        tier: 600,
        prompt: "According to League trivia, what odd plural form does the client use for multiple Nexus structures?",
        answer: "Nexai",
        acceptableAnswers: ["Nexai"],
        source: "https://wiki.leagueoflegends.com/en-us/Nexus",
      },
      {
        id: "lol_600_02",
        categoryId: "video_games",
        tier: 600,
        prompt: "What invulnerable fountain defense is colloquially called the Fountain Laser?",
        answer: "Nexus Obelisk",
        acceptableAnswers: ["Nexus Obelisk", "Fountain Laser"],
        source: "https://wiki.leagueoflegends.com/en-us/Nexus_Obelisk",
      },
    ],
  },
  {
    topicId: "pokemon",
    displayName: "Pokemon",
    parentCategoryId: "video_games",
    questions: [
      {
        id: "pkm_200_01",
        categoryId: "video_games",
        tier: 200,
        prompt: "In most mainline Pokemon games, what do fans call the first Pokemon you choose at the beginning of your journey?",
        answer: "Starter Pokemon",
        acceptableAnswers: ["Starter", "Starter Pokemon", "First partner Pokemon"],
        source: "https://www.pokemon.com/us/pokemon-tcg/product-gallery/first-partner-illustration-collection-series-2",
      },
      {
        id: "pkm_200_02",
        categoryId: "video_games",
        tier: 200,
        prompt: "Which three Pokemon are the first partners in Pokemon Scarlet and Violet?",
        answer: "Sprigatito, Fuecoco, and Quaxly",
        acceptableAnswers: ["Sprigatito Fuecoco Quaxly", "Sprigatito, Fuecoco, Quaxly"],
        source: "https://www.pokemon.com/uk/pokemon-news/reminisce-on-pokemon-scarlet-and-pokemon-violet-with-the-pokemon-tcg",
      },
      {
        id: "pkm_400_01",
        categoryId: "video_games",
        tier: 400,
        prompt: "What Paldea battle mechanic gives a Pokemon a crystal-like crown and can change or boost its type strategy?",
        answer: "Terastallization",
        acceptableAnswers: ["Terastallizing", "Terastal phenomenon", "Terastallization"],
        source: "https://press.pokemon.com/en/NEW-DETAILS-REVEALED-FOR-POKEMON-SCARLET-AND-POKEMON-VIOLET-INCLUDING-",
      },
      {
        id: "pkm_400_02",
        categoryId: "video_games",
        tier: 400,
        prompt: "In Pokemon Legends: Arceus, which three first partner Pokemon are offered to the player?",
        answer: "Rowlet, Cyndaquil, and Oshawott",
        acceptableAnswers: ["Rowlet Cyndaquil Oshawott", "Rowlet, Cyndaquil, Oshawott"],
        source: "https://legends.arceus.pokemon.com/en-us/pokemon",
      },
      {
        id: "pkm_600_01",
        categoryId: "video_games",
        tier: 600,
        prompt: "What Pokemon evolves from Gimmighoul after the trainer collects 999 Gimmighoul Coins?",
        answer: "Gholdengo",
        acceptableAnswers: ["Gholdengo"],
        source: "https://press.pokemon.com/en/releases/OVER-ONE-THOUSAND-POKEMON-ACROSS-THE-FRANCHISE-NOW-DISCOVERED",
      },
      {
        id: "pkm_600_02",
        categoryId: "video_games",
        tier: 600,
        prompt: "In Pokemon Red and Blue, what cable accessory did players originally need to trade Pokemon and complete the Pokedex?",
        answer: "Game Link Cable",
        acceptableAnswers: ["Game Link Cable", "Link Cable", "Game Link"],
        source: "https://www.pokemon.com/uk/pokemon-video-games/pokemon-red-version-and-pokemon-blue-version",
      },
    ],
  },
];

export default VIDEO_GAME_TOPIC_PACKS_DRAFT;
